### ISSUE TITLE
Quality of image not the same in API then from Web UI

### ISSUE THREAD

**Issue by jdc4429** [comfyanonymous/ComfyUI#1022]
Hello again,

I found another issue...  For some reason, the quality of the image being generated from the API is much worse then when generated from the Web interface with the same settings.. I can't figure out why.  I believe I am matching all the parameters like denoise is set to 1 for example.

If you see the two images, same prompt but one from api and the other from web interface... I'm stumped.

![ComfyUI_00007_](https://github.com/comfyanonymous/ComfyUI/assets/19594564/0419649d-c384-499b-a9e4-946ef4496de7)
![ComfyUI_00009_](https://github.com/comfyanonymous/ComfyUI/assets/19594564/f605962d-af3a-4deb-88f0-2b5ca7e858cd)

**Comment by comfyanonymous** [comment]
In the UI you can: click the gear button beside "Queue Size" and "enable dev mode options", then you can use the new button to save workflows in api format that you can use in the API.

**Comment by jdc4429** [comment]
Oh cool, I can rule out if it's a setting this way. quite frankly there are so many! :)

Thank you for the quick reponse.  I love your interface.

**Comment by jdc4429** [comment]
I get an error when I try to use the created api workflow...

Traceback (most recent call last):
  File "c:\inetpub\wwwroot\comfy.py", line 276, in <module>
    prompt = json.loads(prompt_text)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 353, in raw_decode
json.decoder.JSONDecodeError: Invalid control character at: line 19 column 401 (char 707)

Does not seem to like the format..  I was sure to paste everything from """ to """

**Comment by jdc4429** [comment]
Does not seem to match the format I had previously.. had numbers for each section.  This one when I look at the save image does not have a '9' for example..

**Comment by jdc4429** [comment]
Here is the workflow that was created...

[workflow_api.txt](https://github.com/comfyanonymous/ComfyUI/files/12208298/workflow_api.txt)

**Comment by jdc4429** [comment]
FYI..   It is one of the lines from 15 up that is causing it to fail...  Up till 12 it's good.

**Comment by jdc4429** [comment]
Also if you could fix it so the API queue's the requests... You can from the web interface but not the API..

**Comment by jdc4429** [comment]
I might have figured out the issue.  It seems my code was putting %20 & %2C codes in the prompt and I believe that may have been messing up it's ability to read the prompt correctly.

**Comment by jdc4429** [comment]
I believe the Lora is not being applied... WowifierXL but it is listed in the api config.

**Comment by ltdrdata** [comment]
> I believe the Lora is not being applied... WowifierXL but it is listed in the api config.

You'd better insert log printer to LoraLoader or others...

**Comment by dotgrid** [comment]
> Also if you could fix it so the API queue's the requests... You can from the web interface but not the API.. 

I've just completed an API integration and can confirm that API requests are indeed queued.

However, like you, I initially encountered issues because the API wasn't accepting my submitted prompt.

I resolved this by adding code to parse my full prompt into a JSON object before submitting it to the API.

Once I verified that my prompt was valid JSON, everything started working as expected! It's a bit tricky, but it's definitely achievable.

**Comment by jdc4429** [comment]
I am using the full json...  

prompt = json.loads(prompt_text)
# Set the text prompt for our positive CLIPTextEncode
prompt["4"]["inputs"]["ckpt_name"] = smodel
prompt["5"]["inputs"]["height"] = iheight
prompt["5"]["inputs"]["width"] = iwidth
prompt["6"]["inputs"]["text"] = rprompt
prompt["7"]["inputs"]["text"] = nprompt
# Seed must always be different
rnumber = random_number()
prompt["3"]["inputs"]["seed"] = rnumber

ws = websocket.WebSocket()
ws.connect("ws://{}/ws?clientId={}".format(server_address, client_id))
images = get_images(ws, prompt)

**Comment by IntenseSunlight** [comment]
Could the quality issues be due to this line?: https://github.com/comfyanonymous/ComfyUI/blob/8c730dc4a7225b2b103497ea1c2f67e48db145ab/server.py#L543C50-L543C50
