### ISSUE TITLE
Gradio error

### ISSUE THREAD

**Issue by augstl** [comfyanonymous/ComfyUI#1031]
When trying to use 4xUltraSharp upscaler, i'm getting the following error: 
```Error occurred when executing UpscaleModelLoader:

No module named 'gradio'

  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "H:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "H:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_upscale_model.py", line 20, in load_model
    sd = comfy.utils.load_torch_file(model_path, safe_load=True)
  File "H:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 20, in load_torch_file
    pl_sd = torch.load(ckpt, map_location=device, pickle_module=comfy.checkpoint_pickle)
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\safe.py", line 106, in load
    return load_with_extra(filename, extra_handler=global_extra_handler, *args, **kwargs)
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\safe.py", line 131, in load_with_extra
    from . import shared
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\shared.py", line 9, in 
    import gradio as gr
```

I'm also getting this warnings/errors when opening Comfy: 
```Warning: Stable Diffusion not found at path H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ldm
Warning: Taming Transformers not found at path H:\ComfyUI_windows_portable\ComfyUI\taming-transformers\taming
Warning: CodeFormer not found at path H:\ComfyUI_windows_portable\ComfyUI\CodeFormer\inference_codeformer.py
Warning: BLIP not found at path H:\ComfyUI_windows_portable\ComfyUI\BLIP\models\blip.py
Warning: k_diffusion not found at path H:\ComfyUI_windows_portable\ComfyUI\k-diffusion\k_diffusion\sampling.py
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1596, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\__init__.py", line 6, in <module>
    from .modules import deepbooru
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\deepbooru.py", line 10, in <module>
    from . import paths, deepbooru_model, devices, shared, images
  File "H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger\modules\shared.py", line 9, in <module>
    import gradio as gr
ModuleNotFoundError: No module named 'gradio'

Cannot import H:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tagger module for custom nodes: No module named 'gradio' 
```

When trying to install requirements via `pip install -r requirements.txt`, I get a message telling me that "requirement already satisfied", including for gradio.

```H:\ComfyUI_windows_portable\ComfyUI>pip install -r requirements.txt
Requirement already satisfied: torch in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: torchsde in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (0.2.5)
Requirement already satisfied: einops in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (0.6.1)
Requirement already satisfied: transformers>=4.25.1 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (4.31.0)
Requirement already satisfied: safetensors>=0.3.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (0.3.1)
Requirement already satisfied: aiohttp in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (3.8.5)
Requirement already satisfied: accelerate in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 7)) (0.21.0)
Requirement already satisfied: pyyaml in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: Pillow in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (10.0.0)
Requirement already satisfied: scipy in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (1.11.1)
Requirement already satisfied: tqdm in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 11)) (4.65.0)
Requirement already satisfied: filelock in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torch->-r requirements.txt (line 1)) (3.12.2)
Requirement already satisfied: typing-extensions in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torch->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: sympy in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torch->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torch->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torch->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: boltons>=20.2.1 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torchsde->-r requirements.txt (line 2)) (23.0.0)
Requirement already satisfied: trampoline>=0.1.2 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torchsde->-r requirements.txt (line 2)) (0.1.2)
Requirement already satisfied: numpy>=1.19.* in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from torchsde->-r requirements.txt (line 2)) (1.25.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from transformers>=4.25.1->-r requirements.txt (line 4)) (0.16.4)
Requirement already satisfied: packaging>=20.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from transformers>=4.25.1->-r requirements.txt (line 4)) (23.1)
Requirement already satisfied: regex!=2019.12.17 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from transformers>=4.25.1->-r requirements.txt (line 4)) (2023.6.3)
Requirement already satisfied: requests in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from transformers>=4.25.1->-r requirements.txt (line 4)) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from transformers>=4.25.1->-r requirements.txt (line 4)) (0.13.3)
Requirement already satisfied: attrs>=17.3.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (3.2.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->-r requirements.txt (line 6)) (1.3.1)
Requirement already satisfied: psutil in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from accelerate->-r requirements.txt (line 7)) (5.9.5)
Requirement already satisfied: colorama in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from tqdm->-r requirements.txt (line 11)) (0.4.6)
Requirement already satisfied: fsspec in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers>=4.25.1->-r requirements.txt (line 4)) (2023.6.0)
Requirement already satisfied: idna>=2.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from yarl<2.0,>=1.0->aiohttp->-r requirements.txt (line 6)) (3.4)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 4)) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers>=4.25.1->-r requirements.txt (line 4)) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in c:\users\augusto\appdata\local\programs\python\python310\lib\site-packages (from sympy->torch->-r requirements.txt (line 1)) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063 
```

While writing this post, I notices how the dependencies are installed in C:/ while I'm running comfy from H:/. Does that make any difference? 
Anyone have experienced this before and/or know how I might be able to solve it?

**Comment by augstl** [comment]
I removed ComfyUI_tagger and it's working again. Thanks a lot. I don't know why, but it was triggering the error when using the upscaler. Thanks again!
