### ISSUE TITLE
Won't let me update

### ISSUE THREAD

**Issue by springheeledjack66** [comfyanonymous/ComfyUI#1054]
not used it in ages, I couldn't get SDXL working reliably in Automatic1111, herd here was greener pastures. I'm trying to update so I can install the custom nodes manager but it won't let me:

D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>..\python_embeded\python.exe .\update.py ..\ComfyUI\
stashing current changes
nothing to stash
creating backup branch: backup_branch_2023-08-01_00_22_30
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 62, in <module>
    pull(repo)
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 16, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\repository.py", line 362, in checkout_tree
    payload.check_error(err)
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\callbacks.py", line 98, in check_error
    check_error(error_code)
  File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\errors.py", line 65, in check_error
    raise GitError(message)
_pygit2.GitError: 20 conflicts prevent checkout

D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>pause
Press any key to continue . . .

please if any one knows how to fix this let me know.

**Comment by pydn** [comment]
I feel like the easy fix would be to just save your models folder in a different location, delete your current comfyui folder, then clone comfyui again. Then copy your models folder to the new comfyui.

**Comment by ltdrdata** [comment]
> not used it in ages, I couldn't get SDXL working reliably in Automatic1111, herd here was greener pastures. I'm trying to update so I can install the custom nodes manager but it won't let me:
> 
> D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>..\python_embeded\python.exe .\update.py ..\ComfyUI\
> stashing current changes
> nothing to stash
> creating backup branch: backup_branch_2023-08-01_00_22_30
> checking out master branch
> pulling latest changes
> Traceback (most recent call last):
>   File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 62, in <module>
>     pull(repo)
>   File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 16, in pull
>     repo.checkout_tree(repo.get(remote_master_id))
>   File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\repository.py", line 362, in checkout_tree
>     payload.check_error(err)
>   File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\callbacks.py", line 98, in check_error
>     check_error(error_code)
>   File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\errors.py", line 65, in check_error
>     raise GitError(message)
> _pygit2.GitError: 20 conflicts prevent checkout
> 
> D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>pause
> Press any key to continue . . .
> 
> 
> please if any one knows how to fix this let me know.

You changed some files mistakenly.
You can check which files are making conflict through.

git status

**Comment by ltdrdata** [comment]
> > > not used it in ages, I couldn't get SDXL working reliably in Automatic1111, herd here was greener pastures. I'm trying to update so I can install the custom nodes manager but it won't let me:
> > > D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>..\python_embeded\python.exe .\update.py ..\ComfyUI
> > > stashing current changes
> > > nothing to stash
> > > creating backup branch: backup_branch_2023-08-01_00_22_30
> > > checking out master branch
> > > pulling latest changes
> > > Traceback (most recent call last):
> > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 62, in
> > > pull(repo)
> > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 16, in pull
> > > repo.checkout_tree(repo.get(remote_master_id))
> > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\repository.py", line 362, in checkout_tree
> > > payload.check_error(err)
> > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\callbacks.py", line 98, in check_error
> > > check_error(error_code)
> > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\errors.py", line 65, in check_error
> > > raise GitError(message)
> > > _pygit2.GitError: 20 conflicts prevent checkout
> > > D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>pause
> > > Press any key to continue . . .
> > > please if any one knows how to fix this let me know.
> > 
> > 
> > You changed some files mistakenly. You can check which files are making conflict through.
> > git status
> > If you used mklink instead of extra-models.yaml for model file sharing. it must be the problem.
> 
> I used the extra-models.yaml, I decided to redownload everything but now I have this issue:
> 
> The custom node DB is currently being updated, and updates to custom nodes are being checked for. NOTE: Update only checks for extensions that have been fetched.
> 
> that message appears when I try to access the extensions in the browser to add new ones

That's not an error message, but rather an informational message. If you've been stuck in that state for a long time, please share the terminal logs.

**Comment by springheeledjack66** [comment]
> > > > not used it in ages, I couldn't get SDXL working reliably in Automatic1111, herd here was greener pastures. I'm trying to update so I can install the custom nodes manager but it won't let me:
> > > > D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>..\python_embeded\python.exe .\update.py ..\ComfyUI
> > > > stashing current changes
> > > > nothing to stash
> > > > creating backup branch: backup_branch_2023-08-01_00_22_30
> > > > checking out master branch
> > > > pulling latest changes
> > > > Traceback (most recent call last):
> > > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 62, in
> > > > pull(repo)
> > > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update\update.py", line 16, in pull
> > > > repo.checkout_tree(repo.get(remote_master_id))
> > > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\repository.py", line 362, in checkout_tree
> > > > payload.check_error(err)
> > > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\callbacks.py", line 98, in check_error
> > > > check_error(error_code)
> > > > File "D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\pygit2\errors.py", line 65, in check_error
> > > > raise GitError(message)
> > > > _pygit2.GitError: 20 conflicts prevent checkout
> > > > D:\Aiimagegeneration\comfyai\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\update>pause
> > > > Press any key to continue . . .
> > > > please if any one knows how to fix this let me know.
> > > 
> > > 
> > > You changed some files mistakenly. You can check which files are making conflict through.
> > > git status
> > > If you used mklink instead of extra-models.yaml for model file sharing. it must be the problem.
> > 
> > 
> > I used the extra-models.yaml, I decided to redownload everything but now I have this issue:
> > The custom node DB is currently being updated, and updates to custom nodes are being checked for. NOTE: Update only checks for extensions that have been fetched.
> > that message appears when I try to access the extensions in the browser to add new ones
> 
> That's not an error message, but rather an informational message. If you've been stuck in that state for a long time, please share the terminal logs.

oh so if I wait it will sort itself out?
