### ISSUE TITLE
Incompatible architecture on M1

### ISSUE THREAD

**Issue by AstemirDev** [comfyanonymous/ComfyUI#1164]
Reinstalled all requirements multiple times, still have this issue:

Traceback (most recent call last):
  File "/Users/astemirkerefov/ComfyUI/main.py", line 66, in <module>
    import comfy.utils
  File "/Users/astemirkerefov/ComfyUI/comfy/utils.py", line 5, in <module>
    import safetensors.torch
  File "/Users/astemirkerefov/miniconda3/lib/python3.11/site-packages/safetensors/__init__.py", line 5, in <module>
    from ._safetensors_rust import SafetensorError, deserialize, safe_open, serialize, serialize_file  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: dlopen(/Users/astemirkerefov/miniconda3/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so, 0x0002): tried: '/Users/astemirkerefov/miniconda3/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/astemirkerefov/miniconda3/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so' (no such file), '/Users/astemirkerefov/miniconda3/lib/python3.11/site-packages/safetensors/_safetensors_rust.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by nate-aeroof** [comment]
I am receiving the same error and I have no idea why

**Comment by nate-aeroof** [comment]
If you find any answer please let me know. This is making me insane, ive been googling for hours trying to find an answer and I just can't figure it out

**Comment by source-code-hub** [comment]
Looks like `safetensors` package is not compatible with python 3.11 yet. Please use python 3.10 and it should work perfectly fine.
You can try installing the package using below command on python 3.10.
`arch -arm64 python -m pip install sentence_transformers --no-cache`

**Comment by nate-aeroof** [comment]
Thank you so much. I managed to isolate the problem, and figured out it was the safetensors being loaded, but could not figure out what it was I needed to install to get the right ones. Is there a particular directory I need to run this command from?
