### ISSUE TITLE
Installed custom nodes and now I can't run comfyui

### ISSUE THREAD

**Issue by johndgriffin1** [comfyanonymous/ComfyUI#1175]
I installed the [comfyui-reactor-node](https://github.com/Gourieff/comfyui-reactor-node) but now I can't run comfuyi.

I removed the module from my custom_modules folder but my comfyui is still broken.

I get the following when trying to run `run_nvidia_gpu.bat`

```
Traceback (most recent call last):
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\image-generation\comfyui\ComfyUI\comfy\model_management.py", line 186, in <module>
    import accelerate
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\accelerate\accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\accelerate\tracking.py", line 43, in <module>
    from torch.utils import tensorboard
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

ERROR: LOW VRAM MODE NEEDS accelerate.
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
Using xformers cross attention
Traceback (most recent call last):
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\compat\__init__.py", line 42, in tf
    from tensorboard.compat import notf  # noqa: F401
ImportError: cannot import name 'notf' from 'tensorboard.compat' (D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\compat\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1099, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\transformers\models\clip\modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\transformers\modeling_utils.py", line 86, in <module>
    from accelerate import dispatch_model, infer_auto_device_map, init_empty_weights
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\accelerate\__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\accelerate\accelerator.py", line 41, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\accelerate\tracking.py", line 43, in <module>
    from torch.utils import tensorboard
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\torch\utils\tensorboard\__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\torch\utils\tensorboard\writer.py", line 16, in <module>
    from ._embedding import (
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\torch\utils\tensorboard\_embedding.py", line 9, in <module>
    _HAS_GFILE_JOIN = hasattr(tf.io.gfile, "join")
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\lazy.py", line 65, in __getattr__
    return getattr(load_once(self), attr_name)
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\lazy.py", line 97, in wrapper
    cache[arg] = f(arg)
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\lazy.py", line 50, in load_once
    module = load_fn()
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorboard\compat\__init__.py", line 45, in tf
    import tensorflow
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\python\eager\context.py", line 29, in <module>
    from tensorflow.core.framework import function_pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\function_pb2.py", line 16, in <module>
    from tensorflow.core.framework import attr_value_pb2 as tensorflow_dot_core_dot_framework_dot_attr__value__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\attr_value_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_pb2.py", line 16, in <module>
    from tensorflow.core.framework import resource_handle_pb2 as tensorflow_dot_core_dot_framework_dot_resource__handle__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\resource_handle_pb2.py", line 16, in <module>
    from tensorflow.core.framework import tensor_shape_pb2 as tensorflow_dot_core_dot_framework_dot_tensor__shape__pb2
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\tensorflow\core\framework\tensor_shape_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\google\protobuf\descriptor.py", line 561, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ai\image-generation\comfyui\ComfyUI\main.py", line 69, in <module>
    import execution
  File "D:\ai\image-generation\comfyui\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "D:\ai\image-generation\comfyui\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "D:\ai\image-generation\comfyui\ComfyUI\comfy\diffusers_load.py", line 6, in <module>
    from comfy.sd import load_checkpoint
  File "D:\ai\image-generation\comfyui\ComfyUI\comfy\sd.py", line 14, in <module>
    from . import clip_vision
  File "D:\ai\image-generation\comfyui\ComfyUI\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, CLIPImageProcessor, modeling_utils
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1090, in __getattr__
    value = getattr(module, name)
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1089, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "D:\ai\image-generation\comfyui\python_embeded\lib\site-packages\transformers\utils\import_utils.py", line 1101, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by johndgriffin1** [comment]
[This](https://github.com/Gourieff/comfyui-reactor-node/issues/5#issuecomment-1674407184) solution worked for me.

**Comment by WDJJJJJ** [comment]
Can you tell me how you solved this problem? I also encountered the same situation.

**Comment by cyanheads** [comment]
@WDJJJJJ

`pip install protobuf==3.20.3 --force-reinstall`
