### ISSUE TITLE
Error during startup process (No module named 'number')

### ISSUE THREAD

**Issue by DreamLoveBetty** [comfyanonymous/ComfyUI#1189]
An error was reported during the startup process (but it does not affect the operation), with the following prompt message (the error message appeared after the last update, and a warning appeared during the update process as shown in the attachment):

Traceback (most recent call last):
  File "D:\Program\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "D:\Program\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

Cannot import D:\Program\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'

Hope to receive help, thank you！

![20230812022709](https://github.com/comfyanonymous/ComfyUI/assets/138059406/3a7aed1b-063a-48e7-9327-936ac520db27)

**Comment by Qudix** [comment]
The error is self explanatory, that custom node pack you installed cannot find the `numba` dependency

**Comment by DreamLoveBetty** [comment]
@Qudix  Thank you!  Yes, I have attempted to install the required dependencies in requirements. txt (numba), but as shown in the attached image, Torchsde has a non-standard dependency specification numpy>=1.19*

**Comment by magictomagic** [comment]
transformers==4.26.1 have confict
