### ISSUE TITLE
SDXL Control-LoRA giving error "Tensor on device cuda:0 is not on the expected device meta!"

### ISSUE THREAD

**Issue by PhoenixCreation** [comfyanonymous/ComfyUI#1269]
I am using comfyUI with [this](https://huggingface.co/stabilityai/control-lora/blob/main/comfy-control-LoRA-workflows/control-lora-depth-basic_example.json) workflow. I have added the models and selected them properly. But When I run, it gives me following error:

`RuntimeError: Tensor on device cuda:0 is not on the expected device meta!`

Full StackTrace:
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1206, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1176, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 93, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 733, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 154, in sample_euler_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 323, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 311, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 289, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 241, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 809, in get_control
    control = self.control_model(x=x_noisy, hint=self.cond_hint, timesteps=t, context=context, y=y)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\cldm\cldm.py", line 307, in forward
    h = self.middle_block(h, emb, context)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 41, in forward
    x = layer(x, emb)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 219, in forward
    return checkpoint(
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py", line 123, in checkpoint
    return func(*inputs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 243, in _forward
    h = self.out_layers(h)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 901, in forward
    return torch.nn.functional.conv2d(input, self.weight + (torch.mm(self.up.flatten(start_dim=1), self.down.flatten(start_dim=1))).reshape(self.weight.shape).type(self.weight.dtype), self.bias, self.stride, self.padding, self.dilation, self.groups)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_prims_common\wrappers.py", line 220, in _fn
    result = fn(*args, **kwargs)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_prims_common\wrappers.py", line 130, in _fn
    result = fn(**bound.arguments)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_refs\__init__.py", line 975, in add
    return prims.add(a, b)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_ops.py", line 287, in __call__
    return self._op(*args, **kwargs or {})
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_prims\__init__.py", line 346, in _elementwise_meta
    utils.check_same_device(*args_, allow_cpu_scalar_tensors=True)
  File "C:\Tools\Comfy\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\_prims_common\__init__.py", line 596, in check_same_device
    raise RuntimeError(msg)
RuntimeError: Tensor on device cuda:0 is not on the expected device meta!
```

I have updated comfyUI to latest version (commit ID: e9469e732d8c84048dcf4c94604607c92e5297df). I have Nvidia 3050ti mobile GPU. I am running comfyUI with "--windows-standalone-build --lowvram" options. I am using the sdxl_base_1.0 model itself(same as workflow file)

If I remove the controlnet nodes from the workflow then it is generating images without any issues. Also I have replicated same on colab and it is not giving error there. Only difference is that in collab it runs with highvram mode and I am running locally with lowvram mode.

I tried to use --normalvram mode but it seems that it loads models in lowvram mode even in the noraml vram mode. I am attaching log file for this behavior. Check line no. 8 and 187 for reference.
[comfyui.prev copy.log](https://github.com/comfyanonymous/ComfyUI/files/12387689/comfyui.prev.copy.log)

**Comment by Norias** [comment]
I have same error when generating more than one image with control-lora, on a 3060 mobile 6go.
The first one is ok and then i have this error. 

Everything is ok without the control-lora.

**Comment by jbluew** [comment]
I've noticed that switching from the rank 256 models to the 128 models fixed the same issue for me.

**Comment by PhoenixCreation** [comment]
I looked into this issue and it is caused because of model being in thr different device(as suggested by the error itself). 

When I run this, my sdxl_base gets loaded to CPU(known as meta in error), then it loads controlnet model. Now here my RAM is almost full so the ComfyUI tries to load it in the GPU(cuda:0 in the error message) and since controlnet models are relatively small, they can easily be loaded to 4gb VRAM. So now my sdxl_base is in CPU and controlnet is in GPU. 

This is the reason why error message says ''(controlnet) model is on cuda:0(GPU), but it is expected to be on the meta(CPU)''

**Comment by comfyanonymous** [comment]
Should be fixed with: https://github.com/comfyanonymous/ComfyUI/commit/199d73364a58caa64668d5bcfc144a2c10899424

**Comment by PhoenixCreation** [comment]
> Should be fixed with: [199d733](https://github.com/comfyanonymous/ComfyUI/commit/199d73364a58caa64668d5bcfc144a2c10899424)

Hi @comfyanonymous,  I am at work and would not be able to verify this. I will let you know as soon as I can. Meanwhile if someone can verify this then kindly close this issue.

Thanks for awesome work.

**Comment by Norias** [comment]
It's ok now, thank you very much for that and for all your work !

**Comment by PhoenixCreation** [comment]
hi @comfyanonymous @jbluew It is fixed now. I am able to generate images with controlnet now. 

Thanks again for awesome work. Closing this issue.
