### ISSUE TITLE
Error when updating python dependencies

### ISSUE THREAD

**Issue by Davikar** [comfyanonymous/ComfyUI#1309]
Getting the following error when running the bat file for updating comfy and python depenencies:

```
Collecting safetensors>=0.3.0 (from -r ../ComfyUI/requirements.txt (line 5))
  Using cached safetensors-0.3.3.tar.gz (35 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      Traceback (most recent call last):
        File "C:\AI\ComfyUI\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\AI\ComfyUI\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\AI\ComfyUI\python_embeded\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\AI\ComfyUI\python_embeded\lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 4, in <module>
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.
```

Windows 11, Latest comfyui build as of now, Python 3.10.11.

**Comment by Davikar** [comment]
Win64 wheels have been uploaded and safetensors is installing correctly now.

**Comment by Pham3n** [comment]
I am getting the same error
