### ISSUE TITLE
module 'cv2' has no attribute 'resize'

### ISSUE THREAD

**Issue by ffdown** [comfyanonymous/ComfyUI#1351]
When trying to run SDXL with any of the new ControlNet models

!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\canny.py", line 23, in execute
    return (common_annotator_call(CannyDetector(), image, low_threshold=low_threshold, high_threshold=high_threshold), )
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 28, in common_annotator_call
    np_result = model(np_image, output_type="np", **kwargs)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\canny\__init__.py", line 23, in __call__
    input_image = resize_image(input_image, detect_resolution)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\util.py", line 98, in resize_image
    img = cv2.resize(input_image, (W, H), interpolation=cv2.INTER_LANCZOS4 if k > 1 else cv2.INTER_AREA)
AttributeError: module 'cv2' has no attribute 'resize'

**Comment by ltdrdata** [comment]
> 

This issue should be reported here
https://github.com/Fannovel16/comfyui_controlnet_aux/issues

**Comment by Suzie1** [comment]
You could check your cv2 version. You may have an old one. I updated mine and the cv2 errors went away.

**Comment by kronkinatorix** [comment]
I needed to download opencv-python-headless==4..8.0.74 and opencv-python==4.8.0.74, deleting any other references to poencv from the other files, restarting. 

I think maybe that a whole bunch of different nodes downloading opencv-python versions and packages maybe isn't the best idea.
