### ISSUE TITLE
SDXL Refiner Broken after Update 1369 [968078b1]

### ISSUE THREAD

**Issue by elphamale** [comfyanonymous/ComfyUI#1366]
After installing an update any workflow that involves SDXL Refiners fails with following exception.

I have 3060 with 12gb VRAM. And it seems ComfyUI somehow thinks there's a need for 38 gbs to load refiner.

> !!! Exception during processing !!!
> Traceback (most recent call last):
>   File "C:\StableDiffusion\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 106, in efficientloader
>     model, clip, vae = load_checkpoint(ckpt_name, my_unique_id, cache=ckpt_cache, cache_overwrite=True)
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\efficiency-nodes-comfyui\tsc_utils.py", line 181, in load_checkpoint
>     out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae, output_clip=True,
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\sd.py", line 421, in load_checkpoint_guess_config
>     model = model_config.get_model(sd, "model.diffusion_model.", device=inital_load_device)
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\supported_models.py", line 113, in get_model
>     return model_base.SDXLRefiner(self, device=device)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\model_base.py", line 164, in __init__
>     super().__init__(model_config, model_type, device=device)
>   File "C:\StableDiffusion\ComfyUI\comfy\model_base.py", line 23, in __init__
>     self.diffusion_model = UNetModel(**unet_config, device=device)
>                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 559, in __init__
>     SpatialTransformer(
>   File "C:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py", line 669, in __init__
>     [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim[d],
>   File "C:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py", line 669, in <listcomp>
>     [BasicTransformerBlock(inner_dim, n_heads, d_head, dropout=dropout, context_dim=context_dim[d],
>      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py", line 517, in __init__
>     self.ff = FeedForward(dim, dropout=dropout, glu=gated_ff, dtype=dtype, device=device, operations=operations)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py", line 73, in __init__
>     ) if not glu else GEGLU(dim, inner_dim, dtype=dtype, device=device, operations=operations)
>                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\ldm\modules\attention.py", line 58, in __init__
>     self.proj = operations.Linear(dim_in, dim_out * 2, dtype=dtype, device=device)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\ops.py", line 11, in __init__
>     self.weight = torch.nn.Parameter(torch.empty((out_features, in_features), **factory_kwargs))
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 37748736 bytes.

**Comment by elphamale** [comment]
> it's trying to allocate 38MB, make sure you have enough ram and have a page file enabled because the nvidia drivers for windows don't work well without it enabled.

Wait, so its RAM not VRAM?

**Comment by elphamale** [comment]
It was indeed RAM - not VRAM. I increased pagefile size and it solved it.
