### ISSUE TITLE
RAM Allocation Problems after Update 1369 [968078b1]

### ISSUE THREAD

**Issue by elphamale** [comfyanonymous/ComfyUI#1368]
This update brought a lot of "DefaultCPUAllocator: not enough memory: you tried to allocate 37748736 bytes." errors. Most of the workflows became unusable. 
I have 16 Gb RAM and tried increasing pagefile - it helped to an extent but still any workflow that involves scarcely more than SDXL+refiner became unusable.

If there's a workaround PST.

**Comment by comfyanonymous** [comment]
If you look at the memory usage in task manager what does the graph look like?

**Comment by elphamale** [comment]
> If you look at the memory usage in task manager what does the graph look like?

The graph looks like 85-95 percent RAM in use and 50% VRAM in use most of the workflow. On the moment of error it was 93%

> !!! Exception during processing !!!
> Traceback (most recent call last):
>   File "C:\StableDiffusion\ComfyUI\execution.py", line 151, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\execution.py", line 81, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\execution.py", line 74, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\nodes.py", line 124, in upscale
>     processed = script.run(p=sdprocessing, _=None, tile_width=tile_width, tile_height=tile_height,
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 553, in run
>     upscaler.process()
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 136, in process
>     self.image = self.redraw.start(self.p, self.image, self.rows, self.cols)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 243, in start
>     return self.linear_process(p, image, rows, cols)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\repositories\ultimate_sd_upscale\scripts\ultimate-upscale.py", line 178, in linear_process
>     processed = processing.process_images(p)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale\modules\processing.py", line 116, in process_images
>     (latent,) = vae_encoder.encode(p.vae, batched_tiles)
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\nodes.py", line 279, in encode
>     t = vae.encode(pixels[:,:,:,:3])
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\ComfyUI\comfy\sd.py", line 222, in encode
>     model_management.free_memory(memory_used, self.device)
>   File "C:\StableDiffusion\ComfyUI\comfy\model_management.py", line 323, in free_memory
>     m.model_unload()
>   File "C:\StableDiffusion\ComfyUI\comfy\model_management.py", line 294, in model_unload
>     self.model.unpatch_model(self.model.offload_device)
>   File "C:\StableDiffusion\ComfyUI\comfy\model_patcher.py", line 269, in unpatch_model
>     self.model.to(device_to)
>   File "C:\StableDiffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1145, in to
>     return self._apply(convert)
>            ^^^^^^^^^^^^^^^^^^^^
>   File "C:\StableDiffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
>     module._apply(fn)
>   File "C:\StableDiffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
>     module._apply(fn)
>   File "C:\StableDiffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
>     module._apply(fn)
>   [Previous line repeated 7 more times]
>   File "C:\StableDiffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
>     param_applied = fn(param)
>                     ^^^^^^^^^
>   File "C:\StableDiffusion\venv\Lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
>     return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> RuntimeError: [enforce fail at ..\c10\core\impl\alloc_cpu.cpp:72] data. DefaultCPUAllocator: not enough memory: you tried to allocate 37748736 bytes.
> 
> Prompt executed in 142.45 seconds

**Comment by NeedsMoar** [comment]
Also FYI I just looked through the source of that custom upscale node;  I've tried to use it before.  It OOM'd on the GPU side with an SD1.5 model attempting an x2 upscale to 1920x1080 when tiling was turned on almost instantly.  It creates at least 2x the latent space of the final size + >=2x the image space of the final size along with a tensor of the final size as an intermediate for each tile on CPU so it'll chew system memory pretty fast as well.  To make that a little worse, it overrides the torch garbage collector class with an empty function with a pass statement which likely makes everything stick around until the node doesn't exist.

**Comment by bash-j** [comment]
I was looking into RAM usage last night. I tried creating a custom node to free up RAM, but I just couldn't get it to work.
When a model is unloaded, it's moved to RAM. I couldn't find a way to remove it from memory completely without causing other issues. If I tried deleting the model, the next time I ran the workflow it would have an error like None doesn't have... which didn't seem to make sense since current_loaded_models starts off as an empty list, so why does it expect it to be populated on the 2nd batch.
