### ISSUE TITLE
Starting ComfyUI results in an OSError while loading "caffe2_nvrtc.dll"

### ISSUE THREAD

**Issue by VladislavKorecky** [comfyanonymous/ComfyUI#1373]
I recently installed ComfyUI on my Windows machine and received the following error when trying to run the CPU or GPU bat file:
```
D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\main.py", line 66, in <module>
    import comfy.utils
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\__init__.py", line 133, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```

After not seeing any helpful advice on the internet, I decided to update ComfyUI by running `update\update_comfyui_and_python_dependencies.bat`. That didn´t help either.

I also tried searching the error partially by only entering the phrase: _"OSError: [WinError 126] The specified module could not be found."_ By doing this, I found a StackOverflow answer that might be relevant to my issue: https://stackoverflow.com/a/61877084

**Comment by starkgate** [comment]
I also had this issue when running `main.py` on Windows 11 with an AMD GPU. In case anyone runs into this, for me the solution was to install the HIP SDK and setup the corresponding environment variables as explained [here](https://github.com/patientx/ComfyUI-Zluda?tab=readme-ov-file#dependencies) (I used version 6.2 of the SDK):

> Install HIP SDK 5.7.1 from [HERE](https://www.amd.com/en/developer/resources/rocm-hub/hip-sdk.html) the correct version, "Windows 10 & 11 5.7.1 HIP SDK"
> 
> *** (*** this app installs zluda for 5.7.1 by default, if you want to use 6.1 or 6.2 you have to get the latest zluda link from [lshyqqtiger's ZLUDA Fork](https://github.com/lshqqytiger/ZLUDA/releases) then you can use patchzluda2.bat, run it paste the link via right click (a correct link would be like this, https://github.com/lshqqytiger/ZLUDA/releases/download/rel.d60bddbc870827566b3d2d417e00e1d2d8acc026/ZLUDA-windows-rocm6-amd64.zip press enter and it would patch that zluda into comfy for you. Of course this also would mean you have to change the variables below from "5.7" to "6.x" where needed) ***
> 
> Add the system variable HIP_PATH, value: C:\\Program Files\\AMD\\ROCm\\5.7\\ (This is the default folder, if you have installed it on another drive, change if necessary)
> 
>     Check the variables on the lower part (System Variables), there should be a variable called: HIP_PATH.
>     Also check the variables on the lower part (System Variables), there should be a variable called: "Path". Double-click it and click "New" add this: C:\Program Files\AMD\ROCm\5.7\bin
