### ISSUE TITLE
module 'comfy.sd' has no attribute 'ModelPatcher'

### ISSUE THREAD

**Issue by TheMindExpansionNetwork** [comfyanonymous/ComfyUI#1426]
Full traceback is:

!!! Exception during processing !!!
Traceback (most recent call last):
  File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 577, in load_controlnet
    controlnet = comfy.controlnet.load_controlnet(controlnet_path)
  File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\comfy\controlnet.py", line 394, in load_controlnet
    control = ControlNet(control_model, global_average_pooling=global_average_pooling)
  File "K:\AI ART UNIVERSE\COMFY-UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIT\AITemplate\AITemplate.py", line 347, in __init__
    self.control_model_wrapped = comfy.sd.ModelPatcher(self.control_model, load_device=comfy.model_management.get_torch_device(), offload_device=comfy.model_management.unet_offload_device())
AttributeError: module 'comfy.sd' has no attribute 'ModelPatcher'

Prompt executed in 2.83 seconds

I am not sure what is going on I updated my AIT to get rid of an error and get this one

Does anyone know how I could resolve it

**Comment by M1kep** [comment]
This should probably be an issue in the AIT node repo. Hopefully it's just a one line change.
This is the commit that changed the location: https://github.com/comfyanonymous/ComfyUI/commit/f92074b84f44af6127e8f4ed1245d6c04dc0b750

Seems to only be used at the below line, so in theory just needs to point to the new `comfy.model_patcher.ModelPatcher`:
https://github.com/FizzleDorf/AIT/blob/10f7510d27bff53dfea4679957b20b8b091983f1/AITemplate/AITemplate.py#L347

**Comment by mcmonkey4eva** [comment]
Yes please redirect to the relevant AIT repo
