### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by gemyerst** [comfyanonymous/ComfyUI#1484]
Hi there, I started getting errors after running comfyui with the efficiency Ksampler node a few times. I have now uninstalled it, but I am still getting the same errors when using the regular Ksampler, not sure if this is to do with efficiency nodes or not. I have also updated comfyui and restarted both my PC and comfyui.

I have included an image of the errors below as it is too many characters to paste here.
![image](https://github.com/comfyanonymous/ComfyUI/assets/30367707/0cf4e080-a6af-4f83-8554-36b4a449422a)
Thanks!

**Comment by zhulinyv** [comment]
I have the same problem, and I found a same issue which was closed https://github.com/comfyanonymous/ComfyUI/issues/906, then I updated my comfyui, but I still have this problem.
![image](https://github.com/comfyanonymous/ComfyUI/assets/66541860/dd8f63e8-7815-4f5d-9d73-d0db076f4ef6)


System: Windows11
Python: 3.10.10
ComfyUI: 213976f

**Comment by zhulinyv** [comment]
> I have the same problem, and I found a same issue which was closed #906, then I updated my comfyui, but I still have this problem. ![image](https://user-images.githubusercontent.com/66541860/271764804-dd8f63e8-7815-4f5d-9d73-d0db076f4ef6.png)
> 
> System: Windows11 Python: 3.10.10 ComfyUI: [213976f](https://github.com/comfyanonymous/ComfyUI/commit/213976f8c3ea3f45f0c692dd8aac2fd9fea433e3)

I know why this problem occured. Maybe it caused by the updata on Windows.
![image](https://github.com/comfyanonymous/ComfyUI/assets/66541860/8eae1585-610e-4b6d-8a03-15e6bc4b6fb4)
After uninstalling this update, comfyui works fine.

**Comment by XYTPZ258500** [comment]
I have the same problem too.

**Comment by kronkinatorix** [comment]
I'm having this problem as well. 

Additionally having another issue with accelerate where generation stops with the error: ou can't move a model that has some modules offloaded to cpu or disk.")

**Comment by satscape** [comment]
I think I'm having the same issue [workflow](https://pastebin.com/1wgA8qcF) This workflow does animateDiff with LCM, it works fine for two runs and then on the third run I get:
`ERROR:root:Traceback (most recent call last):
  File "/home/scott/Various/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 259, in animatediff_sample
    return wrap_function_to_inject_xformers_bug_info(orig_comfy_sample)(model, noise, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_utils.py", line 197, in wrapped_function
    return function_to_wrap(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/comfy/sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/comfy/sample.py", line 86, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory)
  File "/home/scott/Various/ComfyUI/comfy/model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/comfy/model_management.py", line 298, in model_load
    accelerate.dispatch_model(self.real_model, device_map=device_map, main_device=self.device)
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/big_modeling.py", line 371, in dispatch_model
    attach_align_device_hook_on_blocks(
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 536, in attach_align_device_hook_on_blocks
    attach_align_device_hook_on_blocks(
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 509, in attach_align_device_hook_on_blocks
    attach_align_device_hook(
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 405, in attach_align_device_hook
    add_hook_to_module(module, hook, append=True)
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 145, in add_hook_to_module
    remove_hook_from_module(module)
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 186, in remove_hook_from_module
    module._hf_hook.detach_hook(module)
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 114, in detach_hook
    module = hook.detach_hook(module)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/hooks.py", line 313, in detach_hook
    set_module_tensor_to_device(module, name, device, value=self.weights_map.get(name, None))
  File "/home/scott/Various/ComfyUI/lib/python3.11/site-packages/accelerate/utils/modeling.py", line 261, in set_module_tensor_to_device
    if tensor_name not in module._parameters and tensor_name not in module._buffers:
                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute '_parameters
  File "/home/scott/Various/ComfyUI/comfy/model_management.py", line 289, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/scott/Various/ComfyUI/comfy/model_patcher.py", line 188, in patch_model
    self.backup[key] = weight.to(device=self.offload_device, copy=inplace_update)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Cannot copy out of meta tensor; no data!
'`

Linux, 4GB VRAM, Updated ComfyUI & Custom nodes about 4 days ago.

**Comment by McxCZE** [comment]
Same issue here, however, it has to be some kind of a bug, Because I get this error on EncodeClipText.
