### ISSUE TITLE
new install failing

### ISSUE THREAD

**Issue by alenknight** [comfyanonymous/ComfyUI#1564]
had to reinstall comfyui... getting this error - particularly when i try to load ComfyUI-Manager-and the manager button is missing in my GUI 
i've tried loading other nodes... and they are missing too.

```
C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-09-20 11:48:05.405891

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32704 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\AI\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\AI\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\AI\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\AI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\AI\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\AI\stable-diffusion-webui\models/ControlNet
## ComfyUI-Manager: installing dependencies
Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 30, in <module>
    import git
ModuleNotFoundError: No module named 'git'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 37, in <module>
    run_script([sys.executable, '-s', '-m', 'pip', 'install', '-r', requirements_path])
  File "C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 15, in run_script
    process = subprocess.Popen(cmd, cwd=cwd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True, bufsize=1)
NameError: name 'subprocess' is not defined

Cannot import C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: name 'subprocess' is not defined

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

**Comment by alenknight** [comment]
getting this error now 
```
[comfy_mtb] | STATUS -> Some nodes failed to load:
        Failed to import module faceswap because ModuleNotFoundError: No module named 'onnx.onnx_cpp2py_export.checker'; 'onnx.onnx_cpp2py_export' is not a package

Check that you properly installed the dependencies.
```

**Comment by NeedsMoar** [comment]
You didn't install the requirements of ComfyUI-Manager or comfy_mtb like the message on the second one says.  
The manager needs at least GitPython.  You'll need to run setup for mtb yourself, or better yet install it through the manager once you get that working.

**Comment by ltdrdata** [comment]
This was my fault. It is already fixed.
