### ISSUE TITLE
[Errno 48] error while attempting to bind on address ('127.0.0.1', 8188): address already in use

### ISSUE THREAD

**Issue by Autantpourmoi** [comfyanonymous/ComfyUI#1579]
how to reproduce , starting Comfy ui with python main.py --force-fp16
Comfy ui doesn't work anymore after installing Comfy Ui Manager ( did work once together )

python main.py --force-fp16
** ComfyUI start up time: 2023-09-23 01:42:26.047494

Prestartup times for custom nodes:
   0.0 seconds: /Users/lucvaligny/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 65536 MB, total RAM 65536 MB
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### ComfyUI Revision: 1477 [29ccf9f4]

Import times for custom nodes:
   0.1 seconds: /Users/lucvaligny/ComfyUI/custom_nodes/ComfyUI-Manager
   2.8 seconds: /Users/lucvaligny/ComfyUI/custom_nodes/stability-ComfyUI-nodes

Traceback (most recent call last):
  File "/Users/lucvaligny/ComfyUI/main.py", line 191, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "/Users/lucvaligny/miniforge3/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/lucvaligny/ComfyUI/main.py", line 105, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "/Users/lucvaligny/ComfyUI/server.py", line 609, in start
    await site.start()
  File "/Users/lucvaligny/miniforge3/lib/python3.10/site-packages/aiohttp/web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "/Users/lucvaligny/miniforge3/lib/python3.10/asyncio/base_events.py", line 1519, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 48] error while attempting to bind on address ('127.0.0.1', 8188): address already in use

**Comment by ltdrdata** [comment]
It means that there is another ComfyUi is running.
