### ISSUE TITLE
cv2? 

### ISSUE THREAD

**Issue by Ramam001** [comfyanonymous/ComfyUI#1596]
X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-09-24 18:23:04.255763

Prestartup times for custom nodes:
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 4096 MB, total RAM 14188 MB
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
xformers version: 0.0.21
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints X:/A1111/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path configs X:/A1111/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae X:/A1111/stable-diffusion-webui/models/VAE
Adding extra search path loras X:/A1111/stable-diffusion-webui/models/Lora
Adding extra search path loras X:/A1111/stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models X:/A1111/stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models X:/A1111/stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models X:/A1111/stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings X:/A1111/stable-diffusion-webui/embeddings
Adding extra search path hypernetworks X:/A1111/stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet X:/A1111/stable-diffusion-webui/models/ControlNet
### ComfyUI Revision: 1459 [db63aa7e]
Traceback (most recent call last):
  File "X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes\__init__.py", line 1, in <module>
    from .post_processing_nodes import NODE_CLASS_MAPPINGS
  File "X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes\post_processing_nodes.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes module for custom nodes: No module named 'cv2'
### Loading: ComfyUI-Inspire-Pack (V0.14.1)

Import times for custom nodes:
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\sharpness_ally.py
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\histogram_equalization.py
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\gaussian_blur_ally.py
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\saturation_ally.py
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\imageflip_ally.py
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\Pseudo_HDR_ally.py
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds (IMPORT FAILED): X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.9 seconds: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: X:\A1111\StabilityMatrix-win-x64\Data\Packages\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by NeedsMoar** [comment]
This isn't related to comfy, it's a custom node, and it may or may not be an actual bug there depending on how the nodes were installed.  If you didn't install through the manager the requirements won't be installed, if you did you might have missed the error installing CV2.

The module CV2 isn't installed.  
Run
pip install cv2 
and try again
