### ISSUE TITLE
Error reported after installed several custom nodes

### ISSUE THREAD

**Issue by ultimatech-cn** [comfyanonymous/ComfyUI#1603]
When loading node Manager, there will be following error message reported:

```
FETCH DATA from: D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 522, in fetch_customnode_mappings
    json_obj = await get_data(uri)
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 367, in get_data
    async with session.get(uri) as resp:
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 1141, in __aenter__
    self._resp = await self._coro
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client.py", line 560, in _request
    await resp.start(conn)
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\client_reqrep.py", line 899, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "D:\dev\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [WinError 121] 信号灯超时时间已到
```

**Comment by jn-jairo** [comment]
Errors related to custom nodes should be addressed on the repository where you downloaded that custom node.

This repository doesn't have the code for the ComfyUI-Manager or any other custom node, so there is nothing we can do here.

**Comment by ultimatech-cn** [comment]
Thanks a lot!
