### ISSUE TITLE
Q: How to get mask from Ultralytics?

### ISSUE THREAD

**Issue by sedetweiler** [comfyanonymous/ComfyUI#1656]
I want to work with the mask from Ultralytics, but I do not want to use the facedetailer. Is there a simple method to get the mask that was computed by that node?

**Comment by sedetweiler** [comment]
Sorry, this was not the correct place for this issue.

**Comment by ltdrdata** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/128333288/6d3773da-d67f-4d66-b2f5-936076ce51cd)

However, an issue was discovered during recent testing and has been fixed, so you need to update the `Impact Pack`.

**Comment by sedetweiler** [comment]
Thank you!  My next wish is for a random file to be selected from a directory.  I want to use this for embeddings in the IPadapter. ;-)

**Comment by sedetweiler** [comment]
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 127, in doit
    mask = segm_detector.detect_combined(image, threshold, dilation)
AttributeError: 'NO_SEGM_DETECTOR' object has no attribute 'detect_combined'
```

**Comment by ltdrdata** [comment]
> ```
> !!! Exception during processing !!!
> Traceback (most recent call last):
>   File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "D:\stable_diffusion\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "D:\stable_diffusion\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 127, in doit
>     mask = segm_detector.detect_combined(image, threshold, dilation)
> AttributeError: 'NO_SEGM_DETECTOR' object has no attribute 'detect_combined'
> ```

You should use `-seg` model when if you wanna use SEGM_DETECTOR.
Otherwise, you have to use BBOX_DETECTOR. Each model's capabilities are different.

**Comment by sedetweiler** [comment]
Thanks for the clarification.
