### ISSUE TITLE
Arch Linux AMD RX6750XT  No nvidia driver found error during launch.

### ISSUE THREAD

**Issue by Kuduzkehpan** [comfyanonymous/ComfyUI#1662]
installed smoothly as your  guide describes. After i launch main.py   it gives error.

`Traceback (most recent call last):
  File "/home/mea/ComfyUI/main.py", line 72, in <module>
    import execution
  File "/home/mea/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/home/mea/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/home/mea/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "/home/mea/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/home/mea/ComfyUI/comfy/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/mea/ComfyUI/comfy/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mea/ComfyUI/pyenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/mea/ComfyUI/pyenv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
`  
Automatic1111 works out of the box with same setup. thx for all help.

**Comment by Autantpourmoi** [comment]
> installed opencl packages. with system package manager. then installed pytorch with re-typing it seems copy paste codes caused some problems maybe spacing or so whatever. it works now. if any one counter this again type the codes especially pip and python codes to terminal which are in guide.

ihello , man, i'm struggling since  days with that error message , what codes and guide are u refering too? please
