### ISSUE TITLE
External folder handling for files

### ISSUE THREAD

**Issue by Void2258** [comfyanonymous/ComfyUI#1664]
Models, Vaes, nodes setups, inputs, outputs, etc. are currently stored in the ComfyUI folder in predetermined locations. Any files not part of the install itself should be able to be moved another location, separate from the install folder. This has 2 key advantages:

- It allows you to put these files on a separate drive/device if needed for space (due to the large sizes that can be involved) or technology (SSD vs HDD, NAS use, separating data and programs across different drives) reasons without resorting to symlinks.
- It separates these files from the install so that, in the event something goes wrong that warrants a full delete and reinstall, the files that are not part of the install itself are not inside the folder structure of the install, leading to them also being deleted unless the user remembers to manually move each and every relevant file/folder, which is likely to result in accidental deletion of at least some files.

**Comment by Void2258** [comment]
I have tried to use this, but nothing I try entering into this file will work. Comfy fails to load with errors if the file is not inactivated (extension changed from .yaml).

**Comment by jn-jairo** [comment]
> I have tried to use this, but nothing I try entering into this file will work. Comfy fails to load with errors if the file is not inactivated (extension changed from .yaml). I also meant this to suggest this be something you can set in options.

If you provide the yaml file and errors we can try to help you.

**Comment by Void2258** [comment]
Yaml file can;t be posted to github comments.

File contents:
```
#Rename this to extra_model_paths.yaml and ComfyUI will load it

#config for a1111 ui
#all you have to do is change the base_path to where yours is installed
#a111:
#    base_path: path/to/stable-diffusion-webui/
#
#    checkpoints: models/Stable-diffusion
#    configs: models/Stable-diffusion
#    vae: models/VAE
#    loras: |
#         models/Lora
#         models/LyCORIS
#    upscale_models: |
#                  models/ESRGAN
#                  models/RealESRGAN
#                  models/SwinIR
#    embeddings: embeddings
#    hypernetworks: models/hypernetworks
#    controlnet: models/ControlNet

#other_ui:
#    base_path: path/to/ui
    checkpoints: H:\Stable_diffusion_files\Stable_diffusion_models
    vae: H:\Stable_diffusion_files\VAE
    loras: H:\Stable_diffusion_files\loras
    embeddings: H:\Stable_diffusion_files\embeddings
    controlnet: H:\Stable_diffusion_files\controlnet
#    gligen: models/gligen
#    custom_nodes: path/custom_nodes
```

Error:
```
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\main.py", line 158, in <module>
    load_extra_path_config(extra_model_paths_config_path)
  File "H:\ComfyUI_windows_portable\ComfyUI\main.py", line 134, in load_extra_path_config
    for y in conf[x].split("\n"):
TypeError: string indices must be integers

H:\ComfyUI_windows_portable>pause
```

**Comment by jn-jairo** [comment]
You need to uncomment the other_ui line:

```yaml
other_ui:
    checkpoints: H:\Stable_diffusion_files\Stable_diffusion_models
    vae: H:\Stable_diffusion_files\VAE
    loras: H:\Stable_diffusion_files\loras
    embeddings: H:\Stable_diffusion_files\embeddings
    controlnet: H:\Stable_diffusion_files\controlnet
```

About the output folder there is the option `--output-directory` to set it, but the option to set the input directory is missing so I made a PR #1666 to add it.

**Comment by Void2258** [comment]
Wow suddenly works. It is not clear that line is a command and not an actual comment.

**Comment by jn-jairo** [comment]
The output directory is not added to the yaml file, it is a command option when you start like `python main.py --output-directory "/path/to/output_directory"`

**Comment by Void2258** [comment]
I am using the windows portable version so I just click `run_nvidia_gpu`.

**Comment by jn-jairo** [comment]
> I am using the windows portable version so I just click `run_nvidia_gpu`. And in any case having control of the output location is something that is mostly useful if it has some level of persistence, so a command option is not ideal.

I didn't even know there was a portable version, now your feature requests makes more sense.

**Comment by Void2258** [comment]
I got it from this github repo. It's the only windows version I even see.

**Comment by BlankFX1** [comment]
Comming from A1111 and after trying to get this to run for an hour I already get very UnComfy and frustrated with this UI...

None of this works:
`
other_ui:
checkpoints: G:\SD-Models\CivitAI
`
