### ISSUE TITLE
cannot select an axis to squeeze out which has size not equal to one

### ISSUE THREAD

**Issue by hben35096** [comfyanonymous/ComfyUI#1665]
I upgraded to version: 9bfec2bdbf0b0d778087a9b32f79e57e2d15b913
The following error occurs:

Loads SAM model: /mnt/workspace/ComfyUI/models/sams/VIT-B/sam_vit_b_01ec64.pth (device:AUTO)

0: 640x448 1 person, 89.3ms
Speed: 2.9ms preprocess, 89.3ms inference, 2.6ms postprocess per image at shape (1, 3, 640, 448)
semd to cuda:0
Loads SAM model: /mnt/workspace/ComfyUI/models/sams/VIT-B/sam_vit_b_01ec64.pth (device:AUTO)
semd to cuda:0
# of Detected SEGS: 1
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1918, in doit
    result = core.mask_to_segs(mask, combined, crop_factor, bbox_fill, drop_size)
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 712, in mask_to_segs
    mask = np.squeeze(mask, axis=1)
  File "<__array_function__ internals>", line 200, in squeeze
  File "/opt/conda/lib/python3.10/site-packages/numpy/core/fromnumeric.py", line 1571, in squeeze
    return squeeze(axis=axis)
ValueError: cannot select an axis to squeeze out which has size not equal to one
![image](https://github.com/comfyanonymous/ComfyUI/assets/139383150/fae2dc52-b3e7-4fef-9892-5cc7e8c5c626)

When I fall back to: 77c124c5a17534e347bdebbc1ace807d61416147
then together is normal. We used 3 machines, Linux and Windows, although 9bfec2bdbf0b0d778087a9b32f79e57e2d15b913 error is different, but 77c124c5a17534e347bdebbc1ace807d61416147 are normal.

**Comment by ltdrdata** [comment]
You should update `Impact Pack`, too.
In the recent update, the mask structure of `ComfyUI` has changed, and `Impact Pack` has been updated for compatibility with the revised mask structure.

**Comment by hben35096** [comment]
> You should update `Impact Pack`, too. In the recent update, the mask structure of `ComfyUI` has changed, and `Impact Pack` has been updated for compatibility with the revised mask structure.

I updated ComfyUI to "0e763e880f5e838e7a1e3914444cae6790c48627", Impact Pack updated to "b4c0ddf33e5c8634fce180449af54af4daaa3983", so, an error is reported at another node:

!!! Exception during processing !!!
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 11349, in bounded_image_blend_with_mask
    target_mask_pil = Image.fromarray((target_mask.cpu().numpy() * 255).astype(np.uint8), mode='L')
  File "/opt/conda/lib/python3.10/site-packages/PIL/Image.py", line 3103, in fromarray
    raise ValueError(msg)
ValueError: Too many dimensions: 3 > 2.

I fall back to ComfyUI "77c124c5a17534e347bdebbc1ace807d61416147"; Impact Pack remains up to date "b4c0ddf33e5c8634fce180449af54af4daaa3983". Everything is normal.

**Comment by a63976659** [comment]
中间加入一个镜像节点就可以了 

![Image](https://github.com/user-attachments/assets/4286c5e6-c9d4-4f59-9518-350fd0d6a281)
