### ISSUE TITLE
OSError: [WinError 193]

### ISSUE THREAD

**Issue by DezorianGuv** [comfyanonymous/ComfyUI#1694]
Good day to you,

I am using Automatic1111, but today decided to switch to ComfyUI once more, but I get the following error when starting "run_nvidia_gpu" (I do own such a card):

####################################################

C:\Users\fires\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-08 18:24:10.025363

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\fires\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\fires\ComfyUI_windows_portable\ComfyUI\main.py", line 69, in <module>
    import comfy.utils
  File "C:\Users\fires\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "C:\Users\fires\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 193] %1is not a valid Win32 application. Error loading "C:\Users\fires\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

C:\Users\fires\ComfyUI_windows_portable>pause

####################################################

Any idea? I installed the following, but to no avail:
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
pip install -r requirements.txt

What can I do?

**Comment by NeedsMoar** [comment]
The Windows pre-packaged versions already include torch and all of comfy's own dependencies (you didn't specify which one of the comfy packages you downloaded) but it's unlikely running pip like that actually installed torch where you expected it to.  It needs to be in the embedded environment.  You also need to have a minimum driver version to run the various versions of cuda:  >=527.41 in the case of 12.1, or just install the 11.8 version which doesn't have as many libraries you'll need to build yourself when extensions need them;  the newness of torch 2.1.0 + 12.1 means some of the packages don't exist yet as prebuilts and building them ranges from easy to completely broken at the moment.

**Comment by DezorianGuv** [comment]
SUCCES! 
I installed the mentioned "Cuda 11.8" dev package.

While the "ComfyUI_windows_portable_nvidia_cu121_or_cpu" (resulting in the error described above) still didn't work, another package named "ComfyUI_windows_portable_nvidia_cu118_or_cpu" DID WORK. 

Thanks for the support!

**Comment by NeedsMoar** [comment]
Glad it helped.
Happy image-generating
