### ISSUE TITLE
ComfyUI Exceeds Python Max Recursion Depth When Run For Extended Periods of Time

### ISSUE THREAD

**Issue by jacobhawkins495** [comfyanonymous/ComfyUI#1729]
If you have ComfyUI running for an extended period of time, it will begin producing errors after the KSampler step because it has exceeded Python's maximum recursion depth. I have a slower GPU (RX 5700XT) so I leave ComfyUI running 24/7 generating images that I look at periodically in bulk, picking the best images to use as rotating wallpapers for my computer. After approximately four days, ComfyUI will begin producing the error at the bottom of this issue and will cease to produce images. It will run all steps up to and including the KSampler step to completion, but it will no longer move on to the VAE decode step. I have attached my workflow in case it is needed. It uses a couple nodes I wrote myself that I can provide if needed, but the issue persists without them present.

As time goes on, the console also becomes filled with an increasingly large number of lines saying

`WARNING:accelerate:big_modeling.py: You shouldn't move a model when it is dispatched on multiple devices`

to the point the console is 90% just this warning being repeated.

[WAS Workflow With Upscale and Blur.json](https://github.com/comfyanonymous/ComfyUI/files/12884423/WAS.Workflow.With.Upscale.and.Blur.json)

```
WAS Node Suite: Wildcard Path: /mnt/Deep Storage 2/Stable Diffusions/ComfyUI/custom_nodes/was-node-suite-comfyui/wildcards
WAS Node Suite: CLIPTextEncode Parsed Prompt:
 (photograph:1.1), desert mesa, at dusk, with a river, cloudy weather
WAS Node Suite: Wildcard Path: /mnt/Deep Storage 2/Stable Diffusions/ComfyUI/custom_nodes/was-node-suite-comfyui/wildcards
WAS Node Suite: CLIPTextEncode Parsed Prompt:
 blurry, grainy, noisy, artifacts, oversaturated, low quality, digital art, cartoon, anime, artist name, signature, watermark, text, words, copyright
loading new
loading in lowvram mode 1073.5708379745483
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [05:20<00:00,  8.02s/it]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/nodes.py", line 267, in decode
    return (vae.decode(samples["samples"]), )
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/comfy/sd.py", line 197, in decode
    model_management.free_memory(memory_used, self.device)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/comfy/model_management.py", line 333, in free_memory
    m.model_unload()
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/comfy/model_management.py", line 304, in model_unload
    self.model.unpatch_model(self.model.offload_device)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/comfy/model_patcher.py", line 287, in unpatch_model
    self.model.to(device_to)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/accelerate/big_modeling.py", line 411, in wrapper
    return fn(*args, **kwargs)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/accelerate/big_modeling.py", line 411, in wrapper
    return fn(*args, **kwargs)
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/accelerate/big_modeling.py", line 411, in wrapper
    return fn(*args, **kwargs)
  [Previous line repeated 966 more times]
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/accelerate/big_modeling.py", line 408, in wrapper
    for param in model.parameters():
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1710, in parameters
    for name, param in self.named_parameters(recurse=recurse):
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1737, in named_parameters
    for elem in gen:
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1679, in _named_members
    for module_prefix, module in modules:
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1889, in named_modules
    for m in module.named_modules(memo, submodule_prefix, remove_duplicate):
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1889, in named_modules
    for m in module.named_modules(memo, submodule_prefix, remove_duplicate):
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1889, in named_modules
    for m in module.named_modules(memo, submodule_prefix, remove_duplicate):
  [Previous line repeated 7 more times]
  File "/mnt/Deep Storage 2/Stable Diffusions/ComfyUI/sdxl/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1883, in named_modules
    memo.add(self)
RecursionError: maximum recursion depth exceeded while calling a Python object

Prompt executed in 330.07 seconds
```

**Comment by comfyanonymous** [comment]
This message won't appear anymore since: https://github.com/comfyanonymous/ComfyUI/commit/36a7953142ccf3f9debf9305e3cbeb3bfe956ee3

**Comment by abhinavzspace** [comment]
I am trying to run XY Plots through Comfy Roll custom nodes. Getting the same error, even if I run just two processes in the queue. Kindly let me know if more info is needed. Thanks a lot.

```
To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: C:\Users\abhinav\projects\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
Exception in thread Thread-8 (prompt_worker):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\threading.py", line 953, in run
got prompt
    self._target(*self._args, **self._kwargs)
  File "C:\Users\abhinav\projects\ComfyUI\main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 386, in execute
    to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1], memo)), a[-1]), to_execute)))
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 386, in <lambda>
    to_execute = sorted(list(map(lambda a: (len(recursive_will_execute(prompt, self.outputs, a[-1], memo)), a[-1]), to_execute)))
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 214, in recursive_will_execute
    will_execute += recursive_will_execute(prompt, outputs, input_unique_id, memo)
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 214, in recursive_will_execute
    will_execute += recursive_will_execute(prompt, outputs, input_unique_id, memo)
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 214, in recursive_will_execute
    will_execute += recursive_will_execute(prompt, outputs, input_unique_id, memo)
  [Previous line repeated 990 more times]
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 210, in recursive_will_execute
    if isinstance(input_data, list):
RecursionError: maximum recursion depth exceeded while calling a Python object
```
