### ISSUE TITLE
I use ControlNet T2I-Adapter style model，something wrong  happen？

### ISSUE THREAD

**Issue by GeLi1989** [comfyanonymous/ComfyUI#1732]
error message like  this：

loading new
error checkpoint does not contain controlnet or t2i adapter data /content/ComfyUI/models/controlnet/t2iadapter_style_sd14v1.pth
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/ComfyUI/nodes.py", line 643, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength)
AttributeError: 'NoneType' object has no attribute 'copy'

How can I solve the problem？  Thanks

**Comment by jn-jairo** [comment]
For the t2i adapter style model follow the example here https://github.com/comfyanonymous/ComfyUI/issues/65#issuecomment-1476902577

**Comment by GeLi1989** [comment]
> For the t2i adapter style model follow the example here [#65 (comment)](https://github.com/comfyanonymous/ComfyUI/issues/65#issuecomment-1476902577)

Thanks for your help
