### ISSUE TITLE
Broken : × python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by ksorah1** [comfyanonymous/ComfyUI#1737]
Hello,

I try to upgrade it, I reinstalled everything, but I still get this :
`
C:\Users\JyCS\ComfyUI_windows_portable\update>..\python_embeded\python.exe .\update.py ..\ComfyUI\
stashing current changes
nothing to stash
creating backup branch: backup_branch_2023-10-13_20_09_51
checking out master branch
pulling latest changes
Done!

C:\Users\JyCS\ComfyUI_windows_portable\update>..\python_embeded\python.exe -s -m pip install --upgrade torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117 xformers -r ../ComfyUI/requirements.txt pygit2
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu117
Requirement already satisfied: torch in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (1.13.1+cu117)
Collecting torch
  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/74/07/edce54779f5c3fe8ab8390eafad3d7c8190fce68f922a254ea77f4a94a99/torch-2.1.0-cp311-cp311-win_amd64.whl.metadata
  Using cached torch-2.1.0-cp311-cp311-win_amd64.whl.metadata (25 kB)
Requirement already satisfied: torchvision in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (0.14.1+cu117)
Collecting torchvision
  Obtaining dependency information for torchvision from https://files.pythonhosted.org/packages/20/ac/ab6f42af83349e679b03c9bb18354740c6b58b17dba329fb408730230584/torchvision-0.16.0-cp311-cp311-win_amd64.whl.metadata
  Using cached torchvision-0.16.0-cp311-cp311-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: torchaudio in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (0.13.1+cu117)
Collecting torchaudio
  Obtaining dependency information for torchaudio from https://files.pythonhosted.org/packages/11/30/715101782513f94c834ebe3afb9a29b0fae1121f64963db9d39fb80da53e/torchaudio-2.1.0-cp311-cp311-win_amd64.whl.metadata
  Using cached torchaudio-2.1.0-cp311-cp311-win_amd64.whl.metadata (5.7 kB)
Requirement already satisfied: xformers in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (0.0.16)
Collecting xformers
  Obtaining dependency information for xformers from https://files.pythonhosted.org/packages/8e/28/bb4362c05723324e4b66b3d6ffc901a1ca6382dbf47758d4e8340dcd71a5/xformers-0.0.22-cp311-cp311-win_amd64.whl.metadata
  Using cached xformers-0.0.22-cp311-cp311-win_amd64.whl.metadata (1.0 kB)
Requirement already satisfied: pygit2 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (1.11.1)
Collecting pygit2
  Obtaining dependency information for pygit2 from https://files.pythonhosted.org/packages/f2/6a/943142abc0f35ad6c0b2ede1f561abdece60a09c3ca44cf5ed2ea4416058/pygit2-1.13.1-cp311-cp311-win_amd64.whl.metadata
  Using cached pygit2-1.13.1-cp311-cp311-win_amd64.whl.metadata (3.7 kB)
Requirement already satisfied: torchsde in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 2)) (0.2.5)
Collecting torchsde (from -r ../ComfyUI/requirements.txt (line 2))
  Obtaining dependency information for torchsde from https://files.pythonhosted.org/packages/dd/1f/b67ebd7e19ffe259f05d3cf4547326725c3113d640c277030be3e9998d6f/torchsde-0.2.6-py3-none-any.whl.metadata
  Using cached torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Requirement already satisfied: einops in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 3)) (0.6.0)
Collecting einops (from -r ../ComfyUI/requirements.txt (line 3))
  Obtaining dependency information for einops from https://files.pythonhosted.org/packages/29/0b/2d1c0ebfd092e25935b86509a9a817159212d82aa43d7fb07eca4eeff2c2/einops-0.7.0-py3-none-any.whl.metadata
  Using cached einops-0.7.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: transformers>=4.25.1 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 4)) (4.26.1)
Collecting transformers>=4.25.1 (from -r ../ComfyUI/requirements.txt (line 4))
  Obtaining dependency information for transformers>=4.25.1 from https://files.pythonhosted.org/packages/1a/d1/3bba59606141ae808017f6fde91453882f931957f125009417b87a281067/transformers-4.34.0-py3-none-any.whl.metadata
  Using cached transformers-4.34.0-py3-none-any.whl.metadata (121 kB)
Requirement already satisfied: safetensors>=0.3.0 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 5)) (0.3.0)
Collecting safetensors>=0.3.0 (from -r ../ComfyUI/requirements.txt (line 5))
  Obtaining dependency information for safetensors>=0.3.0 from https://files.pythonhosted.org/packages/da/33/f7437e23b0bb3f14014ab60de5948ca2b5187031e955e2db2fa872e35a3c/safetensors-0.4.0-cp311-none-win_amd64.whl.metadata
  Using cached safetensors-0.4.0-cp311-none-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: aiohttp in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 6)) (3.8.4)
Collecting aiohttp (from -r ../ComfyUI/requirements.txt (line 6))
  Obtaining dependency information for aiohttp from https://files.pythonhosted.org/packages/2e/9f/9c37b01fc6a37c92f139a4cd937a92f03ebbd75379cfd55e85ca1e571643/aiohttp-3.8.6-cp311-cp311-win_amd64.whl.metadata
  Using cached aiohttp-3.8.6-cp311-cp311-win_amd64.whl.metadata (7.9 kB)
Requirement already satisfied: accelerate in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 7)) (0.17.1)
Collecting accelerate (from -r ../ComfyUI/requirements.txt (line 7))
  Obtaining dependency information for accelerate from https://files.pythonhosted.org/packages/d9/92/2d3aecf9f4a192968035880be3e2fc8b48d541c7128f7c936f430d6f96da/accelerate-0.23.0-py3-none-any.whl.metadata
  Using cached accelerate-0.23.0-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pyyaml in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 8)) (6.0.1)
Requirement already satisfied: Pillow in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 9)) (10.0.1)
Requirement already satisfied: scipy in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 10)) (1.10.1)
Collecting scipy (from -r ../ComfyUI/requirements.txt (line 10))
  Obtaining dependency information for scipy from https://files.pythonhosted.org/packages/81/d7/d2537d51efb692d0c411e64267ba349e7668d40f5bc73cefe78ccd650dcd/scipy-1.11.3-cp311-cp311-win_amd64.whl.metadata
  Using cached scipy-1.11.3-cp311-cp311-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: tqdm in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 11)) (4.65.0)
Collecting tqdm (from -r ../ComfyUI/requirements.txt (line 11))
  Obtaining dependency information for tqdm from https://files.pythonhosted.org/packages/00/e5/f12a80907d0884e6dff9c16d0c0114d81b8cd07dc3ae54c5e962cc83037e/tqdm-4.66.1-py3-none-any.whl.metadata
  Using cached tqdm-4.66.1-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: psutil in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from -r ../ComfyUI/requirements.txt (line 12)) (5.9.4)
Collecting psutil (from -r ../ComfyUI/requirements.txt (line 12))
  Using cached psutil-5.9.5-cp36-abi3-win_amd64.whl (255 kB)
Requirement already satisfied: filelock in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.12.4)
Requirement already satisfied: typing-extensions in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (4.5.0)
Requirement already satisfied: sympy in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1)
Requirement already satisfied: jinja2 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (2023.3.0)
Requirement already satisfied: numpy in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.24.2)
Requirement already satisfied: requests in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.28.2)
INFO: pip is looking at multiple versions of xformers to determine which version is compatible with other requirements. This could take a while.
Collecting xformers
  Obtaining dependency information for xformers from https://files.pythonhosted.org/packages/c7/70/e428a00b12c7cde505a48d6c8ea08af6b6867f62fd684b50ee00e52ce080/xformers-0.0.21-cp311-cp311-win_amd64.whl.metadata
  Using cached xformers-0.0.21-cp311-cp311-win_amd64.whl.metadata (1.0 kB)
  Obtaining dependency information for xformers from https://files.pythonhosted.org/packages/27/44/d4a42f582a485b40633b51fc991e73c39b0649ebc08905221adb29631d7f/xformers-0.0.20-cp311-cp311-win_amd64.whl.metadata
  Using cached xformers-0.0.20-cp311-cp311-win_amd64.whl.metadata (1.1 kB)
Collecting pyre-extensions==0.0.29 (from xformers)
  Using cached pyre_extensions-0.0.29-py3-none-any.whl (12 kB)
Requirement already satisfied: pyre-extensions==0.0.23 in c:\users\jycs\comfyui_windows_portable\python_embeded\lib\site-packages (from xformers) (0.0.23)
Collecting xformers
  Using cached xformers-0.0.16.tar.gz (7.3 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\JyCS\AppData\Local\Temp\pip-install-xl_una8f\xformers_08a77800dd4f4fa6bc72bbb664cb77cb\setup.py", line 23, in <module>
          import torch
        File "C:\Users\JyCS\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\__init__.py", line 128, in <module>
          raise err
      OSError: [WinError 127] La procédure spécifiée est introuvable. Error loading "C:\Users\JyCS\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

C:\Users\JyCS\ComfyUI_windows_portable\update>pause
Appuyez sur une touche pour continuer...`

**Comment by ksorah1** [comment]
If I try to run it (run_nvidia_gpu.bat) :

`
C:\Users\JyCS\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-10-13 20:34:41.503874

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\JyCS\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\JyCS\ComfyUI_windows_portable\ComfyUI\main.py", line 69, in <module>
    import comfy.utils
  File "C:\Users\JyCS\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "C:\Users\JyCS\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 127] La procédure spécifiée est introuvable. Error loading "C:\Users\JyCS\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\torch_cuda_cpp.dll" or one of its dependencies.

C:\Users\JyCS\ComfyUI_windows_portable>pause
Appuyez sur une touche pour continuer...


`
