### ISSUE TITLE
ComfyUI graphic bug 

### ISSUE THREAD

**Issue by Saladefroide** [comfyanonymous/ComfyUI#1752]
Hi everyone, 

I have an issue with ComfyUI. All my nodes disapeared  when I was copying and paste the image loader. It seems also appear randomly when I work on my workflows. Have you had any idea to solve it ? 
I also tryied to restart Comfy but the problem still appear. 
(Sorry for my bad english)  
![image](https://github.com/comfyanonymous/ComfyUI/assets/147981819/36388869-d72c-432c-9481-cc9fea3d5c69)

**Comment by Saladefroide** [comment]
Ok, it seems to be the same problem that Deer_duck_doe on this Reddit post in the comments : https://www.reddit.com/r/comfyui/comments/14wme8l/issue_frozen_interface_and_missing_nodes_how_can/
Still not solved :( 
Thanks for helping

**Comment by ltdrdata** [comment]
This is not a graphics issue but something that has caused an error on the front end, leading to the interruption. If you are using Chrome, please press F12 to open the dev console and check for errors.

**Comment by Saladefroide** [comment]
Thanks! I checked the chrome console and found it. But I don't know what's going wrong : 

`Failed to load resource: net::ERR_FILE_NOT_FOUND
127.0.0.1/:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: chrome-extension://lpfemeioodjbpieminkklglpmhlngfcn/contentScripts/theCard.js
:8188/favicon.ico:1 
        
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
logging.js:315 DynamicPrompt detected
console.<computed> @ logging.js:315
logging.js:315 [🐍 pysssss] Skipping LinkRenderMode as core extension found
4logging.js:315 Warning, nodes missing on pasting
console.<computed> @ logging.js:315
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at WorkflowHistory.get_new_candidate_state (WorkflowHistory.js:227:52)
    at WorkflowHistory.before (WorkflowHistory.js:149:14)
    at app.graph.onBeforeChange (WorkflowHistory.js:120:33)
    at LGraph.beforeChange (litegraph.core.js:2024:18)
    at LGraphCanvas.processMouseDown (litegraph.core.js:6111:19)
    at LGraphCanvas.processMouseDown (app.js:846:37)
litegraph.core.js:7676 Uncaught TypeError: Cannot read properties of undefined (reading 'getBounding')
    at LGraphCanvas.computeVisibleNodes (litegraph.core.js:7676:55)
    at LGraphCanvas.drawFrontCanvas (litegraph.core.js:7787:38)
    at LGraphCanvas.draw (litegraph.core.js:7715:18)
    at LGraphCanvas.renderFrame (litegraph.core.js:5783:22)
14litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
18litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at WorkflowHistory.after (WorkflowHistory.js:160:70)
    at app.canvas._mouseup_callback (WorkflowHistory.js:61:37)
9litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
14litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
8litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
26litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
11litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
29litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at WorkflowHistory.get_new_candidate_state (WorkflowHistory.js:227:52)
    at WorkflowHistory.before (WorkflowHistory.js:149:14)
    at app.canvas.onMouse (WorkflowHistory.js:45:33)
    at LGraphCanvas.processMouseDown (litegraph.core.js:5881:22)
    at LGraphCanvas.processMouseDown (app.js:846:37)
2litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at WorkflowHistory.after (WorkflowHistory.js:160:70)
    at app.canvas._mouseup_callback (WorkflowHistory.js:61:37)
6litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
5litegraph.core.js:6398 Uncaught TypeError: Cannot read properties of undefined (reading 'mouseOver')
    at LGraphCanvas.processMouseMove (litegraph.core.js:6398:42)
    at LGraphCanvas.processMouseMove (app.js:872:37)
widgets.js:214 Uncaught TypeError: Cannot read properties of undefined (reading 'widgets')
    at app.canvas.onDrawBackground (widgets.js:214:20)
    at LGraphCanvas.drawBackCanvas (litegraph.core.js:8360:22)
    at LGraphCanvas.draw (litegraph.core.js:7711:18)
    at resizeCanvas (app.js:1282:11)
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
78litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
LGraph.serialize @ litegraph.core.js:2121
(anonyme) @ app.js:1311
6widgets.js:214 Uncaught TypeError: Cannot read properties of undefined (reading 'widgets')
    at app.canvas.onDrawBackground (widgets.js:214:20)
    at LGraphCanvas.drawBackCanvas (litegraph.core.js:8360:22)
    at LGraphCanvas.draw (litegraph.core.js:7711:18)
    at resizeCanvas (app.js:1282:11)
app.canvas.onDrawBackground @ widgets.js:214
LGraphCanvas.drawBackCanvas @ litegraph.core.js:8360
LGraphCanvas.draw @ litegraph.core.js:7711
resizeCanvas @ app.js:1282
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
LGraph.serialize @ litegraph.core.js:2121
(anonyme) @ app.js:1311
20widgets.js:214 Uncaught TypeError: Cannot read properties of undefined (reading 'widgets')
    at app.canvas.onDrawBackground (widgets.js:214:20)
    at LGraphCanvas.drawBackCanvas (litegraph.core.js:8360:22)
    at LGraphCanvas.draw (litegraph.core.js:7711:18)
    at resizeCanvas (app.js:1282:11)
app.canvas.onDrawBackground @ widgets.js:214
LGraphCanvas.drawBackCanvas @ litegraph.core.js:8360
LGraphCanvas.draw @ litegraph.core.js:7711
resizeCanvas @ app.js:1282
litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
LGraph.serialize @ litegraph.core.js:2121
(anonyme) @ app.js:1311
widgets.js:214 Uncaught TypeError: Cannot read properties of undefined (reading 'widgets')
    at app.canvas.onDrawBackground (widgets.js:214:20)
    at LGraphCanvas.drawBackCanvas (litegraph.core.js:8360:22)
    at LGraphCanvas.draw (litegraph.core.js:7711:18)
    at resizeCanvas (app.js:1282:11)
app.canvas.onDrawBackground @ widgets.js:214
LGraphCanvas.drawBackCanvas @ litegraph.core.js:8360
LGraphCanvas.draw @ litegraph.core.js:7711
resizeCanvas @ app.js:1282
138litegraph.core.js:2121 Uncaught TypeError: Cannot read properties of undefined (reading 'serialize')
    at LGraph.serialize (litegraph.core.js:2121:44)
    at app.js:1311:80
LGraph.serialize @ litegraph.core.js:2121
(anonyme) @ app.js:1311`

**Comment by Saladefroide** [comment]
When I refresh the page, the interface come back but the bug appears again when I copy paste some node

**Comment by ltdrdata** [comment]
Update ComfyUI to latest version and disable all custom nodes.
If the issue is persist please make as a another issue.
