### ISSUE TITLE
RuntimeError in import_utils.py

### ISSUE THREAD

**Issue by stalker168** [comfyanonymous/ComfyUI#1753]
Please help me with the problem.
After some time of inactivity, I try to launch ComfyUI and get an error with import_utils.py.

```
Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1282, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\__init__.py", line 15, in <module>
    from . import (
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\mt5\__init__.py", line 29, in <module>
    from ..t5.tokenization_t5 import T5Tokenizer
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\t5\tokenization_t5.py", line 24, in <module>
    import sentencepiece as spm
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sentencepiece\__init__.py", line 13, in <module>
    from . import _sentencepiece
ImportError: cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) (E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sentencepiece\__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py", line 72, in <module>
    import execution
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 12, in <module>
    import nodes
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 12, in <module>
    from . import clip_vision
  File "E:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\clip_vision.py", line 1, in <module>
    from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, CLIPImageProcessor, modeling_utils
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1272, in __getattr__
    module = self._get_module(self._class_to_module[name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 1284, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip because of the following error (look up to see its traceback):
cannot import name '_sentencepiece' from partially initialized module 'sentencepiece' (most likely due to a circular import) (E:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\sentencepiece\__init__.py)
```

I tried [**this**](https://github.com/Gourieff/comfyui-reactor-node/issues/5) method, but it didn't help me.

**Comment by stalker168** [comment]
I solved this problem by completely removing ComfyUI and Python. Then I installed it again.

**Comment by ZWH20** [comment]
I had a similar problem.
Please help me with the problem.
![捕获](https://github.com/user-attachments/assets/8ba7a178-16ef-4eb5-bac7-09555bbd2fc0)
