### ISSUE TITLE
aliyunsdkcore can't install

### ISSUE THREAD

**Issue by THtianhao** [comfyanonymous/ComfyUI#1821]
Dear authors,

I am a plugin developer for ComfyUI. Recently, I have developed a plugin,

[[Portrait-Maker](https://github.com/THtianhao/ComfyUI-Portrait-Maker)](https://github.com/THtianhao/ComfyUI-Portrait-Maker)
My project needs to use modelscope pipeline, and in the requirement.txt, I need to install modelscope. 
However, it depends on  [aliyun-python-sdk-core](https://pypi.org/project/aliyun-python-sdk-core/)

and many users have reported encountering the aliyunsdkcore issue when using the `Windows integration package`

like this:

```
Collecting aliyun-python-sdk-core>=2.13.12 (from oss2~=2.17.0->openxlab->opendatalab->openmim)
  Using cached aliyun-python-sdk-core-2.13.36.tar.gz (440 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\albam\AppData\Local\Temp\pip-install-025cd5tn\aliyun-python-sdk-core_78b82f9b135341b1a2825e5884118385\setup.py", line 41, in <module>
          VERSION = __import__(PACKAGE).__version__
      ModuleNotFoundError: No module named 'aliyunsdkcore'
      [end of output]
```
creating a virtual environment manually does not have this problem ，how can i solve this problem

**Comment by THtianhao** [comment]
help me please

**Comment by wei94480381** [comment]
ModuleNotFoundError: No module named 'modelscope'

Cannot import D:\ComfyUI\custom_nodes\ComfyuI-portrait-Maker module for custom nodes: No module named 'modelscope'
2023-11-28 11:29:10,986 - roop - INFO - roop v0.0.2
这个问题怎么解决啊

**Comment by RalphHan** [comment]
I resolved it by running
```
pip install aliyun-python-sdk-core-v3==2.13.10
```
