### ISSUE TITLE
Unable to run with ipadapter_face without error

### ISSUE THREAD

**Issue by offmybach** [comfyanonymous/ComfyUI#1825]
I am using the Reposer workflow and just simply get to the point where image is generated. I get an error at ipadapter_face nearly every time.

Error occurred when executing IPAdapter:

Error(s) in loading state_dict for Resampler:
size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024]).

File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 162, in adapter
self.ipadapter = IPAdapterModel(
^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\custom_nodes\IPAdapter-ComfyUI\ip_adapter.py", line 102, in __init__
self.image_proj_model.load_state_dict(state_dict["image_proj"])
File "C:\Pacman\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

or 
ed when executing CheckpointLoaderSimple:

'model.diffusion_model.input_blocks.0.0.weight'

File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\nodes.py", line 476, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 416, in load_checkpoint_guess_config
model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 120, in model_config_from_unet
unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 36, in detect_unet_config
model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]

and in the script

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\nodes.py", line 688, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (1.0 - start_percent, 1.0 - end_percent))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

Prompt executed in 4.88 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\nodes.py", line 688, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (1.0 - start_percent, 1.0 - end_percent))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

Prompt executed in 0.09 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\nodes.py", line 688, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (1.0 - start_percent, 1.0 - end_percent))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

Prompt executed in 0.08 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\nodes.py", line 688, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (1.0 - start_percent, 1.0 - end_percent))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

Prompt executed in 0.08 seconds
got prompt
model_type EPS
adm 0
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
left over keys: dict_keys(['alphas_cumprod', 'alphas_cumprod_prev', 'betas', 'log_one_minus_alphas_cumprod', 'posterior_log_variance_clipped', 'posterior_mean_coef1', 'posterior_mean_coef2', 'posterior_variance', 'sqrt_alphas_cumprod', 'sqrt_one_minus_alphas_cumprod', 'sqrt_recip_alphas_cumprod', 'sqrt_recipm1_alphas_cumprod'])
Requested to load SD1ClipModel
Loading 1 new model
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Pacman\ComfyUI_windows_portable\ComfyUI\nodes.py", line 688, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (1.0 - start_percent, 1.0 - end_percent))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

Prompt executed in 4.79 seconds
got prompt
ERROR:root:Failed to validate prompt for output 158:
ERROR:root:* CheckpointLoaderSimple 16:
ERROR:root:  - Value not in list: ckpt_name: 'SD1.5/sd_15_analogMadness_v60.safetensors' not in (list of length 127)
ERROR:root:* CLIPVisionLoader 57:
ERROR:root:  - Value not in list: clip_name: 'ip_adapter_sd15/model.safetensors' not in ['SD1.5\\pytorch_model.bin', 'SDXL\\clip_vision_g.safetensors', 'SDXL\\pytorch_model.bin', 'clip_vision\\open_clip_pytorch_model.bin', 'model.safetensors']
ERROR:root:* ControlNetLoader 156:
ERROR:root:  - Value not in list: control_net_name: 'sd15/control-lora/control_lora_rank128_v11p_sd15_openpose_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 227:
ERROR:root:* ControlNetLoader 181:
ERROR:root:  - Value not in list: control_net_name: 'sd15/sd15_control_v11f1e_tile_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 232:
ERROR:root:* UpscaleModelLoader 188:
ERROR:root:  - Value not in list: model_name: 'swift_srgan_2x.pth' not in ['4x-UltraSharp.pth', 'RealESRGAN_x2.pth', 'RealESRGAN_x4plus_anime_6B.pth']
ERROR:root:Output will be ignored
Prompt executed in 0.72 seconds
got prompt
ERROR:root:Failed to validate prompt for output 158:
ERROR:root:* CLIPVisionLoader 57:
ERROR:root:  - Value not in list: clip_name: 'ip_adapter_sd15/model.safetensors' not in ['SD1.5\\pytorch_model.bin', 'SDXL\\clip_vision_g.safetensors', 'SDXL\\pytorch_model.bin', 'clip_vision\\open_clip_pytorch_model.bin', 'model.safetensors']
ERROR:root:* ControlNetLoader 156:
ERROR:root:  - Value not in list: control_net_name: 'sd15/control-lora/control_lora_rank128_v11p_sd15_openpose_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 227:
ERROR:root:* ControlNetLoader 181:
ERROR:root:  - Value not in list: control_net_name: 'sd15/sd15_control_v11f1e_tile_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 232:
ERROR:root:* UpscaleModelLoader 188:
ERROR:root:  - Value not in list: model_name: 'swift_srgan_2x.pth' not in ['4x-UltraSharp.pth', 'RealESRGAN_x2.pth', 'RealESRGAN_x4plus_anime_6B.pth']
ERROR:root:Output will be ignored
Prompt executed in 0.04 seconds
got prompt
ERROR:root:Failed to validate prompt for output 158:
ERROR:root:* CLIPVisionLoader 57:
ERROR:root:  - Value not in list: clip_name: 'ip_adapter_sd15/model.safetensors' not in ['SD1.5\\pytorch_model.bin', 'SDXL\\clip_vision_g.safetensors', 'SDXL\\pytorch_model.bin', 'clip_vision\\open_clip_pytorch_model.bin', 'model.safetensors']
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 227:
ERROR:root:* ControlNetLoader 181:
ERROR:root:  - Value not in list: control_net_name: 'sd15/sd15_control_v11f1e_tile_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 232:
ERROR:root:* UpscaleModelLoader 188:
ERROR:root:  - Value not in list: model_name: 'swift_srgan_2x.pth' not in ['4x-UltraSharp.pth', 'RealESRGAN_x2.pth', 'RealESRGAN_x4plus_anime_6B.pth']
ERROR:root:Output will be ignored
Prompt executed in 0.03 seconds
got prompt
ERROR:root:Failed to validate prompt for output 158:
ERROR:root:* CheckpointLoaderSimple 16:
ERROR:root:  - Value not in list: ckpt_name: 'SD1.5/sd_15_analogMadness_v60.safetensors' not in (list of length 127)
ERROR:root:* CLIPVisionLoader 57:
ERROR:root:  - Value not in list: clip_name: 'ip_adapter_sd15/model.safetensors' not in ['SD1.5\\pytorch_model.bin', 'SDXL\\clip_vision_g.safetensors', 'SDXL\\pytorch_model.bin', 'clip_vision\\open_clip_pytorch_model.bin', 'model.safetensors']
ERROR:root:* ControlNetLoader 156:
ERROR:root:  - Value not in list: control_net_name: 'sd15/control-lora/control_lora_rank128_v11p_sd15_openpose_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 227:
ERROR:root:* ControlNetLoader 181:
ERROR:root:  - Value not in list: control_net_name: 'sd15/sd15_control_v11f1e_tile_fp16.safetensors' not in (list of length 27)
ERROR:root:Output will be ignored
ERROR:root:Failed to validate prompt for output 232:
ERROR:root:* UpscaleModelLoader 188:
ERROR:root:  - Value not in list: model_name: 'swift_srgan_2x.pth' not in ['4x-UltraSharp.pth', 'RealESRGAN_x2.pth', 'RealESRGAN_x4plus_anime_6B.pth']
ERROR:root:Output will be ignored
Prompt executed in 0.93 seconds

**Comment by jn-jairo** [comment]
> Value not in list

Looks like you loaded a workflow but you don't have the models.

**Comment by saqibraza0902** [comment]
I encounter the same issue, i have the models but still getting the issue, PS: i am using custom nodes of IP Adapter
