### ISSUE TITLE
RuntimeError: Found no NVIDIA driver on your system

### ISSUE THREAD

**Issue by brunodpoliveira** [comfyanonymous/ComfyUI#1865]
Running this on Paperspace. Today's update broke ComfyUI for me. Whenever I try to run it, I stumble upon this error:

Traceback (most recent call last):
  File "/notebooks/ComfyUI/main.py", line 72, in <module>
    import execution
  File "/notebooks/ComfyUI/execution.py", line 12, in <module>
    import nodes
  File "/notebooks/ComfyUI/nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "/notebooks/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "/notebooks/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/notebooks/ComfyUI/comfy/model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/notebooks/ComfyUI/comfy/model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 769, in current_device
    _lazy_init()
  File "/usr/local/lib/python3.9/dist-packages/torch/cuda/__init__.py", line 298, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

I'm renting a RTX4000 or RTX5000,depending on the availability. It was working just fine this (29th October 2023) morning, but after an update, this error began showing up

**Comment by brunodpoliveira** [comment]
Latest update solved this problem
