### ISSUE TITLE
Snapshot manager

### ISSUE THREAD

**Issue by p0mad** [comfyanonymous/ComfyUI#1903]
FETCH DATA from: E:\integral\control\custom_nodes\ComfyUI-Manager\extension-node-map.json
Error handling request
Traceback (most recent call last):
  File "D:\sl\mamba\envs\comf\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request  
    resp = await request_handler(request)
  File "D:\sl\mamba\envs\comf\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "D:\sl\mamba\envs\comf\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "E:\integral\control\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "E:\integral\control\custom_nodes\ComfyUI-Manager\__init__.py", line 693, in get_snapshot_list   
    items = [f[:-5] for f in os.listdir(snapshots_directory) if f.endswith('.json')]
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'E:\\integral\\control\\custom_nodes\\ComfyUI-Manager\\snapshots'

**Comment by ltdrdata** [comment]
This issue is fixed on ComfyUI-Manager V0.38.2.
