### ISSUE TITLE
can't load lcm checkpoint, lcm lora works well

### ISSUE THREAD

**Issue by frankyifei** [comfyanonymous/ComfyUI#1933]
when trying to load lcm sdxl checkpoint, throw this error
```
Error occurred when executing CheckpointLoaderSimple:

'model.diffusion_model.input_blocks.0.0.weight'

File "F:\Comfy\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "F:\Comfy\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "F:\Comfy\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "F:\Comfy\ComfyUI\nodes.py", line 476, in load_checkpoint
out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
File "F:\Comfy\ComfyUI\comfy\sd.py", line 431, in load_checkpoint_guess_config
model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
File "F:\Comfy\ComfyUI\comfy\model_detection.py", line 141, in model_config_from_unet
unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
File "F:\Comfy\ComfyUI\comfy\model_detection.py", line 49, in detect_unet_config
model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
```

**Comment by comfyanonymous** [comment]
It's in diffusers format so you have to use the UNETLoader node to load it.

Here's a workflow: 
![ComfyUI_07672_](https://github.com/comfyanonymous/ComfyUI/assets/121283862/787efdac-f344-4c82-990d-0d8737b3bb00)

**Comment by frankyifei** [comment]
Thank you, it works. I also noticed there is a big difference in speed when I changed CFG to 1.0, 2.56/s. if using higher or lower than 1, speed is only around 1.40 which is what I normally get with SDXL. Same thing happen to lcm-lora. Why is that?

**Comment by comfyanonymous** [comment]
CFG 1.0 means there's negative prompt so there's 2x less processing to do to generate the image.

**Comment by zhanghongyong123456** [comment]
> It's in diffusers format so you have to use the UNETLoader node to load it.
> 
> Here's a workflow: ![ComfyUI_07672_](https://user-images.githubusercontent.com/121283862/281926547-787efdac-f344-4c82-990d-0d8737b3bb00.png)

when   i  use   this  workflow, i have   this  error,
![image](https://github.com/comfyanonymous/ComfyUI/assets/48466610/90e75878-d91e-4860-9df1-3fabe046432d)
I  use  UNERLoader   model :  
![image](https://github.com/comfyanonymous/ComfyUI/assets/48466610/0a76fa05-25f4-4c81-b229-882196b59be2)
I'm not sure what's wrong

**Comment by zhanghongyong123456** [comment]
> > It's in diffusers format so you have to use the UNETLoader node to load it.
> > Here's a workflow: ![ComfyUI_07672_](https://user-images.githubusercontent.com/121283862/281926547-787efdac-f344-4c82-990d-0d8737b3bb00.png)
> 
> when i use this workflow, i have this error, ![image](https://user-images.githubusercontent.com/48466610/281976215-90e75878-d91e-4860-9df1-3fabe046432d.png) I use UNERLoader model : download model in ![image](https://user-images.githubusercontent.com/48466610/281976842-a62377cf-19fd-48b3-8f80-fdaa00b6a020.png)
> 
> ![image](https://user-images.githubusercontent.com/48466610/281976392-0a76fa05-25f4-4c81-b229-882196b59be2.png) I'm not sure what's wrong

Mybe   use   this    worlflow  ,it's   OK,Use   Load Lora replace 
https://github.com/comfyanonymous/ComfyUI/issues/1934#issuecomment-1804991327

**Comment by comfyanonymous** [comment]
Use this workflow for the LCM loras:
https://gist.github.com/comfyanonymous/b948fd68aacc65c2ed37d743d0964f27

**Comment by zhanghongyong123456** [comment]
> Use this workflow for the LCM loras: https://gist.github.com/comfyanonymous/b948fd68aacc65c2ed37d743d0964f27

thanks,  It is   OK  ,

**Comment by zhanghongyong123456** [comment]
> Use this workflow for the LCM loras: https://gist.github.com/comfyanonymous/b948fd68aacc65c2ed37d743d0964f27

How do you use these two models（ 2 Full Param-tuned LCM (SD-XL, SSD-1B),）：
https://huggingface.co/latent-consistency/lcm-sdxl

**Comment by ltdrdata** [comment]
> ![image](https://user-images.githubusercontent.com/12389696/282124548-8da331c0-e7ba-45df-9e1f-4b6481e708b7.png) i get this error: When loading the graph, the following node types were not found: ModelSamplingDiscrete Nodes that have failed to load will show as red on the graph.
> 
> where can i download the node?

Update ComfyUI

**Comment by zhangp365** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/144313702/6ceabcda-c41e-45d4-a678-2f8ae95639bc)
When I use this in video 2 video, there are some error logs. How can I fix that?
![image](https://github.com/comfyanonymous/ComfyUI/assets/144313702/219a0c38-f2d2-42f0-90da-693687592152)

**Comment by xiaocaijiayou** [comment]
> It's in diffusers format so you have to use the UNETLoader node to load it.
> 
> Here's a workflow: ![ComfyUI_07672_](https://private-user-images.githubusercontent.com/121283862/281926547-787efdac-f344-4c82-990d-0d8737b3bb00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEyMjI2MDcsIm5iZiI6MTcwMTIyMjMwNywicGF0aCI6Ii8xMjEyODM4NjIvMjgxOTI2NTQ3LTc4N2VmZGFjLWYzNDQtNGM4Mi05OTBkLTBkODczN2IzYmIwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTEyOVQwMTQ1MDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZTEwNDRlMDMxMTkxM2RmOWFiZmQ3NGMzMWFjODJiOTM1Y2JmMzU0ZjI5Mjg2YzQzMWMwZmEyYzRiNmQyY2I3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2WumdddghkDEPJaNc7wZSvTkGpkfIDH9MbV50lzANw0)

Where to get the unet file? I only have the whole safetensors file with all components.

**Comment by hippogamesunity** [comment]
The same here. I can load sdXL_v10VAEFix.safetensors but not pixel-art-xl-v1.1.safetensors. How to get UNETLoader ? It's not present in the loaders list.

**Comment by giusparsifal** [comment]
Hell, sorry for my question, what does it means "workflow is in the image"? I can't understand it, please someone will explain me? Thank you...

**Comment by Dont-look-at-me** [comment]
when i tried to use SD3, i encounted the same problom. i dont know what's wrong.



the error code:
!!! Exception during processing!!! 'model.diffusion_model.input_blocks.0.0.weight'
Traceback (most recent call last):
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 516, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 476, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 232, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD3\UI\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 113, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'
