### ISSUE TITLE
The following node types were not found

### ISSUE THREAD

**Issue by luyaohwang** [comfyanonymous/ComfyUI#1935]
### ComfyUI Revision: 1667 [3e0033ef] | Released on '2023-11-10'

When loading the graph, the following node types were not found:
VHS_LoadVideoPath
LineArtPreprocessor
VHS_VideoCombine
VHS_LoadImagesPath
BatchPromptScheduleLatentInput
Nodes that have failed to load will show as red on the graph.

C:\Users\andy\Documents\Work\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI start up time: 2023-11-10 16:59:28.941586
Failed to execute startup-script: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / 'default'

Prestartup times for custom nodes:
   0.0 seconds (PRESTARTUP FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65349 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1667 [3e0033ef] | Released on '2023-11-10'
Traceback (most recent call last):
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 14, in <module>
    from .load_video_nodes import LoadVideoUpload, LoadVideoPath
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2'
Traceback (most recent call last):
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 2, in <module>
    from .utils import here, create_node_input_types
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'cv2'
Traceback (most recent call last):
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
ModuleNotFoundError: No module named 'numexpr'

Cannot import C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds (IMPORT FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds (IMPORT FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.2 seconds: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by zhanghongyong123456** [comment]
> ### Loading: ComfyUI-Manager (V0.43)
> ### ComfyUI Revision: 1667 [[3e0033e](https://github.com/comfyanonymous/ComfyUI/commit/3e0033ef30a111076af54a7a4e6b470cdc570886)] | Released on '2023-11-10'
> When loading the graph, the following node types were not found: VHS_LoadVideoPath LineArtPreprocessor VHS_VideoCombine VHS_LoadImagesPath BatchPromptScheduleLatentInput Nodes that have failed to load will show as red on the graph.
> 
> C:\Users\andy\Documents\Work\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build ** ComfyUI start up time: 2023-11-10 16:59:28.941586 Failed to execute startup-script: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py / 'default'
> 
> Prestartup times for custom nodes: 0.0 seconds (PRESTARTUP FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 24564 MB, total RAM 65349 MB Set vram state to: NORMAL_VRAM Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync VAE dtype: torch.bfloat16 Using pytorch cross attention
> 
> ### Loading: ComfyUI-Manager (V0.43)
> ### ComfyUI Revision: 1667 [[3e0033e](https://github.com/comfyanonymous/ComfyUI/commit/3e0033ef30a111076af54a7a4e6b470cdc570886)] | Released on '2023-11-10'
> Traceback (most recent call last): File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite__init__.py", line 1, in from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 14, in from .load_video_nodes import LoadVideoUpload, LoadVideoPath File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 5, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> Cannot import C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2' Traceback (most recent call last): File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux__init__.py", line 2, in from .utils import here, create_node_input_types File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\utils.py", line 4, in import cv2 ModuleNotFoundError: No module named 'cv2'
> 
> Cannot import C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux module for custom nodes: No module named 'cv2' Traceback (most recent call last): File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes__init__.py", line 57, in from .ScheduledNodes import ( File "C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in import numexpr ModuleNotFoundError: No module named 'numexpr'
> 
> Cannot import C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr'
> 
> Import times for custom nodes: 0.0 seconds (IMPORT FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux 0.0 seconds: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet 0.0 seconds (IMPORT FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes 0.0 seconds: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved 0.0 seconds (IMPORT FAILED): C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite 0.2 seconds: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188 FETCH DATA from: C:\Users\andy\Documents\Work\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

you  can  Install both libraries yourself,  like   this  :
![image](https://github.com/comfyanonymous/ComfyUI/assets/48466610/248a2431-9db0-4aff-8bae-209277f185cc)
python.exe -m pip install opencv-python  numexpr
