### ISSUE TITLE
Error at launching the UI

### ISSUE THREAD

**Issue by Bullseye110** [comfyanonymous/ComfyUI#1988]
Hello!

I'm trying to install ComfyUI with AnimateDiff on my sagemaker environment and I get this error:

"http://localhost:8188/" 
/home/studio-lab-user/ComfyUI 
** ComfyUI start up time: 2023-11-16 21:34:49.190564 
Prestartup times for custom nodes: 0.0 seconds: /home/studio-lab-user/ComfyUI/custom_nodes/ComfyUI-Manager Traceback (most recent call last): File "/home/studio-lab-user/ComfyUI/main.py", line 72, in <module> import execution File "/home/studio-lab-user/ComfyUI/execution.py", line 12, in <module> import nodes File 
"/home/studio-lab-user/ComfyUI/nodes.py", line 20, in <module> import comfy.diffusers_load File "/home/studio-lab-user/ComfyUI/comfy/diffusers_load.py", line 4, in <module> import comfy.sd File "/home/studio-lab-user/ComfyUI/comfy/sd.py", line 5, in <module> from comfy import model_management File "/home/studio-lab-user/ComfyUI/comfy/model_management.py", line 114, in <module> total_vram = get_total_memory(get_torch_device()) / (1024 * 1024) File "/home/studio-lab-user/ComfyUI/comfy/model_management.py", line 83, in get_torch_device return torch.device(torch.cuda.current_device()) File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/cuda/__init__.py", line 769, in current_device _lazy_init() File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init torch._C._cuda_init() RuntimeError: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org/ to install a PyTorch version that has been compiled with your version of the CUDA driver. "

I fixed it with: "!pip install xformers==0.0.20 tomesd==0.1.3 pytorch-lightning==1.9.4 accelerate==0.21.0".

But if I try to install the "Auxiliary Preprocessors" from the ComfyUI manager (because I need this node for AnimateDiff), I get the same error as before after I restart the UI to apply the installed nodes.

Do you have any idea on how I can make it to work?

I really wish to start learning AnimateDiff...

**Comment by DextiNxD** [comment]
found solution?

**Comment by gutris1** [comment]
> found solution?

try this [book](https://github.com/gutris1/segsmaker/blob/main/Segsmaker_ComfyUI.ipynb)
