### ISSUE TITLE
error if the image save path is on diffrent drive

### ISSUE THREAD

**Issue by ml1969** [comfyanonymous/ComfyUI#2025]
Hello together,

forst I have to say I love comfyui, great work. Laso the custom nodes.
RESPECT at all who are working for it.

My "problem" is.
I use a custom "image saver node".
If the path is on the same drive as the ComfyUI_windows_portable  there is no error message.
If I change the saving path to an diffrent drive, I got an error message.
The image is stored correctly.
For example.
The "ComfyUI_windows_portable" is on drive M: and I use as image saving path E:\images
following will come up in the console window:

`File "M:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "M:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "M:\ComfyUI_windows_portable\ComfyUI\server.py", line 271, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 826, in commonpath
ValueError: Paths don't have the same drive` 

I tried diffrent custom nodes WAS / WLSH  all the same error. If I bypass the saver node, no error message comes.

Greetings
michael

P.S. Sorry for my bad english. English ist not my native language.

**Comment by nintendnerd** [comment]
same here, using WAS Suite Image Save node to change my output folder to another drive

WAS Node Suite: Image file saved to: x:\2023-12-05\ComfyUI_0001.png
Prompt executed in 2.55 seconds
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 271, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 826, in commonpath
ValueError: Paths don't have the same drive
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "R:\PROJECTS\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 271, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 826, in commonpath
ValueError: Paths don't have the same drive

**Comment by ml1969** [comment]
@ltdrdata 
you´re right.
Comyui ist isnstalled on an other drive.
For saving the files I use a custom node, where I can specify the path and filename.
And Yes the path directs to an other drive. The images will be saved normaly.
But the error message irritates me a little.

Greeetings
Michael

**Comment by GalaxyTimeMachine** [comment]
I get the same error using the Ace Step v1.5 template, so not a custom node issue. Strangely, it doesn't happen every time, but sometimes it won't save the output MP3 because of it, other times it will.

```
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 510, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\middleware\cache_middleware.py", line 27, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 83, in deprecation_warning
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 173, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\server.py", line 498, in view_image
    if os.path.commonpath((os.path.abspath(full_output_dir), output_dir)) != output_dir:
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 861, in commonpath
ValueError: Paths don't have the same drive
```

**Comment by AlUlkesh** [comment]
You can always try simply using a symlink to the other drive, for example:

```
From the comfyui-maindir:

cd output
mklink /D mp3 r:\my_mp3
```

Then you can use the symlink as the directory for your outputs, but they still will physically be on the other drive.
