### ISSUE TITLE
TypeError: forward_timestep_embed() got an unexpected keyword argument 'time_context'

### ISSUE THREAD

**Issue by Yaohs1995** [comfyanonymous/ComfyUI#2037]
when I update the project, raise the error (TypeError: forward_timestep_embed() got an unexpected keyword argument 'time_context')
ERROR:root:Traceback (most recent call last):
  File "/home/yaohs/Work/ComfyUI/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/yaohs/Work/ComfyUI/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/yaohs/Work/ComfyUI/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/yaohs/Work/ComfyUI/nodes.py", line 1286, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/yaohs/Work/ComfyUI/nodes.py", line 1256, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/yaohs/Work/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 229, in animatediff_sample
    return wrap_function_to_inject_xformers_bug_info(orig_comfy_sample)(model, noise, *args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/model_utils.py", line 197, in wrapped_function
    return function_to_wrap(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/yaohs/Work/ComfyUI/comfy/samplers.py", line 711, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/yaohs/Work/ComfyUI/comfy/samplers.py", line 617, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/yaohs/Work/ComfyUI/comfy/samplers.py", line 556, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/comfy/samplers.py", line 277, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/comfy/samplers.py", line 267, in forward
    return self.apply_model(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/comfy/samplers.py", line 264, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/home/yaohs/Work/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 596, in sliding_sampling_function
    cond, uncond = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "/home/yaohs/Work/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 473, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/yaohs/Work/ComfyUI/comfy/model_base.py", line 73, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/yaohs/miniconda3/envs/cfui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/yaohs/Work/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 854, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
TypeError: forward_timestep_embed() got an unexpected keyword argument 'time_context'

**Comment by lenage** [comment]
got same issue here

**Comment by lenage** [comment]
rollback to 022033a0e75901c7c357ab96e1c804fd5da05770 works for me

**Comment by Yaohs1995** [comment]
I solved the problem through your method，thank you

**Comment by 0atmeal-ai** [comment]
> rollback to [022033a](https://github.com/comfyanonymous/ComfyUI/commit/022033a0e75901c7c357ab96e1c804fd5da05770) works for me

can you explain this please,  im having same error

**Comment by lenage** [comment]
> > rollback to [022033a](https://github.com/comfyanonymous/ComfyUI/commit/022033a0e75901c7c357ab96e1c804fd5da05770) works for me
> 
> can you explain this please, im having same error

just `git checkout 022033a0e75901c7c357ab96e1c804fd5da05770` to ignore latest changes

**Comment by 0atmeal-ai** [comment]
@lenage Thankyou mate

**Comment by zcai08** [comment]
same error.
I want to use SVD nodes so rollback doesn't work for me.
It seems that forward_timestep_embed() got embedded before, and the new defined one did not get to work.
I don't know how to fix it. I just simply copy the new funciton before the calls and looks like it works

**Comment by ltdrdata** [comment]
> same error. I want to use SVD nodes so rollback doesn't work for me. It seems that forward_timestep_embed() got embedded before, and the new defined one did not get to work. I don't know how to fix it. I just simply copy the new funciton before the calls and looks like it works

Even after updating both `ComfyUI` and `AnimateDiff Evolved` nodes to the latest versions, is the issue still persisting?

**Comment by gaathi1111** [comment]
> > same error. I want to use SVD nodes so rollback doesn't work for me. It seems that forward_timestep_embed() got embedded before, and the new defined one did not get to work. I don't know how to fix it. I just simply copy the new funciton before the calls and looks like it works
> 
> Even after updating both `ComfyUI` and `AnimateDiff Evolved` nodes to the latest versions, is the issue still persisting?

yes it still exists

**Comment by zcai08** [comment]
> > same error. I want to use SVD nodes so rollback doesn't work for me. It seems that forward_timestep_embed() got embedded before, and the new defined one did not get to work. I don't know how to fix it. I just simply copy the new funciton before the calls and looks like it works
> 
> Even after updating both `ComfyUI` and `AnimateDiff Evolved` nodes to the latest versions, is the issue still persisting?

Got resolved. Thanks

**Comment by barclayslb** [comment]
> hi [@ltdrdata](https://github.com/ltdrdata) , this issue is resolved for me. Updating AnimateDiff evolved custom node worked. Thanks.

After installing AnimateDiff evolved , and put the 3 files in comfyUI \models it works !
the three files was : mm_sd_v15_v2, mm_sdxl_v10_beta, v3_sd15_mm (.ckpt files), the link : https://huggingface.co/guoyww/animatediff/tree/main
