### ISSUE TITLE
Ngrok visit comfyUI Error

### ISSUE THREAD

**Issue by 6174** [comfyanonymous/ComfyUI#2042]
I am trying to make my comfyUI web service public to the internet.  After I started ngrok, and visit the public url, the ComfyUI Web service is responsed, but showing error. 

This is ngrok log
```shell
ngrok http https://127.0.0.1:8188
ession Status                online
Account                       xxxxx (Plan: Free)
Version                       3.4.0
Region                        Japan (jp)
Latency                       161ms
Web Interface                 http://127.0.0.1:4040
Forwarding                    https://4554-223-73-39-189.ngrok-free.app -> https://0.0.0.0:8188

Connections                   ttl     opn     rt1     rt5     p50     p90
                              2       0       0.01    0.00    0.00    0.00

HTTP Requests
-------------

GET /favicon.ico
GET /
```

This is comfyUI error log

```shell
Error handling request
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
```

My system is MacOS  14.0 (23A344)

**Comment by Sd-rep** [comment]
`Traceback (most recent call last):
  File "/home/g4you_app_dev/ComfyUI/venv/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01'
      ^`

**Comment by liuyuzhou** [comment]
I have the same problem. Ubuntu 22.04  Tencent Cloud
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/tool-install/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x02:\x01'
      ^
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/tool-install/anaconda3/envs/comfyui/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x02:\x01'
      ^

**Comment by metamountain** [comment]
me2.

**Comment by wszxdzd** [comment]
me too
