### ISSUE TITLE
issue loading unet

### ISSUE THREAD

**Issue by alenknight** [comfyanonymous/ComfyUI#2049]
after updating today, unetloader seems to be throwing this error (Was running ok with last week's updates)

<img width="752" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22153900/bd3f45f2-30f4-4e52-b9f6-8eaa1eeb55d9">

```
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-11-24 20:13:52.618546

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\AI\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\AI\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\AI\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\AI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\AI\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\AI\stable-diffusion-webui\models/ControlNet
Error:
[WinError 1314] A required privilege is not held by the client: 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'C:\\AI\\ComfyUI\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to C:\AI\ComfyUI\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals\js
Target: C:\AI\ComfyUI\ComfyUI\web\extensions\ComfyLiterals
### Loading: ComfyUI-Impact-Pack (V4.34)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
### Loading: ComfyUI-Inspire-Pack (V0.47.1)
### Loading: ComfyUI-Manager (V1.2.1)
### ComfyUI Revision: 1733 [e020ab61] | Released on '2023-11-24'
moviepy is already installed.
cv2 is already installed.
git is already installed.
zipfile is already installed.
skbuild is already installed.

[SD Prompt Reader] Node version: 1.1.0
[SD Prompt Reader] Core version: 1.3.4b2
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Torch version: 2.0.1+cu118
Comfyroll Custom Nodes: Loaded
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
DWPose: Onnxruntime with acceleration providers detected
Davemane42 Custom Nodes: Loaded
FizzleDorf Custom Nodes: Loaded
Using xformers cross attention
[tinyterraNodes] Loaded
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Efficiency Nodes: Attempting to add 'AnimatedDiff Script' Node (ComfyUI-AnimateDiff-Evolved add-on)...Success!
Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
C:\AI\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
C:\AI\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions
[Power Noise Suite]: 🦚🦚🦚 Squeaa-squee!!! 🦚🦚🦚
[Power Noise Suite]: Tamed 11 wild nodes.

[rgthree] Loaded 15 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Searge-SDXL v4.3.1 in C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 198 nodes successfully.

        "Art is the light that shines even in the darkest corners." - Unknown


Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\invert_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\invert_image_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\image_to_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\imageflip_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\histogram_equalization.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sharpness_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\image_to_contrast_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\mosaic_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\crop_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\gaussian_blur_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\vae_decode_preview.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\brightness_contrast_ally_modified.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Kohya_hiResFix.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_utility.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\brightness_contrast_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Pseudo_HDR_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\monocromatic_clip_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\gaussian_blur_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\canvas_tab
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\saturation_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Mile-High-Styler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Noise
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_restart_sampling
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\cg_custom_core
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\PowerNoiseSuite
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_NoxinNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\NodeGPT
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\clipseg.py
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.5 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.7 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
   1.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-N-Nodes
   1.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
QualityOfLifeSuit_Omar92::NSP ready
got prompt
model_type EPS
adm 0
Using xformers attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using xformers attention in VAE
missing {'cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.logit_scale', 'cond_stage_model.clip_l.text_projection'}
loaded straight to GPU
Requested to load BaseModel
Loading 1 new model
Requested to load SD1ClipModel
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:10<00:00,  1.98it/s]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 761, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 495, in load_unet
    model_config = model_detection.model_config_from_diffusers_unet(sd, unet_dtype)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_detection.py", line 297, in model_config_from_diffusers_unet
    return model_config_from_unet_config(unet_config)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_detection.py", line 150, in model_config_from_unet_config
    if model_config.matches(unet_config):
  File "C:\AI\ComfyUI\ComfyUI\comfy\supported_models_base.py", line 28, in matches
    if s.unet_config[k] != unet_config[k]:
KeyError: 'use_temporal_attention'

Prompt executed in 14.83 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 761, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 495, in load_unet
    model_config = model_detection.model_config_from_diffusers_unet(sd, unet_dtype)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_detection.py", line 297, in model_config_from_diffusers_unet
    return model_config_from_unet_config(unet_config)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_detection.py", line 150, in model_config_from_unet_config
    if model_config.matches(unet_config):
  File "C:\AI\ComfyUI\ComfyUI\comfy\supported_models_base.py", line 28, in matches
    if s.unet_config[k] != unet_config[k]:
KeyError: 'use_temporal_attention'

Prompt executed in 0.11 seconds
got prompt
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 761, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "C:\AI\ComfyUI\ComfyUI\comfy\sd.py", line 495, in load_unet
    model_config = model_detection.model_config_from_diffusers_unet(sd, unet_dtype)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_detection.py", line 297, in model_config_from_diffusers_unet
    return model_config_from_unet_config(unet_config)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_detection.py", line 150, in model_config_from_unet_config
    if model_config.matches(unet_config):
  File "C:\AI\ComfyUI\ComfyUI\comfy\supported_models_base.py", line 28, in matches
    if s.unet_config[k] != unet_config[k]:
KeyError: 'use_temporal_attention'

Prompt executed in 0.11 seconds
```

here's my unet models folder

<img width="732" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/22153900/dc6ce88a-31a7-49a2-ac02-9d9871546f50">

**Comment by comfyanonymous** [comment]
This should be fixed now.

**Comment by alenknight** [comment]
that worked.  thanks!
