### ISSUE TITLE
Is the right mouse button invalidated?

### ISSUE THREAD

**Issue by hben35096** [comfyanonymous/ComfyUI#2116]
ComfyUI Revision: 1758 [6b769bca] | Released on '2023-11-30'

Is the right mouse button invalidated?

**Comment by yinxiang5588** [comment]
I also have this question, my right mouse button is also ineffective on a blank screen.

**Comment by liulsg** [comment]
@ltdrdata 
Same mistake. This is the error message from the browser. Because I don't know how to program, I don't know if this will help
groupNode.js:1013 Uncaught ReferenceError: opts is not defined
    at LGraphCanvas.getCanvasMenuOptions (groupNode.js:1013:77)
    at LGraphCanvas.getCanvasMenuOptions (nodeTemplates.js:305:25)
    at LGraphCanvas.getCanvasMenuOptions (graphArrange.js:8:25)
    at LGraphCanvas.getCanvasMenuOptions (nodeFinder.js:25:25)
    at LGraphCanvas.getCanvasMenuOptions (workflowImage.js:591:26)
    at LGraphCanvas.processContextMenu (litegraph.core.js:13305:34)
    at LGraphCanvas.processMouseDown (litegraph.core.js:6269:10)
    at LGraphCanvas.processMouseDown (undoRedo.js:147:29)
    at LGraphCanvas.processMouseDown (app.js:878:37)

**Comment by ltdrdata** [comment]
> @ltdrdata Same mistake. This is the error message from the browser. Because I don't know how to program, I don't know if this will help groupNode.js:1013 Uncaught ReferenceError: opts is not defined at LGraphCanvas.getCanvasMenuOptions (groupNode.js:1013:77) at LGraphCanvas.getCanvasMenuOptions (nodeTemplates.js:305:25) at LGraphCanvas.getCanvasMenuOptions (graphArrange.js:8:25) at LGraphCanvas.getCanvasMenuOptions (nodeFinder.js:25:25) at LGraphCanvas.getCanvasMenuOptions (workflowImage.js:591:26) at LGraphCanvas.processContextMenu (litegraph.core.js:13305:34) at LGraphCanvas.processMouseDown (litegraph.core.js:6269:10) at LGraphCanvas.processMouseDown (undoRedo.js:147:29) at LGraphCanvas.processMouseDown (app.js:878:37)

It's an issue which is related to recent merged PR.

**Comment by ltdrdata** [comment]
Update ComfyUI. Comfy patched this.

**Comment by hben35096** [comment]
OK

**Comment by hben35096** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/139383150/ec65f759-b656-40e4-a8cc-607649cf6339)
![image](https://github.com/comfyanonymous/ComfyUI/assets/139383150/a329de5a-1cdf-467c-8962-6e9dc6db502b)

So far, everything was perfect without any problems. But...

![image](https://github.com/comfyanonymous/ComfyUI/assets/139383150/0c7fc3e0-0f0f-4a03-af46-1b84f7a1ae4d)
![image](https://github.com/comfyanonymous/ComfyUI/assets/139383150/7a6e5790-7369-43f1-a85e-3e15a0f46938)

**Comment by vivektekale** [comment]
I am having issues right clicking the mouse not opening the node menu

Comfyui - v0.3.26

Having this error in the browser

litegraph.core.js:13772 Uncaught TypeError: this.addItem is not a function
    at LiteGraph.ContextMenu.ContextMenu (litegraph.core.js:13772:18)
    at LiteGraph.ContextMenu (contextMenuFilter.js:11:24)
    at LiteGraph.ContextMenu (contextMenuHook.js:86:19)
    at new LiteGraph.ContextMenu (menu_auto_nest.js:33:44)
    at LGraphCanvas.processContextMenu (litegraph.core.js:13368:20)
    at LGraphCanvas.processMouseDown (litegraph.core.js:6295:10)
    at LGraphCanvas.processMouseDown (changeTracker.js:160:31)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.js:93:26)
    at LGraphCanvas.processMouseDown (rgthree.js:241:48)
    at LGraphCanvas.processMouseDown (app.js:1009:37)
