### ISSUE TITLE
ComfyUI has the worst API in the entire world

### ISSUE THREAD

**Issue by ashleykleynhans** [comfyanonymous/ComfyUI#2210]
Congratulations on building the worst API in the entire world.  I have never had the immense displeasure of using a REST API in my entire life before I used the horrific nightmare of a REST API offered by ComfyUI.

Please consider building a civilised REST API that does not completely suck.

**Comment by jjiikkkk** [comment]
yes they often update and change, more changes, more errors
errors come out again in command lines for launching

**Comment by jjiikkkk** [comment]
/opt/conda/bin/lt -> /opt/conda/lib/node_modules/localtunnel/bin/lt.jsmdoParallel extract 1-convert/2.
/opt/conda/lib
└── localtunnel@2.0.2 

/kaggle/working/ComfyUI
Total VRAM 15110 MB, total RAM 32110 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using pytorch cross attention
/opt/conda/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.24.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

ComfyUI finished loading, trying to launch localtunnel (if it gets stuck here localtunnel is having issues)

The password/enpoint ip for localtunnel is: 35.204.107.51
/opt/conda/lib/node_modules/localtunnel/bin/lt.js:65
(async () => {
       ^

SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:387:7)
    at startup (bootstrap_node.js:153:9)

**Comment by jjiikkkk** [comment]
very poor service

**Comment by mope81** [comment]
12:35:46.795 [Info] Self-Start ComfyUI-0 on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
12:35:46.796 [Info] Self-Start ComfyUI-0 on port 7821 had errors before shutdown:
ComfyUI-0 on port 7821 error: OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

12:35:46.810 [Error] Internal error processing T2I request: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at StableSwarmUI.Utils.Utilities.ReceiveData(WebSocket socket, Int32 maxBytes, CancellationToken limit) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/Utils/Utilities.cs:line 212
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 245
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 704
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 255

**Comment by mope81** [comment]
这怎么处理啊  有人知道么
12:35:46.795 [Info] Self-Start ComfyUI-0 on port 7821 unexpectedly exited (if something failed, change setting `LogLevel` to `Debug` to see why!)
12:35:46.796 [Info] Self-Start ComfyUI-0 on port 7821 had errors before shutdown:
ComfyUI-0 on port 7821 error: OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.

12:35:46.810 [Error] Internal error processing T2I request: System.Net.WebSockets.WebSocketException (0x80004005): The remote party closed the WebSocket connection without completing the close handshake.
   at System.Net.WebSockets.ManagedWebSocket.ThrowEOFUnexpected()
   at System.Net.WebSockets.ManagedWebSocket.EnsureBufferContainsAsync(Int32 minimumRequiredBytes, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.WebSockets.ManagedWebSocket.ReceiveAsyncPrivate[TResult](Memory`1 payloadBuffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location ---
   at StableSwarmUI.Utils.Utilities.ReceiveData(WebSocket socket, Int32 maxBytes, CancellationToken limit) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/Utils/Utilities.cs:line 212
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.AwaitJobLive(String workflow, String batchId, Action`1 takeOutput, T2IParamInput user_input, CancellationToken interrupt) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 245
   at StableSwarmUI.Builtin_ComfyUIBackend.ComfyUIAPIAbstractBackend.GenerateLive(T2IParamInput user_input, String batchId, Action`1 takeOutput) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/BuiltinExtensions/ComfyUIBackend/ComfyUIAPIAbstractBackend.cs:line 704
   at StableSwarmUI.Text2Image.T2IEngine.CreateImageTask(T2IParamInput user_input, String batchId, GenClaim claim, Action`1 output, Action`1 setError, Boolean isWS, Single backendTimeoutMin, Action`2 saveImages, Boolean canCallTools) in /Volumes/Extreme SSD/Data/Packages/StableSwarmUI/src/Text2Image/T2IEngine.cs:line 255

**Comment by hanjin66** [comment]
what about this?
Error occurred when executing CheckpointLoaderSimple:

'NoneType' object has no attribute 'lower'

  File "/home/mylinux/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mylinux/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mylinux/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mylinux/ComfyUI/nodes.py", line 518, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mylinux/ComfyUI/comfy/sd.py", line 482, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mylinux/ComfyUI/comfy/utils.py", line 14, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
       ^^^^^^^^^^
