### ISSUE TITLE
Error when running Hypertile

### ISSUE THREAD

**Issue by Davikar** [comfyanonymous/ComfyUI#2218]
Getting the following error when using the Hypertile node:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\AI\ComfyUI\ComfyUI\nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "C:\AI\ComfyUI\ComfyUI\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 711, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 617, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 556, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\k_diffusion\sampling.py", line 503, in sample_dpmpp_2s_ancestral
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 277, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 267, in forward
    return self.apply_model(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 264, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 252, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "C:\AI\ComfyUI\ComfyUI\comfy\samplers.py", line 230, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "C:\AI\ComfyUI\ComfyUI\comfy\model_base.py", line 83, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL\modules\custom_sdxl_ksampler.py", line 70, in new_unet_forward
    x0 = old_unet_forward(self, x, timesteps, context, y, control, transformer_options, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 854, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "C:\AI\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 46, in forward_timestep_embed
    x = layer(x, context, transformer_options)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\ldm\modules\attention.py", line 605, in forward
    x = block(x, context=context[i], transformer_options=transformer_options)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\AI\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\ldm\modules\attention.py", line 432, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "C:\AI\ComfyUI\ComfyUI\comfy\ldm\modules\diffusionmodules\util.py", line 190, in checkpoint
    return func(*inputs)
  File "C:\AI\ComfyUI\ComfyUI\comfy\ldm\modules\attention.py", line 471, in _forward
    n, context_attn1, value_attn1 = p(n, context_attn1, value_attn1, extra_options)
  File "C:\AI\ComfyUI\ComfyUI\comfy_extras\nodes_hypertile.py", line 55, in hypertile_in
    nh = random_divisor(h, latent_tile_size * factor, swap_size)
  File "C:\AI\ComfyUI\ComfyUI\comfy_extras\nodes_hypertile.py", line 16, in random_divisor
    idx = randint(low=0, high=len(ns) - 1, size=(1,)).item()
RuntimeError: random_ expects 'from' to be less than 'to', but got from=0 >= to=0
```
(Latest version of Comfy as of now. Python 3.10.11, Windows 11.)

**Comment by Davikar** [comment]
Well, it's quite messy...
But the important part is at the 'Basic Upscale' group:
<img width="1517" alt="image" src="https://github.com/comfyanonymous/ComfyUI/assets/8229634/e1bf8302-61e6-4a0c-ad7a-b45eba7203bf">
[Simple SDXL.json](https://github.com/comfyanonymous/ComfyUI/files/13604658/Simple.SDXL.json)

**Comment by comfyanonymous** [comment]
should be fixed now.
