### ISSUE TITLE
Another group node failure

### ISSUE THREAD

**Issue by Simn** [comfyanonymous/ComfyUI#2281]
Here's another JS failure related to group nodes:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at GroupNodeHandler.updateInnerWidgets (groupNode.js:929:63)
    at GroupNodeHandler.node.getInnerNodes (groupNode.js:674:9)
    at ComfyApp.graphToPrompt (app.js:1695:59)
    at ComfyApp.queuePrompt (app.js:1859:27)
    at HTMLButtonElement.onclick (ui.js:626:24)
```

I don't have a reproducible example yet, but maybe the stacktrace already tells you something!

cc @pythongosssss

**Comment by Simn** [comment]
Try this:

<img width="701" alt="brave_ajJUawhlL1" src="https://github.com/comfyanonymous/ComfyUI/assets/634365/49c35008-1a28-4469-a1c3-88039a26231c">

Not sure if this is specific to that node kind.
