### ISSUE TITLE
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188)

### ISSUE THREAD

**Issue by whmc76** [comfyanonymous/ComfyUI#2305]
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\main.py", line 220, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\main.py", line 124, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "E:\IMAGE\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\__init__.py", line 212, in new_start
    await site.start()
  File "E:\IMAGE\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_runner.py", line 121, in start
    self._server = await loop.create_server(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "asyncio\base_events.py", line 1525, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): 通常每个套接字地址(协议/网络地址/ 端口)只允许使用一次。

**Comment by ltdrdata** [comment]
It's because the previously run ComfyUI didn't completely shut down.

If you have ever restarted ComfyUI by pressing the `restart` button, you need to press `ctrl-c` in the terminal once again to completely shut it down. Alternatively, you can close the terminal where ComfyUI was initiated.

**Comment by whmc76** [comment]
got it thx
