### ISSUE TITLE
WinError 182 after updating ComfyUI- plea for help

### ISSUE THREAD

**Issue by Vegansaregrassfed** [comfyanonymous/ComfyUI#2345]
I'm pretty new to this but slowly learning, so treat me like I'm dumb.

nvfuser_codegen.dll is present in the directory.
How do I know what dependency and how do I fix?

Updated Comfy this morning and am now getting this:

Traceback (most recent call last):
  File "T:\Comfy\ComfyUI\main.py", line 73, in <module>
    import comfy.utils
  File "T:\Comfy\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "T:\Comfy\python_embeded\Lib\site-packages\torch\__init__.py", line 128, in <module>
    raise err
OSError: [WinError 182] The operating system cannot run %1. Error loading "T:\Comfy\python_embeded\Lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.

T:\Comfy>pause
Press any key to continue . . .

I tried uninstall torch and then reinstall. but got this (I'm probably entering this wrong)

T:\Comfy\python_embeded\Lib\site-packages>pip uninstall T:\Comfy\python_embeded\Lib\site-packages torch
ERROR: Directory 'T:\\Comfy\\python_embeded\\Lib\\site-packages' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

**Comment by Vegansaregrassfed** [comment]
I am dumb. But slowly getting smarter.

I should have run the requirements.txt
