### ISSUE TITLE
Unable to run using Python Embeddable Package

### ISSUE THREAD

**Issue by Limitex** [comfyanonymous/ComfyUI#2350]
I tried to run it using Embeddable Package to avoid conflicts with other environments.
But, the following error is output and I cannot run it.

```powershell
PS D:\Desktop\ComfyUI> python-3.10.6-embed-amd64/python.exe ComfyUI/main.py
Traceback (most recent call last):
  File "D:\Desktop\ComfyUI\ComfyUI\main.py", line 1, in <module>
    import comfy.options
ModuleNotFoundError: No module named 'comfy'
```

Also, if `import comfy.options` and `comfy.options.enable_args_parsing() `are commented out, the following error occurs

```powershell
PS D:\Desktop\ComfyUI> python-3.10.6-embed-amd64/python.exe ComfyUI/main.py
Traceback (most recent call last):
  File "D:\Desktop\ComfyUI\ComfyUI\main.py", line 6, in <module>
    import folder_paths
ModuleNotFoundError: No module named 'folder_paths'
```
Other versions could not be run.
Will this be resolved?

directory structure
```
ComfyUI
|-ComfyUI
|  |-.ci
|  |-.github
|  |- ...
|-python-3.10.6-embed-amd64
|  |-Lib
|  |-Scripts
|  |- ...
|  |-python.exe
|  |- ...
```

Python was built using the following steps

1. Download [this](https://www.python.org/ftp/python/3.10.6/python-3.10.6-embed-amd64.zip) from [official](https://www.python.org/downloads/windows/).
2. Extract to `ComfyUI/`
3. Uncomment out `import site` of `python-3.10.6-embed-amd64\python310._pth`

**Comment by nanojin** [comment]
Same issue here. Unable to resolve this issue on colab.

![image](https://github.com/comfyanonymous/ComfyUI/assets/23135397/787fba14-06d3-42a9-8fb6-4bdbbfa67f7a)

**Comment by BrandonGTS** [comment]
Found a way to solve this problem and makes comfy working (not sure it is correct way of doing it, but works)
1. In you Embedded Python Folder, find **pythonxxx._pth** file, mine is **python310._pth**
2. Add relative dir to your ComfyUI root
![image](https://github.com/comfyanonymous/ComfyUI/assets/68947199/9136d87c-4ad0-454f-a274-600986cdbac7)

And it should work now.
