### ISSUE TITLE
ERROR:root:!!! Exception during processing !!! ERROR:root:Traceback (most recent call last):

### ISSUE THREAD

**Issue by ttaaa1** [comfyanonymous/ComfyUI#2353]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\nodes.py", line 476, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\comfy\sd.py", line 444, in load_checkpoint_guess_config
    model_config = model_detection.model_config_from_unet(sd, "model.diffusion_model.", unet_dtype)
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\comfy\model_detection.py", line 157, in model_config_from_unet
    unet_config = detect_unet_config(state_dict, unet_key_prefix, dtype)
  File "D:\diannao\ComfyUI\ComfyUI-master\ComfyUI-master\comfy\model_detection.py", line 50, in detect_unet_config
    model_channels = state_dict['{}input_blocks.0.0.weight'.format(key_prefix)].shape[0]
KeyError: 'model.diffusion_model.input_blocks.0.0.weight'

**Comment by hippogamesunity** [comment]
+1

**Comment by hippogamesunity** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/7318172/d6f248dd-dbb7-40db-9345-9f3e8f8add03)
Just downloaded and executed.
