### ISSUE TITLE
Error occurred when executing KSampler:Given groups=1, weight of size [320, 5, 3, 3], expected input[32, 4, 96, 96] to have 5 channels, but got 4 channels instead

### ISSUE THREAD

**Issue by dancemanUK** [comfyanonymous/ComfyUI#2358]
Error occurred when executing KSampler:

Given groups=1, weight of size [320, 5, 3, 3], expected input[32, 4, 96, 96] to have 5 channels, but got 4 channels instead

<img width="1196" alt="wechat_20231223204913" src="https://github.com/comfyanonymous/ComfyUI/assets/1702623/899029f6-f695-49b5-95a0-d3b75acfb4a0">
[error.txt](https://github.com/comfyanonymous/ComfyUI/files/13759139/error.txt)

got prompt
[AnimateDiffEvo] - INFO - Sliding context window activated - latents passed in (64) greater than context_length 16.
[AnimateDiffEvo] - INFO - Using motion module v3_sd15_mm_old.ckpt version v3.
  0%|                                                                                                                                                  | 0/17 [00:00<?, ?it/s]
2023-12-23 21:09:44,904 - root - ERROR - !!! Exception during processing !!!
2023-12-23 21:09:44,906 - root - ERROR - Traceback (most recent call last):
  File "G:\comfyUI+AnimateDiff\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\comfyUI+AnimateDiff\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\comfyUI+AnimateDiff\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\comfyUI+AnimateDiff\ComfyUI\nodes.py", line 1299, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "G:\comfyUI+AnimateDiff\ComfyUI\nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 284, in motion_sample
    return wrap_function_to_inject_xformers_bug_info(orig_comfy_sample)(model, noise, *args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_utils.py", line 205, in wrapped_function
    return function_to_wrap(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\sample.py", line 101, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 129, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\samplers.py", line 716, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI_smZNodes\__init__.py", line 138, in sample
    return _sample(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\samplers.py", line 622, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\samplers.py", line 526, in sample
    return uni_pc.sample_unipc(model_wrap, noise, latent_image, sigmas, max_denoise=self.max_denoise(model_wrap, sigmas), extra_args=extra_args, noise_mask=denoise_mask, callback=callback, variant='bh2', disable=disable_pbar)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 892, in sample_unipc
    x = uni_pc.sample(img, timesteps=timesteps, skip_type="time_uniform", method="multistep", order=order, lower_order_final=True, callback=callback, disable_pbar=disable)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 730, in sample
    model_prev_list = [self.model_fn(x, vec_t)]
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 421, in model_fn
    return self.data_prediction_fn(x, t)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 403, in data_prediction_fn
    noise = self.noise_prediction_fn(x, t)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 397, in noise_prediction_fn
    return self.model(x, t)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 329, in model_fn
    return noise_pred_fn(x, t_continuous)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 297, in noise_pred_fn
    output = model(x, t_input, **model_kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 883, in <lambda>
    lambda input, sigma, **kwargs: predict_eps_sigma(model, input, sigma, **kwargs),
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\extra_samplers\uni_pc.py", line 858, in predict_eps_sigma
    return  (input - model(input, sigma_in, **kwargs)) / sigma
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\samplers.py", line 275, in forward
    return self.apply_model(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 876, in apply_model
    out = super().apply_model(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\samplers.py", line 272, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 634, in sliding_sampling_function
    cond, uncond = sliding_calc_cond_uncond_batch(model, cond, uncond, x, timestep, model_options)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 615, in sliding_calc_cond_uncond_batch
    sub_cond_out, sub_uncond_out = calc_cond_uncond_batch(model, sub_cond, sub_uncond, sub_x, sub_timestep, model_options)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 488, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\control\utils.py", line 411, in get_control_inject
    return self.get_control_advanced(x_noisy, t, cond, batched_number)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\control\control.py", line 310, in get_control_advanced
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\control\control_sparsectrl.py", line 56, in forward
    guided_hint = self.input_hint_block(hint, emb, context)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 62, in forward
    return forward_timestep_embed(self, *args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 111, in forward_timestep_embed
    x = layer(x)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\ComfyUI\comfy\ops.py", line 43, in forward
    return super().forward(*args, **kwargs)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "G:\comfyUI+AnimateDiff\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 5, 3, 3], expected input[32, 4, 96, 96] to have 5 channels, but got 4 channels instead

Prompt executed in 2.59 seconds

**Comment by dancemanUK** [comment]
change  animatediff controlnet model, it 's OK ,please closed  this issues. thank you!

**Comment by kane1718** [comment]
I also encountered this kind of channel asymmetry problem, how did you solve it? I can't change the model.

**Comment by kane1718** [comment]
I also came across this sort of channel asymmetry issue. How did you address it? I am unable to modify the model.

**Comment by mcmonkey4eva** [comment]
@kane1718 this is a very old issue, your situation is probably unique, please post as a new issue
