### ISSUE TITLE
Traceback error since updated the missing contents

### ISSUE THREAD

**Issue by nothingness6** [comfyanonymous/ComfyUI#2384]
Since I updated the missing contents through the manager, it shows the error and doesn't execute at all. 

'''
Traceback (most recent call last):
  File "P:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\main.py", line 224, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "P:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\main.py", line 128, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "P:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\server.py", line 617, in start
    await site.start()
  File "P:\AI_Tools\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "asyncio\base_events.py", line 1519, in create_server
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
'''

**Comment by ltdrdata** [comment]
There is ComfyUI is already running. You should terminate it before start new ComfyUI.
