### ISSUE TITLE
KSampler appears to bomb for no reason

### ISSUE THREAD

**Issue by Strontium99** [comfyanonymous/ComfyUI#2430]
Got a reoccurring issue where the KSampler bombs for no reason. No error shows in the command window, just the "Pause. Press any key to continue . . .". 

I enabled logging and this is the error it throws:
`	{
		"source": "console",
		"type": "error",
		"timestamp": "2024-01-01T16:12:41.042Z",
		"message": "TypeError\nFailed to fetch\nTypeError: Failed to fetch\n    at ComfyApi.fetchApi (http://127.0.0.1:15423/scripts/api.js:15:10)\n    at ComfyApi.getQueue (http://127.0.0.1:15423/scripts/api.js:237:27)\n    at ComfyApi.getItems (http://127.0.0.1:15423/scripts/api.js:226:16)\n    at ComfyList.load (http://127.0.0.1:15423/scripts/ui.js:449:27)\n    at ComfyList.update (http://127.0.0.1:15423/scripts/ui.js:498:15)\n    at ComfyApi.<anonymous> (http://127.0.0.1:15423/scripts/ui.js:537:15)\n    at WebSocket.<anonymous> (http://127.0.0.1:15423/scripts/api.js:77:10)\n"
	}`

Can't find a common factor to cause the issue, and have tried "Update all" from the manager.

**Comment by Strontium99** [comment]
Closing this issue as it looks like the crashes were due to a faulty graphics card.
