### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by wibur0620** [comfyanonymous/ComfyUI#2452]
** ComfyUI startup time: 2024-01-04 15:57:14.391856
** Platform: Windows
** Python version: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI\venv\Scripts\python.exe
** Log path: D:\AI\ComfyUI\comfyui.log

#######################################################################
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'D:\AI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack'
Install: pip packages for 'D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
Install: install script for 'D:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
Exception in thread Thread-1 (handle_stream):
Traceback (most recent call last):
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 90, in handle_stream
    print(prefix, msg, end="")
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
    self.sync_write(message)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 203, in sync_write
    self.last_char = message[-1]
IndexError: string index out of range
Install: pip packages for 'D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager'
Install: pip packages for 'D:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux'
Exception in thread Thread-3 (handle_stream):
Traceback (most recent call last):
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 90, in handle_stream
    print(prefix, msg, end="")
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
    self.sync_write(message)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 203, in sync_write
    self.last_char = message[-1]
IndexError: string index out of range
Exception in thread Thread-5 (handle_stream):
Traceback (most recent call last):
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 90, in handle_stream
    print(prefix, msg, end="")
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
    self.sync_write(message)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 203, in sync_write
    self.last_char = message[-1]
IndexError: string index out of range
Exception in thread Thread-7 (handle_stream):
Traceback (most recent call last):
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 90, in handle_stream
    print(prefix, msg, end="")
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
    self.sync_write(message)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 203, in sync_write
    self.last_char = message[-1]
IndexError: string index out of range
Install: install script for 'D:\AI\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation'
Exception in thread Thread-9 (handle_stream):
Traceback (most recent call last):
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "C:\Users\空灵\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 90, in handle_stream
    print(prefix, msg, end="")
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 193, in write
    self.sync_write(message)
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager\prestartup_script.py", line 203, in sync_write
    self.last_char = message[-1]
IndexError: string index out of range

**Comment by wibur0620** [comment]
After I updated everything in the plugin manager, I received this error message and currently cannot open comfyui

**Comment by wibur0620** [comment]
Python版本: 3.10.6
Traceback (most recent call last):
  File "D:\AI\ComfyUI\update.py", line 5, in <module>
    import pygit2
ModuleNotFoundError: No module named 'pygit2'
-
This will try to update pytorch and all python dependencies, if you get an error wait for pytorch/xformers to fix their stuff
You should not be running this anyways unless you really have to
-
If you just want to update normally, close this and run update_comfyui.bat instead.
-
请按任意键继续. . .
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl (2473.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 GB 2.0 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.16.2%2Bcu121-cp310-cp310-win_amd64.whl (5.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 13.9 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cu121/torchaudio-2.1.2%2Bcu121-cp310-cp310-win_amd64.whl (4.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.0/4.0 MB 9.9 MB/s eta 0:00:00
Collecting pygit2
  Downloading pygit2-1.13.3-cp310-cp310-win_amd64.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 1.1 MB/s eta 0:00:00
Collecting torchsde
  Using cached torchsde-0.2.6-py3-none-any.whl (61 kB)
Collecting einops
  Using cached einops-0.7.0-py3-none-any.whl (44 kB)
Collecting transformers>=4.25.1
  Downloading transformers-4.36.2-py3-none-any.whl (8.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.2/8.2 MB 8.1 MB/s eta 0:00:00
Collecting safetensors>=0.3.0
  Downloading safetensors-0.4.1-cp310-none-win_amd64.whl (277 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.3/277.3 kB 388.7 kB/s eta 0:00:00
Collecting aiohttp
  Downloading aiohttp-3.9.1-cp310-cp310-win_amd64.whl (364 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 364.6/364.6 kB 11.4 MB/s eta 0:00:00
Collecting pyyaml
  Using cached PyYAML-6.0.1-cp310-cp310-win_amd64.whl (145 kB)
Collecting Pillow
  Downloading pillow-10.2.0-cp310-cp310-win_amd64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 14.0 MB/s eta 0:00:00
Collecting scipy
  Using cached scipy-1.11.4-cp310-cp310-win_amd64.whl (44.1 MB)
Collecting tqdm
  Using cached tqdm-4.66.1-py3-none-any.whl (78 kB)
Collecting psutil
  Downloading psutil-5.9.7-cp37-abi3-win_amd64.whl (252 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 252.2/252.2 kB 16.1 MB/s eta 0:00:00
Collecting sympy
  Using cached https://download.pytorch.org/whl/sympy-1.12-py3-none-any.whl (5.7 MB)
Collecting fsspec
  Using cached fsspec-2023.12.2-py3-none-any.whl (168 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Collecting jinja2
  Using cached https://download.pytorch.org/whl/Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting networkx
  Using cached networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting filelock
  Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Collecting requests
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Collecting numpy
  Downloading numpy-1.26.3-cp310-cp310-win_amd64.whl (15.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.8/15.8 MB 7.7 MB/s eta 0:00:00
Collecting cffi>=1.16.0
  Using cached cffi-1.16.0-cp310-cp310-win_amd64.whl (181 kB)
Collecting trampoline>=0.1.2
  Using cached trampoline-0.1.2-py3-none-any.whl (5.2 kB)
Collecting regex!=2019.12.17
  Downloading regex-2023.12.25-cp310-cp310-win_amd64.whl (269 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 269.5/269.5 kB 1.2 MB/s eta 0:00:00
Collecting packaging>=20.0
  Using cached packaging-23.2-py3-none-any.whl (53 kB)
Collecting huggingface-hub<1.0,>=0.19.3
  Using cached huggingface_hub-0.20.1-py3-none-any.whl (330 kB)
Collecting tokenizers<0.19,>=0.14
  Downloading tokenizers-0.15.0-cp310-none-win_amd64.whl (2.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 10.0 MB/s eta 0:00:00
Collecting yarl<2.0,>=1.0
  Downloading yarl-1.9.4-cp310-cp310-win_amd64.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 325.9 kB/s eta 0:00:00
Collecting multidict<7.0,>=4.5
  Using cached multidict-6.0.4-cp310-cp310-win_amd64.whl (28 kB)
Collecting attrs>=17.3.0
  Downloading attrs-23.2.0-py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.8/60.8 kB 268.7 kB/s eta 0:00:00
Collecting aiosignal>=1.1.2
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting async-timeout<5.0,>=4.0
  Using cached async_timeout-4.0.3-py3-none-any.whl (5.7 kB)
Collecting frozenlist>=1.1.1
  Downloading frozenlist-1.4.1-cp310-cp310-win_amd64.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 2.7 MB/s eta 0:00:00
Collecting colorama
  Using cached https://download.pytorch.org/whl/colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting idna>=2.0
  Using cached idna-3.6-py3-none-any.whl (61 kB)
Collecting MarkupSafe>=2.0
  Using cached https://download.pytorch.org/whl/MarkupSafe-2.1.3-cp310-cp310-win_amd64.whl (17 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Collecting charset-normalizer<4,>=2
  Using cached charset_normalizer-3.3.2-cp310-cp310-win_amd64.whl (100 kB)
Collecting urllib3<3,>=1.21.1
  Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Collecting mpmath>=0.19
  Using cached https://download.pytorch.org/whl/mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: trampoline, mpmath, urllib3, typing-extensions, sympy, safetensors, regex, pyyaml, pycparser, psutil, Pillow, packaging, numpy, networkx, multidict, MarkupSafe, idna, fsspec, frozenlist, filelock, einops, colorama, charset-normalizer, certifi, attrs, async-timeout, yarl, tqdm, scipy, requests, jinja2, cffi, aiosignal, torch, pygit2, huggingface-hub, aiohttp, torchvision, torchsde, torchaudio, tokenizers, transformers
Successfully installed MarkupSafe-2.1.3 Pillow-10.2.0 aiohttp-3.9.1 aiosignal-1.3.1 async-timeout-4.0.3 attrs-23.2.0 certifi-2023.11.17 cffi-1.16.0 charset-normalizer-3.3.2 colorama-0.4.6 einops-0.7.0 filelock-3.13.1 frozenlist-1.4.1 fsspec-2023.12.2 huggingface-hub-0.20.1 idna-3.6 jinja2-3.1.2 mpmath-1.3.0 multidict-6.0.4 networkx-3.2.1 numpy-1.26.3 packaging-23.2 psutil-5.9.7 pycparser-2.21 pygit2-1.13.3 pyyaml-6.0.1 regex-2023.12.25 requests-2.31.0 safetensors-0.4.1 scipy-1.11.4 sympy-1.12 tokenizers-0.15.0 torch-2.1.2+cu121 torchaudio-2.1.2+cu121 torchsde-0.2.6 torchvision-0.16.2+cu121 tqdm-4.66.1 trampoline-0.1.2 transformers-4.36.2 typing-extensions-4.9.0 urllib3-2.1.0 yarl-1.9.4
WARNING: There was an error checking the latest version of pip.


--------------------------------After uninstalling and installing the venv environment again, this error still prompts--------------------------

**Comment by fuzzyfaraway** [comment]
I resolved this by replacing the _Negative Cond Placeholder (Impact Pack)_ node with an empty _Clip Text Encode_ prompt.

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/issues/287
