### ISSUE TITLE
ConnectionResetError: Cannot write to closing transport with "dreamshaperXL_turboDpmppSDE.safetensors"

### ISSUE THREAD

**Issue by Shayan-Mazahir** [comfyanonymous/ComfyUI#2463]
System Specs:
- 8 GB RAM
- Intel Core i5 5th gen
- CPU

Hi, so i was using the following checkpoint:
-  **dreamshaperXL_turboDpmppSDE.safetensors**

and got the following error:

```
Error handling request
Traceback (most recent call last):
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\comfy ui\ComfyUI_windows_portable\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\comfy ui\ComfyUI_windows_portable\ComfyUI\server.py", line 100, in websocket_handler
    await ws.prepare(request)
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_ws.py", line 153, in prepare
    payload_writer = await super().prepare(request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_response.py", line 415, in prepare
    return await self._start(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_response.py", line 423, in _start
    await self._write_headers()
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_response.py", line 503, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\http_writer.py", line 130, in write_headers
    self._write(buf)
  File "D:\User\comfy ui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\http_writer.py", line 75, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
```

i am not sure why am i getting this, i tried seeing the reasons for the error, but was not able to fine. I apologize if i have missed something. I am good in python, but not that expert.

**Comment by Akira13641** [comment]
I've started getting this exact same error just recently with all manner of checkpoints, for unclear reasons, at seemingly random time, on a fully up-to-date Comfy installation.
