### ISSUE TITLE
Issues after upgrading

### ISSUE THREAD

**Issue by sinxyz** [comfyanonymous/ComfyUI#2498]
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'configure')
TypeError: Cannot read properties of undefined (reading 'configure')
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1681:15)
    at async reader.onload (http://127.0.0.1:8188/scripts/app.js:2026:6)

**Comment by 875767531** [comment]
There may be a conflict with mixlab

**Comment by NC17z** [comment]
Same issue here... 
TypeError: Cannot read properties of undefined (reading 'configure')
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1681:15)
    at async HTMLButtonElement.onclick (http://127.0.0.1:8188/scripts/ui.js:532:7)

**Comment by QianquanChina** [comment]
> There may be a conflict with mixlab

yes,！！！！when I  disable mixlab node and node comfyui is running normally

**Comment by DieserBobby** [comment]
that was helpful for me as well

**Comment by AkoZ** [comment]
Yyeeahahahahh after 2h .. re-installing whole but not this one MIXlab things !:! ....sshhooww thank you @QianquanChina 
for short to find ez: and replace:
https://github.com/shadowcz007/comfyui-mixlab-nodes

**Comment by DaiNguyen1234** [comment]
Yep. I delete mix lab in custome_nodes and got ComfyUI back to normal.
