### ISSUE TITLE
Error after KSampler execution.

### ISSUE THREAD

**Issue by razvanab** [comfyanonymous/ComfyUI#2518]
I get this error after KSampler execution:

`Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\ComfyUI\main.py", line 241, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "H:\ComfyUI_windows_portable\ComfyUI\main.py", line 143, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "H:\ComfyUI_windows_portable\ComfyUI\server.py", line 627, in publish_loop
    await self.send(*msg)
  File "H:\ComfyUI_windows_portable\ComfyUI\server.py", line 562, in send
    await self.send_json(event, data, sid)
  File "H:\ComfyUI_windows_portable\ComfyUI\server.py", line 613, in send_json
    await send_socket_catch_exception(ws.send_json, message)
  File "H:\ComfyUI_windows_portable\ComfyUI\server.py", line 41, in send_socket_catch_exception
    await function(message)
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_ws.py", line 352, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_ws.py", line 336, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\http_websocket.py", line 644, in _send_frame
    message = await compressobj.compress(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\compression_utils.py", line 71, in compress
    async with self._compress_lock:
  File "asyncio\locks.py", line 15, in __aenter__
  File "asyncio\locks.py", line 106, in acquire
  File "asyncio\mixins.py", line 20, in _get_loop
RuntimeError: <asyncio.locks.Lock object at 0x000001E8A59BD290 [unlocked, waiters:1]> is bound to a different event loop`

**Comment by razvanab** [comment]
The problem was with an extension and not with the comfyui.
[comfyui-profiler](https://github.com/tzwm/comfyui-profiler)
