### ISSUE TITLE
ComfyUI Does not start after full installation of nodes

### ISSUE THREAD

**Issue by Bombyring** [comfyanonymous/ComfyUI#2533]
D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** Comfy Deploy Revision: f5991a1bf837cb3d84af63c8a90782acba7ceb88
** ComfyUI startup time: 2024-01-13 13:18:40.688416
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) ![Снимок экрана 2024-01-13 132931](https://github.com/comfyanonymous/ComfyUI/assets/156510084/bdd5a2c4-c5d9-4a60-8cca-e2d815966df1)
** Python executable: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-deploy\comfyui.log
Downloading SVD model: svd.safetensors...
"wget" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Downloading SVD model: svd_image_decoder.safetensors...
"wget" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Downloading SVD model: svd_xt.safetensors...
"wget" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.
Downloading SVD model: svd_xt_image_decoder.safetensors...
"wget" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

Prestartup times for custom nodes:
   0.0 seconds: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   0.0 seconds: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.0 seconds: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.0 seconds: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MagicAnimate
   0.0 seconds: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-deploy

Total VRAM 10240 MB, total RAM 32523 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\a-person-mask-generator\__init__.py", line 1, in <module>
    from .a_person_mask_generator_comfyui import APersonMaskGenerator
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\a-person-mask-generator\a_person_mask_generator_comfyui.py", line 9, in <module>
    import wget
ModuleNotFoundError: No module named 'wget'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\a-person-mask-generator module for custom nodes: No module named 'wget'
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\abg-comfyui\__init__.py", line 3, in <module>
    import onnxruntime as rt
ModuleNotFoundError: No module named 'onnxruntime'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\abg-comfyui module for custom nodes: No module named 'onnxruntime'
Total VRAM 10240 MB, total RAM 32523 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
VAE dtype: torch.bfloat16
ASTERR config loaded successfully
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\avatar-graph-comfyui\__init__.py", line 12, in <module>
    import routes
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\avatar-graph-comfyui\routes.py", line 4, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\avatar-graph-comfyui module for custom nodes: No module named 'dotenv'
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\__init__.py", line 2, in <module>
    from .bilbox_post_processing import BilboXLut, BilboXVignette
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\bilbox_post_processing.py", line 6, in <module>
    from colour.io.luts.iridas_cube import read_LUT_IridasCube, LUT3D, LUT3x1D
ModuleNotFoundError: No module named 'colour'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui module for custom nodes: No module named 'colour'
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-noise\__init__.py", line 2, in <module>
    from .hijack import NODE_CLASS_MAPPINGS as hijack_mappings
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-noise\hijack.py", line 2, in <module>
    from custom_nodes.cg_custom_core.ui_decorator import ui_signal
ModuleNotFoundError: No module named 'custom_nodes.cg_custom_core'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-noise module for custom nodes: No module named 'custom_nodes.cg_custom_core'
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap\nodes.py", line 4, in <module>
    from facexlib.detection import RetinaFace
ModuleNotFoundError: No module named 'facexlib'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap module for custom nodes: No module named 'facexlib'
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-pants\__init__.py", line 1, in <module>
    from .nodes import square_image_node, text_encode_aio
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-pants\nodes\text_encode_aio.py", line 2, in <module>
    import tomli
ModuleNotFoundError: No module named 'tomli'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-pants module for custom nodes: No module named 'tomli'
Error:
[WinError 1314] Клиент не обладает требуемыми правами: 'D:\\Моделирование\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'D:\\Моделирование\\ComfyUI_windows_portable_nvidia_cu121_or_cpu\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR\__init__.py", line 1, in <module>
    from .qr_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR\qr_nodes.py", line 2, in <module>
    import qrcode
ModuleNotFoundError: No module named 'qrcode'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR module for custom nodes: No module named 'qrcode'
Traceback (most recent call last):
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes\__init__.py", line 1, in <module>
    from .qr_validation import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes\qr_validation.py", line 3, in <module>
    from pyzbar.pyzbar import decode
ModuleNotFoundError: No module named 'pyzbar'

Cannot import D:\Моделирование\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyQR-scanning-nodes module for custom nodes: No module named 'pyzbar'
[ComfyUI-0️⃣ 2️⃣ 4️⃣ 6️⃣ ] Loaded all nodes and apis (/0246-parse).
![Снимок экрана 2024-01-13 133219](https://github.com/comfyanonymous/ComfyUI/assets/156510084/5c6e0489-0532-42b3-be8d-f38b2b1b041d)
Nvidia geforce RTX 3080 graphics card is installed
Win 11

**Comment by alexbofa** [comment]
Hello, the same problem. 

Send the name nodes from `ComfyUI\custom_nodes` to understand who is broken.

**Comment by ricardofeynman** [comment]
This may not be the issue preventing ComfyUI starting, however it would help get rid of unrelated issues if you first installed the missing modules, e.g.  pip install colour, pip install wget, etc etc. Should be easier to identify the source of your main issue.

The only issue I've encountered so far that has completely prevented ComfyUI from loading up, even when there were many similar module missing errors after new custom node installs, has been due to a package called "ComfyUI"/"ComfyUI-dist..." 

It may be unrelated, but I suggest looking in the Python site-packages folder to see if "ComfyUI"/"ComfyUI-dist..." folders exist, and if so, just remove them and then try to load ComfUI. Nothing that I could detect was broken by removing them. I still have to track down how many custom node devs have utilised this problem package. Might effect functionality for some specific nodes of theirs. 

Fingers crossed for you both that this could be a solution, and good luck finding the issue if unrelated to the mentioned packages.

**Comment by Bombyring** [comment]
Thanks for the answers.I completely removed Comfy and reinstalled it from scratch without downloading the packages.So far, everything is working at a minimum.

**Comment by Tekaiguy** [comment]
Issue seems resolved.
