### ISSUE TITLE
Encountered issues while using stable-fast

### ISSUE THREAD

**Issue by canbetry** [comfyanonymous/ComfyUI#2580]
/alidata1/soft/anaconda3/envs/myenv/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: '/alidata1/soft/anaconda3/envs/myenv/lib/python3.10/site-packages/torchvision/image.so: undefined symbol: _ZN3c104cuda9SetDeviceEi'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(
ComfyUI_stable_fast: tensorrt_node import failed.
Traceback (most recent call last):
  File "/alidata1/luoyunlong/comfyUI/custom_nodes/ComfyUI_stable_fast/__init__.py", line 26, in <module>
    from .tensorrt_node import (
  File "/alidata1/luoyunlong/comfyUI/custom_nodes/ComfyUI_stable_fast/tensorrt_node.py", line 13, in <module>
    from .module.controlnet_tensorrt import (
  File "/alidata1/luoyunlong/comfyUI/custom_nodes/ComfyUI_stable_fast/module/controlnet_tensorrt.py", line 1, in <module>
    from .tensorrt_wrapper import CallableTensorRTEngineWrapper
  File "/alidata1/luoyunlong/comfyUI/custom_nodes/ComfyUI_stable_fast/module/tensorrt_wrapper.py", line 19, in <module>
    from .tensorrt_utilities import Engine
  File "/alidata1/luoyunlong/comfyUI/custom_nodes/ComfyUI_stable_fast/module/tensorrt_utilities.py", line 73, in <module>
    class TQDMProgressMonitor(trt.IProgressMonitor):
AttributeError: module 'tensorrt' has no attribute 'IProgressMonitor'

**Comment by canbetry** [comment]
centos 7, NVIDIA T4 GPU

**Comment by canbetry** [comment]
use extension ComfyUI_stable_fast
