### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by GeLi1989** [comfyanonymous/ComfyUI#2598]
Comfyui is running . After completing the drawing, sometimes  may encounter such problems, and at this time, you can only restart the comfyui service;

How should I solve this problem?  Thanks！

log:
got prompt
Exception in thread Thread-2 (prompt_worker):
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/ComfyUI/main.py", line 111, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "/root/ComfyUI/execution.py", line 355, in execute
    recursive_output_delete_if_changed(prompt, self.old_prompt, self.outputs, x)
  File "/root/ComfyUI/execution.py", line 229, in recursive_output_delete_if_changed
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs)
  File "/root/ComfyUI/execution.py", line 28, in get_input_data
    obj = outputs[input_unique_id][output_index]
IndexError: list index out of range

Is it caused by insufficient memory or VRAM？

**Comment by WooXinyi** [comment]
same error, have you solved it?

**Comment by ltdrdata** [comment]
It seems that the phenomenon occurred when there were no outputs connected to the node where the error happened.

For instance, suppose there is a node that detects all faces in an image and outputs them as a list. If an image with no faces is inputted, this phenomenon occurs.

To avoid such issues, some nodes use tricks like outputting at least one empty image as a minimum.

**Comment by WooXinyi** [comment]
> It seems that the phenomenon occurred when there were no outputs connected to the node where the error happened.
> 
> For instance, suppose there is a node that detects all faces in an image and outputs them as a list. If an image with no faces is inputted, this phenomenon occurs.
> 
> To avoid such issues, some nodes use tricks like outputting at least one empty image as a minimum.
> 
> bottom line. You need to check the node before the one where the error occurred, not the node with the error.

Yes you're right, I found it occurred when the inputs of one node was not given.
When this phenomenon occurred, sometimes it raised execption in process, while other times it raised execption in thread. I can only restart the comfyui service when thread execption occurred. I don't know what the difference is between these two situations.
