### ISSUE TITLE
Error when starting comfyui on mac m1

### ISSUE THREAD

**Issue by Bavoch** [comfyanonymous/ComfyUI#2606]
Traceback (most recent call last):
  File "/Users/Bavoch/ComfyUI/main.py", line 73, in <module>
    import comfy.utils
  File "/Users/Bavoch/ComfyUI/comfy/utils.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

screenshot：
![CleanShot 2024-01-21 at 23 33 34](https://github.com/comfyanonymous/ComfyUI/assets/26532557/c007c562-0afe-4cc3-9f21-2d89b99f782f)

**Comment by cyLi-Tiger** [comment]
you didn't install `torch` package, you can learn use Anaconda to manage your python package

**Comment by rugovit** [comment]
If you want painless  installation  for mac  you can  use a script in  [ComfyUI-Mac-Installer Github repo](https://github.com/rugovit/ComfyUI-Mac-Installer)  I wrote because I also lost a lot of time setting up ComfyUI on Mac

**Comment by Bavoch** [comment]
> If you want painless installation for mac you can use a script in [ComfyUI-Mac-Installer Github repo](https://github.com/rugovit/ComfyUI-Mac-Installer) I wrote because I also lost a lot of time setting up ComfyUI on Mac

Thanks a lot! You just saved my life!!!

**Comment by Bavoch** [comment]
> If you want painless installation for mac you can use a script in [ComfyUI-Mac-Installer Github repo](https://github.com/rugovit/ComfyUI-Mac-Installer) I wrote because I also lost a lot of time setting up ComfyUI on Mac

I successfully ran comfyui, but the output images are blurry. How can I solve this problem?
![image](https://github.com/comfyanonymous/ComfyUI/assets/26532557/f7cf5453-915e-4955-9e34-f72553d891b6)

**Comment by rugovit** [comment]
@Bavoch  Glad to be of help! I am new to ComfyUI myself but maybe it is width and height  settings  ?
