### ISSUE TITLE
IS_CHANGED() accept True as well

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#263]
Currently this seems to only work on a image hex, from physical disk

Can this also work if it's simply returned True or Falae? So that node logic can specify it's state?

**Comment by comfyanonymous** [comment]
If you want your node to run all the time do this:
```
    @classmethod
    def IS_CHANGED(s, **kwargs):
        return float("NaN")
```

**Comment by WASasquatch** [comment]
Oh awesome! Thanks for this!

**Comment by WASasquatch** [comment]
> If you want your node to run all the time do this:
> 
> ```
>     @classmethod
>     def IS_CHANGED(s, **kwargs):
>         return float("NaN")
> ```

I am getting the following error using this code: 

```
Exception in thread Thread-1 (prompt_worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\ComfyUI_windows_portable\ComfyUI\main.py", line 43, in prompt_worker
    e.execute(item[-2], item[-1])
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 148, in execute
    recursive_output_delete_if_changed(prompt, self.old_prompt, self.outputs, x)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 97, in recursive_output_delete_if_changed
    input_data_all = get_input_data(inputs, class_def)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 21, in get_input_data
    obj = outputs[input_unique_id][output_index]
KeyError: '25'
```

**Comment by comfyanonymous** [comment]
can you give me the node code you are using it with so I can check?

**Comment by WASasquatch** [comment]
Here ya go

```python
class WAS_Debug_Number_to_Console:
    def __init__(self):
        pass

    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "number": ("NUMBER",),
                "label": ("STRING", {"default": 'Debug to Console', "multiline": False}),
            }
        }

    RETURN_TYPES = ("NUMBER",)
    OUTPUT_NODE = True
    FUNCTION = "debug_to_console"

    CATEGORY = "WAS Suite/Debug"

    def debug_to_console(self, number, label):
        if label.strip() != '':
            print(
                f'\033[34mWAS Node Suite \033[33m{label}\033[0m:\n{number}\n')
        else:
            print(
                f'\033[34mWAS Node Suite \033[33mDebug to Console\033[0m:\n{number}\n')
        return (number, )
        
    @classmethod
    def IS_CHANGED(cls, **kwargs):
        return float("NaN")
```

**Comment by comfyanonymous** [comment]
Hopefully it's fixed now: https://github.com/comfyanonymous/ComfyUI/commit/3444ffff3b892456f94c13365ab498e6971f018d

**Comment by WASasquatch** [comment]
> Hopefully it's fixed now: [3444fff](https://github.com/comfyanonymous/ComfyUI/commit/3444ffff3b892456f94c13365ab498e6971f018d)

Yep, that did it.

**Comment by WASasquatch** [comment]
Hmm, for my batch function, it doesn't seem to be working. It's always just running once:

```python
class WAS_Load_Image_Batch:
    def __init__(self):
        pass
            
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "mode": (["single_image", "incremental_image"],),
                "index": ("INT", {"default": 0, "min": 0, "max": 150000, "step": 1}),
                "label": ("STRING", {"default": 'Batch 001', "multiline": False}),
                "path": ("STRING", {"default": './ComfyUI/input/', "multiline": False}),
            },
        }

    RETURN_TYPES = ("IMAGE",)
    FUNCTION = "load_batch_images"

    CATEGORY = "WAS Suite/IO"

    def load_batch_images(self, path, index=0, mode="single_image", label='Batch 001') -> tuple[torch.Tensor] | tuple:

        if not os.path.exists(path):
            return (None, )
        fl = self.BatchImageLoader(path, label)
        if mode == 'single_image':
            image = fl.get_image_by_id(index)
        else:
            image = fl.get_next_image()
        self.image = image

        return (pil2tensor(image), )

    class BatchImageLoader:
        def __init__(self, directory_path, label):
            self.WDB = WDB
            self.image_paths = []
            self.load_images(directory_path)
            self.image_paths.sort()  # sort the image paths by name
            stored_directory_path = self.WDB.get('Batch Paths', label)
            if stored_directory_path != directory_path:
                self.index = 0
                self.WDB.insert('Batch Counters', label, 0)
                self.WDB.insert('Batch Paths', label, directory_path)
            else:
                self.index = self.WDB.get('Batch Counters', label, 0)
            self.label = label

        def load_images(self, directory_path):
            allowed_extensions = ('.jpeg', '.jpg', '.png',
                                  '.tiff', '.gif', '.bmp', '.webp')
            for file_name in os.listdir(directory_path):
                if file_name.lower().endswith(allowed_extensions):
                    image_path = os.path.join(directory_path, file_name)
                    self.image_paths.append(image_path)

        def get_image_by_id(self, image_id):
            if image_id < 0 or image_id >= len(self.image_paths):
                raise ValueError(f"\033[34mWAS NS\033[0m Error: Invalid image index `{image_id}`")
            return Image.open(self.image_paths[image_id])

        def get_next_image(self):
            if self.index >= len(self.image_paths):
                self.index = 0
            image_path = self.image_paths[self.index]
            self.index += 1
            if self.index == len(self.image_paths):
                self.index = 0
            print(f'\033[34mWAS NS \033[33m{self.label}\033[0m Index:', self.index)
            self.WDB.insert('Batch Counters', self.label, self.index)
            return Image.open(image_path)

    @classmethod
    def IS_CHANGED(cls, **kwargs):
        return float("NaN")
```
Only the first image is generated each run, and the printing of the index only runs once, as well as the database storage only making first entry and not updating count so not like it's bugged showing only first image.

**Comment by WASasquatch** [comment]
Actually never-mind, it was an error that for some reason was never being outputted to console. That's super strange.
