### ISSUE TITLE
/usr/bin/python3.10: No module named pip

### ISSUE THREAD

**Issue by azamet90** [comfyanonymous/ComfyUI#2651]
```
(venv) xxx@fedora:~/Masaüstü/stable-diffusion-webui$ sh webui.sh 

################################################################
Install script for stable-diffusion + Web UI
Tested on Debian 11 (Bullseye), Fedora 34+ and openSUSE Leap 15.4 or newer.
################################################################

################################################################
Running on xxx user
################################################################

################################################################
Repo already cloned, using it as install directory
################################################################

################################################################
python venv already activate or run without venv: /home/xxx/Masaüstü/stable-diffusion-webui/venv
################################################################

################################################################
Launching launch.py...
################################################################
Using TCMalloc: libtcmalloc_minimal.so.4
Python 3.10.13 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
Version: v1.7.0
Commit hash: cf2772fab0af5573da775e7437e6acdca424f26e
Launching Web UI with arguments: --medvram
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Style database not found: /home/xxx/Masaüstü/stable-diffusion-webui/styles.csv
ControlNet preprocessor location: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-controlnet/annotator/downloads
2024-01-28 04:50:53,292 - ControlNet - INFO - ControlNet v1.1.439
2024-01-28 04:50:53,367 - ControlNet - INFO - ControlNet v1.1.439
04:50:53 - ReActor - STATUS - Running v0.6.1-b2 on Device: CUDA
Loading weights [84d76a0328] from /home/xxx/Masaüstü/stable-diffusion-webui/models/Stable-diffusion/epicrealism_naturalSinRC1VAE.safetensors
2024-01-28 04:50:54,014 - ControlNet - INFO - ControlNet UI callback registered.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Creating model from config: /home/xxx/Masaüstü/stable-diffusion-webui/configs/v1-inference.yaml
[sd-webui-comfyui] Started callback listeners for process webui
[sd-webui-comfyui] Starting subprocess for comfyui...
Startup time: 8.3s (prepare environment: 3.0s, import torch: 1.9s, import gradio: 0.6s, setup paths: 0.8s, other imports: 0.4s, load scripts: 0.7s, create ui: 0.6s, gradio launch: 0.3s).
[ComfyUI] [sd-webui-comfyui] Setting up IPC...
[ComfyUI] [sd-webui-comfyui] Using inter-process communication strategy: File system
[ComfyUI] [sd-webui-comfyui] Started callback listeners for process comfyui
[ComfyUI] [sd-webui-comfyui] Patching ComfyUI...
Applying attention optimization: Doggettx... done.
[ComfyUI] Total VRAM 16368 MB, total RAM 31994 MB
[ComfyUI] Set vram state to: NORMAL_VRAM
[ComfyUI] Device: cuda:0 AMD Radeon RX 6900 XT : native
[ComfyUI] VAE dtype: torch.float32
[ComfyUI] Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Model loaded in 2.6s (load weights from disk: 0.7s, create model: 0.5s, apply weights to model: 0.9s, load VAE: 0.2s, calculate empty prompt: 0.3s).
[ComfyUI] [sd-webui-comfyui] Launching ComfyUI with arguments: --listen 127.0.0.1 --port 8189
[ComfyUI] ** ComfyUI startup time: 2024-01-28 04:50:56.252768
[ComfyUI] ** Platform: Linux
[ComfyUI] ** Python version: 3.10.13 (main, Dec 18 2023, 00:00:00) [GCC 13.2.1 20231205 (Red Hat 13.2.1-6)]
[ComfyUI] ** Python executable: /usr/bin/python3.10
[ComfyUI] ** Log path: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/comfyui.log
[ComfyUI] ### Loading: ComfyUI-Manager (V2.4.2)
[ComfyUI] ### ComfyUI Revision: 1934 [7f4725f6] | Released on '2024-01-27'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[ComfyUI] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
/usr/bin/python3.10: No module named pip
[ComfyUI] Traceback (most recent call last):
  File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui/__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 14103, in <module>
    if 'opencv-python' in packages() or 'opencv-python-headless' in packages():
  File "/home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui/WAS_Node_Suite.py", line 336, in packages
    return [( r.decode().split('==')[0] if not versions else r.decode() ) for r in subprocess.check_output([sys.executable, '-s', '-m', 'pip', 'freeze']).split()]
  File "/usr/lib64/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3.10', '-s', '-m', 'pip', 'freeze']' returned non-zero exit status 1.

[ComfyUI] Cannot import /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui module for custom nodes: Command '['/usr/bin/python3.10', '-s', '-m', 'pip', 'freeze']' returned non-zero exit status 1.
[ComfyUI] 
Import times for custom nodes:
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_save_image.py
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_io.py
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-Logic
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/comfyui_custom_nodes/webui_proxy_nodes.py
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
[ComfyUI]    0.0 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/stability-ComfyUI-nodes
[ComfyUI]    0.1 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/ComfyUI-Manager
[ComfyUI]    0.1 seconds (IMPORT FAILED): /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui
[ComfyUI]    0.7 seconds: /home/xxx/Masaüstü/stable-diffusion-webui/extensions/sd-webui-comfyui/ComfyUI/custom_nodes/comfyui_controlnet_aux
[ComfyUI]
[ComfyUI] Starting server

[ComfyUI] To see the GUI go to: http://127.0.0.1:8189
^CInterrupted with signal 2 in <frame at 0x564f59b4c490, file '/usr/lib64/python3.10/threading.py', line 324, code wait>
[ComfyUI] 
Stopped server
(venv) xxx@fedora:~/Masaüstü/stable-diffusion-webui$ [ComfyUI] [sd-webui-comfyui] The webui has exited, exiting comfyui.
[ComfyUI] [sd-webui-comfyui] Stopped callback listeners for process comfyui
^C
```
```
(venv) xxx@fedora:~/Masaüstü/stable-diffusion-webui$ /usr/bin/python3.10 --version
Python 3.10.13
(venv) xxx@fedora:~/Masaüstü/stable-diffusion-webui$ python3 --version
Python 3.12.1
(venv) xxx@fedora:~/Masaüstü/stable-diffusion-webui$ python --version
Python 3.10.13
(venv) xxx@fedora:~/Masaüstü/stable-diffusion-webui$ 
```

**Comment by azamet90** [comment]
this problem is solved, can be closed.
