### ISSUE TITLE
im giving up with this!

### ISSUE THREAD

**Issue by azamet90** [comfyanonymous/ComfyUI#2659]
Traceback (most recent call last):
  File "/home/xxx/Masaüstü/ComfyUI/nodes.py", line 1872, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/xxx/Masaüstü/ComfyUI/custom_nodes/ComfyUI-Manager/__init__.py", line 100, in <module>
    from git.remote import RemoteProgress
ModuleNotFoundError: No module named 'git'

was already giving some errors but this last one was the last drop makes the glass full... enough! removing this now!

**Comment by azamet90** [comment]
> This is not related AMD issue. And this issue is unrelated to ComfyUI itself; it pertains to the extension feature, ComfyUI-Manager.
> 
> The installation of ComfyUI-Manager did not occur correctly. Basically, automatic installation was set up for the first run to simplify the installation process, but it seems that automatic installation failed for unknown reasons.
> 
> It seems that the GitPython package is not installed in your ComfyUI Python environment, or the Git program is not installed correctly.

it does works on the manager side actually but having another errors. it does this problem only on this standalone version. other problems related to comfyui manager, i posted to other git page.
