### ISSUE TITLE
Can't load page ,all nodes gone!

### ISSUE THREAD

**Issue by jesenzhang** [comfyanonymous/ComfyUI#2681]
![image](https://github.com/comfyanonymous/ComfyUI/assets/7984556/e694b350-02ed-4916-9e51-ff0bfe1907e2)

ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Workspace\AI\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Workspace\AI\ComfyUI\server.py", line 424, in get_object_info
    return web.json_response(out)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_response.py", line 809, in json_response
    text = dumps(data)
           ^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable
FETCH DATA from: G:\Workspace\AI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
ERROR:aiohttp.server:Error handling request
Traceback (most recent call last):
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Workspace\AI\ComfyUI\server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "G:\Workspace\AI\ComfyUI\server.py", line 424, in get_object_info
    return web.json_response(out)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\site-packages\aiohttp\web_response.py", line 809, in json_response
    text = dumps(data)
           ^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "D:\MiniConda\envs\comfy\Lib\json\encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type builtin_function_or_method is not JSON serializable

**Comment by ltdrdata** [comment]
It seems that a specific custom node implemented incorrectly is causing the collapse of ComfyUI. Move all custom nodes in the path `ComfyUI/custom_nodes` to another dir, and gradually restore 5-10 of them at a time, examining which custom node might be problematic.

**Comment by jesenzhang** [comment]
> It seems that a specific custom node implemented incorrectly is causing the collapse of ComfyUI. Move all custom nodes in the path `ComfyUI/custom_nodes` to another dir, and gradually restore 5-10 of them at a time, examining which custom node might be problematic.

Yes, I found the problematic custom node, thanks so much.

**Comment by ltdrdata** [comment]
> > It seems that a specific custom node implemented incorrectly is causing the collapse of ComfyUI. Move all custom nodes in the path `ComfyUI/custom_nodes` to another dir, and gradually restore 5-10 of them at a time, examining which custom node might be problematic.
> 
> Yes, I found the problematic custom node, thanks so much.

What custom node made that problem?

**Comment by jesenzhang** [comment]
> > > It seems that a specific custom node implemented incorrectly is causing the collapse of ComfyUI. Move all custom nodes in the path `ComfyUI/custom_nodes` to another dir, and gradually restore 5-10 of them at a time, examining which custom node might be problematic.
> > 
> > 
> > Yes, I found the problematic custom node, thanks so much.
> 
> What custom node made that problem?

It's a custom node from a plugin, I did some modifications, and gave a wrong type to reurntypes.

**Comment by ltdrdata** [comment]
> > > > It seems that a specific custom node implemented incorrectly is causing the collapse of ComfyUI. Move all custom nodes in the path `ComfyUI/custom_nodes` to another dir, and gradually restore 5-10 of them at a time, examining which custom node might be problematic.
> > > 
> > > 
> > > Yes, I found the problematic custom node, thanks so much.
> > 
> > 
> > What custom node made that problem?
> 
> It's a custom node from a plugin, I did some modifications, and gave a wrong type to reurntypes.

Got it...
