### ISSUE TITLE
Error with HAT upscale model for certain resolutions

### ISSUE THREAD

**Issue by Acly** [comfyanonymous/ComfyUI#2726]
[XPixelGroup/HAT](https://github.com/XPixelGroup/HAT) is a great upscale model. Using it with "Upscale Image (using Model)" will raise an error for some resolutions:
```
RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (0, 12) at dimension 2 of input [1, 3, 4, 256]
```
Reproducer workflow (using 256x484 image): [upscale_HAT_256x484.json](https://github.com/comfyanonymous/ComfyUI/files/14156792/upscale_HAT_256x484.json)

<details>
<summary>Traceback</summary>

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Dev\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\comfy_extras\nodes_upscale_model.py", line 52, in upscale
    s = comfy.utils.tiled_scale(in_img, lambda a: upscale_model(a), tile_x=tile, tile_y=tile, overlap=overlap, upscale_amount=upscale_model.scale, pbar=pbar)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aclys\AppData\Roaming\Python\Python311\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\comfy\utils.py", line 418, in tiled_scale
    ps = function(s_in).to(output_device)
         ^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\comfy_extras\nodes_upscale_model.py", line 52, in <lambda>
    s = comfy.utils.tiled_scale(in_img, lambda a: upscale_model(a), tile_x=tile, tile_y=tile, overlap=overlap, upscale_amount=upscale_model.scale, pbar=pbar)
                                                  ^^^^^^^^^^^^^^^^
  File "C:\Users\aclys\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aclys\AppData\Roaming\Python\Python311\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\comfy_extras\chainner_models\architecture\HAT.py", line 1266, in forward
    x = self.check_image_size(x)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Dev\ComfyUI\comfy_extras\chainner_models\architecture\HAT.py", line 1234, in check_image_size
    x = F.pad(x, (0, mod_pad_w, 0, mod_pad_h), "reflect")
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Padding size should be less than the corresponding input dimension, but got: padding (0, 12) at dimension 2 of input [1, 3, 4, 256]
```
</details>

The issue is that the ComfyUI's tiling can create slim left-over tiles at the image border, and implementation of HAT requires a minimum size greater or equal to its window_size (16).

**Comment by comfyanonymous** [comment]
Should be fixed with: https://github.com/comfyanonymous/ComfyUI/commit/236bda26830d719843ba9b5703894297f67f6704

**Comment by Acly** [comment]
That works, thank you!
