### ISSUE TITLE
Cannot get ComfyUI to launch for manual installation; 'torch' missing error

### ISSUE THREAD

**Issue by uraniumcrystalsmaster** [comfyanonymous/ComfyUI#2752]
I tried to download Comfyui manually, but it still gives me the same error. I installed torch in the ComfyUI folder because the ComfyUI installation guide does not provide a location to install it: C:\Users\urani\ComfyUI_manual_install\ComfyUI>python main.py --force-fp16
Traceback (most recent call last):
File "C:\Users\urani\ComfyUI_manual_install\ComfyUI\main.py", line 73, in
import comfy.utils
File "C:\Users\urani\ComfyUI_manual_install\ComfyUI\comfy\utils.py", line 1, in
import torch
ModuleNotFoundError: No module named 'torch'

**Comment by ltdrdata** [comment]
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#windows

**Comment by WillianReis92** [comment]
same problem here

**Comment by cgwers** [comment]
I love ComfyUI, but this constant break/fix BSing around with torch and cuda is indicative of serious development methodology issues in this project. On average, I'm managing 3-4 days a week with a running system. The rest of that time is trying to figure out why cuda and torch are fried when I haven't added any custom modules. The reliance on git modules during startup is a hinderance to everyone trying to work with SD stuff since it breaks so damned often. 

I realize that this applies to other image AI UIs, too. So talk to them and fix this crap. You're all going to be squashed by the professionals (MS/META/GOOGLE) if you don't figure out how to make these UIs work reliably. Once they release a buy-me monolith app that generates images, you're all sunk.

**Comment by mrljdx** [comment]
same problem on macos when update the latest commit 
```
** ComfyUI startup time: 2024-05-24 19:55:24.263218
** Platform: Darwin
** Python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
** Python executable: /opt/homebrew/opt/python@3.12/bin/python3.12
** Log path: /Users/mrljdx/Workspace/Github/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /Users/mrljdx/Workspace/Github/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
  File "/Users/mrljdx/Workspace/Github/ComfyUI/main.py", line 73, in <module>
    import comfy.utils
  File "/Users/mrljdx/Workspace/Github/ComfyUI/comfy/utils.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
```

**Comment by bparlan** [comment]
Just encountered same problem, it was working a month ago tbh.

`** ComfyUI startup time: 2024-06-22 17:25:22.567353
** Platform: Darwin
** Python version: 3.9.6 (default, Nov 10 2023, 13:38:27) 
[Clang 15.0.0 (clang-1500.1.0.2.5)]
** Python executable: /Library/Developer/CommandLineTools/usr/bin/python3
** Log path: /Users/bparlan/AI/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /Users/bparlan/AI/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
  File "/Users/bparlan/AI/ComfyUI/main.py", line 73, in <module>
    import comfy.utils
  File "/Users/bparlan/AI/ComfyUI/comfy/utils.py", line 1, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
`

**Comment by Vittorio792** [comment]
Try installing conda: Look here: [](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-with-commands)

Then do this command: `conda create -n my_env python=3.11`
Then: `conda activate my_env`
Then `pip install -r requirements.txt`
Then `python main.py`

If you are on Windows you might get an error like this: "raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled"
If you do in the conda environment do `pip uninstall torch` and then `Nvidia users should install stable pytorch using this command:

```
pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
OR
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124`
```
This is going to work if you have an Nvidia GPU, otherwise follow this guide on ComfyUI repo: [](https://github.com/comfyanonymous/ComfyUI)

**Comment by leyap** [comment]
> 在 macos 上更新最新提交时出现同样的问题
> 
> ```
> ** ComfyUI startup time: 2024-05-24 19:55:24.263218
> ** Platform: Darwin
> ** Python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
> ** Python executable: /opt/homebrew/opt/python@3.12/bin/python3.12
> ** Log path: /Users/mrljdx/Workspace/Github/ComfyUI/comfyui.log
> 
> Prestartup times for custom nodes:
>    0.0 seconds: /Users/mrljdx/Workspace/Github/ComfyUI/custom_nodes/ComfyUI-Manager
> 
> Traceback (most recent call last):
>   File "/Users/mrljdx/Workspace/Github/ComfyUI/main.py", line 73, in <module>
>     import comfy.utils
>   File "/Users/mrljdx/Workspace/Github/ComfyUI/comfy/utils.py", line 1, in <module>
>     import torch
> ModuleNotFoundError: No module named 'torch'
> ```

same problem
Traceback (most recent call last):
  File "/Users/xxx/comfy-ui/ComfyUI/main.py", line 94, in <module>
    import comfy.utils
  File "/Users/xxx/comfy-ui/ComfyUI/comfy/utils.py", line 20, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

**Comment by ltdrdata** [comment]
> > 在 macos 上更新最新提交时出现同样的问题
> > 
> > ```
> > ** ComfyUI startup time: 2024-05-24 19:55:24.263218
> > ** Platform: Darwin
> > ** Python version: 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
> > ** Python executable: /opt/homebrew/opt/python@3.12/bin/python3.12
> > ** Log path: /Users/mrljdx/Workspace/Github/ComfyUI/comfyui.log
> > 
> > Prestartup times for custom nodes:
> >    0.0 seconds: /Users/mrljdx/Workspace/Github/ComfyUI/custom_nodes/ComfyUI-Manager
> > 
> > Traceback (most recent call last):
> >   File "/Users/mrljdx/Workspace/Github/ComfyUI/main.py", line 73, in <module>
> >     import comfy.utils
> >   File "/Users/mrljdx/Workspace/Github/ComfyUI/comfy/utils.py", line 1, in <module>
> >     import torch
> > ModuleNotFoundError: No module named 'torch'
> > ```
> 
> same problem
> ** ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2025-01-16 13:02:58.874812
> ** Platform: Darwin
> ** Python version: 3.13.1 (main, Dec  3 2024, 17:59:52) [Clang 16.0.0 (clang-1600.0.26.4)]
> Traceback (most recent call last):
>   File "/Users/xxx/comfy-ui/ComfyUI/main.py", line 94, in <module>
>     import comfy.utils
>   File "/Users/xxx/comfy-ui/ComfyUI/comfy/utils.py", line 20, in <module>
>     import torch
> ModuleNotFoundError: No module named 'torch'

You need to install dependencies.
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#apple-mac-silicon

**Comment by emosGambler** [comment]
For me the solution was to make sure the torch is being installed with venv enabled:

`.\venv\Scripts\Activate.ps1`

then:

`pip install torch`

If permission issues on Windows, try firstly:

`Set-ExecutionPolicy RemoteSigned -Scope CurrentUser`

and proceed again with mentioned commands.
