### ISSUE TITLE
Paperspace usage?

### ISSUE THREAD

**Issue by jayceftg** [comfyanonymous/ComfyUI#2778]
This is not a comfyUI issue, but a paperspace one, but am here to check if there's any solutions.

So I have been using comfyUI on paperspace's free servers for a while with this notebook script: https://github.com/comfyanonymous/ComfyUI/blob/master/notebooks/comfyui_colab.ipynb

However, they informed me that using cloudflare or tunneling with comfyUI there could be bannable. They say that deployment on Gradio (like automatic1111's webui) is fine.

Is there some way to do such a deployment?

**Comment by TheLastBen** [comment]
There is a dedicated ComfyUI notebook for Paperspace https://github.com/TheLastBen/fast-stable-diffusion

**Comment by jayceftg** [comment]
> There is a dedicated ComfyUI notebook for Paperspace https://github.com/TheLastBen/fast-stable-diffusion

Thanks very much, captain. It worked by creating a paperspacegradient.com official tunnel for the local port? Is it done automatically by Paperspace? I browsed through the notebook but not sure which part is related to the generation of this url?

**Comment by TheLastBen** [comment]
you run the cells down to "start comfyui" it will give you a link to the interface

**Comment by jayceftg** [comment]
> you run the cells down to "start comfyui" it will give you a link to the interface

Thanks. Yes, I got the link. However, I didn't find which one of the args or something else was related to the link. The link seems to always be the same. However, just trying to check which code did that to make sure.

**Comment by TheLastBen** [comment]
I'm not sure what you mean

**Comment by jayceftg** [comment]
> I'm not sure what you mean

Thanks. I was asking how a url like 'https://tensorboard-n5tozx0ylb.clg07azjl.paperspacegradient.com/' was generated for accessing ComfyUI on the local port? 

From your code: Args="--listen --port 6006 --preview-method auto", you run ComfyUI on the local 6006 port, which could not be accessed remotely if not for you generating 'https://tensorboard-n5tozx0ylb.clg07azjl.paperspacegradient.com/' url.

This seems like a tunnelling service provided by paperspacegradient as it's in the url? But I didn't find info about this. Maybe that is related to the 'PAPERSPACE_FQDN' variable in 'https://huggingface.co/datasets/TheLastBen/PPS/raw/main/Scripts/mainppsComfy.py'?

Could you talk a bit about what sets up the tunnel?

**Comment by TheLastBen** [comment]
it is paperspace provided tunneling service

**Comment by jayceftg** [comment]
> it is paperspace provided tunneling service

Hi, really appreciate all the previous help. However, I encounter something I couldn't solve. When using your script, it generates a url like https://tensorboard-nicxemghpy.clg07azjl.paperspacegradient.com/.

Using it (tensorboard-nicxemghpy.clg07azjl.paperspacegradient.com) with the official example API script https://github.com/comfyanonymous/ComfyUI/blob/master/script_examples/websockets_api_example.py gives an error:

Traceback (most recent call last):
  File "c:\Users\AdminJ\Desktop\proj6related\comfyapi\websockets_api_example.py", line 215, in <module>
    ws.connect("ws://{}/ws?clientId={}".format(server_address, client_id))
  File "C:\Program Files\Python310\lib\site-packages\websocket\_core.py", line 266, in connect
    self.sock, addrs = connect(
  File "C:\Program Files\Python310\lib\site-packages\websocket\_http.py", line 128, in connect
    hostname, port_from_url, resource, is_secure = parse_url(url)
  File "C:\Program Files\Python310\lib\site-packages\websocket\_url.py", line 62, in parse_url
    raise ValueError("scheme %s is invalid" % scheme)
ValueError: scheme https is invalid

So it seems although the official script is trying to use ws, the url is converted from ws:// to htts:// so the ws related code couldn't run. Have you encountered this before?

**Comment by jayceftg** [comment]
> it is paperspace provided tunneling service

Probably it's related to tunnel restrictions or something. Tried the same offical ws script with Cloudflare tunnel it's 403 error. But 127.0.0.1:port would work.
