### ISSUE TITLE
ClipTextEncodeSDXL module not working Key Error 'g'

### ISSUE THREAD

**Issue by Ignaciol0** [comfyanonymous/ComfyUI#2787]
Hello I am using a simple workflow trying out the ClipTextEncodeSDXL and when this block is running I run into this Key error.
```
KeyError: 'g'
ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_clip_sdxl.py", line 44, in encode
if len(tokens["l"]) != len(tokens["g"]):
```
I tried modifiying the source file with no luck and couldn't even get the format the tokens are passed to the tokenize function so I cannot fix it by myself.
This is the full error :
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\myuser\Documents\Ai\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\Documents\Ai\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\Documents\Ai\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\myuser\Documents\Ai\ComfyUI\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_clip_sdxl.py", line 44, in encode
    if len(tokens["l"]) != len(tokens["g"]):
                               ~~~~~~^^^^^
KeyError: 'g'
```
My graphics card is  NVIDIA GeForce RTX 4060 Laptop GPU but I don't think this is the problem my python version is Python 3.11.7

**Comment by Guillaume-Fgt** [comment]
This is probably because you are not using an SDXL model but a 1.5/2.0/cascade one. Which checkpoint did you load?

**Comment by Ignaciol0** [comment]
Well thats wright sorry
