### ISSUE TITLE
File "asyncio\proactor_events.py", line 165, in _call_connection_lost

### ISSUE THREAD

**Issue by stephantual** [comfyanonymous/ComfyUI#2815]
When you have multiple tabs open (edge/win11/all latest everything inc. comfy) -you get random:
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost when browsing other tabs, i found youtube was a good one to repeat this message.

The full dump is 
```

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

AFAIK it's non-fatal but it's certainly new - wasn't doing that as of a week ago. 

I hope this helps a bit.

**Comment by Voinay** [comment]
Same here

**Comment by yang1010x** [comment]
修改asyncio\windows_events.py文件，把
DefaultEventLoopPolicy = WindowsProactorEventLoopPolicy
修改成
DefaultEventLoopPolicy = WindowsSelectorEventLoopPolicy

**Comment by xueqing0622** [comment]
> > 修改asyncio\windows_events.py文件，把 DefaultEventLoopPolicy = WindowsProactorEventLoopPolicy 修改成 DefaultEventLoopPolicy = WindowsSelectorEventLoopPolicy
> 
> Instead of directly modifying the Python file, it is recommended to add `windows_selector_event_loop_policy=True` to `ComfyUI-Manager/config.ini`.

`ComfyUI-Manager` not have `config.ini`, and I add `config.ini` copy `windows_selector_event_loop_policy=True` in it and error still there.

**Comment by ArctiXArts** [comment]
Confirming for anyone who has the same issue, both these options work.

I've just changed the config.ini which is in ComfyUI\user\default\ComfyUI-Manager

**Comment by xueqing0622** [comment]
> Confirming for anyone who has the same issue, both these options work.
> 
> I've just changed the config.ini which is in ComfyUI\user\default\ComfyUI-Manager

thx, [ArctiXArts](https://github.com/ArctiXArts), find the path and fixed the promblem.

**Comment by geocine** [comment]
This should be stickied somewhere I just experienced this issue today

**Comment by xiaobai9009** [comment]
> > 确认给任何遇到相同问题的人，这两个选项都有效。
> > 我刚刚修改了位于 ComfyUI\user\default\ComfyUI-Manager 的 config.ini 文件。
> 
> 谢谢，[ArctiXArts](https://github.com/ArctiXArts) 找到了路径并解决了问题。

However, a new problem arises: when windows_selector_event_loop_policy is set to True, it will force the system to use the old SelectorEventLoop, which causes compatibility issues with the video preview function of ComfyUI-VideoHelperSuite, and the video preview function will fail to load.

**Comment by doubley2000** [comment]
这样改确实不报错了，但远程的预览图不能显示

**Comment by essence25** [comment]
So as of Jan/2026 is there a fix for this that does not break something else? I'm still getting these random errors on console. 
CFI v0.82.

**Comment by xueqing0622** [comment]
no config.ini which is in ComfyUI\user\default\ComfyUI-Manager now, and still same error

**Comment by Venoboy** [comment]
now it's in ComfyUI\user\ __manager

**Comment by essence25** [comment]
I finally solved this problem by suppressing the "ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host" errors from polluting the console. This does not modify main.py and survives updates.

PLEASE LET ME KNOW IF THIS WORKS FOR YOU!

in custom_nodes create folder "asyncio_quiet"
inside folder create ```__init__.py```  and place this code inside:

```
# asyncio_quiet custom node package

NODE_CLASS_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS = {}
```

then create "prestartup_script.py" and place this code inside:

```
import os

print("[asyncio_quiet] prestartup loaded")

if os.name == "nt":
    try:
        import asyncio.proactor_events as _pe

        _orig_call_connection_lost = _pe._ProactorBasePipeTransport._call_connection_lost
        _orig_del = _pe._ProactorBasePipeTransport.__del__

        def _patched_call_connection_lost(self, exc):
            try:
                return _orig_call_connection_lost(self, exc)
            except ConnectionResetError as e:
                if "forcibly closed by the remote host" in str(e):
                    return
                raise

        def _patched_del(self):
            try:
                return _orig_del(self)
            except ValueError as e:
                if "I/O operation on closed pipe" in str(e):
                    return
                raise

        _pe._ProactorBasePipeTransport._call_connection_lost = _patched_call_connection_lost
        _pe._ProactorBasePipeTransport.__del__ = _patched_del

        print("[asyncio_quiet] Windows asyncio transport noise suppression enabled")

    except Exception as e:
        print(f"[asyncio_quiet] Failed to apply patch: {e}")
```

**Comment by DaKrampus** [comment]
Thank you, thank you, and thank you! Brilliant idea, though it does not work for me as is..LOL.  because i have a german operating system.. so it wont find the string "forcibly closed...."  i changed this paragraph from:

```
        def _patched_call_connection_lost(self, exc):
            try:
                return _orig_call_connection_lost(self, exc)
            except ConnectionResetError as e:
                if "forcibly closed by the remote host" in str(e):
                    return
                raise
```

to 
```
        def _patched_call_connection_lost(self, exc):
            try:
                return _orig_call_connection_lost(self, exc)
            except ConnectionResetError:
                return
```

and for the moment everything works ok.. its loaded (thats what it says in the startup log) and i havent  had any messages yet. I'll keep you posted.  Its an elegant way of hiding the message.

**Comment by garrettashcroft1231-max** [comment]
Thanks for sharing this workaround—that actually makes a lot of sense.

**Comment by essence25** [comment]
You are welcome! glad to hear that it works!

I also did a fix for Crystools, breaks console colorization and suppresses other nodes from showing colorized output on console:
FIX: https://github.com/crystian/ComfyUI-Crystools/issues/279
More about the issue: https://github.com/crystian/ComfyUI-Crystools/issues/255

**Comment by essence25** [comment]
prestartup_script.py added green color to show at startup. 

```
import os

_GREEN = "\x1b[32m"
_RED = "\x1b[31m"
_RESET = "\x1b[0m"

def _cprint(text, color):
    print(f"{color}{text}{_RESET}")

_cprint("[asyncio_quiet] Pre-startup Loaded!", _GREEN)

if os.name == "nt":
    try:
        import asyncio.proactor_events as _pe

        _orig_call_connection_lost = _pe._ProactorBasePipeTransport._call_connection_lost
        _orig_del = _pe._ProactorBasePipeTransport.__del__

        def _patched_call_connection_lost(self, exc):
            try:
                return _orig_call_connection_lost(self, exc)
            except ConnectionResetError as e:
                if "forcibly closed by the remote host" in str(e):
                    return
                raise

        def _patched_del(self):
            try:
                return _orig_del(self)
            except ValueError as e:
                if "I/O operation on closed pipe" in str(e):
                    return
                raise

        _pe._ProactorBasePipeTransport._call_connection_lost = _patched_call_connection_lost
        _pe._ProactorBasePipeTransport.__del__ = _patched_del

        _cprint("[asyncio_quiet] Windows asyncio transport noise suppression enabled!", _GREEN)

    except Exception as e:
        _cprint(f"[asyncio_quiet] Failed to apply patch: {e}", _RED)
```
