### ISSUE TITLE
Connection issue downloading models from Huggingface

### ISSUE THREAD

**Issue by Matthewjmiller07** [comfyanonymous/ComfyUI#2825]
Virtual Environment Activated
** ComfyUI startup time: 2024-02-18 06:44:24.645565
** Platform: Darwin
** Python version: 3.11.7 | packaged by conda-forge | (main, Dec 23 2023, 14:38:07) [Clang 16.0.6 ]
** Python executable: /Users/matthewmiller/Desktop/ComfyUI/myenv/bin/python
** Log path: /Users/matthewmiller/comfyui.log
[ComfyUI-Manager] WARN: Unsafe - SSL verification bypass option is Enabled. (see ComfyUI-Manager/config.ini)

Prestartup times for custom nodes:
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 16384 MB, total RAM 16384 MB
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.1.2 with CUDA None (you have 2.2.0)
    Python  3.11.4 (you have 3.11.7)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
xformers version: 0.0.24
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
### ComfyUI Revision: 1973 [7f89cb48] | Released on '2024-02-14'
/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/transformers/utils/generic.py:309: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
/Users/matthewmiller/Desktop/ComfyUI/myenv/src/diffusers/src/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
/Users/matthewmiller/Desktop/ComfyUI/myenv/src/diffusers/src/diffusers/utils/outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
Failed to auto update `Quality of Life Suit` 
QualityOfLifeSuit_Omar92_DIR: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92

[rgthree] Loaded 33 exciting nodes.
[rgthree] Will use rgthree's optimized recursive execution.

### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V0.64)
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Total VRAM 16384 MB, total RAM 16384 MB
xformers version: 0.0.24
Forcing FP16.
Set vram state to: SHARED
Device: mps
VAE dtype: torch.float32
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfy_mtb] | INFO -> loaded 63 nodes successfuly
Loaded efficiency nodes from /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
hus' utility nodes: loaded
Patching UNetModel.forward
UNetModel.forward has been successfully patched.
### Loading: Save as Webp
Copying JS files for Workflow loading

Import times for custom nodes:
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/FreeU_Advanced
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI_hus_utils
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Saveaswebp
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/SD-Advanced-Noise
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/cg-use-everywhere
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui-previewlatent
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy-image-saver
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-PhotoMaker-Plus
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/wlsh_nodes
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/CharacterFaceSwap
   0.1 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.1 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Manager
   0.2 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui-art-venture
   0.6 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux
   3.5 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
   3.6 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb
  13.8 seconds: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-DiffusersStableCascade

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
[ERROR] An error occurred while retrieving information for the 'Load Face Swap Model (mtb)' node.
Traceback (most recent call last):
  File "/Users/matthewmiller/Desktop/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb/nodes/faceswap.py", line 69, in INPUT_TYPES
    [x.name for x in cls.get_models()],
                     ^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb/nodes/faceswap.py", line 62, in get_models
    return [x for x in models_path if x.suffix in [".onnx", ".pth"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb/nodes/faceswap.py", line 62, in <listcomp>
    return [x for x in models_path if x.suffix in [".onnx", ".pth"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/miniconda3/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matthewmiller/Desktop/ComfyUI/models/insightface'
got prompt
Error handling request
Traceback (most recent call last):
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/server.py", line 47, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/server.py", line 474, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/execution.py", line 620, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'class_type'
FETCH DATA from: /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'Load Face Swap Model (mtb)' node.
Traceback (most recent call last):
  File "/Users/matthewmiller/Desktop/ComfyUI/server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb/nodes/faceswap.py", line 69, in INPUT_TYPES
    [x.name for x in cls.get_models()],
                     ^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb/nodes/faceswap.py", line 62, in get_models
    return [x for x in models_path if x.suffix in [".onnx", ".pth"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfy_mtb/nodes/faceswap.py", line 62, in <listcomp>
    return [x for x in models_path if x.suffix in [".onnx", ".pth"]]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/miniconda3/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/matthewmiller/Desktop/ComfyUI/models/insightface'
got prompt
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
Failed to find /Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts/lllyasviel/Annotators/body_pose_model.pth.
 Downloading from huggingface.co
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/miniconda3/lib/python3.11/ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/miniconda3/lib/python3.11/ssl.py", line 1108, in _create
    self.do_handshake()
  File "/Users/matthewmiller/miniconda3/lib/python3.11/ssl.py", line 1383, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /repos/a2/11/a211ef997fa284ad67caa591ca931692f9a8a018910b18a04d9e6dff396f02e3/25a948c16078b0f08e236bda51a385d855ef4c153598947c28c0d47ed94bb746?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27body_pose_model.pth%3B+filename%3D%22body_pose_model.pth%22%3B&Expires=1708517157&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwODUxNzE1N319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9hMi8xMS9hMjExZWY5OTdmYTI4NGFkNjdjYWE1OTFjYTkzMTY5MmY5YThhMDE4OTEwYjE4YTA0ZDllNmRmZjM5NmYwMmUzLzI1YTk0OGMxNjA3OGIwZjA4ZTIzNmJkYTUxYTM4NWQ4NTVlZjRjMTUzNTk4OTQ3YzI4YzBkNDdlZDk0YmI3NDY~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=DN9pDBRMNwUfUzNia6PRs0ShSVxQqq~OLvg589z0myCqXd6IpLVhszp201kNrk3-txG~77gzhNWFumaOSnwZ7l7vMhJJ~CQi4tLhj9uLeNN0AB1uXw3oeo1TRgyu8gtLKegyt5LyNJvr7~Ia0zRLgp-0ZVttRprqRt6x6s6r~~LJnDHp37mjMvEFloeqawbtfkZfuakgNJfKxOAqbLT4gVcu9jcue~ADJM6masE49uKs2bA5vnMpkO1L5PjVl5PDasrUwFifo~-ERIQu9cgpBuZoN~NH7SwZ4GkNY6WSadJb3TNDsLIa2W6EsGZvtyb47igkIqXO~AKSJKBhWqzmHg__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/matthewmiller/Desktop/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui-art-venture/modules/controlnet/__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui-art-venture/modules/controlnet/__init__.py", line 47, in apply_preprocessor
    res = getattr(preprocessor_class(), function_name)(**preprocessor_args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux/node_wrappers/openpose.py", line 26, in estimate_pose
    model = OpenposeDetector.from_pretrained().to(model_management.get_torch_device())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/open_pose/__init__.py", line 123, in from_pretrained
    body_model_path = custom_hf_download(pretrained_model_or_path, filename, subfolder=subfolder)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/util.py", line 264, in custom_hf_download
    model_path = hf_hub_download(repo_id=pretrained_model_or_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/huggingface_hub/utils/_validators.py", line 118, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 1457, in hf_hub_download
    http_get(
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 451, in http_get
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/huggingface_hub/file_download.py", line 408, in _request_wrapper
    response = get_session().request(method=method, url=url, **params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/huggingface_hub/utils/_http.py", line 67, in send
    return super().send(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/matthewmiller/Desktop/ComfyUI/myenv/lib/python3.11/site-packages/requests/adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: (MaxRetryError("HTTPSConnectionPool(host='cdn-lfs.huggingface.co', port=443): Max retries exceeded with url: /repos/a2/11/a211ef997fa284ad67caa591ca931692f9a8a018910b18a04d9e6dff396f02e3/25a948c16078b0f08e236bda51a385d855ef4c153598947c28c0d47ed94bb746?response-content-disposition=attachment%3B+filename*%3DUTF-8%27%27body_pose_model.pth%3B+filename%3D%22body_pose_model.pth%22%3B&Expires=1708517157&Policy=eyJTdGF0ZW1lbnQiOlt7IkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTcwODUxNzE1N319LCJSZXNvdXJjZSI6Imh0dHBzOi8vY2RuLWxmcy5odWdnaW5nZmFjZS5jby9yZXBvcy9hMi8xMS9hMjExZWY5OTdmYTI4NGFkNjdjYWE1OTFjYTkzMTY5MmY5YThhMDE4OTEwYjE4YTA0ZDllNmRmZjM5NmYwMmUzLzI1YTk0OGMxNjA3OGIwZjA4ZTIzNmJkYTUxYTM4NWQ4NTVlZjRjMTUzNTk4OTQ3YzI4YzBkNDdlZDk0YmI3NDY~cmVzcG9uc2UtY29udGVudC1kaXNwb3NpdGlvbj0qIn1dfQ__&Signature=DN9pDBRMNwUfUzNia6PRs0ShSVxQqq~OLvg589z0myCqXd6IpLVhszp201kNrk3-txG~77gzhNWFumaOSnwZ7l7vMhJJ~CQi4tLhj9uLeNN0AB1uXw3oeo1TRgyu8gtLKegyt5LyNJvr7~Ia0zRLgp-0ZVttRprqRt6x6s6r~~LJnDHp37mjMvEFloeqawbtfkZfuakgNJfKxOAqbLT4gVcu9jcue~ADJM6masE49uKs2bA5vnMpkO1L5PjVl5PDasrUwFifo~-ERIQu9cgpBuZoN~NH7SwZ4GkNY6WSadJb3TNDsLIa2W6EsGZvtyb47igkIqXO~AKSJKBhWqzmHg__&Key-Pair-Id=KVTP0A1DKRTAX (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1006)')))"), '(Request ID: 381ef927-4363-4cd5-8fdb-b858f6be9eef)')

Prompt executed in 0.81 seconds

**Comment by corvo4791** [comment]
Same issue here. Any devs online?
Thanks.
