### ISSUE TITLE
TypeError: unet_dtype() got an unexpected keyword argument 'supported_dtypes'

### ISSUE THREAD

**Issue by chris1024hub** [comfyanonymous/ComfyUI#2830]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "L:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 552, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "L:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 467, in load_checkpoint_guess_config
    unet_dtype = model_management.unet_dtype(model_params=parameters, supported_dtypes=model_config.supported_inference_dtypes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unet_dtype() got an unexpected keyword argument 'supported_dtypes'

Prompt executed in 0.54 seconds

after update got this erro ,same like all model willl stop at the model loading stage

**Comment by shiimizu** [comment]
https://github.com/comfyanonymous/ComfyUI/issues/2806

**Comment by shiimizu** [comment]
Duplicate of https://github.com/comfyanonymous/ComfyUI/issues/2806
