### ISSUE TITLE
CUDA error: invalid configuration argument within the KSampler of the SVD workflow.

### ISSUE THREAD

**Issue by gin-melodic** [comfyanonymous/ComfyUI#2836]
I encountered an error while using the SVD example (https://comfyanonymous.github.io/ComfyUI_examples/video/). Based on the error message, I carefully checked the CUDA configuration and uninstalled all custom nodes, but the problem still persists.

![image](https://github.com/comfyanonymous/ComfyUI/assets/4485145/fa738a65-7c28-485c-94a1-4990eb9f24cb)
> This workflow simplifies the image generation part to quickly reproduce the issue.

## Error stack trace

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/sd/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/sd/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/sd/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/sd/ComfyUI/nodes.py", line 1380, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/home/sd/ComfyUI/nodes.py", line 1350, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/home/sd/ComfyUI/comfy/sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 713, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 618, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 557, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 281, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 271, in forward
    return self.apply_model(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 268, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 248, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "/home/sd/ComfyUI/comfy/samplers.py", line 222, in calc_cond_uncond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "/home/sd/ComfyUI/comfy/model_base.py", line 91, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 847, in forward
    h = forward_timestep_embed(module, h, emb, context, transformer_options, time_context=time_context, num_video_frames=num_video_frames, image_only_indicator=image_only_indicator)
  File "/home/sd/ComfyUI/comfy/ldm/modules/diffusionmodules/openaimodel.py", line 39, in forward_timestep_embed
    x = layer(x, context, time_context, num_video_frames, image_only_indicator, transformer_options)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/ldm/modules/attention.py", line 785, in forward
    x_mix = mix_block(x_mix, context=time_context) #TODO: transformer_options
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/ldm/modules/attention.py", line 459, in forward
    return checkpoint(self._forward, (x, context, transformer_options), self.parameters(), self.checkpoint)
  File "/home/sd/ComfyUI/comfy/ldm/modules/diffusionmodules/util.py", line 189, in checkpoint
    return func(*inputs)
  File "/home/sd/ComfyUI/comfy/ldm/modules/attention.py", line 519, in _forward
    n = self.attn1(n, context=context_attn1, value=value_attn1)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/sd/ComfyUI/comfy/ldm/modules/attention.py", line 411, in forward
    out = optimized_attention(q, k, v, self.heads)
  File "/home/sd/ComfyUI/comfy/ldm/modules/attention.py", line 326, in attention_xformers
    out = xformers.ops.memory_efficient_attention(q, k, v, attn_bias=mask)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 192, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 290, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 310, in _memory_efficient_attention_forward
    out, *_ = op.apply(inp, needs_gradient=False)
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/xformers/ops/fmha/cutlass.py", line 175, in apply
    out, lse, rng_seed, rng_offset = cls.OPERATOR(
  File "/home/sd/anaconda3/envs/sd/lib/python3.10/site-packages/torch/_ops.py", line 502, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: CUDA error: invalid configuration argument
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

## Associated Version Check

```shell
$ nvidia-smi
Mon Feb 19 08:07:32 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla V100S-PCIE-32GB          On  | 00000000:03:00.0 Off |                  Off |
| N/A   33C    P0              27W / 250W |      5MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla V100S-PCIE-32GB          On  | 00000000:0B:00.0 Off |                  Off |
| N/A   36C    P0              38W / 250W |   5230MiB / 32768MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1036      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A      1036      G   /usr/lib/xorg/Xorg                            4MiB |
|    1   N/A  N/A     31795      C   python                                     5222MiB |
+---------------------------------------------------------------------------------------+
```

```shell
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

$ python
Python 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.0.1+cu117
>>> print(torch.version.cuda)
11.7
```

Currently, only the KSampler in the SVD process is affected. The KSampler for generating images is working fine. Additionally, I've tried using both CUDA 12.2 and 11.7 versions, but the issue persists. Has anyone else encountered the same problem?

**Comment by OPeixe** [comment]
I have the same problem in windows, identical outputs since using pytorch==2.2.0+cu121, the solution is to avoid xformres (--disable-xformers), I'm currently launching the server with --use-pytorch-cross-attention and the error is not anymore, but I feel I'm using more VRAM and in upscaled latentes it takes longer.

**Comment by gin-melodic** [comment]
> I have the same problem in windows, identical outputs since using pytorch==2.2.0+cu121, the solution is to avoid xformres (--disable-xformers), I'm currently launching the server with --use-pytorch-cross-attention and the error is not anymore, but I feel I'm using more VRAM and in upscaled latentes it takes longer.

Thank you for your suggestion! The workflow for SVD is currently functioning properly. I tried --disable-xformers and --use-pytorch-cross-attention; either of these two flags on their own in the command can make SVD work properly. It might be that my V100 does not support xformers under certain conditions.

**Comment by tonynoce** [comment]
Hi ! This last weekend upgraded my card to a 3090 and having the same problem, will try the fix mentioned by Opeixe and come back

**Comment by tonynoce** [comment]
Yup, disabling x-formers fixed this
