### ISSUE TITLE
(Stable Cascade)  The controlnet is not working, an error occurred on the 【Apply Controlnet】node

### ISSUE THREAD

**Issue by daidongzhe** [comfyanonymous/ComfyUI#2884]
【Apply Controlnet】node  &  canny controlnet model  

error info:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 814, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent))
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by brundlesprout** [comment]
check your unet loader, first should be stage_b, second should be stage_c

**Comment by MoonMoon82** [comment]
@brundlesprout The controlnet node should be placed into the positive conditioning of the stage_c sampler. But exactly this produces this error.
I already posted it in https://github.com/comfyanonymous/ComfyUI/issues/2785 but nobody cared yet :(

**Comment by axel578** [comment]
It would increase stable cascade usage a lot if control net model was supported

**Comment by Matthaeus07** [comment]
This bugs me out too. If someone wants the (not working) workflow [here](https://github.com/comfyanonymous/ComfyUI/files/14470918/workflow.json). 
However, this is how it should work according to the documentation.

**Comment by SSA4** [comment]
Still waiting for a fix of this error

**Comment by MoonMoon82** [comment]
At least the canny controlnet works successfully!

**Comment by Matthaeus07** [comment]
> At least the canny controlnet works successfully!

How did you get it to work? May you share your workflow?

**Comment by MoonMoon82** [comment]
@Matthaeus07 Using canny controlnet works just like any other model. Just make sure that it is only connected to stage_c sampler.

SuperResolution also works now!
But to use it, it's neccessary to use the new "StableCascade_SuperResolutionControlnet" node as kind of preprocessor and connect stage_c and stage_b latent outputs to each sampler.

**Comment by Tener** [comment]
Would any of you mind sharing example workflow for controlnet + stable cascade?

**Comment by Matthaeus07** [comment]
Just got it working. Here is the [workflow.json](https://github.com/comfyanonymous/ComfyUI/files/14552014/workflow.json)

**Comment by EtienneExalgo** [comment]
> Just got it working. Here is the [sc-canny-workflow.json](https://github.com/comfyanonymous/ComfyUI/files/14552072/sc-canny-workflow.json)

Can you explain a bit more ? Your workflow fires the same error for me : "Error occurred when executing ControlNetApplyAdvanced:

'NoneType' object has no attribute 'copy'"

**Comment by Matthaeus07** [comment]
> > Just got it working. Here is the [sc-canny-workflow.json](https://github.com/comfyanonymous/ComfyUI/files/14552072/sc-canny-workflow.json)
> 
> Hi Mattaeus07, thanks !
> 
> Can you explain a bit more ? Your workflow fires the same error for me : "Error occurred when executing ControlNetApplyAdvanced:
> 
> 'NoneType' object has no attribute 'copy'"


I am sorry that it does not work for you. Try updating ComfyUI. I hope that will fix the problem for you!

**Comment by defensezone** [comment]
> > > Just got it working. Here is the [sc-canny-workflow.json](https://github.com/comfyanonymous/ComfyUI/files/14552072/sc-canny-workflow.json)
> > 
> > 
> > Hi Mattaeus07, thanks !
> > Can you explain a bit more ? Your workflow fires the same error for me : "Error occurred when executing ControlNetApplyAdvanced:
> > 'NoneType' object has no attribute 'copy'"
> 
> I am sorry that it does not work for you. Try updating ComfyUI. I hope that will fix the problem for you!

canny works, but super_resolution gives an error:
`Error occurred when executing ControlNetApply:

'NoneType' object has no attribute 'copy'

File "w:\GIT\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "w:\GIT\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "w:\GIT\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "w:\GIT\ComfyUI_windows_portable\ComfyUI\nodes.py", line 770, in apply_controlnet
c_net = control_net.copy().set_cond_hint(control_hint, strength)
^^^^^^^^^^^^^^^^`

**Comment by rivo** [comment]
>> 'NoneType' object has no attribute 'copy'

> Try updating ComfyUI. I hope that will fix the problem for you!

@EtienneExalgo I had exactly the same problem and updating ComfyUI to the latest version fixed it for me.
