### ISSUE TITLE
new stable casecade model on Comfyui Error

### ISSUE THREAD

**Issue by qingyuan18** [comfyanonymous/ComfyUI#2920]
upgrade to the latest Comfyui and import stableai sample casecade workflow, and the unet load throws error: 

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/ubuntu/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/ubuntu/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/ubuntu/ComfyUI/nodes.py", line 838, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "/home/ubuntu/ComfyUI/comfy/sd.py", line 596, in load_unet
    model = load_unet_state_dict(sd)
  File "/home/ubuntu/ComfyUI/comfy/sd.py", line 583, in load_unet_state_dict
    unet_dtype = model_management.unet_dtype(model_params=parameters, supported_dtypes=model_config.supported_inference_dtypes)
TypeError: unet_dtype() got an unexpected keyword argument 'supported_dtypes'

**Comment by shiimizu** [comment]
update all your custom nodes

**Comment by shiimizu** [comment]
Update your custom nodes.

**Comment by qingyuan18** [comment]
@shiimizu thanks for your quick response
but we are using default node within comfyui(checkpoint load), there is no new customer nodes import 

is there anything missing?

Thanks
