### ISSUE TITLE
Comfy Server accidently stopped

### ISSUE THREAD

**Issue by legendxcheng** [comfyanonymous/ComfyUI#2968]
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\main.py", line 246, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "asyncio\base_events.py", line 653, in run_until_complete
  File "D:\ComfyUI\ComfyUI\main.py", line 148, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "D:\ComfyUI\ComfyUI\server.py", line 627, in publish_loop
    await self.send(*msg)
  File "D:\ComfyUI\ComfyUI\server.py", line 558, in send
    await self.send_image(data, sid=sid)
  File "D:\ComfyUI\ComfyUI\server.py", line 595, in send_image
    await self.send_bytes(BinaryEventTypes.PREVIEW_IMAGE, preview_bytes, sid=sid)
  File "D:\ComfyUI\ComfyUI\server.py", line 603, in send_bytes
    await send_socket_catch_exception(ws.send_bytes, message)
  File "D:\ComfyUI\ComfyUI\server.py", line 41, in send_socket_catch_exception
    await function(message)
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_ws.py", line 315, in send_bytes
    await self._writer.send(data, binary=True, compress=compress)
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\http_websocket.py", line 688, in send
    await self._send_frame(message, WSMsgType.BINARY, compress)
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\http_websocket.py", line 659, in _send_frame
    await self.protocol._drain_helper()
  File "D:\ComfyUI\python_embeded\Lib\site-packages\aiohttp\base_protocol.py", line 90, in _drain_helper
    await asyncio.shield(waiter)
  File "asyncio\proactor_events.py", line 401, in _loop_writing
  File "asyncio\windows_events.py", line 566, in send
ConnectionAbortedError: [WinError 10053] 你的主机中的软件中止了一个已建立的连接。

What's wrong?
I was just running workflows in api mode.

**Comment by zhaowtVincent** [comment]
same error

**Comment by aiXia121** [comment]
more details

**Comment by maweiqiang1978** [comment]
File "asyncio\base_events.py", line 1227, in sendfile
  File "asyncio\proactor_events.py", line 768, in _sendfile_native
  File "asyncio\base_events.py", line 914, in sock_sendfile
  File "asyncio\proactor_events.py", line 756, in _sock_sendfile_native
  File "asyncio\windows_events.py", line 803, in _poll
  File "asyncio\windows_events.py", line 462, in finish_socket_func
PermissionError: [WinError 22] 设备不识别此命令。


me too
