### ISSUE TITLE
Stable Cascade Control Net still not implemented :/

### ISSUE THREAD

**Issue by axel578** [comfyanonymous/ComfyUI#2971]
Control is what's making a model usable for strict image generation, sadly its not implemented yet in comfy ui :

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
File "E:__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "E:__ai_env\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 814, in apply_controlnet
c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent))
^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

**Comment by felipesilvame** [comment]
What controlnet are you using?
Because stable cascade implemented `canny`, `inpaint`, and `super_resolution` [from here](https://huggingface.co/stabilityai/stable-cascade/tree/main/controlnet)

I created a simple workflow with the models and works ok (but using almost my 12GB VRAM)
![image](https://github.com/comfyanonymous/ComfyUI/assets/20867306/b43534b3-0296-4897-9c53-4b3faddc4fba)


And also commented in #2984 where I downloaded the models

Workflow can be downloaded (here)[https://gist.github.com/felipesilvame/12cbf43fa1e6d10baef54772549b37cb]

Hope it works! 🧑‍💻😊

**Comment by defensezone** [comment]
> What controlnet are you using? Because stable cascade implemented `canny`, `inpaint`, and `super_resolution` [from here](https://huggingface.co/stabilityai/stable-cascade/tree/main/controlnet)
> 
> I created a simple workflow with the models and works ok (but using almost my 12GB VRAM) ![image](https://private-user-images.githubusercontent.com/20867306/310516485-b43534b3-0296-4897-9c53-4b3faddc4fba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDU1NzMsIm5iZiI6MTcwOTc0NTI3MywicGF0aCI6Ii8yMDg2NzMwNi8zMTA1MTY0ODUtYjQzNTM0YjMtMDI5Ni00ODk3LTljNTMtNGIzZmFkZGM0ZmJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE3MTQzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyZmFjYWI3MTRkNDMyNTM1Mzg1MzZmNjE5YTliYjQ3NmY0NGUwMTRlOGM0ZjJmYzhlYjM3NWQyOTNhNTFhODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4L5xnPh7pep9YEAkFhHPdexD_GerC2vHdKlmjG9qnrQ)
> 
> And also commented in #2984 where I downloaded the models
> 
> Workflow can be downloaded [here](https://gist.github.com/felipesilvame/12cbf43fa1e6d10baef54772549b37cb)
> 
> Hope it works! 🧑‍💻😊

canny works, but super_resolution gives an error:
`Error occurred when executing ControlNetApply:

'NoneType' object has no attribute 'copy'

File "w:\GIT\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "w:\GIT\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "w:\GIT\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "w:\GIT\ComfyUI_windows_portable\ComfyUI\nodes.py", line 770, in apply_controlnet
c_net = control_net.copy().set_cond_hint(control_hint, strength)
^^^^^^^^^^^^^^^^`

**Comment by earthstorm86** [comment]
Yeah same here, very interested to see SuperResolution working please.
