### ISSUE TITLE
whenever i import workflow,it shows     comfyui_commit_hash = launcher_json["snapshot_json"]["comfyui"] KeyError: 'snapshot_json'

### ISSUE THREAD

**Issue by harbinman** [comfyanonymous/ComfyUI#2976]
ERROR in app: Exception on /api/import_project [POST]
Traceback (most recent call last):
  File "/comfyui-launcher/venv/lib/python3.10/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/comfyui-launcher/venv/lib/python3.10/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/comfyui-launcher/venv/lib/python3.10/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/comfyui-launcher/venv/lib/python3.10/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/comfyui-launcher/server/server.py", line 150, in import_project
    create_comfyui_project(
  File "/comfyui-launcher/server/utils.py", line 433, in create_comfyui_project
    comfyui_commit_hash = launcher_json["snapshot_json"]["comfyui"]
KeyError: 'snapshot_json'

**Comment by ltdrdata** [comment]
This issue should be reported to here:
https://github.com/ComfyWorkflows/ComfyUI-Launcher/issues
