### ISSUE TITLE
After last update imme

### ISSUE THREAD

**Issue by cerarslan** [comfyanonymous/ComfyUI#2998]
After the last update, it switches off instantly. I can't see the error in the terminal window, and when I say with cpu, I get the following error and I think it's the same; 

Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\main.py", line 76, in <module>
    import execution
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 7, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\cascade\stage_c_coder.py", line 19, in <module>
    import torchvision
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\__init__.py", line 1, in <module>
    from ._register_onnx_ops import _register_custom_op
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\_register_onnx_ops.py", line 5, in <module>
    from torch.onnx import symbolic_opset11 as opset11
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\__init__.py", line 46, in <module>
    from ._internal.exporter import (  # usort:skip. needs to be last to avoid circular import
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\_internal\exporter.py", line 44, in <module>
    from torch.onnx._internal.fx import (
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\_internal\fx\__init__.py", line 1, in <module>
    from .patcher import ONNXTorchPatcher
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\onnx\_internal\fx\patcher.py", line 11, in <module>
    import transformers  # type: ignore[import]
    ^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\__init__.py", line 18, in <module>
    from huggingface_hub import get_full_repo_name  # for backward compatibility
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1229, in _handle_fromlist
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py", line 370, in __getattr__
    submod = importlib.import_module(submod_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\hf_api.py", line 62, in <module>
    from ._inference_endpoints import InferenceEndpoint, InferenceEndpointType
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\_inference_endpoints.py", line 7, in <module>
    from .inference._client import InferenceClient
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\inference\_client.py", line 56, in <module>
    from huggingface_hub.inference._common import (
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\inference\_common.py", line 51, in <module>
    from ._text_generation import TextGenerationStreamResponse, _parse_text_generation_error
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\inference\_text_generation.py", line 59, in <module>
    @dataclass
     ^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\dataclasses.py", line 250, in dataclass
    return create_dataclass(_cls)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\dataclasses.py", line 241, in create_dataclass
    pydantic_complete = _pydantic_dataclasses.complete_dataclass(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_dataclasses.py", line 154, in complete_dataclass
    schema = gen_schema.generate_schema(cls, from_dunder_get_core_schema=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 499, in generate_schema
    schema = self._generate_schema(obj)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 737, in _generate_schema
    schema = self._post_process_generated_schema(self._generate_schema_inner(obj))
                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 764, in _generate_schema_inner
    return self.match_type(obj)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 838, in match_type
    return self._dataclass_schema(obj, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1487, in _dataclass_schema
    args = sorted(
           ^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 1488, in <genexpr>
    (self._generate_dc_field_schema(k, v, decorators) for k, v in fields.items()),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pydantic\_internal\_generate_schema.py", line 941, in _generate_dc_field_schema
    return core_schema.dataclass_field(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dataclass_field() got an unexpected keyword argument 'init'

C:\ComfyUI_windows_portable>pause
Press any key to continue . . .

**Comment by ltdrdata** [comment]
It seems that the versions of the pip package `transformers` are not compatible. How did you update them?

**Comment by cerarslan** [comment]
> It seems that the versions of the pip package `transformers` are not compatible. How did you update ComfyUI?

Hello sir, and thanks for replying. I updated the manager

**Comment by ltdrdata** [comment]
Try this.

```
C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U transformers
```

**Comment by cerarslan** [comment]
> Try this.
> 
> ```
> C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install -U transformers
> ```

It didn't work sir, but I solved my problem with a clean install. Although I'm not sure, I think the problem was caused by ComfyUI-Inference-Core-Nodes. Btw I learn a lot from you. Thank you for all your hard work ^^

**Comment by Gustav85** [comment]
i installed inference core node too and got this same error
