### ISSUE TITLE
random crashes since last update

### ISSUE THREAD

**Issue by vicentecarro** [comfyanonymous/ComfyUI#2999]
Ubuntu 23.10. Since last update of comfyui it randomly crashes when generating the images. I always can see the same message in the terminal:
Prompt executed in 63.15 seconds
Traceback (most recent call last):
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/main.py", line 253, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/main.py", line 148, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/server.py", line 627, in publish_loop
    await self.send(*msg)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/server.py", line 562, in send
    await self.send_json(event, data, sid)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/server.py", line 615, in send_json
    await send_socket_catch_exception(self.sockets[sid].send_json, message)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/server.py", line 41, in send_socket_catch_exception
    await function(message)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/web_ws.py", line 351, in send_json
    await self.send_str(dumps(data), compress=compress)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/web_ws.py", line 335, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/http_websocket.py", line 644, in _send_frame
    message = await compressobj.compress(message)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/vicente/Samsung870VQO1TB/comfyui/ComfyUI/venv/lib/python3.11/site-packages/aiohttp/compression_utils.py", line 71, in compress
    async with self._compress_lock:
  File "/usr/lib/python3.11/asyncio/locks.py", line 15, in __aenter__
    await self.acquire()
  File "/usr/lib/python3.11/asyncio/locks.py", line 106, in acquire
    fut = self._get_loop().create_future()
          ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/mixins.py", line 20, in _get_loop
    raise RuntimeError(f'{self!r} is bound to a different event loop')
RuntimeError: <asyncio.locks.Lock object at 0x7426ab643690 [unlocked, waiters:1]> is bound to a different event loop

After the crash I restart comfyui try the same workflow and most times it works fine. This happened with multiple differnt workflows. Also the first time it happened it was so bad that it rejected generating anymore images and finally had to reboot my computer, then it got fine (for a while). 
Frequency wise I'm not sure, maybe once every hour of intense usage? Especially if I set a batch of 100 generations and go. When I'm back it may did 5 or 15 images and it crashed.

**Comment by ltdrdata** [comment]
It appears to be a race condition issue. It could be a phenomenon caused by the installation of certain custom nodes. For now, the only option may be to remove some custom nodes and test in that form.

Especially if the occurrence is so random, it's a very challenging problem.

**Comment by vicentecarro** [comment]
This is the list of custom nodes I have. Coincidentally I reinstalled the whole comfyui a couple of days ago. And no, I didn't have the problem before reinstalling fresh. 

1	Dr.Lt.Data	 [**ComfyUI-Manager**](https://github.com/ltdrdata/ComfyUI-Manager)
22	Davemane42	 [**Visual Area Conditioning / Latent composition**](https://github.com/Davemane42/ComfyUI_Dave_CustomNode)
59	pythongosssss	 [**pythongosssss/ComfyUI-Custom-Scripts**](https://github.com/pythongosssss/ComfyUI-Custom-Scripts)
127	Kosinkadink	 [**AnimateDiff Evolved**](https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved)
128	Kosinkadink	 [**ComfyUI-VideoHelperSuite**](https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite)
154	Extraltodeus	 [**ComfyUI-AutomaticCFG**](https://github.com/Extraltodeus/ComfyUI-AutomaticCFG)
313	Danand	 [**ComfyUI-ComfyCouple**](https://github.com/Danand/ComfyUI-ComfyCouple)
355	11cafe	 [**ComfyUI Workspace Manager - Comfyspace**](https://github.com/11cafe/comfyui-workspace-manager)
401	jitcoder	 [**LoraInfo**](https://github.com/jitcoder/lora-info)
452	tzwm	 [**ComfyUI Profiler**](https://github.com/tzwm/comfyui-profiler)
572	huchenlei	 [**ComfyUI-layerdiffusion**](https://github.com/huchenlei/ComfyUI-layerdiffusion)
592	ailex000	 [**Image Gallery**](https://github.com/ailex000/ComfyUI-Extensions)

I think that's a pretty safe and common list, right? Anything 'sus' there? 
I have ComfyUI Workspace Manager - Comfyspace in Beta version, also from a couple of days ago, as I'm helping them to QA it. I'll let them know about this, just in case. I cannot go back to their main just yet, as the changes where destructive (if I understood it right).

**Comment by vicentecarro** [comment]
It got solved after AutomaticCFG custom node got updated.

**Comment by vicentecarro** [comment]
And I was wrong, the offender was "comfyui-profiler":
https://github.com/tzwm/comfyui-profiler/issues/2
