### ISSUE TITLE
After the latest version update, the ControlNet cannot be utilized. 

### ISSUE THREAD

**Issue by H-Bole** [comfyanonymous/ComfyUI#3039]
Today, after updating to the latest version and attempting to use ControlNet, I encountered an error upon startup. I recalled that it was functioning correctly yesterday. Therefore, I reverted back to the previous version, and it worked as expected. This indicates that there is an issue with the latest version.
This is my ControlNet file.
![image](https://github.com/comfyanonymous/ComfyUI/assets/102267145/7e70f33c-70d5-4e46-bdc0-037cc18afc88)
```
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
clip missing: ['clip_l.logit_scale', 'clip_l.transformer.text_projection.weight']
Requested to load SD1ClipModel
Loading 1 new model
Requested to load BaseModel
Loading 1 new model
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.2\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI-aki-v1.2\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI-aki-v1.2\nodes.py", line 1369, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\ComfyUI-aki-v1.2\nodes.py", line 1339, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\ComfyUI-aki-v1.2\custom_nodes\Comfyui-StableSR\nodes.py", line 69, in hook_sample
    return original_sample(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 248, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\comfy\sample.py", line 100, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 704, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 609, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 548, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\comfy\k_diffusion\sampling.py", line 745, in sample_lcm
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 286, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, model_options=model_options, seed=seed)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 273, in forward
    return self.apply_model(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 270, in apply_model
    out = sampling_function(self.inner_model, x, timestep, uncond, cond, cond_scale, model_options=model_options, seed=seed)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 250, in sampling_function
    cond_pred, uncond_pred = calc_cond_uncond_batch(model, cond, uncond_, x, timestep, model_options)
  File "D:\ComfyUI-aki-v1.2\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_uncond_batch
    return calc_cond_uncond_batch_original_tiled_diffusion_4a357b8e(model, cond, uncond, x_in, timestep, model_options)
  File "D:\ComfyUI-aki-v1.2\comfy\samplers.py", line 198, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "D:\ComfyUI-aki-v1.2\comfy\controlnet.py", line 182, in get_control
    control = self.control_model(x=x_noisy.to(dtype), hint=self.cond_hint, timesteps=timestep.float(), context=context.to(dtype), y=y)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\container.py", line 217, in forward
    input = module(input)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.2\comfy\controlnet.py", line 217, in forward
    weight, bias = comfy.ops.cast_bias_weight(self, input)
  File "D:\ComfyUI-aki-v1.2\comfy\ops.py", line 27, in cast_bias_weight
    if s.bias_function is not None:
  File "D:\ComfyUI-aki-v1.2\.ext\Lib\site-packages\torch\nn\modules\module.py", line 1688, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'Linear' object has no attribute 'bias_function'

```

**Comment by senlyu163** [comment]
same error, after commit : db8b59ecff7be40377d17ea69487f442b469c536

**Comment by skyler14** [comment]
Also having this issue

**Comment by amimi818** [comment]
same error...

**Comment by comfyanonymous** [comment]
Should be fixed now.

**Comment by H-Bole** [comment]
now is ok
