### ISSUE TITLE
TypeError: string indices must be integers, not 'str'

### ISSUE THREAD

**Issue by DuckyBlender** [comfyanonymous/ComfyUI#3054]
This error while sending a request using the API. Any ideas what I'm doing wrong?

```
Error handling request
Traceback (most recent call last):
  File "/home/alan/Github/ComfyUI/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/Github/ComfyUI/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/Github/ComfyUI/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/Github/ComfyUI/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/Github/ComfyUI/server.py", line 468, in post_prompt
    valid = execution.validate_prompt(prompt)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alan/Github/ComfyUI/execution.py", line 625, in validate_prompt
    class_ = nodes.NODE_CLASS_MAPPINGS[prompt[x]['class_type']]
                                       ~~~~~~^^^
TypeError: string indices must be integers, not 'str'
```

**Comment by DuckyBlender** [comment]
Should the http://localhost:8188/prompt be sent with POST or GET?

**Comment by bigcat88** [comment]
Looks like flow in invalid format, need more information to say what is wrong

**Comment by DuckyBlender** [comment]
> Looks like flow in invalid format, need more information to say what is wrong

Unless my code is wrong (https://github.com/DuckyBlender/duckgpt/blob/main/comfyui-rs/src/lib.rs) this just sends the `workflow_api.json` with the custom prompt... Will do more testing

**Comment by bigcat88** [comment]
Please attach the content of "prompt" as archive here.

I think nodes ids are integers in it and Comfy requires strings types, but it is an assumption

**Comment by DuckyBlender** [comment]
Oh my god I fixed it, sorry. I was sending quote escaped JSON... Sorry for opening this issue
