### ISSUE TITLE
WinError5  , ComfyUI  not work

### ISSUE THREAD

**Issue by KumaPlayWithShader** [comfyanonymous/ComfyUI#3070]
It's a clear comfyui windows portable, with RTX4060 8GB.

Traceback (most recent call last):
  File "D:\ComfyUI_Portable\ComfyUI\main.py", line 205, in <module>
    server = server.PromptServer(loop)
  File "D:\ComfyUI_Portable\ComfyUI\server.py", line 67, in init
    mimetypes.init()
  File "mimetypes.py", line 368, in init
  File "mimetypes.py", line 253, in read_windows_registry
PermissionError: [WinError 5] 存取被拒。

![WinError5](https://github.com/comfyanonymous/ComfyUI/assets/63226136/1596415b-14af-47af-a14e-a991101ffd29)

**Comment by bigcat88** [comment]
This is not a bug in ComfyUI, imho.
And it is unrelated to hardware, it is a software problem.

https://docs.python.org/3/library/mimetypes.html#mimetypes.init

https://bugs.python.org/issue38672

**Comment by KumaPlayWithShader** [comment]
So, anyone know how to  fixed this problem? 
I am not familiar with python stuff.....

**Comment by ApexHigh** [comment]
Moving the folder with ComfyUI from drive C to drive D worked for me. I think this is due to more restrictive permissions on the system disk.
