### ISSUE TITLE
[Feature Request] Allow us to resize images past 8192 px

### ISSUE THREAD

**Issue by Vigilence** [comfyanonymous/ComfyUI#3101]
I didn't realize that there was a cap of image size 8192 px.  If this can be lifted that would be super!

Starting server

```
To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: I:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 88, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
got prompt
Failed to validate prompt for output 59:
* ImageScale 71:
  - Value 12960 bigger than max of 8192: width
Output will be ignored
Failed to validate prompt for output 38:
Output will be ignored
Failed to validate prompt for output 39:
Output will be ignored
[rgthree] Using rgthree's optimized recursive execution.
[rgthree] First run patching recursive_output_delete_if_changed and recursive_will_execute.
[rgthree] Note: If execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.
```

**Comment by NutchapolSal** [comment]
As a workaround, I think you can just change the value in `nodes.py` where it defines `MAX_RESOLUTION=8192` then (re)start your ComfyUI, and hope there's no other hardcoded limits in other parts of the code

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/11838e60f4aac495c6f0aed09415f3e8e0d2a402
