### ISSUE TITLE
err:folders = folder_names_and_paths[folder_name] KeyError: 'sams'

### ISSUE THREAD

**Issue by ddppccc** [comfyanonymous/ComfyUI#3134]
folders = folder_names_and_paths[folder_name]
KeyError: 'sams'

**Comment by uni-devboy** [comment]
same error here


```Import times for custom nodes:
   0.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds (IMPORT FAILED): E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inference-Core-Nodes
   0.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.1 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\antrobots-comfyUI-nodepack
   0.1 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_segformer_b2_clothes
   0.2 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.5 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes
   1.0 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Seg_VITON
   1.2 seconds: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-J

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[ERROR] An error occurred while retrieving information for the 'PrimereImageSegments' node.
Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 420, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\server.py", line 398, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Primere_Nodes\Nodes\Segments.py", line 134, in INPUT_TYPES
    sams = list(filter(lambda x: x.startswith('sam_vit'), folder_paths.get_filename_list("sams")))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 220, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 187, in get_filename_list_
    folders = folder_names_and_paths[folder_name]
              ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
KeyError: 'sams'
```

**Comment by uni-devboy** [comment]
sams path was missing from the comfyui folder_paths.py file. I fixed the error by adding the below to the folder_paths.py file. 

`folder_names_and_paths["sams"] = ([os.path.join(models_dir, "sams")], supported_pt_extensions)`

**Comment by ltdrdata** [comment]
> sams path was missing from the comfyui folder_paths.py file. I fixed the error by adding the below to the folder_paths.py file.
> 
> `folder_names_and_paths["sams"] = ([os.path.join(models_dir, "sams")], supported_pt_extensions)`

'sams' path is not belongs to ComfyUI core. Create `ComfyUI/models/sams` by your self. Or download sam models from ComfyUI-Managers's `Install models`.
