### ISSUE TITLE
ComfyUi on RunPod- Launching issue

### ISSUE THREAD

**Issue by wermind00** [comfyanonymous/ComfyUI#3164]
Hi!
I am new in Comfy Ui. I run it through RunPod, first time everything worked, however after trying to insall missing nodes i had to refresh it and cannot run ComfyUi with second try. Please help!
While trying to run it i come across this error: ImportError: /workspace/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister

root@0ce38ac98898:/# apt update
Hit:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64 InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:6 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
108 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@0ce38ac98898:/# apt install psmisc
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
psmisc is already the newest version (23.4-2build3).
0 upgraded, 0 newly installed, 0 to remove and 108 not upgraded.
root@0ce38ac98898:/# fuser -k 3000/tcp
root@0ce38ac98898:/# cd /workspace/ComfyUI/venv
root@0ce38ac98898:/workspace/ComfyUI/venv# source bin/activate
(venv) root@0ce38ac98898:/workspace/ComfyUI/venv# cd /workspace/ComfyUI
(venv) root@0ce38ac98898:/workspace/ComfyUI# pip install torch torchvision torchaudio
Requirement already satisfied: torch in ./venv/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: torchvision in ./venv/lib/python3.10/site-packages (0.17.2)
Requirement already satisfied: torchaudio in ./venv/lib/python3.10/site-packages (2.2.2)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in ./venv/lib/python3.10/site-packages (from torch) (12.1.105)
Requirement already satisfied: sympy in ./venv/lib/python3.10/site-packages (from torch) (1.12)
Requirement already satisfied: networkx in ./venv/lib/python3.10/site-packages (from torch) (3.2.1)
Requirement already satisfied: nvidia-cudnn-cu12==8.9.2.26 in ./venv/lib/python3.10/site-packages (from torch) (8.9.2.26)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in ./venv/lib/python3.10/site-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in ./venv/lib/python3.10/site-packages (from torch) (12.1.0.106)
Requirement already satisfied: triton==2.2.0 in ./venv/lib/python3.10/site-packages (from torch) (2.2.0)
Requirement already satisfied: typing-extensions>=4.8.0 in ./venv/lib/python3.10/site-packages (from torch) (4.10.0)
Requirement already satisfied: jinja2 in ./venv/lib/python3.10/site-packages (from torch) (3.1.3)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in ./venv/lib/python3.10/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in ./venv/lib/python3.10/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in ./venv/lib/python3.10/site-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in ./venv/lib/python3.10/site-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in ./venv/lib/python3.10/site-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in ./venv/lib/python3.10/site-packages (from torch) (10.3.2.106)
Requirement already satisfied: filelock in ./venv/lib/python3.10/site-packages (from torch) (3.13.3)
Requirement already satisfied: fsspec in ./venv/lib/python3.10/site-packages (from torch) (2024.3.1)
Requirement already satisfied: nvidia-nccl-cu12==2.19.3 in ./venv/lib/python3.10/site-packages (from torch) (2.19.3)
Requirement already satisfied: nvidia-nvjitlink-cu12 in ./venv/lib/python3.10/site-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.4.99)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./venv/lib/python3.10/site-packages (from torchvision) (9.5.0)
Requirement already satisfied: numpy in ./venv/lib/python3.10/site-packages (from torchvision) (1.26.4)
Requirement already satisfied: MarkupSafe>=2.0 in ./venv/lib/python3.10/site-packages (from jinja2->torch) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in ./venv/lib/python3.10/site-packages (from sympy->torch) (1.3.0)
(venv) root@0ce38ac98898:/workspace/ComfyUI# python main.py --listen 0.0.0.0 --port 3000
** ComfyUI startup time: 2024-03-28 15:06:06.838097
** Platform: Linux
** Python version: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
** Python executable: /workspace/ComfyUI/venv/bin/python
** Log path: /workspace/ComfyUI/comfyui.log

Prestartup times for custom nodes:
0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
File "/workspace/ComfyUI/main.py", line 73, in
import comfy.utils
File "/workspace/ComfyUI/comfy/utils.py", line 1, in
import torch
File "/workspace/ComfyUI/venv/lib/python3.10/site-packages/torch/init.py", line 237, in
from torch._C import * # noqa: F403
ImportError: /workspace/ComfyUI/venv/lib/python3.10/site-packages/torch/lib/libtorch_cuda.so: undefined symbol: ncclCommRegister
(venv) root@0ce38ac98898:/workspace/ComfyUI#

**Comment by bigcat88** [comment]
missing nodes install a higher version of `pytorch` that requires `nccl 2.19.4`

Reference: https://github.com/NVIDIA/nccl/issues/1180
