### ISSUE TITLE
KSampler: "float division by zero" when denoise is 0

### ISSUE THREAD

**Issue by clayne** [comfyanonymous/ComfyUI#3171]
```
Traceback (most recent call last):
  File "F:\stablediffusion\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\stablediffusion\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "F:\stablediffusion\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\stablediffusion\ComfyUI\nodes.py", line 1369, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "F:\stablediffusion\ComfyUI\nodes.py", line 1339, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample    
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impa
ct on other operations.
  File "F:\stablediffusion\ComfyUI\custom_nodes\comfyui-diffusion-cg\recenter.py", line 29, in sample_center
    return SAMPLE(*args, **kwargs)
  File "F:\stablediffusion\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 267, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "F:\stablediffusion\ComfyUI\comfy\sample.py", line 98, in sample
    sampler = comfy.samplers.KSampler(real_model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=den
oise, model_options=model.model_options)
  File "F:\stablediffusion\ComfyUI\comfy\samplers.py", line 658, in __init__
    self.set_steps(steps, denoise)
  File "F:\stablediffusion\ComfyUI\comfy\samplers.py", line 681, in set_steps
    new_steps = int(steps/denoise)
ZeroDivisionError: float division by zero
```
Here:
```python
676     def set_steps(self, steps, denoise=None):
677         self.steps = steps
678         if denoise is None or denoise > 0.9999:
679             self.sigmas = self.calculate_sigmas(steps).to(self.device)
680         else:
681             new_steps = int(steps/denoise)
682             sigmas = self.calculate_sigmas(new_steps).to(self.device)
683             self.sigmas = sigmas[-(steps + 1):]
```
Seems like this should be checked for 0 and processing bypassed or something more graceful along the same lines. A denoise of 0.0 doesn't seem like a pathological state it seems like a "this should be bypassed" state and a floating point exception doesn't help. There could also be cases where it's converted to an input and an external source ends up sending 0 for whatever reason.

**Comment by NeedsMoar** [comment]
Right click->bypass is the "this should be bypassed" state in comfy (or use control flow nodes if you need to do it programmatically.  Denoise == 0.0 should at best print a clean error or not be allowed as input, not ignore-and-fallthrough.

**Comment by yarikmoscow** [comment]
just make CROP - DISABLED in LTXV Base Sampler node
