### ISSUE TITLE
Saving the model in fp8 (SDXL Exception), but for sd1.5 work

### ISSUE THREAD

**Issue by rtadeu82** [comfyanonymous/ComfyUI#3188]
**Is it possible to fix saving SDXL models?**

---

Tried saving a 1.5 model with fp8 startup parameters and got a 1gb model and it even loads and generates normally.
![image](https://github.com/comfyanonymous/ComfyUI/assets/89509058/1198900b-9a1c-46a3-a68a-8d4b99e0d8f8)

generation comparison on model deliberate_v2  fp16 vs fp8 (comfyui run in fp16 mode)
![image](https://github.com/comfyanonymous/ComfyUI/assets/89509058/9b4f3e37-d093-493f-92b9-7df863a26cad)

I also tried to save sdxl model and got an error when saving it
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "A:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.py", line 226, in save
    save_checkpoint(model, clip=clip, vae=vae, filename_prefix=filename_prefix, output_dir=self.output_dir, prompt=prompt, extra_pnginfo=extra_pnginfo)
  File "A:\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_model_merging.py", line 206, in save_checkpoint
    comfy.sd.save_checkpoint(output_checkpoint, model, clip, vae, clip_vision, metadata=metadata)
  File "A:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 612, in save_checkpoint
    sd = model.model.state_dict_for_saving(clip_sd, vae.get_sd(), clip_vision_sd)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_windows_portable\ComfyUI\comfy\model_base.py", line 195, in state_dict_for_saving
    extra_sds.append(self.model_config.process_clip_state_dict_for_saving(clip_state_dict))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_windows_portable\ComfyUI\comfy\supported_models.py", line 203, in process_clip_state_dict_for_saving
    state_dict_g = diffusers_convert.convert_text_enc_state_dict_v20(state_dict, "clip_g")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_convert.py", line 252, in convert_text_enc_state_dict_v20
    new_state_dict[relabelled_key + ".in_proj_weight"] = torch.cat(tensors)
                                                         ^^^^^^^^^^^^^^^^^^
RuntimeError: "cat_cuda" not implemented for 'Float8_e4m3fn'
```

**update**
if text encoder is left in fp16 and unet in fp8, then saving happens without errors and the model is 4.26gb.

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/6c6a39251fe313c56a88c90d820009073b623dfe

This should be fixed now.
