### ISSUE TITLE
cannot import name 'instantiate_from_config' from partially initialized module 'comfy.ldm.util'

### ISSUE THREAD

**Issue by jteijema** [comfyanonymous/ComfyUI#3189]
```console
** ComfyUI startup time: 2024-04-02 17:10:18.255991
** Platform: Windows
** Python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)]
** Python executable: C:\Users\x\Documents\ComfyUI\env\Scripts\python.exe
** Log path: C:\Users\x\Documents\ComfyUI\ComfyUI-master\comfyui.log

Prestartup times for custom nodes:
   0.4 seconds: C:\Users\x\Documents\ComfyUI\ComfyUI-master\custom_nodes\ComfyUI-Manager-main

Total VRAM 8188 MB, total RAM 16107 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Traceback (most recent call last):
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\main.py", line 76, in <module>
    import execution
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\execution.py", line 11, in <module>
    import nodes
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\comfy\sd.py", line 6, in <module>
    from .ldm.models.autoencoder import AutoencoderKL, AutoencodingEngine
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\comfy\ldm\models\autoencoder.py", line 9, in <module>
    from comfy.ldm.util import instantiate_from_config
  File "C:\Users\x\Documents\ComfyUI\ComfyUI-master\comfy\ldm\util.py", line 18, in <module>
    from comfy.ldm.util import instantiate_from_config
ImportError: cannot import name 'instantiate_from_config' from partially initialized module 'comfy.ldm.util' (most likely due to a circular import) (C:\Users\x\Documents\ComfyUI\ComfyUI-master\comfy\ldm\util.py)
```

Hi. I am getting the following error after running from a fresh installation, in a venv. 
```console
pip freeze
aiohttp==3.9.3
aiosignal==1.3.1
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
colorama==0.4.6
einops==0.7.0
filelock==3.13.3
frozenlist==1.4.1
fsspec==2024.3.1
huggingface-hub==0.22.2
idna==3.6
Jinja2==3.1.3
kornia==0.7.2
kornia_rs==0.1.2
MarkupSafe==2.1.5
mpmath==1.3.0
multidict==6.0.5
networkx==3.2.1
numpy==1.26.4
packaging==24.0
pillow==10.3.0
psutil==5.9.8
PyYAML==6.0.1
regex==2023.12.25
requests==2.31.0
safetensors==0.4.2
scipy==1.12.0
setuptools==69.2.0
sympy==1.12
tokenizers==0.15.2
torch==2.2.2+cu121
torchaudio==2.2.2+cu121
torchsde==0.2.6
torchvision==0.17.2+cu121
tqdm==4.66.2
trampoline==0.1.2
transformers==4.39.3
typing_extensions==4.10.0
urllib3==2.2.1
yarl==1.9
```

**Comment by jteijema** [comment]
Turns out my installation was corrupted. Fixed by recloning.
