### ISSUE TITLE
AttributeError: module 'comfy.samplers' has no attribute 'calculate_sigmas_scheduler'

### ISSUE THREAD

**Issue by oktetopython** [comfyanonymous/ComfyUI#3218]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "H:\ComfyUI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-sampler-lcm-alternative\sampler_lcm_alt.py", line 81, in get_sigmas
    sigmas = comfy.samplers.calculate_sigmas_scheduler(model.model, "sgm_uniform", total_steps).cpu()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.samplers' has no attribute 'calculate_sigmas_scheduler'

Prompt executed in 86.45 seconds

**Comment by ltdrdata** [comment]
You need to update `ComfyUI-sampler-lcm-alternative` custom node.

**Comment by oktetopython** [comment]
Okay, thank you

**Comment by dwgeneral** [comment]
I have updated the custom node, and still got this error:
```
Error occurred when executing LCMScheduler:

module 'comfy.samplers' has no attribute 'calculate_sigmas'

File "/root/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/root/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/root/ComfyUI/custom_nodes/ComfyUI-sampler-lcm-alternative/sampler_lcm_alt.py", line 81, in get_sigmas
sigmas = comfy.samplers.calculate_sigmas(model.get_model_object("model_sampling"), "sgm_uniform", total_steps).cpu()
```

**Comment by oktetopython** [comment]
Just update all the content to the latest, including comfyui
