### ISSUE TITLE
When executing the Queue prompt, the backend will report the following error:, The version just updated today uses the Windows integration package

### ISSUE THREAD

**Issue by wyply115** [comfyanonymous/ComfyUI#3223]
Error handling request
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x02:\x01')

**Comment by zRich** [comment]
My comfyui is runing with ningx reverse proxy
I encountered the similar error 
![image](https://github.com/comfyanonymous/ComfyUI/assets/2752413/18f80eb4-7991-4617-baf4-8b4568309ed2)
![image](https://github.com/comfyanonymous/ComfyUI/assets/2752413/e9aac4f5-4fb0-4db5-840d-aac1c60a36ea)
