### ISSUE TITLE
AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

### ISSUE THREAD

**Issue by zhuhanyuan** [comfyanonymous/ComfyUI#3236]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhudigi/AItools/ComfyUI-master/custom_nodes/ComfyUI_IPAdapter_plus/IPAdapterPlus.py", line 436, in load_models
    is_sdxl = isinstance(model.model, (comfy.model_base.SDXL, comfy.model_base.SDXLRefiner, comfy.model_base.SDXL_instructpix2pix))
                                                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

**Comment by originalpaul** [comment]
<img width="624" alt="Screenshot 2024-04-11 at 12 30 08 PM" src="https://github.com/comfyanonymous/ComfyUI/assets/53717310/46ab6f07-c180-4810-8fff-64b20bc6f57f">

Same error for me, also on Apple M1.

**Comment by datuizhuang** [comment]
same error

**Comment by BitReign** [comment]
Same on Win i9

**Comment by superadi04** [comment]
same here

**Comment by zhuhanyuan** [comment]
Just update comfyUI, everything will be OK!

**Comment by BitReign** [comment]
> Just update comfyUI, everything will be OK!

Updating all via manager solved my issue. Thanks.

**Comment by X3lnThpi** [comment]
@BitReign is right, thanks man.

**Comment by DING03015** [comment]
"ComfyUI is already up to date with the latest version.", but AttributeError still occurs: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'
I'd like to ask if there are any other ways
![截屏2024-05-08 10 05 30](https://github.com/comfyanonymous/ComfyUI/assets/163505072/ba433063-bb12-4bc4-93f7-ee1330f8d26f)
![截屏2024-05-08 10 24 04](https://github.com/comfyanonymous/ComfyUI/assets/163505072/ed3251f7-b5ba-44cc-9169-8b0d19389679)

**Comment by ltdrdata** [comment]
> SDXL_instructpix2pix

goto ComfyUI dir in cmd and execute this.
```
git status
```

What is displayed?

**Comment by DING03015** [comment]
Execute git status in the comfyUI directory
display：
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   extra_model_paths.yaml.example

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .DS_Store
        comfy/.DS_Store
        comfy/ldm/.DS_Store
        comfy_extras/.DS_Store
        comfy_extras/chainner_models/.DS_Store
        comfy_extras/chainner_models/architecture/.DS_Store
        comfyui.log
        comfyui.prev.log
        comfyui.prev2.log
        node_helpers.py
        tests-ui/.DS_Store
        tests/.DS_Store
        web/.DS_Store

no changes added to commit (use "git add" and/or "git commit -a")

Then enter the command git log
display：
commit d3406d8d588d6b0c2da44c9bf378733a2077a14f (HEAD -> master, origin/master, origin/HEAD)
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sun Mar 17 08:57:49 2024 -0400

    Increase image batch nodes maximum values.

commit d7897fff2cfd38eac051fbc958a6f944bdf68cc9
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sat Mar 16 14:49:35 2024 -0400

    Move cascade scale factor from stage_a to latent_formats.py

commit f2fe635c9f56a8e78866f59b3f110585e75b42f4
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Fri Mar 15 19:34:22 2024 -0400

    SamplerDPMAdaptative node to test the different options.

commit 448d9263a258062344e25135fc49d26a7e60887a
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Thu Mar 14 09:30:21 2024 -0400

    Fix control loras breaking.

commit db8b59ecff7be40377d17ea69487f442b469c536
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Wed Mar 13 19:04:41 2024 -0400

    Lower memory usage for loras in lowvram mode at the cost of perf.

commit eda87043862f743b0a0467735f8531f7c4709b3a
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Tue Mar 12 12:16:37 2024 -0400

    Add SamplerDPMPP_3M_SDE node.

commit e7b8e240f76d2afe0eed6db7a35833923792ae94
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Tue Mar 12 04:34:34 2024 -0400

    Add SamplerLMS node.

commit 2a813c3b09292c9aeab622ddf65d77e5d8171d0d
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Mon Mar 11 16:24:47 2024 -0400

    Switch some more prints to logging.

:

**Comment by DING03015** [comment]
> > SDXL_instructpix2pix
> 
> 在 cmd 中转到 ComfyUI 目录并执行此命令。
> 
> ```
> git status
> ```
> 
> 显示什么？
> 
> 并检查此命令。
> 
> ```
> git log
> ```

Execute git status in the comfyUI directory
display：
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   extra_model_paths.yaml.example

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .DS_Store
        comfy/.DS_Store
        comfy/ldm/.DS_Store
        comfy_extras/.DS_Store
        comfy_extras/chainner_models/.DS_Store
        comfy_extras/chainner_models/architecture/.DS_Store
        comfyui.log
        comfyui.prev.log
        comfyui.prev2.log
        node_helpers.py
        tests-ui/.DS_Store
        tests/.DS_Store
        web/.DS_Store

no changes added to commit (use "git add" and/or "git commit -a")

Then enter the command git log
display：
commit d3406d8d588d6b0c2da44c9bf378733a2077a14f (HEAD -> master, origin/master, origin/HEAD)
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sun Mar 17 08:57:49 2024 -0400

    Increase image batch nodes maximum values.

commit d7897fff2cfd38eac051fbc958a6f944bdf68cc9
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sat Mar 16 14:49:35 2024 -0400

    Move cascade scale factor from stage_a to latent_formats.py

commit f2fe635c9f56a8e78866f59b3f110585e75b42f4
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Fri Mar 15 19:34:22 2024 -0400

    SamplerDPMAdaptative node to test the different options.

commit 448d9263a258062344e25135fc49d26a7e60887a
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Thu Mar 14 09:30:21 2024 -0400

    Fix control loras breaking.

commit db8b59ecff7be40377d17ea69487f442b469c536
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Wed Mar 13 19:04:41 2024 -0400

    Lower memory usage for loras in lowvram mode at the cost of perf.

commit eda87043862f743b0a0467735f8531f7c4709b3a
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Tue Mar 12 12:16:37 2024 -0400

    Add SamplerDPMPP_3M_SDE node.

commit e7b8e240f76d2afe0eed6db7a35833923792ae94
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Tue Mar 12 04:34:34 2024 -0400

    Add SamplerLMS node.

commit 2a813c3b09292c9aeab622ddf65d77e5d8171d0d
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Mon Mar 11 16:24:47 2024 -0400

    Switch some more prints to logging.

:

**Comment by ltdrdata** [comment]
It seems that updating failed due to your ComfyUI file is modified.
(The dialog message should be patched)

Just execute this.
```
git checkout extra_model_paths.yaml.example
git pull
```

**Comment by DING03015** [comment]
> 由于您的 ComfyUI 文件被修改，更新似乎失败。 （应该修补对话框消息）
> 
> 只需执行这个即可。
> 
> ```
> git checkout extra_model_paths.yaml.example
> git pull
> ```
Thank you very much for your reply
After executing the command, it displays
Updated 1 path from the index
Already up to date.

Then restart comfyUI. After clicking, AttributeError is still displayed: module 'comfy.model_base' has no attribute 'SDXL_instructpix2pix'

**Comment by DING03015** [comment]
> 由于您的 ComfyUI 文件被修改，更新似乎失败。 （修复应该对话框消息）
> 
> 执行这个即可。
> 
> ```
> git checkout extra_model_paths.yaml.example
> git pull
> ```
After closing comfyUI, I just reentered the command -git status
display:
On branch master
Your branch is up to date with 'origin/master'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        .DS_Store
        comfy/.DS_Store
        comfy/ldm/.DS_Store
        comfy_extras/.DS_Store
        comfy_extras/chainner_models/.DS_Store
        comfy_extras/chainner_models/architecture/.DS_Store
        comfyui.log
        comfyui.prev.log
        comfyui.prev2.log
        node_helpers.py
        tests-ui/.DS_Store
        tests/.DS_Store
        web/.DS_Store

nothing added to commit but untracked files present (use "git add" to track)

**Comment by ltdrdata** [comment]
> > 由于您的 ComfyUI 文件被修改，更新似乎失败。 （修复应该对话框消息）
> > 执行这个即可。
> > ```
> > git checkout extra_model_paths.yaml.example
> > git pull
> > ```
> 
> After closing comfyUI, I just reentered the command -git status display: On branch master Your branch is up to date with 'origin/master'.
> 
> Untracked files: (use "git add ..." to include in what will be committed) .DS_Store comfy/.DS_Store comfy/ldm/.DS_Store comfy_extras/.DS_Store comfy_extras/chainner_models/.DS_Store comfy_extras/chainner_models/architecture/.DS_Store comfyui.log comfyui.prev.log comfyui.prev2.log node_helpers.py tests-ui/.DS_Store tests/.DS_Store web/.DS_Store
> 
> nothing added to commit but untracked files present (use "git add" to track)

huh... `node_helpers.py` should not exists in there.
remove `node_helpers.py` and `git pull` again.

**Comment by DING03015** [comment]
> > > 由于您的 ComfyUI 文件被修改，更新似乎失败。 （修复应该对话框消息）
> > > 执行这个即可。
> > > ```
> > > git checkout extra_model_paths.yaml.example
> > > git pull
> > > ```
> > 
> > 
> > After closing comfyUI, I just reentered the command -git status display: On branch master Your branch is up to date with 'origin/master'.
> > Untracked files: (use "git add ..." to include in what will be committed) .DS_Store comfy/.DS_Store comfy/ldm/.DS_Store comfy_extras/.DS_Store comfy_extras/chainner_models/.DS_Store comfy_extras/chainner_models/architecture/.DS_Store comfyui.log comfyui.prev.log comfyui.prev2.log node_helpers.py tests-ui/.DS_Store tests/.DS_Store web/.DS_Store
> > nothing added to commit but untracked files present (use "git add" to track)
> 
> huh... `node_helpers.py` should not exists in there. remove `node_helpers.py` and `git pull` again.
> 
> And you need to execute `git log` to check up to date.

After deleting this file node_helpers.py and executing the command
display：
commit d3406d8d588d6b0c2da44c9bf378733a2077a14f (HEAD -> master, origin/master, origin/HEAD)
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sun Mar 17 08:57:49 2024 -0400

    Increase image batch nodes maximum values.

commit d7897fff2cfd38eac051fbc958a6f944bdf68cc9
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Sat Mar 16 14:49:35 2024 -0400

    Move cascade scale factor from stage_a to latent_formats.py

commit f2fe635c9f56a8e78866f59b3f110585e75b42f4
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Fri Mar 15 19:34:22 2024 -0400

    SamplerDPMAdaptative node to test the different options.

commit 448d9263a258062344e25135fc49d26a7e60887a
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Thu Mar 14 09:30:21 2024 -0400

    Fix control loras breaking.

commit db8b59ecff7be40377d17ea69487f442b469c536
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Wed Mar 13 19:04:41 2024 -0400

    Lower memory usage for loras in lowvram mode at the cost of perf.

commit eda87043862f743b0a0467735f8531f7c4709b3a
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Tue Mar 12 12:16:37 2024 -0400

    Add SamplerDPMPP_3M_SDE node.

commit e7b8e240f76d2afe0eed6db7a35833923792ae94
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Tue Mar 12 04:34:34 2024 -0400

    Add SamplerLMS node.

commit 2a813c3b09292c9aeab622ddf65d77e5d8171d0d
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Mon Mar 11 16:24:47 2024 -0400

    Switch some more prints to logging.

:

**Comment by ltdrdata** [comment]
Did you execute `git pull` after remove it?

**Comment by DING03015** [comment]
> git log

git pull performed after deleting files
Executing git pull shows: Already up to date.
The last command executed is git log

**Comment by DING03015** [comment]
> > > git 日志
> > 
> > 
> > 删除文件后执行 git pull 执行 git pull 显示：已经是最新的。最后执行的命令是 git log
> 
> 您的 ComfyUI 本地存储库无效。我建议删除它并重新克隆它。

Okay, I'll try it, thank you for your help
