### ISSUE TITLE
convert input to... error 

### ISSUE THREAD

**Issue by liulsg** [comfyanonymous/ComfyUI#3254]
TypeError: Cannot read properties of undefined (reading 'inputs')
    at LiteGraph.ContextMenu (main.js:209:25)
    at LiteGraph.ContextMenu (menu_auto_nest.js:33:44)
    at new LiteGraph.ContextMenu (easyContextMenu.js:48:44)
    at Object.construct (contextMenuHook.js:24:12)
    at HTMLDivElement.inner_onclick (litegraph.core.js:13951:35)

**Comment by ww5552031** [comment]
My solution disabled  AIGODLIKE-COMFYUI-TRANSLATION

**Comment by Joshua19770704** [comment]
I have the same problem, must disable AIGODLIKE-COMFYUI-TRANSLATION to let it work

**Comment by ericlee2023** [comment]
是的。正确。

**Comment by TigoTin** [comment]
update AIGODLIKE-COMFYUI-TRANSLATION

**Comment by vanche1212** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/19466281/df1496fe-2ba5-4d8e-8564-043add87856d)
好像不行诶，怎么input没有了

**Comment by vanche1212** [comment]
![image](https://github.com/comfyanonymous/ComfyUI/assets/19466281/fed7db0d-5a4f-4487-87ac-61086c3c2283)

**Comment by ZhianLin** [comment]
Manager->Install Custom Nodes -> 
![image](https://github.com/user-attachments/assets/5e393636-2576-4cb4-ac11-18572b2b6895)
