### ISSUE TITLE
KeyError: 'VideoTriangleCFGGuidance'

### ISSUE THREAD

**Issue by Banbury** [comfyanonymous/ComfyUI#3381]
Commit: eecd69b
OS: Windows 11
Python: 3.10

I am trying to use the SV3D nodes. The workflow works in principle, but at the end of the generation I get the following error:

```
Traceback (most recent call last):
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\nodes\__init__.py", line 94, in chunks
    comfy_script = transpile.WorkflowToScriptTranspiler(workflow).to_script(end_nodes)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 338, in to_script
    for node in self._topological_generations_ordered_dfs(end_nodes):
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 313, in _topological_generations_ordered_dfs
    yield from visit(v)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 308, in visit
    yield from visit(node_u)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 308, in visit
    yield from visit(node_u)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 308, in visit
    yield from visit(node_u)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 303, in visit
    inputs = passes.multiplexer_node_input_filter(G.nodes[node], self._widget_values_to_dict(v.type, v.widgets_values))
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 116, in _widget_values_to_dict
    widget_value_names = self._get_widget_value_names(node_type)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 85, in _get_widget_value_names
    input_types = self._get_input_types(node_type)
  File "d:\comfyui\.venv\lib\site-packages\comfy_script\transpile\__init__.py", line 81, in _get_input_types
    return self.nodes_info[node_type]['input']
KeyError: 'VideoTriangleCFGGuidance'
```
Since the VideoTriangleCFGGuidance is important to using SV3D, I'm wondering, what is happening here. Do I have to download an additional model?

I have attached the workflow.

[workflow.json](https://github.com/comfyanonymous/ComfyUI/files/15175410/workflow.json)

**Comment by ltdrdata** [comment]
That's odd... https://github.com/comfyanonymous/ComfyUI/commit/eecd69b53a896343775bcb02a4f8349e7442ffd1 have VideoTriangleCFGGuidance, VideoTriangleCFGGuidance.

Check if the `comfy_extra/nodes_video_model.py` file contains `VideoTriangleCFGGuidance`.

**Comment by Banbury** [comment]
The class does exist.
I have to admit, that I'm using hiddenswitch/ComfyUI, because it's easier to set up. So he may have broken something.
