### ISSUE TITLE
Import failed, No module named git.remote

### ISSUE THREAD

**Issue by roland3564** [comfyanonymous/ComfyUI#3440]
Windows 11, nvidia RTX 4060, ram 16Gb, cpu i7, python installed with the required dependencies, here's the log:

`main.py --windows-standalone-build --listen 0.0.0.0`

```
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-05-10 22:17:26.072281
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.3 seconds: C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8188 MB, total RAM 16024 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4060 Laptop GPU : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\__init__.py", line 6, in <module>
    from .glob import manager_server
  File "C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 18, in <module>
    import manager_core as core
  File "C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\glob\manager_core.py", line 10, in <module>
    from git.remote import RemoteProgress
ModuleNotFoundError: No module named 'git.remote'

Cannot import C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager module for custom nodes: No module named 'git.remote'

Import times for custom nodes:
   0.0 seconds: C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.1 seconds (IMPORT FAILED): C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://0.0.0.0:8188

Stopped server
```

**Comment by ltdrdata** [comment]
`C:\Users\rolan\Documents\AI\ComfyUI_windows_portable\python_embedded\python.exe -m pip freeze`

What is displayed?

**Comment by roland3564** [comment]
Nvm, I reinstalled and now Is working
