### ISSUE TITLE
NotADirectoryError: [WinError 267] The directory name is invalid

### ISSUE THREAD

**Issue by BenDes21** [comfyanonymous/ComfyUI#3534]
**Hello there, I get this error when I try to update all my nodes, anyone know where its can from ? Thanks**

Update ComfyUI
comfy_path: C:\Users\Admin\Documents\Stable diffusion\ComfyUI
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\commands\freeze.py", line 98, in run
    for line in freeze(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\freeze.py", line 43, in freeze
    req = FrozenRequirement.from_dist(dist)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\freeze.py", line 238, in from_dist
    req, comments = _get_editable_info(dist)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\operations\freeze.py", line 165, in _get_editable_info
    vcs_backend = vcs.get_backend_for_dir(location)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 238, in get_backend_for_dir
    repo_path = vcs_backend.get_repository_root(location)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\vcs\git.py", line 501, in get_repository_root
    r = cls.run_command(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\vcs\versioncontrol.py", line 650, in run_command
    return call_subprocess(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_internal\utils\subprocess.py", line 141, in call_subprocess
    proc = subprocess.Popen(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid

**Comment by NeedsMoar** [comment]
Probably trying to run as the Admin user on Windows?

**Comment by WainWong** [comment]
same

**Comment by mcmonkey4eva** [comment]
This is an issue with pip/python/windows, not ComfyUI

**Comment by ltdrdata** [comment]
I recommend that move `C:\Users\Admin\Documents\Stable diffusion\ComfyUI` to `C:\ComfyUI`
If the path contains blanks or special characters, it often causes problems. In particular, on Windows, the length of the path frequently also causes issues.

And it seems that you are using the system Python, which you shouldn't do. Set up a `venv` or use a portable version instead.
