### ISSUE TITLE
Error with 1024x1024 images and ddim_uniform

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#359]
```
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 177, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 56, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 65, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 685, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 649, in common_ksampler
    sampler = comfy.samplers.KSampler(real_model, steps=steps, device=device, sampler=sampler_name, scheduler=scheduler, denoise=denoise)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 348, in __init__
    self.set_steps(steps, denoise)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 380, in set_steps
    sigmas = self._calculate_sigmas(new_steps)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 366, in _calculate_sigmas
    sigmas = ddim_scheduler(self.model_wrap, steps).to(self.device)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 245, in ddim_scheduler
    sigs.append(model.t_to_sigma(torch.tensor(ddim_timesteps[x])))
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 85, in t_to_sigma
    log_sigma = (1 - w) * self.log_sigmas[low_idx] + w * self.log_sigmas[high_idx]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000
```

**Comment by comfyanonymous** [comment]
That's an issue with the number of steps not the the size of the image. How many did you put?

**Comment by WASasquatch** [comment]
> That's an issue with the number of steps not the the size of the image. How many did you put?

Default 20.

**Comment by comfyanonymous** [comment]
which denoise did you put?

**Comment by WASasquatch** [comment]
> which denoise did you put?

`0.55` not exactly a clean float.

**Comment by comfyanonymous** [comment]
Is this still a problem? If it is can you post the exact workflow?

**Comment by WASasquatch** [comment]
Haven't checked, just stopped using ddim. Let me update and test.
