### ISSUE TITLE
Some upscale-related custom nodes are checked for errors.

### ISSUE THREAD

**Issue by Neytiri7** [comfyanonymous/ComfyUI#3604]
https://github.com/portu-sim/comfyui_bmab If you use upscale for that node, an error occurs.

The node developer is believed to be a ComfyUI error.
Please check.

![image](https://github.com/comfyanonymous/ComfyUI/assets/139053327/b3aac4fe-65ab-485d-b50d-b02d93f21262)

WARNING: comfy_extras.chainner_models is deprecated and has been replaced by the spandrel library.
!!! Exception during processing!!! 'ImageModelDescriptor' object has no attribute 'state_dict'
Traceback (most recent call last):
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\sampler.py", line 388, in sample
    s = self.upscale_with_model(model_name, pixels)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\custom_nodes\comfyui_bmab\bmab\nodes\sampler.py", line 344, in upscale_with_model
    memory_required = model_management.module_size(upscale_model)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\SynologyDrive\ComfyUI-webui\ComfyUI\comfy\model_management.py", line 267, in module_size
    sd = module.state_dict()
         ^^^^^^^^^^^^^^^^^
AttributeError: 'ImageModelDescriptor' object has no attribute 'state_dict'

**Comment by Neytiri7** [comment]
They said they changed it to an updated code.
