### ISSUE TITLE
ComfyUI Can`t run with GTX 1650

### ISSUE THREAD

**Issue by AkarinLiu** [comfyanonymous/ComfyUI#3621]
## Logs
```
PS C:\Users\LX\AIGC\ComfyUI> python main.py

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\LX\AIGC\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "C:\Users\LX\AIGC\ComfyUI\main.py", line 73, in <module>
    import comfy.utils
  File "C:\Users\LX\AIGC\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "C:\Users\LX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\__init__.py", line 141, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "C:\Users\LX\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\lib\shm.dll" or one of its dependencies.
```

**Comment by comfyanonymous** [comment]
If you try using the standalone package does it work?

**Comment by ltdrdata** [comment]
Set up your environment using either the portable package or by creating a environment with venv.

**Comment by Shiyetu** [comment]
你好，请问你解决了吗
