### ISSUE TITLE
An error after update

### ISSUE THREAD

**Issue by seghier** [comfyanonymous/ComfyUI#3629]
Hello , I update ComfyUI from Manager but i get this error after runnig `run_cpu.bat`

```
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\main.py", line 73, in <module>
    import comfy.utils
  File "E:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 7, in <module>
    from PIL import Image
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\PIL\Image.py", line 50, in <module>
    from . import (
ImportError: cannot import name 'UnidentifiedImageError' from 'PIL' (unknown location)
```
i try: 
`update_comfyui.bat`
`update_comfyui_and_python_dependencies.bat`
but the error still appears

![image](https://github.com/comfyanonymous/ComfyUI/assets/6026588/b3fd9b4a-a1e7-4a23-93e2-24f794bf1361)

**Comment by ltdrdata** [comment]
`.\python_embeded\python -m pip install --force-reinstall -U pillow`

**Comment by seghier** [comment]
Thanks @ltdrdata 
Looks like the update broke other module , i reinstall ComfyUI totally
