### ISSUE TITLE
mask composite only accept positive value?

### ISSUE THREAD

**Issue by RoyDingZF** [comfyanonymous/ComfyUI#3642]
I would like to set the x, y value to negative when using the node.

**Comment by Lalimec** [comment]
Is there a reason for to keep the values positive? same thing happens with the image composite node.

```
got prompt
!!! Exception during processing !!! The size of tensor a (0) must match the size of tensor b (1024) at non-singleton dimension 2
Traceback (most recent call last):
  File "/home/ubuntu/cemil-test/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/cemil-test/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ubuntu/cemil-test/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ubuntu/cemil-test/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ubuntu/cemil-test/ComfyUI/comfy_extras/nodes_mask.py", line 250, in combine
    output[:, top:bottom, left:right] = destination_portion + source_portion
RuntimeError: The size of tensor a (0) must match the size of tensor b (1024) at non-singleton dimension 2
```

**Comment by Tekaiguy** [comment]
I would also like this, it's possible to push the overlaying image off the right side of the composite, but not the left side. Negative numbers are the only solution UNLESS the default position is off screen top-left. That way, only positive numbers could be used to cover all possible positions.
