### ISSUE TITLE
Comfy start with a wrong pytorch version.

### ISSUE THREAD

**Issue by giusparsifal** [comfyanonymous/ComfyUI#3663]
Hello, after an upgrade (my fault), was installed **pytorch version: 2.3.1+cu121** and Comfy don't start anymore.
So I uninstalled 2.3.1 and installed again pytorch version: 2.3.0+cu121.

When I try to discover what version I have via command "pip list | findstr torch" the result is

torch                   2.3.0+cu121
torchaudio          2.3.0+cu121
torchsde             0.2.6
torchvision          0.18.0+cu121

So it seems to be ok.
But when I start ComfyUI I got this error

_D:\ComfyUI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-06 01:58:36.998353
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\ComfyUI\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: D:\ComfyUI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
   0.3 seconds: D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 81852 MB
**pytorch version: 2.3.1+cu121**
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py", line 76, in <module>
    import execution
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 11, in <module>
    import nodes
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 17, in <module>
    from . import model_detection
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "D:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\__init__.py", line 33, in <module>
    from .generic import (
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\generic.py", line 31, in <module>
    from .import_utils import (
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\import_utils.py", line 272, in <module>
    torch_version = version.parse(_torch_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\packaging\version.py", line 54, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\packaging\version.py", line 198, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'

D:\ComfyUI\ComfyUI_windows_portable>pause
Premere un tasto per continuare . . ._

As you can see it loads (from where?)
**pytorch version: 2.3.1+cu121**

How I can solve it?
Thank you.

**Comment by PrometheusDante** [comment]
Having the same issue right now and I'm losing my mind over this bs.

**Comment by PrometheusDante** [comment]
Which folders and where were they? I'm still struggling with this.

**Comment by PeggyFree** [comment]
> Alright, I've managed to get this to work by replacing the following folders from `D:\...\ComfyUI\python_embeded\Lib\site-packages`
> 
> > torch
> > torch-2.3.1+cu118.dist-info
> > torchaudio
> > torchaudio-2.3.1+cu118.dist-info
> > torchvision
> > torchvision-0.18.1+cu118.dist-info
> 
> with the 2.3.0 ones I've installed, that for some reason all ended up in `C:\Users\Username\AppData\Roaming\Python\Python310\site-packages` namely:
> 
> > torch
> > torch-2.3.0+cu118.dist-info
> > torchaudio
> > torchaudio-2.3.0+cu118.dist-info
> > torchvision
> > torchvision-0.18.0+cu118.dist-info
> 
> And then it finally started up with pytorch 2.3.0 as supposed to.

Thank you for your precious help. I faced almost the same problem, my comfy site-package was still on torch 2.0 while pip had updated Username\AppData\... 

I guess there is a magic command to do, something like "venv etc." in order to get into the comfy python environment instead of the system one.

**Comment by Vektor369** [comment]
Everything was fine, then I restarted and got the "Torch not being compiled with CUDA enabled" error.

The upgrading Torch command at least got it to restart, but now apparently the xFormers are wrong, among several other things.

After a 2.4GB download (but hey, what's another two-and-a-half gigs to us AI users, amirite?) I got the following warning and error:

```
WARNING: The scripts convert-caffe2-to-onnx.exe, convert-onnx-to-caffe2.exe and torchrun.exe are installed in 'F:\AI\ComfyUI_windows_portable\python_embeded\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
xformers 0.0.27.post2 requires torch==2.4.0, but you have torch 2.3.0+cu121 which is incompatible.
```

No idea what the convert-caffe2-to-onnx script thing is, or what to do about it.

And now I'm getting the following popup on startup:
```
python.exe - Entry Point Not Found
The procedure entry point
?parseSchema@jit@torch@@YA?AUFunctionSchema@c10@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z could not be located in the dynamic link library
F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\_C.pyd.
```

And my console looks like this:
```
F:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-08 16:56:18.352651
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: F:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: F:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.6 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32648 MB
pytorch version: 2.3.0+cu121
WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.4.0+cu121 with CUDA 1201 (you have 2.3.0+cu121)
    Python  3.11.9 (you have 3.11.9)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\AI\ComfyUI_windows_portable\ComfyUI\web
Adding F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Loaded ControlNetPreprocessors nodes from F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.4.5)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V7.4.5)
Loaded ImpactPack nodes from[Impact Pack] Wildcards loading done.
F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\__init__.py", line 3, in <module>
    from .BiRefNet_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet\BiRefNet_node.py", line 18, in <module>
    from loguru import logger
ModuleNotFoundError: No module named 'loguru'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet module for custom nodes: No module named 'loguru'
[Crystools INFO] Crystools version: 1.16.6
[Crystools INFO] CPU: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3070
[Crystools INFO] NVIDIA Driver: 560.94
documents.core.js found at F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Documents\web\js\documents.core.js
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\__init__.py", line 7, in <module>
    from .nodes import NODE_CLASS_MAPPINGS
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF\nodes.py", line 3, in <module>
    import gguf
ModuleNotFoundError: No module named 'gguf'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF module for custom nodes: No module named 'gguf'
### Loading: ComfyUI-Impact-Pack (V7.4.5)
[Impact Pack] Wildcards loading done.
Total VRAM 8192 MB, total RAM 32648 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2653 [c27ebeb1] | Released on '2024-09-06'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-SpriteSheetCutter\\__init__.py'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SpriteSheetCutter module for custom nodes: [Errno 2] No such file or directory: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-SpriteSheetCutter\\__init__.py'
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4\__init__.py", line 6, in <module>
    import bitsandbytes
ModuleNotFoundError: No module named 'bitsandbytes'

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4 module for custom nodes: No module named 'bitsandbytes'

[rgthree] Loaded 42 epic nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.


Import times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SpriteSheetCutter.py
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SpriteSheetCutter
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.1 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper
   0.1 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Documents
   0.2 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.2 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2
   0.3 seconds (IMPORT FAILED): F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet
   0.3 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.4 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BrushNet
   0.5 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ToonCrafter
   1.1 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
```

So, it's looking like xFormers wants PyTorch 2.4.0, but updating to PyTorch 2.4.0 throws the error about Torch not being compiled with CUDA enabled? And it can't find efficiency nodes, Onnxruntime, AdvancedControlNet nodes, AnimateDiff nodes, loguru module, gguf module, or bitsandbytes module. Any ideas?
