### ISSUE TITLE
After the Comfy update 1 hour ago, I can no longer manage larger workflows

### ISSUE THREAD

**Issue by murphylanga** [comfyanonymous/ComfyUI#3667]
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'find')
TypeError: Cannot read properties of undefined (reading 'find')
    at nodeType.onGraphConfigured (http://127.0.0.1:8188/extensions/core/widgetInputs.js:359:29)
    at app.graph.onConfigure (http://127.0.0.1:8188/scripts/app.js:1406:29)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2260:9)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1393:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:69:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1838:15)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/core/undoRedo.js:25:12)
    at async app.loadGraphData (http://127.0.0.1:8188/extensions/ComfyUI-Manager/components-manager.js:771:9)
    at async reader.onload (http://127.0.0.1:8188/scripts/app.js:2206:6)
This may be due to the following script:
/extensions/core/widgetInputs.js

Here you can find a workflow:
https://openart.ai/workflows/murphylanga/automatic_comfyui_sdxl_modul-incl-faceswap/2Bsh5QwsrQkKFx6CLCz7

**Comment by murphylanga** [comment]
The problem is the update of the:
[comfyui-prompt-reader-node](https://github.com/receyuki/comfyui-prompt-reader-node)

Should I delete this post again?

**Comment by murphylanga** [comment]
The problem was updating:

[comfyui-prompt-reader-node](https://github.com/receyuki/comfyui-prompt-reader-node)

The developer was super fast and has already solved the problem :-) Wow and thank you very much.
