### ISSUE TITLE
New changes break video diffusion

### ISSUE THREAD

**Issue by limejet** [comfyanonymous/ComfyUI#3680]
Hello!

This is a duplicate issue of #3677.
When using the second workflow on the [Video Examples page](https://comfyanonymous.github.io/ComfyUI_examples/video/) with the latest commit (a5e6a63), the second KSampler node crashes. 

I'm not well-enough versed in the code to pinpoint the actual issue, but i added some logging and can tell that the `'area'` cond is never passed into any execution of `get_area_and_mult`. This is fine as long as `'model_conds'` is not also passed in, which it is in the second KSampler run.

<details>
<summary>Screenshot of UI with crashed node highlighted</summary>

![Screenshot_20240610_191025](https://github.com/comfyanonymous/ComfyUI/assets/4407285/6af80b2b-3c95-4409-8936-041c250ea42d)

</details>

<details>
<summary>Log with traceback</summary>

```
(venv) ~/s/s/ComfyUI
$ python main.py
Total VRAM 24560 MB, total RAM 64230 MB
pytorch version: 2.3.1+rocm6.0
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7900 XTX : native
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Adding extra search path checkpoints external/models/Stable-diffusion
Adding extra search path configs external/models/Stable-diffusion
Adding extra search path vae external/models/VAE
Adding extra search path loras external/models/Lora
Adding extra search path loras external/models/LyCORIS
Adding extra search path upscale_models external/models/ESRGAN
Adding extra search path upscale_models external/models/RealESRGAN
Adding extra search path upscale_models external/models/SwinIR
Adding extra search path embeddings external/models/embeddings
Adding extra search path hypernetworks external/models/hypernetworks
Adding extra search path controlnet external/models/ControlNet

Import times for custom nodes:
   0.0 seconds: ComfyUI/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type EPS
Using split attention in VAE
Using split attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|██████████████████████████████████| 15/15 [00:02<00:00,  5.95it/s]
Requested to load AutoencoderKL
Loading 1 new model
model_type V_PREDICTION_EDM
Using split attention in VAE
Using split attention in VAE
Requested to load CLIPVisionModelProjection
Loading 1 new model
Requested to load AutoencodingEngine
Loading 1 new model
Requested to load SVD_img2vid
Loading 1 new model
  0%|                                  | 0/20 [00:00<?, ?it/s]
!!! Exception during processing!!! 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "ComfyUI/nodes.py", line 1346, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "ComfyUI/nodes.py", line 1316, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "ComfyUI/comfy/sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "ComfyUI/comfy/samplers.py", line 794, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "ComfyUI/comfy/samplers.py", line 696, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "ComfyUI/comfy/samplers.py", line 683, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "ComfyUI/comfy/samplers.py", line 662, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "ComfyUI/comfy/samplers.py", line 567, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "ComfyUI/venv/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "ComfyUI/comfy/k_diffusion/sampling.py", line 137, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "ComfyUI/comfy/samplers.py", line 291, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "ComfyUI/comfy/samplers.py", line 649, in __call__
    return self.predict_noise(*args, **kwargs)
  File "ComfyUI/comfy/samplers.py", line 652, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "ComfyUI/comfy/samplers.py", line 277, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "ComfyUI/comfy/samplers.py", line 151, in calc_cond_batch
    p = get_area_and_mult(x, x_in, timestep)
  File "ComfyUI/comfy/samplers.py", line 69, in get_area_and_mult
    conditioning[c] = model_conds[c].process_cond(batch_size=x_in.shape[0], device=x_in.device, area=area)
  File "ComfyUI/comfy/conds.py", line 32, in process_cond
    data = self.cond[:,:,area[2]:area[0] + area[2],area[3]:area[1] + area[3]]
                         ~~~~^^^
TypeError: 'NoneType' object is not subscriptable

Prompt executed in 13.00 seconds
```
</details>

**Comment by mcmonkey4eva** [comment]
> This is a duplicate issue of #3677.

Then please post your details there rather than the duplicate
