### ISSUE TITLE
After reinstallation can't launch Comfy

### ISSUE THREAD

**Issue by Aendar** [comfyanonymous/ComfyUI#3687]

**Comment by Aendar** [comment]
Sorry, missclicked "enter"
Here is the log.
```
D:\ComfyUI_windows_portable_nightly_pytorch>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\main.py", line 73, in <module>
    import comfy.utils
  File "D:\ComfyUI_windows_portable_nightly_pytorch\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "D:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\__init__.py", line 144, in <module>
    raise err
OSError: [WinError 126] Не найден указанный модуль. Error loading "D:\ComfyUI_windows_portable_nightly_pytorch\python_embeded\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

D:\ComfyUI_windows_portable_nightly_pytorch>pause
```

**Comment by heiheiheibj** [comment]
I am experiencing the same problem. How was this problem solved?
thx

**Comment by Aendar** [comment]
> I am experiencing the same problem. How was this problem solved? thx
Hi, I didn't really understand what worked for me. But after I downloaded the January 31 release, everything worked. Then I just updated ComfyUI through the manager.

**Comment by heiheiheibj** [comment]
I have installed the  January 31 release as you suggested, and the issue has been resolved. Thank you very much.
