### ISSUE TITLE
SD3: 'NoneType' object has no attribute 'tokenize'

### ISSUE THREAD

**Issue by Troyificus** [comfyanonymous/ComfyUI#3690]
Comfy is updated to the latest version. Using the default flow in Comfy with SD3 Medium and getting this error on first run;

```
got prompt
model_type FLOW
Using xformers attention in VAE
Using xformers attention in VAE
no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
!!! Exception during processing!!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Trism\ComfyUI_windows_portable\ComfyUI\nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
AttributeError: 'NoneType' object has no attribute 'tokenize'

Prompt executed in 2.89 seconds
```

**Comment by wanws** [comment]
same question...cannot know how to do..

**Comment by emperinter** [comment]
same issue !

**Comment by emperinter** [comment]
> same issue !

Should be the model does not meet the ComfyUI standard, change a model on the good, the specific principles did not look at, need to refer to the ComfyUI document description, which should be described!

**Comment by w-h-w** [comment]
我也是这个问题stableDiffusion3SD3_sd3Medium
