### ISSUE TITLE
RuntimeError: CUDA error: HIPBLAS_STATUS_NOT_SUPPORTED when calling `HIPBLAS_STATUS_NOT_SUPPORTED`

### ISSUE THREAD

**Issue by KEDI103** [comfyanonymous/ComfyUI#3698]
I tried to run SD 3 but I run into this I also installed amdsmi for be sure its not causing by it.
I got Radeon VII gfx_906
using 
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1
in ubuntu
Also my VRAM getting up to %80
![resim](https://github.com/comfyanonymous/ComfyUI/assets/52115509/3a8717f2-c2ed-4698-86fa-a18d5a9fd040)

heres terminal
```
To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type FLOW
Using split attention in VAE
Using split attention in VAE
no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
clip missing: ['text_projection.weight']
Requested to load SD3ClipModel
Loading 1 new model

rocblaslt warning: No paths matched /media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/lib/hipblaslt/library/*gfx906*co. Make sure that HIPBLASLT_TENSILE_LIBPATH is set correctly.
!!! Exception during processing!!! CUDA error: HIPBLAS_STATUS_NOT_SUPPORTED when calling `HIPBLAS_STATUS_NOT_SUPPORTED`
Traceback (most recent call last):
  File "/media/b_cansin/ai/ai/ComfyUI-master/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/media/b_cansin/ai/ai/ComfyUI-master/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/media/b_cansin/ai/ai/ComfyUI-master/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy_extras/nodes_sd3.py", line 79, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/sd.py", line 142, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/sd3_clip.py", line 104, in encode_token_weights
    lg_out, l_pooled = self.clip_l.encode_token_weights(token_weight_pairs_l)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/sd1_clip.py", line 40, in encode_token_weights
    out, pooled = self.encode(to_encode)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/sd1_clip.py", line 201, in encode
    return self(tokens)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/sd1_clip.py", line 180, in forward
    outputs = self.transformer(tokens, attention_mask, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/clip_model.py", line 134, in forward
    x = self.text_model(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/clip_model.py", line 109, in forward
    x, i = self.encoder(x, mask=mask, intermediate_output=intermediate_output)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/clip_model.py", line 68, in forward
    x = l(x, mask, optimized_attention)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/clip_model.py", line 49, in forward
    x += self.self_attn(self.layer_norm1(x), mask, optimized_attention)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/clip_model.py", line 16, in forward
    q = self.q_proj(x)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/ops.py", line 50, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "/media/b_cansin/ai/ai/ComfyUI-master/comfy/ops.py", line 46, in forward_comfy_cast_weights
    return torch.nn.functional.linear(input, weight, bias)
RuntimeError: CUDA error: HIPBLAS_STATUS_NOT_SUPPORTED when calling `HIPBLAS_STATUS_NOT_SUPPORTED`

Prompt executed in 144.77 seconds

```

**Comment by AngryLoki** [comment]
For some reason Pytorch insists on using majestic hipBLASLt library, which in ROCm 6.1 is supported only by MI250X and MI300X (insert <Spanish Laughing Guy>).

To skip loading of this library, use `TORCH_BLAS_PREFER_HIPBLASLT=0` environment variable.
Note that this variable is supported only since pytorch 2.4.0-rc1 (not in 2.3.1), so install nightly build with
```
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1 --upgrade
```

**Comment by KEDI103** [comment]
> For some reason latest versions of Pytorch insist on using majestic hipBLASLt library, which in ROCm 6.1 is supported only by MI250X and MI300X (insert `<Spanish Laughing Guy>`).
> 
> To skip loading of this library, use `TORCH_BLAS_PREFER_HIPBLASLT=0` environment variable. Note that this variable is supported only since pytorch 2.4.0-rc1 (not in 2.3.1), so install nightly build with
> 
> ```
> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm6.1 --upgrade
> ```
With this it fixed problem. Thank you for your help.
```
cd "/media/b_cansin/ai/ai/ComfyUI-master"
source venv/bin/activate
TORCH_BLAS_PREFER_HIPBLASLT=0 python main.py
```

![resim](https://github.com/comfyanonymous/ComfyUI/assets/52115509/f3409304-690a-4c38-a921-e38ccbeac408)
