### ISSUE TITLE
ModuleNotFoundError: No module named 'comfy_extras.nodes_model_merging'

### ISSUE THREAD

**Issue by Chaoses-Ib** [comfyanonymous/ComfyUI#3702]
```python
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\comfy_extras\nodes_video_model.py", line 6, in <module>
    import comfy_extras.nodes_model_merging
ModuleNotFoundError: No module named 'comfy_extras.nodes_model_merging'

Cannot import D:\ComfyUI\comfy_extras\nodes_video_model.py module for custom nodes: No module named 'comfy_extras.nodes_model_merging'
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\comfy_extras\nodes_model_merging_model_specific.py", line 1, in <module>
    import comfy_extras.nodes_model_merging
ModuleNotFoundError: No module named 'comfy_extras.nodes_model_merging'

Cannot import D:\ComfyUI\comfy_extras\nodes_model_merging_model_specific.py module for custom nodes: No module named 'comfy_extras.nodes_model_merging'
...

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_video_model.py
IMPORT FAILED: nodes_model_merging_model_specific.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt
```
`pip install -r requirements.txt` doesn't help. After I added an empty `__init__.py` in `comfy_extras`, it works again. Is this the right way to solve it? Or did I miss something?

- OS: Windows 11 24H2
- Python version: 3.10.10
- ComfyUI version: 605e64f6d3da44235498bf9103d7aab1c95ef211

**Comment by Chaoses-Ib** [comment]
Ok, I forgot I've installed #298 within the same venv. Uninstalling it fixes the problem.
