### ISSUE TITLE
Exception during processing!!! GET was unable to find an engine to execute this computation

### ISSUE THREAD

**Issue by Maybeetw** [comfyanonymous/ComfyUI#3705]
!!! Exception during processing!!! GET was unable to find an engine to execute this computation
Traceback (most recent call last):
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/nodes.py", line 268, in decode
    return (vae.decode(samples["samples"]), )
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/comfy/sd.py", line 309, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/comfy/ldm/models/autoencoder.py", line 137, in decode
    x = self.decoder(z, **kwargs)
  File "/home/somnus/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/somnus/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 625, in forward
    h = self.conv_in(z)
  File "/home/somnus/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/somnus/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/somnus/0D48B7F718FBAA5C/AIterm/dm/ComfyUI/comfy/ops.py", line 66, in forward
    return super().forward(*args, **kwargs)
  File "/home/somnus/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 460, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/somnus/anaconda3/envs/comfyui/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 456, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation

**Comment by cyscn** [comment]
hello,how did you solve it?

**Comment by Ozanta** [comment]
Same issue, bump

**Comment by FuNian788** [comment]
same issue

**Comment by MadPonyInteractive** [comment]
same issue on my quadro gpu, but all good on my rtx

**Comment by HeadsetGuy** [comment]
same issue, amd gpu

**Comment by RarogCmex** [comment]
This is not ComfyUI issue, but pytorch one.

**Comment by dusieq95** [comment]
how to fix it?

**Comment by KiloTheNeko** [comment]
> This is not ComfyUI issue, but pytorch one.

yeah but what is the solution ?

**Comment by KNIGHTCORE47** [comment]
i also face a similar problem like this, have modify the "comfyui.bat" file as -

@echo off

set "CUDA_LAUNCH_BLOCKING=1"
set "PYTHON=%~dp0venv\Scripts\python.exe"
set "GIT="
set "VENV_DIR=.\venv"

set "COMMANDLINE_ARGS=--auto-launch --use-quad-cross-attention --force-fp16 --reserve-vram 0.7"

set "ZLUDA_COMGR_LOG_LEVEL=1"

the --reserve-vram 0.7 variable is relative to the available vram, for my case 0.7 is the sweet spot.
