### ISSUE TITLE
source code string cannot contain null bytes

### ISSUE THREAD

**Issue by cielglan** [comfyanonymous/ComfyUI#3710]
I am trying to install custom node of Comfyui_image2prompt , comfyui-mixlab-node, ComfyUI_essentials.

These 3 node failed to install and all of them show the same error following. 
I can not install them.

Anyone know how to fix this problem ?

Traceback (most recent call last):
  File "E:\ComfyUI\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials\__init__.py", line 2, in <module>
    from .image import IMAGE_CLASS_MAPPINGS, IMAGE_NAME_MAPPINGS
  File "E:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials\image.py", line 7, in <module>
    import torchvision.transforms.v2 as T
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torchvision\transforms\v2\__init__.py", line 3, in <module>
    from . import functional  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torchvision\transforms\v2\functional\__init__.py", line 3, in <module>
    from ._utils import is_pure_tensor, register_kernel  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torchvision\transforms\v2\functional\_utils.py", line 5, in <module>
    from torchvision import tv_tensors
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torchvision\tv_tensors\__init__.py", line 3, in <module>
    from ._bounding_boxes import BoundingBoxes, BoundingBoxFormat
  File "E:\ComfyUI\python_embeded\Lib\site-packages\torchvision\tv_tensors\_bounding_boxes.py", line 9, in <module>
    from ._tv_tensor import TVTensor
SyntaxError: source code string cannot contain null bytes

**Comment by AngryLoki** [comment]
@cielglan , I remember some antivirus (probably AVG) damages files randomly, filling blocks with null bytes (yeah, it's a nightmare).
You should redownload and unpack ComfyUI again.

**Comment by cielglan** [comment]
@AngryLoki, Thank you for your advice. Oh, it is a really nightmare for me. I will sleep first and then I will try your suggestions. Thank you.
