### ISSUE TITLE
Execution queue error

### ISSUE THREAD

**Issue by cpken** [comfyanonymous/ComfyUI#3723]
Execution queue error（执行队列报错）：
```
got prompt
!!! Exception during processing!!! Error while deserializing header: MetadataIncompleteBuffer
Traceback (most recent call last):
  File "/home/depth/StableDiffusion3Medium/comfyui/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/depth/StableDiffusion3Medium/comfyui/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/depth/StableDiffusion3Medium/comfyui/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/depth/StableDiffusion3Medium/comfyui/nodes.py", line 516, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/home/depth/StableDiffusion3Medium/comfyui/comfy/sd.py", line 464, in load_checkpoint_guess_config
    sd = comfy.utils.load_torch_file(ckpt_path)
  File "/home/depth/StableDiffusion3Medium/comfyui/comfy/utils.py", line 14, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/home/depth/anaconda3/envs/sd3/lib/python3.10/site-packages/safetensors/torch.py", line 311, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: MetadataIncompleteBuffer
```

May I ask how to solve it?（请问如何解决）

**Comment by cwallen** [comment]
When I had this error it was caused by a lora that didn't completely download.
