### ISSUE TITLE
Nodes that have failed to load will show as red on the graph.

### ISSUE THREAD

**Issue by carmancifter** [comfyanonymous/ComfyUI#3753]
I get this error. how can i solve it?

![Screenshot 2024-06-17 080001](https://github.com/comfyanonymous/ComfyUI/assets/77528762/9a694b03-a608-409f-9a8f-ab36cab5c113)

![Screenshot 2024-06-17 080541](https://github.com/comfyanonymous/ComfyUI/assets/77528762/0f1a27ce-773e-4f15-bffc-1d50394c05b8)

**Comment by carmancifter** [comment]
here is my terminal log. I would really appreciate if you help. I've been trying for 5 days.

C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-06-17 15:31:22.837063
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\python_embeded\python.exe
** Log path: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.5 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 65277 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes\__init__.py", line 1, in <module>
    from .nodes.nodes import *
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes\nodes\nodes.py", line 3, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

Cannot import C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes module for custom nodes: No module named 'matplotlib'
### Loading: ComfyUI-Manager (V2.38.1)
### ComfyUI Revision: 2251 [0e06b370] | Released on '2024-06-14'
[VideoHelperSuite] - WARNING - Failed to import imageio_ffmpeg
[VideoHelperSuite] - ERROR - No valid ffmpeg found.
Traceback (most recent call last):
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\__init__.py", line 1, in <module>
    from .videohelpersuite.nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 18, in <module>
    from .load_video_nodes import LoadVideoUpload, LoadVideoPath
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\load_video_nodes.py", line 6, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

Cannot import C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite module for custom nodes: No module named 'cv2'
Command failed with return code: 1
''C:' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\utils.py", line 406, in import_install
    importlib.import_module(package_name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'requirements'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1890, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\__init__.py", line 33, in <module>
    from .endpoint import endlog
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\endpoint.py", line 20, in <module>
    import_install("requirements")
  File "C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\utils.py", line 418, in import_install
    importlib.import_module(package_name)
  File "importlib\__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'requirements'

Cannot import C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb module for custom nodes: No module named 'requirements'

Import times for custom nodes:
   0.0 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds (IMPORT FAILED): C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds (IMPORT FAILED): C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds (IMPORT FAILED): C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.0 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.2 seconds: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\Users\carma\OneDrive\Masaüstü\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]

**Comment by ltdrdata** [comment]
`Masaüstü` This seems not a good directory name. Move ComfyUI_windows_portable to C:\
