### ISSUE TITLE
Convert to group Node : not working properly

### ISSUE THREAD

**Issue by MaraScott** [comfyanonymous/ComfyUI#3850]
When selecting nodes to convert the node workflow is saved but the grouped node do not appear.

Trying to create the groupNode are trying to add the groupNode to the workflow trigger the same error

```
#litegraph.core.js:437 
TypeError: Cannot read properties of undefined (reading '0')
    at new ComfyNode (app.js:1680:50)
    at Object.createNode (litegraph.core.js:435:28)
    at GroupNodeHandler.fromNodes (groupNode.js:1190:31)
    at async HTMLDivElement.callback (groupNode.js:1210:12)
```

I tried to fix this issue, but something is slipping away to me

**Comment by wanglaofei** [comment]
Same question, any solutions? Thanks a lot!
