### ISSUE TITLE
ComfyUI does not start up with Python 3.8 since PR #3903

### ISSUE THREAD

**Issue by MasterIO02** [comfyanonymous/ComfyUI#3937]
### Expected Behavior

ComfyUI starts up.

### Actual Behavior

ComfyUI crashes while loading folder_paths.py

### Steps to Reproduce

Run ComfyUI using Python 3.8: `python3.8 main.py`

### Debug Logs

```powershell
Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import folder_paths
  File "/home/StableDiffusion/StableSwarmUI/dlbackend/ComfyUI/folder_paths.py", line 5, in <module>
    supported_pt_extensions: set[str] = set(['.ckpt', '.pt', '.bin', '.pth', '.safetensors', '.pkl'])
TypeError: 'type' object is not subscriptable
```

### Other

I believe this is caused by #3903 which introduced a typing on the set of supported extensions, which Python 3.8 may not support?
This error does not happen with Python 3.10.

**Comment by MasterIO02** [comment]
Thanks for the fix!
