### ISSUE TITLE
CPU startup, save and execution queue errors

### ISSUE THREAD

**Issue by itmengdl** [comfyanonymous/ComfyUI#3950]
### Expected Behavior

1、点击保存时应该自动保存设置好的文件；
2、执行队列时应该生成图片

1. When you click Save, the set file should be automatically saved;
2. When executing the queue, an image should be generated

### Actual Behavior

1、点击保存时修改好名字，浏览器自动下载该文件
![image](https://github.com/comfyanonymous/ComfyUI/assets/58615896/ec7c8c36-788a-474f-9b79-551493119dca)

2、执行队列时，报错
![image](https://github.com/comfyanonymous/ComfyUI/assets/58615896/a10ec17d-81ed-4a5a-bec9-432729dadcd5)

1. Click Save and modify the name. The browser will automatically download the file.
2. When executing the queue, an error message will be displayed.

### Steps to Reproduce

1、双击 run_cpu.bat启动
2、进入web页面，点击保存
3、输入文件名字，点击确定，文件就自动下载
4、点击添加提示词队列，再点击执行队列，就开始报错了

1. Double-click run_cpu.bat to start
2. Enter the web page and click Save
3. Enter the file name and click OK, the file will be automatically downloaded
4. Click Add prompt word queue, then click Execute queue, and it will start reporting errors

### Debug Logs

```powershell
D:\tools\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --cpu --windows-standalone-build
Total VRAM 16109 MB, total RAM 16109 MB
pytorch version: 2.3.1+cu121
Set vram state to: DISABLED
Device: cpu
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention

Import times for custom nodes:
   0.0 seconds: D:\tools\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\tools\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation-main

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model_type FLOW
got prompt
Using split attention in VAE
Using split attention in VAE
no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
!!! Exception during processing!!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tokenize'

Prompt executed in 5.63 seconds
!!! Exception during processing!!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tokenize'

Prompt executed in 0.00 seconds
got prompt
!!! Exception during processing!!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tokenize'

Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing!!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tokenize'

Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing!!! 'NoneType' object has no attribute 'tokenize'
Traceback (most recent call last):
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\tools\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 57, in encode
    tokens = clip.tokenize(text)
             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'tokenize'

Prompt executed in 0.00 seconds
```

**Comment by mcmonkey4eva** [comment]
The error message is:
`no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.`

Are you attempting to load an SD3 model that doesn't have the textencs included? If so, see the ComfyUI examples page for SD3 workflows.

----

Google Translate:

Google 翻译：
错误消息为：
`检查点中没有 CLIP/文本编码器权重，不会加载文本编码器模型。`

您是否尝试加载未包含文本编码器的 SD3 模型？如果是，请参阅 ComfyUI 示例页面了解 SD3 工作流程。
