### ISSUE TITLE
Install the version of cu121, run an error message

### ISSUE THREAD

**Issue by music1999** [comfyanonymous/ComfyUI#3971]
### Your question

Install the version of cu121, run an error message

### Logs

```powershell
Install the version of cu121, run an error message, and prompt:
Traceback (most recent call last):
File "F: \ Xunlei Download \ ComfyUI_windows_portable \ ComfyUI \ main. py", line 73, in <module>
import comfy.utils
File "F: \ Xunlei Download \ ComfyUI_windows_portable \ ComfyUI \ comfy \ utilities. py", line 1, in<module>
import torch
File "F: \ Xunlei Download \ ComfyUI_windows.portable \ python_embeded \ Lib \ site packages \ torch \ _ init__. py", line 132, in <module>
raise err
OSError: [WinError 127] The specified program cannot be found. Error loading "F: \ Xunlei Download \ ComfyUI_windows_portable \ python_embeded \ Lib \ site packages \ torch \ lib \ nvfusier_codegen. dll" or one of its dependencies
```

**Comment by bluevisor** [comment]
It would be easier to help you if you provide your python version, cuda version, and torch version.

I highly recommend getting a launcher, such as stability matrix or huishi-launcher. managing all this mess by hand is not worth the effort.
