### ISSUE TITLE
reveal:ImportError: cannot import name 'wrap_model' from 'comfy.samplers'

### ISSUE THREAD

**Issue by liang-jing-kai** [comfyanonymous/ComfyUI#4051]
### Expected Behavior

Run comfyui

### Actual Behavior

reveal:ImportError: cannot import name 'wrap_model' from 'comfy.samplers'

### Steps to Reproduce

Run comfyui

### Debug Logs

```powershell
** ComfyUI startup time: 2024-07-18 15:15:44.300340
** Platform: Windows
** Python version: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\ComfyUI-aki-v1.3\venv\Scripts\Python.exe
** Log path: E:\ComfyUI-aki-v1.3\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
   0.0 seconds: E:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager

Total VRAM 16375 MB, total RAM 32578 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: E:\ComfyUI-aki-v1.3\web
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[AnimateDiff] - ERROR - No models available. Please download one and put it in models folder
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['E:\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'E:\\ComfyUI-aki-v1.3\\models\\animatediff_models']
[Crystools INFO] Crystools version: 1.11.0
[Crystools INFO] CPU: 13th Gen Intel(R) Core(TM) i7-13700KF - Arch: AMD64 - OS: Windows 10
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 555.85
### Loading: ComfyUI-Impact-Pack (V4.83.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Inspire-Pack (V0.65.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.9)
### ComfyUI Revision: 2375 [1cde6b2e] | Released on '2024-07-16'
### Loading: Workspace Manager (V1.0.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
E:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
### [START] ComfyUI AlekPet Nodes ###
Node -> ArgosTranslateNode [Loading]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Node -> DeepTranslatorNode [Loading]
Node -> ExtrasNode [Loading]
Node -> GoogleTranslateNode [Loading]
Node -> PainterNode [Loading]
Node -> PoseNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
FizzleDorf Custom Nodes: Loaded
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl
Looking in links: https://pypi.oystermercury.top/
Requirement already satisfied: segment_anything in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from -r requirements.txt (line 1)) (1.0)
Requirement already satisfied: torch in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from -r requirements.txt (line 2)) (2.3.0+cu121)
Requirement already satisfied: numpy in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from -r requirements.txt (line 3)) (1.26.2)
Requirement already satisfied: pillow in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from -r requirements.txt (line 4)) (9.5.0)
Requirement already satisfied: filelock in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (4.12.2)
Requirement already satisfied: sympy in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (1.13.0)
Requirement already satisfied: networkx in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (3.3)
Requirement already satisfied: jinja2 in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (3.1.4)
Requirement already satisfied: fsspec in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (2024.6.1)
Requirement already satisfied: mkl<=2021.4.0,>=2021.1.1 in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from torch->-r requirements.txt (line 2)) (2021.4.0)
Requirement already satisfied: intel-openmp==2021.* in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->-r requirements.txt (line 2)) (2021.4.0)
Requirement already satisfied: tbb==2021.* in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from mkl<=2021.4.0,>=2021.1.1->torch->-r requirements.txt (line 2)) (2021.13.0)
Requirement already satisfied: MarkupSafe>=2.0 in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from jinja2->torch->-r requirements.txt (line 2)) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in e:\webui_forge_cu121_torch21\webui_forge_cu121_torch21\venv\lib\site-packages (from sympy->torch->-r requirements.txt (line 2)) (1.3.0)
Traceback (most recent call last):
  File "E:\ComfyUI-aki-v1.3\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "E:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "E:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (E:\ComfyUI-aki-v1.3\comfy\samplers.py)
```

**Comment by mizukarada** [comment]
Not a ComfyUI bug. Use this [fork](https://github.com/jags111/efficiency-nodes-comfyui/pull/157) for Efficiency Nodes.
