### ISSUE TITLE
Cant start Comfyui after recent update.

### ISSUE THREAD

**Issue by nodegraphics** [comfyanonymous/ComfyUI#4069]
### Your question

All my nodes are appearing red , and no custom nodes are loaded, including comfyui manager. i wasnt sure if the problem is due to update or on my end.

### Logs

```powershell
FETCH DATA from: A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
Error handling request
Traceback (most recent call last):
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 45, in cache_control
    response: web.Response = await handler(request)
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 57, in cors_middleware
    response = await handler(request)
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\server.py", line 447, in get_object_info
    return web.json_response(out)
  File "A:\Program_Files\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_response.py", line 811, in json_response
    text = dumps(data)
  File "json\__init__.py", line 231, in dumps
  File "json\encoder.py", line 199, in encode
  File "json\encoder.py", line 257, in iterencode
  File "json\encoder.py", line 179, in default
TypeError: Object of type method is not JSON serializable
```

**Comment by ltdrdata** [comment]
Disable all custom nodes and restart again.

**Comment by lavibeats** [comment]
did not worked for me :(

**Comment by nodegraphics** [comment]
I moved all the custom nodes to another directory, except for the manager. It worked for me, and I updated everything. However, when I moved my custom nodes back, it didn't work.

As a solution, I reinstalled all the custom nodes by opening a workflow that contains most of my custom nodes (using the "Install Mission Node" feature).

**Comment by lavibeats** [comment]
> I moved all the custom nodes to another directory, except for the manager. It worked for me, and I updated everything. However, when I moved my custom nodes back, it didn't work.
> 
> 
> 
> As a solution, I reinstalled all the custom nodes by opening a workflow that contains most of my custom nodes (using the "Install Mission Node" feature).




I installed different drive still same situation

**Comment by ltdrdata** [comment]
> I moved all the custom nodes to another directory, except for the manager. It worked for me, and I updated everything. However, when I moved my custom nodes back, it didn't work.
> 
> As a solution, I reinstalled all the custom nodes by opening a workflow that contains most of my custom nodes (using the "Install Mission Node" feature).

You need to test by gradually re-enabling custom nodes one by one to identify which specific custom node, when enabled, causes the issue to occur.
