### ISSUE TITLE
IndexError: The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 360, 360, 3] at index 1

### ISSUE THREAD

**Issue by nomoreadj** [comfyanonymous/ComfyUI#4072]
### Your question

when im using [ComfyUI-3D-Pack]/[_Example_Workflows]/CRM MVDiffusion_to_InstantMesh.json
it stopped at node [Comfy3D] Load CRM MVDiffusion Model

### Logs

```powershell
[Load_CRM_MVDiffusion_Model] loaded model ckpt from C:\ComfyUI\custom_nodes\ComfyUI-3D-Pack\Checkpoints\CRM\pixel-diffusion.pth
!!! Exception during processing!!! The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 360, 360, 3] at index 1
Traceback (most recent call last):
File "C:\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 2006, in run_model
pixel_img = torch_imgs_to_pils(reference_image, reference_mask)[0]
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\ComfyUI\custom_nodes\ComfyUI-3D-Pack\shared_utils\image_utils.py", line 29, in torch_imgs_to_pils
images[inv_mask_index] = 0.
~~~~~~^^^^^^^^^^^^^^^^
IndexError: The shape of the mask [1, 64, 64] at index 1 does not match the shape of the indexed tensor [1, 360, 360, 3] at index 1
```

### Other

and I encountered the SAME issue like this, MrForExample/ComfyUI-3D-Pack#215. and i fixed it by following the comment,then i got another issue that I'm asking about.

**Comment by ltdrdata** [comment]
This issue should be handled in ComfyUI-3D-Pack repo.
