### ISSUE TITLE
BUG when using stable audio and saving the result with builtin save audio

### ISSUE THREAD

**Issue by 3blackbar** [comfyanonymous/ComfyUI#4077]
### Expected Behavior

save properly

### Actual Behavior

Requested to load AudioOobleckVAE
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 10.07it/s]
!!! Exception during processing!!! can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\comfy_extras\nodes_audio.py", line 155, in save_audio
    torchaudio.save(buff, waveform, audio["sample_rate"], format="FLAC")
  File "D:\comfyui\python_embeded\Lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
           ^^^^^^^^^^^^^
  File "D:\comfyui\python_embeded\Lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "D:\comfyui\python_embeded\Lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 457, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "D:\comfyui\python_embeded\Lib\site-packages\soundfile.py", line 309, in write
    data = np.asarray(data)
           ^^^^^^^^^^^^^^^^
  File "D:\comfyui\python_embeded\Lib\site-packages\torch\_tensor.py", line 1087, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Prompt executed in 39.09 seconds

### Steps to Reproduce

Just use the workflow 
[SAUDIO.json](https://github.com/user-attachments/files/16325874/SAUDIO.json)

### Debug Logs

```powershell
Requested to load AudioOobleckVAE
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [00:02<00:00, 10.07it/s]
!!! Exception during processing!!! can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI\comfy_extras\nodes_audio.py", line 155, in save_audio
    torchaudio.save(buff, waveform, audio["sample_rate"], format="FLAC")
  File "D:\comfyui\python_embeded\Lib\site-packages\torchaudio\_backend\utils.py", line 313, in save
    return backend.save(
           ^^^^^^^^^^^^^
  File "D:\comfyui\python_embeded\Lib\site-packages\torchaudio\_backend\soundfile.py", line 44, in save
    soundfile_backend.save(
  File "D:\comfyui\python_embeded\Lib\site-packages\torchaudio\_backend\soundfile_backend.py", line 457, in save
    soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
  File "D:\comfyui\python_embeded\Lib\site-packages\soundfile.py", line 309, in write
    data = np.asarray(data)
           ^^^^^^^^^^^^^^^^
  File "D:\comfyui\python_embeded\Lib\site-packages\torch\_tensor.py", line 1087, in __array__
    return self.numpy()
           ^^^^^^^^^^^^
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Prompt executed in 39.09 seconds
```

### Other

I fixed it  on my pc with some code change

**Comment by comfyanonymous** [comment]
Should be fixed now: https://github.com/comfyanonymous/ComfyUI/commit/f836e69346844c65dcf2418346db9a9a9b32a445
