### ISSUE TITLE
_convert elif isinstance(model.model, comfy.model_base.AuraFlow):

### ISSUE THREAD

**Issue by fengtaogogo** [comfyanonymous/ComfyUI#4097]
### Expected Behavior

got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 1222.7403841018677
!!! Exception during processing!!! module 'comfy.model_base' has no attribute 'AuraFlow'
Traceback (most recent call last):
  File "/data/codes/ai_test/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 523, in convert
    return super()._convert(
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 170, in _convert
    elif isinstance(model.model, comfy.model_base.AuraFlow):
AttributeError: module 'comfy.model_base' has no attribute 'AuraFlow'

Prompt executed in 0.98 seconds

### Actual Behavior

got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 1222.7403841018677
!!! Exception during processing!!! module 'comfy.model_base' has no attribute 'AuraFlow'
Traceback (most recent call last):
  File "/data/codes/ai_test/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 523, in convert
    return super()._convert(
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 170, in _convert
    elif isinstance(model.model, comfy.model_base.AuraFlow):
AttributeError: module 'comfy.model_base' has no attribute 'AuraFlow'

Prompt executed in 0.98 seconds

### Steps to Reproduce

got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 1222.7403841018677
!!! Exception during processing!!! module 'comfy.model_base' has no attribute 'AuraFlow'
Traceback (most recent call last):
  File "/data/codes/ai_test/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 523, in convert
    return super()._convert(
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 170, in _convert
    elif isinstance(model.model, comfy.model_base.AuraFlow):
AttributeError: module 'comfy.model_base' has no attribute 'AuraFlow'

Prompt executed in 0.98 seconds

### Debug Logs

```powershell
got prompt
Requested to load SDXL
Loading 1 new model
loading in lowvram mode 1222.7403841018677
!!! Exception during processing!!! module 'comfy.model_base' has no attribute 'AuraFlow'
Traceback (most recent call last):
  File "/data/codes/ai_test/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/data/codes/ai_test/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 523, in convert
    return super()._convert(
  File "/data/codes/ai_test/ComfyUI/custom_nodes/ComfyUI_TensorRT/tensorrt_convert.py", line 170, in _convert
    elif isinstance(model.model, comfy.model_base.AuraFlow):
AttributeError: module 'comfy.model_base' has no attribute 'AuraFlow'

Prompt executed in 0.98 seconds
```

**Comment by ltdrdata** [comment]
You need to upgrade ComfyUI to latest version.
