### ISSUE TITLE
Disappearing parent node

### ISSUE THREAD

**Issue by yincangshiwei** [comfyanonymous/ComfyUI#4111]
### Expected Behavior

Can display/retain the parent node normally

### Actual Behavior

When clicking on the current node, the parent node list will disappear
![ufsmd-skdjg](https://github.com/user-attachments/assets/ee01179f-90fd-4b94-a966-de8a1b681311)

### Steps to Reproduce

Not related to workflow

### Debug Logs

```powershell
[ERROR] An error occurred while retrieving information for the 'CR Select Font' node.
Traceback (most recent call last):
  File "/root/ComfyUI/server.py", line 443, in get_object_info
    out[x] = node_info(x)
  File "/root/ComfyUI/server.py", line 420, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/root/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes/nodes/nodes_graphics_text.py", line 467, in INPUT_TYPES
    file_list = [f for f in os.listdir(font_dir) if os.path.isfile(os.path.join(font_dir, f)) and f.lower().endswith(".ttf")]
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/fonts/truetype'

FETCH DATA from: /root/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
```

**Comment by ltdrdata** [comment]
This issue should be reported to [ComfyUI_Comfyroll_CustomNodes](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/issues) repo.
