### ISSUE TITLE
Launching ComfyUI crashes sound driver

### ISSUE THREAD

**Issue by MNeMoNiCuZ** [comfyanonymous/ComfyUI#4135]
### Expected Behavior

For my sound driver to remain uncrashed :)

### Actual Behavior

When launching ComfyUI, the sound driver apparently crashes. It affects both playing music, and videos. 

### Steps to Reproduce

Launch the program using my setup.

### Debug Logs

```powershell
Activating virtual environment...
Virtual environment activated.
Initializing ComfyUI
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-29 10:19:34.875903
** Platform: Windows
** Python version: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
** Python executable: C:\AI\ComfyUI\venv\Scripts\python.exe
** ComfyUI Path: C:\AI\ComfyUI
** Log path: C:\AI\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\AI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: C:\AI\ComfyUI\custom_nodes\ComfyUI-Marigold
   3.3 seconds: C:\AI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 64727 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\AI\ComfyUI\web
C:\AI\ComfyUI\venv\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Web extensions folder found at C:\AI\ComfyUI\web\extensions\ComfyLiterals
[Allor]: No new updates.
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Adding C:\AI\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from C:\AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from C:\AI\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from C:\AI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from C:\AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from C:\AI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V5.18.14)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V5.18.14)
Loaded ImpactPack nodes from C:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
No module 'xformers'. Proceeding without it.
[Crystools INFO] Crystools version: 1.15.0
[Crystools INFO] CPU: Unknown - Arch: Unknown - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 552.22
Warning, cannot find cuda-compiled version of RoPE2D, using a slow pytorch version instead
Comfy-Easy-Use v1.2.1: Loaded
### ComfyUI-FaceSwap: Check dependencies
### ComfyUI-FaceSwap: Check basic models
Total VRAM 24576 MB, total RAM 64727 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V5.18.14)
### Loading: ComfyUI-Inspire-Pack (V0.82.4)
jjk_util loding
### Loading: ComfyUI-Manager (V2.48.2)
### ComfyUI Revision: 2413 [f82d09c9] | Released on '2024-07-27'
C:\AI\ComfyUI\custom_nodes\ComfyUI-Marigold\nodes.py:44: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  empty_text_embed = torch.load(os.path.join(script_directory, "empty_text_embed.pt"), map_location="cpu")
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available True
edit_mask.available True
## lama torchscript model not found: C:\AI\ComfyUI\models\lama\big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
LaMaInpainting.available True
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
## clip_interrogator_model not found: C:\AI\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: C:\AI\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: C:\AI\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
 --------------
MNeMiC Nodes: Loaded
ComfyUI-N-Sidebar is loading...
[ReActor] - STATUS - Running v0.5.1-a6 in ComfyUI
Torch version: 2.4.0+cu121
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
Imported node: DT_Flatten_Colors
Imported node: DT_FontText
Imported node: DT_GenerateNoise
Imported node: DT_Glitch_This
Imported node: DT_Hue_Rotation
Imported node: DT_Load_Picture_Index
Imported node: DT_PILGram
Imported node: DT_Pixel_Sort
Imported node: DT_Play_Sound_At_Execution
Imported node: DT_PromptGen
Imported node: DT_Solid_Color
Imported node: DT_Swap_Color_Mode
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------


It crashes as soon as it reaches here.
```

### Other

I cannot find anything relevant, and I don't think it's about this node specifically.
It crashes even if I don't have any custom nodes installed.

It started happening a few days ago.
I did a clean checkout and it also happens there.

![image](https://github.com/user-attachments/assets/179f1e8e-52be-428c-b7f8-aeafd0b0138a)

**Comment by ltdrdata** [comment]
First, please disable all custom nodes and check if the same symptom occurs.

**Comment by ltdrdata** [comment]
Try downgrading your PyTorch version and test if the same issue occurs.

**Comment by MNeMoNiCuZ** [comment]
> Try downgrading your PyTorch version and test if the same issue occurs.

Could you please tell me how/which version to downgrade to?

I have the following from my pip list:
```
torch                        2.4.0+cu121
torchaudio                   2.4.0+cu121
torchmetrics                 1.4.0.post0
torchsde                     0.2.6
torchvision                  0.19.0+cu121
```

When I launch without any nodes, it **doesn't** crash the audio.

I still get this warning though:
C:\AI\ComfyUI\venv\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

I'll do some split-tests until I find the node/s causing the issue.

**Comment by ltdrdata** [comment]
Remove them and try this.
`pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121`

**Comment by MNeMoNiCuZ** [comment]
I'll try that.

I have isolated the audio driver crash to these 2 node packs:
https://github.com/dchatel/comfyui_facetools
https://github.com/chflame163/ComfyUI_LayerStyle

**Comment by MNeMoNiCuZ** [comment]
> Remove them and try this.
> 
> ```
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
> ```
> 
> If this method doesn't resolve the issue, I recommend also trying to reinstall the drivers.

After reinstalling torch like this:

```
Activating virtual environment...
Virtual environment activated.
(venv) C:\AI\ComfyUI>pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
Looking in indexes: https://download.pytorch.org/whl/cu121
Collecting torch==2.3.1
  Downloading https://download.pytorch.org/whl/cu121/torch-2.3.1%2Bcu121-cp310-cp310-win_amd64.whl (2423.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 GB 2.9 MB/s eta 0:00:00
Collecting torchvision==0.18.1
  Downloading https://download.pytorch.org/whl/cu121/torchvision-0.18.1%2Bcu121-cp310-cp310-win_amd64.whl (5.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.7/5.7 MB 40.5 MB/s eta 0:00:00
Collecting torchaudio==2.3.1
  Downloading https://download.pytorch.org/whl/cu121/torchaudio-2.3.1%2Bcu121-cp310-cp310-win_amd64.whl (4.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.1/4.1 MB 37.2 MB/s eta 0:00:00
Requirement already satisfied: filelock in c:\ai\comfyui\venv\lib\site-packages (from torch==2.3.1) (3.15.4)
Requirement already satisfied: typing-extensions>=4.8.0 in c:\ai\comfyui\venv\lib\site-packages (from torch==2.3.1) (4.12.2)
Requirement already satisfied: sympy in c:\ai\comfyui\venv\lib\site-packages (from torch==2.3.1) (1.13.1)
Requirement already satisfied: networkx in c:\ai\comfyui\venv\lib\site-packages (from torch==2.3.1) (3.3)
Requirement already satisfied: jinja2 in c:\ai\comfyui\venv\lib\site-packages (from torch==2.3.1) (3.1.4)
Requirement already satisfied: fsspec in c:\ai\comfyui\venv\lib\site-packages (from torch==2.3.1) (2024.5.0)
Collecting mkl<=2021.4.0,>=2021.1.1 (from torch==2.3.1)
  Downloading https://download.pytorch.org/whl/mkl-2021.4.0-py2.py3-none-win_amd64.whl (228.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 228.5/228.5 MB 21.8 MB/s eta 0:00:00
Requirement already satisfied: numpy in c:\ai\comfyui\venv\lib\site-packages (from torchvision==0.18.1) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in c:\ai\comfyui\venv\lib\site-packages (from torchvision==0.18.1) (9.5.0)
Collecting intel-openmp==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1)
  Downloading https://download.pytorch.org/whl/intel_openmp-2021.4.0-py2.py3-none-win_amd64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 37.3 MB/s eta 0:00:00
Collecting tbb==2021.* (from mkl<=2021.4.0,>=2021.1.1->torch==2.3.1)
  Downloading https://download.pytorch.org/whl/tbb-2021.11.0-py3-none-win_amd64.whl (298 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 298.3/298.3 kB ? eta 0:00:00
Requirement already satisfied: MarkupSafe>=2.0 in c:\ai\comfyui\venv\lib\site-packages (from jinja2->torch==2.3.1) (2.1.5)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\ai\comfyui\venv\lib\site-packages (from sympy->torch==2.3.1) (1.3.0)
Installing collected packages: tbb, intel-openmp, mkl, torch, torchvision, torchaudio
  Attempting uninstall: torch
    Found existing installation: torch 2.4.0+cu121
    Uninstalling torch-2.4.0+cu121:
      Successfully uninstalled torch-2.4.0+cu121
  Attempting uninstall: torchvision
    Found existing installation: torchvision 0.19.0+cu121
    Uninstalling torchvision-0.19.0+cu121:
      Successfully uninstalled torchvision-0.19.0+cu121
  Attempting uninstall: torchaudio
    Found existing installation: torchaudio 2.4.0+cu121
    Uninstalling torchaudio-2.4.0+cu121:
      Successfully uninstalled torchaudio-2.4.0+cu121
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ultralyticsplus 0.1.0 requires protobuf<3.21,>=3.20, but you have protobuf 4.25.4 which is incompatible.
Successfully installed intel-openmp-2021.4.0 mkl-2021.4.0 tbb-2021.11.0 torch-2.3.1+cu121 torchaudio-2.3.1+cu121 torchvision-0.18.1+cu121
```

I no longer have this warning:
```
C:\AI\ComfyUI\venv\lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: torch.cuda.amp.custom_fwd(args...) is deprecated. Please use torch.amp.custom_fwd(args..., device_type='cuda') instead.
@torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
```

But when I try to launch with facetools in, I get this error:
```
Traceback (most recent call last):
  File "C:\AI\ComfyUI\main.py", line 264, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\AI\ComfyUI\main.py", line 159, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\AI\ComfyUI\server.py", line 677, in start
    await site.start()
  File "C:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "C:\Python310\lib\asyncio\base_events.py", line 1513, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
```

And LayerStyle gives me this error:
```
Activating virtual environment...
Virtual environment activated.
Initializing ComfyUI
Total VRAM 24576 MB, total RAM 64727 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\AI\ComfyUI\web
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
# 😺dzNodes: LayerStyle -> Warning: C:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Find 1 LUTs in C:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut
# 😺dzNodes: LayerStyle -> Find 1 Fonts in C:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font

Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\custom_nodes\websocket_image_save.py
   2.9 seconds: C:\AI\ComfyUI\custom_nodes\ComfyUI_LayerStyle

Traceback (most recent call last):
  File "C:\AI\ComfyUI\main.py", line 264, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "C:\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\AI\ComfyUI\main.py", line 159, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "C:\AI\ComfyUI\server.py", line 677, in start
    await site.start()
  File "C:\AI\ComfyUI\venv\lib\site-packages\aiohttp\web_runner.py", line 119, in start
    self._server = await loop.create_server(
  File "C:\Python310\lib\asyncio\base_events.py", line 1513, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
```

I never did see these errors before, in my original launching console log.

Both still crash the audio drivers.

**Comment by ltdrdata** [comment]
```
OSError: [Errno 10048] error while attempting to bind on address ('127.0.0.1', 8188): only one usage of each socket address (protocol/network address/port) is normally permitted
```

That means there is a ComfyUI process still running in the background that has not been terminated yet.

**Comment by MNeMoNiCuZ** [comment]
All other comfy terminals were closed. I'll try a reboot to make sure.

**Comment by ltdrdata** [comment]
That error means there's an instance of ComfyUI running somewhere that you're not aware of. Close all terminals and open a new terminal to test it.

**Comment by MNeMoNiCuZ** [comment]
After rebooting, it does no longer show that error message.

The audio crash is still present. The error message appears to have been unrelated.

I am testing with only
https://github.com/dchatel/comfyui_facetools
or 
https://github.com/chflame163/ComfyUI_LayerStyle
individually, one at a time.

They both launch as expected without any error messages.

**Comment by robinjhuang** [comment]
The port error was happening because you already had a ComfyUI instance running. Which git commit are you on for your version of ComfyUI? Can you see if you audio driver still crashes when you don't have any custom nodes installed?

**Comment by MNeMoNiCuZ** [comment]
> The port error was happening because you already had a ComfyUI instance running. Which git commit are you on for your version of ComfyUI? Can you see if you audio driver still crashes when you don't have any custom nodes installed?

1. Yeah. It must have remained even though I had closed all comfy CMD windows. A restart fixed this part with the instances.

2. I'm not 100% sure how to check which version I'm on. Is this the information you are asking for:
```
C:\AI\ComfyUI>git show
commit c75b50607b4ab78ef9c7c5c9e0c8672146ead91b (HEAD -> master, origin/master, origin/HEAD)
Author: comfyanonymous <comfyanonymous@protonmail.com>
Date:   Mon Jul 29 11:15:37 2024 -0400

    Less confusing exception if pillow() function fails.

diff --git a/node_helpers.py b/node_helpers.py
index fee6287..4b38bff 100644
--- a/node_helpers.py
+++ b/node_helpers.py
@@ -25,7 +25,7 @@ def pillow(fn, arg):
     finally:
         if prev_value is not None:
             ImageFile.LOAD_TRUNCATED_IMAGES = prev_value
-        return x
+    return x

 def hasher():
     hashfuncs = {
```

3. It does not appear to crash if I have no custom nodes installed, or if I have 94 other custom node packs installed that work just fine. It only (and always) crashes, if I have either facetools or layerstyle in my custom_nodes folder.

**Comment by ltdrdata** [comment]
> > The port error was happening because you already had a ComfyUI instance running. Which git commit are you on for your version of ComfyUI? Can you see if you audio driver still crashes when you don't have any custom nodes installed?
> 
> 1. Yeah. It must have remained even though I had closed all comfy CMD windows. A restart fixed this part with the instances.
> 2. I'm not 100% sure how to check which version I'm on. Is this the information you are asking for:
> 
> ```
> C:\AI\ComfyUI>git show
> commit c75b50607b4ab78ef9c7c5c9e0c8672146ead91b (HEAD -> master, origin/master, origin/HEAD)
> Author: comfyanonymous <comfyanonymous@protonmail.com>
> Date:   Mon Jul 29 11:15:37 2024 -0400
> 
>     Less confusing exception if pillow() function fails.
> 
> diff --git a/node_helpers.py b/node_helpers.py
> index fee6287..4b38bff 100644
> --- a/node_helpers.py
> +++ b/node_helpers.py
> @@ -25,7 +25,7 @@ def pillow(fn, arg):
>      finally:
>          if prev_value is not None:
>              ImageFile.LOAD_TRUNCATED_IMAGES = prev_value
> -        return x
> +    return x
> 
>  def hasher():
>      hashfuncs = {
> ```
> 
> 3. It does not appear to crash if I have no custom nodes installed, or if I have 94 other custom node packs installed that work just fine. It only (and always) crashes, if I have either facetools or layerstyle in my custom_nodes folder.

In that case, it seems this should be handled in the relevant repository rather than the ComfyUI repo.

**Comment by LichAcademy** [comment]
> Remove them and try this.
> 
> ```
> pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
> ```
> 
> If this method doesn't resolve the issue, I recommend also trying to reinstall the drivers.

This worked for me too. ☝️

**Comment by MNeMoNiCuZ** [comment]
> > Remove them and try this.
> > ```
> > pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If this method doesn't resolve the issue, I recommend also trying to reinstall the drivers.
> 
> This worked for me too. ☝️

What problem were you having? Crashed audio drivers or something else?

**Comment by LichAcademy** [comment]
> > > Remove them and try this.
> > > ```
> > > pip install torch==2.3.1 torchvision==0.18.1 torchaudio==2.3.1 --index-url https://download.pytorch.org/whl/cu121
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > If this method doesn't resolve the issue, I recommend also trying to reinstall the drivers.
> > 
> > 
> > This worked for me too. ☝️
> 
> What problem were you having? Crashed audio drivers or something else?

I encountered a warning when installing ComfyUI manually (as I always did in the past). When you do a Google search for the error, this was the first link:

[comfyui FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.](https://www.google.com/search?q=comfyui+FutureWarning%3A+%60torch.cuda.amp.custom_fwd%28args...%29%60+is+deprecated.+Please+use+%60torch.amp.custom_fwd%28args...%2C+device_type%3D%27cuda%27%29%60+instead.&client=firefox-b-d&sca_esv=ce82090d53e0c143&sxsrf=ADLYWIKzJZcmEJ3J-iJ4gHpuc6j5PMBX0w%3A1722407036259&ei=fNipZta7D4mQseMPvICQkAc&ved=0ahUKEwjW6bec0tCHAxUJSGwGHTwABHIQ4dUDCBA&uact=5&oq=comfyui+FutureWarning%3A+%60torch.cuda.amp.custom_fwd%28args...%29%60+is+deprecated.+Please+use+%60torch.amp.custom_fwd%28args...%2C+device_type%3D%27cuda%27%29%60+instead.&gs_lp=Egxnd3Mtd2l6LXNlcnAikgFjb21meXVpIEZ1dHVyZVdhcm5pbmc6IGB0b3JjaC5jdWRhLmFtcC5jdXN0b21fZndkKGFyZ3MuLi4pYCBpcyBkZXByZWNhdGVkLiBQbGVhc2UgdXNlIGB0b3JjaC5hbXAuY3VzdG9tX2Z3ZChhcmdzLi4uLCBkZXZpY2VfdHlwZT0nY3VkYScpYCBpbnN0ZWFkLjIKECMYsAIYsAMYJzIOEAAYgAQYsAMYhgMYigUyDhAAGIAEGLADGIYDGIoFMgsQABiABBiwAxiiBDILEAAYgAQYsAMYogQyCxAAGIAEGLADGKIESM4JUJcDWJcDcAF4AJABAJgBAKABAKoBALgBA8gBAPgBAvgBAZgCAaACB5gDAOIDBRIBMSBAiAYBkAYGkgcBMaAHAA&sclient=gws-wiz-serp)

Only ComfyUI and Manager were installed at the time, it was a clean Conda environment, nothing there except python.

Do you need exact commands I used?
