### ISSUE TITLE
Can't run comfyui  aiohttp problem?

### ISSUE THREAD

**Issue by pandayummy** [comfyanonymous/ComfyUI#4140]
### Your question

All nodes successfully added.

Traceback (most recent call last):
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\ComfyUI\main.py", line 231, in <module>
    server.add_routes()
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\ComfyUI\server.py", line 573, in add_routes
    self.app.add_routes(api_routes)
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 367, in add_routes
    return self.router.add_routes(routes)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1275, in add_routes
    registered_routes.extend(route_def.register(self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_routedef.py", line 76, in register
    return [reg(self.path, self.handler, **self.kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 1236, in add_get
    resource.add_route(hdrs.METH_HEAD, handler, **kwargs)
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_urldispatcher.py", line 363, in add_route
    raise RuntimeError(
RuntimeError: Added route will never be executed, method HEAD is already registered

C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable>pause
Press any key to continue . . .

**Comment by chrislailiru** [comment]
me too
![Uploading 微信图片_20240730104417.jpg…]()

**Comment by kawaii2020** [comment]
And when I run update_comfyui.bat


stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-07-30_11_39_53
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\update\update.py", line 19, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\repository.py", line 286, in checkout_tree
    payload.check_error(err)
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "C:\Users\CHENG\AppData\Roaming\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: 2 conflicts prevent checkout
Press any key to continue . . .

**Comment by kawaii2020** [comment]
I figured it out, the issue was caused by  https://github.com/Fannovel16/comfyui_controlnet_aux

That plugin is full of bugs, deleted it, and everything is OK now.

@chrislailiru

**Comment by kakaxixx** [comment]
the same question

**Comment by kawaii2020** [comment]
> the same question

just delete **comfyui_controlnet_aux**  in **custom_nodes** folder.

**Comment by quantumsquirrel** [comment]
- same issue in   v0.4.54  
[2025-07-06 15:43:22.090] [info]  Checkpoint files will always be loaded safely.

[2025-07-06 15:43:22.220] [info]  Total VRAM 32607 MB, total RAM 32680 MB
pytorch version: 2.7.0+cu128

[2025-07-06 15:43:22.221] [info]  Set vram state to: NORMAL_VRAM

[2025-07-06 15:43:22.222] [info]  Device: cuda:0 NVIDIA GeForce RTX 5090 : cudaMallocAsync

[2025-07-06 15:43:23.961] [info]  Using pytorch attention

[2025-07-06 15:43:25.848] [error] Traceback (most recent call last):
  File "C:\Users\DarvisCH\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\main.py", line 130, in <module>

[2025-07-06 15:43:25.849] [error]     import server
  File "C:\Users\X\AppData\Local\Programs\@comfyorgcomfyui-electron\resources\ComfyUI\server.py", line 21, in <module>
    import aiohttp
  File "C:\Users\X\Documents\ComfyUI\.venv\Lib\site-packages\aiohttp\__init__.py", line 6, in <module>
    from .client import (
  File "C:\Users\X\Documents\ComfyUI\.venv\Lib\site-packages\aiohttp\client.py", line 40, in <module>
    from . import hdrs, http, payload
  File "C:\Users\X\Documents\ComfyUI\.venv\Lib\site-packages\aiohttp\http.py", line 15, in <module>
    from .http_websocket import (
  File "C:\Users\X\Documents\ComfyUI\.venv\Lib\site-packages\aiohttp\http_websocket.py", line 3, in <module>
    from ._websocket.helpers import WS_KEY, ws_ext_gen, ws_ext_parse
ModuleNotFoundError: No module named 'aiohttp._websocket.helpers'; 'aiohttp._websocket' is not a package

**Comment by ltdrdata** [comment]
> Hi - same issue - have just deleted the controlnet folder - but still same error
> 
> [2025-04-14 07:50:29.328] Traceback (most recent call last): [2025-04-14 07:50:29.328] File "/home/ajo6268/comfyui/ComfyUI/main.py", line 300, in [2025-04-14 07:50:29.328] event_loop, _, start_all_func = start_comfyui() [2025-04-14 07:50:29.328] ^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.332] File "/home/ajo6268/comfyui/ComfyUI/main.py", line 268, in start_comfyui [2025-04-14 07:50:29.332] prompt_server.add_routes() [2025-04-14 07:50:29.332] File "/home/ajo6268/comfyui/ComfyUI/server.py", line 732, in add_routes [2025-04-14 07:50:29.333] self.app.add_routes(api_routes) [2025-04-14 07:50:29.333] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_app.py", line 389, in add_routes [2025-04-14 07:50:29.333] return self.router.add_routes(routes) [2025-04-14 07:50:29.334] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.337] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1281, in add_routes [2025-04-14 07:50:29.337] registered_routes.extend(route_def.register(self)) [2025-04-14 07:50:29.337] ^^^^^^^^^^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.342] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_routedef.py", line 76, in register [2025-04-14 07:50:29.343] return [reg(self.path, self.handler, **self.kwargs)] [2025-04-14 07:50:29.343] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.347] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1242, in add_get [2025-04-14 07:50:29.347] resource.add_route(hdrs.METH_HEAD, handler, **kwargs) [2025-04-14 07:50:29.347] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 367, in add_route [2025-04-14 07:50:29.347] raise RuntimeError( [2025-04-14 07:50:29.348] RuntimeError: Added route will never be executed, method HEAD is already registered

Disable all custom nodes and try again. If the issue is gone, gradually restore some of the custom nodes.

**Comment by adamreading** [comment]
> > Hi - same issue - have just deleted the controlnet folder - but still same error
> > [2025-04-14 07:50:29.328] Traceback (most recent call last): [2025-04-14 07:50:29.328] File "/home/ajo6268/comfyui/ComfyUI/main.py", line 300, in [2025-04-14 07:50:29.328] event_loop, _, start_all_func = start_comfyui() [2025-04-14 07:50:29.328] ^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.332] File "/home/ajo6268/comfyui/ComfyUI/main.py", line 268, in start_comfyui [2025-04-14 07:50:29.332] prompt_server.add_routes() [2025-04-14 07:50:29.332] File "/home/ajo6268/comfyui/ComfyUI/server.py", line 732, in add_routes [2025-04-14 07:50:29.333] self.app.add_routes(api_routes) [2025-04-14 07:50:29.333] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_app.py", line 389, in add_routes [2025-04-14 07:50:29.333] return self.router.add_routes(routes) [2025-04-14 07:50:29.334] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.337] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1281, in add_routes [2025-04-14 07:50:29.337] registered_routes.extend(route_def.register(self)) [2025-04-14 07:50:29.337] ^^^^^^^^^^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.342] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_routedef.py", line 76, in register [2025-04-14 07:50:29.343] return [reg(self.path, self.handler, **self.kwargs)] [2025-04-14 07:50:29.343] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ [2025-04-14 07:50:29.347] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 1242, in add_get [2025-04-14 07:50:29.347] resource.add_route(hdrs.METH_HEAD, handler, **kwargs) [2025-04-14 07:50:29.347] File "/home/ajo6268/envs/comfyui/lib/python3.12/site-packages/aiohttp/web_urldispatcher.py", line 367, in add_route [2025-04-14 07:50:29.347] raise RuntimeError( [2025-04-14 07:50:29.348] RuntimeError: Added route will never be executed, method HEAD is already registered
> 
> Disable all custom nodes and try again. If the issue is gone, gradually restore some of the custom nodes.

to be fair this is 3 months old - I can't even remember what the heck i was trying to do back then....
