### ISSUE TITLE
Error loading "g:\ComfyUI\.venv\Lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies

### ISSUE THREAD

**Issue by long3012218885** [comfyanonymous/ComfyUI#4172]
### Your question

![image](https://github.com/user-attachments/assets/f7162d20-923b-4f6d-a389-d5d1bc0997b9)

### Logs

```powershell
G:\ComfyUI>python server.py
Traceback (most recent call last):
  File "G:\ComfyUI\server.py", line 6, in <module>
    import nodes
  File "G:\ComfyUI\nodes.py", line 1, in <module>
    import torch
  File "g:\ComfyUI\.venv\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] 找不到指定的模块。 Error loading "g:\ComfyUI\.venv\Lib\site-packages\torch\lib\torch_python.dll" or one of its dependencies.
```

**Comment by Buumcode** [comment]
Error [WinError 126] is error about DLL dependencies. You have DLL, but your DLL trying to connect to other DLL's - dependecied DLL's - which you don't have.
Example: I have Windows 7 and have this error:
OSError: [WinError 126] The specified module could not be found. Error loading "C:\ComfyUI_v0.0.2\python_embeded\Lib\site-packages\torch\lib\c10_cuda.dll" or one of its dependencies.
https://www.dependencywalker.com/ show me that for c10_cuda.dll. As you can see, my c10_cuda.dll can't find dependencies DLL's. So I need to find them and install.
![Dependency_walker_c10_cuda-dll_snap](https://github.com/user-attachments/assets/2d5462c0-5db9-4eca-b14e-e025ac99398c)

**Comment by Buumcode** [comment]
LOL, I find all this DLL's on https://ru.dll-files.com/ and manually install all of them. And... They immediately asking me for more DLL's – first of in list is unsearcheable on this site. OK, I'm off )
![Dependency_walker_c10_cuda-dll_snap_3](https://github.com/user-attachments/assets/d7f6953c-827e-4b99-89a2-6fd9a774c08e)

**Comment by DiegoRRR** [comment]
Are you trying to use a recent version of ComfyUI on Windows 7? I am also trying to use ComfyUI on Windows 7. I read that Comfy now needs Cuda 12 while Windows 7 can only use Cuda dlls up to Cuda 11. Because of this the last version we can use is from 28 april 2023, that you can find here under the "assets" rollup : https://github.com/comfyanonymous/ComfyUI/releases . Maybe this can help you.
