### ISSUE TITLE
Unet loader error with the Flux Example workflow

### ISSUE THREAD

**Issue by Aura-anon** [comfyanonymous/ComfyUI#4188]
### Expected Behavior

Expect the workflow to work even if I may not have computer good enough

### Actual Behavior

Doesn't load the first node, I get an Unet loader error

![image](https://github.com/user-attachments/assets/2349b761-899d-4268-a230-923b3bee7d9e)

### Steps to Reproduce

download flux1 schnell
update comfyui
download vae ae.sft 
run the second example workflow here https://comfyanonymous.github.io/ComfyUI_examples/flux/

### Debug Logs

```powershell
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: S:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\extension-node-map.json [DONE]
got prompt
!!! Exception during processing!!! Expected a torch.device with a specified index or an integer, but got:cuda
Traceback (most recent call last):
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\nodes.py", line 836, in load_unet
    model = comfy.sd.load_unet(unet_path, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 627, in load_unet
    model = load_unet_state_dict(sd, dtype=dtype)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 611, in load_unet_state_dict
    unet_dtype = model_management.unet_dtype(model_params=parameters, supported_dtypes=model_config.supported_inference_dtypes)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 560, in unet_dtype
    if should_use_bf16(device, model_params=model_params, manual_cast=True):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 941, in should_use_bf16
    free_model_memory = maximum_vram_for_weights(device)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 531, in maximum_vram_for_weights
    return (get_total_memory(device) * 0.8 - minimum_inference_memory())
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 110, in get_total_memory
    _, mem_total_cuda = torch.cuda.mem_get_info(dev)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\memory.py", line 654, in mem_get_info
    device = _get_device_index(device)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\_utils.py", line 38, in _get_device_index
    return _torch_get_device_index(device, optional, allow_cpu)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\SD\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_utils.py", line 815, in _get_device_index
    raise ValueError(
ValueError: Expected a torch.device with a specified index or an integer, but got:cuda

Prompt executed in 0.19 seconds
```

### Other

computer: 1080Ti, 16gb ram, r7 1700x

**Comment by comfyanonymous** [comment]
That's fixed now, update.
