### ISSUE TITLE
Loading aborted due to error reloading workflow data

### ISSUE THREAD

**Issue by GrenKain** [comfyanonymous/ComfyUI#4192]
### Expected Behavior

Loading workflow

### Actual Behavior

The error appeared after updating ComfyUI
I moved the workflow to the workspace and it should load.
They all overlapped each other.
![Screenshot_4](https://github.com/user-attachments/assets/4204bca6-6d55-40fc-a4aa-f1527329c119)
![Screenshot_5](https://github.com/user-attachments/assets/d8e79d40-d8c9-41ef-8926-6a5f6cf7cbc6)
![Screenshot_6](https://github.com/user-attachments/assets/10e11eb1-0eba-4a2a-8f6b-ba64d0055c7f)

### Steps to Reproduce

Loading workflow

### Debug Logs

```powershell
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading '_overwrited')
TypeError: Cannot read properties of undefined (reading '_overwrited')
    at nodeDrawProfiler (http://127.0.0.1:8188/extensions/comfyui-profiler/index.js:30:29)
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/comfyui-profiler/index.js:66:7)
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:136:28)
    at app.graph.onNodeAdded (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:136:28)
    at LGraph.add (http://127.0.0.1:8188/lib/litegraph.core.js:1465:18)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2232:22)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1416:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:160:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1900:15)
This may be due to the following script:
/extensions/comfyui-profiler/index.js
```

**Comment by ltdrdata** [comment]
It seems that your workflow is invalid.

**Comment by ltdrdata** [comment]
Disable `comfyui-profiler` extension and try again.

**Comment by GrenKain** [comment]
Thank you, it helped me
