### ISSUE TITLE
New Update causes Pytorch error

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#4218]
### Expected Behavior

Launch Comfy

### Actual Behavior

Traceback (most recent call last):
  File "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\main.py", line 83, in <module>
    import comfy.utils
  File "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.

### Steps to Reproduce

update

### Debug Logs

```powershell
Traceback (most recent call last):
  File "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\main.py", line 83, in <module>
    import comfy.utils
  File "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\comfy\utils.py", line 1, in <module>
    import torch
  File "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "\\newestgtx1650\18 tb\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\torch\lib\shm.dll" or one of its dependencies.
```

**Comment by BrechtCorbeel** [comment]
currently testing upgrading torch to 24.0 otherwise it will be a down grade, but I do not know which torch package this is stemming from there are 5 different ones in the library

**Comment by BrechtCorbeel** [comment]
Fixed it. don't know if it was 24.0 upgrade or I did a second overall update via stabilty matrix
