### ISSUE TITLE
First run error:  ModuleNotFoundError: No module named 'transformers.utils'   Windows+Cuda

### ISSUE THREAD

**Issue by Fredrum** [comfyanonymous/ComfyUI#4225]
### Your question

Hi!
I'm attempting to re-install a fresh ComfyUI on my Win11 PC with NVidia 3060.

I have cuda pytorch installed.
Did git clone on the repo.
Ran the requirements install as instructed.

Tried to start with:
python .\main.py

But 'm getting the error message:

  File "D:\ai\ComfyUI\comfy\supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "D:\ai\ComfyUI\comfy\sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "C:\Users\fred_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\fred_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
ModuleNotFoundError: No module named 'transformers.utils'

Any ideas why this is erroring?

Cheers
Fred

### Logs

```powershell
PS D:\ai\ComfyUI> python .\main.py
Total VRAM 12288 MB, total RAM 65303 MB
pytorch version: 2.4.0+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\ai\ComfyUI\main.py", line 86, in <module>
    import execution
  File "D:\ai\ComfyUI\execution.py", line 12, in <module>
    import nodes
  File "D:\ai\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "D:\ai\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\ai\ComfyUI\comfy\sd.py", line 17, in <module>
    from . import model_detection
  File "D:\ai\ComfyUI\comfy\model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "D:\ai\ComfyUI\comfy\supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "D:\ai\ComfyUI\comfy\sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "C:\Users\fred_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "C:\Users\fred_\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
ModuleNotFoundError: No module named 'transformers.utils'
```

**Comment by ltdrdata** [comment]
You have to use portable version or venv.

**Comment by Fredrum** [comment]
Ok thank you I'll try that next time!
Ended up using the downloadable zip file and that worked ok.
