### ISSUE TITLE
Broken update.

### ISSUE THREAD

**Issue by tounsicorp** [comfyanonymous/ComfyUI#4228]
### Expected Behavior

main.py no longer starts, crashes constantly.  Gives error claiming torch doesn't exist, yet it's there and verified.

## ComfyUI-Manager: installing dependencies done.
[2024-08-05 15:41] ** ComfyUI startup time: 2024-08-05 15:41:15.056232
[2024-08-05 15:41] ** Platform: Windows
[2024-08-05 15:41] ** Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
[2024-08-05 15:41] ** Python executable: C:\Python312\python.exe
[2024-08-05 15:41] ** ComfyUI Path: B:\STABLE LOCAL\Comfy\ComfyUI
[2024-08-05 15:41] ** Log path: B:\STABLE LOCAL\Comfy\ComfyUI\comfyui.log
[2024-08-05 15:41] Downloading SVD model: svd.safetensors...
[2024-08-05 15:41] Downloading SVD model: svd_image_decoder.safetensors...
[2024-08-05 15:41] Downloading SVD model: svd_xt.safetensors...
[2024-08-05 15:41] Downloading SVD model: svd_xt_image_decoder.safetensors...
[2024-08-05 15:41] 
Prestartup times for custom nodes:
[2024-08-05 15:41]    0.0 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\rgthree-comfy
[2024-08-05 15:41]    0.6 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-08-05 15:41]    0.6 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
[2024-08-05 15:41] 
Traceback (most recent call last):
[2024-08-05 15:41]   File "B:\STABLE LOCAL\Comfy\ComfyUI\main.py", line 77, in <module>
[2024-08-05 15:41]     import comfy.utils
[2024-08-05 15:41]   File "B:\STABLE LOCAL\Comfy\ComfyUI\comfy\utils.py", line 1, in <module>
[2024-08-05 15:41]     import torch
[2024-08-05 15:41] ModuleNotFoundError: No module named 'torch'

### Steps to Reproduce

Constant repeated after update. 

### Debug Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2024-08-05 15:41] ** ComfyUI startup time: 2024-08-05 15:41:15.056232
[2024-08-05 15:41] ** Platform: Windows
[2024-08-05 15:41] ** Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
[2024-08-05 15:41] ** Python executable: C:\Python312\python.exe
[2024-08-05 15:41] ** ComfyUI Path: B:\STABLE LOCAL\Comfy\ComfyUI
[2024-08-05 15:41] ** Log path: B:\STABLE LOCAL\Comfy\ComfyUI\comfyui.log
[2024-08-05 15:41] Downloading SVD model: svd.safetensors...
[2024-08-05 15:41] Downloading SVD model: svd_image_decoder.safetensors...
[2024-08-05 15:41] Downloading SVD model: svd_xt.safetensors...
[2024-08-05 15:41] Downloading SVD model: svd_xt_image_decoder.safetensors...
[2024-08-05 15:41] 
Prestartup times for custom nodes:
[2024-08-05 15:41]    0.0 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\rgthree-comfy
[2024-08-05 15:41]    0.6 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-08-05 15:41]    0.6 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
[2024-08-05 15:41] 
Traceback (most recent call last):
[2024-08-05 15:41]   File "B:\STABLE LOCAL\Comfy\ComfyUI\main.py", line 77, in <module>
[2024-08-05 15:41]     import comfy.utils
[2024-08-05 15:41]   File "B:\STABLE LOCAL\Comfy\ComfyUI\comfy\utils.py", line 1, in <module>
[2024-08-05 15:41]     import torch
[2024-08-05 15:41] ModuleNotFoundError: No module named 'torch'
```

**Comment by NPDX909** [comment]
What happens when u reinstall torch using nightly build

pip uninstall torch
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124

**Comment by tounsicorp** [comment]
> What happens when u reinstall torch using nightly build
> 
> pip uninstall torch pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu124

Same stuff.  new module though



## ComfyUI-Manager: installing dependencies done.
[2024-08-05 15:54] ** ComfyUI startup time: 2024-08-05 15:54:49.360015
[2024-08-05 15:54] ** Platform: Windows
[2024-08-05 15:54] ** Python version: 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
[2024-08-05 15:54] ** Python executable: C:\Python312\python.exe
[2024-08-05 15:54] ** ComfyUI Path: B:\STABLE LOCAL\Comfy\ComfyUI
[2024-08-05 15:54] ** Log path: B:\STABLE LOCAL\Comfy\ComfyUI\comfyui.log
[2024-08-05 15:54] Downloading SVD model: svd.safetensors...
[2024-08-05 15:54] Downloading SVD model: svd_image_decoder.safetensors...
[2024-08-05 15:54] Downloading SVD model: svd_xt.safetensors...
[2024-08-05 15:54] Downloading SVD model: svd_xt_image_decoder.safetensors...
[2024-08-05 15:54] 
Prestartup times for custom nodes:
[2024-08-05 15:54]    0.0 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\rgthree-comfy
[2024-08-05 15:54]    0.6 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
[2024-08-05 15:54]    0.8 seconds: B:\STABLE LOCAL\Comfy\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-08-05 15:54] 
Traceback (most recent call last):
[2024-08-05 15:54]   File "B:\STABLE LOCAL\Comfy\ComfyUI\main.py", line 80, in <module>
[2024-08-05 15:54]     import execution
[2024-08-05 15:54]   File "B:\STABLE LOCAL\Comfy\ComfyUI\execution.py", line 11, in <module>
[2024-08-05 15:54]     import nodes
[2024-08-05 15:54]   File "B:\STABLE LOCAL\Comfy\ComfyUI\nodes.py", line 21, in <module>
[2024-08-05 15:54]     import comfy.diffusers_load
[2024-08-05 15:54]   File "B:\STABLE LOCAL\Comfy\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
[2024-08-05 15:54]     import comfy.sd
[2024-08-05 15:54]   File "B:\STABLE LOCAL\Comfy\ComfyUI\comfy\sd.py", line 5, in <module>
[2024-08-05 15:54]     from comfy import model_management
[2024-08-05 15:54]   File "B:\STABLE LOCAL\Comfy\ComfyUI\comfy\model_management.py", line 1, in <module>
[2024-08-05 15:54]     import psutil
[2024-08-05 15:54] ModuleNotFoundError: No module named 'psutil'

**Comment by tounsicorp** [comment]
Also broke FaceRestoreCFWithModel
FaceRestoreModelLoader
ReActorFaceSwap
systems.

**Comment by BrechtCorbeel** [comment]
> ] ModuleNotFoundError: No module named 'psutil'

I instaled Torch 24.0 it defaulted to downloading 23.0, but I also did an overall update, which I did with smatrix, which I run comfy through, so unsure if one or the other fixed it.
