### ISSUE TITLE
Cannot load multipart safetensors

### ISSUE THREAD

**Issue by flywhc** [comfyanonymous/ComfyUI#4256]
### Expected Behavior

Tried to load a model from:
[](https://huggingface.co/sayakpaul/FLUX.1-merged)

It is a multipart safetensors contains three files:
```
diffusion_pytorch_model-00001-of-00003.safetensors
diffusion_pytorch_model-00002-of-00003.safetensors
diffusion_pytorch_model-00003-of-00003.safetensors
```

Automatic11111 SD can load this model by selecting the first safetensors file.

### Actual Behavior

ComfyUI throw Exception:
```
Traceback (most recent call last):
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\nodes.py", line 518, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 518, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\AIGC\sd.webui\webui\models/Stable-diffusion\diffusion_pytorch_model-00001-of-00003.safetensors

```

### Steps to Reproduce

Load Checkpoint and select diffusion_pytorch_model-00001-of-00003.safetensors.
![image](https://github.com/user-attachments/assets/10c3cfd9-ec11-4a51-9b59-482f0606159c)

### Debug Logs

```powershell
To see the GUI go to: http://127.0.0.1:8188
got prompt
!!! Exception during processing!!! ERROR: Could not detect model type of: C:\AIGC\sd.webui\webui\models/Stable-diffusion\diffusion_pytorch_model-00001-of-00003.safetensors
Traceback (most recent call last):
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\nodes.py", line 518, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AIGC\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 518, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\AIGC\sd.webui\webui\models/Stable-diffusion\diffusion_pytorch_model-00001-of-00003.safetensors
```

**Comment by sahibalejandro** [comment]
Hello y'all! Any ideas on how to achieve this?

**Comment by FunnyWii** [comment]
> Hello y'all! Any ideas on how to achieve this?

Same issue, how did you solve that?
