### ISSUE TITLE
AttributeError: 'ModelPatcher' object has no attribute 'current_device'

### ISSUE THREAD

**Issue by klossm** [comfyanonymous/ComfyUI#4269]
### Your question

Comfyui_Fooocus_promptExpansion This plugin gives an error in the latest version of comfyui, the old version of comfyui doesn't have this problem.

### Logs

```powershell
Traceback (most recent call last):
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "L:\stable-diffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\Comfyui_Fooocus_promptExpansion\prompt_expansion.py", line 171, in expand_prompt
    final_prompt = expansion(prompt, seed)
  File "L:\stable-diffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\stable-diffusion\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "L:\stable-diffusion\extensions\sd-webui-comfyui\ComfyUI\custom_nodes\Comfyui_Fooocus_promptExpansion\prompt_expansion.py", line 110, in __call__
    if self.patcher.current_device != self.patcher.load_device:
AttributeError: 'ModelPatcher' object has no attribute 'current_device'
```

**Comment by iamterryclark** [comment]
i  updated all my installed nodes and this seems to resolve it,. using 0.0.4

**Comment by WXS051** [comment]
按照楼上的做法，问题已经解决，谢谢
