### ISSUE TITLE
AttributeError: 'ModelPatcher' object has no attribute 'current_device'

### ISSUE THREAD

**Issue by haisheng666** [comfyanonymous/ComfyUI#4278]
### Expected Behavior

My comfyui and animatediff evolved are both the latest versions. Please solve this problem.

### Actual Behavior

[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt
Model doesn't have a device attribute.
!!! Exception during processing!!! 'ModelPatcher' object has no attribute 'current_device'
Traceback (most recent call last):
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes_gen1.py", line 160, in load_mm_and_inject_params
    model = ModelPatcherAndInjector.create_from(model, hooks_only=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 96, in create_from
    return ModelPatcherAndInjector(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 39, in __init__
    super().__init__(m.model, m.load_device, m.offload_device, m.size, m.current_device, weight_inplace_update=m.weight_inplace_update)
                                                                       ^^^^^^^^^^^^^^^^
AttributeError: 'ModelPatcher' object has no attribute 'current_device'

#12 [ADE_AnimateDiffLoaderWithContext]: 7.55s
Prompt executed in 26.52 seconds

### Steps to Reproduce

[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt
Model doesn't have a device attribute.
!!! Exception during processing!!! 'ModelPatcher' object has no attribute 'current_device'
Traceback (most recent call last):
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes_gen1.py", line 160, in load_mm_and_inject_params
    model = ModelPatcherAndInjector.create_from(model, hooks_only=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 96, in create_from
    return ModelPatcherAndInjector(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 39, in __init__
    super().__init__(m.model, m.load_device, m.offload_device, m.size, m.current_device, weight_inplace_update=m.weight_inplace_update)
                                                                       ^^^^^^^^^^^^^^^^
AttributeError: 'ModelPatcher' object has no attribute 'current_device'

#12 [ADE_AnimateDiffLoaderWithContext]: 7.55s
Prompt executed in 26.52 seconds

### Debug Logs

```powershell
[AnimateDiffEvo] - INFO - Loading motion module v3_sd15_mm.ckpt
Model doesn't have a device attribute.
!!! Exception during processing!!! 'ModelPatcher' object has no attribute 'current_device'
Traceback (most recent call last):
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\nodes_gen1.py", line 160, in load_mm_and_inject_params
    model = ModelPatcherAndInjector.create_from(model, hooks_only=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 96, in create_from
    return ModelPatcherAndInjector(model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ProgramFilesSingle\huishi_launcher_2\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\model_injection.py", line 39, in __init__
    super().__init__(m.model, m.load_device, m.offload_device, m.size, m.current_device, weight_inplace_update=m.weight_inplace_update)
                                                                       ^^^^^^^^^^^^^^^^
AttributeError: 'ModelPatcher' object has no attribute 'current_device'

#12 [ADE_AnimateDiffLoaderWithContext]: 7.55s
Prompt executed in 26.52 seconds
```

### Other

My comfyui and animatediff evolved are both the latest versions. Please solve this problem.

**Comment by comfyanonymous** [comment]
Are you sure? I'm pretty sure this was fixed in animatediff evolved.

**Comment by haisheng666** [comment]
Problem solved. Thank you very much

**Comment by musyc1009** [comment]
I updated everything and still getting this error

**Comment by zboing** [comment]
Problem solved only by deleting AnimateDiff-Evolved folder and installed it as new. The update procedure didn't worked.

**Comment by aetherwu** [comment]
> Problem solved only by deleting AnimateDiff-Evolved folder and installed it as new. The update procedure didn't worked.

I second it.
I deleted the old node folder and reinstalled it - it fixed and works fine now.
