### ISSUE TITLE
Last update (a3cc3267489bfd44e5a994d98d52481c0cc80730) broke SamplerCustomAdvanced node

### ISSUE THREAD

**Issue by San4itos** [comfyanonymous/ComfyUI#4289]
### Expected Behavior

Expecting to have no errors

### Actual Behavior

Last update broke the SamplerCustomAdvanced node.
```
Error occurred when executing SamplerCustomAdvanced:

list index out of range

File "/home/san4itos/ComfyUI/execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "/home/san4itos/ComfyUI/execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "/home/san4itos/ComfyUI/execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "/home/san4itos/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 612, in sample
samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
File "/home/san4itos/ComfyUI/comfy/samplers.py", line 706, in sample
self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
File "/home/san4itos/ComfyUI/comfy/sampler_helpers.py", line 66, in prepare_sampling
comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
File "/home/san4itos/ComfyUI/comfy/model_management.py", line 517, in load_models_gpu
cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
File "/home/san4itos/ComfyUI/comfy/model_management.py", line 319, in model_load
raise e
File "/home/san4itos/ComfyUI/comfy/model_management.py", line 313, in model_load
self.real_model = self.model.patch_model_lowvram(device_to=patch_model_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
File "/home/san4itos/ComfyUI/comfy/model_patcher.py", line 421, in patch_model_lowvram
self.lowvram_load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
File "/home/san4itos/ComfyUI/comfy/model_patcher.py", line 399, in lowvram_load
weight = param[0]
```

### Steps to Reproduce

Load Flux Dev example workflow and press "Queue Prompt" button.

### Debug Logs

```powershell
Total VRAM 16368 MB, total RAM 31713 MB
pytorch version: 2.4.0+rocm6.1
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7800 XT : native
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
[Prompt Server] web root: /home/san4itos/ComfyUI/web
/home/san4itos/miniconda3/envs/sd_env/lib/python3.10/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: /home/san4itos/ComfyUI/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
/home/san4itos/miniconda3/envs/sd_env/lib/python3.10/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Model doesn't have a device attribute.
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
Requested to load Flux
Loading 1 new model
!!! Exception during processing!!! list index out of range
Traceback (most recent call last):
  File "/home/san4itos/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/san4itos/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/san4itos/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/san4itos/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 612, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "/home/san4itos/ComfyUI/comfy/samplers.py", line 706, in sample
    self.inner_model, self.conds, self.loaded_models = comfy.sampler_helpers.prepare_sampling(self.model_patcher, noise.shape, self.conds)
  File "/home/san4itos/ComfyUI/comfy/sampler_helpers.py", line 66, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, memory_required=memory_required, minimum_memory_required=minimum_memory_required)
  File "/home/san4itos/ComfyUI/comfy/model_management.py", line 517, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/home/san4itos/ComfyUI/comfy/model_management.py", line 319, in model_load
    raise e
  File "/home/san4itos/ComfyUI/comfy/model_management.py", line 313, in model_load
    self.real_model = self.model.patch_model_lowvram(device_to=patch_model_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/home/san4itos/ComfyUI/comfy/model_patcher.py", line 421, in patch_model_lowvram
    self.lowvram_load(device_to, lowvram_model_memory=lowvram_model_memory, force_patch_weights=force_patch_weights)
  File "/home/san4itos/ComfyUI/comfy/model_patcher.py", line 399, in lowvram_load
    weight = param[0]
IndexError: list index out of range

Prompt executed in 38.31 seconds
```

**Comment by rbbrdckybk** [comment]
Having the same issue. No errors if I revert to ```e545a63```.

**Comment by retronomi** [comment]
Same here

**Comment by makeitrad** [comment]
Same issue here, same errors as well...

**Comment by marduk191** [comment]
yup, this happened lol

**Comment by JorgeR81** [comment]
The same error also happens with the regular KSampler node, using Flux.

`IndexError: list index out of range`

**Comment by comfyanonymous** [comment]
Should be fixed now sorry about that.

**Comment by makeitrad** [comment]
> Should be fixed now sorry about that.

Confirmed working. Thanks Comfy!

**Comment by marduk191** [comment]
crisis averted.
