### ISSUE TITLE
FLUX error 'conv_in.weight'

### ISSUE THREAD

**Issue by drago87** [comfyanonymous/ComfyUI#4317]
### Your question

When i try to run comfyui with FLUX i get the error 'conv_in.weight' i'm using the [flux_schnell_example](https://github.com/user-attachments/assets/f4211f70-eab3-458d-88fa-aaba301f76ac) with the 11.9 gb [schnell fb8](https://huggingface.co/Kijai/flux-fp8) unet version. I'm also getting the same error with [flux.1 schnell FP8 Kijai 11GB](https://civitai.com/models/618486?modelVersionId=694756). Is there a fix for this?
Also the DualClipLoader is missing the 'Flux' setting under 'Type' it only have 'sdxl' and 'sd3'

### Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2024-08-11 22:39] ** ComfyUI startup time: 2024-08-11 22:39:38.854741
[2024-08-11 22:39] ** Platform: Windows
[2024-08-11 22:39] ** Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
[2024-08-11 22:39] ** Python executable: D:\AI\pinokio\api\comfyui.git\app\env\Scripts\python.exe
[2024-08-11 22:39] ** ComfyUI Path: D:\AI\pinokio\api\comfyui.git\app
[2024-08-11 22:39] ** Log path: D:\AI\pinokio\api\comfyui.git\app\comfyui.log
[2024-08-11 22:39] 
Prestartup times for custom nodes:
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\rgthree-comfy
[2024-08-11 22:39]    4.8 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager
[2024-08-11 22:39] 
Total VRAM 16379 MB, total RAM 32679 MB
[2024-08-11 22:39] pytorch version: 2.3.0+cu121
[2024-08-11 22:39] Set vram state to: NORMAL_VRAM
[2024-08-11 22:39] Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
[2024-08-11 22:39] Using pytorch cross attention
[2024-08-11 22:39] [Prompt Server] web root: D:\AI\pinokio\api\comfyui.git\app\web
[2024-08-11 22:39] Adding extra search path blip G:/AI/models\blip/
[2024-08-11 22:39] Adding extra search path checkpoints G:/AI/models\checkpoints/
[2024-08-11 22:39] Adding extra search path clip G:/AI/models\clip/
[2024-08-11 22:39] Adding extra search path clip_vision G:/AI/models\clip_vision/
[2024-08-11 22:39] Adding extra search path codeformer G:/AI/models\Codeformer/
[2024-08-11 22:39] Adding extra search path configs G:/AI/models\configs/
[2024-08-11 22:39] Adding extra search path controlnet G:/AI/models\controlnet/
[2024-08-11 22:39] Adding extra search path deepbooru G:/AI/models\deepbooru/
[2024-08-11 22:39] Adding extra search path diffusers G:/AI/models\diffusers/
[2024-08-11 22:39] Adding extra search path embeddings G:/AI/models\embeddings/
[2024-08-11 22:39] Adding extra search path ESRGAN G:/AI/models\ESRGAN/
[2024-08-11 22:39] Adding extra search path GFPGAN G:/AI/models\GFPGAN/
[2024-08-11 22:39] Adding extra search path gligen G:/AI/models\gligen/
[2024-08-11 22:39] Adding extra search path hypernetworks G:/AI/models\hypernetworks/
[2024-08-11 22:39] Adding extra search path ipadapter G:/AI/models\ipadapter/
[2024-08-11 22:39] Adding extra search path karlo G:/AI/models\karlo/
[2024-08-11 22:39] Adding extra search path LDSR G:/AI/models\LDSR/
[2024-08-11 22:39] Adding extra search path llm G:/AI/models\llm/
[2024-08-11 22:39] Adding extra search path loras G:/AI/models\loras/
[2024-08-11 22:39] Adding extra search path sams G:/AI/models\sams/
[2024-08-11 22:39] Adding extra search path ultralytics G:/AI/models\ultralytics/
[2024-08-11 22:39] Adding extra search path unet G:/AI/models\unet/
[2024-08-11 22:39] Adding extra search path upscale_models G:/AI/models\upscale_models/
[2024-08-11 22:39] Adding extra search path vae G:/AI/models\vae/
[2024-08-11 22:39] Adding extra search path VAE-approx G:/AI/models\VAE-approx/
[2024-08-11 22:39] Adding extra search path checkpoints D:/AI/models/checkpoints
[2024-08-11 22:39] Adding extra search path unet D:/AI/models/unet/
[2024-08-11 22:39] Error:
[WinError 1314] Klienten saknar ett nödvändigt privilegium: 'D:\\AI\\pinokio\\api\\comfyui.git\\app\\custom_nodes\\ComfyLiterals\\js' -> 'D:\\AI\\pinokio\\api\\comfyui.git\\app\\web\\extensions\\ComfyLiterals'
Failed to create symlink to D:\AI\pinokio\api\comfyui.git\app\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyLiterals\js
Target: D:\AI\pinokio\api\comfyui.git\app\web\extensions\ComfyLiterals
[2024-08-11 22:39] [Crystools [0;32mINFO[0m] Crystools version: 1.16.6
[2024-08-11 22:39] [Crystools [0;32mINFO[0m] CPU: AMD Ryzen 5 3600X 6-Core Processor - Arch: AMD64 - OS: Windows 10
[2024-08-11 22:39] [Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
[2024-08-11 22:39] [Crystools [0;32mINFO[0m] GPU/s:
[2024-08-11 22:39] [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 4060 Ti
[2024-08-11 22:39] [Crystools [0;32mINFO[0m] NVIDIA Driver: 560.70
[2024-08-11 22:39] ### Loading: ComfyUI-Impact-Pack (V6.2)
[2024-08-11 22:39] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[2024-08-11 22:39] [Impact Pack] Wildcards loading done.
[2024-08-11 22:39] [36;20m[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ckpts path: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Inference-Core-Nodes\src\inference_core_nodes\controlnet_preprocessors\ckpts[0m
[2024-08-11 22:39] [36;20m[inference_core_nodes.controlnet_preprocessors] | INFO -> Using symlinks: False[0m
[2024-08-11 22:39] [36;20m[inference_core_nodes.controlnet_preprocessors] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2024-08-11 22:39] DWPose: Onnxruntime with acceleration providers detected
[2024-08-11 22:39] ### Loading: ComfyUI-Inspire-Pack (V0.83)
[2024-08-11 22:39] ### Loading: ComfyUI-Manager (V2.48.6)
[2024-08-11 22:39] ### ComfyUI Revision: 2409 [45a2842d] | Released on '2024-07-26'
[2024-08-11 22:39] Failed to auto update `Quality of Life Suit` 
[2024-08-11 22:39] [33mQualityOfLifeSuit_Omar92_DIR:[0m D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[2024-08-11 22:39] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-08-11 22:39] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-08-11 22:39] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-08-11 22:39] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-08-11 22:39] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-08-11 22:39] A new version of Albumentations is available: 1.4.13 (you have 1.4.7). Upgrade using: pip install --upgrade albumentations
[2024-08-11 22:39] [0;33m[ReActor][0m - [38;5;173mSTATUS[0m - [0;32mRunning v0.5.1-a6 in ComfyUI[0m
[2024-08-11 22:39] Torch version: 2.3.0+cu121
[2024-08-11 22:39] D:\AI\pinokio\api\comfyui.git\app
[2024-08-11 22:39] ############################################
[2024-08-11 22:39] D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-NAI-styler\CSV
[2024-08-11 22:39] ############################################
[2024-08-11 22:39] []
[2024-08-11 22:39] ############################################
[2024-08-11 22:39] 
[1mFrom Bmad Custom Nodes[0m
[2024-08-11 22:39]  [92mLoaded 122 nodes:
[2024-08-11 22:39]   + api nodes (14)
[2024-08-11 22:39]   + simple utility nodes (58)
[2024-08-11 22:39]   + CV nodes (49)
[2024-08-11 22:39]   + color clip ade20k node (1)
[2024-08-11 22:39]  [93mNot loaded:
[2024-08-11 22:39]   * extension dependent nodes
[2024-08-11 22:39]  [91mProblems:
[2024-08-11 22:39]   ! No module named 'custom_nodes.ComfyUI_ADV_CLIP_emb'
[2024-08-11 22:39] [0m
[2024-08-11 22:39] ------------------------------------------
[2024-08-11 22:39] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
[2024-08-11 22:39] ------------------------------------------
[2024-08-11 22:39] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[2024-08-11 22:39] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[2024-08-11 22:39] ------------------------------------------
[2024-08-11 22:39] A new version of Albumentations is available: 1.4.13 (you have 1.4.7). Upgrade using: pip install --upgrade albumentations
[2024-08-11 22:39] 
[2024-08-11 22:39] [92m[rgthree] Loaded 42 extraordinary nodes.[00m
[2024-08-11 22:39] [92m[rgthree] Will use rgthree's optimized recursive execution.[00m
[2024-08-11 22:39] 
[2024-08-11 22:39] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2024-08-11 22:39] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `D:\AI\pinokio\api\comfyui.git\app\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2024-08-11 22:39] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m218[0m [32mnodes successfully.[0m
[2024-08-11 22:39] 
	[3m[93m"Every artist was first an amateur."[0m[3m - Ralph Waldo Emerson[0m
[2024-08-11 22:39] 
[2024-08-11 22:39] 
Import times for custom nodes:
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\rembg-comfyui-node
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\rembg-comfyui-node-better
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\PonySwitch.py
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\websocket_image_save.py
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui_lora_tag_loader
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\Xycuno-Oobabooga
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Logic
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui-diffusion-cg
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\masquerade-nodes-comfyui
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui-fitsize
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui-base64-to-image
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-YOLO
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\lora-info
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\cg-use-everywhere
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_Cutoff
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-post-processing-nodes
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_experiments
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui-inpaint-nodes
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Universal-Styler
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfy-plasma
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Custom-Scripts
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyMath
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyLiterals
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\Derfuu_ComfyUI_ModdedNodes
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_IPAdapter_plus
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\rgthree-comfy
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui_bmad_nodes
[2024-08-11 22:39]    0.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\efficiency-nodes-comfyui
[2024-08-11 22:39]    0.1 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Inspire-Pack
[2024-08-11 22:39]    0.1 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-08-11 22:39]    0.3 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Crystools
[2024-08-11 22:39]    0.5 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-IF_AI_tools
[2024-08-11 22:39]    0.6 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Manager
[2024-08-11 22:39]    1.0 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\hd_node
[2024-08-11 22:39]    1.1 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\batchImg-rembg-ComfyUI-nodes
[2024-08-11 22:39]    1.4 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\comfyui-reactor-node
[2024-08-11 22:39]    1.7 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Impact-Pack
[2024-08-11 22:39]    1.8 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\ComfyUI-Inference-Core-Nodes
[2024-08-11 22:39]    2.2 seconds: D:\AI\pinokio\api\comfyui.git\app\custom_nodes\was-node-suite-comfyui
[2024-08-11 22:39] 
[2024-08-11 22:39] Starting server

[2024-08-11 22:39] To see the GUI go to: http://127.0.0.1:8188
[2024-08-11 22:41] got prompt
[2024-08-11 22:41] Failed to validate prompt for output 28:
[2024-08-11 22:41] * DualCLIPLoader 11:
[2024-08-11 22:41]   - Value not in list: type: 'flux' not in ['sdxl', 'sd3']
[2024-08-11 22:41] Output will be ignored
[2024-08-11 22:41] invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
[2024-08-11 22:41] got prompt
[2024-08-11 22:41] [32m[rgthree] Using rgthree's optimized recursive execution.[00m
[2024-08-11 22:41] [32m[rgthree][00m First run patching recursive_output_delete_if_changed and recursive_will_execute.[00m
[2024-08-11 22:41] [33m[rgthree] Note: [0mIf execution seems broken due to forward ComfyUI changes, you can disable the optimization from rgthree settings in ComfyUI.[00m
[2024-08-11 22:41] !!! Exception during processing!!! 'conv_in.weight'
[2024-08-11 22:41] Traceback (most recent call last):
  File "D:\AI\pinokio\api\comfyui.git\app\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\AI\pinokio\api\comfyui.git\app\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\AI\pinokio\api\comfyui.git\app\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\AI\pinokio\api\comfyui.git\app\nodes.py", line 829, in load_unet
    model = comfy.sd.load_unet(unet_path)
  File "D:\AI\pinokio\api\comfyui.git\app\comfy\sd.py", line 608, in load_unet
    model = load_unet_state_dict(sd)
  File "D:\AI\pinokio\api\comfyui.git\app\comfy\sd.py", line 581, in load_unet_state_dict
    model_config = model_detection.model_config_from_diffusers_unet(sd)
  File "D:\AI\pinokio\api\comfyui.git\app\comfy\model_detection.py", line 473, in model_config_from_diffusers_unet
    unet_config = unet_config_from_diffusers_unet(state_dict)
  File "D:\AI\pinokio\api\comfyui.git\app\comfy\model_detection.py", line 355, in unet_config_from_diffusers_unet
    match["model_channels"] = state_dict["conv_in.weight"].shape[0]
KeyError: 'conv_in.weight'

[2024-08-11 22:41] Prompt executed in 0.10 seconds
```

### Other

Win 10
RTX 4060 Ti
ComfyUi Version: ? (Updated today)
```
Error occurred when executing UNETLoader:

'conv_in.weight'

File "D:\AI\pinokio\api\comfyui.git\app\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "D:\AI\pinokio\api\comfyui.git\app\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "D:\AI\pinokio\api\comfyui.git\app\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "D:\AI\pinokio\api\comfyui.git\app\nodes.py", line 829, in load_unet
model = comfy.sd.load_unet(unet_path)
File "D:\AI\pinokio\api\comfyui.git\app\comfy\sd.py", line 608, in load_unet
model = load_unet_state_dict(sd)
File "D:\AI\pinokio\api\comfyui.git\app\comfy\sd.py", line 581, in load_unet_state_dict
model_config = model_detection.model_config_from_diffusers_unet(sd)
File "D:\AI\pinokio\api\comfyui.git\app\comfy\model_detection.py", line 473, in model_config_from_diffusers_unet
unet_config = unet_config_from_diffusers_unet(state_dict)
File "D:\AI\pinokio\api\comfyui.git\app\comfy\model_detection.py", line 355, in unet_config_from_diffusers_unet
match["model_channels"] = state_dict["conv_in.weight"].shape[0]
```

**Comment by ltdrdata** [comment]
That means your ComfyUI is outdated version.

**Comment by tzktok** [comment]
> That means your ComfyUI is outdated version.

i have updated the comfyui still same error.. @ltdrdata  @drago87  Any solutions..

**Comment by Sylsatra** [comment]
Could you try updating using this method? I just wanted to let you know that it works for me:
Locate to your "Comfyui\ComfyUI_windows_portable"
and look for  the folder "update"
in there launch "update_comfyui.bat"

**Comment by ltdrdata** [comment]
> > That means your ComfyUI is outdated version.
> 
> i have updated the comfyui still same error.. @ltdrdata @drago87 Any solutions..

Show me the startup messages of the ComfyUI.

**Comment by kolty17** [comment]
It happened to me when I accidentally used a Lora as a Diffusion model, are you sure you don't need to use Load Checkpoint?

**Comment by aiXia121** [comment]
same error! I  finetuned the dit by the x-flux repo and transfered the dit.bin model to the dit.safetensors modal, while i got the following error when i used the comfyui's load diffusion model, 

[2024-09-27 10:16] Prompt executed in 10.76 seconds
[2024-09-27 10:18] got prompt
[2024-09-27 10:18] !!! Exception during processing !!! 'conv_in.weight'
[2024-09-27 10:18] Traceback (most recent call last):
  File "/data2/xxx/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/data2/xxx/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/nodes.py", line 874, in load_unet
    model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/comfy/sd.py", line 662, in load_diffusion_model
    model = load_diffusion_model_state_dict(sd, model_options=model_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/comfy/sd.py", line 629, in load_diffusion_model_state_dict
    model_config = model_detection.model_config_from_diffusers_unet(sd)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/comfy/model_detection.py", line 496, in model_config_from_diffusers_unet
    unet_config = unet_config_from_diffusers_unet(state_dict)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data2/xxx/ComfyUI/comfy/model_detection.py", line 372, in unet_config_from_diffusers_unet
    match["model_channels"] = state_dict["conv_in.weight"].shape[0]
                              ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'conv_in.weight'

**Comment by ltdrdata** [comment]
> same error! I finetuned the dit by the x-flux repo and transfered the dit.bin model to the dit.safetensors modal, while i got the following error when i used the comfyui's load diffusion model,
> 
> [2024-09-27 10:16] Prompt executed in 10.76 seconds [2024-09-27 10:18] got prompt [2024-09-27 10:18] !!! Exception during processing !!! 'conv_in.weight' [2024-09-27 10:18] Traceback (most recent call last): File "/data2/xxx/ComfyUI/execution.py", line 317, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/execution.py", line 192, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i) File "/data2/xxx/ComfyUI/execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs)) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/nodes.py", line 874, in load_unet model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/comfy/sd.py", line 662, in load_diffusion_model model = load_diffusion_model_state_dict(sd, model_options=model_options) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/comfy/sd.py", line 629, in load_diffusion_model_state_dict model_config = model_detection.model_config_from_diffusers_unet(sd) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/comfy/model_detection.py", line 496, in model_config_from_diffusers_unet unet_config = unet_config_from_diffusers_unet(state_dict) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/data2/xxx/ComfyUI/comfy/model_detection.py", line 372, in unet_config_from_diffusers_unet match["model_channels"] = state_dict["conv_in.weight"].shape[0] ~~~~~~~~~~^^^^^^^^^^^^^^^^^^ KeyError: 'conv_in.weight'

It seems that you are using invalid model.
Why did you download that model file?

**Comment by MUTOU77** [comment]
Prompt executed in 0.05 seconds
got prompt
Failed to validate prompt for output 87:
* (prompt):
  - Required input is missing: images
* SaveImage 87:
  - Required input is missing: images
Output will be ignored
!!! Exception during processing !!! 'conv_in.weight'
Traceback (most recent call last):
  File "D:\AI程序\ComfyUI-aki-v1.4\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI程序\ComfyUI-aki-v1.4\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI程序\ComfyUI-aki-v1.4\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI程序\ComfyUI-aki-v1.4\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\AI程序\ComfyUI-aki-v1.4\nodes.py", line 910, in load_unet
    model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options)
  File "D:\AI程序\ComfyUI-aki-v1.4\comfy\sd.py", line 994, in load_diffusion_model
    model = load_diffusion_model_state_dict(sd, model_options=model_options)
  File "D:\AI程序\ComfyUI-aki-v1.4\comfy\sd.py", line 954, in load_diffusion_model_state_dict
    model_config = model_detection.model_config_from_diffusers_unet(sd)
  File "D:\AI程序\ComfyUI-aki-v1.4\comfy\model_detection.py", line 641, in model_config_from_diffusers_unet
    unet_config = unet_config_from_diffusers_unet(state_dict)
  File "D:\AI程序\ComfyUI-aki-v1.4\comfy\model_detection.py", line 517, in unet_config_from_diffusers_unet
    match["model_channels"] = state_dict["conv_in.weight"].shape[0]
KeyError: 'conv_in.weight'

我也是这样的问题，在线等解决
