### ISSUE TITLE
Flux nodes work fine in workflow from localhost but causes error when same workflow used in API

### ISSUE THREAD

**Issue by jdc4429** [comfyanonymous/ComfyUI#4344]
### Expected Behavior

Image created

### Actual Behavior

Error:

model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
Requested to load Flux
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████| 6/6 [01:32<00:00, 15.39s/it]
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load AutoencoderKL
Loading 1 new model
!!! Exception during processing!!! Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 160, 90] to have 4 channels, but got 16 channels instead
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\nodes.py", line 270, in decode
    return (vae.decode(samples["samples"]), )
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\comfy\sd.py", line 322, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\comfy\ldm\models\autoencoder.py", line 199, in decode
    dec = self.post_quant_conv(z)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\comfy\ops.py", line 93, in forward
    return super().forward(*args, **kwargs)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 160, 90] to have 4 channels, but got 16 channels instead

Prompt executed in 194.95 seconds

### Steps to Reproduce

Run workflow...
[Flux full checkpoint API test.json](https://github.com/user-attachments/files/16606291/Flux.full.checkpoint.API.test.json)

### Debug Logs

```powershell
got prompt
[rgthree] Using rgthree's optimized recursive execution.
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
Requested to load FluxClipModel_
Loading 1 new model
clip missing: ['text_projection.weight']
Requested to load Flux
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████| 6/6 [01:37<00:00, 16.30s/it]
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load AutoencodingEngine
Loading 1 new model
Prompt executed in 255.51 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
100%|██████████████████████████████████████████████████████████████████████████████| 6/6 [01:37<00:00, 16.31s/it]
Requested to load AutoencodingEngine
Loading 1 new model
Prompt executed in 106.29 seconds
got prompt
[rgthree] Using rgthree's optimized recursive execution.
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
Requested to load Flux
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████| 6/6 [01:32<00:00, 15.39s/it]
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load AutoencoderKL
Loading 1 new model
!!! Exception during processing!!! Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 160, 90] to have 4 channels, but got 16 channels instead
Traceback (most recent call last):
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\nodes.py", line 270, in decode
    return (vae.decode(samples["samples"]), )
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\comfy\sd.py", line 322, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\comfy\ldm\models\autoencoder.py", line 199, in decode
    dec = self.post_quant_conv(z)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\inetpub\wwwroot\ComfyUI\ComfyUI\comfy\ops.py", line 93, in forward
    return super().forward(*args, **kwargs)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\inetpub\wwwroot\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 160, 90] to have 4 channels, but got 16 channels instead

Prompt executed in 194.95 seconds
```

### Other

To confirm, I can run this workflow myself in the web interface without any issues.  But when I copy the workflow to an API I get the above error.  Some how the vae does not appear to be matching I believe.. 16 channels instead of 4.. I don't understand how this works in the web interface but not through the API.

**Comment by jdc4429** [comment]
For some reason it's now crashing even running SDXL through the API.  I have downgraded torch back to 2.3.1 and xformers to .0.0.27 but it's still crashing. It always seems to crash after Requested to load AutoencoderKL.

Error: model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|█████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:21<00:00,  2.71s/it]
Requested to load AutoencoderKL
Loading 1 new model
[START] Security scan
[DONE] Security scan

**Comment by jdc4429** [comment]
I have seen the exact same issue experienced by two other people on Reddit in attempting to get Flux to work from the API.

**Comment by jdc4429** [comment]
The issue happens on torch 2.3.1 and torch 2.4.0 The issue may be with xformers. Removing xformers seems to have stopped the crashing. But just changed and only tried 3 times so far.. Will see after more tries.

**Comment by jdc4429** [comment]
Can someone please look at this.. It's gotten so bad after updating that I can't even run SDXL without it constantly crashing when going through the API! I had to take my site down basically because it's so screwed up!  ComfyUI is no longer stable. I tried reinstalling from scratch with no extra nodes and it's still crashing almost every time!  No error message, it's like it's seg faulting! Please fix!

**Comment by jdc4429** [comment]
Turned this off in case it's affecting.. regarding shared memory

![image](https://github.com/user-attachments/assets/7b5ffa91-e430-4063-bcd8-5d66c42ce3fc)

**Comment by jdc4429** [comment]
Still crashing... Geting this error now since update.  C:\inetpub\wwwroot\ComfyUI\python_embeded\Lib\site-packages\torchsde\_brownian\brownian_interval.py:608: UserWarning: Should have tb<=t1 but got tb=14.614640235900879 and t1=14.61464.
  warnings.warn(f"Should have {tb_name}<=t1 but got {tb_name}={tb} and t1={self._end}.")

**Comment by jdc4429** [comment]
For the record, I have a P40 (24gb) as cuda0 and RTX 2070 (8gb) as cuda1.  I have tried 0.0.4 to 0.0.8 and they all are having the same issue of seg faulting from memory issues it seems.  I have installed from scratch 3 times now.

**Comment by jdc4429** [comment]
Still crashing with latest update when attempting to run SDXL lightning now at 1920x1080.. No error displayed.. 8gb and 24gb cards

Loading 1 new model
loaded completely 0.0 4897.0483474731445 True
100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 8/8 [00:19<00:00,  2.45s/it]
Unloading models for lowram load.
1 models unloaded.
Loading 1 new model
loaded completely 0.0 319.11416244506836 True
[START] Security scan

**Comment by jdc4429** [comment]
Still crashing after latest update.. says memory issues are fixed.. Not.. Still can't even do SDXL 1920x1080... still crashing without error.. I would suspect from memory issues.

**Comment by jdc4429** [comment]
Still crashing in latest updates.. Updated 8/29...

**Comment by jdc4429** [comment]
Still crashing in latest updates.. 0.2.0

Still unable to run SDXL in 1920x1080 resolution.. This used to work before Flux was introduced! Please FIX! Still crashing with no error!!!

**Comment by jdc4429** [comment]
Tried updating to 0.2.2 with new install.. still NOT WORKING correctly! Still crashing with no error message when attempting to do SDXL 1920x1080 or FLUX through the API!!!
