### ISSUE TITLE
Problem with certain VAE files

### ISSUE THREAD

**Issue by Nechochwen-D** [comfyanonymous/ComfyUI#435]
I keep getting this dump when I try to run `orangemix.vae.pt`,
```Traceback (most recent call last):
  File "ComfyUI-master/execution.py", line 182, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "ComfyUI-master/execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "ComfyUI-master/execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "ComfyUI-master/execution.py", line 58, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "ComfyUI-master/execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "ComfyUI-master/nodes.py", line 300, in load_vae
    vae = comfy.sd.VAE(ckpt_path=vae_path)
  File "ComfyUI-master/comfy/sd.py", line 393, in __init__
    self.first_stage_model = AutoencoderKL(ddconfig, {'target': 'torch.nn.Identity'}, 4, monitor="val/rec_loss", ckpt_path=ckpt_path)
  File "ComfyUI-master/comfy/ldm/models/autoencoder.py", line 50, in __init__
    self.init_from_ckpt(ckpt_path, ignore_keys=ignore_keys)
  File "ComfyUI-master/comfy/ldm/models/autoencoder.py", line 57, in init_from_ckpt
    sd = torch.load(path, map_location="cpu")["state_dict"]
  File "anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 809, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 1172, in _load
    result = unpickler.load()
File "anaconda3/lib/python3.8/site-packages/torch/serialization.py", line 1165, in find_class
    return super().find_class(mod_name, name)
  File "anaconda3/lib/python3.8/site-packages/pytorch_lightning/__init__.py", line 26, in <module>
    from pytorch_lightning.callbacks import Callback  # noqa: E402
  File "anaconda3/lib/python3.8/site-packages/pytorch_lightning/callbacks/__init__.py", line 14, in <module>
    from pytorch_lightning.callbacks.batch_size_finder import BatchSizeFinder
  File "anaconda3/lib/python3.8/site-packages/pytorch_lightning/callbacks/batch_size_finder.py", line 24, in <module>
    from pytorch_lightning.callbacks.callback import Callback
  File "anaconda3/lib/python3.8/site-packages/pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
  File "anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/__init__.py", line 21, in <module>
    from pytorch_lightning.utilities.combined_loader import CombinedLoader  # noqa: F401
  File "anaconda3/lib/python3.8/site-packages/pytorch_lightning/utilities/combined_loader.py", line 18, in <module>
    from typing_extensions import Self, TypedDict
ImportError: cannot import name 'Self' from 'typing_extensions' (/home/david/anaconda3/lib/python3.8/site-packages/typing_extensions.py)```

Not quite sure what is causing it. I have so far tried reinstalling the referenced modules to no avail.

Furthermore the official `vae-ft-mse-840000-ema-pruned.ckpt` file works fine so I am at a loss here.

**Comment by Nechochwen-D** [comment]
Seems to have resolved itself after fixing the issue from #436.
