### ISSUE TITLE
[RESOLVED] Error message upon system update(numpy>=1.24.0)

### ISSUE THREAD

**Issue by Nechochwen-D** [comfyanonymous/ComfyUI#436]
Not entirely sure what is going on here, but I now see this message when I try to launch CUI. I have updated CUI to the latest commit[58ed0f2](https://github.com/comfyanonymous/ComfyUI/commit/58ed0f2da438aaf253f9880578d694ad917819f8) and have performed a forced reinstall of the python modules via `pip install --user --force-reinstall -r requirements.txt` after running into the previous error when attempting to use an external VAE #435. Any help would be appreciated at this point.
```$ python /home/USER/ComfyUI-master/main.py
/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py:569: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  (np.object, string),
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1126, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/home/USER/anaconda3/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/USER/.local/lib/python3.8/site-packages/transformers/models/clip/modeling_clip.py", line 27, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/USER/.local/lib/python3.8/site-packages/transformers/modeling_utils.py", line 83, in <module>
    from accelerate import __version__ as accelerate_version
  File "/home/USER/.local/lib/python3.8/site-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/home/USER/.local/lib/python3.8/site-packages/accelerate/accelerator.py", line 37, in <module>
    from .tracking import LOGGER_TYPE_TO_CLASS, GeneralTracker, filter_trackers
  File "/home/USER/.local/lib/python3.8/site-packages/accelerate/tracking.py", line 42, in <module>
    from torch.utils import tensorboard
  File "/home/USER/.local/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py", line 12, in <module>
    from .writer import FileWriter, SummaryWriter  # noqa: F401
  File "/home/USER/.local/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 13, in <module>
    from tensorboard.summary.writer.event_file_writer import EventFileWriter
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/summary/__init__.py", line 22, in <module>
    from tensorboard.summary import v1  # noqa: F401
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/summary/v1.py", line 23, in <module>
    from tensorboard.plugins.histogram import summary as _histogram_summary
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/plugins/histogram/summary.py", line 35, in <module>
    from tensorboard.plugins.histogram import summary_v2
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/plugins/histogram/summary_v2.py", line 35, in <module>
    from tensorboard.util import tensor_util
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/util/tensor_util.py", line 20, in <module>
    from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/__init__.py", line 22, in <module>
    from .dtypes import as_dtype  # noqa
  File "/home/USER/anaconda3/lib/python3.8/site-packages/tensorboard/compat/tensorflow_stub/dtypes.py", line 569, in <module>
    (np.object, string),
  File "/home/USER/.local/lib/python3.8/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/USER/ComfyUI-master/main.py", line 25, in <module>
    import execution
  File "/home/USER/ComfyUI-master/execution.py", line 11, in <module>
    import nodes
  File "/home/USER/ComfyUI-master/nodes.py", line 13, in <module>
    from comfy.diffusers_convert import load_diffusers
  File "/home/USER/ComfyUI-master/comfy/diffusers_convert.py", line 11, in <module>
    from comfy.sd import ModelPatcher, load_model_weights, CLIP, VAE
  File "/home/USER/ComfyUI-master/comfy/sd.py", line 5, in <module>
    import sd1_clip
  File "/home/USER/ComfyUI-master/comfy/sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer, CLIPTextModel, CLIPTextConfig
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/USER/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1117, in __getattr__
    value = getattr(module, name)
  File "/home/USER/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1116, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/USER/.local/lib/python3.8/site-packages/transformers/utils/import_utils.py", line 1128, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.clip.modeling_clip because of the following error (look up to see its traceback):
module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe. 
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations```

**Comment by comfyanonymous** [comment]
If you do: ```pip install --user --upgrade -r requirements.txt``` does it fix it?

**Comment by Nechochwen-D** [comment]
Downgrading numpy to 1.20.0 'pip install --user numpy==1.20.0` seems to have let it run.
I will attempt your fix now.

**Comment by Nechochwen-D** [comment]
Same error as before after `pip install --user --upgrade -r requirements.txt`
I think I will just downgrade it for the moment. At least it seems to work for now.

**Comment by Nechochwen-D** [comment]
`pip install --user numpy==1.23.5` works. It seems that they changed something when moving to 1.24.x as anything beyond that breaks things.
