### ISSUE TITLE
Unable to load nvfuser_codegen.dll

### ISSUE THREAD

**Issue by afunyun** [comfyanonymous/ComfyUI#4391]
### Your question

Not sure why but I updated comfy and suddenly started getting errors loading torch. The file IS there in that location, so I'm not sure what the problem might be. Originally it had another error in the torch init, but after doing some troubleshooting it's now this error. I should note, this particular log is from a swarmUI comfy install, but I also get the same error on my separate comfyui install. I have already reinstalled the entire UI and it's still giving this error. 

### Logs

```powershell
21:56:33.362 [Init] Self-Start ComfyUI-0 on port 7822 is loading...
21:56:35.765 [Warning] [ComfyUI-0/STDOUT] Traceback (most recent call last):
21:56:35.765 [Warning] [ComfyUI-0/STDOUT]   File "X:\Stable Diffusion\Data\Packages\ComfyUI\main.py", line 83, in <module>
21:56:35.765 [Warning] [ComfyUI-0/STDOUT]     import comfy.utils
21:56:35.765 [Warning] [ComfyUI-0/STDOUT]   File "X:\Stable Diffusion\Data\Packages\ComfyUI\comfy\utils.py", line 20, in <module>
21:56:35.765 [Warning] [ComfyUI-0/STDOUT]     import torch
21:56:35.765 [Warning] [ComfyUI-0/STDOUT]   File "X:\Stable Diffusion\Data\Packages\ComfyUI\venv\lib\site-packages\torch\__init__.py", line 137, in <module>
21:56:35.766 [Warning] [ComfyUI-0/STDOUT]     raise err
21:56:35.766 [Warning] [ComfyUI-0/STDOUT] OSError: [WinError 127] The specified procedure could not be found. Error loading "X:\Stable Diffusion\Data\Packages\ComfyUI\venv\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
```

**Comment by vander2000** [comment]
Same error, di you found a solution ? In my case I use stability matrix

**Comment by ltdrdata** [comment]
This seems to be a symptom of your torch being corrupted.
It appears you're using venv, so try reconstructing your venv.

If you're still experiencing the same symptoms, try downloading and using the portable version for comparison.
