### ISSUE TITLE
Search box changed and broke

### ISSUE THREAD

**Issue by BladeMcCool** [comfyanonymous/ComfyUI#4419]
### Expected Behavior

search results should populate when typing node names

### Actual Behavior

instead it just has a spinner now (the ui for this add/search completely changed?) and js error in console like this:

![image](https://github.com/user-attachments/assets/055c4010-4442-42f2-9cf6-f5be6209860b)

### Steps to Reproduce

double click in the ui to add a new node via search, experience a different/new search ui which does not work

### Debug Logs

```powershell
NodeSearchBoxPopover.vue:130 
TypeError: Cannot read properties of undefined (reading 'nodeFilters')
    at NodeSearchFilter.vue:53:37
    at runtime-core.esm-bundler.js:1808:40
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at hook.__weh.hook.__weh (runtime-core.esm-bundler.js:1788:19)
    at flushPostFlushCbs (runtime-core.esm-bundler.js:379:35)
    at flushJobs (runtime-core.esm-bundler.js:415:5)
    at flushJobs (runtime-core.esm-bundler.js:419:7)

NodeSearchBox.vue:115 
TypeError: Cannot read properties of undefined (reading 'searchNode')
    at search3 (NodeSearchBox.vue:94:41)
    at createVNode.onComplete._cache.<computed>._cache.<computed> (NodeSearchBox.vue:136:29)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
    at emit (runtime-core.esm-bundler.js:726:5)
    at Proxy.search2 (index.mjs:826:12)
    at Proxy.onFocus4 (index.mjs:339:14)
    at _ctx.multiple.mergeProps.onFocus._cache.<computed>._cache.<computed> (index.mjs:1132:51)
    at callWithErrorHandling (runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:202:17)
```

**Comment by BladeMcCool** [comment]
idk i'm gonna try a fresh install and see if it is doing that there too. been running this install for many months now, updated several times etc, most recently in the last day to mess with the flux thing (it was working and i wanted to try the .gguf quantization stuff next, but then my comfy ui went weird)

**Comment by BladeMcCool** [comment]
yeah so fresh install seems to not have this issue? idk .... will re-open if i run into issues again. sorry to bother.
