### ISSUE TITLE
_pygit2.GitError: 1 conflict prevents checkout  ， There was an error when using update

### ISSUE THREAD

**Issue by JioJe** [comfyanonymous/ComfyUI#4433]
### Your question

stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-08-17_17_49_28
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "D:\ComfyUI\ComfyUI_windows_portable\update\update.py", line 19, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\repository.py", line 286, in checkout_tree
    payload.check_error(err)
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: 1 conflict prevents checkout
请按任意键继续. . .

### Logs

```powershell
stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-08-17_17_52_27
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "D:\ComfyUI\ComfyUI_windows_portable\update\update.py", line 19, in pull
    repo.checkout_tree(repo.get(remote_master_id))
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\repository.py", line 286, in checkout_tree
    payload.check_error(err)
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "D:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: 1 conflict prevents checkout
```

### Other

My git is up to date and my environment dependencies are on the latest version

**Comment by ltdrdata** [comment]
goto `D:\ComfyUI\ComfyUI_windows_portable\ComfyUI` in cmd.
and execute
```
git status
```

**Comment by JioJe** [comment]
> 转到`D:\ComfyUI\ComfyUI_windows_portable\ComfyUI`cmd. 并执行
> 
> ```
> git status
> ```
> 
> 显示什么？

![image](https://github.com/user-attachments/assets/1701b36c-0e71-407e-a6fe-f979627745ac)

**Comment by ltdrdata** [comment]
> > 转到`D:\ComfyUI\ComfyUI_windows_portable\ComfyUI`cmd. 并执行
> > ```
> > git status
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 显示什么？
> 
> ![image](https://private-user-images.githubusercontent.com/171318305/359810400-1701b36c-0e71-407e-a6fe-f979627745ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMzk3NzUsIm5iZiI6MTcyNDIzOTQ3NSwicGF0aCI6Ii8xNzEzMTgzMDUvMzU5ODEwNDAwLTE3MDFiMzZjLTBlNzEtNDA3ZS1hNmZlLWY5Nzk2Mjc3NDVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQxMTI0MzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYWQ4OTA5YjY4MmVkMDBhNmU2ZjkwYWZhZWFmZWM3YWFjZjIyNTNkZGEzNDdmYWYxNjAxYjFkMmQwYjllMzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GShZ97jOqLT8bOlqvgf5Yt2S0vBZSJqITA_7RTIQAlI)

Execute
```
git pulll
```

What is displayed?

**Comment by JioJe** [comment]
thanks!It has been solved, the reason is that there are some old files in the web folder, and the solution is to directly delete the web folder and update it again.

**Comment by Vigilence** [comment]
This helped me as well, thank you @ltdrdata
