### ISSUE TITLE
start error report 

### ISSUE THREAD

**Issue by quqiufeng** [comfyanonymous/ComfyUI#4455]
### Expected Behavior

when start comfyui

[ERROR] An error occurred while retrieving information for the 'ttN pipeLoaderSDXL' node.
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
  File "G:\ComfyUI\ComfyUI\server.py", line 426, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "G:\ComfyUI\ComfyUI\server.py", line 426, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'

### Actual Behavior

start comfyui

### Steps to Reproduce

start comfyui

### Debug Logs

```powershell
[ERROR] An error occurred while retrieving information for the 'ttN pipeLoaderSDXL' node.
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\server.py", line 452, in get_object_info
    out[x] = node_info(x)
  File "G:\ComfyUI\ComfyUI\server.py", line 426, in node_info
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
  File "G:\ComfyUI\ComfyUI\server.py", line 426, in <dictcomp>
    info['input_order'] = {key: list(value.keys()) for (key, value) in obj_class.INPUT_TYPES().items()}
AttributeError: 'str' object has no attribute 'keys'
```

### Other

the newest code

**Comment by christian-byrne** [comment]
Update ComfyUI_tinyterraNodes. Fixed in TinyTerra/ComfyUI_tinyterraNodes@8c39f9e
