### ISSUE TITLE
_scaled_mm_out_cuda is not compiled for this platform. after updating to use --fast

### ISSUE THREAD

**Issue by DarkAlchy** [comfyanonymous/ComfyUI#4539]
### Expected Behavior

That it generates without error.

### Actual Behavior

!!! Exception during processing !!! _scaled_mm_out_cuda is not compiled for this platform.
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "F:\ComfyUI\nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 434, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 116, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "F:\ComfyUI\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1447, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
  File "F:\ComfyUI\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1470, in sample
    return _sample(*args, **kwargs)
  File "F:\ComfyUI\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\ComfyUI\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\ComfyUI\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "F:\ComfyUI\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "F:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\ComfyUI\comfy\k_diffusion\sampling.py", line 144, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "F:\ComfyUI\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 993, in __call__
    return self.predict_noise(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1043, in predict_noise
    out = super().predict_noise(*args, **kwargs)
  File "F:\ComfyUI\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "F:\ComfyUI\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "F:\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_batch
    return calc_cond_batch_original_tiled_diffusion_f93ec39f(model, conds, x_in, timestep, model_options)
  File "F:\ComfyUI\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 68, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "F:\ComfyUI\comfy\model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\comfy\ldm\flux\model.py", line 159, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control)
  File "F:\ComfyUI\comfy\ldm\flux\model.py", line 104, in forward_orig
    img = self.img_in(img)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\comfy\ops.py", line 67, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "F:\ComfyUI\comfy\ops.py", line 285, in forward_comfy_cast_weights
    out = fp8_linear(self, input)
  File "F:\ComfyUI\comfy\ops.py", line 267, in fp8_linear
    o = torch._scaled_mm(inn, w, out_dtype=input.dtype, bias=cast_to_input(self.bias, input, non_blocking=non_blocking), scale_a=scale_input, scale_b=scale_weight)
RuntimeError: _scaled_mm_out_cuda is not compiled for this platform.

### Steps to Reproduce

Just gen.

### Debug Logs

```powershell
!!! Exception during processing !!! _scaled_mm_out_cuda is not compiled for this platform.
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\nodes.py", line 1429, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "F:\ComfyUI\nodes.py", line 1396, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "F:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 434, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 116, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
  File "F:\ComfyUI\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1447, in KSampler_sample
    return _KSampler_sample(*args, **kwargs)
  File "F:\ComfyUI\comfy\samplers.py", line 829, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1470, in sample
    return _sample(*args, **kwargs)
  File "F:\ComfyUI\comfy\samplers.py", line 729, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\ComfyUI\comfy\samplers.py", line 716, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "F:\ComfyUI\comfy\samplers.py", line 695, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "F:\ComfyUI\comfy\samplers.py", line 600, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "F:\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\ComfyUI\comfy\k_diffusion\sampling.py", line 144, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "F:\ComfyUI\comfy\samplers.py", line 299, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 993, in __call__
    return self.predict_noise(*args, **kwargs)
  File "F:\ComfyUI\custom_nodes\ComfyUI_smZNodes\smZNodes.py", line 1043, in predict_noise
    out = super().predict_noise(*args, **kwargs)
  File "F:\ComfyUI\comfy\samplers.py", line 685, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "F:\ComfyUI\comfy\samplers.py", line 279, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "F:\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\.patches.py", line 4, in calc_cond_batch
    return calc_cond_batch_original_tiled_diffusion_f93ec39f(model, conds, x_in, timestep, model_options)
  File "F:\ComfyUI\comfy\samplers.py", line 228, in calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 68, in apply_model_uncond_cleanup_wrapper
    return orig_apply_model(self, *args, **kwargs)
  File "F:\ComfyUI\comfy\model_base.py", line 142, in apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\comfy\ldm\flux\model.py", line 159, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control)
  File "F:\ComfyUI\comfy\ldm\flux\model.py", line 104, in forward_orig
    img = self.img_in(img)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "F:\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\comfy\ops.py", line 67, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
  File "F:\ComfyUI\comfy\ops.py", line 285, in forward_comfy_cast_weights
    out = fp8_linear(self, input)
  File "F:\ComfyUI\comfy\ops.py", line 267, in fp8_linear
    o = torch._scaled_mm(inn, w, out_dtype=input.dtype, bias=cast_to_input(self.bias, input, non_blocking=non_blocking), scale_a=scale_input, scale_b=scale_weight)
RuntimeError: _scaled_mm_out_cuda is not compiled for this platform.
```

**Comment by comfyanonymous** [comment]
Update pytorch.

**Comment by DarkAlchy** [comment]
Ahhh, it is your environment that is on 2.3.0.  My kohya is on 12.4 and 2.4 something (all the latest).

**Comment by AugmentedRealityCat** [comment]
I got the same error.
If I go back to a previous snapshot the problem goes away.
In both cases (the recent error and the previous snapshot) I have the exact same pytorch version (2.3.1+cu121).

Could this be related to the new --fast flag ? I removed that as well after reverting to the older snapshot, so maybe it's part of the solution. 

I'm now moving to more recent snapshots to identify how recently this problem began.

**Comment by ltdrdata** [comment]
> I got the same error. If I go back to a previous snapshot the problem goes away. In both cases (the recent error and the previous snapshot) I have the exact same pytorch version (2.3.1+cu121).
> 
> Could this be related to the new --fast flag ? I removed that as well after reverting to the older snapshot, so maybe it's part of the solution.
> 
> I'm now moving to more recent snapshots to identify how recently this problem began.

You need to update `cuda 12.4` version.

**Comment by AI-Made-Simple** [comment]
thanks, installing cuda 12.4 fixed the error. Ran ./python -m pip install torch==2.4.0 torchvision torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124 from inside a cmd opened from within python_embeded folder structure as am using portable comfy

**Comment by chubbypillow93** [comment]
> thanks, installing cuda 12.4 fixed the error for me. Ran ./python -m pip install torch==2.4.0 torchvision torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124 from inside a cmd opened from within python_embeded folder structure as am using portable comfy

Thanks bro your comment solved my problem!

**Comment by AugmentedRealityCat** [comment]
A new dev version of Xformers has been released that is compatible with torch 2.4 and cuda 12.4

https://github.com/facebookresearch/xformers/actions/runs/10559887009

In the lower part of that page, you'll find `xformers-0.0.28.dev893+cu124-cp311-cp311-win_amd64.whl` and other python wheels for various versions of _python_ ( 3.8 to 3.12 ) and _cuda_ ( 118 to 124 ), and there are _rocm_ and _ubuntu_ options available there as well.

Now everything works, including xformers !

**Comment by NeoAnthropocene** [comment]
> A new dev version of Xformers has been released that is compatible with torch 2.4 and cuda 12.4
> 
> https://github.com/facebookresearch/xformers/actions/runs/10559887009
> 
> In the lower part of that page, you'll find `xformers-0.0.28.dev893+cu124-cp311-cp311-win_amd64.whl` and other python wheels for various versions of _python_ ( 3.8 to 3.12 ) and _cuda_ ( 118 to 124 ), and there are _rocm_ and _ubuntu_ options available there as well.
> 
> Now everything works, including xformers !

Can you please help this Win11 peasant how to find the right xformers? I checked your link but I don't understand anything.
On top of that, how should I install the xformers without breaking the current portable ComfyUI environment?

**Comment by AugmentedRealityCat** [comment]
To find the right whl (wheel) for your system, you must select the one with the proper OS at the beginning of its name. In your case, it would start with `windows-8-core-` . Then, you must select among those the one which has the same version of Python (py3.8 to py3.12), Pytorch (torch2.4.0), and cuda (+cu118, +cu121 or +cu124). To check the version of Python currently installed on your system, you can refer to the logged information on the Comfy console window. You'll find it just after the OS information, written like this `Python version: 3.11.6`, it's among the first 10 lines at the top of that log - and just a few lines under that python version you'll find the two last parameters, `pytorch version: X.X.X+cuXXX`.

You download the corresponding WHL file and you put it in your comfy folder, and the you refer to it directly as a target for your install command. I used Comfy's own package installer to do it and simply put the full filename as a package name, including the .whl extension.

**Comment by NeoAnthropocene** [comment]
> To find the right whl (wheel) for your system, you must select the one with the proper OS at the beginning of its name. In your case, it would start with `windows-8-core-` . Then, you must select among those the one which has the same version of Python (py3.8 to py3.12), Pytorch (torch2.4.0), and cuda (+cu118, +cu121 or +cu124). To check the version of Python currently installed on your system, you can refer to the logged information on the Comfy console window. You'll find it just after the OS information, written like this `Python version: 3.11.6`, it's among the first 10 lines at the top of that log - and just a few lines under that python version you'll find the two last parameters, `pytorch version: X.X.X+cuXXX`.
> 
> You download the corresponding WHL file and you put it in your comfy folder, and then you refer to it directly as a target for your install command. I used Comfy's own package installer to do it and simply put the full filename as a package name, including the .whl extension at the end.
> 
> All that being said, this new version is still in development and it might be safer to wait for a proper release.

Hey thanks for the quick reply! 
I can try it on a separate venv of ComfyUI if I've got the time. I don't want to break the current venv.
