### ISSUE TITLE
Loading SD15 Inpainting model in diffusers format checkpoint results in ERROR: Unsupported UNET

### ISSUE THREAD

**Issue by Scorpinaus** [comfyanonymous/ComfyUI#4563]
### Expected Behavior

Model loads correctly, such as when use a normal version of the model (In this case: raemumix_v81 was selected): 
model weight dtype torch.float16, manual cast: None
model_type EPS
clip missing: ['text_projection.weight']
Requested to load SD1ClipModel
Loading 1 new model
loaded completely 0.0 235.84423828125 True
C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 159.55708122253418 True
Requested to load BaseModel
Loading 1 new model
loaded completely 0.0 1639.406135559082 True
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.09it/s]
Prompt executed in 10.46 seconds

### Actual Behavior

RuntimeError: ERROR: Could not detect model type of: C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\raemumix_v81-inpainting.safetensors

### Steps to Reproduce

1. Use normal inpainting workflow, see image below: 
![image](https://github.com/user-attachments/assets/dbfa352d-d0d8-4045-ba45-e03bdebabcdf)
2. Click render and see the error pop-up.

### Debug Logs

```powershell
Requested to load SD1ClipModel
Loading 1 new model
loaded completely 0.0 235.84423828125 True
C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 159.55708122253418 True
Requested to load BaseModel
Loading 1 new model
loaded completely 0.0 1639.406135559082 True
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:06<00:00,  3.09it/s]
Prompt executed in 10.46 seconds
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
ERROR UNSUPPORTED UNET C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\raemumix_v81-inpainting.safetensors
!!! Exception during processing !!! ERROR: Could not detect model type of: C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\raemumix_v81-inpainting.safetensors
Traceback (most recent call last):
  File "C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 877, in load_unet
    model = comfy.sd.load_diffusion_model(unet_path, model_options=model_options)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 676, in load_diffusion_model
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(unet_path))
RuntimeError: ERROR: Could not detect model type of: C:\Users\Admin\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\raemumix_v81-inpainting.safetensors
```

**Comment by Scorpinaus** [comment]
Have delved into the code portion - particularly under model_detection.py. Specifically under function: unet_config_from_diffusers_unet.

Under supported models, the unet_config for sd15_diffusers_inpainting is not present, where the difference is the in-channels:9, compared to normal sd15 having in-channels:4

![image](https://github.com/user-attachments/assets/3d522d10-0f75-4d87-98f1-81b22cf2cb43)

Will open up a PR with the addition shortly!
