### ISSUE TITLE
ComfyUI-Manager nod Install 

### ISSUE THREAD

**Issue by HASAN3DG** [comfyanonymous/ComfyUI#4582]
### Expected Behavior

ComfyUI-Manager nod Install 
________________________________
![Screenshot 2024-08-24 104840](https://github.com/user-attachments/assets/b3cad530-b1e6-44e9-ac65-2e34c45ab858)

![Screenshot 2024-08-24 104322](https://github.com/user-attachments/assets/8793c069-85fe-4c13-873d-dacaf6b5bae7)

### Actual Behavior

![image](https://github.com/user-attachments/assets/c93f4193-c786-4ff0-a678-371915e2cc96)

### Steps to Reproduce

![image](https://github.com/user-attachments/assets/5752e472-fa58-4a08-ae01-efec8ac160a7)

### Debug Logs

```powershell
Microsoft Windows [Version 10.0.22631.4037]
(c) Microsoft Corporation. All rights reserved.

C:\ComfyUI-master>python main.py
[START] Security scan
[DONE] Security scan
Failed to execute startup-script: C:\ComfyUI-master\custom_nodes\ComfyUI-Manager\prestartup_script.py / Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Prestartup times for custom nodes:
   1.2 seconds (PRESTARTUP FAILED): C:\ComfyUI-master\custom_nodes\ComfyUI-Manager

Total VRAM 12287 MB, total RAM 65445 MB
pytorch version: 2.3.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 Ti : cudaMallocAsync

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\ComfyUI-master\main.py", line 86, in <module>
    import execution
  File "C:\ComfyUI-master\execution.py", line 13, in <module>
    import nodes
  File "C:\ComfyUI-master\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\ComfyUI-master\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\ComfyUI-master\comfy\sd.py", line 8, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "C:\ComfyUI-master\comfy\ldm\cascade\stage_c_coder.py", line 19, in <module>
    import torchvision
  File "C:\Program Files\Python312\Lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Program Files\Python312\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "C:\Program Files\Python312\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "C:\Program Files\Python312\Lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "C:\Program Files\Python312\Lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "C:\Program Files\Python312\Lib\site-packages\torchvision\ops\roi_align.py", line 4, in <module>
    import torch._dynamo
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\__init__.py", line 64, in <module>
    torch.manual_seed = disable(torch.manual_seed)
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\decorators.py", line 50, in disable
    return DisableContext()(fn)
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\eval_frame.py", line 410, in __call__
    (filename is None or trace_rules.check(fn))
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\trace_rules.py", line 3378, in check    return check_verbose(obj, is_inlined_call).skipped
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\trace_rules.py", line 3361, in check_verbose
    rule = torch._dynamo.trace_rules.lookup_inner(
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\trace_rules.py", line 3442, in lookup_inner
    rule = get_torch_obj_rule_map().get(obj, None)
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\trace_rules.py", line 2782, in get_torch_obj_rule_map
    obj = load_object(k)
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\trace_rules.py", line 2811, in load_object
    val = _load_obj_from_str(x[0])
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\_dynamo\trace_rules.py", line 2795, in _load_obj_from_str
    return getattr(importlib.import_module(module), obj_name)
  File "C:\Program Files\Python312\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\nested\_internal\nested_tensor.py", line 417, in <module>
    values=torch.randn(3, 3, device="meta"),
C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\torch\nested\_internal\nested_tensor.py:417: UserWarning: Failed to initialize NumPy: _ARRAY_API not found (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
  values=torch.randn(3, 3, device="meta"),
Using pytorch cross attention
[Prompt Server] web root: C:\ComfyUI-master\web
Adding extra search path checkpoints D:\stable-diffusion-webui\webui\models/Stable-diffusion
Adding extra search path configs D:\stable-diffusion-webui\webui\models/Stable-diffusion
Adding extra search path vae D:\stable-diffusion-webui\webui\models/VAE
Adding extra search path loras D:\stable-diffusion-webui\webui\models/Lora
Adding extra search path loras D:\stable-diffusion-webui\webui\models/LyCORIS
Adding extra search path upscale_models D:\stable-diffusion-webui\webui\models/ESRGAN
Adding extra search path upscale_models D:\stable-diffusion-webui\webui\models/RealESRGAN
Adding extra search path upscale_models D:\stable-diffusion-webui\webui\models/SwinIR
Adding extra search path embeddings D:\stable-diffusion-webui\webui\embeddings
Adding extra search path hypernetworks D:\stable-diffusion-webui\webui\models/hypernetworks
Adding extra search path controlnet D:\stable-diffusion-webui\webui\models/ControlNet
Traceback (most recent call last):
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\git\__init__.py", line 296, in <module>
    refresh()
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\git\__init__.py", line 287, in refresh
    if not Git.refresh(path=path):
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\git\cmd.py", line 631, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ComfyUI-master\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-Manager\__init__.py", line 6, in <module>
    from .glob import manager_server
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-Manager\glob\manager_server.py", line 13, in <module>
    import git
  File "C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\git\__init__.py", line 298, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet


Cannot import C:\ComfyUI-master\custom_nodes\ComfyUI-Manager module for custom nodes: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

Traceback (most recent call last):
  File "C:\ComfyUI-master\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI-master\\custom_nodes\\docker-openssl-master\\__init__.py'

Cannot import C:\ComfyUI-master\custom_nodes\docker-openssl-master module for custom nodes: [Errno 2] No such file or directory: 'C:\\ComfyUI-master\\custom_nodes\\docker-openssl-master\\__init__.py'

Import times for custom nodes:
   0.0 seconds: C:\ComfyUI-master\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): C:\ComfyUI-master\custom_nodes\docker-openssl-master
   0.0 seconds (IMPORT FAILED): C:\ComfyUI-master\custom_nodes\ComfyUI-Manager
   0.0 seconds: C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main
   0.5 seconds: C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools

Starting server

To see the GUI go to: http://127.0.0.1:8188
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "C:\ComfyUI-master\server.py", line 468, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI-master\server.py", line 436, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ComfyUI-master\\input\\IF_AI\\presets\\agents'

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
[ERROR] An error occurred while retrieving information for the 'IF_ChatPrompt' node.
Traceback (most recent call last):
  File "C:\ComfyUI-master\server.py", line 468, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI-master\server.py", line 436, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main\IFChatPromptNode.py", line 109, in INPUT_TYPES
    node = cls()
           ^^^^^
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main\IFChatPromptNode.py", line 53, in __init__
    self.agent_tools = self.load_agent_tools()
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\custom_nodes\ComfyUI-IF_AI_tools-main\IFChatPromptNode.py", line 78, in load_agent_tools
    for filename in os.listdir(self.agents_dir):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\ComfyUI-master\\input\\IF_AI\\presets\\agents'

got prompt
Failed to validate prompt for output 9:
* CheckpointLoaderSimple 4:
  - Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in ['PRealism_v21MainVAE.safetensors', 'Photon_v1.safetensors', 'RMSDXLLightning.safetensors', 'SUPIR-v0F.ckpt', 'aniverse_v30Pruned.safetensors', 'epicrealism_naturalSinRC1VAE.safetensors', 'flux1-dev-bnb-nf4.safetensors', 'fluxunchainedAndSchnfuFluxD_fuT516xfp8E4m3fnV11.safetensors', 'mistoLine_rank256.safetensors', 'mysticmirth_v10.safetensors', 'photonLCM_v10.safetensors', 'picxReal_10.safetensors', 'pixelAlchemy_hV22.safetensors', 'pixelwavesigma_01.safetensors', 'sdXL_BASE_v10VAEFix.safetensors']
* HypernetworkLoader 10:
  - Value not in list: hypernetwork_name: 'dantionMarbleStatues_10.pt' not in ['j9063DStyle_.pt', 'sxzCinematic_800StrongEnough.pt']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
C:\Users\moaaz\AppData\Roaming\Python\Python312\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
C:\ComfyUI-master\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)
Requested to load SDXL
Loading 1 new model
loaded completely 0.0 4897.0483474731445 True
100%|███████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  6.72it/s]
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 159.55708122253418 True
!!! Exception during processing !!! Numpy is not available
Traceback (most recent call last):
  File "C:\ComfyUI-master\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-master\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\nodes.py", line 1497, in save_images
    i = 255. * image.cpu().numpy()
               ^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available

Prompt executed in 13.05 seconds
got prompt
100%|███████████████████████████████████████████████████████████████████████████████████| 20/20 [00:02<00:00,  7.11it/s]
!!! Exception during processing !!! Numpy is not available
Traceback (most recent call last):
  File "C:\ComfyUI-master\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-master\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI-master\nodes.py", line 1497, in save_images
    i = 255. * image.cpu().numpy()
               ^^^^^^^^^^^^^^^^^^^
RuntimeError: Numpy is not available

Prompt executed in 2.94 seconds
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

**Comment by ltdrdata** [comment]
This issue should be report to ComfyUI-Manager.

And make sure latest git installation.
https://github.com/ltdrdata/ComfyUI-Manager#installationmethod2-installation-for-portable-comfyui-version-comfyui-manager-only
