### ISSUE TITLE
when i update comfyui,i cannot use it anymore

### ISSUE THREAD

**Issue by DamienCz** [comfyanonymous/ComfyUI#4661]
### Expected Behavior

<img width="1284" alt="5df160f3dfa550a52ef154807881db4" src="https://github.com/user-attachments/assets/d6b3de7b-6f18-4a30-9bd8-cd2f71e522cb">

### Actual Behavior

After I updated to the latest comfyui, I clicked on start but couldn't open the web page in Google Chrome or others,

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Unhandled exception
Traceback (most recent call last):
  File "G:\sd_training_infor\software\cf_new4\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 531, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "G:\sd_training_infor\software\cf_new4\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 448, in _handle_request
    assert self._request_handler is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
<img width="1284" alt="5df160f3dfa550a52ef154807881db4" src="https://github.com/user-attachments/assets/7e88d807-a25b-4c65-89e0-50d6e57aaa88">

### Steps to Reproduce

Starting server
To see the GUI go to: http://127.0.0.1:8188
To see the GUI go to: https://127.0.0.1:8189
Error: OpenAI API key is invalid OpenAI features wont work for you
QualityOfLifeSuit_Omar92::NSP ready
# 😺dzNodes: LayerStyle -> Warning: G:\sd_training_infor\software\cf_new4\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: G:\sd_training_infor\software\cf_new4\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: G:\sd_training_infor\software\cf_new4\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
# 😺dzNodes: LayerStyle -> Warning: G:\sd_training_infor\software\cf_new4\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size.
[ERROR:0@27.859] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
[ERROR:0@27.888] global obsensor_uvc_stream_channel.cpp:158 cv::obsensor::getStreamChannelGroup Camera index out of range
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Unhandled exception
Traceback (most recent call last):
  File "G:\sd_training_infor\software\cf_new4\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 531, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "G:\sd_training_infor\software\cf_new4\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 448, in _handle_request
    assert self._request_handler is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Debug Logs

```powershell
After I updated to the latest comfyui, I clicked on start but couldn't open the web page in Google Chrome or others,

Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 80, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Unhandled exception
Traceback (most recent call last):
  File "G:\sd_training_infor\software\cf_new4\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 531, in start
    resp, reset = await task
                  ^^^^^^^^^^
  File "G:\sd_training_infor\software\cf_new4\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 448, in _handle_request
    assert self._request_handler is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by afk4life** [comment]
Make sure it's really dead, go to Windows task manager, kill python.exe, then try and start it again
