### ISSUE TITLE
lora trainer error ,CUSOLVERMG64_11.DLL missing dependecy

### ISSUE THREAD

**Issue by Kuroshironya** [comfyanonymous/ComfyUI#4731]
### Your question

I tried every way by reinstalling the packages, only manually, but I can't solve the problem with the file dependency

![Screenshot 2024-09-01 131141](https://github.com/user-attachments/assets/ed2d397b-7d90-45af-b1da-e055023a0bf6)

I don't know how to solve it anymore
this is the console log:
got prompt
[]
D:\STABLE DIFFUISION\Nuova cartella\ComfyUI_windows_portable\ComfyUI\custom_nodes\Lora-Training-in-Comfy/sd-scripts/train_network.py
Traceback (most recent call last):
File "", line 189, in run_module_as_main
File "", line 112, in get_module_details
File "D:\STABLE DIFFUISION\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate_init.py", line 16, in
from .accelerator import Accelerator
File "D:\STABLE DIFFUISION\ComfyUI_windows_portable\python_embeded\Lib\site-packages\accelerate\accelerator.py", line 32, in
import torch
File "D:\STABLE DIFFUISION\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch_init.py", line 137, in
raise err
OSError: [WinError 193] %1 non è un'applicazione di Win32 valida. Error loading "D:\STABLE DIFFUISION\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\lib\cusolverMg64_11.dll" or one of its dependencies.
Train finished
Prompt executed in 14.12 seconds

**Comment by ltdrdata** [comment]
This issue should be handled in:
https://github.com/JeremyGuo/Lora-Training-in-Comfy?tab=readme-ov-file

**Comment by Kuroshironya** [comment]
I understand but no one is responding on the Lora Trainer page. I was hoping someone could give me a hand or advice quickly

**Comment by ltdrdata** [comment]
I recommend removing torch and related packages and reinstalling them.
