### ISSUE TITLE
TypeError: Cannot redefine property: 0

### ISSUE THREAD

**Issue by Pancat007** [comfyanonymous/ComfyUI#4774]
### Your question

I try to use other's shared workflow, when I drag and drop the workflow to comfyui, it shows the error, 

Loading aborted due to error reloading workflow data

TypeError: Cannot redefine property: 0
TypeError: Cannot redefine property: 0
    at Function.defineProperty (<anonymous>)
    at lockArray (http://10.30.2.72:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:13:10)
    at lockNode (http://10.30.2.72:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:117:5)
    at nodeType.onConfigure (http://10.30.2.72:8188/extensions/ComfyUI-Custom-Scripts/js/locking.js:181:5)
    at ComfyNode.configure (http://10.30.2.72:8188/assets/index-CI3N807S.js:66723:14)
    at _LGraph2.configure (http://10.30.2.72:8188/assets/index-CI3N807S.js:66509:20)
    at LGraph.configure (http://10.30.2.72:8188/assets/index-CI3N807S.js:85882:26)
    at LGraph.configure (http://10.30.2.72:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://10.30.2.72:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:160:21)
    at ComfyApp.loadGraphData (http://10.30.2.72:8188/assets/index-CI3N807S.js:86334:18)
This may be due to the following script:
/extensions/ComfyUI-Custom-Scripts/js/locking.js

The comfyui core and all the custom nodes are at the latest version.
I got this error when I try some specific workflow, like: https://openart.ai/workflows/rui400/cuteyou---20/xlYuNy8lGiNNXDTUtVCj

![image](https://github.com/user-attachments/assets/332e58cc-cc09-4b19-993f-04ba31bfe283)

**Comment by TW-Xiao** [comment]
I also encountered this problem, have you solved it?

**Comment by TW-Xiao** [comment]
It should be a problem caused by the ComfyUI version update

**Comment by Pancat007** [comment]
> I also encountered this problem, have you solved it?

I'm already using the latest version.

**Comment by TW-Xiao** [comment]
![image](https://github.com/user-attachments/assets/448cef46-f4ea-46bb-93ed-897bf7a05472)

**Comment by TW-Xiao** [comment]
We need to revert back to v0.1.3 to resolve this issue.

**Comment by huchenlei** [comment]
Update your https://github.com/pythongosssss/ComfyUI-Custom-Scripts to solve this issue.

**Comment by Pancat007** [comment]
My Custom Scripts already at the latest version, roll back to the old version could solve the issue. v0.1.3 works.
