### ISSUE TITLE
VHS_LoadVideoPath：float floor division by zero

### ISSUE THREAD

**Issue by cuixiao8765** [comfyanonymous/ComfyUI#4806]
### Your question

# ComfyUI Error Report
## Error Details
- **Node Type:** VHS_LoadVideoPath
- **Exception Type:** ZeroDivisionError
- **Exception Message:** float floor division by zero
## Stack Trace
```
  File "/Users/cuixiao/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/cuixiao/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/cuixiao/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/Users/cuixiao/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 320, in load_video
    return load_video_cv(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 171, in load_video_cv
    max_loadable_frames = int(memory_limit//(width*height*3*(.1)))
                              ~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~

```
## System Information
- **ComfyUI Version:** v0.2.2-1-gc27ebeb
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 10:07:17) [Clang 14.0.6 ]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.0.dev20240825
## Devices

- **Name:** mps
  - **Type:** mps
  - **VRAM Total:** 34359738368
  - **VRAM Free:** 14798438400
  - **Torch VRAM Total:** 34359738368
  - **Torch VRAM Free:** 14798438400

## Logs
```
2024-09-06 15:28:07,764 - root - INFO - Total VRAM 32768 MB, total RAM 32768 MB
2024-09-06 15:28:07,764 - root - INFO - pytorch version: 2.5.0.dev20240825
2024-09-06 15:28:07,764 - root - INFO - Set vram state to: SHARED
2024-09-06 15:28:07,764 - root - INFO - Device: mps
2024-09-06 15:28:08,316 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-09-06 15:28:08,747 - root - INFO - [Prompt Server] web root: /Users/cuixiao/ComfyUI/web
2024-09-06 15:28:10,905 - root - INFO - Total VRAM 32768 MB, total RAM 32768 MB
2024-09-06 15:28:10,905 - root - INFO - pytorch version: 2.5.0.dev20240825
2024-09-06 15:28:10,905 - root - INFO - Set vram state to: SHARED
2024-09-06 15:28:10,905 - root - INFO - Device: mps
2024-09-06 15:28:11,862 - root - INFO - 
Import times for custom nodes:
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-IC-Light
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/comfyui-various
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/efficiency-nodes-comfyui
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-segment-anything-2
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/rgthree-comfy
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI_essentials
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-09-06 15:28:11,862 - root - INFO -    0.0 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
2024-09-06 15:28:11,862 - root - INFO -    0.1 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-06 15:28:11,862 - root - INFO -    0.2 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI_FizzNodes
2024-09-06 15:28:11,862 - root - INFO -    0.6 seconds: /Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-09-06 15:28:11,862 - root - INFO -    1.9 seconds: /Users/cuixiao/ComfyUI/custom_nodes/comfyui-reactor-node
2024-09-06 15:28:11,862 - root - INFO - 
2024-09-06 15:28:11,867 - root - INFO - Starting server

2024-09-06 15:28:11,867 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-06 15:28:19,573 - root - INFO - got prompt
2024-09-06 15:28:19,585 - root - ERROR - !!! Exception during processing !!! float floor division by zero
2024-09-06 15:28:19,589 - root - ERROR - Traceback (most recent call last):
  File "/Users/cuixiao/ComfyUI/execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cuixiao/ComfyUI/execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cuixiao/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/cuixiao/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 320, in load_video
    return load_video_cv(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cuixiao/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite/videohelpersuite/load_video_nodes.py", line 171, in load_video_cv
    max_loadable_frames = int(memory_limit//(width*height*3*(.1)))
                              ~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float floor division by zero

2024-09-06 15:28:19,591 - root - INFO - Prompt executed in 0.01 seconds
```

**Comment by mcmonkey4eva** [comment]
issue with that custom node pack, not comfy core

**Comment by yarikmoscow** [comment]
just make CROP - DISABLED in LTXV Base Sampler node
