### ISSUE TITLE
DeepBump runnig issue

### ISSUE THREAD

**Issue by shaokahn666** [comfyanonymous/ComfyUI#4827]
### Your question

Im trying to run DeepBump , but Im getting this error

This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...) 

already tried add the providers as show above, but nothing changes, still same issue.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** Deep Bump (mtb)
- **Exception Type:** ValueError
- **Exception Message:** This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
## Stack Trace

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 363, in apply
    out_img = color_to_normals(
              ^^^^^^^^^^^^^^^^^

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 72, in color_to_normals
    ort_session = ort.InferenceSession(model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
    raise e

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)

  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
    raise ValueError(

```
## System Information
- **ComfyUI Version:** v0.2.2-6-gbb52934
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 2205230642
  - **Torch VRAM Total:** 21441282048
  - **Torch VRAM Free:** 6567474

## Logs
```
2024-09-07 11:26:07,327 - root - INFO - Total VRAM 24564 MB, total RAM 130265 MB
2024-09-07 11:26:07,327 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-07 11:26:07,328 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-07 11:26:07,328 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-09-07 11:26:08,009 - root - INFO - Using pytorch cross attention
2024-09-07 11:26:08,937 - root - INFO - [Prompt Server] web root: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\web
2024-09-07 11:26:10,639 - root - INFO - Total VRAM 24564 MB, total RAM 130265 MB
2024-09-07 11:26:10,639 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-07 11:26:10,641 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-07 11:26:10,641 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-09-07 11:26:14,127 - root - INFO - 
Import times for custom nodes:
2024-09-07 11:26:14,127 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\gcLatentTunnel.py
2024-09-07 11:26:14,127 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-07 11:26:14,127 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\tiled_ksampler
2024-09-07 11:26:14,127 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-09-07 11:26:14,128 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\asymmetric-tiling-comfyui
2024-09-07 11:26:14,128 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
2024-09-07 11:26:14,128 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-mxToolkit
2024-09-07 11:26:14,128 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-07 11:26:14,129 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-07 11:26:14,129 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-09-07 11:26:14,129 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
2024-09-07 11:26:14,130 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
2024-09-07 11:26:14,130 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffusionLight
2024-09-07 11:26:14,130 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-07 11:26:14,130 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-marnodes
2024-09-07 11:26:14,131 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-09-07 11:26:14,131 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
2024-09-07 11:26:14,131 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
2024-09-07 11:26:14,131 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-09-07 11:26:14,132 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ControlAltAI-Nodes
2024-09-07 11:26:14,132 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
2024-09-07 11:26:14,132 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-plasma
2024-09-07 11:26:14,132 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-09-07 11:26:14,132 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-09-07 11:26:14,134 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-07 11:26:14,134 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
2024-09-07 11:26:14,134 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-07 11:26:14,134 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-09-07 11:26:14,135 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-07 11:26:14,135 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
2024-09-07 11:26:14,135 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-07 11:26:14,135 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JakeUpgrade
2024-09-07 11:26:14,136 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Saver
2024-09-07 11:26:14,136 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-09-07 11:26:14,136 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\virtuoso-nodes
2024-09-07 11:26:14,136 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
2024-09-07 11:26:14,137 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-09-07 11:26:14,137 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-07 11:26:14,137 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-07 11:26:14,137 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-09-07 11:26:14,138 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
2024-09-07 11:26:14,138 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-09-07 11:26:14,138 - root - INFO -    0.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
2024-09-07 11:26:14,138 - root - INFO -    0.2 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
2024-09-07 11:26:14,139 - root - INFO -    0.2 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
2024-09-07 11:26:14,139 - root - INFO -    0.3 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-09-07 11:26:14,139 - root - INFO -    0.3 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-07 11:26:14,139 - root - INFO -    0.3 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-09-07 11:26:14,140 - root - INFO -    0.5 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
2024-09-07 11:26:14,140 - root - INFO -    0.5 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2
2024-09-07 11:26:14,140 - root - INFO -    0.5 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-09-07 11:26:14,140 - root - INFO -    0.5 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
2024-09-07 11:26:14,141 - root - INFO -    1.0 seconds: C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-09-07 11:26:14,141 - root - INFO - 
2024-09-07 11:26:14,149 - root - INFO - Starting server

2024-09-07 11:26:14,149 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-07 11:26:25,706 - root - INFO - got prompt
2024-09-07 11:26:25,772 - root - INFO - Using pytorch attention in VAE
2024-09-07 11:26:25,773 - root - INFO - Using pytorch attention in VAE
2024-09-07 11:26:26,214 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-09-07 11:26:26,215 - root - INFO - model_type FLUX
2024-09-07 11:27:08,583 - root - WARNING - clip missing: ['text_projection.weight']
2024-09-07 11:27:09,248 - root - INFO - Requested to load FluxClipModel_
2024-09-07 11:27:09,249 - root - INFO - Loading 1 new model
2024-09-07 11:27:10,589 - root - INFO - loaded completely 0.0 9319.23095703125 True
2024-09-07 11:27:10,987 - root - INFO - Requested to load AutoencodingEngine
2024-09-07 11:27:10,988 - root - INFO - Loading 1 new model
2024-09-07 11:27:11,048 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-09-07 11:27:11,178 - root - INFO - Requested to load Flux
2024-09-07 11:27:11,178 - root - INFO - Loading 1 new model
2024-09-07 11:27:35,343 - root - INFO - loaded completely 0.0 11350.048889160156 True
2024-09-07 11:27:39,928 - root - INFO - Requested to load AutoencodingEngine
2024-09-07 11:27:39,928 - root - INFO - Loading 1 new model
2024-09-07 11:27:39,954 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-09-07 11:27:40,086 - root - ERROR - !!! Exception during processing !!! This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)
2024-09-07 11:27:40,087 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 363, in apply
    out_img = color_to_normals(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb\nodes\deep_bump.py", line 72, in color_to_normals
    ort_session = ort.InferenceSession(model)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 396, in __init__
    raise e
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 383, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\DarkSoul\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 415, in _create_inference_session
    raise ValueError(
ValueError: This ORT build has ['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'] enabled. Since ORT 1.9, you are required to explicitly set the providers parameter when instantiating InferenceSession. For example, onnxruntime.InferenceSession(..., providers=['TensorrtExecutionProvider', 'CUDAExecutionProvider', 'CPUExecutionProvider'], ...)

2024-09-07 11:27:40,089 - root - INFO - Prompt executed in 74.38 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
This issue should be moved to mtb repo
https://github.com/melMass/comfy_mtb/issues
