### ISSUE TITLE
Unable to fetch infor for lora/checkpoint

### ISSUE THREAD

**Issue by S0LTIS** [comfyanonymous/ComfyUI#4838]
### Your question

Does anyone know how to fix this? I have reinstalled comfyui from a fresh download of the  file.

### Logs

```powershell
Error handling request
Traceback (most recent call last):
  File "C:\COMFYUI DIRs\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\ComfyUI\server.py", line 61, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\ComfyUI\server.py", line 73, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\COMFYUI DIRs\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\model_info.py", line 65, in load_metadata
    pos = name.index("/")
          ^^^^^^^^^^^^^^^
ValueError: substring not found
```

### Other

I right click the node, then click "View Checkpoint info...."

Then this pops up in console.

![image](https://github.com/user-attachments/assets/6e79a5a2-7aa8-49f6-816b-9fec8ca716fc)

**Comment by S0LTIS** [comment]
Nvm wrong place to ask this

**Comment by DuXinshu520** [comment]
Excuse me, I encountered the same problem today, so I would like to ask how you solved it?

**Comment by ltdrdata** [comment]
> Excuse me, I encountered the same problem today, so I would like to ask how you solved it?

https://github.com/pythongosssss/ComfyUI-Custom-Scripts/issues

**Comment by filwu8** [comment]
Error handling request
Traceback (most recent call last):
  File "D:\Ai\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ComfyUI_windows_portable_nvidia\ComfyUI\server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ComfyUI_windows_portable_nvidia\ComfyUI\server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ComfyUI_windows_portable_nvidia\ComfyUI\server.py", line 75, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Ai\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\better_combos.py", line 58, in get_examples
    pos = name.index("/")
          ^^^^^^^^^^^^^^^
ValueError: substring not found
