### ISSUE TITLE
compute_index_ranges_weights" not implemented for 'Half'

### ISSUE THREAD

**Issue by dfahuiwe** [comfyanonymous/ComfyUI#4861]
### Feature Idea

<img width="730" alt="8ce6226618105fc9eb6699a7032b8f4" src="https://github.com/user-attachments/assets/672b415e-a195-4d15-ac88-aedccd74f483">

**Comment by ltdrdata** [comment]
Your issue report is missing critical information.
Please provide the full information copied through the "Copy to Clipboard" function.

**Comment by fakeqq** [comment]
# ComfyUI Error Report
## Error Details
- **Node Type:** MimicMotionSampler
- **Exception Type:** RuntimeError
- **Exception Message:** "compute_index_ranges_weights" not implemented for 'Half'
## Stack Trace
```
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 297, in process
    frames = pipeline(

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 521, in __call__
    image_embeddings = self._encode_image(image, device, num_videos_per_prompt, self.do_classifier_free_guidance, image_embed_strength=image_embed_strength)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 152, in _encode_image
    image = clip_preprocess(image.clone(), 224)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\comfy\clip_vision.py", line 25, in clip_preprocess
    image = torch.nn.functional.interpolate(image, size=(round(scale * image.shape[2]), round(scale * image.shape[3])), mode="bicubic", antialias=True)

  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\nn\functional.py", line 4072, in interpolate
    return torch._C._nn._upsample_bicubic2d_aa(input, output_size, align_corners, scale_factors)

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\main.py --auto-launch --force-fp32 --preview-method auto --use-quad-cross-attention --normalvram --directml 0 --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** privateuseone
  - **Type:** privateuseone
  - **VRAM Total:** 1073741824
  - **VRAM Free:** 1073741824
  - **Torch VRAM Total:** 1073741824
  - **Torch VRAM Free:** 1073741824

## Logs
```
2024-09-10 18:17:02,956 - root - INFO - Using directml with device: Intel(R) Arc(TM) A770 Graphics
2024-09-10 18:17:02,956 - root - INFO - Total VRAM 1024 MB, total RAM 65453 MB
2024-09-10 18:17:02,956 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-10 18:17:03,456 - root - INFO - Forcing FP32, if this improves things please report it.
2024-09-10 18:17:03,456 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-10 18:17:03,456 - root - INFO - Device: privateuseone
2024-09-10 18:17:05,959 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-09-10 18:17:08,943 - root - INFO - [Prompt Server] web root: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\web
2024-09-10 18:17:12,239 - root - WARNING - Traceback (most recent call last):
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torchaudio\__init__.py", line 1, in <module>
    from . import (  # noqa: F401
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torchaudio\_extension\__init__.py", line 45, in <module>
    _load_lib("libtorchaudio")
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torchaudio\_extension\utils.py", line 64, in _load_lib
    torch.ops.load_library(path)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\_ops.py", line 1032, in load_library
    ctypes.CDLL(path)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\ctypes\__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
FileNotFoundError: Could not find module 'F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.

2024-09-10 18:17:12,239 - root - WARNING - Cannot import F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\comfy_extras\nodes_audio.py module for custom nodes: Could not find module 'F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\Lib\site-packages\torchaudio\lib\libtorchaudio.pyd' (or one of its dependencies). Try using the full path with constructor syntax.
2024-09-10 18:17:12,255 - root - INFO - Using directml with device: Intel(R) Arc(TM) A770 Graphics
2024-09-10 18:17:12,255 - root - INFO - Total VRAM 1024 MB, total RAM 65453 MB
2024-09-10 18:17:12,255 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-10 18:17:12,255 - root - INFO - Forcing FP32, if this improves things please report it.
2024-09-10 18:17:12,255 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-10 18:17:12,255 - root - INFO - Device: privateuseone
2024-09-10 18:17:18,005 - root - INFO - 
Import times for custom nodes:
2024-09-10 18:17:18,005 - root - INFO -    0.0 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\websocket_image_save.py
2024-09-10 18:17:18,005 - root - INFO -    0.0 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-10 18:17:18,005 - root - INFO -    0.3 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-KJNodes
2024-09-10 18:17:18,005 - root - INFO -    0.4 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper
2024-09-10 18:17:18,005 - root - INFO -    1.0 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-Manager
2024-09-10 18:17:18,005 - root - INFO -    1.7 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-10 18:17:18,005 - root - INFO -    2.3 seconds: F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\comfyui_controlnet_aux
2024-09-10 18:17:18,005 - root - INFO - 
2024-09-10 18:17:18,005 - root - WARNING - WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

2024-09-10 18:17:18,005 - root - WARNING - IMPORT FAILED: nodes_audio.py
2024-09-10 18:17:18,005 - root - WARNING - 
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
2024-09-10 18:17:18,005 - root - WARNING - Please do a: pip install -r requirements.txt
2024-09-10 18:17:18,005 - root - WARNING - 
2024-09-10 18:17:18,020 - root - INFO - Starting server

2024-09-10 18:17:18,020 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-10 18:17:42,142 - root - INFO - got prompt
2024-09-10 18:19:17,975 - root - ERROR - !!! Exception during processing !!! "compute_index_ranges_weights" not implemented for 'Half'
2024-09-10 18:19:18,014 - root - ERROR - Traceback (most recent call last):
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 297, in process
    frames = pipeline(
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 521, in __call__
    image_embeddings = self._encode_image(image, device, num_videos_per_prompt, self.do_classifier_free_guidance, image_embed_strength=image_embed_strength)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 152, in _encode_image
    image = clip_preprocess(image.clone(), 224)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\comfy\clip_vision.py", line 25, in clip_preprocess
    image = torch.nn.functional.interpolate(image, size=(round(scale * image.shape[2]), round(scale * image.shape[3])), mode="bicubic", antialias=True)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\nn\functional.py", line 4072, in interpolate
    return torch._C._nn._upsample_bicubic2d_aa(input, output_size, align_corners, scale_factors)
RuntimeError: "compute_index_ranges_weights" not implemented for 'Half'

2024-09-10 18:19:18,016 - root - INFO - Prompt executed in 95.66 seconds
2024-09-10 18:19:49,779 - root - INFO - got prompt
2024-09-10 18:19:50,588 - root - ERROR - !!! Exception during processing !!! "compute_index_ranges_weights" not implemented for 'Half'
2024-09-10 18:19:50,589 - root - ERROR - Traceback (most recent call last):
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\nodes.py", line 297, in process
    frames = pipeline(
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 521, in __call__
    image_embeddings = self._encode_image(image, device, num_videos_per_prompt, self.do_classifier_free_guidance, image_embed_strength=image_embed_strength)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\custom_nodes\ComfyUI-MimicMotionWrapper\mimicmotion\pipelines\pipeline_mimicmotion.py", line 152, in _encode_image
    image = clip_preprocess(image.clone(), 224)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\comfy\clip_vision.py", line 25, in clip_preprocess
    image = torch.nn.functional.interpolate(image, size=(round(scale * image.shape[2]), round(scale * image.shape[3])), mode="bicubic", antialias=True)
  File "F:\BaiduNetdiskDownload\comf4\ComfyUI-MimicMotion\python\lib\site-packages\torch\nn\functional.py", line 4072, in interpolate
    return torch._C._nn._upsample_bicubic2d_aa(input, output_size, align_corners, scale_factors)
RuntimeError: "compute_index_ranges_weights" not implemented for 'Half'

2024-09-10 18:19:50,590 - root - INFO - Prompt executed in 0.59 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":61,"last_link_id":153,"nodes":[{"id":58,"type":"MimicMotionDecode","pos":{"0":1459,"1":497},"size":{"0":255.466796875,"1":78},"flags":{},"order":10,"mode":0,"inputs":[{"name":"mimic_pipeline","type":"MIMICPIPE","link":150,"slot_index":0,"label":"mimic_pipeline"},{"name":"samples","type":"LATENT","link":149,"label":"samples"}],"outputs":[{"name":"images","type":"IMAGE","links":[151,152],"slot_index":0,"shape":3,"label":"images"}],"properties":{"Node name for S&R":"MimicMotionDecode"},"widgets_values":[4]},{"id":9,"type":"GetImageSizeAndCount","pos":{"0":779,"1":600},"size":{"0":210,"1":86},"flags":{},"order":7,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":112,"label":"image"}],"outputs":[{"name":"image","type":"IMAGE","links":[148],"slot_index":0,"shape":3,"label":"image"},{"name":"576 width","type":"INT","links":null,"shape":3,"label":"576 width"},{"name":"896 height","type":"INT","links":null,"shape":3,"label":"1024 height"},{"name":"132 count","type":"INT","links":null,"shape":3,"label":"340 count"}],"properties":{"Node name for S&R":"GetImageSizeAndCount"}},{"id":61,"type":"Note","pos":{"0":190,"1":246},"size":{"0":683.275146484375,"1":95.09097290039062},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"title":"视频教程","properties":{"text":""},"widgets_values":["B站：艾橘溪。https://space.bilibili.com/486814801\n\n如有疑问，可联系作者技术指导：\n由于程序插件环境搭建、效果调试等非常耗时间耗精力，因此如需远程技术指导，需微信付费技术指导。\n加微信：abinsz，备注：Ai指导\n"],"color":"#432","bgcolor":"#653","shape":4},{"id":16,"type":"VHS_VideoCombine","pos":{"0":1504,"1":920},"size":[1252.271240234375,310],"flags":{},"order":13,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":93,"label":"images"},{"name":"audio","type":"VHS_AUDIO","link":null,"label":"audio"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"meta_batch"},{"name":"vae","type":"VAE","link":null,"label":"vae"}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"Filenames"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":30,"loop_count":0,"filename_prefix":"MimicMotion/min","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"min_00039.mp4","subfolder":"MimicMotion","type":"output","format":"video/h264-mp4","frame_rate":30}}}},{"id":28,"type":"ImageResizeKJ","pos":{"0":-101,"1":442},"size":{"0":315,"1":242},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":61,"label":"image"},{"name":"get_image_size","type":"IMAGE","link":null,"label":"get_image_size"},{"name":"width_input","type":"INT","link":null,"widget":{"name":"width_input"},"label":"width_input"},{"name":"height_input","type":"INT","link":null,"widget":{"name":"height_input"},"label":"height_input"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[95,110,147],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"width","type":"INT","links":[88],"slot_index":1,"shape":3,"label":"width"},{"name":"height","type":"INT","links":[89],"slot_index":2,"shape":3,"label":"height"}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[576,1024,"lanczos",true,64,0,0,"disabled"]},{"id":35,"type":"ImageResizeKJ","pos":{"0":291,"1":441},"size":{"0":315,"1":242},"flags":{},"order":5,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":86,"label":"image"},{"name":"get_image_size","type":"IMAGE","link":null,"label":"get_image_size"},{"name":"width_input","type":"INT","link":88,"widget":{"name":"width_input"},"label":"width_input"},{"name":"height_input","type":"INT","link":89,"widget":{"name":"height_input"},"label":"height_input"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[111,137],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"width","type":"INT","links":null,"shape":3,"label":"width"},{"name":"height","type":"INT","links":null,"shape":3,"label":"height"}],"properties":{"Node name for S&R":"ImageResizeKJ"},"widgets_values":[576,1024,"lanczos",false,64,0,0,"disabled"]},{"id":42,"type":"MimicMotionGetPoses","pos":{"0":242,"1":763},"size":{"0":330,"1":126},"flags":{},"order":6,"mode":0,"inputs":[{"name":"ref_image","type":"IMAGE","link":110,"label":"ref_image"},{"name":"pose_images","type":"IMAGE","link":111,"label":"pose_images"}],"outputs":[{"name":"poses_with_ref","type":"IMAGE","links":[112,114],"slot_index":0,"shape":3,"label":"poses_with_ref"},{"name":"pose_images","type":"IMAGE","links":[138],"slot_index":1,"shape":3,"label":"pose_images"}],"properties":{"Node name for S&R":"MimicMotionGetPoses"},"widgets_values":[true,true,true]},{"id":37,"type":"VHS_VideoCombine","pos":{"0":622,"1":761},"size":[440,977.3333333333333],"flags":{},"order":8,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":114,"label":"images"},{"name":"audio","type":"VHS_AUDIO","link":null,"label":"audio"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"meta_batch"},{"name":"vae","type":"VAE","link":null,"label":"vae"}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"Filenames"}],"title":"Video Combine 🎥🅥🅗🅢 B站 艾橘溪","properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":30,"loop_count":0,"filename_prefix":"MimicPose","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"MimicPose_00001.mp4","subfolder":"","type":"temp","format":"video/h264-mp4","frame_rate":30}}}},{"id":2,"type":"DownloadAndLoadMimicMotionModel","pos":{"0":743,"1":419},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"mimic_pipeline","type":"MIMICPIPE","links":[146,150],"shape":3,"label":"mimic_pipeline"}],"properties":{"Node name for S&R":"DownloadAndLoadMimicMotionModel"},"widgets_values":["MimicMotion-fp16.safetensors","fp16",false]},{"id":57,"type":"MimicMotionSampler","pos":{"0":1101,"1":419},"size":{"0":315,"1":430},"flags":{},"order":9,"mode":0,"inputs":[{"name":"mimic_pipeline","type":"MIMICPIPE","link":146,"label":"mimic_pipeline"},{"name":"ref_image","type":"IMAGE","link":147,"label":"ref_image"},{"name":"pose_images","type":"IMAGE","link":148,"label":"pose_images"},{"name":"optional_scheduler","type":"DIFFUSERS_SCHEDULER","link":null,"label":"optional_scheduler"}],"outputs":[{"name":"samples","type":"LATENT","links":[149],"slot_index":0,"shape":3,"label":"samples"}],"title":"MimicMotion Sampler - B站 艾橘溪","properties":{"Node name for S&R":"MimicMotionSampler"},"widgets_values":[25,2,2,42,"fixed",15,0,16,6,false,1,0,1,1]},{"id":17,"type":"ImageConcatMulti","pos":{"0":1480,"1":639},"size":{"0":295.9825134277344,"1":199.4539794921875},"flags":{},"order":11,"mode":0,"inputs":[{"name":"image_1","type":"IMAGE","link":95,"label":"image_1"},{"name":"image_2","type":"IMAGE","link":137,"label":"image_2"},{"name":"image_3","type":"IMAGE","link":138,"label":"image_3"},{"name":"image_4","type":"IMAGE","link":151,"label":"image_4"}],"outputs":[{"name":"images","type":"IMAGE","links":[93],"slot_index":0,"shape":3,"label":"images"}],"title":"Image Concatenate Multi -B站 艾橘溪","properties":{},"widgets_values":[4,"right",false,null]},{"id":59,"type":"VHS_VideoCombine","pos":{"0":1109,"1":910},"size":[350.4765930175781,310],"flags":{},"order":12,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":152,"slot_index":0,"label":"images"},{"name":"audio","type":"VHS_AUDIO","link":null,"label":"audio"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"meta_batch"},{"name":"vae","type":"VAE","link":null,"label":"vae"}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"Filenames"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":30,"loop_count":0,"filename_prefix":"MimicMotion/min","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"min_00038.mp4","subfolder":"MimicMotion","type":"output","format":"video/h264-mp4","frame_rate":30}}}},{"id":3,"type":"LoadImage","pos":{"0":-477,"1":761},"size":{"0":362.3768615722656,"1":721.183837890625},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[61],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["背景.jpg","image"]},{"id":5,"type":"VHS_LoadVideo","pos":{"0":-81,"1":748},"size":[280.4635925292969,739.04638671875],"flags":{},"order":3,"mode":0,"inputs":[{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"meta_batch"},{"name":"vae","type":"VAE","link":null,"label":"vae"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[86],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"frame_count","type":"INT","links":null,"shape":3,"label":"frame_count"},{"name":"audio","type":"VHS_AUDIO","links":null,"shape":3,"label":"audio"},{"name":"video_info","type":"VHS_VIDEOINFO","links":null,"shape":3,"label":"video_info"}],"properties":{"Node name for S&R":"VHS_LoadVideo"},"widgets_values":{"video":"31231.mp4","force_rate":0,"force_size":"Disabled","custom_width":512,"custom_height":512,"frame_load_cap":0,"skip_first_frames":0,"select_every_nth":1,"choose video to upload":"image","videopreview":{"hidden":false,"paused":false,"params":{"frame_load_cap":0,"skip_first_frames":0,"force_rate":0,"filename":"31231.mp4","type":"input","format":"video/mp4","select_every_nth":1}}}}],"links":[[61,3,0,28,0,"IMAGE"],[86,5,0,35,0,"IMAGE"],[88,28,1,35,2,"INT"],[89,28,2,35,3,"INT"],[93,17,0,16,0,"IMAGE"],[95,28,0,17,0,"IMAGE"],[110,28,0,42,0,"IMAGE"],[111,35,0,42,1,"IMAGE"],[112,42,0,9,0,"IMAGE"],[114,42,0,37,0,"IMAGE"],[137,35,0,17,1,"IMAGE"],[138,42,1,17,2,"IMAGE"],[146,2,0,57,0,"MIMICPIPE"],[147,28,0,57,1,"IMAGE"],[148,9,0,57,2,"IMAGE"],[149,57,0,58,1,"LATENT"],[150,2,0,58,0,"MIMICPIPE"],[151,58,0,17,3,"IMAGE"],[152,58,0,59,0,"IMAGE"]],"groups":[{"title":"图片生成跳舞视频 MimicMotion！B站：艾橘溪。Ai微信群，请加微信号：abinsz，进群","bounding":[60,158,974,207],"color":"#b58b2a","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.620921323059155,"offset":[690.7392041398416,-3.4890160370756576]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI-MimicMotionWrapper
https://github.com/kijai/ComfyUI-MimicMotionWrapper
