### ISSUE TITLE
Flux errors since latest update

### ISSUE THREAD

**Issue by Tromazing** [comfyanonymous/ComfyUI#4862]
### Expected Behavior

Expected to generate image using established basic Flux workflow.

### Actual Behavior

Errors:
![Screenshot 2024-09-09 121643](https://github.com/user-attachments/assets/fb1f4afd-aeea-477d-b334-eab99ab59699)
I've tried updating all nodes and rebooting machine.
Other models seem ok - generating in PonyXL works with no problems.

### Steps to Reproduce

Json attached.
[FluxError.json](https://github.com/user-attachments/files/16929621/FluxError.json)

### Debug Logs

```powershell
got prompt
Using xformers attention in VAE
Using xformers attention in VAE
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
clip missing: ['text_projection.weight']
!!! Exception during processing !!! Error(s) in loading state_dict for Sequential:
	Missing key(s) in state_dict: "1.weight", "1.bias", "3.conv.0.weight", "3.conv.0.bias", "3.conv.2.weight", "3.conv.2.bias", "3.conv.4.weight", "3.conv.4.bias", "4.conv.0.weight", "4.conv.0.bias", "4.conv.2.weight", "4.conv.2.bias", "4.conv.4.weight", "4.conv.4.bias", "5.conv.0.weight", "5.conv.0.bias", "5.conv.2.weight", "5.conv.2.bias", "5.conv.4.weight", "5.conv.4.bias", "7.weight", "8.conv.0.weight", "8.conv.0.bias", "8.conv.2.weight", "8.conv.2.bias", "8.conv.4.weight", "8.conv.4.bias", "9.conv.0.weight", "9.conv.0.bias", "9.conv.2.weight", "9.conv.2.bias", "9.conv.4.weight", "9.conv.4.bias", "10.conv.0.weight", "10.conv.0.bias", "10.conv.2.weight", "10.conv.2.bias", "10.conv.4.weight", "10.conv.4.bias", "12.weight", "13.conv.0.weight", "13.conv.0.bias", "13.conv.2.weight", "13.conv.2.bias", "13.conv.4.weight", "13.conv.4.bias", "14.conv.0.weight", "14.conv.0.bias", "14.conv.2.weight", "14.conv.2.bias", "14.conv.4.weight", "14.conv.4.bias", "15.conv.0.weight", "15.conv.0.bias", "15.conv.2.weight", "15.conv.2.bias", "15.conv.4.weight", "15.conv.4.bias", "17.weight", "18.conv.0.weight", "18.conv.0.bias", "18.conv.2.weight", "18.conv.2.bias", "18.conv.4.weight", "18.conv.4.bias", "19.weight", "19.bias". 
	Unexpected key(s) in state_dict: "decoder.layers.0.bias", "decoder.layers.0.weight", "decoder.layers.11.weight", "decoder.layers.12.conv.0.bias", "decoder.layers.12.conv.0.weight", "decoder.layers.12.conv.2.bias", "decoder.layers.12.conv.2.weight", "decoder.layers.12.conv.4.bias", "decoder.layers.12.conv.4.weight", "decoder.layers.13.conv.0.bias", "decoder.layers.13.conv.0.weight", "decoder.layers.13.conv.2.bias", "decoder.layers.13.conv.2.weight", "decoder.layers.13.conv.4.bias", "decoder.layers.13.conv.4.weight", "decoder.layers.14.conv.0.bias", "decoder.layers.14.conv.0.weight", "decoder.layers.14.conv.2.bias", "decoder.layers.14.conv.2.weight", "decoder.layers.14.conv.4.bias", "decoder.layers.14.conv.4.weight", "decoder.layers.16.weight", "decoder.layers.17.conv.0.bias", "decoder.layers.17.conv.0.weight", "decoder.layers.17.conv.2.bias", "decoder.layers.17.conv.2.weight", "decoder.layers.17.conv.4.bias", "decoder.layers.17.conv.4.weight", "decoder.layers.18.bias", "decoder.layers.18.weight", "decoder.layers.2.conv.0.bias", "decoder.layers.2.conv.0.weight", "decoder.layers.2.conv.2.bias", "decoder.layers.2.conv.2.weight", "decoder.layers.2.conv.4.bias", "decoder.layers.2.conv.4.weight", "decoder.layers.3.conv.0.bias", "decoder.layers.3.conv.0.weight", "decoder.layers.3.conv.2.bias", "decoder.layers.3.conv.2.weight", "decoder.layers.3.conv.4.bias", "decoder.layers.3.conv.4.weight", "decoder.layers.4.conv.0.bias", "decoder.layers.4.conv.0.weight", "decoder.layers.4.conv.2.bias", "decoder.layers.4.conv.2.weight", "decoder.layers.4.conv.4.bias", "decoder.layers.4.conv.4.weight", "decoder.layers.6.weight", "decoder.layers.7.conv.0.bias", "decoder.layers.7.conv.0.weight", "decoder.layers.7.conv.2.bias", "decoder.layers.7.conv.2.weight", "decoder.layers.7.conv.4.bias", "decoder.layers.7.conv.4.weight", "decoder.layers.8.conv.0.bias", "decoder.layers.8.conv.0.weight", "decoder.layers.8.conv.2.bias", "decoder.layers.8.conv.2.weight", "decoder.layers.8.conv.4.bias", "decoder.layers.8.conv.4.weight", "decoder.layers.9.conv.0.bias", "decoder.layers.9.conv.0.weight", "decoder.layers.9.conv.2.bias", "decoder.layers.9.conv.2.weight", "decoder.layers.9.conv.4.bias", "decoder.layers.9.conv.4.weight", "encoder.layers.0.bias", "encoder.layers.0.weight", "encoder.layers.1.conv.0.bias", "encoder.layers.1.conv.0.weight", "encoder.layers.1.conv.2.bias", "encoder.layers.1.conv.2.weight", "encoder.layers.1.conv.4.bias", "encoder.layers.1.conv.4.weight", "encoder.layers.10.weight", "encoder.layers.11.conv.0.bias", "encoder.layers.11.conv.0.weight", "encoder.layers.11.conv.2.bias", "encoder.layers.11.conv.2.weight", "encoder.layers.11.conv.4.bias", "encoder.layers.11.conv.4.weight", "encoder.layers.12.conv.0.bias", "encoder.layers.12.conv.0.weight", "encoder.layers.12.conv.2.bias", "encoder.layers.12.conv.2.weight", "encoder.layers.12.conv.4.bias", "encoder.layers.12.conv.4.weight", "encoder.layers.13.conv.0.bias", "encoder.layers.13.conv.0.weight", "encoder.layers.13.conv.2.bias", "encoder.layers.13.conv.2.weight", "encoder.layers.13.conv.4.bias", "encoder.layers.13.conv.4.weight", "encoder.layers.14.bias", "encoder.layers.14.weight", "encoder.layers.2.weight", "encoder.layers.3.conv.0.bias", "encoder.layers.3.conv.0.weight", "encoder.layers.3.conv.2.bias", "encoder.layers.3.conv.2.weight", "encoder.layers.3.conv.4.bias", "encoder.layers.3.conv.4.weight", "encoder.layers.4.conv.0.bias", "encoder.layers.4.conv.0.weight", "encoder.layers.4.conv.2.bias", "encoder.layers.4.conv.2.weight", "encoder.layers.4.conv.4.bias", "encoder.layers.4.conv.4.weight", "encoder.layers.5.conv.0.bias", "encoder.layers.5.conv.0.weight", "encoder.layers.5.conv.2.bias", "encoder.layers.5.conv.2.weight", "encoder.layers.5.conv.4.bias", "encoder.layers.5.conv.4.weight", "encoder.layers.6.weight", "encoder.layers.7.conv.0.bias", "encoder.layers.7.conv.0.weight", "encoder.layers.7.conv.2.bias", "encoder.layers.7.conv.2.weight", "encoder.layers.7.conv.4.bias", "encoder.layers.7.conv.4.weight", "encoder.layers.8.conv.0.bias", "encoder.layers.8.conv.0.weight", "encoder.layers.8.conv.2.bias", "encoder.layers.8.conv.2.weight", "encoder.layers.8.conv.4.bias", "encoder.layers.8.conv.4.weight", "encoder.layers.9.conv.0.bias", "encoder.layers.9.conv.0.weight", "encoder.layers.9.conv.2.bias", "encoder.layers.9.conv.2.weight", "encoder.layers.9.conv.4.bias", "encoder.layers.9.conv.4.weight". 
Traceback (most recent call last):
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\StableDiffusion\Packages\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 609, in sample
    callback = latent_preview.prepare_callback(guider.model_patcher, sigmas.shape[-1] - 1, x0_output)
  File "D:\StableDiffusion\Packages\ComfyUI\latent_preview.py", line 82, in prepare_callback
    previewer = get_previewer(model.load_device, model.model.latent_format)
  File "D:\StableDiffusion\Packages\ComfyUI\latent_preview.py", line 67, in get_previewer
    taesd = TAESD(None, taesd_decoder_path, latent_channels=latent_format.latent_channels).to(device)
  File "D:\StableDiffusion\Packages\ComfyUI\comfy\taesd\taesd.py", line 61, in __init__
    self.taesd_decoder.load_state_dict(comfy.utils.load_torch_file(decoder_path, safe_load=True))
  File "D:\StableDiffusion\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Sequential:
	Missing key(s) in state_dict: "1.weight", "1.bias", "3.conv.0.weight", "3.conv.0.bias", "3.conv.2.weight", "3.conv.2.bias", "3.conv.4.weight", "3.conv.4.bias", "4.conv.0.weight", "4.conv.0.bias", "4.conv.2.weight", "4.conv.2.bias", "4.conv.4.weight", "4.conv.4.bias", "5.conv.0.weight", "5.conv.0.bias", "5.conv.2.weight", "5.conv.2.bias", "5.conv.4.weight", "5.conv.4.bias", "7.weight", "8.conv.0.weight", "8.conv.0.bias", "8.conv.2.weight", "8.conv.2.bias", "8.conv.4.weight", "8.conv.4.bias", "9.conv.0.weight", "9.conv.0.bias", "9.conv.2.weight", "9.conv.2.bias", "9.conv.4.weight", "9.conv.4.bias", "10.conv.0.weight", "10.conv.0.bias", "10.conv.2.weight", "10.conv.2.bias", "10.conv.4.weight", "10.conv.4.bias", "12.weight", "13.conv.0.weight", "13.conv.0.bias", "13.conv.2.weight", "13.conv.2.bias", "13.conv.4.weight", "13.conv.4.bias", "14.conv.0.weight", "14.conv.0.bias", "14.conv.2.weight", "14.conv.2.bias", "14.conv.4.weight", "14.conv.4.bias", "15.conv.0.weight", "15.conv.0.bias", "15.conv.2.weight", "15.conv.2.bias", "15.conv.4.weight", "15.conv.4.bias", "17.weight", "18.conv.0.weight", "18.conv.0.bias", "18.conv.2.weight", "18.conv.2.bias", "18.conv.4.weight", "18.conv.4.bias", "19.weight", "19.bias". 
	Unexpected key(s) in state_dict: "decoder.layers.0.bias", "decoder.layers.0.weight", "decoder.layers.11.weight", "decoder.layers.12.conv.0.bias", "decoder.layers.12.conv.0.weight", "decoder.layers.12.conv.2.bias", "decoder.layers.12.conv.2.weight", "decoder.layers.12.conv.4.bias", "decoder.layers.12.conv.4.weight", "decoder.layers.13.conv.0.bias", "decoder.layers.13.conv.0.weight", "decoder.layers.13.conv.2.bias", "decoder.layers.13.conv.2.weight", "decoder.layers.13.conv.4.bias", "decoder.layers.13.conv.4.weight", "decoder.layers.14.conv.0.bias", "decoder.layers.14.conv.0.weight", "decoder.layers.14.conv.2.bias", "decoder.layers.14.conv.2.weight", "decoder.layers.14.conv.4.bias", "decoder.layers.14.conv.4.weight", "decoder.layers.16.weight", "decoder.layers.17.conv.0.bias", "decoder.layers.17.conv.0.weight", "decoder.layers.17.conv.2.bias", "decoder.layers.17.conv.2.weight", "decoder.layers.17.conv.4.bias", "decoder.layers.17.conv.4.weight", "decoder.layers.18.bias", "decoder.layers.18.weight", "decoder.layers.2.conv.0.bias", "decoder.layers.2.conv.0.weight", "decoder.layers.2.conv.2.bias", "decoder.layers.2.conv.2.weight", "decoder.layers.2.conv.4.bias", "decoder.layers.2.conv.4.weight", "decoder.layers.3.conv.0.bias", "decoder.layers.3.conv.0.weight", "decoder.layers.3.conv.2.bias", "decoder.layers.3.conv.2.weight", "decoder.layers.3.conv.4.bias", "decoder.layers.3.conv.4.weight", "decoder.layers.4.conv.0.bias", "decoder.layers.4.conv.0.weight", "decoder.layers.4.conv.2.bias", "decoder.layers.4.conv.2.weight", "decoder.layers.4.conv.4.bias", "decoder.layers.4.conv.4.weight", "decoder.layers.6.weight", "decoder.layers.7.conv.0.bias", "decoder.layers.7.conv.0.weight", "decoder.layers.7.conv.2.bias", "decoder.layers.7.conv.2.weight", "decoder.layers.7.conv.4.bias", "decoder.layers.7.conv.4.weight", "decoder.layers.8.conv.0.bias", "decoder.layers.8.conv.0.weight", "decoder.layers.8.conv.2.bias", "decoder.layers.8.conv.2.weight", "decoder.layers.8.conv.4.bias", "decoder.layers.8.conv.4.weight", "decoder.layers.9.conv.0.bias", "decoder.layers.9.conv.0.weight", "decoder.layers.9.conv.2.bias", "decoder.layers.9.conv.2.weight", "decoder.layers.9.conv.4.bias", "decoder.layers.9.conv.4.weight", "encoder.layers.0.bias", "encoder.layers.0.weight", "encoder.layers.1.conv.0.bias", "encoder.layers.1.conv.0.weight", "encoder.layers.1.conv.2.bias", "encoder.layers.1.conv.2.weight", "encoder.layers.1.conv.4.bias", "encoder.layers.1.conv.4.weight", "encoder.layers.10.weight", "encoder.layers.11.conv.0.bias", "encoder.layers.11.conv.0.weight", "encoder.layers.11.conv.2.bias", "encoder.layers.11.conv.2.weight", "encoder.layers.11.conv.4.bias", "encoder.layers.11.conv.4.weight", "encoder.layers.12.conv.0.bias", "encoder.layers.12.conv.0.weight", "encoder.layers.12.conv.2.bias", "encoder.layers.12.conv.2.weight", "encoder.layers.12.conv.4.bias", "encoder.layers.12.conv.4.weight", "encoder.layers.13.conv.0.bias", "encoder.layers.13.conv.0.weight", "encoder.layers.13.conv.2.bias", "encoder.layers.13.conv.2.weight", "encoder.layers.13.conv.4.bias", "encoder.layers.13.conv.4.weight", "encoder.layers.14.bias", "encoder.layers.14.weight", "encoder.layers.2.weight", "encoder.layers.3.conv.0.bias", "encoder.layers.3.conv.0.weight", "encoder.layers.3.conv.2.bias", "encoder.layers.3.conv.2.weight", "encoder.layers.3.conv.4.bias", "encoder.layers.3.conv.4.weight", "encoder.layers.4.conv.0.bias", "encoder.layers.4.conv.0.weight", "encoder.layers.4.conv.2.bias", "encoder.layers.4.conv.2.weight", "encoder.layers.4.conv.4.bias", "encoder.layers.4.conv.4.weight", "encoder.layers.5.conv.0.bias", "encoder.layers.5.conv.0.weight", "encoder.layers.5.conv.2.bias", "encoder.layers.5.conv.2.weight", "encoder.layers.5.conv.4.bias", "encoder.layers.5.conv.4.weight", "encoder.layers.6.weight", "encoder.layers.7.conv.0.bias", "encoder.layers.7.conv.0.weight", "encoder.layers.7.conv.2.bias", "encoder.layers.7.conv.2.weight", "encoder.layers.7.conv.4.bias", "encoder.layers.7.conv.4.weight", "encoder.layers.8.conv.0.bias", "encoder.layers.8.conv.0.weight", "encoder.layers.8.conv.2.bias", "encoder.layers.8.conv.2.weight", "encoder.layers.8.conv.4.bias", "encoder.layers.8.conv.4.weight", "encoder.layers.9.conv.0.bias", "encoder.layers.9.conv.0.weight", "encoder.layers.9.conv.2.bias", "encoder.layers.9.conv.2.weight", "encoder.layers.9.conv.4.bias", "encoder.layers.9.conv.4.weight". 

Prompt executed in 276.36 seconds
```

**Comment by ltdrdata** [comment]
Verify that the files `taef1_decoder.pth` and `taef1_encoder.pth` have been downloaded correctly.

**Comment by Tromazing** [comment]
*slaps forehead for not realising earlier*. Fixed. Thanks!
