### ISSUE TITLE
pip install -r requirements.txt  numpy (>=1.19.*) ; python_version >= "3.7"

### ISSUE THREAD

**Issue by why-is-me** [comfyanonymous/ComfyUI#4895]
### Expected Behavior

I am installing ComfyUI using source code on ununtu22.04, Python version 3.11.4, numpy version 1.26.4

### Actual Behavior

ERROR: Exception:
Traceback (most recent call last):
  ........
pip._vendor.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^


### Steps to Reproduce

pip install -r requirements.txt

### Debug Logs

```powershell
pip install -r requirements.txt
Requirement already satisfied: torch in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 1)) (2.5.0.dev20240911+cu124)
Requirement already satisfied: torchsde in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 2)) (0.2.5)
Requirement already satisfied: torchvision in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 3)) (0.20.0.dev20240911+cu124)
Requirement already satisfied: torchaudio in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 4)) (2.5.0.dev20240911+cu124)
Requirement already satisfied: einops in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 5)) (0.4.1)
Requirement already satisfied: transformers>=4.28.1 in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 6)) (4.40.2)
Requirement already satisfied: tokenizers>=0.13.3 in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 7)) (0.19.1)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 8)) (0.1.99)
Requirement already satisfied: safetensors>=0.4.2 in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 9)) (0.4.3)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 10)) (3.8.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (6.0.1)
Requirement already satisfied: Pillow in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (9.5.0)
Collecting scipy==1.12.0 (from -r requirements.txt (line 13))
  Using cached scipy-1.12.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
Requirement already satisfied: tqdm in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 14)) (4.66.4)
Requirement already satisfied: psutil in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 15)) (5.9.5)
Collecting kornia>=0.7.1 (from -r requirements.txt (line 18))
  Using cached kornia-0.7.3-py2.py3-none-any.whl.metadata (7.7 kB)
Collecting spandrel (from -r requirements.txt (line 19))
  Using cached spandrel-0.3.4-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: soundfile in /usr/local/lib/python3.11/site-packages (from -r requirements.txt (line 20)) (0.12.1)
Collecting numpy==1.26.4 (from -r requirements.txt (line 21))
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.12.3)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (4.11.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (2023.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (12.4.127)
Requirement already satisfied: pytorch-triton==3.1.0+5fe38ffd73 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.1.0+5fe38ffd73)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/site-packages (from sympy==1.13.1->torch->-r requirements.txt (line 1)) (1.3.0)
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/requirements.py", line 36, in __init__
    parsed = _parse_requirement(requirement_string)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 62, in parse_requirement
    return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 80, in _parse_requirement
    url, specifier, marker = _parse_requirement_details(tokenizer)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 118, in _parse_requirement_details
    specifier = _parse_specifier(tokenizer)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 214, in _parse_specifier
    parsed_specifiers = _parse_version_many(tokenizer)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/_parser.py", line 229, in _parse_version_many
    tokenizer.raise_syntax_error(
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/_tokenizer.py", line 167, in raise_syntax_error
    raise ParserSyntaxError(
pip._vendor.packaging._tokenizer.ParserSyntaxError: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 427, in resolve
    failure_causes = self._attempt_to_pin_criterion(name)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 239, in _attempt_to_pin_criterion
    criteria = self._get_updated_criteria(candidate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 229, in _get_updated_criteria
    for requirement in self._p.get_dependencies(candidate=candidate):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 247, in get_dependencies
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/provider.py", line 247, in <listcomp>
    return [r for r in candidate.iter_dependencies(with_requires) if r is not None]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 401, in iter_dependencies
    for r in self.dist.iter_dependencies():
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_dists.py", line 215, in iter_dependencies
    req = get_requirement(req_string.strip())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_internal/utils/packaging.py", line 45, in get_requirement
    return Requirement(req_string)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pip/_vendor/packaging/requirements.py", line 38, in __init__
    raise InvalidRequirement(str(e)) from e
pip._vendor.packaging.requirements.InvalidRequirement: .* suffix can only be used with `==` or `!=` operators
    numpy (>=1.19.*) ; python_version >= "3.7"
           ~~~~~~~^
```


### Other

_No response_

**Comment by ltdrdata** [comment]
`pip install --upgrade pip` and try again.

**Comment by why-is-me** [comment]
> `pip install --upgrade pip` and try again.

Thanks, The current version of pip I am using is 24.2, which is displayed as the latest version.
Then, I forcibly uninstalled pip and reinstalled it using： python - m secureprip - upgrade
My current pip version is 23.1.2
Finally execute:  pip3 install -r requirements.txt
 it's fine now，pip needs to be downgraded
