### ISSUE TITLE
Custom Node is not defined after update to ComfyUI v0.2.2

### ISSUE THREAD

**Issue by MaraScott** [comfyanonymous/ComfyUI#4897]
### Expected Behavior

I developped Custom Node and when I had it to the workflow they work as expected, nothing special

### Actual Behavior

once added to the workflow, if I click on it, the text, fields, inputs, outputs disapear and I got a console log message

```
Uncaught ReferenceError: node is not defined
    at __LGraphCanvas.drawSelectionBounding (litegraph.es.js:8280:65)
    at __LGraphCanvas.drawNodeShape (litegraph.es.js:8231:14)
    at LGraphCanvas.drawNodeShape (app.ts:1444:37)
    at __LGraphCanvas.drawNode (litegraph.es.js:7711:12)
    at LGraphCanvas.drawNode (label.js:130:27)
    at LGraphCanvas.drawNode (snapToGrid.ts:106:27)
    at LGraphCanvas.drawNode (snapToGrid.js:216:24)
    at snapToGrid.js:130:43
    at wrapCallInSettingCheck (snapToGrid.js:27:9)
    at LGraphCanvas.drawNode (snapToGrid.js:130:5)
```

### Steps to Reproduce

use an empty workflow, make sure to use ComfyUI v0.2.2, install ComfyUI-Manager, and MaraScott node https://github.com/MaraScott/ComfyUI_MaraScott_Nodes?tab=readme-ov-file#anybus-node-aka-universalbus-node

on workflow add **"🐰 AnyBus - UniversalBus v2 /*"** _(not the one with a cross ❌)_

### Debug Logs

```powershell
js console.log 


Uncaught ReferenceError: node is not defined
    at __LGraphCanvas.drawSelectionBounding (litegraph.es.js:8280:65)
    at __LGraphCanvas.drawNodeShape (litegraph.es.js:8231:14)
    at LGraphCanvas.drawNodeShape (app.ts:1444:37)
    at __LGraphCanvas.drawNode (litegraph.es.js:7711:12)
    at LGraphCanvas.drawNode (label.js:130:27)
    at LGraphCanvas.drawNode (snapToGrid.ts:106:27)
    at LGraphCanvas.drawNode (snapToGrid.js:216:24)
    at snapToGrid.js:130:43
    at wrapCallInSettingCheck (snapToGrid.js:27:9)
    at LGraphCanvas.drawNode (snapToGrid.js:130:5)
```
```


### Other

_No response_

**Comment by christian-byrne** [comment]
This issue is fixed by Comfy-Org/litegraph.js#126. It will be fixed on the next frontend update. Verify by launching with `--front-end-version Comfy-Org/ComfyUI_frontend@latest`

**Comment by MaraScott** [comment]
Hi @christian-byrne , thx, it seems to work now.
