### ISSUE TITLE
VAEDecode Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead

### ISSUE THREAD

**Issue by StefanIgnjatovic12** [comfyanonymous/ComfyUI#4900]
### Your question

Hi,

Trying to use ComfyUI with flux dev and a LoRA but keep getting this error. ComfyUI is up to date. I'm on runpod and using the aitrepreneur/comfyui:2.3.5 template. I've tried with a few different workflows and keep getting the same error. Also tried updating pytorch but no dice. 

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** VAEDecode
- **Exception Type:** RuntimeError
- **Exception Message:** Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead
## Stack Trace

  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/comfy/sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 199, in decode
    dec = self.post_quant_conv(z)
          ^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/workspace/ComfyUI/comfy/ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-31-gb962db9
- **Arguments:** main.py --listen 0.0.0.0 --port 3001
- **OS:** posix
- **Python Version:** 3.11.9 (main, Apr  6 2024, 17:59:24) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA A40 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 47622258688
  - **VRAM Free:** 13501833066
  - **Torch VRAM Total:** 33923530752
  - **Torch VRAM Free:** 172924778

## Logs
```
2024-09-12 12:55:10,001 - root - INFO - Total VRAM 45416 MB, total RAM 515616 MB
2024-09-12 12:55:10,002 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-12 12:55:15,488 - root - INFO - xformers version: 0.0.27.post2
2024-09-12 12:55:15,489 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-12 12:55:15,490 - root - INFO - Device: cuda:0 NVIDIA A40 : cudaMallocAsync
2024-09-12 12:55:16,042 - root - INFO - Using xformers cross attention
2024-09-12 12:55:25,469 - root - INFO - [Prompt Server] web root: /workspace/ComfyUI/web
2024-09-12 12:55:34,939 - root - INFO - 
Import times for custom nodes:
2024-09-12 12:55:34,948 - root - INFO -    0.0 seconds: /workspace/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-12 12:55:34,950 - root - INFO -    0.0 seconds: /workspace/ComfyUI/custom_nodes/extended-saveimage-comfyui
2024-09-12 12:55:34,952 - root - INFO -    0.2 seconds: /workspace/ComfyUI/custom_nodes/mikey_nodes
2024-09-12 12:55:34,954 - root - INFO -    0.3 seconds: /workspace/ComfyUI/custom_nodes/save-image-extended-comfyui
2024-09-12 12:55:34,955 - root - INFO -    0.4 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-12 12:55:34,957 - root - INFO -    0.9 seconds: /workspace/ComfyUI/custom_nodes/rgthree-comfy
2024-09-12 12:55:34,958 - root - INFO - 
2024-09-12 12:55:34,993 - root - INFO - Starting server

2024-09-12 12:55:34,997 - root - INFO - To see the GUI go to: http://0.0.0.0:3001
2024-09-12 12:57:37,709 - root - INFO - got prompt
2024-09-12 12:57:37,824 - root - ERROR - Failed to validate prompt for output 33:
2024-09-12 12:57:37,826 - root - ERROR - * VAELoader 10:
2024-09-12 12:57:37,827 - root - ERROR -   - Value not in list: vae_name: 'ae.sft' not in ['sdxl_vae.safetensors']
2024-09-12 12:57:37,828 - root - ERROR - Output will be ignored
2024-09-12 12:57:37,829 - root - WARNING - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-09-12 12:58:07,459 - root - INFO - got prompt
2024-09-12 12:58:08,151 - root - INFO - Using xformers attention in VAE
2024-09-12 12:58:08,156 - root - INFO - Using xformers attention in VAE
2024-09-12 12:58:12,990 - root - INFO - model weight dtype torch.bfloat16, manual cast: None
2024-09-12 12:58:12,996 - root - INFO - model_type FLUX
2024-09-12 12:59:43,640 - root - WARNING - clip missing: ['text_projection.weight']
2024-09-12 12:59:44,861 - root - INFO - Requested to load FluxClipModel_
2024-09-12 12:59:44,862 - root - INFO - Loading 1 new model
2024-09-12 12:59:52,616 - root - INFO - loaded completely 0.0 9319.23095703125 True
2024-09-12 12:59:53,623 - root - INFO - Requested to load Flux
2024-09-12 12:59:53,624 - root - INFO - Loading 1 new model
2024-09-12 13:00:03,452 - root - INFO - loaded completely 0.0 22700.097778320312 True
2024-09-12 13:00:37,015 - root - INFO - Requested to load AutoencoderKL
2024-09-12 13:00:37,016 - root - INFO - Loading 1 new model
2024-09-12 13:00:37,080 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-09-12 13:00:37,092 - root - ERROR - !!! Exception during processing !!! Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead
2024-09-12 13:00:37,136 - root - ERROR - Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 199, in decode
    dec = self.post_quant_conv(z)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead

2024-09-12 13:00:37,139 - root - INFO - Prompt executed in 149.55 seconds
2024-09-12 13:08:07,704 - root - INFO - got prompt
2024-09-12 13:08:08,124 - root - INFO - Requested to load FluxClipModel_
2024-09-12 13:08:08,125 - root - INFO - Loading 1 new model
2024-09-12 13:08:08,381 - root - INFO - Requested to load Flux
2024-09-12 13:08:08,381 - root - INFO - Loading 1 new model
2024-09-12 13:08:23,994 - root - INFO - loaded completely 0.0 22700.097778320312 True
2024-09-12 13:08:49,568 - root - ERROR - !!! Exception during processing !!! Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead
2024-09-12 13:08:49,574 - root - ERROR - Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 199, in decode
    dec = self.post_quant_conv(z)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead

2024-09-12 13:08:49,577 - root - INFO - Prompt executed in 41.84 seconds
2024-09-12 13:15:25,251 - root - INFO - got prompt
2024-09-12 13:15:51,396 - root - ERROR - !!! Exception during processing !!! Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead
2024-09-12 13:15:51,398 - root - ERROR - Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/nodes.py", line 284, in decode
    return (vae.decode(samples["samples"]), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/sd.py", line 328, in decode
    pixel_samples[x:x+batch_number] = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 199, in decode
    dec = self.post_quant_conv(z)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/ComfyUI/comfy/ops.py", line 106, in forward
    return super().forward(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 144, 112] to have 4 channels, but got 16 channels instead

2024-09-12 13:15:51,400 - root - INFO - Prompt executed in 26.02 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":34,"last_link_id":68,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":660,"1":50},"size":{"0":210,"1":46},"flags":{"collapsed":true,"pinned":false},"order":13,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":24},{"name":"vae","type":"VAE","link":12}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[60],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"color":"#332922","bgcolor":"#593930","shape":1},{"id":13,"type":"SamplerCustomAdvanced","pos":{"0":440,"1":680},"size":{"0":236.8000030517578,"1":106},"flags":{"collapsed":false,"pinned":false},"order":12,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":37,"slot_index":0},{"name":"guider","type":"GUIDER","link":30,"slot_index":1},{"name":"sampler","type":"SAMPLER","link":19,"slot_index":2},{"name":"sigmas","type":"SIGMAS","link":20,"slot_index":3},{"name":"latent_image","type":"LATENT","link":68,"slot_index":4}],"outputs":[{"name":"output","type":"LATENT","links":[24],"slot_index":0,"shape":3},{"name":"denoised_output","type":"LATENT","links":null,"shape":3}],"properties":{"Node name for S&R":"SamplerCustomAdvanced"},"color":"#332922","bgcolor":"#593930","shape":1},{"id":22,"type":"BasicGuider","pos":{"0":370,"1":50},"size":{"0":241.79998779296875,"1":46},"flags":{"collapsed":true,"pinned":false},"order":11,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":63,"slot_index":0},{"name":"conditioning","type":"CONDITIONING","link":43,"slot_index":1}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[30],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"BasicGuider"},"color":"#323","bgcolor":"#535","shape":1},{"id":26,"type":"Empty Latent Ratio Select SDXL","pos":{"0":40,"1":660},"size":{"0":319.20001220703125,"1":82},"flags":{"collapsed":false,"pinned":false},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[68],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"Empty Latent Ratio Select SDXL"},"widgets_values":["3:4 [896x1152 portrait]",1],"color":"#323","bgcolor":"#535","shape":1},{"id":28,"type":"EmptyLatentImage","pos":{"0":40,"1":790},"size":{"0":315,"1":106},"flags":{"pinned":false},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[552,752,1],"color":"#291529","bgcolor":"#3d293d","shape":1},{"id":25,"type":"RandomNoise","pos":{"0":20,"1":440},"size":{"0":315,"1":82},"flags":{"pinned":false},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[37],"shape":3}],"properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[775158970588122,"randomize"],"color":"#323","bgcolor":"#535","shape":1},{"id":33,"type":"SaveImageExtended","pos":{"0":830,"1":120},"size":{"0":728.0142822265625,"1":678.1754150390625},"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":60}],"outputs":[],"properties":{"Node name for S&R":"SaveImageExtended"},"widgets_values":["Flux/image","PNG","","ckpt_name","-","disabled",false,"",true,4,"last",true,true,".webp",90,false,"",""],"color":"#002b52","bgcolor":"#4a4a4a","shape":1},{"id":12,"type":"UNETLoader","pos":{"0":26,"1":145},"size":{"0":315,"1":82},"flags":{"pinned":false},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[38,61],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux1-dev.safetensors","default"],"shape":1},{"id":11,"type":"DualCLIPLoader","pos":{"0":28,"1":276},"size":{"0":315,"1":106},"flags":{"pinned":false},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[62],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["t5xxl_fp16.safetensors","clip_l.safetensors","flux"],"shape":1},{"id":27,"type":"FluxGuidance","pos":{"0":27,"1":34},"size":{"0":317.4000244140625,"1":58},"flags":{"pinned":false},"order":10,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":42}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[43],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"FluxGuidance"},"widgets_values":[1.9000000000000001],"color":"#223","bgcolor":"#335","shape":1},{"id":10,"type":"VAELoader","pos":{"0":512,"1":12},"size":{"0":315,"1":58},"flags":{"collapsed":true,"pinned":false},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[12],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["sdxl_vae.safetensors"],"color":"#323","bgcolor":"#535","shape":1},{"id":6,"type":"CLIPTextEncode","pos":{"0":368,"1":117},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{"pinned":false},"order":9,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":64}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[42],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["A captivating photograph capturing StefanIgnjatovic man standing confidently on a snow-blanketed forest trail during the tranquil, ethereal hour of dusk. The scene is framed in a vertical orientation, accentuating the tall, majestic trees that stretch upwards, their branches dusted with freshly fallen snow. Soft, muted hues of purples and blues fill the sky, as the last remnants of daylight gently embrace the landscape, creating a serene and contemplative atmosphere. StefanIgnjatovic man is positioned slightly off-center, his expression thoughtful, as he gazes down the winding path that disappears into the delicate whisper of falling snowflakes. \n\nThe photograph employs a shallow depth of field, with a slight bokeh effect capturing snowflakes in mid-air, adding dimension and a sense of serenity to the composition. The scene is illuminated with soft, ambient lighting, a subtle interplay of natural and magical, casting gentle shadows and highlighting textures in the snow and bark of the trees. The forest exudes a sense of quiet solitude and timeless beauty, enveloping the viewer in its calming embrace. The style draws inspiration from Impressionist techniques, where light's play is paramount, offering both realism and a picturesque, dreamlike quality to the winter scene."],"color":"#232","bgcolor":"#353","shape":1},{"id":34,"type":"Lora Loader Stack (rgthree)","pos":{"0":-320,"1":280},"size":{"0":315,"1":246},"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":61},{"name":"clip","type":"CLIP","link":62}],"outputs":[{"name":"MODEL","type":"MODEL","links":[63],"slot_index":0,"shape":3},{"name":"CLIP","type":"CLIP","links":[64],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"Lora Loader Stack (rgthree)"},"widgets_values":["stefan_flux_with_trigger_v1_000003000.safetensors",1,"None",1,"None",1,"None",1],"color":"#223","bgcolor":"#335","shape":1},{"id":16,"type":"KSamplerSelect","pos":{"0":390,"1":340},"size":{"0":315,"1":58},"flags":{"pinned":false},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[19],"shape":3}],"properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"],"color":"#223","bgcolor":"#335","shape":1},{"id":17,"type":"BasicScheduler","pos":{"0":390,"1":450},"size":{"0":315,"1":106},"flags":{"pinned":false},"order":7,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":38,"slot_index":0}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[20],"shape":3}],"properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["simple",30,1],"color":"#223","bgcolor":"#335","shape":1}],"links":[[12,10,0,8,1,"VAE"],[19,16,0,13,2,"SAMPLER"],[20,17,0,13,3,"SIGMAS"],[24,13,0,8,0,"LATENT"],[30,22,0,13,1,"GUIDER"],[37,25,0,13,0,"NOISE"],[38,12,0,17,0,"MODEL"],[42,6,0,27,0,"CONDITIONING"],[43,27,0,22,1,"CONDITIONING"],[60,8,0,33,0,"IMAGE"],[61,12,0,34,0,"MODEL"],[62,11,0,34,1,"CLIP"],[63,34,0,22,0,"MODEL"],[64,34,1,6,0,"CLIP"],[68,26,0,13,4,"LATENT"]],"groups":[{"title":"","bounding":[16,582,693,326],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[475.9915335743806,87.57056913858221]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
You have selected the SDXL VAE instead of the Flux VAE.

**Comment by Shengmaqingkuang** [comment]
Given groups=1, weight of size [4, 4, 1, 1], expected input[1, 16, 152, 104] to have 4 channels, but got 16 channels instead

**Comment by lovk4ch** [comment]
I also had same error in Wan 2.2, but it worked good when I changed VAE model to Wan 2.1 - as I see, they have different types of tensors.

**Comment by Azhou51** [comment]
Simple. The VAE file was not selected correctly
