### ISSUE TITLE
 LayerMask: YoloV8Detect name 'NODE_NAME' is not defined

### ISSUE THREAD

**Issue by Auroralr** [comfyanonymous/ComfyUI#4910]
### Your question

![屏幕截图 2024-09-13 231428](https://github.com/user-attachments/assets/28809ffd-cdfb-4c58-9a10-93690b7b6e69)
# ComfyUI Error Report
## Error Details
- **Node Type:** LayerMask: YoloV8Detect
- **Exception Type:** NameError
- **Exception Message:** name 'NODE_NAME' is not defined
## Stack Trace
```
  File "C:\Aiart\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\Aiart\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\Aiart\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Aiart\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\Aiart\ComfyUI\custom_nodes\ComfyUI_LayerStyle\py\yolov8_detect.py", line 74, in yolo_detect
    log(f"{NODE_NAME} mask or box not detected.")
![image](https://github.com/user-attachments/assets/49939fb4-c814-491f-a89a-5ddfc34e2e22)


### Logs

_No response_

### Other

ComfyUI\models\yolo have yolov8m-face.pt

**Comment by Amorano** [comment]
![image](https://github.com/user-attachments/assets/9c16c80b-975d-4644-b5a6-ef058c43f55a)

This isnt a ComfyUI problem?

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI_LayerStyle.
https://github.com/chflame163/ComfyUI_LayerStyle

**Comment by Jams63** [comment]
whats the fix , even v2 also shows the same bug. "  LayerColor: ColorofShadowHighlightV2
name 'NODE_NAME' is not defined ".



# ComfyUI Error Report
## Error Details
- **Node Type:** LayerColor: ColorofShadowHighlightV2
- **Exception Type:** NameError
- **Exception Message:** name 'NODE_NAME' is not defined
## Stack Trace
```
  File "E:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "E:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_LayerStyle-main\py\color_correct_shadow_and_highlight.py", line 231, in color_shadow_and_highlight_v2
    log(f"{NODE_NAME} Processed {len(ret_images)} image(s).", message_type='finish')

```
## System Information
- **ComfyUI Version:** v0.2.4-10-g5cbb01b
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 11810832384
  - **VRAM Free:** 6910249012
  - **Torch VRAM Total:** 3657433088
  - **Torch VRAM Free:** 32639028

## Logs
```
2024-11-01 10:40:41,298 - root - INFO - Total VRAM 11264 MB, total RAM 65449 MB
2024-11-01 10:40:41,298 - root - INFO - pytorch version: 2.4.1+cu121
2024-11-01 10:40:41,306 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-01 10:40:41,307 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
2024-11-01 10:40:42,175 - root - INFO - Using pytorch cross attention
2024-11-01 10:40:43,255 - root - INFO - [Prompt Server] web root: E:\pinokio\api\comfy.git\app\web
2024-11-01 10:40:46,027 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-01 10:40:46,041 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-11-01 10:40:46,044 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-01 10:40:47,146 - root - INFO - Total VRAM 11264 MB, total RAM 65449 MB
2024-11-01 10:40:47,147 - root - INFO - pytorch version: 2.4.1+cu121
2024-11-01 10:40:47,149 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-01 10:40:47,149 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
2024-11-01 10:40:50,821 - root - INFO - --------------
2024-11-01 10:40:50,821 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-01 10:40:50,832 - root - INFO - ChatGPT.available True
2024-11-01 10:40:50,832 - root - INFO - edit_mask.available True
2024-11-01 10:40:51,006 - root - INFO - ClipInterrogator.available True
2024-11-01 10:40:51,144 - root - INFO - PromptGenerate.available True
2024-11-01 10:40:51,144 - root - INFO - ChinesePrompt.available True
2024-11-01 10:40:51,144 - root - INFO - RembgNode_.available True
2024-11-01 10:40:51,641 - root - INFO - TripoSR.available
2024-11-01 10:40:51,642 - root - INFO - MiniCPMNode.available
2024-11-01 10:40:51,676 - root - INFO - Scenedetect.available
2024-11-01 10:40:51,772 - root - INFO - FishSpeech.available
2024-11-01 10:40:51,780 - root - INFO - SenseVoice.available
2024-11-01 10:40:51,801 - root - INFO - Whisper.available False
2024-11-01 10:40:51,813 - root - INFO - FalVideo.available
2024-11-01 10:40:51,818 - root - INFO - [93m -------------- [0m
2024-11-01 10:40:55,409 - root - INFO - 
Import times for custom nodes:
2024-11-01 10:40:55,410 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\websocket_image_save.py
2024-11-01 10:40:55,410 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\sdxl_prompt_styler
2024-11-01 10:40:55,410 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_SUNoise
2024-11-01 10:40:55,410 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-IC-Light-Native
2024-11-01 10:40:55,411 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-mxToolkit
2024-11-01 10:40:55,411 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-BRIA_AI-RMBG
2024-11-01 10:40:55,411 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\cg-use-everywhere
2024-11-01 10:40:55,412 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\sigmas_tools_and_the_golden_scheduler
2024-11-01 10:40:55,412 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUi-Ollama-YN
2024-11-01 10:40:55,412 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-ResAdapter
2024-11-01 10:40:55,412 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Eagle-PNGInfo
2024-11-01 10:40:55,413 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-01 10:40:55,413 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\sd-perturbed-attention
2024-11-01 10:40:55,413 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyUI_FrequencySeparation_RGB-HSV
2024-11-01 10:40:55,413 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-01 10:40:55,413 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-enricos-nodes
2024-11-01 10:40:55,414 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-lama-remover
2024-11-01 10:40:55,414 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-AutomaticCFG
2024-11-01 10:40:55,414 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-eesahesNodes
2024-11-01 10:40:55,414 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyLiterals
2024-11-01 10:40:55,414 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui_controlnet_aux
2024-11-01 10:40:55,415 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-TiledDiffusion
2024-11-01 10:40:55,415 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-layerdiffuse
2024-11-01 10:40:55,415 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\hd_node
2024-11-01 10:40:55,415 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-tooling-nodes
2024-11-01 10:40:55,416 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfy-image-saver
2024-11-01 10:40:55,416 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Custom-Scripts
2024-11-01 10:40:55,416 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-various
2024-11-01 10:40:55,416 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-01 10:40:55,417 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_essentials
2024-11-01 10:40:55,417 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyMath
2024-11-01 10:40:55,417 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Florence2
2024-11-01 10:40:55,417 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Impact-Pack
2024-11-01 10:40:55,418 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-01 10:40:55,418 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\x-flux-comfyui
2024-11-01 10:40:55,418 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-KJNodes
2024-11-01 10:40:55,418 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-01 10:40:55,419 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-GGUF
2024-11-01 10:40:55,419 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-LivePortraitKJ
2024-11-01 10:40:55,419 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\rgthree-comfy
2024-11-01 10:40:55,419 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders
2024-11-01 10:40:55,420 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-01 10:40:55,420 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-IC-Light-main
2024-11-01 10:40:55,420 - root - INFO -    0.0 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\CharacterFaceSwap
2024-11-01 10:40:55,420 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-SAM2
2024-11-01 10:40:55,420 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-instantId-faceswap
2024-11-01 10:40:55,420 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-reactor-node
2024-11-01 10:40:55,421 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-CogVideoXWrapper
2024-11-01 10:40:55,421 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_LayerStyle-main
2024-11-01 10:40:55,421 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui_segment_anything
2024-11-01 10:40:55,421 - root - INFO -    0.1 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_LayerStyle
2024-11-01 10:40:55,421 - root - INFO -    0.2 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Gemini
2024-11-01 10:40:55,422 - root - INFO -    0.2 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_MileHighStyler
2024-11-01 10:40:55,422 - root - INFO -    0.3 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-ollama
2024-11-01 10:40:55,422 - root - INFO -    0.3 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-SUPIR
2024-11-01 10:40:55,422 - root - INFO -    0.3 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_MaraScott_Nodes
2024-11-01 10:40:55,422 - root - INFO -    0.4 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-BrushNet-main
2024-11-01 10:40:55,423 - root - INFO -    0.4 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-01 10:40:55,423 - root - INFO -    0.4 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Crystools
2024-11-01 10:40:55,423 - root - INFO -    0.4 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Easy-Use
2024-11-01 10:40:55,423 - root - INFO -    0.5 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Manager
2024-11-01 10:40:55,423 - root - INFO -    0.5 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-BiRefNet-ZHO
2024-11-01 10:40:55,423 - root - INFO -    0.7 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-art-venture
2024-11-01 10:40:55,423 - root - INFO -    0.9 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Image-Filters
2024-11-01 10:40:55,424 - root - INFO -    1.3 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\comfyui-mixlab-nodes
2024-11-01 10:40:55,424 - root - INFO -    1.8 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-11-01 10:40:55,424 - root - INFO -    1.9 seconds: E:\pinokio\api\comfy.git\app\custom_nodes\was-node-suite-comfyui
2024-11-01 10:40:55,424 - root - INFO - 
2024-11-01 10:40:55,447 - root - INFO - Starting server

2024-11-01 10:40:55,448 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-01 10:41:16,169 - root - INFO - got prompt
2024-11-01 10:41:16,182 - root - ERROR - Failed to validate prompt for output 65:
2024-11-01 10:41:16,183 - root - ERROR - * (prompt):
2024-11-01 10:41:16,183 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,183 - root - ERROR - * PreviewImage 65:
2024-11-01 10:41:16,183 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,184 - root - ERROR - Output will be ignored
2024-11-01 10:41:16,186 - root - ERROR - Failed to validate prompt for output 71:
2024-11-01 10:41:16,186 - root - ERROR - * (prompt):
2024-11-01 10:41:16,187 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,187 - root - ERROR - * PreviewImage 71:
2024-11-01 10:41:16,187 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,187 - root - ERROR - Output will be ignored
2024-11-01 10:41:16,188 - root - ERROR - Failed to validate prompt for output 69:
2024-11-01 10:41:16,188 - root - ERROR - * (prompt):
2024-11-01 10:41:16,188 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,189 - root - ERROR - * PreviewImage 69:
2024-11-01 10:41:16,189 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,189 - root - ERROR - Output will be ignored
2024-11-01 10:41:16,189 - root - ERROR - Failed to validate prompt for output 73:
2024-11-01 10:41:16,189 - root - ERROR - * (prompt):
2024-11-01 10:41:16,190 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,190 - root - ERROR - * PreviewImage 73:
2024-11-01 10:41:16,190 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,190 - root - ERROR - Output will be ignored
2024-11-01 10:41:16,190 - root - ERROR - Failed to validate prompt for output 75:
2024-11-01 10:41:16,191 - root - ERROR - * (prompt):
2024-11-01 10:41:16,191 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,191 - root - ERROR - * PreviewImage 75:
2024-11-01 10:41:16,191 - root - ERROR -   - Required input is missing: images
2024-11-01 10:41:16,191 - root - ERROR - Output will be ignored
2024-11-01 10:41:16,338 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
2024-11-01 10:41:16,339 - root - INFO - model_type FLUX
2024-11-01 10:41:18,609 - root - INFO - Using pytorch attention in VAE
2024-11-01 10:41:18,610 - root - INFO - Using pytorch attention in VAE
2024-11-01 10:41:21,291 - comfyui_segment_anything - WARNING - using extra model: E:\pinokio\api\comfy.git\app\models\sams\sam_vit_h_4b8939.pth
2024-11-01 10:41:39,045 - root - INFO - Using pytorch attention in VAE
2024-11-01 10:41:39,046 - root - INFO - Using pytorch attention in VAE
2024-11-01 10:41:39,153 - root - INFO - Requested to load FluxClipModel_
2024-11-01 10:41:39,154 - root - INFO - Loading 1 new model
2024-11-01 10:41:40,312 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-11-01 10:41:40,912 - root - INFO - Requested to load AutoencodingEngine
2024-11-01 10:41:40,912 - root - INFO - Loading 1 new model
2024-11-01 10:41:42,739 - root - INFO - loaded completely 0.0 319.7467155456543 True
2024-11-01 10:41:43,541 - root - INFO - Unloading models for lowram load.
2024-11-01 10:41:43,612 - root - INFO - 1 models unloaded.
2024-11-01 10:41:43,612 - root - INFO - Loading 1 new model
2024-11-01 10:41:43,682 - root - INFO - loaded completely 0.0 319.7467155456543 True
2024-11-01 10:41:44,443 - root - INFO - Requested to load Flux
2024-11-01 10:41:44,443 - root - INFO - Loading 1 new model
2024-11-01 10:41:45,625 - root - INFO - loaded partially 4945.617638153077 4945.4853515625 0
2024-11-01 10:42:52,702 - root - INFO - Requested to load AutoencodingEngine
2024-11-01 10:42:52,702 - root - INFO - Loading 1 new model
2024-11-01 10:42:54,496 - root - INFO - loaded completely 0.0 319.7467155456543 True
2024-11-01 10:43:02,821 - root - ERROR - !!! Exception during processing !!! name 'NODE_NAME' is not defined
2024-11-01 10:43:02,835 - root - ERROR - Traceback (most recent call last):
  File "E:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_LayerStyle-main\py\color_correct_shadow_and_highlight.py", line 119, in color_shadow_and_highlight
    log(f"{NODE_NAME} Processed {len(ret_images)} image(s).", message_type='finish')
NameError: name 'NODE_NAME' is not defined

2024-11-01 10:43:02,838 - root - INFO - Prompt executed in 106.64 seconds
2024-11-01 10:46:04,991 - root - INFO - got prompt
2024-11-01 10:46:05,006 - root - ERROR - Failed to validate prompt for output 65:
2024-11-01 10:46:05,007 - root - ERROR - * (prompt):
2024-11-01 10:46:05,007 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,007 - root - ERROR - * PreviewImage 65:
2024-11-01 10:46:05,008 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,008 - root - ERROR - Output will be ignored
2024-11-01 10:46:05,010 - root - ERROR - Failed to validate prompt for output 71:
2024-11-01 10:46:05,011 - root - ERROR - * (prompt):
2024-11-01 10:46:05,011 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,011 - root - ERROR - * PreviewImage 71:
2024-11-01 10:46:05,011 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,012 - root - ERROR - Output will be ignored
2024-11-01 10:46:05,012 - root - ERROR - Failed to validate prompt for output 69:
2024-11-01 10:46:05,012 - root - ERROR - * (prompt):
2024-11-01 10:46:05,012 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,013 - root - ERROR - * PreviewImage 69:
2024-11-01 10:46:05,013 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,013 - root - ERROR - Output will be ignored
2024-11-01 10:46:05,013 - root - ERROR - Failed to validate prompt for output 73:
2024-11-01 10:46:05,014 - root - ERROR - * (prompt):
2024-11-01 10:46:05,014 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,014 - root - ERROR - * PreviewImage 73:
2024-11-01 10:46:05,014 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,014 - root - ERROR - Output will be ignored
2024-11-01 10:46:05,015 - root - ERROR - Failed to validate prompt for output 75:
2024-11-01 10:46:05,015 - root - ERROR - * (prompt):
2024-11-01 10:46:05,015 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,015 - root - ERROR - * PreviewImage 75:
2024-11-01 10:46:05,015 - root - ERROR -   - Required input is missing: images
2024-11-01 10:46:05,016 - root - ERROR - Output will be ignored
2024-11-01 10:46:07,274 - root - ERROR - !!! Exception during processing !!! name 'NODE_NAME' is not defined
2024-11-01 10:46:07,281 - root - ERROR - Traceback (most recent call last):
  File "E:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_LayerStyle-main\py\color_correct_shadow_and_highlight.py", line 231, in color_shadow_and_highlight_v2
    log(f"{NODE_NAME} Processed {len(ret_images)} image(s).", message_type='finish')
NameError: name 'NODE_NAME' is not defined

2024-11-01 10:46:07,283 - root - INFO - Prompt executed in 2.26 seconds
2024-11-01 10:47:02,558 - root - INFO - got prompt
2024-11-01 10:47:02,571 - root - ERROR - Failed to validate prompt for output 65:
2024-11-01 10:47:02,571 - root - ERROR - * (prompt):
2024-11-01 10:47:02,571 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,572 - root - ERROR - * PreviewImage 65:
2024-11-01 10:47:02,572 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,572 - root - ERROR - Output will be ignored
2024-11-01 10:47:02,575 - root - ERROR - Failed to validate prompt for output 71:
2024-11-01 10:47:02,575 - root - ERROR - * (prompt):
2024-11-01 10:47:02,575 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,576 - root - ERROR - * PreviewImage 71:
2024-11-01 10:47:02,576 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,576 - root - ERROR - Output will be ignored
2024-11-01 10:47:02,577 - root - ERROR - Failed to validate prompt for output 69:
2024-11-01 10:47:02,577 - root - ERROR - * (prompt):
2024-11-01 10:47:02,577 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,577 - root - ERROR - * PreviewImage 69:
2024-11-01 10:47:02,577 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,578 - root - ERROR - Output will be ignored
2024-11-01 10:47:02,578 - root - ERROR - Failed to validate prompt for output 73:
2024-11-01 10:47:02,578 - root - ERROR - * (prompt):
2024-11-01 10:47:02,578 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,578 - root - ERROR - * PreviewImage 73:
2024-11-01 10:47:02,579 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,579 - root - ERROR - Output will be ignored
2024-11-01 10:47:02,579 - root - ERROR - Failed to validate prompt for output 75:
2024-11-01 10:47:02,579 - root - ERROR - * (prompt):
2024-11-01 10:47:02,580 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,580 - root - ERROR - * PreviewImage 75:
2024-11-01 10:47:02,580 - root - ERROR -   - Required input is missing: images
2024-11-01 10:47:02,580 - root - ERROR - Output will be ignored
2024-11-01 10:47:02,632 - root - INFO - Requested to load Flux
2024-11-01 10:47:02,632 - root - INFO - Loading 1 new model
2024-11-01 10:47:03,935 - root - INFO - loaded partially 4933.617638153077 4933.48828125 0
2024-11-01 10:48:12,437 - root - INFO - Requested to load AutoencodingEngine
2024-11-01 10:48:12,437 - root - INFO - Loading 1 new model
2024-11-01 10:48:14,254 - root - INFO - loaded completely 0.0 319.7467155456543 True
2024-11-01 10:48:21,992 - root - ERROR - !!! Exception during processing !!! name 'NODE_NAME' is not defined
2024-11-01 10:48:22,000 - root - ERROR - Traceback (most recent call last):
  File "E:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "E:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_LayerStyle-main\py\color_correct_shadow_and_highlight.py", line 231, in color_shadow_and_highlight_v2
    log(f"{NODE_NAME} Processed {len(ret_images)} image(s).", message_type='finish')
NameError: name 'NODE_NAME' is not defined

2024-11-01 10:48:22,002 - root - INFO - Prompt executed in 79.42 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
