### ISSUE TITLE
**Exception Message:** list.remove(x): x not in list

### ISSUE THREAD

**Issue by Spinaster** [comfyanonymous/ComfyUI#4913]
### Your question

Hello, after updating ComfyUI and all the dependencies I can’t run Florence 2 but also Ollama and Qwen2.
I can’t load the full logs because of an error uploading.
Thanks.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** Florence2ModelLoader
- **Exception Type:** ValueError
- **Exception Message:** list.remove(x): x not in list
## Stack Trace

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 166, in loadmodel
    model = AutoModelForCausalLM.from_pretrained(model_path, attn_implementation=attention, device_map=device, torch_dtype=dtype,trust_remote_code=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\auto_factory.py", line 547, in from_pretrained
    model_class = get_class_from_dynamic_module(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 506, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 331, in get_cached_module_file
    modules_needed = check_imports(resolved_module_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dynamic_module_utils.py", line 177, in check_imports
    imports = get_imports(filename)
              ^^^^^^^^^^^^^^^^^^^^^

  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 23, in fixed_get_imports
    imports.remove("flash_attn")

```
## System Information
- **ComfyUI Version:** v0.2.2-26-g9f4daca
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 15964569600
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-09-13 21:19:54,739 - root - INFO - Total VRAM 16380 MB, total RAM 32691 MB
2024-09-13 21:19:54,739 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-13 21:19:56,097 - root - INFO - xformers version: 0.0.27.post2
2024-09-13 21:19:56,098 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-13 21:19:56,098 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-09-13 21:19:56,339 - root - INFO - Using xformers cross attention
2024-09-13 21:19:57,380 - root - INFO - [Prompt Server] web root: E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-09-13 21:19:57,387 - root - INFO - Adding extra search path checkpoints D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/checkpoints/
2024-09-13 21:19:57,387 - root - INFO - Adding extra search path clip D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/clip/
2024-09-13 21:19:57,387 - root - INFO - Adding extra search path clip_vision D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/clip_vision/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path configs D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/configs/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path controlnet D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/controlnet/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path embeddings D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/embeddings/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path loras D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/loras/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path inpaint D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/inpaint/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path upscale_models D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/upscale_models/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path vae D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/vae/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path unet D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/unet/
2024-09-13 21:19:57,388 - root - INFO - Adding extra search path prompt_generator D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/prompt_generator/
2024-09-13 21:19:57,389 - root - INFO - Adding extra search path LLM D:/AI/2_ComfyUI_windows_portable/ComfyUI/models/LLM/
2024-09-13 21:20:26,468 - root - INFO - Total VRAM 16380 MB, total RAM 32691 MB
2024-09-13 21:20:26,468 - root - INFO - pytorch version: 2.4.0+cu121
2024-09-13 21:20:26,468 - root - INFO - xformers version: 0.0.27.post2
2024-09-13 21:20:26,468 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-13 21:20:26,468 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-09-13 21:20:27,401 - root - WARNING - Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\__init__.py", line 1, in <module>
    from . import birefnet
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\birefnet.py", line 7, in <module>
    from models.baseline import BiRefNet
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\baseline.py", line 16, in <module>
    from models.refinement.refiner import Refiner, RefinerPVTInChannels4, RefUNet
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\models\refinement\refiner.py", line 11, in <module>
    from dataset import class_labels_TR_sorted
  File "E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO\dataset.py", line 10, in <module>
    from utils import path_to_image
ImportError: cannot import name 'path_to_image' from 'utils' (E:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\utils\__init__.py)
```

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI-Florence2 repo.
https://github.com/kijai/ComfyUI-Florence2

**Comment by f91sundayf911** [comment]
我也遇到了这样的问题
