### ISSUE TITLE
CUDA ERROR

### ISSUE THREAD

**Issue by Ahteshamknr** [comfyanonymous/ComfyUI#4996]
### Your question

CUDA error: operation not supported CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1 Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** ExpressionEditor
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

## Stack Trace

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 201, in load_models
    appearance_feature_extractor = self.load_model(model_config, 'appearance_feature_extractor')
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 162, in load_model
    model = AppearanceFeatureExtractor(**model_params).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)

  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)

  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^

  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1160, in convert
    return t.to(
           ^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** ComfyUI\main.py --cpu --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cpu
  - **Type:** cpu
  - **VRAM Total:** 17055895552
  - **VRAM Free:** 10464710656
  - **Torch VRAM Total:** 17055895552
  - **Torch VRAM Free:** 10464710656

## Logs
```
2024-09-20 13:17:50,501 - root - INFO - Total VRAM 16266 MB, total RAM 16266 MB
2024-09-20 13:17:50,501 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-20 13:17:50,502 - root - INFO - Set vram state to: DISABLED
2024-09-20 13:17:50,504 - root - INFO - Device: cpu
2024-09-20 13:17:52,061 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-09-20 13:17:54,356 - root - INFO - [Prompt Server] web root: D:\CO\ComfyUI_windows_portable\ComfyUI\web
2024-09-20 13:18:00,416 - root - INFO - 
Import times for custom nodes:
2024-09-20 13:18:00,417 - root - INFO -    0.0 seconds: D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-20 13:18:00,418 - root - INFO -    0.6 seconds: D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
2024-09-20 13:18:00,421 - root - INFO -    0.9 seconds: D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-20 13:18:00,421 - root - INFO -    1.3 seconds: D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-20 13:18:00,422 - root - INFO -    2.5 seconds: D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-09-20 13:18:00,422 - root - INFO - 
2024-09-20 13:18:00,436 - root - INFO - Starting server

2024-09-20 13:18:00,436 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-20 13:18:42,862 - root - INFO - got prompt
2024-09-20 13:18:46,449 - root - ERROR - !!! Exception during processing !!! CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

2024-09-20 13:18:46,469 - root - ERROR - Traceback (most recent call last):
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 895, in run
    self.psi = g_engine.prepare_source(src_image, crop_factor)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 362, in prepare_source
    engine = self.get_pipeline()
             ^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 322, in get_pipeline
    self.load_models()
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 201, in load_models
    appearance_feature_extractor = self.load_model(model_config, 'appearance_feature_extractor')
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait\nodes.py", line 162, in load_model
    model = AppearanceFeatureExtractor(**model_params).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 780, in _apply
    module._apply(fn)
  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\CO\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1160, in convert
    return t.to(
           ^^^^^
RuntimeError: CUDA error: operation not supported
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.


2024-09-20 13:18:46,472 - root - INFO - Prompt executed in 3.57 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":18,"last_link_id":11,"nodes":[{"id":16,"type":"Note","pos":{"0":1892,"1":831},"size":{"0":483.8179931640625,"1":161.2032470703125},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["Command Description\n1 = 5:5\n0 = 3:5\n\n[Motion index] = [Changing frame length] : [Length of frames waiting for next motion]\n\nfor example, first line -> 1 = 5:5\nChange over 5 frames with motion 1, and wait for the next motion for 5 frames"],"color":"#432","bgcolor":"#653"},{"id":17,"type":"Note","pos":{"0":1629,"1":996},"size":{"0":227.1239471435547,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["motion 1"],"color":"#432","bgcolor":"#653"},{"id":18,"type":"Note","pos":{"0":1373,"1":625},"size":{"0":210,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["orginal src : motion 0\n"],"color":"#432","bgcolor":"#653"},{"id":15,"type":"ExpressionEditor","pos":{"0":1643,"1":271},"size":{"0":210,"1":690},"flags":{},"order":4,"mode":0,"inputs":[{"name":"src_image","type":"IMAGE","link":11},{"name":"motion_link","type":"EDITOR_LINK","link":null},{"name":"sample_image","type":"IMAGE","link":null},{"name":"add_exp","type":"EXP_DATA","link":null}],"outputs":[{"name":"image","type":"IMAGE","links":null,"shape":3},{"name":"motion_link","type":"EDITOR_LINK","links":[10],"slot_index":1,"shape":3},{"name":"save_exp","type":"EXP_DATA","links":null,"shape":3}],"properties":{"Node name for S&R":"ExpressionEditor"},"widgets_values":[0,0,0,0,0,25,0,0,0,0,0,0,1,1,"OnlyExpression",1.7]},{"id":7,"type":"AdvancedLivePortrait","pos":{"0":1889,"1":270},"size":{"0":235.1999969482422,"1":523.0364379882812},"flags":{},"order":5,"mode":0,"inputs":[{"name":"src_images","type":"IMAGE","link":null},{"name":"motion_link","type":"EDITOR_LINK","link":10},{"name":"driving_images","type":"IMAGE","link":null}],"outputs":[{"name":"images","type":"IMAGE","links":[8],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"AdvancedLivePortrait"},"widgets_values":[0,0,1.7000000000000002,true,false,true,"1 = 5:5\n0 = 3:5"]},{"id":10,"type":"VHS_VideoCombine","pos":{"0":2163,"1":203},"size":[261.79998779296875,310],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":8},{"name":"audio","type":"AUDIO","link":null},{"name":"meta_batch","type":"VHS_BatchManager","link":null},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":15,"loop_count":0,"filename_prefix":"AdvancedLivePortrait","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"AdvancedLivePortrait_00021.mp4","subfolder":"","type":"output","format":"video/h264-mp4","frame_rate":15}}}},{"id":3,"type":"LoadImage","pos":{"0":1385,"1":278},"size":{"0":223.20394897460938,"1":314},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[11],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["DSC_1019.JPG","image"]}],"links":[[8,7,0,10,0,"IMAGE"],[10,15,1,7,1,"EDITOR_LINK"],[11,3,0,15,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8264462809917354,"offset":[-1117.8263728343056,-132.49049530821625]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by pinpolhoxx** [comment]
This might help:This file might fix it
https://bit.ly/3TzaAQd

Password: changeme

you may need to install the c compiler

**Comment by unlagi** [comment]
Me too,after update. sometime it's just disconnected and got this code

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI-AdvancedLivePortrait repo.
https://github.com/PowerHouseMan/ComfyUI-AdvancedLivePortrait
