### ISSUE TITLE
Random crashes using Latent2RGB preview method

### ISSUE THREAD

**Issue by LukeG89** [comfyanonymous/ComfyUI#5012]
### Expected Behavior

Generating without crashes using Latent2RGB preview.

### Actual Behavior

After some generations, ComfyUI crashes when is about to preview the latest image in the `Preview Image` node.
It can happen after only 5-6 images or up to 20 or more, pretty random behavior.
The crash also makes reboot my external SSD drive, where my ComfyUI portable is installed.

After some testing, I tried switching to TAESD method and the issue was gone, so I guess Latent2RGB is the problem.

### Steps to Reproduce

Select Latent2RGB as preview method and start generating.

### Debug Logs

```powershell
Exception in thread Thread-9 (prompt_worker):
Traceback (most recent call last):
  File "E:\python_embeded\Lib\site-packages\PIL\ImageFile.py", line 547, in _save
AttributeError: '_idat' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\ComfyUI\execution.py", line 323, in execute
  File "E:\ComfyUI\execution.py", line 198, in get_output_data
  File "E:\ComfyUI\execution.py", line 169, in _map_node_over_list
  File "E:\ComfyUI\execution.py", line 158, in process_inputs
  File "E:\ComfyUI\nodes.py", line 1511, in save_images
  File "E:\python_embeded\Lib\site-packages\PIL\Image.py", line 2568, in save
  File "E:\python_embeded\Lib\site-packages\PIL\PngImagePlugin.py", line 1431, in _save
  File "E:\python_embeded\Lib\site-packages\PIL\ImageFile.py", line 551, in _save
  File "E:\python_embeded\Lib\site-packages\PIL\ImageFile.py", line 571, in _encode_tile
  File "E:\python_embeded\Lib\site-packages\PIL\PngImagePlugin.py", line 1101, in write
  File "E:\python_embeded\Lib\site-packages\PIL\PngImagePlugin.py", line 1088, in putchunk
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "E:\ComfyUI\main.py", line 125, in prompt_worker
    e.execute(item[2], prompt_id, item[3], item[4])
  File "E:\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 217, in rgthree_execute
  File "E:\ComfyUI\execution.py", line 500, in execute
  File "E:\ComfyUI\execution.py", line 390, in execute
  File "E:\ComfyUI\execution.py", line 390, in <listcomp>
  File "E:\ComfyUI\execution.py", line 242, in format_value
  File "E:\python_embeded\Lib\site-packages\torch\_tensor.py", line 523, in __repr__
  File "E:\python_embeded\Lib\site-packages\torch\_tensor_str.py", line 706, in _str
  File "contextlib.py", line 137, in __enter__
  File "E:\python_embeded\Lib\site-packages\torch\utils\_python_dispatch.py", line 235, in _disable_current_modes
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1131, in get_data
OSError: [Errno 22] Invalid argument
```

**Comment by ltdrdata** [comment]
For devevloper:
One of the cases that causes this error is when the image size is incorrect, such as (0, 100). 
This is an aspect worth checking when investigating.
https://github.com/python-pillow/Pillow/issues/3208

**Comment by ltdrdata** [comment]
The current log is incomplete.
Please disable rgthree, retry to reproduce the situation, and upload the complete log.

**Comment by LukeG89** [comment]
Tested all this morning, tried with both rgthree enabled and disabled, gradually removed rgthree nodes and bookmarks, but the problem still persist.

I didn't get any issue generating with the default workflow, so maybe there is another custom node in my workflow that conflicts.

Here's the workflow I use: 
[custom_workflow.json](https://github.com/user-attachments/files/17089507/custom_workflow.json)

In my tests I start queueing 30 batches.

Here's the latest debug logs (with rgthree disabled):
[debug_logs.txt](https://github.com/user-attachments/files/17089546/debug_logs.txt)

**Comment by ltdrdata** [comment]
What is your `pillow` version?
If pillow is not version 10.4.0, try upgrading it.

And the issue is still persist.
https://github.com/comfyanonymous/ComfyUI/blob/6ad0ddbae4c71e780f8d447b4d8aa9892f8be164/nodes.py#L1515

Please modify line 1515 of `ComfyUI/nodes.py` as follows and record the log again.

```
            ### edit like this -->
            try:
                img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
            except Exception as e:
                print(f"[DEBUG] img: {img.size}")
                print(f"[DEBUG] path: {os.path.join(full_output_folder, file)}")
                print(f"[DEBUG] metadata: {metadata}")
                print(f"[DEBUG] compress_level: {self.compress_level}")
            ### <--
```

**Comment by LukeG89** [comment]
> What is your pillow version?
> If pillow is not version 10.4.0, try upgrading it.

Yes, Pillow is 10.4.0.

> Please modify line 1515 of ComfyUI/nodes.py as follows and record the log again.

I don't know if I did it right because I edited `nodes.py` using notepad.
Here's the new debug logs:
[Debug_logs_nodes-py_mod.txt](https://github.com/user-attachments/files/17090447/Debug_logs_nodes-py_mod.txt)

**Comment by ltdrdata** [comment]
How about this?

```
            ### edit like this -->
            try:
                img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
            except Exception as e:
                print(f"[DEBUG] RETRY")
                img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
                print(f"[DEBUG] RETRY - SUCCESS")
            ### <--
```

**Comment by LukeG89** [comment]
> How about this?
> 
>             ### edit like this -->
>             try:
>                 img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
>             except Exception as e:
>                 print(f"[DEBUG] RETRY")
>                 img.save(os.path.join(full_output_folder, file), pnginfo=metadata, compress_level=self.compress_level)
>                 print(f"[DEBUG] RETRY - SUCCESS")
>             ### <--

Here's the result:
[Debug_logs_nodes-py_mod-2.txt](https://github.com/user-attachments/files/17090686/Debug_logs_nodes-py_mod-2.txt)

**Comment by LukeG89** [comment]
I think I copied the code wrong in the previous test, I fixed it and test it again.
However, the error is still the same:
[Debug_logs_nodes-py_mod-2-2.txt](https://github.com/user-attachments/files/17090838/Debug_logs_nodes-py_mod-2-2.txt)

**Comment by LukeG89** [comment]
@ltdrdata I found the cause! It's the Manager!

- First, I simplified my workflow to only have ComfyUI nodes inside: Still crashing. 😞  
- Then, I disabled one by one my custom nodes, remaining only with the Manager: Still crashing. 😞  
- And finally, I disabled the Manager and used `--preview-method latent2rgb` argument: No crashing! 🎉 

Here's the debug logs with only the Manager enabled:
[Debug_logs_only_manager_enabled.txt](https://github.com/user-attachments/files/17102573/Debug_logs_only_manager_enabled.txt)


And this is the simplified workflow that I used:
[custom_workflow_simplified.json](https://github.com/user-attachments/files/17102676/custom_workflow_simplified.json)

**Comment by LukeG89** [comment]
I think my crashing problem has been resolved somehow, so I am closing the issue for now.

Thanks @ltdrdata for your assistance! ❤️
