### ISSUE TITLE
CatVTONWrapper - Torch not compiled with CUDA enabled on Mac mini M2 Pro 32GB

### ISSUE THREAD

**Issue by Basementbluesboy** [comfyanonymous/ComfyUI#5014]
### Your question

Hi there,
I am running ComfyUI on a Mac mini M2 Pro with 32GB of shared RAM. I am fairly new to comfyui, but from what I read is that CUDA is an accelerator for Nvidia so it does not work for Mac. I switched the LayerMask: SegmentAnythingUltraV2 to CPU instead of CUDA, but still it does not work. It always tries to use CUDA and generates the attached error. Se protocol below. Does anybody know what I have to change to work the basic CatVTON workflow work.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** CatVTONWrapper
- **Exception Type:** AssertionError
- **Exception Message:** Torch not compiled with CUDA enabled
## Stack Trace

  File "/Users/Stefan/AI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/Users/Stefan/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/py/cat_vton.py", line 42, in catvton
    pipeline = CatVTONPipeline(
               ^^^^^^^^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/py/catvton/pipeline.py", line 42, in __init__
    self.vae = AutoencoderKL.from_pretrained(os.path.join(folder_paths.models_dir, "CatVTON", "sd-vae-ft-mse")).to(device, dtype=weight_dtype)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)

  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)

  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^

  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
           ^^^^^

  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")

```
## System Information
- **ComfyUI Version:** v0.2.2-58-g38c6908
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.12.6 (main, Sep  6 2024, 19:03:47) [Clang 15.0.0 (clang-1500.3.9.4)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1
## Devices

- **Name:** mps
  - **Type:** mps
  - **VRAM Total:** 34359738368
  - **VRAM Free:** 12284624896
  - **Torch VRAM Total:** 34359738368
  - **Torch VRAM Free:** 12284624896

## Logs
```
2024-09-21 21:47:05,047 - root - INFO - Total VRAM 32768 MB, total RAM 32768 MB
2024-09-21 21:47:05,047 - root - INFO - pytorch version: 2.4.1
2024-09-21 21:47:05,047 - root - INFO - Set vram state to: SHARED
2024-09-21 21:47:05,048 - root - INFO - Device: mps
2024-09-21 21:47:05,422 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-09-21 21:47:05,922 - root - INFO - [Prompt Server] web root: /Users/Stefan/AI/ComfyUI/web
2024-09-21 21:47:07,328 - root - INFO - 
Import times for custom nodes:
2024-09-21 21:47:07,328 - root - INFO -    0.0 seconds: /Users/Stefan/AI/ComfyUI/custom_nodes/websocket_image_save.py
2024-09-21 21:47:07,328 - root - INFO -    0.0 seconds: /Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
2024-09-21 21:47:07,328 - root - INFO -    0.1 seconds: /Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper
2024-09-21 21:47:07,328 - root - INFO -    0.1 seconds: /Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI-Manager
2024-09-21 21:47:07,328 - root - INFO -    0.2 seconds: /Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-09-21 21:47:07,328 - root - INFO -    0.9 seconds: /Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI_LayerStyle
2024-09-21 21:47:07,328 - root - INFO - 
2024-09-21 21:47:07,331 - root - INFO - Starting server

2024-09-21 21:47:07,331 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-21 21:47:56,820 - root - INFO - got prompt
2024-09-21 21:48:07,981 - root - ERROR - !!! Exception during processing !!! Torch not compiled with CUDA enabled
2024-09-21 21:48:07,983 - root - ERROR - Traceback (most recent call last):
  File "/Users/Stefan/AI/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/Stefan/AI/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/py/cat_vton.py", line 42, in catvton
    pipeline = CatVTONPipeline(
               ^^^^^^^^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/custom_nodes/ComfyUI_CatVTON_Wrapper/py/catvton/pipeline.py", line 42, in __init__
    self.vae = AutoencoderKL.from_pretrained(os.path.join(folder_paths.models_dir, "CatVTON", "sd-vae-ft-mse")).to(device, dtype=weight_dtype)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1174, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 780, in _apply
    module._apply(fn)
  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 805, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1160, in convert
    return t.to(
           ^^^^^
  File "/Users/Stefan/AI/ComfyUI/venv/lib/python3.12/site-packages/torch/cuda/__init__.py", line 305, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

2024-09-21 21:48:07,984 - root - INFO - Prompt executed in 11.16 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":6,"last_link_id":6,"nodes":[{"id":4,"type":"LayerMask: MaskPreview","pos":{"0":903,"1":444},"size":{"0":277.20001220703125,"1":246},"flags":{},"order":3,"mode":0,"inputs":[{"name":"mask","type":"MASK","link":2}],"outputs":[],"properties":{"Node name for S&R":"LayerMask: MaskPreview"},"color":"rgba(27, 80, 119, 0.7)"},{"id":6,"type":"PreviewImage","pos":{"0":1273,"1":33},"size":{"0":323.8887023925781,"1":455.15203857421875},"flags":{},"order":5,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":6}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"}},{"id":1,"type":"LoadImage","pos":{"0":45,"1":28},"size":{"0":309.2167053222656,"1":333.2966613769531},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1,5],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["F-4.png","image"]},{"id":2,"type":"LoadImage","pos":{"0":45,"1":423},"size":{"0":308.3948059082031,"1":348.0320739746094},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[4],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["Cloth-4.jpeg","image"]},{"id":3,"type":"LayerMask: SegmentAnythingUltra V2","pos":{"0":414,"1":424},"size":{"0":428.4000244140625,"1":342},"flags":{},"order":2,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1}],"outputs":[{"name":"image","type":"IMAGE","links":null,"shape":3},{"name":"mask","type":"MASK","links":[2,3],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"LayerMask: SegmentAnythingUltra V2"},"widgets_values":["sam_vit_h (2.56GB)","GroundingDINO_SwinT_OGC (694MB)",0.3,"VITMatte",6,6,0.01,0.99,false,"shirt, pants,","cpu",2],"color":"rgba(27, 80, 119, 0.7)"},{"id":5,"type":"CatVTONWrapper","pos":{"0":901,"1":32},"size":{"0":315,"1":218},"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":5},{"name":"mask","type":"MASK","link":3},{"name":"refer_image","type":"IMAGE","link":4}],"outputs":[{"name":"image","type":"IMAGE","links":[6],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CatVTONWrapper"},"widgets_values":[25,"fp16",487622387700327,"randomize",40,2.5]}],"links":[[1,1,0,3,0,"IMAGE"],[2,3,1,4,0,"MASK"],[3,3,1,5,1,"MASK"],[4,2,0,5,2,"IMAGE"],[5,1,0,5,0,"IMAGE"],[6,5,0,6,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6303940863128487,"offset":[323.2067561922929,234.68752712037428]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
Remove your torch and related packages.

And follow these installation instructions:
https://github.com/comfyanonymous/ComfyUI#apple-mac-silicon
