### ISSUE TITLE
CLIP Text Encode (Prompt)  not showing up when added. 

### ISSUE THREAD

**Issue by kwang0429** [comfyanonymous/ComfyUI#5041]
### Expected Behavior

CLIP Text Encode (Prompt)  can no longer be added and previous workflow that has CLIP Text Encode (Prompt)  has been missing ? 

### Actual Behavior

CLIP Text Encode (Prompt)  shows up properly

### Steps to Reproduce

after upgrading to the latest comfyui, 

### Debug Logs

```powershell
I:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-23 18:49:09.751969
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: I:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: I:\ComfyUI_windows_portable\ComfyUI
** Log path: I:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   2.6 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 262039 MB
pytorch version: 2.2.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: I:\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints D:\A1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs D:\A1111\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae D:\A1111\stable-diffusion-webui\models/VAE
Adding extra search path loras D:\A1111\stable-diffusion-webui\models/Lora
Adding extra search path loras D:\A1111\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models D:\A1111\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings D:\A1111\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks D:\A1111\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet D:\A1111\stable-diffusion-webui\models/ControlNet
Error:
[WinError 1314] A required privilege is not held by the client: 'I:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyLiterals\\js' -> 'I:\\ComfyUI_windows_portable\\ComfyUI\\web\\extensions\\ComfyLiterals'
Failed to create symlink to I:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals\js
Target: I:\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Adding I:\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.6.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V7.6.2)
Loaded ImpactPack nodes from I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools INFO] Crystools version: 1.18.2
[Crystools INFO] CPU: AMD Ryzen Threadripper 3970X 32-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4090
[Crystools INFO] NVIDIA Driver: 560.81
documents.core.js found at I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Documents\web\js\documents.core.js
[ComfyUI-Easy-Use] server: v1.2.3 Loaded
[ComfyUI-Easy-Use] web root: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
!!!Hallo path was added to I:\ComfyUI_windows_portable\python_embeded\Lib\site-packages/Hallo.pth
 if meet No module named 'hallo' error,please restart comfyui
Hallo use cache models,make sure your 'pretrained_models' complete
Traceback (most recent call last):
  File "I:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\__init__.py", line 33, in <module>
    from .nodes import PreViewVideo,HalloNode,LoadImagePath, LoadAudioPath
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\nodes.py", line 6, in <module>
    from Hallo.scripts.inference import inference_process
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 40, in <module>
    from hallo.datasets.audio_processor import AudioProcessor
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\hallo\datasets\audio_processor.py", line 14, in <module>
    from audio_separator.separator import Separator
ModuleNotFoundError: No module named 'audio_separator'

Cannot import I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo module for custom nodes: No module named 'audio_separator'
Total VRAM 24564 MB, total RAM 262039 MB
pytorch version: 2.2.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V7.6.2)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.2.2)
### Loading: ComfyUI-Manager (V2.51.1)
### ComfyUI Revision: 2724 [3a0eeee3] | Released on '2024-09-23'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
json_repair## OK
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
--------------
 ### Mixlab Nodes: Loaded
ChatGPT.available True
edit_mask.available True
simple_lama_inpainting## OK
## lama torchscript model not found: I:\ComfyUI_windows_portable\ComfyUI\models\lama\big-lama.pt,pls download from https://github.com/enesmsahin/simple-lama-inpainting/releases/download/v0.1.0/big-lama.pt
LaMaInpainting.available True
## clip_interrogator_model not found: I:\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: I:\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: I:\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available False
 --------------
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.2.2+cu121
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
ColorMod: Ignoring node 'CV2TonemapDurand' due to cv2 edition/version
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
### [START] ComfyUI AlekPet Nodes v1.0.29 ###
Node -> ArgosTranslateNode: ArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode [Loading]
Node -> DeepTranslatorNode: DeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode [Loading] Node -> GoogleTranslateNode: GoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode [Loading]

Node -> PoseNode: PoseNode [Loading]
Node -> ExtrasNode: PreviewTextNode, HexToHueNode, ColorsCorrectNode [Loading]
Node -> IDENode: IDENode [Loading]
Node -> PainterNode: PainterNode [Loading]
### [END] ComfyUI AlekPet Nodes ###
FizzleDorf Custom Nodes: Loaded
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
Traceback (most recent call last):
  File "I:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StableAudio_Open\__init__.py", line 5, in <module>
    from .StableAudio_Open_Node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StableAudio_Open\StableAudio_Open_Node.py", line 4, in <module>
    from stable_audio_tools import get_pretrained_model, create_model_from_config
ModuleNotFoundError: No module named 'stable_audio_tools'

Cannot import I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StableAudio_Open module for custom nodes: No module named 'stable_audio_tools'
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 86 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.

[rgthree] Loaded 42 epic nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Every artist was first an amateur." - Ralph Waldo Emerson

Traceback (most recent call last):
  File "I:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui-main\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui-main\nodes.py", line 12, in <module>
    from .xflux.src.flux.util import (configs, load_ae, load_clip,
ImportError: cannot import name 'configs' from 'x-flux-comfyui-main.xflux.src.flux.util' (I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui-main\xflux\src\flux\util.py)

Cannot import I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui-main module for custom nodes: cannot import name 'configs' from 'x-flux-comfyui-main.xflux.src.flux.util' (I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui-main\xflux\src\flux\util.py)

Import times for custom nodes:
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rembg-comfyui-node
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\image-resize-comfyui
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_SimpleMath
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-floodgate
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere-main
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_PRNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Prompt-Preview
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds (IMPORT FAILED): I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui-main
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_StableAudio_Open
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tooling-nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Text_Image-Composite
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-plasma
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ColorMod
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\hd_node
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NegiTools
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\IC-Light-ComfyUI-Node
   0.0 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds (IMPORT FAILED): I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Documents
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.1 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.2 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\eden_comfy_pipelines
   0.4 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   0.6 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.6 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.6 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.6 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.8 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   1.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   1.7 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   1.8 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   2.3 seconds: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
QualityOfLifeSuit_Omar92::NSP ready
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
[comfy_mtb] | INFO -> Found multiple match, we will pick the last D:\A1111\stable-diffusion-webui\models/SwinIR
['I:\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'D:\\A1111\\stable-diffusion-webui\\models/ESRGAN', 'D:\\A1111\\stable-diffusion-webui\\models/RealESRGAN', 'D:\\A1111\\stable-diffusion-webui\\models/SwinIR']
[comfy_mtb] | WARNING -> Face restoration models not found.
[]
[]
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
# 😺dzNodes: LayerStyle -> Warning: I:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle\resource_dir.ini not found, default directory to be used.
[]
[]
Update ComfyUI
```

### Other

https://youtu.be/Meefw1f9EcQ

**Comment by chrish222** [comment]
I have the same issue with CLIP Text Encode (Prompt) not showing up, directly after latest update. Regardless if i pull it from a noodle-docking-point or calling it from the modal menu, it does not show up. Old workflows with CLIP Text Encode (Prompt) all show red boxes. 

A few other nodes such as Save Image dont seem to work, too.

Also updated ComfyUI Manager and most extensions, but didnt resolve the issue.

**Comment by kwang0429** [comment]
Absolutely the same issue as me. exact the same behavior.  I ended up reinstalling comfyui and replaced my model folder.

**Comment by ltdrdata** [comment]
Please disable all custom nodes and refresh the browser and test again.

**Comment by kwang0429** [comment]
For me the last plugin I installed is https://huggingface.co/stabilityai/stable-audio-open-1.0
I didn't have CG-Use_everywhere installed.

**Comment by jpoll962** [comment]
For future readers: I hadn't installed anything new. I just updated ComfyUI. Same issue happened to me, except the specific conflicting node was `pysssss.AutoCompleter`.
