### ISSUE TITLE
Connecting remotely with https

### ISSUE THREAD

**Issue by spider2077** [comfyanonymous/ComfyUI#5050]
### Your question

ok so when I first setup it used to work just fine then after a update and some custom  node installs now i cant access cofyui remotly via https, it works via http but not https anymore.... here is the error i get in the console when i try to establish connection with comfyui 
Error handling request
Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable_nvidia\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 362, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp\\_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    bytearray(b'\x16\x03\x01\x07')

**Comment by ltdrdata** [comment]
Disable all custom nodes (move them to another folder outside of ComfyUI) and test by restarting. If there's no problem, gradually restore some of the custom nodes to identify which custom node is causing the issue.

**Comment by spider2077** [comment]
thank you node were the issue comfyui-mixlab-nodes, used enable and disable from the manager till I got to it thanks again

**Comment by Lalimec** [comment]
I ve been having this exact issue for while, and today i did a clean installation for some other reason but its still there. I guess its the manager lol.

```
(venv) ubuntu@ip-172-31-45-103:~/ComfyUI$ python main.py --listen 0.0.0.0 --port 8188
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies. (GitPython)
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-22 16:08:55.838550
** Platform: Linux
** Python version: 3.12.6 | packaged by conda-forge | (main, Sep 22 2024, 14:16:49) [GCC 13.3.0]
** Python executable: /home/ubuntu/ComfyUI/venv/bin/python
** ComfyUI Path: /home/ubuntu/ComfyUI
** Log path: /home/ubuntu/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   6.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 22503 MB, total RAM 63592 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA A10G : cudaMallocAsync
Using pytorch cross attention
/home/ubuntu/ComfyUI/comfy/extra_samplers/uni_pc.py:19: SyntaxWarning: invalid escape sequence '\h'
  """Create a wrapper class for the forward SDE (VP type).
****** User settings have been changed to be stored on the server instead of browser storage. ******
****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******
[Prompt Server] web root: /home/ubuntu/ComfyUI/web
/home/ubuntu/ComfyUI/venv/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2779 [8ce2a105] | Released on '2024-10-22'

Import times for custom nodes:
   0.0 seconds: /home/ubuntu/ComfyUI/custom_nodes/websocket_image_save.py
   0.1 seconds: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager

Starting server

To see the GUI go to: http://0.0.0.0:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x07'
      ^
Error handling request
Traceback (most recent call last):
  File "/home/ubuntu/ComfyUI/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 377, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 563, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x01\x07'
      ^
FETCH DATA from: /home/ubuntu/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
```

**Comment by thelastpolaris** [comment]
Use http instead of https to access your comfy ui – http://your_ip:8188
