### ISSUE TITLE
IPAdapterSimple.apply_ipadapter() got an unexpected keyword argument 'clip_vision'

### ISSUE THREAD

**Issue by jeffreyrobeson** [comfyanonymous/ComfyUI#5053]
### Your question

# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapter
- **Exception Type:** TypeError
- **Exception Message:** IPAdapterSimple.apply_ipadapter() got an unexpected keyword argument 'clip_vision'
## Stack Trace
```
  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

```
## System Information
- **ComfyUI Version:** v0.2.2-75-gfdf3756
- **Arguments:** F:\aigc\ComfyUI-aki-v1.4\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17175150592
  - **VRAM Free:** 13781395750
  - **Torch VRAM Total:** 2113929216
  - **Torch VRAM Free:** 4155686

## Logs
```
2024-09-25 14:41:57,110 - root - INFO - Total VRAM 16380 MB, total RAM 32598 MB
2024-09-25 14:41:57,111 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-25 14:42:01,955 - root - INFO - xformers version: 0.0.27
2024-09-25 14:42:01,955 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-25 14:42:01,956 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-09-25 14:42:03,755 - root - INFO - Using xformers cross attention
2024-09-25 14:42:06,750 - root - INFO - [Prompt Server] web root: F:\aigc\ComfyUI-aki-v1.4\web
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path checkpoints F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/Stable-diffusion
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path configs F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/Stable-diffusion
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path vae F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/VAE
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path loras F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/Lora
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path loras F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/LyCORIS
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path upscale_models F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/ESRGAN
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path upscale_models F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/RealESRGAN
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path upscale_models F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/SwinIR
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path embeddings F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\embeddings
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path hypernetworks F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/hypernetworks
2024-09-25 14:42:06,784 - root - INFO - Adding extra search path controlnet F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/ControlNet
2024-09-25 14:42:06,785 - root - INFO - Adding extra search path ipadapter F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models\ipadapter
2024-09-25 14:42:06,785 - root - INFO - Adding extra search path clip_vision F:\aigc\sd-webui-aki\sd-webui-aki-v4.6.1\models/clipvision
2024-09-25 14:42:08,653 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\AniTalker-ComfyUI\__init__.py", line 18, in <module>
    import torchlm
ModuleNotFoundError: No module named 'torchlm'

2024-09-25 14:42:08,653 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\AniTalker-ComfyUI module for custom nodes: No module named 'torchlm'
2024-09-25 14:42:17,972 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Hallo\__init__.py", line 33, in <module>
    from .nodes import PreViewVideo,HalloNode,LoadImagePath, LoadAudioPath
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Hallo\nodes.py", line 6, in <module>
    from Hallo.scripts.inference import inference_process
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 40, in <module>
    from hallo.datasets.audio_processor import AudioProcessor
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Hallo\Hallo\hallo\datasets\audio_processor.py", line 14, in <module>
    from audio_separator.separator import Separator
ModuleNotFoundError: No module named 'audio_separator'

2024-09-25 14:42:17,972 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Hallo module for custom nodes: No module named 'audio_separator'
2024-09-25 14:42:18,061 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-I2V-Adapter\__init__.py", line 4, in <module>
    from .nodes import *
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-I2V-Adapter\nodes.py", line 20, in <module>
    from i2v_adapter.models.unet import UNet3DConditionModel
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-I2V-Adapter\i2v_adapter\models\unet.py", line 16, in <module>
    from diffusers.modeling_utils import ModelMixin
ModuleNotFoundError: No module named 'diffusers.modeling_utils'

2024-09-25 14:42:18,061 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-I2V-Adapter module for custom nodes: No module named 'diffusers.modeling_utils'
2024-09-25 14:42:22,115 - root - INFO - Total VRAM 16380 MB, total RAM 32598 MB
2024-09-25 14:42:22,115 - root - INFO - pytorch version: 2.3.1+cu121
2024-09-25 14:42:22,115 - root - INFO - xformers version: 0.0.27
2024-09-25 14:42:22,115 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-25 14:42:22,115 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 Ti : cudaMallocAsync
2024-09-25 14:42:27,887 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MuseTalk_FSH\__init__.py", line 1, in <module>
    from .nodes import MuseTalk,LoadVideo,PreViewVideo,CombineAudioVideo,MuseTalkRealTime
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MuseTalk_FSH\nodes.py", line 3, in <module>
    from .inference import MuseTalk_INFER
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MuseTalk_FSH\inference.py", line 14, in <module>
    from mmpose.apis import init_model
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\site-packages\mmpose\__init__.py", line 2, in <module>
    import mmcv
ModuleNotFoundError: No module named 'mmcv'

2024-09-25 14:42:27,887 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MuseTalk_FSH module for custom nodes: No module named 'mmcv'
2024-09-25 14:42:37,917 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\aigc\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI_MiniCPM-V-2_6-int4\\__init__.py'

2024-09-25 14:42:37,917 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_MiniCPM-V-2_6-int4 module for custom nodes: [Errno 2] No such file or directory: 'F:\\aigc\\ComfyUI-aki-v1.4\\custom_nodes\\ComfyUI_MiniCPM-V-2_6-int4\\__init__.py'
2024-09-25 14:42:38,738 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\DiffSynth-ComfyUI\__init__.py", line 5, in <module>
    from .video_synthesis_nodes import DownloadModelsNode, CogVideoNode,TextEncode
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\DiffSynth-ComfyUI\video_synthesis_nodes.py", line 9, in <module>
    from diffsynth import download_models,ModelManager\
ImportError: cannot import name 'download_models' from 'diffsynth' (F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\__init__.py)

2024-09-25 14:42:38,738 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\DiffSynth-ComfyUI module for custom nodes: cannot import name 'download_models' from 'diffsynth' (F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\__init__.py)
2024-09-25 14:42:39,146 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\FancyVideo-ComfyUI\__init__.py", line 11, in <module>
    from fancyvideo.pipelines.fancyvideo_infer_pipeline import InferPipeline
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\FancyVideo-ComfyUI\fancyvideo\pipelines\fancyvideo_infer_pipeline.py", line 23, in <module>
    from fancyvideo.models.cv_vae.modeling_vae import CVVAEModel
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\FancyVideo-ComfyUI\fancyvideo\models\cv_vae\modeling_vae.py", line 6, in <module>
    from diffusers.modeling_utils import ModelMixin
ModuleNotFoundError: No module named 'diffusers.modeling_utils'

2024-09-25 14:42:39,146 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\FancyVideo-ComfyUI module for custom nodes: No module named 'diffusers.modeling_utils'
2024-09-25 14:42:39,501 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\VideoSys-ComfyUI\__init__.py", line 6, in <module>
    from videosys import CogVideoXConfig,VideoSysEngine,LatteConfig,OpenSoraConfig,OpenSoraPlanConfig
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\VideoSys-ComfyUI\videosys\__init__.py", line 2, in <module>
    from .core.parallel_mgr import initialize
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\VideoSys-ComfyUI\videosys\core\parallel_mgr.py", line 5, in <module>
    from colossalai.cluster.process_group_mesh import ProcessGroupMesh
ModuleNotFoundError: No module named 'colossalai'

2024-09-25 14:42:39,502 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\VideoSys-ComfyUI module for custom nodes: No module named 'colossalai'
2024-09-25 14:42:40,612 - root - WARNING - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ViewCrafter-ComfyUI\__init__.py", line 11, in <module>
    from .infer import ViewCrafter
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ViewCrafter-ComfyUI\infer.py", line 22, in <module>
    import pytorch3d
ModuleNotFoundError: No module named 'pytorch3d'

2024-09-25 14:42:40,612 - root - WARNING - Cannot import F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ViewCrafter-ComfyUI module for custom nodes: No module named 'pytorch3d'
2024-09-25 14:42:40,613 - root - INFO - 
Import times for custom nodes:
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\websocket_image_save.py
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\comfyui_fk_server
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\FreeU_Advanced
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ControlNet-LLLite-ComfyUI
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_TiledKSampler
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\stability-ComfyUI-nodes
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_experiments
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\PowerNoiseSuite
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_MiniCPM-V-2_6-int4
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\comfyui_segment_anything
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_IPAdapter_plus
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_UltimateSDUpscale
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Custom-Scripts
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\images-grid-comfy-plugin
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\VideoSys-ComfyUI
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\DiffSynth-ComfyUI
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\efficiency-nodes-comfyui
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\RealisDance-ComfyUI
2024-09-25 14:42:40,613 - root - INFO -    0.0 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-KJNodes
2024-09-25 14:42:40,613 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\comfyui-animatediff
2024-09-25 14:42:40,613 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-3d-photo-inpainting
2024-09-25 14:42:40,613 - root - INFO -    0.1 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-I2V-Adapter
2024-09-25 14:42:40,613 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-25 14:42:40,613 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-WD14-Tagger
2024-09-25 14:42:40,613 - root - INFO -    0.1 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MuseTalk_FSH
2024-09-25 14:42:40,614 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Marigold
2024-09-25 14:42:40,614 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Inspire-Pack
2024-09-25 14:42:40,614 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\comfyui_controlnet_aux
2024-09-25 14:42:40,614 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Crystools
2024-09-25 14:42:40,614 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-25 14:42:40,614 - root - INFO -    0.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\DHLive-ComfyUI
2024-09-25 14:42:40,614 - root - INFO -    0.2 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\comfyui-workspace-manager
2024-09-25 14:42:40,614 - root - INFO -    0.2 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_essentials
2024-09-25 14:42:40,614 - root - INFO -    0.3 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\rgthree-comfy
2024-09-25 14:42:40,614 - root - INFO -    0.4 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\AniTalker-ComfyUI
2024-09-25 14:42:40,614 - root - INFO -    0.4 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\FancyVideo-ComfyUI
2024-09-25 14:42:40,614 - root - INFO -    0.4 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-09-25 14:42:40,614 - root - INFO -    0.6 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_V-Express
2024-09-25 14:42:40,614 - root - INFO -    0.7 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-SAM2
2024-09-25 14:42:40,614 - root - INFO -    1.0 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Hallo
2024-09-25 14:42:40,614 - root - INFO -    1.1 seconds (IMPORT FAILED): F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ViewCrafter-ComfyUI
2024-09-25 14:42:40,614 - root - INFO -    1.2 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack
2024-09-25 14:42:40,614 - root - INFO -    1.4 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Manager
2024-09-25 14:42:40,614 - root - INFO -    1.7 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_FizzNodes
2024-09-25 14:42:40,614 - root - INFO -    2.7 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-IP_LAP
2024-09-25 14:42:40,614 - root - INFO -    3.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-UniAnimate
2024-09-25 14:42:40,614 - root - INFO -    3.4 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-09-25 14:42:40,614 - root - INFO -    4.1 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-MimicMotion
2024-09-25 14:42:40,614 - root - INFO -    7.9 seconds: F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-DiffSynth-Studio
2024-09-25 14:42:40,614 - root - INFO - 
2024-09-25 14:42:40,627 - root - INFO - Starting server

2024-09-25 14:42:40,628 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-25 14:42:44,963 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'LatentSwitch' node.
2024-09-25 14:42:45,054 - root - ERROR - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\server.py", line 564, in get_object_info
    out[x] = node_info(x)
  File "F:\aigc\ComfyUI-aki-v1.4\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "F:\aigc\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack\modules\impact\util_nodes.py", line 19, in INPUT_TYPES
    stack = inspect.stack()
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 1673, in stack
    return getouterframes(sys._getframe(1), context)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 1650, in getouterframes
    frameinfo = (frame,) + getframeinfo(frame, context)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 1624, in getframeinfo
    lines, lnum = findsource(frame)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 952, in findsource
    module = getmodule(object, file)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 875, in getmodule
    f = getabsfile(module)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 844, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 817, in getsourcefile
    filename = getfile(object)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\site-packages\torch\package\package_importer.py", line 698, in _patched_getfile
    return _orig_getfile(object)
  File "F:\aigc\ComfyUI-aki-v1.4\python\lib\inspect.py", line 778, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'viewcrafter.utils' (<_frozen_importlib_external._NamespaceLoader object at 0x0000018A66E89930>)> is a built-in module

2024-09-25 14:42:53,521 - root - INFO - got prompt
2024-09-25 14:43:10,837 - py.warnings - WARNING - F:\aigc\ComfyUI-aki-v1.4\python\lib\site-packages\torch\functional.py:512: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at ..\aten\src\ATen\native\TensorShape.cpp:3588.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]

2024-09-25 14:43:39,190 - py.warnings - WARNING - F:\aigc\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils\checkpoint.py:464: UserWarning: torch.utils.checkpoint: the use_reentrant parameter should be passed explicitly. In version 2.4 we will raise an exception if use_reentrant is not passed. use_reentrant=False is recommended, but if you need to preserve the current default behavior, you can pass use_reentrant=True. Refer to docs for more details on the differences between the two variants.
  warnings.warn(

2024-09-25 14:43:39,190 - py.warnings - WARNING - F:\aigc\ComfyUI-aki-v1.4\python\lib\site-packages\torch\utils\checkpoint.py:91: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(

2024-09-25 14:47:07,828 - root - INFO - Using xformers attention in VAE
2024-09-25 14:47:07,829 - root - INFO - Using xformers attention in VAE
2024-09-25 14:47:07,950 - root - INFO - Requested to load AutoencoderKL
2024-09-25 14:47:07,951 - root - INFO - Loading 1 new model
2024-09-25 14:47:08,125 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-09-25 14:49:21,485 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-09-25 14:49:21,485 - root - INFO - model_type EPS
2024-09-25 14:50:04,581 - root - INFO - Using xformers attention in VAE
2024-09-25 14:50:04,582 - root - INFO - Using xformers attention in VAE
2024-09-25 14:50:12,927 - root - INFO - Requested to load SD1ClipModel
2024-09-25 14:50:12,927 - root - INFO - Loading 1 new model
2024-09-25 14:50:13,244 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-09-25 14:50:13,413 - py.warnings - WARNING - F:\aigc\ComfyUI-aki-v1.4\comfy\ldm\modules\attention.py:407: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  out = torch.nn.functional.scaled_dot_product_attention(q, k, v, attn_mask=mask, dropout_p=0.0, is_causal=False)

2024-09-25 14:50:52,434 - root - ERROR - !!! Exception during processing !!! IPAdapterSimple.apply_ipadapter() got an unexpected keyword argument 'clip_vision'
2024-09-25 14:50:52,549 - root - ERROR - Traceback (most recent call last):
  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\aigc\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
TypeError: IPAdapterSimple.apply_ipadapter() got an unexpected keyword argument 'clip_vision'

2024-09-25 14:50:52,551 - root - INFO - Prompt executed in 478.97 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI_IPAdapter_plus repo.
https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by Swmailv** [comment]
我也遇到了这个问题，请问怎么解决

**Comment by jeffreyrobeson** [comment]
更换最新节点IPAdapterSimple，问题解决
