### ISSUE TITLE
ReActor custom node Masking Helper - NameError: name 'YOLO' is not defined

### ISSUE THREAD

**Issue by spencerkiddle** [comfyanonymous/ComfyUI#5068]
### Your question

Cannot use Masking Helper custom node for ReActor.  Throws a name error 'YOLO' is not defined although there are three different yolo models I've tested this with. 
![image](https://github.com/user-attachments/assets/7eb1c306-4b47-4714-91f7-8622a974fdb9)
![image](https://github.com/user-attachments/assets/d1d16d84-72ee-46ab-9d14-b963516a2374)

### Logs

```powershell
loaded completely 14589.547244644165 12119.472778320312 True
100%|██████████████████████████████████████████████████████████████████████████████| 9/9 [00:38<00:00,  4.23s/it]
[ReActor] 03:06:39 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 03:06:39 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 03:06:39 - STATUS - Analyzing Target Image...
[ReActor] 03:06:39 - STATUS - Swapping...
[ReActor] 03:06:39 - STATUS - Face Boost is enabled
[ReActor] 03:06:39 - STATUS - Boosting the Face with GPEN-BFR-1024.onnx | Face Size is set to 1024 with Scale Factor = 8.0 and 'Bicubic' interpolation
[ReActor] 03:06:43 - STATUS - --Done!--
[ReActor] 03:06:43 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
!!! Exception during processing !!! name 'YOLO' is not defined
Traceback (most recent call last):
  File "C:\GO\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GO\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GO\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\GO\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GO\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 741, in execute
    bbox_model = subcore.load_yolo(bbox_model_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\GO\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\scripts\r_masking\subcore.py", line 16, in load_yolo
    return YOLO(model_path)
           ^^^^
NameError: name 'YOLO' is not defined

Prompt executed in 50.28 seconds
```

**Comment by ltdrdata** [comment]
This issue should be moved to comfyui-reactor-node repo.
https://github.com/Gourieff/comfyui-reactor-node
