### ISSUE TITLE
ComfyUI cpu

### ISSUE THREAD

**Issue by ayttop** [comfyanonymous/ComfyUI#5085]
### Your question

how to run flux gguf ComfyUI cpu?

### Logs

```powershell
It asks for Nvidia definition and I am running it on CPU
```

### Other

win11
ram64
i7
igpu intel

**Comment by ayttop** [comment]
# ComfyUI Error Report
## Error Details
- **Node Type:** XlabsSampler
- **Exception Type:** RuntimeError
- **Exception Message:** Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
## Stack Trace
```
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 361, in sampling
    if torch.cuda.is_bf16_supported():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 138, in is_bf16_supported
    device = torch.cuda.current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()

  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()

```
## System Information
- **ComfyUI Version:** v0.2.2-79-g83b01f9
- **Arguments:** ComfyUI\main.py --cpu --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cpu
  - **Type:** cpu
  - **VRAM Total:** 68470378496
  - **VRAM Free:** 48596049920
  - **Torch VRAM Total:** 68470378496
  - **Torch VRAM Free:** 48596049920

## Logs
```
2024-09-27 12:43:16,872 - root - INFO - Total VRAM 65298 MB, total RAM 65298 MB
2024-09-27 12:43:16,872 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-27 12:43:16,872 - root - INFO - Set vram state to: DISABLED
2024-09-27 12:43:16,872 - root - INFO - Device: cpu
2024-09-27 12:43:17,341 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-09-27 12:43:18,045 - root - INFO - [Prompt Server] web root: C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\web
2024-09-27 12:43:18,513 - root - INFO - 
Import times for custom nodes:
2024-09-27 12:43:18,513 - root - INFO -    0.0 seconds: C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-27 12:43:18,513 - root - INFO -    0.0 seconds: C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-09-27 12:43:18,513 - root - INFO -    0.1 seconds: C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-09-27 12:43:18,513 - root - INFO -    0.2 seconds: C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-27 12:43:18,513 - root - INFO - 
2024-09-27 12:43:18,513 - root - INFO - Starting server

2024-09-27 12:43:18,513 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-27 12:48:38,133 - root - INFO - got prompt
2024-09-27 12:48:38,152 - root - INFO - Using split attention in VAE
2024-09-27 12:48:38,152 - root - INFO - Using split attention in VAE
2024-09-27 12:48:38,396 - root - INFO - Requested to load FluxClipModel_
2024-09-27 12:48:38,396 - root - INFO - Loading 1 new model
2024-09-27 12:48:38,406 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-09-27 12:48:39,236 - root - WARNING - clip missing: ['text_projection.weight']
2024-09-27 12:48:57,016 - root - INFO - model weight dtype torch.float32, manual cast: None
2024-09-27 12:48:57,017 - root - INFO - model_type FLUX
2024-09-27 12:49:50,201 - root - INFO - Requested to load Flux
2024-09-27 12:49:50,202 - root - INFO - Loading 1 new model
2024-09-27 12:49:50,256 - root - INFO - loaded completely 0.0 4757.636962890625 True
2024-09-27 12:49:50,293 - root - ERROR - !!! Exception during processing !!! Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
2024-09-27 12:49:50,294 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 361, in sampling
    if torch.cuda.is_bf16_supported():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 138, in is_bf16_supported
    device = torch.cuda.current_device()
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 878, in current_device
    _lazy_init()
  File "C:\Users\Aytto\OneDrive\Desktop\77\new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

2024-09-27 12:49:50,296 - root - INFO - Prompt executed in 72.16 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":43,"last_link_id":87,"nodes":[{"id":3,"type":"XlabsSampler","pos":{"0":887,"1":57},"size":{"0":356.8063659667969,"1":342.29022216796875},"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":79,"slot_index":0},{"name":"conditioning","type":"CONDITIONING","link":18},{"name":"neg_conditioning","type":"CONDITIONING","link":26},{"name":"latent_image","type":"LATENT","link":75},{"name":"controlnet_condition","type":"ControlNetCondition","link":null}],"outputs":[{"name":"latent","type":"LATENT","links":[6],"shape":3}],"properties":{"Node name for S&R":"XlabsSampler"},"widgets_values":[4,"fixed",25,1,3.5,0,1]},{"id":42,"type":"Reroute","pos":{"0":-295,"1":-173},"size":[75,26],"flags":{},"order":8,"mode":0,"inputs":[{"name":"","type":"*","link":85}],"outputs":[{"name":"","type":"CLIP","links":[86],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":6,"type":"EmptyLatentImage","pos":{"0":925,"1":478},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[75],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[768,768,1]},{"id":27,"type":"ApplyFluxIPAdapter","pos":{"0":507,"1":98},"size":{"0":210,"1":98},"flags":{},"order":10,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":84,"slot_index":0},{"name":"ip_adapter_flux","type":"IP_ADAPTER_FLUX","link":65},{"name":"image","type":"IMAGE","link":73,"slot_index":2}],"outputs":[{"name":"MODEL","type":"MODEL","links":[79],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ApplyFluxIPAdapter"},"widgets_values":[0.8200000000000001],"color":"#232","bgcolor":"#353"},{"id":19,"type":"CLIPTextEncodeFlux","pos":{"0":653,"1":411},"size":{"0":400,"1":200},"flags":{"collapsed":true},"order":9,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":87,"slot_index":0}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[26],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPTextEncodeFlux"},"widgets_values":["","",4]},{"id":7,"type":"VAEDecode","pos":{"0":1265,"1":-305},"size":{"0":210,"1":46},"flags":{},"order":13,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":6,"slot_index":0},{"name":"vae","type":"VAE","link":59}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[80],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":8,"type":"VAELoader","pos":{"0":923,"1":-286},"size":{"0":251.00521850585938,"1":58.95216751098633},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[59],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"]},{"id":16,"type":"LoadImage","pos":{"0":-913,"1":-214},"size":{"0":315,"1":314},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[72],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["example.jpg","image"]},{"id":32,"type":"LoadFluxIPAdapter","pos":{"0":70,"1":117},"size":{"0":315,"1":106},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"ipadapterFlux","type":"IP_ADAPTER_FLUX","links":[65],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"LoadFluxIPAdapter"},"widgets_values":["flux-ip-adapter.safetensors","clipgguf.safetensors","CPU"],"color":"#232","bgcolor":"#353"},{"id":33,"type":"ImageScale","pos":{"0":-296,"1":154},"size":{"0":315,"1":130},"flags":{},"order":7,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":72,"slot_index":0}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[73],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ImageScale"},"widgets_values":["nearest-exact",512,512,"disabled"],"color":"#232","bgcolor":"#353"},{"id":37,"type":"UnetLoaderGGUF","pos":{"0":182,"1":279},"size":{"0":315,"1":58},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[84],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"UnetLoaderGGUF"},"widgets_values":["flux1-dev-Q2_K.gguf"],"color":"#322","bgcolor":"#533"},{"id":4,"type":"DualCLIPLoader","pos":{"0":-654,"1":392},"size":{"0":315,"1":106},"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[85,87],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","clip_l.safetensors","flux"],"color":"#223","bgcolor":"#335"},{"id":38,"type":"SaveImage","pos":{"0":-126,"1":549},"size":{"0":669.4788818359375,"1":775.4940795898438},"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":80}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":43,"type":"Note","pos":{"0":-1392.354248046875,"1":159.88404846191406},"size":{"0":527.305419921875,"1":204.95562744140625},"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[],"properties":{},"widgets_values":["IPA Model\n\nhttps://huggingface.co/XLabs-AI/flux-ip-adapter/tree/main\n\nclip vision IPA\nhttps://huggingface.co/openai/clip-vit-large-patch14/tree/main\n\nXFLUX NODES\nhttps://github.com/XLabs-AI/x-flux-comfyui\n\nGGUF nodes\nhttps://github.com/city96/ComfyUI-GGUF"],"color":"#432","bgcolor":"#653"},{"id":5,"type":"CLIPTextEncodeFlux","pos":{"0":428,"1":-169},"size":{"0":400,"1":200},"flags":{},"order":11,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":86,"slot_index":0}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[18],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPTextEncodeFlux"},"widgets_values":["holding sign with glowing green text \"X-LABS IP Adapter\"","holding sign with glowing green text \"X-LABS IP Adapter\"",1],"color":"#223","bgcolor":"#335"}],"links":[[6,3,0,7,0,"LATENT"],[18,5,0,3,1,"CONDITIONING"],[26,19,0,3,2,"CONDITIONING"],[59,8,0,7,1,"VAE"],[65,32,0,27,1,"IP_ADAPTER_FLUX"],[72,16,0,33,0,"IMAGE"],[73,33,0,27,2,"IMAGE"],[75,6,0,3,3,"LATENT"],[79,27,0,3,0,"MODEL"],[80,7,0,38,0,"IMAGE"],[84,37,0,27,0,"MODEL"],[85,4,0,42,0,"*"],[86,42,0,5,0,"CLIP"],[87,4,0,19,0,"CLIP"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9090909090909091,"offset":[406.24178908186633,186.47345218490753]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ayttop** [comment]
Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from

**Comment by ayttop** [comment]
i run it with run_cpu.bat

**Comment by ayttop** [comment]
new_ComfyUI_windows_portable_nvidia_cu124_or_cpu\ComfyUI_windows_portable\run_cpu.bat

**Comment by ltdrdata** [comment]
Please move this issue to related repo.
https://github.com/XLabs-AI/x-flux-comfyui/issues
