### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'configure')

### ISSUE THREAD

**Issue by WakerKQ-lab** [comfyanonymous/ComfyUI#5102]
### Your question

Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'configure')
TypeError: Cannot read properties of undefined (reading 'configure')
    at ComfyApp.loadGraphData (https://aistudioproxy.alipay.com/proxy/libroAppInstance_48550677_-112443766:8080/proxy/app/7860/assets/index-Drc_oD2f.js:82011:18)
    at async app2.loadGraphData (https://aistudioproxy.alipay.com/proxy/libroAppInstance_48550677_-112443766:8080/proxy/app/7860/assets/index-Drc_oD2f.js:76641:18)
    at async ComfyApp.handleFile (https://aistudioproxy.alipay.com/proxy/libroAppInstance_48550677_-112443766:8080/proxy/app/7860/assets/index-Drc_oD2f.js:82325:9)
![lQLPKejE3CvV7EfNAmrNCNiwR33a6_jBdDMG4OiAfek5AQ_2264_618](https://github.com/user-attachments/assets/9a25674b-4f2e-4a91-afe8-fe24d776962a)

### Logs

```powershell
can anyone tell how to fix this issue? I tried remove all custom nodes, but the error remains
```

**Comment by ltdrdata** [comment]
Please disable all custom nodes and refresh the browser and test again.
