### ISSUE TITLE
"index 1097454993 is out of bounds for dimension 0 with size 1000"

### ISSUE THREAD

**Issue by AfroSpartan** [comfyanonymous/ComfyUI#5141]
### Your question

After rendering one image, attempting to render another throws the error `index 1097454993 is out of bounds for dimension 0 with size 1000` from the ksampler node.

### Logs

```powershell
got prompt
!!! Exception during processing !!! index 1097454993 is out of bounds for dimension 0 with size 1000
Traceback (most recent call last):
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\nodes.py", line 1434, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\nodes.py", line 1401, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\sample.py", line 41, in sample
    sampler = comfy.samplers.KSampler(model, steps=steps, device=model.load_device, sampler=sampler_name, scheduler=scheduler, denoise=denoise, model_options=model.model_options)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\samplers.py", line 779, in __init__
    self.set_steps(steps, denoise)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\samplers.py", line 800, in set_steps
    self.sigmas = self.calculate_sigmas(steps).to(self.device)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\samplers.py", line 791, in calculate_sigmas
    sigmas = calculate_sigmas(self.model.get_model_object("model_sampling"), self.scheduler, steps)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\samplers.py", line 741, in calculate_sigmas
    sigmas = normal_scheduler(model_sampling, steps)
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\samplers.py", line 339, in normal_scheduler
    if math.isclose(float(s.sigma(end)), 0, abs_tol=0.00001):
  File "G:\Projects\Dev\SD-Zluda\ComfyUI\comfy\model_sampling.py", line 110, in sigma
    log_sigma = (1 - w) * self.log_sigmas[low_idx] + w * self.log_sigmas[high_idx]
IndexError: index 1097454993 is out of bounds for dimension 0 with size 1000
```

### Other

I'm running on AMD/Zluda/Windows if that has any relevance

**Comment by wietzeschelhaas** [comment]
Did you find a solution to this? Im struggling with the exact same problem

**Comment by AfroSpartan** [comment]
No, I think I ended up using something else but I can't remember what it was now
