### ISSUE TITLE
Error(s) in loading state_dict for Resampler: size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).

### ISSUE THREAD

**Issue by niemeng51** [comfyanonymous/ComfyUI#5146]
### Your question

# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterApply
- **Exception Type:** RuntimeError
- **Exception Message:** Error(s) in loading state_dict for Resampler:
	size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).
## Stack Trace
```
  File "S:\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "S:\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "S:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "S:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 769, in apply_ipadapter
    self.ipadapter = IPAdapter(

  File "S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 369, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])

  File "S:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** S:\ComfyUI-aki-v1.3\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884246528
  - **VRAM Free:** 7958737408
  - **Torch VRAM Total:** 3758096384
  - **Torch VRAM Free:** 30454272

## Logs
```
2024-10-04 11:54:00,164 - root - INFO - Total VRAM 12287 MB, total RAM 32675 MB
2024-10-04 11:54:00,164 - root - INFO - pytorch version: 2.1.2+cu118
2024-10-04 11:54:00,381 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-10-04 11:54:00,381 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-04 11:54:00,381 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-10-04 11:54:01,219 - root - INFO - Using xformers cross attention
2024-10-04 11:54:01,697 - root - INFO - [Prompt Server] web root: S:\ComfyUI-aki-v1.3\web
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path checkpoints E:\sd-webui-aki-v4.8/models/Stable-diffusion
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path configs E:\sd-webui-aki-v4.8/models/Stable-diffusion
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path vae E:\sd-webui-aki-v4.8/models/VAE
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path loras E:\sd-webui-aki-v4.8/models/Lora
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path loras E:\sd-webui-aki-v4.8/models/LyCORIS
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path upscale_models E:\sd-webui-aki-v4.8/models/ESRGAN
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path upscale_models E:\sd-webui-aki-v4.8/models/RealESRGAN
2024-10-04 11:54:01,699 - root - INFO - Adding extra search path upscale_models E:\sd-webui-aki-v4.8/models/SwinIR
2024-10-04 11:54:01,700 - root - INFO - Adding extra search path embeddings E:\sd-webui-aki-v4.8/embeddings
2024-10-04 11:54:01,700 - root - INFO - Adding extra search path hypernetworks E:\sd-webui-aki-v4.8/models/hypernetworks
2024-10-04 11:54:01,700 - root - INFO - Adding extra search path controlnet E:\sd-webui-aki-v4.8/models/ControlNet
2024-10-04 11:54:02,510 - root - WARNING - Traceback (most recent call last):
  File "S:\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "S:\ComfyUI-aki-v1.3\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
ModuleNotFoundError: No module named 'torchaudio'

2024-10-04 11:54:02,511 - root - WARNING - Cannot import S:\ComfyUI-aki-v1.3\comfy_extras\nodes_audio.py module for custom nodes: No module named 'torchaudio'
2024-10-04 11:54:09,016 - root - WARNING - Traceback (most recent call last):
  File "S:\ComfyUI-aki-v1.3\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'S:\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Frame-Interpolation\\__init__.py'

2024-10-04 11:54:09,016 - root - WARNING - Cannot import S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Frame-Interpolation module for custom nodes: [Errno 2] No such file or directory: 'S:\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Frame-Interpolation\\__init__.py'
2024-10-04 11:54:09,042 - root - INFO - Total VRAM 12287 MB, total RAM 32675 MB
2024-10-04 11:54:09,042 - root - INFO - pytorch version: 2.1.2+cu118
2024-10-04 11:54:09,042 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-10-04 11:54:09,042 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-04 11:54:09,042 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-10-04 11:54:26,747 - root - INFO - 
Import times for custom nodes:
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\websocket_image_save.py
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF-main
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds (IMPORT FAILED): S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\comfyui_segment_anything
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\x-flux-comfyui-main
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-GGUF
2024-10-04 11:54:26,747 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-KJNodes-main
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\OneButtonPrompt-main
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy-main
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IC-Light-main
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus-main
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_bitsandbytes_NF4-master
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-04 11:54:26,748 - root - INFO -    0.0 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
2024-10-04 11:54:26,748 - root - INFO -    0.1 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\Comfyui-ergouzi-Nodes-main
2024-10-04 11:54:26,748 - root - INFO -    0.1 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet-Wrapper-main
2024-10-04 11:54:26,748 - root - INFO -    0.1 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-04 11:54:26,748 - root - INFO -    0.3 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
2024-10-04 11:54:26,748 - root - INFO -    0.3 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet-main
2024-10-04 11:54:26,748 - root - INFO -    0.3 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-SAM2
2024-10-04 11:54:26,748 - root - INFO -    0.4 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use-main
2024-10-04 11:54:26,748 - root - INFO -    0.4 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
2024-10-04 11:54:26,748 - root - INFO -    0.4 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
2024-10-04 11:54:26,748 - root - INFO -    0.7 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
2024-10-04 11:54:26,748 - root - INFO -    4.5 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\was-node-suite-comfyui
2024-10-04 11:54:26,748 - root - INFO -    5.6 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools
2024-10-04 11:54:26,748 - root - INFO -   10.6 seconds: S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-10-04 11:54:26,748 - root - INFO - 
2024-10-04 11:54:26,748 - root - WARNING - WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

2024-10-04 11:54:26,749 - root - WARNING - IMPORT FAILED: nodes_audio.py
2024-10-04 11:54:26,749 - root - WARNING - 
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
2024-10-04 11:54:26,749 - root - WARNING - Please do a: pip install -r requirements.txt
2024-10-04 11:54:26,749 - root - WARNING - 
2024-10-04 11:54:26,764 - root - INFO - Starting server

2024-10-04 11:54:26,764 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-04 11:59:47,310 - root - INFO - got prompt
2024-10-04 11:59:47,838 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-04 11:59:47,839 - root - INFO - model_type V_PREDICTION_EDM
2024-10-04 11:59:48,588 - root - INFO - Using xformers attention in VAE
2024-10-04 11:59:48,598 - root - INFO - Using xformers attention in VAE
2024-10-04 11:59:57,818 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-04 11:59:57,819 - root - INFO - model_type EPS
2024-10-04 12:03:55,794 - root - INFO - Using xformers attention in VAE
2024-10-04 12:03:55,796 - root - INFO - Using xformers attention in VAE
2024-10-04 12:04:07,177 - root - INFO - Requested to load SDXLClipModel
2024-10-04 12:04:07,177 - root - INFO - Loading 1 new model
2024-10-04 12:04:07,186 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-04 12:04:17,825 - root - INFO - Requested to load SDXL
2024-10-04 12:04:17,825 - root - INFO - Loading 1 new model
2024-10-04 12:04:19,316 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-10-04 12:04:26,294 - root - INFO - Requested to load AutoencoderKL
2024-10-04 12:04:26,294 - root - INFO - Loading 1 new model
2024-10-04 12:04:26,466 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-04 12:04:27,021 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-04 12:04:27,021 - root - INFO - Loading 1 new model
2024-10-04 12:04:27,393 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-10-04 12:04:27,508 - root - INFO - Requested to load AutoencodingEngine
2024-10-04 12:04:27,509 - root - INFO - Loading 1 new model
2024-10-04 12:04:27,574 - root - INFO - loaded completely 0.0 186.42957878112793 True
2024-10-04 12:04:27,800 - root - INFO - Requested to load SVD_img2vid
2024-10-04 12:04:27,800 - root - INFO - Loading 1 new model
2024-10-04 12:04:31,901 - root - INFO - loaded completely 0.0 2907.987678527832 True
2024-10-04 12:08:10,769 - root - INFO - Requested to load AutoencodingEngine
2024-10-04 12:08:10,769 - root - INFO - Loading 1 new model
2024-10-04 12:08:10,967 - root - INFO - loaded completely 0.0 186.42957878112793 True
2024-10-04 12:08:28,115 - root - INFO - Prompt executed in 520.75 seconds
2024-10-04 12:10:54,701 - root - INFO - got prompt
2024-10-04 12:10:54,778 - root - INFO - Requested to load SDXLClipModel
2024-10-04 12:10:54,778 - root - INFO - Loading 1 new model
2024-10-04 12:10:55,241 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-04 12:10:55,309 - root - INFO - Requested to load SDXL
2024-10-04 12:10:55,309 - root - INFO - Loading 1 new model
2024-10-04 12:10:57,147 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-10-04 12:11:03,831 - root - INFO - Requested to load AutoencoderKL
2024-10-04 12:11:03,831 - root - INFO - Loading 1 new model
2024-10-04 12:11:04,628 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-04 12:11:05,088 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-04 12:11:05,088 - root - INFO - Loading 1 new model
2024-10-04 12:11:05,473 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-10-04 12:11:05,571 - root - INFO - Requested to load AutoencodingEngine
2024-10-04 12:11:05,571 - root - INFO - Loading 1 new model
2024-10-04 12:11:05,950 - root - INFO - loaded completely 0.0 186.42957878112793 True
2024-10-04 12:11:08,585 - root - INFO - Unloading models for lowram load.
2024-10-04 12:11:09,274 - root - INFO - 0 models unloaded.
2024-10-04 12:15:05,201 - root - INFO - Requested to load AutoencodingEngine
2024-10-04 12:15:05,201 - root - INFO - Loading 1 new model
2024-10-04 12:15:05,331 - root - INFO - loaded completely 0.0 186.42957878112793 True
2024-10-04 12:15:22,327 - root - INFO - Prompt executed in 267.58 seconds
2024-10-04 13:08:07,039 - root - INFO - got prompt
2024-10-04 13:08:07,225 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-04 13:08:07,226 - root - INFO - Loading 1 new model
2024-10-04 13:08:07,590 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-10-04 13:08:09,297 - root - INFO - loaded completely 5855.799919891358 2907.987678527832 True
2024-10-04 13:10:03,661 - root - INFO - Requested to load AutoencodingEngine
2024-10-04 13:10:03,661 - root - INFO - Loading 1 new model
2024-10-04 13:10:03,881 - root - INFO - loaded completely 0.0 186.42957878112793 True
2024-10-04 13:10:12,315 - root - INFO - Prompt executed in 125.22 seconds
2024-10-04 13:45:36,034 - root - INFO - got prompt
2024-10-04 13:48:45,784 - root - INFO - Prompt executed in 189.73 seconds
2024-10-04 14:28:18,920 - root - INFO - got prompt
2024-10-04 14:28:21,589 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-04 14:28:21,589 - root - INFO - model_type EPS
2024-10-04 14:29:00,449 - root - INFO - Using xformers attention in VAE
2024-10-04 14:29:00,451 - root - INFO - Using xformers attention in VAE
2024-10-04 14:29:26,809 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-04 14:29:26,810 - root - INFO - Loading 1 new model
2024-10-04 14:29:28,075 - root - INFO - loaded completely 0.0 3522.953369140625 True
2024-10-04 14:29:29,058 - root - ERROR - !!! Exception during processing !!! Error(s) in loading state_dict for Resampler:
	size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).
2024-10-04 14:29:29,063 - root - ERROR - Traceback (most recent call last):
  File "S:\ComfyUI-aki-v1.3\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "S:\ComfyUI-aki-v1.3\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "S:\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "S:\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 769, in apply_ipadapter
    self.ipadapter = IPAdapter(
  File "S:\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 369, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "S:\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Resampler:
	size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1664]).

2024-10-04 14:29:29,065 - root - INFO - Prompt executed in 70.12 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":21,"last_link_id":27,"nodes":[{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":40,"1":467},"size":{"0":315,"1":98},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[21,26],"slot_index":0,"label":"模型"},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1,"label":"CLIP"},{"name":"VAE","type":"VAE","links":[8],"slot_index":2,"label":"VAE"}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["人物00\\majicMIX realistic 麦橘写实_v7.safetensors"]},{"id":6,"type":"CLIPTextEncode","pos":{"0":447,"1":188},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["1girl, "]},{"id":7,"type":"CLIPTextEncode","pos":{"0":439,"1":404},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":7,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":17,"type":"LoadImage","pos":{"0":661.432373046875,"1":1109.138916015625},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[20,25],"shape":3,"label":"图像"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["微信图片_20240728100509.png","image"]},{"id":16,"type":"CLIPVisionLoader","pos":{"0":656.432373046875,"1":988.1387939453125},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP_VISION","type":"CLIP_VISION","links":[17,24],"shape":3,"label":"CLIP视觉"}],"properties":{"Node name for S&R":"CLIPVisionLoader"},"widgets_values":["clip_vision_g.safetensors"]},{"id":15,"type":"IPAdapterModelLoader","pos":{"0":653.432373046875,"1":837.138916015625},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"IPADAPTER","type":"IPADAPTER","links":[16,23],"slot_index":0,"shape":3,"label":"IPAdapter"}],"properties":{"Node name for S&R":"IPAdapterModelLoader"},"widgets_values":["ip-adapter-plus-face_sd15.safetensors"]},{"id":3,"type":"KSampler","pos":{"0":1017.4325561523438,"1":1143.138916015625},"size":{"0":320,"1":470},"flags":{},"order":10,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":27,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":4,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":6,"label":"负面条件"},{"name":"latent_image","type":"LATENT","link":2,"label":"Latent"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[1098341053690610,"randomize",20,8,"euler","normal",1]},{"id":5,"type":"EmptyLatentImage","pos":{"0":664.432373046875,"1":1494.138916015625},"size":{"0":315,"1":106},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,768,1]},{"id":21,"type":"IPAdapterApply","pos":{"0":1009,"1":836},"size":{"0":315,"1":258},"flags":{},"order":8,"mode":0,"inputs":[{"name":"ipadapter","type":"IPADAPTER","link":23,"label":"IPAdapter"},{"name":"clip_vision","type":"CLIP_VISION","link":24,"label":"CLIP视觉"},{"name":"image","type":"IMAGE","link":25,"label":"图像"},{"name":"model","type":"MODEL","link":26,"label":"模型"},{"name":"attn_mask","type":"MASK","link":null,"label":"关注层遮罩"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[27],"slot_index":0,"shape":3,"label":"模型"}],"properties":{"Node name for S&R":"IPAdapterApply"},"widgets_values":[1,0,"original",0,1,false]},{"id":9,"type":"SaveImage","pos":{"0":1973,"1":318},"size":{"0":210,"1":270},"flags":{},"order":12,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":8,"type":"VAEDecode","pos":{"0":1669,"1":313},"size":{"0":210,"1":46},"flags":{},"order":11,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7,"label":"Latent"},{"name":"vae","type":"VAE","link":8,"label":"VAE"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"VAEDecode"}},{"id":20,"type":"InsightFaceLoader","pos":{"0":1459.720947265625,"1":1220.970458984375},"size":{"0":315,"1":58},"flags":{},"order":5,"mode":4,"inputs":[],"outputs":[{"name":"INSIGHTFACE","type":"INSIGHTFACE","links":[19],"shape":3}],"properties":{"Node name for S&R":"InsightFaceLoader"},"widgets_values":["CUDA"]},{"id":18,"type":"IPAdapterApplyFaceID","pos":{"0":1475.720947265625,"1":842.97021484375},"size":{"0":315,"1":326},"flags":{},"order":9,"mode":4,"inputs":[{"name":"ipadapter","type":"IPADAPTER","link":16,"label":"IPAdapter"},{"name":"clip_vision","type":"CLIP_VISION","link":17,"label":"CLIP视觉"},{"name":"insightface","type":"INSIGHTFACE","link":19,"label":"InsightFace"},{"name":"image","type":"IMAGE","link":20,"label":"图像"},{"name":"model","type":"MODEL","link":21,"label":"模型"},{"name":"attn_mask","type":"MASK","link":null,"label":"关注层遮罩"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[],"slot_index":0,"shape":3,"label":"模型"}],"properties":{"Node name for S&R":"IPAdapterApplyFaceID"},"widgets_values":[1,0,"original",0,1,false,1,false]}],"links":[[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[16,15,0,18,0,"IPADAPTER"],[17,16,0,18,1,"CLIP_VISION"],[19,20,0,18,2,"INSIGHTFACE"],[20,17,0,18,3,"IMAGE"],[21,4,0,18,4,"MODEL"],[23,15,0,21,0,"IPADAPTER"],[24,16,0,21,1,"CLIP_VISION"],[25,17,0,21,2,"IMAGE"],[26,4,0,21,3,"MODEL"],[27,21,0,3,0,"MODEL"]],"groups":[{"title":"Group","bounding":[643,760,704,864],"color":"#3f789e","font_size":24,"flags":{}},{"title":"Group","bounding":[1450,769,351,520],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.5054470284992951,"offset":[765.8362295794207,-49.0354572895057]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ltdrdata** [comment]
First of all, your custom node is outdated. Update it to the latest version and then try to reproduce the issue again.

Also, this issue is related to ComfyUI_IPAdapter_plus, so if you're still experiencing this issue after updating, please post it on that repository.
https://github.com/cubiq/ComfyUI_IPAdapter_plus

**Comment by niemeng51** [comment]
THANK YOU

**Comment by AthenixOnTop** [comment]
I still don't know how to fix this!

**Comment by alexzheng1996** [comment]
> First of all, your custom node is outdated. Update it to the latest version and then try to reproduce the issue again.
> 
> Also, this issue is related to ComfyUI_IPAdapter_plus, so if you're still experiencing this issue after updating, please post it on that repository. https://github.com/cubiq/ComfyUI_IPAdapter_plus

Hi Boss, I have download all of ipadapter_plus, but still not work.
