### ISSUE TITLE
KSampler (Efficient) error issue

### ISSUE THREAD

**Issue by ClarenceDS** [comfyanonymous/ComfyUI#5149]
### Expected Behavior

I wanted to have a qr code to be combined with an image.

### Actual Behavior

KSampler (Efficient)
mat1 and mat2 shapes cannot be multiplied (154x2048 and 768x320)

### Steps to Reproduce

I just clicked queue prompt.

### Debug Logs

```powershell
2024-10-04 23:21:25,723 - root - INFO - Total VRAM 12282 MB, total RAM 32505 MB
2024-10-04 23:21:25,723 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-04 23:21:25,723 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-04 23:21:25,724 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-10-04 23:21:26,250 - root - INFO - Using pytorch cross attention
2024-10-04 23:21:27,116 - root - INFO - [Prompt Server] web root: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-04 23:21:27,117 - root - INFO - Adding extra search path checkpoints path/to/stable-diffusion-webui/models/Stable-diffusion
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path vae path/to/stable-diffusion-webui/models/VAE
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path loras path/to/stable-diffusion-webui/models/Lora
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
2024-10-04 23:21:27,118 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
2024-10-04 23:21:27,119 - root - INFO - Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
2024-10-04 23:21:27,119 - root - INFO - Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
2024-10-04 23:21:27,119 - root - INFO - Adding extra search path controlnet path/to/stable-diffusion-webui/models/ControlNet
2024-10-04 23:21:27,395 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SkidRenz\\Downloads\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\clip_vision\\__init__.py'

2024-10-04 23:21:27,395 - root - WARNING - Cannot import C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip_vision module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\SkidRenz\\Downloads\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\clip_vision\\__init__.py'
2024-10-04 23:21:27,830 - root - WARNING - Traceback (most recent call last):
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1998, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\SkidRenz\\Downloads\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ipadapter\\__init__.py'

2024-10-04 23:21:27,831 - root - WARNING - Cannot import C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ipadapter module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\SkidRenz\\Downloads\\ComfyUI_windows_portable_nvidia\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ipadapter\\__init__.py'
2024-10-04 23:21:27,831 - root - INFO - 
Import times for custom nodes:
2024-10-04 23:21:27,831 - root - INFO -    0.0 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-04 23:21:27,832 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ipadapter
2024-10-04 23:21:27,832 - root - INFO -    0.0 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-04 23:21:27,832 - root - INFO -    0.0 seconds (IMPORT FAILED): C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\clip_vision
2024-10-04 23:21:27,832 - root - INFO -    0.0 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-04 23:21:27,832 - root - INFO -    0.0 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-04 23:21:27,833 - root - INFO -    0.0 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-04 23:21:27,833 - root - INFO -    0.2 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-04 23:21:27,833 - root - INFO -    0.2 seconds: C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-04 23:21:27,833 - root - INFO - 
2024-10-04 23:21:27,837 - root - INFO - Starting server

2024-10-04 23:21:27,837 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-04 23:23:30,496 - root - INFO - got prompt
2024-10-04 23:23:30,501 - root - ERROR - Failed to validate prompt for output 100:
2024-10-04 23:23:30,501 - root - ERROR - * Efficient Loader 97:
2024-10-04 23:23:30,501 - root - ERROR -   - Required input is missing: ckpt_name
2024-10-04 23:23:30,501 - root - ERROR - Output will be ignored
2024-10-04 23:23:30,501 - root - ERROR - Failed to validate prompt for output 96:
2024-10-04 23:23:30,502 - root - ERROR - Output will be ignored
2024-10-04 23:23:30,505 - root - INFO - Prompt executed in 0.00 seconds
2024-10-04 23:34:34,980 - root - INFO - got prompt
2024-10-04 23:34:34,985 - root - ERROR - Failed to validate prompt for output 100:
2024-10-04 23:34:34,986 - root - ERROR - * Efficient Loader 97:
2024-10-04 23:34:34,986 - root - ERROR -   - Required input is missing: ckpt_name
2024-10-04 23:34:34,986 - root - ERROR - Output will be ignored
2024-10-04 23:34:34,986 - root - ERROR - Failed to validate prompt for output 96:
2024-10-04 23:34:34,986 - root - ERROR - Output will be ignored
2024-10-04 23:34:34,990 - root - INFO - Prompt executed in 0.00 seconds
2024-10-04 23:37:36,085 - root - INFO - got prompt
2024-10-04 23:37:36,220 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-04 23:37:36,235 - root - INFO - model_type EPS
2024-10-04 23:37:37,026 - root - INFO - Using pytorch attention in VAE
2024-10-04 23:37:37,027 - root - INFO - Using pytorch attention in VAE
2024-10-04 23:37:37,243 - root - INFO - Requested to load SDXLClipModel
2024-10-04 23:37:37,243 - root - INFO - Loading 1 new model
2024-10-04 23:37:37,251 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-04 23:37:37,973 - root - INFO - Requested to load SDXLClipModel
2024-10-04 23:37:37,973 - root - INFO - Loading 1 new model
2024-10-04 23:37:38,305 - root - WARNING - warning, embedding:quality\FastNegativeV2, does not exist, ignoring
2024-10-04 23:37:38,306 - root - WARNING - warning, embedding:quality\FastNegativeV2, does not exist, ignoring
2024-10-04 23:37:40,486 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-04 23:37:40,486 - root - INFO - Loading 1 new model
2024-10-04 23:37:40,666 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-10-04 23:37:42,859 - root - INFO - Requested to load ControlNet
2024-10-04 23:37:42,859 - root - INFO - Requested to load SDXL
2024-10-04 23:37:42,860 - root - INFO - Loading 2 new models
2024-10-04 23:37:42,963 - root - INFO - loaded completely 0.0 689.0852355957031 True
2024-10-04 23:37:43,667 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-10-04 23:37:45,652 - root - ERROR - !!! Exception during processing !!! mat1 and mat2 shapes cannot be multiplied (154x2048 and 768x320)
2024-10-04 23:37:45,694 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 732, in sample
    samples, images, gifs, preview = process_latent_image(model, seed, steps, cfg, sampler_name, scheduler,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 550, in process_latent_image
    samples = KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1434, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1401, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\sampling.py", line 116, in acn_sample
    return orig_comfy_sample(model, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\utils.py", line 117, in uncond_multiplier_check_cn_sample
    return orig_comfy_sample(model, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SkidRenz\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
```

### Other

![Untitled](https://github.com/user-attachments/assets/5a6c0e9d-eb0f-460a-b863-d8d05f7e0bda)

**Comment by ClarenceDS** [comment]
solved it. I had to replace the monster qr which was not compatible with SDXL. it was a version compatible for SD1.5
