### ISSUE TITLE
24/10/7 After Updated, I cannot use controlnet, Ksampler Error 0

### ISSUE THREAD

**Issue by Nikki29o** [comfyanonymous/ComfyUI#5181]
### Expected Behavior

![image](https://github.com/user-attachments/assets/cadbe753-6e6b-45c4-a339-9fc12562e1fe)
I checked the version of controlnet and checkpoint. The difference before I can run this workflow is that I update ComfyUI and install flux nodes.

### Actual Behavior

![image](https://github.com/user-attachments/assets/f6035997-54dd-44e1-bac7-af876224d75b)

### Steps to Reproduce

[workflow (1).json](https://github.com/user-attachments/files/17278619/workflow.1.json)

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** KSampler
- **Exception Type:** KeyError
- **Exception Message:** 0
## Stack Trace
File "ComfyUI/execution.py", line 323, in execute output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

File "ComfyUI/execution.py", line 198, in get_output_data return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

File "ComfyUI/execution.py", line 169, in _map_node_over_list process_inputs(input_dict, i)

File "ComfyUI/execution.py", line 158, in process_inputs results.append(getattr(obj, func)(**inputs))

File "ComfyUI/nodes.py", line 1434, in sample return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)

File "ComfyUI/nodes.py", line 1401, in common_ksampler samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

File "ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/sample_error_enhancer.py", line 9, in informative_sample return original_sample(*args, **kwargs) # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.

File "ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/animatediff/sampling.py", line 313, in motion_sample return orig_comfy_sample(model, noise, *args, **kwargs)

File "ComfyUI/comfy/sample.py", line 43, in sample samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

File "ComfyUI/comfy/samplers.py", line 829, in sample return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

File "ComfyUI/comfy/samplers.py", line 729, in sample return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

File "ComfyUI/comfy/samplers.py", line 716, in sample output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

File "ComfyUI/comfy/samplers.py", line 695, in inner_sample samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

File "ComfyUI/comfy/samplers.py", line 600, in sample samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context return func(*args, **kwargs)

File "ComfyUI/comfy/k_diffusion/sampling.py", line 155, in sample_euler denoised = model(x, sigma_hat * s_in, **extra_args)

File "ComfyUI/comfy/samplers.py", line 299, in call out = self.inner_model(x, sigma, model_options=model_options, seed=seed)

File "ComfyUI/comfy/samplers.py", line 682, in call return self.predict_noise(*args, **kwargs)

File "ComfyUI/comfy/samplers.py", line 685, in predict_noise return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)

File "ComfyUI/comfy/samplers.py", line 279, in sampling_function out = calc_cond_batch(model, conds, x, timestep, model_options)

File "ComfyUI/comfy/samplers.py", line 202, in calc_cond_batch c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))

File "ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 468, in get_control_inject return self.get_control_advanced(x_noisy, t, cond, batched_number)

File "ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 32, in get_control_advanced return self.sliding_get_control(x_noisy, t, cond, batched_number)

File "ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/control.py", line 79, in sliding_get_control return self.control_merge(None, control, control_prev, output_dtype)

File "ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/adv_control/utils.py", line 575, in control_merge_inject x = control_output[i]
## System Information
- **ComfyUI Version:** v0.2.2-92-ge5ecdfd
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.0+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25386352640
  - **VRAM Free:** 22068404756
  - **Torch VRAM Total:** 3087007744
  - **Torch VRAM Free:** 359014932

## Logs
2024-10-07 12:03:55,124 - root - INFO - Total VRAM 24210 MB, total RAM 1031716 MB 2024-10-07 12:03:55,124 - root - INFO - pytorch version: 2.3.0+cu121 2024-10-07 12:03:55,125 - root - INFO - Set vram state to: NORMAL_VRAM 2024-10-07 12:03:55,125 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync 2024-10-07 12:03:56,396 - root - INFO - Using pytorch cross attention 2024-10-07 12:03:57,466 - root - INFO - [Prompt Server] web root: ComfyUI/web 2024-10-07 12:03:57,996 - root - WARNING - Traceback (most recent call last): File "ComfyUI/nodes.py", line 1998, in load_custom_node module_spec.loader.exec_module(module) File "<frozen importlib._bootstrap_external>", line 883, in exec_module File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed File "ComfyUI/comfy_extras/nodes_audio.py", line 1, in <module> import torchaudio File "/usr/local/lib/python3.10/dist-packages/torchaudio/init.py", line 2, in <module> from . import _extension # noqa # usort: skip File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/init.py", line 38, in <module> _load_lib("libtorchaudio") File "/usr/local/lib/python3.10/dist-packages/torchaudio/_extension/utils.py", line 60, in _load_lib torch.ops.load_library(path) File "/usr/local/lib/python3.10/dist-packages/torch/_ops.py", line 1032, in load_library ctypes.CDLL(path) File "/usr/lib/python3.10/ctypes/init.py", line 374, in init self._handle = _dlopen(self._name, mode) OSError: /usr/local/lib/python3.10/dist-packages/torchaudio/lib/libtorchaudio.so: undefined symbol: _ZNK3c105Error4whatEv

202
```

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Advanced-ControlNet repo.
https://github.com/Kosinkadink/ComfyUI-Advanced-ControlNet
