### ISSUE TITLE
AV_ControlNetPreprocessor list index out of range

### ISSUE THREAD

**Issue by CrimoMX** [comfyanonymous/ComfyUI#5195]
### Expected Behavior

Well, I'm trying to use openpose preprocessor and it wont't work

### Actual Behavior

It gets me this error: 
![image](https://github.com/user-attachments/assets/d455a303-50ee-4893-ae2c-6c7e864ff796)

### Steps to Reproduce

When you try to queue your prompt, you'll get this error.
![image](https://github.com/user-attachments/assets/60e227e0-838e-4176-a8c3-462070f17463)
![image](https://github.com/user-attachments/assets/c8c6f962-5e26-420e-afcc-a2ac57540691)

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** AV_ControlNetPreprocessor
- **Exception Type:** IndexError
- **Exception Message:** list index out of range
## Stack Trace

  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2-94-g614377a
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 10736893952
  - **VRAM Free:** 9423405056
  - **Torch VRAM Total:** 167772160
  - **Torch VRAM Free:** 142458880

## Logs
```
2024-10-09 12:09:10,730 - root - INFO - Total VRAM 10240 MB, total RAM 49071 MB
2024-10-09 12:09:10,730 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-09 12:09:10,731 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-09 12:09:10,731 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
2024-10-09 12:09:11,536 - root - INFO - Using pytorch cross attention
2024-10-09 12:09:12,705 - root - INFO - [Prompt Server] web root: D:\ComfyUI\ComfyUI\web
2024-10-09 12:09:14,505 - root - INFO - 
Import times for custom nodes:
2024-10-09 12:09:14,505 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-09 12:09:14,505 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-09 12:09:14,506 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-09 12:09:14,506 - root - INFO -    0.1 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-09 12:09:14,506 - root - INFO -    0.5 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-09 12:09:14,506 - root - INFO -    0.6 seconds: D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture
2024-10-09 12:09:14,506 - root - INFO - 
2024-10-09 12:09:14,515 - root - INFO - Starting server

2024-10-09 12:09:14,515 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-09 12:11:17,389 - root - INFO - got prompt
2024-10-09 12:11:17,483 - root - INFO - Prompt executed in 0.09 seconds
2024-10-09 12:12:30,597 - root - INFO - got prompt
2024-10-09 12:12:30,692 - root - INFO - Prompt executed in 0.09 seconds
2024-10-09 12:14:04,352 - root - INFO - got prompt
2024-10-09 12:14:04,466 - root - INFO - Prompt executed in 0.11 seconds
2024-10-09 12:14:42,304 - root - INFO - got prompt
2024-10-09 12:15:23,866 - root - INFO - got prompt
2024-10-09 12:15:27,064 - root - INFO - got prompt
2024-10-09 12:15:40,715 - root - INFO - Prompt executed in 58.41 seconds
2024-10-09 12:15:40,938 - root - INFO - Prompt executed in 0.07 seconds
2024-10-09 12:15:40,942 - root - INFO - Prompt executed in 0.00 seconds
2024-10-09 12:15:55,031 - root - INFO - got prompt
2024-10-09 12:16:00,197 - root - INFO - Prompt executed in 5.16 seconds
2024-10-09 12:19:53,098 - root - INFO - got prompt
2024-10-09 12:19:54,456 - root - INFO - Prompt executed in 1.36 seconds
2024-10-09 12:20:20,659 - root - INFO - got prompt
2024-10-09 12:20:33,473 - root - INFO - Prompt executed in 12.81 seconds
2024-10-09 12:20:52,205 - root - INFO - got prompt
2024-10-09 12:20:52,263 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-10-09 12:20:52,281 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-10-09 12:20:52,282 - root - INFO - Prompt executed in 0.08 seconds
2024-10-09 12:22:52,350 - root - INFO - got prompt
2024-10-09 12:22:52,356 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-10-09 12:22:52,357 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-10-09 12:22:52,358 - root - INFO - Prompt executed in 0.01 seconds
2024-10-09 12:24:22,119 - root - INFO - got prompt
2024-10-09 12:24:22,172 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-10-09 12:24:22,173 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-10-09 12:24:22,174 - root - INFO - Prompt executed in 0.05 seconds
2024-10-09 12:24:45,650 - root - INFO - got prompt
2024-10-09 12:24:45,674 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-10-09 12:24:45,676 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-10-09 12:24:45,676 - root - INFO - Prompt executed in 0.02 seconds
2024-10-09 12:25:00,308 - root - INFO - got prompt
2024-10-09 12:25:00,315 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-10-09 12:25:00,315 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-10-09 12:25:00,316 - root - INFO - Prompt executed in 0.01 seconds
2024-10-09 12:25:34,067 - root - INFO - got prompt
2024-10-09 12:25:34,074 - root - ERROR - !!! Exception during processing !!! list index out of range
2024-10-09 12:25:34,075 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in apply_preprocessor
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\custom_nodes\comfyui-art-venture\modules\controlnet\__init__.py", line 43, in <dictcomp>
    preprocessor_args.update({key: default_args[i + len(required_args)] for i, key in enumerate(optional_args)})
                                   ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range

2024-10-09 12:25:34,076 - root - INFO - Prompt executed in 0.01 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":5,"last_link_id":3,"nodes":[{"id":5,"type":"SaveImage","pos":{"0":891,"1":137},"size":[484.47177218419233,474.6511762996172],"flags":{},"order":2,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":3}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":2,"type":"LoadImage","pos":{"0":39,"1":149},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["00000-3180268910.png","image"]},{"id":1,"type":"AV_ControlNetPreprocessor","pos":{"0":502,"1":152},"size":{"0":315,"1":150},"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[3],"slot_index":0},{"name":"CNET_NAME","type":"STRING","links":null}],"properties":{"Node name for S&R":"AV_ControlNetPreprocessor"},"widgets_values":["openpose","sdxl",1024,"None"]}],"links":[[1,2,0,1,0,"IMAGE"],[3,1,0,5,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[51.558867464245225,171.03189865155468]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ErnieAllen** [comment]
This error also happens if you use the Flux Negative Prompt Placeholder to feed the negative conditioning into the ApplyControlNet node. Using an empty clip text encode node solved it for me.

**Comment by ltdrdata** [comment]
> This error also happens if you use the Flux Negative Prompt Placeholder to feed the negative conditioning into the ApplyControlNet node. Using an empty clip text encode node solved it for me.

The 'Negative Prompt Placeholder' node is a specialized node meant for samplers in the Impact/Inspire Pack. It should not be applied to ApplyControlNet and other nodes.
It can only be used with the samplers and detailers from the Impact/Inspire Pack.
