### ISSUE TITLE
V100  dtype error!

### ISSUE THREAD

**Issue by tendrillion** [comfyanonymous/ComfyUI#5202]
### Expected Behavior

work well

### Actual Behavior

RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: c10::Half key.dtype: c10::BFloat16 and value.dtype: c10::BFloat16 instead.

### Steps to Reproduce

Platform: Linux
Python version: 3.10.12
pytorch version: 2.2.2+cu121
xformers version: 0.0.25.post1
Device: Tesla V100-SXM2-32GB 
ComfyUI Revision: 2733 [3bb4dec7] | Released on '2024-09-28'

### Debug Logs

```powershell
Using xformers attention in VAE
Using xformers attention in VAE
clip missing: ['text_projection.weight']
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type FLOW
Is model already patched? False
It looks like you are trying to rescale already rescaled images. If the input images have pixel values between 0 and 1, set `do_rescale=False` to avoid rescaling them again.
We are patching diffusion model, be patient please
Patched succesfully!
Requested to load Flux
Loading 1 new model
loaded completely 0.0 12252.515686035156 True
Sampling:   0%|                                                                                                        | 0/25 [00:00<?, ?it/s]
!!! Exception during processing !!! Expected query, key, and value to have the same dtype, but got query.dtype: c10::Half key.dtype: c10::BFloat16 and value.dtype: c10::BFloat16 instead.
Traceback (most recent call last):
  File "/home/admin123/repository/aigc/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/admin123/repository/aigc/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/admin123/repository/aigc/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/admin123/repository/aigc/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/nodes.py", line 411, in sampling
    x = denoise(
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/sampling.py", line 193, in denoise
    pred = model_forward(
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/sampling.py", line 51, in model_forward
    img, txt = block(img=img, txt=txt, vec=vec, pe=pe)
  File "/home/admin123/venv/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/venv/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/xflux/src/flux/modules/layers.py", line 297, in forward
    return self.processor(self, img, txt, vec, pe)
  File "/home/admin123/venv/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/venv/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/layers.py", line 375, in forward
    self.shift_ip(img_q, attn, img)
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/layers.py", line 304, in shift_ip
    x += block(img_qkv, attn)
  File "/home/admin123/venv/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/admin123/venv/sd/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/admin123/repository/aigc/ComfyUI/custom_nodes/x-flux-comfyui/layers.py", line 257, in forward
    ip_attention = F.scaled_dot_product_attention(
RuntimeError: Expected query, key, and value to have the same dtype, but got query.dtype: c10::Half key.dtype: c10::BFloat16 and value.dtype: c10::BFloat16 instead.
```

**Comment by ltdrdata** [comment]
Please move this issue to x-flux-comfyui repo.
https://github.com/XLabs-AI/x-flux-comfyui
