### ISSUE TITLE
time out error

### ISSUE THREAD

**Issue by brianzz462** [comfyanonymous/ComfyUI#5203]
Traceback (most recent call last):
  File "F:\AI_install\image generation\comfyui\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI_install\image generation\comfyui\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI_install\image generation\comfyui\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI_install\image generation\comfyui\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\AI_install\image generation\comfyui\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 200, in tag
    tags.append(wait_for_async(lambda: tag(image, model, threshold, character_threshold, exclude_tags, replace_underscore, trailing_comma)))
  File "F:\AI_install\image generation\comfyui\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 214, in wait_for_async
    loop.run_until_complete(run_async())
  File "C:\Users\brian\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "F:\AI_install\image generation\comfyui\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 204, in run_async
    r = await async_fn()
  File "F:\AI_install\image generation\comfyui\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 55, in tag
    await download_model(model_name, client_id, node)
  File "F:\AI_install\image generation\comfyui\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\wd14tagger.py", line 129, in download_model
    await download_to_file(
  File "F:\AI_install\image generation\comfyui\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger\pysssss.py", line 186, in download_to_file
    async for chunk in response.content.iter_chunked(2048):
  File "F:\AI_install\image generation\comfyui\ComfyUI\.venv\lib\site-packages\aiohttp\streams.py", line 50, in __anext__
    rv = await self.read_func()
  File "F:\AI_install\image generation\comfyui\ComfyUI\.venv\lib\site-packages\aiohttp\streams.py", line 396, in read
    await self._wait("read")
  File "F:\AI_install\image generation\comfyui\ComfyUI\.venv\lib\site-packages\aiohttp\streams.py", line 314, in _wait
    with self._timer:
  File "F:\AI_install\image generation\comfyui\ComfyUI\.venv\lib\site-packages\aiohttp\helpers.py", line 736, in __exit__
    raise asyncio.TimeoutError from exc_val
asyncio.exceptions.TimeoutError 

how do stop it from erroring out at 5 minutes

**Comment by ltdrdata** [comment]
First of all, this issue is related to a custom node and has nothing to do with ComfyUI itself.
And this issue generally occurs when your network is too slow to fetch the model file within the time limit.
Go to the custom node repository and ask about how to manually download and save the model file.

https://github.com/pythongosssss/ComfyUI-WD14-Tagger

**Comment by brianzz462** [comment]
> First of all, this issue is related to a custom node and has nothing to do with ComfyUI itself. And this issue generally occurs when your network is too slow to fetch the model file within the time limit. Go to the custom node repository and ask about how to manually download and save the model file.
> 
> https://github.com/pythongosssss/ComfyUI-WD14-Tagger

i only asked here because this was where it sent me from the error message and i did manually download it but it deletes it when i use the custom node wd tagger  thank you for the help

**Comment by brianzz462** [comment]
> First of all, this issue is related to a custom node and has nothing to do with ComfyUI itself. And this issue generally occurs when your network is too slow to fetch the model file within the time limit. Go to the custom node repository and ask about how to manually download and save the model file.
> 
> https://github.com/pythongosssss/ComfyUI-WD14-Tagger

thank you again i didnt have the .csv file with the model hope you have a wonderful day
