### ISSUE TITLE
What is this error I'm getting now when I launch ComfyUI?

### ISSUE THREAD

**Issue by SinMxchine** [comfyanonymous/ComfyUI#5209]
### Your question

I was using ComfyUI from 9 months now and about a week ago after installing ComfyUI for "FLEX" I can no longer launch it without getting this error. It just closes and won't launch.

What is this error and does anyone know how to fix it?

### Logs

```powershell
E:\AI\SDAI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-10 12:37:34.964686
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: E:\AI\SDAI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\AI\SDAI\ComfyUI_windows_portable\ComfyUI
** Log path: E:\AI\SDAI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   1.2 seconds: E:\AI\SDAI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 32532 MB
pytorch version: 2.1.2+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "E:\AI\SDAI\ComfyUI_windows_portable\ComfyUI\main.py", line 90, in <module>
    import execution
  File "E:\AI\SDAI\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "E:\AI\SDAI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 22, in <module>
    import comfy.samplers
  File "E:\AI\SDAI\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 9, in <module>
    import scipy.stats
  File "E:\AI\SDAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\scipy\stats\__init__.py", line 608, in <module>
    from ._stats_py import *
  File "E:\AI\SDAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\scipy\stats\_stats_py.py", line 46, in <module>
    from . import distributions
  File "E:\AI\SDAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "E:\AI\SDAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\scipy\stats\_continuous_distns.py", line 33, in <module>
    import scipy.stats._boost as _boost
  File "E:\AI\SDAI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\scipy\stats\_boost\__init__.py", line 13, in <module>
    from scipy.stats._boost.nbinom_ufunc import (
ImportError: DLL load failed while importing nbinom_ufunc: %1 is not a valid Win32 application.

E:\AI\SDAI\ComfyUI_windows_portable>pause
Press any key to continue . . .
```

**Comment by LukeG89** [comment]
Have you tried upgrading ComfyUI using `update_comfyui_and_python_dependencies.bat` inside `update` folder?

That should also upgrade your outdated Pytorch to the current stable version 2.4.1+cu124.

**Comment by SinMxchine** [comment]
> Have you tried upgrading ComfyUI using `update_comfyui_and_python_dependencies.bat` inside `update` folder?
> 
> That should also upgrade your outdated Pytorch to the current stable version 2.4.1+cu124.

I didn't even know we had an update .bat. Thank you for letting me know. I ran it and now it works! Thank you!
