### ISSUE TITLE
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by prog-ape** [comfyanonymous/ComfyUI#5217]
### Expected Behavior

flux-dev img2img

### Actual Behavior

!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "/home/ai/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ai/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ai/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ai/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ai/ComfyUI/custom_nodes/masquerade-nodes-comfyui/MaskNodes.py", line 481, in mix
    return (image1 * (1. - mask) + image2 * mask,)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Steps to Reproduce

python main.py --front-end-version Comfy-Org/ComfyUI_frontend@latest --gpu-only --verbose
This exception will occur after adding --gpu-only to the startup parameter

### Debug Logs

```powershell
!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "/home/ai/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ai/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/home/ai/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ai/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/home/ai/ComfyUI/custom_nodes/masquerade-nodes-comfyui/MaskNodes.py", line 481, in mix
    return (image1 * (1. - mask) + image2 * mask,)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

**Comment by ltdrdata** [comment]
Please move this issue to masquerade-nodes-comfyui.
https://github.com/BadCafeCode/masquerade-nodes-comfyui
