### ISSUE TITLE
The UI structure of the canvas has changed after the update. I don’t know if it conflicts with other plug-ins or with new functions.

### ISSUE THREAD

**Issue by cgl13207205048** [comfyanonymous/ComfyUI#5221]
### Expected Behavior

Please help check whether the updated content conflicts with interface-related content.

### Actual Behavior

![微信图片_20241012140150](https://github.com/user-attachments/assets/e1b6e237-add7-469e-9e6a-cb106a879b65)

### Steps to Reproduce

![微信图片_20241012140150](https://github.com/user-attachments/assets/b94ceb86-9916-457a-b3b9-7bf2a96db977)
When you click on the queue, the UI interface will shake.The black gap will also become wider

### Debug Logs

```powershell
F:\ComfyUI>set http_proxy=http://127.0.0.1:7897

F:\ComfyUI>set https_proxy=http://127.0.0.1:7897

F:\ComfyUI>call E:\Anaconda\Scripts\activate.bat comfyui
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-12 13:55:24.109811
** Platform: Windows
** Python version: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
** Python executable: E:\Anaconda\envs\comfyui\python.exe
** ComfyUI Path: F:\ComfyUI
** Log path: F:\ComfyUI\comfyui.log
[34m[MaraScott] [92mInitialization[0m

Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI\custom_nodes\rgthree-comfy-main
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes
   3.7 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65349 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: F:\ComfyUI\web
Adding extra search path checkpoints H:\stable-diffusion-webui/models/Stable-diffusion
Adding extra search path configs H:\stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae H:\stable-diffusion-webui/models/VAE
Adding extra search path loras H:\stable-diffusion-webui/models/Lora
Adding extra search path loras H:\stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models H:\stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models H:\stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models H:\stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings H:\stable-diffusion-webui/embeddings
Adding extra search path hypernetworks H:\stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet H:\stable-diffusion-webui/models/ControlNet
Web extensions folder found at F:\ComfyUI\web\extensions\ComfyLiterals
[92m[Allor][0m: 0 nodes were overridden.
[92m[Allor][0m: 12 modules were enabled.
[92m[Allor][0m: 98 nodes were loaded.
[AnimateDiff] - [0;33mWARNING[0m - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[AnimateDiff] - [0;31mERROR[0m - No models available. Please download one and put it in models folder
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
F:\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\ComfyUI-Anyline\__init__.py", line 1, in <module>
    from .anyline import AnyLine
  File "F:\ComfyUI\custom_nodes\ComfyUI-Anyline\anyline.py", line 9, in <module>
    from custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed import TEDDetector
ImportError: cannot import name 'TEDDetector' from 'custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed' (unknown location)

Cannot import F:\ComfyUI\custom_nodes\ComfyUI-Anyline module for custom nodes: cannot import name 'TEDDetector' from 'custom_nodes.comfyui_controlnet_aux.src.controlnet_aux.teed' (unknown location)
Adding F:\ComfyUI\custom_nodes to sys.path
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
Loaded Efficiency nodes from F:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from F:\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from F:\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Loaded IPAdapter nodes from F:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from F:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.9)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
### Loading: ComfyUI-Impact-Pack (V7.9)
Loaded ImpactPack nodes from F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
[Crystools [0;32mINFO[0m] Crystools version: 1.19.0
[Crystools [0;32mINFO[0m] CPU: 13th Gen Intel(R) Core(TM) i5-13600KF - Arch: AMD64 - OS: Windows 10
[Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
[Crystools [0;32mINFO[0m] GPU/s:
[Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 3090
[Crystools [0;32mINFO[0m] NVIDIA Driver: 560.94
documents.core.js found at F:\ComfyUI\custom_nodes\ComfyUI-Documents\web\js\documents.core.js
[34m[ComfyUI-Easy-Use] server: [0mv1.2.4 [92mLoaded[0m
[34m[ComfyUI-Easy-Use] web root: [0mF:\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 [92mLoaded[0m
Total VRAM 24576 MB, total RAM 65349 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.27
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
[33mUnable to import guidedFilter, make sure you have only opencv-contrib-python or run the import_error_install.bat script[m
### Loading: ComfyUI-Impact-Pack (V7.9)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.3)
A new version of Albumentations is available: 1.4.18 (you have 1.4.11). Upgrade using: pip install --upgrade albumentations
[94mtheUpsiders Logic Nodes: [92mLoaded[0m
### Loading: ComfyUI-Manager (V2.51.7)
### ComfyUI Revision: 2756 [6632365e] | Released on '2024-10-11'
json_repair## OK
--------------
[91m ### Mixlab Nodes: [93mLoaded
ChatGPT.available True
edit_mask.available True
simple_lama_inpainting## OK
LaMaInpainting.available True
## clip_interrogator_model not found: F:\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: F:\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: F:\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Scenedetect.available
FishSpeech.available
SenseVoice.available
Whisper.available False
[93m -------------- [0m
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Nvidia APEX normalization not installed, using PyTorch LayerNorm
Failed to auto update `Quality of Life Suit`
[33mQualityOfLifeSuit_Omar92_DIR:[0m F:\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[0;33m[ReActor][0m - [38;5;173mSTATUS[0m - [0;32mRunning v0.5.1-a4 in ComfyUI[0m
Torch version: 2.3.1+cu121
Traceback (most recent call last):
  File "F:\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI\custom_nodes\ComfyUI-Snap_Processing\__init__.py", line 2, in <module>
    from .Snap_canvas import PyQtCanvasNode
  File "F:\ComfyUI\custom_nodes\ComfyUI-Snap_Processing\Snap_canvas.py", line 3, in <module>
    from PyQt5.QtCore import QEventLoop
ModuleNotFoundError: No module named 'PyQt5'

Cannot import F:\ComfyUI\custom_nodes\ComfyUI-Snap_Processing module for custom nodes: No module named 'PyQt5'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: AzureExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Workspace manager - Openning file hash dict
🦄🦄Loading: Workspace Manager (V2.1.0)

[1mFrom Bmad Custom Nodes[0m
 [92mLoaded 125 nodes:
  + api nodes (14)
  + simple utility nodes (58)
  + CV nodes (50)
  + color clip ade20k node (1)
  + extension dependent nodes (2)
[0m
------------------------------------------
[34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[1;35m### [START] ComfyUI AlekPet Nodes [1;34mv1.0.29.1[0m[1;35m ###[0m
[92mNode -> ArgosTranslateNode: [93mArgosTranslateCLIPTextEncodeNode, ArgosTranslateTextNode[0m [92m[Loading] [0m
[92mNode -> DeepTranslatorNode: [93mDeepTranslatorCLIPTextEncodeNode, DeepTranslatorTextNode[0m [92m[Loading] [0m
[92mNode -> GoogleTranslateNode: [93mGoogleTranslateCLIPTextEncodeNode, GoogleTranslateTextNode[0m [92m[Loading] [0m
[92mNode -> PoseNode: [93mPoseNode[0m [92m[Loading] [0m
[92mNode -> ExtrasNode: [93mPreviewTextNode, HexToHueNode, ColorsCorrectNode[0m [92m[Loading] [0m
[92mNode -> IDENode: [93mIDENode[0m [92m[Loading] [0m
[92mNode -> PainterNode: [93mPainterNode[0m [92m[Loading] [0m
[1;35m### [END] ComfyUI AlekPet Nodes ###[0m
LOADED 6 FONTS
No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'


███╗   ███╗ █████╗  ██████╗██╗  ██╗██╗███╗   ██╗███████╗
████╗ ████║██╔══██╗██╔════╝██║  ██║██║████╗  ██║██╔════╝
██╔████╔██║███████║██║     ███████║██║██╔██╗ ██║█████╗
██║╚██╔╝██║██╔══██║██║     ██╔══██║██║██║╚██╗██║██╔══╝
██║ ╚═╝ ██║██║  ██║╚██████╗██║  ██║██║██║ ╚████║███████╗
╚═╝     ╚═╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝╚═╝  ╚═══╝╚══════╝

██████╗ ███████╗██╗     ██╗   ██╗███████╗██╗ ██████╗ ███╗   ██╗███████╗
██╔══██╗██╔════╝██║     ██║   ██║██╔════╝██║██╔═══██╗████╗  ██║██╔════╝
██║  ██║█████╗  ██║     ██║   ██║███████╗██║██║   ██║██╔██╗ ██║███████╗
██║  ██║██╔══╝  ██║     ██║   ██║╚════██║██║██║   ██║██║╚██╗██║╚════██║
██████╔╝███████╗███████╗╚██████╔╝███████║██║╚██████╔╝██║ ╚████║███████║
╚═════╝ ╚══════╝╚══════╝ ╚═════╝ ╚══════╝╚═╝ ╚═════╝ ╚═╝  ╚═══╝╚══════╝



[34mFizzleDorf Custom Nodes: [92mLoaded[0m
# 😺dzNodes: LayerStyle -> [1;33mCannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to [4mhttps://github.com/chflame163/ComfyUI_LayerStyle/issues/5[0m[m
# 😺dzNodes: LayerStyle -> [1;33mFind 1 LUTs in F:\ComfyUI\custom_nodes\ComfyUI_LayerStyle\lut[m
# 😺dzNodes: LayerStyle -> [1;33mFind 6 Fonts in F:\ComfyUI\custom_nodes\ComfyUI_LayerStyle\font[m
llama-cpp installed
Successfully installed py-cord[voice]
[34m[MaraScott] [92mLoaded[0m
# 😺dzNodes: WordCloud ->  find 142 fonts in C:\Windows\fonts
[36;20m[comfy_mtb] | INFO -> loaded [96m86[0m nodes successfuly[0m
[36;20m[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.[0m
Initializing ControlAltAI Nodes
WARNING: Could not find OPENAI_API_KEY in .env, disabling gpt prompt generation.
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[92m[rgthree] Loaded 40 epic nodes.[0m
[33m[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.[0m

[34mWAS Node Suite: [0mBlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.[0m
[34mWAS Node Suite: [0m`CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.[0m
[34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `F:\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m219[0m [32mnodes successfully.[0m

        [3m[93m"Art should disturb the comfortable and comfort the disturbed." - Cesar Cruz[0m


Import times for custom nodes:
   0.0 seconds: F:\ComfyUI\custom_nodes\rembg-comfyui-node-better
   0.0 seconds: F:\ComfyUI\custom_nodes\rembg-comfyui-node
   0.0 seconds: F:\ComfyUI\custom_nodes\style_aligned_comfy
   0.0 seconds: F:\ComfyUI\custom_nodes\AIGODLIKE-ComfyUI-Translation
   0.0 seconds: F:\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: F:\ComfyUI\custom_nodes\Skimmed_CFG
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-mxToolkit
   0.0 seconds: F:\ComfyUI\custom_nodes\Comfyui_TTP_Toolset
   0.0 seconds: F:\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: F:\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-FluxExt-MZ
   0.0 seconds: F:\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-IC-Light-Native
   0.0 seconds: F:\ComfyUI\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui_storydiffusion
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Logic
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_DeepFakeDefenders
   0.0 seconds: F:\ComfyUI\custom_nodes\Comfyui_joytag
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-YOLO
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-fitsize
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-BRIA_AI-RMBG
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: F:\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: F:\ComfyUI\custom_nodes\cg-image-picker
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Alimama-ControlNet-compatible
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Tara-LLM-Integration
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_experiments
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_densediffusion
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-ollama-prompt-encode
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-eesahesNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-enricos-nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\wlsh_nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-lama-remover
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: F:\ComfyUI\custom_nodes\MistoControlNet-Flux-dev
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
   0.0 seconds (IMPORT FAILED): F:\ComfyUI\custom_nodes\ComfyUI-Snap_Processing
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-portrait-master
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: F:\ComfyUI\custom_nodes\ControlAltAI-Nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Kolors-MZ
   0.0 seconds: F:\ComfyUI\custom_nodes\DistanceSampler
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-hiforce-plugin
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-AutoCropFaces
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: F:\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Image-Filters
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: F:\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_omost
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: F:\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
   0.0 seconds: F:\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-various
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-KwaiKolorsWrapper
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-JDCN
   0.0 seconds: F:\ComfyUI\custom_nodes\rgthree-comfy-main
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-MimicMotionWrapper
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-IC-Light
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui_bmad_nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\OneButtonPrompt
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis
   0.0 seconds: F:\ComfyUI\custom_nodes\eden_comfy_pipelines
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_ProPainter_Nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\EasyAnimate
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_WordCloud
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_MS_Diffusion
   0.0 seconds: F:\ComfyUI\custom_nodes\CharacterFaceSwap
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_smZNodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_NYJY
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-workspace-manager
   0.0 seconds: F:\ComfyUI\custom_nodes\comfy_mtb
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI_MaraScott_Nodes
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-FluxTrainer
   0.0 seconds: F:\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: F:\ComfyUI\custom_nodes\comfyui_segment_anything
   0.1 seconds: F:\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Documents
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyUI-UltraPixel
   0.1 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Gemini
   0.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI_Fill-Nodes
   0.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI-IF_AI_tools
   0.2 seconds (IMPORT FAILED): F:\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.3 seconds: F:\ComfyUI\custom_nodes\ComfyUI-SUPIR
   0.3 seconds: F:\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   0.3 seconds: F:\ComfyUI\custom_nodes\comfyui-ollama
   0.4 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.5 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Allor
   0.6 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes
   0.7 seconds: F:\ComfyUI\custom_nodes\ComfyUI-BrushNet
   1.2 seconds: F:\ComfyUI\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
   1.5 seconds: F:\ComfyUI\custom_nodes\was-node-suite-comfyui
   1.6 seconds: F:\ComfyUI\custom_nodes\comfyui-art-venture
   1.9 seconds: F:\ComfyUI\custom_nodes\CosyVoice-ComfyUI
   2.0 seconds: F:\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   5.8 seconds: F:\ComfyUI\custom_nodes\comfyui_LLM_party

Starting server

To see the GUI go to: http://127.0.0.1:8188
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: F:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
[33mQualityOfLifeSuit_Omar92:[0m:NSP ready
[36;20m[comfy_mtb] | INFO -> Found multiple match, we will pick the last H:\stable-diffusion-webui/models/SwinIR
['F:\\ComfyUI\\models\\upscale_models', 'H:\\stable-diffusion-webui/models/ESRGAN', 'H:\\stable-diffusion-webui/models/RealESRGAN', 'H:\\stable-diffusion-webui/models/SwinIR'][0m
[33;20m[comfy_mtb] | WARNING -> Face restoration models not found.[0m
[]
[]
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
F:\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
[]
[]
got prompt
Using xformers attention in VAE
Using xformers attention in VAE
# 😺dzNodes: LayerStyle -> [1;32mImageScaleByAspectRatio V2 Processed 1 image(s).[m
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
clip missing: ['text_projection.weight']
Requested to load ControlNetFlux
Requested to load Flux
Loading 2 new models
loaded completely 0.0 4083.416015625 True
loaded completely 0.0 11350.048889160156 True
  0%|                                                                                           | 0/30 [00:00<?, ?it/s]Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [01:04<00:00,  2.16s/it]
Prompt executed in 85.27 seconds
```

**Comment by huchenlei** [comment]
Try disable mixlab nodes.

**Comment by cgl13207205048** [comment]
> Try disable mixlab nodes. If issue not resolved, you can use https://github.com/Comfy-Org/comfy-cli#bisect-custom-nodes to bisect which custom node cause the issue.
排查了不是mixlab的问题，comfy-cli这个不会用啊
