### ISSUE TITLE
Problem with ComfyUI workflow "ControlNetApplySD3  'NoneType' object has no attribute 'copy'"

### ISSUE THREAD

**Issue by ABSOMA021085** [comfyanonymous/ComfyUI#5229]
### Your question

I get the following error when running the workflow

I leave a video of what I am working on as a reference.

https://www.youtube.com/watch?v=MbQv8zoNEfY

video of reference

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** ControlNetApplySD3
- **Exception Type:** AttributeError
- **Exception Message:** 'NoneType' object has no attribute 'copy'
## Stack Trace

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 848, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
            ^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3-3-g6632365
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25769148416
  - **VRAM Free:** 19327837688
  - **Torch VRAM Total:** 5100273664
  - **Torch VRAM Free:** 57107960

## Logs
```
2024-10-12 11:47:24,318 - root - INFO - Total VRAM 24575 MB, total RAM 65461 MB
2024-10-12 11:47:24,318 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-12 11:47:24,318 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-12 11:47:24,318 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-10-12 11:47:26,738 - root - INFO - Using pytorch cross attention
2024-10-12 11:47:32,778 - root - INFO - [Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
2024-10-12 11:47:36,818 - root - INFO - Total VRAM 24575 MB, total RAM 65461 MB
2024-10-12 11:47:36,818 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-12 11:47:36,818 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-12 11:47:36,818 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
2024-10-12 11:47:37,468 - root - INFO - 
Import times for custom nodes:
2024-10-12 11:47:37,468 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-12 11:47:37,468 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-12 11:47:37,468 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-12 11:47:37,468 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-10-12 11:47:37,468 - root - INFO -    0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-12 11:47:37,468 - root - INFO -    0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-12 11:47:37,468 - root - INFO -    0.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-12 11:47:37,468 - root - INFO -    0.3 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-eesahesNodes
2024-10-12 11:47:37,468 - root - INFO -    0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-12 11:47:37,468 - root - INFO -    0.4 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-12 11:47:37,468 - root - INFO -    1.1 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-10-12 11:47:37,468 - root - INFO - 
2024-10-12 11:47:37,478 - root - INFO - Starting server

2024-10-12 11:47:37,478 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-12 12:16:10,093 - root - INFO - got prompt
2024-10-12 12:16:10,103 - root - ERROR - Failed to validate prompt for output 147:
2024-10-12 12:16:10,103 - root - ERROR - * UpscaleModelLoader 83:
2024-10-12 12:16:10,103 - root - ERROR -   - Value not in list: model_name: '4x-ClearRealityV1.pth' not in ['ClearRealityV1\\4x-ClearRealityV1.pth', 'ClearRealityV1\\4x-ClearRealityV1_Soft.pth', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1-fp16.bin', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1-fp32.bin', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1_Soft-fp16.bin', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1_Soft-fp32.bin']
2024-10-12 12:16:10,103 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,103 - root - ERROR - Failed to validate prompt for output 321:
2024-10-12 12:16:10,103 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,103 - root - ERROR - Failed to validate prompt for output 311:
2024-10-12 12:16:10,103 - root - ERROR - * InstantX Flux Union ControlNet Loader 334:
2024-10-12 12:16:10,103 - root - ERROR -   - Value not in list: control_net_name: 'flux\InstantX_flux.safetensors' not in ['flux-canny-controlnet-v3.safetensors', 'flux-canny-controlnet.safetensors', 'flux-canny-controlnet_v2.safetensors', 'flux-depth-controlnet-v3.safetensors', 'flux-depth-controlnet.safetensors', 'flux-depth-controlnet_v2.safetensors', 'flux-hed-controlnet-v3.safetensors', 'flux-hed-controlnet.safetensors', 'flux\\diffusion_pytorch_model.safetensors']
2024-10-12 12:16:10,103 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,103 - root - ERROR - Failed to validate prompt for output 301:
2024-10-12 12:16:10,103 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 140:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 320:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 145:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 319:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 179:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 84:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 258:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,108 - root - ERROR - Failed to validate prompt for output 299:
2024-10-12 12:16:10,108 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 138:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 146:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 322:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 317:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 323:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 316:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 300:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 87:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 318:
2024-10-12 12:16:10,113 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,113 - root - ERROR - Failed to validate prompt for output 141:
2024-10-12 12:16:10,118 - root - ERROR - Output will be ignored
2024-10-12 12:16:10,647 - root - INFO - Using pytorch attention in VAE
2024-10-12 12:16:10,647 - root - INFO - Using pytorch attention in VAE
2024-10-12 12:16:18,202 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-10-12 12:16:18,202 - root - INFO - model_type FLUX
2024-10-12 12:27:11,335 - root - ERROR - error could not detect control model type.
2024-10-12 12:27:11,335 - root - ERROR - error checkpoint does not contain controlnet or t2i adapter data D:\ComfyUI_windows_portable\ComfyUI\models\controlnet\flux\diffusion_pytorch_model.safetensors
2024-10-12 12:27:13,290 - root - INFO - Requested to load FluxClipModel_
2024-10-12 12:27:13,294 - root - INFO - Loading 1 new model
2024-10-12 12:27:13,301 - root - INFO - loaded completely 0.0 4777.53759765625 True
2024-10-12 12:27:51,099 - root - WARNING - clip missing: ['text_projection.weight']
2024-10-12 12:27:52,730 - root - ERROR - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-10-12 12:27:52,745 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 848, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

2024-10-12 12:27:52,750 - root - INFO - Prompt executed in 702.63 seconds
2024-10-12 12:44:26,904 - root - INFO - got prompt
2024-10-12 12:44:26,917 - root - ERROR - Failed to validate prompt for output 147:
2024-10-12 12:44:26,917 - root - ERROR - * UpscaleModelLoader 83:
2024-10-12 12:44:26,917 - root - ERROR -   - Value not in list: model_name: '4x-ClearRealityV1.pth' not in ['ClearRealityV1\\4x-ClearRealityV1.pth', 'ClearRealityV1\\4x-ClearRealityV1_Soft.pth', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1-fp16.bin', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1-fp32.bin', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1_Soft-fp16.bin', 'ClearRealityV1\\BROKEN_NCNN\\4x-ClearRealityV1_Soft-fp32.bin']
2024-10-12 12:44:26,917 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,917 - root - ERROR - Failed to validate prompt for output 321:
2024-10-12 12:44:26,917 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,917 - root - ERROR - Failed to validate prompt for output 311:
2024-10-12 12:44:26,917 - root - ERROR - * InstantX Flux Union ControlNet Loader 334:
2024-10-12 12:44:26,917 - root - ERROR -   - Value not in list: control_net_name: 'flux\InstantX_flux.safetensors' not in ['flux-canny-controlnet-v3.safetensors', 'flux-canny-controlnet.safetensors', 'flux-canny-controlnet_v2.safetensors', 'flux-depth-controlnet-v3.safetensors', 'flux-depth-controlnet.safetensors', 'flux-depth-controlnet_v2.safetensors', 'flux-hed-controlnet-v3.safetensors', 'flux-hed-controlnet.safetensors', 'flux\\diffusion_pytorch_model.safetensors']
2024-10-12 12:44:26,917 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,917 - root - ERROR - Failed to validate prompt for output 301:
2024-10-12 12:44:26,917 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,917 - root - ERROR - Failed to validate prompt for output 140:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 320:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 145:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 319:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 179:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 84:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 258:
2024-10-12 12:44:26,922 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,922 - root - ERROR - Failed to validate prompt for output 299:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 138:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 146:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 322:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 317:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 323:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 316:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 300:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 87:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,927 - root - ERROR - Failed to validate prompt for output 318:
2024-10-12 12:44:26,927 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,932 - root - ERROR - Failed to validate prompt for output 141:
2024-10-12 12:44:26,932 - root - ERROR - Output will be ignored
2024-10-12 12:44:26,992 - root - ERROR - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-10-12 12:44:26,992 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 848, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'copy'

2024-10-12 12:44:26,997 - root - INFO - Prompt executed in 0.06 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

![Screenshot 2024-10-12 at 12-30-54 ComfyUI](https://github.com/user-attachments/assets/f0f76743-0561-4c02-8915-43143904b5b3)
![Screenshot 2024-10-12 at 12-29-58 ComfyUI](https://github.com/user-attachments/assets/91e3539f-aa8b-4e68-bd58-4c4894345ce3)

**Comment by ltdrdata** [comment]
ControlNetApplySD3 is deprecated.
Use Apply ControlNet instead.

Make sure your ComfyUI is up to date.

**Comment by doctorbinsibar** [comment]
hi had exactly the same problem its the problem for control net model you have to download the right one from here: 
https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro/tree/main

**Comment by ABSOMA021085** [comment]
> hi had exactly the same problem its the problem for control net model you have to download the right one from here: https://huggingface.co/Shakker-Labs/FLUX.1-dev-ControlNet-Union-Pro/tree/main

thank you very much my brother, have a great night, I send you a big hug.
