### ISSUE TITLE
XlabsSampler

### ISSUE THREAD

**Issue by Brick-test1** [comfyanonymous/ComfyUI#5243]
### Your question

I run flow, but it error can you help me. plz!
 ComfyUI Flux (ControlNet) Workflow: Replacing Background for Anything (Portrait, Product, etc.)

Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
Input tensor shape: torch.Size([1, 16, 75, 150]). Additional info: {'ph': 2, 'pw': 2}.
Shape mismatch, can't divide axis of length 75 in chunks of 2

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** XlabsSampler
- **Exception Type:** einops.EinopsError
- **Exception Message:**  Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
 Input tensor shape: torch.Size([1, 16, 75, 150]). Additional info: {'ph': 2, 'pw': 2}.
 Shape mismatch, can't divide axis of length 75 in chunks of 2
## Stack Trace

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 458, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 258, in denoise_controlnet
    orig_image = rearrange(orig_image, "b c (h ph) (w pw) -> b (h w) (c ph pw)", ph=2, pw=2).to(img.device, dtype = img.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))

```
## System Information
- **ComfyUI Version:** v0.2.2-85-gd985d1d
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589475840
  - **VRAM Free:** 1864014176
  - **Torch VRAM Total:** 5737807872
  - **Torch VRAM Free:** 160078176

## Logs
```
2024-10-14 15:21:17,852 - root - INFO - Total VRAM 8192 MB, total RAM 65468 MB
2024-10-14 15:21:17,852 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-14 15:21:17,861 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-14 15:21:17,862 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
2024-10-14 15:21:18,765 - root - INFO - Using pytorch cross attention
2024-10-14 15:21:19,887 - root - INFO - [Prompt Server] web root: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\web
2024-10-14 15:21:19,889 - root - INFO - Adding extra search path checkpoints H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/Stable-diffusion
2024-10-14 15:21:19,889 - root - INFO - Adding extra search path configs H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/Stable-diffusion
2024-10-14 15:21:19,890 - root - INFO - Adding extra search path vae H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/VAE
2024-10-14 15:21:19,890 - root - INFO - Adding extra search path loras H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/Lora
2024-10-14 15:21:19,890 - root - INFO - Adding extra search path loras H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/LyCORIS
2024-10-14 15:21:19,890 - root - INFO - Adding extra search path upscale_models H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/ESRGAN
2024-10-14 15:21:19,890 - root - INFO - Adding extra search path upscale_models H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/RealESRGAN
2024-10-14 15:21:19,892 - root - INFO - Adding extra search path upscale_models H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/SwinIR
2024-10-14 15:21:19,892 - root - INFO - Adding extra search path embeddings H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\embeddings
2024-10-14 15:21:19,892 - root - INFO - Adding extra search path hypernetworks H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/hypernetworks
2024-10-14 15:21:19,892 - root - INFO - Adding extra search path controlnet H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\models/ControlNet
2024-10-14 15:21:22,134 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-10-14 15:21:22,952 - root - INFO - Total VRAM 8192 MB, total RAM 65468 MB
2024-10-14 15:21:22,952 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-14 15:21:22,953 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-14 15:21:22,954 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2070 SUPER : cudaMallocAsync
2024-10-14 15:21:25,320 - root - INFO - --------------
2024-10-14 15:21:25,320 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-10-14 15:21:25,321 - root - INFO - ChatGPT.available True
2024-10-14 15:21:25,322 - root - INFO - edit_mask.available True
2024-10-14 15:21:25,467 - root - INFO - ClipInterrogator.available True
2024-10-14 15:21:25,602 - root - INFO - PromptGenerate.available True
2024-10-14 15:21:25,602 - root - INFO - ChinesePrompt.available True
2024-10-14 15:21:25,602 - root - INFO - RembgNode_.available True
2024-10-14 15:21:26,042 - root - INFO - TripoSR.available
2024-10-14 15:21:26,042 - root - INFO - MiniCPMNode.available
2024-10-14 15:21:26,093 - root - INFO - Scenedetect.available
2024-10-14 15:21:26,194 - root - INFO - FishSpeech.available
2024-10-14 15:21:26,204 - root - INFO - SenseVoice.available
2024-10-14 15:21:26,204 - root - INFO - [93m -------------- [0m
2024-10-14 15:21:28,846 - root - INFO - 
Import times for custom nodes:
2024-10-14 15:21:28,846 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-14 15:21:28,847 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Latent-Upscaler
2024-10-14 15:21:28,847 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Latent-Interposer
2024-10-14 15:21:28,847 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Dragos_Nodes
2024-10-14 15:21:28,847 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-14 15:21:28,848 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Noise
2024-10-14 15:21:28,848 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SD-Advanced-Noise
2024-10-14 15:21:28,848 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-10-14 15:21:28,848 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-10-14 15:21:28,849 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YOLO
2024-10-14 15:21:28,850 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-fitsize
2024-10-14 15:21:28,850 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Logic
2024-10-14 15:21:28,850 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-lama-remover
2024-10-14 15:21:28,850 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_experiments
2024-10-14 15:21:28,851 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-14 15:21:28,851 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyLiterals
2024-10-14 15:21:28,851 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TextOnSegs
2024-10-14 15:21:28,851 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Filters
2024-10-14 15:21:28,852 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
2024-10-14 15:21:28,852 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-10-14 15:21:28,852 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-14 15:21:28,853 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-14 15:21:28,853 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-14 15:21:28,853 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-10-14 15:21:28,854 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-14 15:21:28,854 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-14 15:21:28,854 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-14 15:21:28,854 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-10-14 15:21:28,855 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-14 15:21:28,855 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
2024-10-14 15:21:28,855 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Allor-main
2024-10-14 15:21:28,855 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-10-14 15:21:28,856 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-JDCN
2024-10-14 15:21:28,856 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-14 15:21:28,856 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-14 15:21:28,856 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-14 15:21:28,857 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-10-14 15:21:28,857 - root - INFO -    0.0 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-14 15:21:28,857 - root - INFO -    0.1 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
2024-10-14 15:21:28,857 - root - INFO -    0.1 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-14 15:21:28,857 - root - INFO -    0.1 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\CharacterFaceSwap
2024-10-14 15:21:28,858 - root - INFO -    0.1 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
2024-10-14 15:21:28,858 - root - INFO -    0.1 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-14 15:21:28,858 - root - INFO -    0.1 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-10-14 15:21:28,858 - root - INFO -    0.2 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
2024-10-14 15:21:28,858 - root - INFO -    0.2 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-14 15:21:28,859 - root - INFO -    0.2 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateAnyone-Evolved
2024-10-14 15:21:28,859 - root - INFO -    0.4 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\clipseg.py
2024-10-14 15:21:28,859 - root - INFO -    0.4 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-14 15:21:28,859 - root - INFO -    0.5 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-14 15:21:28,859 - root - INFO -    0.7 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Allor
2024-10-14 15:21:28,860 - root - INFO -    1.3 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-10-14 15:21:28,860 - root - INFO -    1.4 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
2024-10-14 15:21:28,860 - root - INFO -    2.2 seconds: H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-14 15:21:28,860 - root - INFO - 
2024-10-14 15:21:28,878 - root - INFO - Starting server

2024-10-14 15:21:28,878 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-14 15:44:41,280 - root - INFO - got prompt
2024-10-14 15:44:42,406 - root - INFO - Using pytorch attention in VAE
2024-10-14 15:44:42,409 - root - INFO - Using pytorch attention in VAE
2024-10-14 15:44:49,743 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-14 15:44:50,293 - root - INFO - model_type EPS
2024-10-14 15:45:09,319 - root - INFO - Using pytorch attention in VAE
2024-10-14 15:45:09,320 - root - INFO - Using pytorch attention in VAE
2024-10-14 15:45:21,502 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-14 15:45:21,502 - root - INFO - model_type EPS
2024-10-14 15:46:23,471 - root - INFO - Using pytorch attention in VAE
2024-10-14 15:46:23,472 - root - INFO - Using pytorch attention in VAE
2024-10-14 15:47:14,605 - root - INFO - Requested to load AutoencodingEngine
2024-10-14 15:47:14,605 - root - INFO - Loading 1 new model
2024-10-14 15:47:14,661 - root - INFO - loaded partially 64.0 63.99951171875 0
2024-10-14 15:49:01,225 - root - WARNING - clip missing: ['text_projection.weight']
2024-10-14 15:49:01,653 - root - INFO - Requested to load FluxClipModel_
2024-10-14 15:49:01,653 - root - INFO - Loading 1 new model
2024-10-14 15:49:01,887 - root - INFO - loaded partially 64.0 64.03662109375 0
2024-10-14 15:49:13,380 - root - INFO - Unloading models for lowram load.
2024-10-14 15:49:13,423 - root - INFO - 1 models unloaded.
2024-10-14 15:49:13,423 - root - INFO - Loading 1 new model
2024-10-14 15:49:13,469 - root - INFO - loaded partially 64.0 64.03662109375 0
2024-10-14 15:49:27,488 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
2024-10-14 15:49:27,496 - root - INFO - model_type FLOW
2024-10-14 15:51:15,357 - root - INFO - Requested to load Flux
2024-10-14 15:51:15,395 - root - INFO - Loading 1 new model
2024-10-14 15:51:15,962 - root - INFO - loaded partially 64.0 63.9638671875 0
2024-10-14 15:51:23,024 - root - INFO - Unloading models for lowram load.
2024-10-14 15:51:28,297 - root - INFO - 1 models unloaded.
2024-10-14 15:51:28,297 - root - INFO - Loading 1 new model
2024-10-14 15:51:30,452 - root - INFO - loaded partially 3857.1054332733156 3856.6377563476562 0
2024-10-14 15:51:31,842 - root - ERROR - !!! Exception during processing !!!  Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
 Input tensor shape: torch.Size([1, 16, 75, 150]). Additional info: {'ph': 2, 'pw': 2}.
 Shape mismatch, can't divide axis of length 75 in chunks of 2
2024-10-14 15:51:31,910 - root - ERROR - Traceback (most recent call last):
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 523, in reduce
    return _apply_recipe(
           ^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 234, in _apply_recipe
    init_shapes, axes_reordering, reduced_axes, added_axes, final_shapes, n_axes_w_added = _reconstruct_from_shape(
                                                                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 187, in _reconstruct_from_shape_uncached
    raise EinopsError(f"Shape mismatch, can't divide axis of length {length} in chunks of {known_product}")
einops.EinopsError: Shape mismatch, can't divide axis of length 75 in chunks of 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\nodes.py", line 458, in sampling
    x = denoise_controlnet(
        ^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui\sampling.py", line 258, in denoise_controlnet
    orig_image = rearrange(orig_image, "b c (h ph) (w pw) -> b (h w) (c ph pw)", ph=2, pw=2).to(img.device, dtype = img.dtype)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 591, in rearrange
    return reduce(tensor, pattern, reduction="rearrange", **axes_lengths)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "H:\Stable Diffusion\Comfy UI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\einops\einops.py", line 533, in reduce
    raise EinopsError(message + "\n {}".format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "b c (h ph) (w pw) -> b (h w) (c ph pw)".
 Input tensor shape: torch.Size([1, 16, 75, 150]). Additional info: {'ph': 2, 'pw': 2}.
 Shape mismatch, can't divide axis of length 75 in chunks of 2

2024-10-14 15:51:31,943 - root - INFO - Prompt executed in 410.44 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by LukeG89** [comment]
It's not a ComfyUI bug, you should report it here: https://github.com/XLabs-AI/x-flux-comfyui

It seems someone already opened a similar issue: https://github.com/XLabs-AI/x-flux-comfyui/issues/54

Try using a latent with dimensions that are divisible by 8.
