### ISSUE TITLE
Ipadapter model not found

### ISSUE THREAD

**Issue by arujjval** [comfyanonymous/ComfyUI#5266]
### Your question

While using IPadapter unified loader, I am getting the error below. I have all the models present in models/ipadapter folder in bin/safetensor format. Still not able to get what's the issue.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** IPAdapterUnifiedLoader
- **Exception Type:** Exception
- **Exception Message:** IPAdapter model not found.
## Stack Trace

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 573, in load_models
    raise Exception("IPAdapter model not found.")

```
## System Information
- **ComfyUI Version:** v0.2.3-13-g7390ff3
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 4294443008
  - **VRAM Free:** 1651906912
  - **Torch VRAM Total:** 1811939328
  - **Torch VRAM Free:** 32433708

## Logs
```
2024-10-17 10:06:57,529 - root - INFO - Total VRAM 4096 MB, total RAM 15557 MB
2024-10-17 10:06:57,529 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-17 10:06:57,529 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-17 10:06:57,529 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
2024-10-17 10:06:58,702 - root - INFO - Using pytorch cross attention
2024-10-17 10:07:00,320 - root - INFO - [Prompt Server] web root: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path checkpoints .\models/checkpoints/
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path ipadapter .\models/ipadapter
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path clip .\models/clip/
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path clip_vision .\models/clip_vision/
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path configs .\models/configs/
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path controlnet .\models/controlnet/
2024-10-17 10:07:00,322 - root - INFO - Adding extra search path diffusion_models .\models/diffusion_models
2024-10-17 10:07:00,323 - root - INFO - Adding extra search path diffusion_models .\models/unet
2024-10-17 10:07:00,323 - root - INFO - Adding extra search path embeddings .\models/embeddings/
2024-10-17 10:07:00,323 - root - INFO - Adding extra search path loras .\models/loras/
2024-10-17 10:07:00,323 - root - INFO - Adding extra search path upscale_models .\models/upscale_models/
2024-10-17 10:07:00,323 - root - INFO - Adding extra search path vae .\models/vae/
2024-10-17 10:07:02,661 - root - WARNING - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\__init__.py", line 1, in <module>
    from .WAS_Node_Suite import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 37, in <module>
    from numba import jit
ModuleNotFoundError: No module named 'numba'

2024-10-17 10:07:02,662 - root - WARNING - Cannot import D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui module for custom nodes: No module named 'numba'
2024-10-17 10:07:02,664 - root - INFO - 
Import times for custom nodes:
2024-10-17 10:07:02,664 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-17 10:07:02,664 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-17 10:07:02,664 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-17 10:07:02,664 - root - INFO -    0.0 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-17 10:07:02,664 - root - INFO -    0.1 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-10-17 10:07:02,664 - root - INFO -    0.4 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-17 10:07:02,664 - root - INFO -    0.5 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-17 10:07:02,664 - root - INFO -    0.8 seconds: D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CustomNodes
2024-10-17 10:07:02,664 - root - INFO - 
2024-10-17 10:07:02,671 - root - INFO - Starting server

2024-10-17 10:07:02,671 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-17 10:07:11,273 - root - INFO - got prompt
2024-10-17 10:07:14,238 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-17 10:07:14,256 - root - INFO - model_type EPS
2024-10-17 10:07:21,011 - root - INFO - Using pytorch attention in VAE
2024-10-17 10:07:21,019 - root - INFO - Using pytorch attention in VAE
2024-10-17 10:07:21,813 - root - INFO - Requested to load SDXLClipModel
2024-10-17 10:07:21,813 - root - INFO - Loading 1 new model
2024-10-17 10:07:21,823 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-17 10:07:38,946 - root - ERROR - !!! Exception during processing !!! IPAdapter model not found.
2024-10-17 10:07:38,954 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 573, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

2024-10-17 10:07:38,959 - root - INFO - Prompt executed in 27.68 seconds
2024-10-17 10:08:36,283 - root - INFO - got prompt
2024-10-17 10:08:36,307 - root - ERROR - !!! Exception during processing !!! IPAdapter model not found.
2024-10-17 10:08:36,308 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 573, in load_models
    raise Exception("IPAdapter model not found.")
Exception: IPAdapter model not found.

2024-10-17 10:08:36,309 - root - INFO - Prompt executed in 0.02 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":19,"last_link_id":22,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":1209,"1":188},"size":{"0":210,"1":46},"flags":{},"order":13,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":{"0":1451,"1":189},"size":{"0":210,"1":270},"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":10,"type":"LoadImage","pos":{"0":139,"1":-231},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[10],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_00023_.png","image"]},{"id":7,"type":"CLIPTextEncode","pos":{"0":413,"1":389},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":8,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[18],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark, watermark"]},{"id":18,"type":"ControlNetApplyAdvanced","pos":{"0":449,"1":662},"size":{"0":315,"1":186},"flags":{},"order":11,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":16},{"name":"negative","type":"CONDITIONING","link":18},{"name":"control_net","type":"CONTROL_NET","link":17},{"name":"image","type":"IMAGE","link":21},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[19],"slot_index":0,"shape":3},{"name":"negative","type":"CONDITIONING","links":[20],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[1,0,1]},{"id":13,"type":"DWPreprocessor","pos":{"0":442,"1":916},"size":{"0":315,"1":198},"flags":{},"order":5,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":14}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[15,21],"slot_index":0,"shape":3},{"name":"POSE_KEYPOINT","type":"POSE_KEYPOINT","links":null,"shape":3}],"properties":{"Node name for S&R":"DWPreprocessor"},"widgets_values":["disable","enable","disable",512,"yolox_l.onnx","dw-ll_ucoco_384_bs5.torchscript.pt"]},{"id":17,"type":"ControlNetLoader","pos":{"0":22,"1":634},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[17],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["OpenPoseXL2.safetensors"]},{"id":14,"type":"LoadImage","pos":{"0":-31,"1":894},"size":{"0":315,"1":314},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[14],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["456345581_472829068968858_5217233821900136786_n.jpg","image"]},{"id":15,"type":"PreviewImage","pos":{"0":1033,"1":880},"size":{"0":210,"1":246},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":15}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":12,"type":"IPAdapter","pos":{"0":612,"1":-98},"size":{"0":315,"1":190},"flags":{},"order":10,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":12},{"name":"ipadapter","type":"IPADAPTER","link":13},{"name":"image","type":"IMAGE","link":10},{"name":"attn_mask","type":"MASK","link":null,"shape":7}],"outputs":[{"name":"MODEL","type":"MODEL","links":[22],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"IPAdapter"},"widgets_values":[0.75,0,1,"standard"]},{"id":3,"type":"KSampler","pos":{"0":863,"1":186},"size":{"0":315,"1":262},"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":22},{"name":"positive","type":"CONDITIONING","link":19},{"name":"negative","type":"CONDITIONING","link":20},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[293860398971154,"randomize",30,8,"dpmpp_2m","karras",1]},{"id":6,"type":"CLIPTextEncode","pos":{"0":415,"1":186},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":7,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[16],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["realistic photograph, closeup, beautiful woman, smiling, blond, symmetrical features, closed mouth, clear skin, wearing a tank top, light makeup, elegant, refined, delicate features, soft lighting, natural look, brown eyes, chiseled cheekbones, slight smile, glossy lips, natural hair color, background blurred\n\n4k, highly detailed, high-quality, masterpiece"]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":35,"1":238},"size":{"0":315,"1":98},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[11],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["realismEngineSDXL_v30VAE.safetensors"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":869,"1":497},"size":{"0":315,"1":106},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,4]},{"id":11,"type":"IPAdapterUnifiedLoader","pos":{"0":570,"1":-294},"size":{"0":315,"1":78},"flags":{},"order":6,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":11},{"name":"ipadapter","type":"IPADAPTER","link":null,"shape":7}],"outputs":[{"name":"model","type":"MODEL","links":[12],"slot_index":0,"shape":3},{"name":"ipadapter","type":"IPADAPTER","links":[13],"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"IPAdapterUnifiedLoader"},"widgets_values":["PLUS (high strength)"]}],"links":[[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[5,4,1,7,0,"CLIP"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[10,10,0,12,2,"IMAGE"],[11,4,0,11,0,"MODEL"],[12,11,0,12,0,"MODEL"],[13,11,1,12,1,"IPADAPTER"],[14,14,0,13,0,"IMAGE"],[15,13,0,15,0,"IMAGE"],[16,6,0,18,0,"CONDITIONING"],[17,17,0,18,2,"CONTROL_NET"],[18,7,0,18,1,"CONDITIONING"],[19,18,0,3,1,"CONDITIONING"],[20,18,1,3,2,"CONDITIONING"],[21,13,0,18,3,"IMAGE"],[22,12,0,3,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650705,"offset":[176.38904481945485,652.9957040820054]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by LukeG89** [comment]
It's not a ComfyUI issue, you should've opened the issue in the [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) custom node. 

However, I know that if you don't rename the models right, the unified loader won't find them.
Follow the instructions here: https://github.com/cubiq/ComfyUI_IPAdapter_plus?tab=readme-ov-file#installation
