### ISSUE TITLE
Flux Dev's model type not being detected

### ISSUE THREAD

**Issue by SquidR** [comfyanonymous/ComfyUI#5283]
### Your question

Whenever i try to load in the Flux Dev safetensors file, installed from the civitai page, ComfyUI says "ERROR: Could not detect model type of: C:\Users ..."

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** CheckpointLoaderSimple
- **Exception Type:** RuntimeError
- **Exception Message:** ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors
## Stack Trace

  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 540, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 558, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))

```
## System Information
- **ComfyUI Version:** v0.2.3
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8585216000
  - **VRAM Free:** 7382892544
  - **Torch VRAM Total:** 33554432
  - **Torch VRAM Free:** 25034752

## Logs
```
2024-10-18 16:32:23,421 - root - INFO - Total VRAM 8188 MB, total RAM 32406 MB
2024-10-18 16:32:23,421 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-18 16:32:23,422 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-18 16:32:23,422 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
2024-10-18 16:32:24,573 - root - INFO - Using pytorch cross attention
2024-10-18 16:32:29,622 - root - INFO - [Prompt Server] web root: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-18 16:32:31,293 - root - INFO - 
Import times for custom nodes:
2024-10-18 16:32:31,293 - root - INFO -    0.0 seconds: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-18 16:32:31,293 - root - INFO -    0.0 seconds: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-18 16:32:31,293 - root - INFO -    0.0 seconds: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-18 16:32:31,294 - root - INFO -    0.0 seconds: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-18 16:32:31,294 - root - INFO -    0.3 seconds: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-18 16:32:31,294 - root - INFO -    0.5 seconds: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-18 16:32:31,294 - root - INFO - 
2024-10-18 16:32:31,298 - root - INFO - Starting server

2024-10-18 16:32:31,298 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-18 16:36:40,924 - root - INFO - got prompt
2024-10-18 16:36:41,408 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-18 16:36:41,429 - root - INFO - model_type EPS
2024-10-18 16:36:47,618 - root - INFO - Using pytorch attention in VAE
2024-10-18 16:36:47,620 - root - INFO - Using pytorch attention in VAE
2024-10-18 16:36:48,054 - root - INFO - Requested to load SDXLClipModel
2024-10-18 16:36:48,054 - root - INFO - Loading 1 new model
2024-10-18 16:36:48,063 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-18 16:36:50,727 - root - INFO - Requested to load SDXLClipModel
2024-10-18 16:36:50,728 - root - INFO - Loading 1 new model
2024-10-18 16:36:51,559 - root - INFO - Requested to load SDXL
2024-10-18 16:36:51,559 - root - INFO - Loading 1 new model
2024-10-18 16:36:52,957 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-10-18 16:37:15,216 - root - INFO - Requested to load AutoencoderKL
2024-10-18 16:37:15,216 - root - INFO - Loading 1 new model
2024-10-18 16:37:16,749 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-18 16:37:17,958 - root - INFO - Prompt executed in 37.03 seconds
2024-10-18 16:40:37,884 - root - INFO - got prompt
2024-10-18 16:40:39,095 - root - ERROR - !!! Exception during processing !!! ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors
2024-10-18 16:40:39,105 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 540, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 558, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors

2024-10-18 16:40:39,106 - root - INFO - Prompt executed in 1.22 seconds
2024-10-18 16:40:59,802 - root - INFO - got prompt
2024-10-18 16:40:59,968 - root - ERROR - !!! Exception during processing !!! ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors
2024-10-18 16:40:59,968 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 540, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 558, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors

2024-10-18 16:40:59,969 - root - INFO - Prompt executed in 0.17 seconds
2024-10-18 16:42:18,968 - root - INFO - got prompt
2024-10-18 16:42:19,074 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-18 16:42:19,075 - root - INFO - model_type EPS
2024-10-18 16:42:19,750 - root - INFO - Using pytorch attention in VAE
2024-10-18 16:42:19,752 - root - INFO - Using pytorch attention in VAE
2024-10-18 16:42:19,921 - root - INFO - Requested to load SDXLClipModel
2024-10-18 16:42:19,921 - root - INFO - Loading 1 new model
2024-10-18 16:42:19,929 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-10-18 16:42:20,909 - root - INFO - Requested to load SDXLClipModel
2024-10-18 16:42:20,909 - root - INFO - Loading 1 new model
2024-10-18 16:42:21,217 - root - INFO - Requested to load SDXL
2024-10-18 16:42:21,218 - root - INFO - Loading 1 new model
2024-10-18 16:42:22,461 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-10-18 16:42:36,275 - root - INFO - Requested to load AutoencoderKL
2024-10-18 16:42:36,275 - root - INFO - Loading 1 new model
2024-10-18 16:42:37,479 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-18 16:42:38,380 - root - INFO - Prompt executed in 19.41 seconds
2024-10-18 16:42:48,907 - root - INFO - got prompt
2024-10-18 16:42:49,308 - root - ERROR - !!! Exception during processing !!! ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors
2024-10-18 16:42:49,309 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 540, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 558, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors

2024-10-18 16:42:49,310 - root - INFO - Prompt executed in 0.40 seconds
2024-10-18 16:43:08,436 - root - INFO - got prompt
2024-10-18 16:43:08,674 - root - ERROR - !!! Exception during processing !!! ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors
2024-10-18 16:43:08,675 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 540, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 558, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\Users\squid\Documents\ai shit\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models\checkpoints\flux_dev.safetensors

2024-10-18 16:43:08,675 - root - INFO - Prompt executed in 0.24 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":16,"last_link_id":26,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":1233,"1":34},"size":{"0":210,"1":46},"flags":{},"order":6,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[19,21],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":10,"type":"PreviewImage","pos":{"0":1857,"1":33},"size":{"0":210,"1":246},"flags":{"collapsed":false},"order":7,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":19}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":12,"type":"ImageScale","pos":{"0":1491,"1":166},"size":{"0":315,"1":130},"flags":{},"order":8,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":21}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[20],"slot_index":0}],"properties":{"Node name for S&R":"ImageScale"},"widgets_values":["area",1024,1024,"disabled"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":536,"1":699},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[1024,1024,1]},{"id":14,"type":"PreviewImage","pos":{"0":2076,"1":31},"size":{"0":210,"1":246},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":20}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":3,"type":"KSampler","pos":{"0":952,"1":192},"size":{"0":315,"1":262},"flags":{},"order":5,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1},{"name":"positive","type":"CONDITIONING","link":24},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[174043461825091,"randomize",19,8,"euler_ancestral","normal",1]},{"id":7,"type":"CLIPTextEncode","pos":{"0":329,"1":473},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":26}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["bad anatomy, extra people, (deformed iris, deformed pupils, mutated hands and fingers:1.4), (deformed, distorted, disfigured:1.3), poorly drawn, bad anatomy, wrong anatomy, extra limb, missing limb, floating limbs, disconnected limbs, mutation, mutated, ugly, disgusting, amputation, signature, watermark, airbrush, photoshop, plastic doll, (ugly eyes, deformed iris, deformed pupils, fused lips and teeth:1.2), text, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, masculine, obese, fat, out of frame, caricature, body horror, mutant, facebook, youtube, food, lowres, text, error, cropped, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, out of frame, extra fingers, mutated hands, poorly drawn hands, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions, malformed limbs, missing arms, missing legs, extra arms, extra legs, fused fingers, too many fingers, long neck, username, watermark, signature, anthro"]},{"id":13,"type":"CLIPSetLastLayer","pos":{"0":-154,"1":324},"size":{"0":315,"1":58},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":14}],"outputs":[{"name":"CLIP","type":"CLIP","links":[],"slot_index":0}],"properties":{"Node name for S&R":"CLIPSetLastLayer"},"widgets_values":[-2]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":16,"1":62},"size":{"0":315,"1":98},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[14,25,26],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["flux_dev.safetensors"]},{"id":15,"type":"CLIPTextEncodeSDXLRefiner","pos":{"0":333,"1":217},"size":{"0":400,"1":200},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":25}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[24],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncodeSDXLRefiner"},"widgets_values":[6,1024,1024,"a illustration of a artificial intelligence stable diffusion's latent space "]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[14,4,1,13,0,"CLIP"],[19,8,0,10,0,"IMAGE"],[20,12,0,14,0,"IMAGE"],[21,8,0,12,0,"IMAGE"],[24,15,0,3,1,"CONDITIONING"],[25,4,1,15,0,"CLIP"],[26,4,1,7,0,"CLIP"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8390545288824064,"offset":[534.7454812902204,281.5962999560121]}},"version":0.4}
```

## Additional Context
All i had done was move the flux dev checkpoint into the checkpoints folder, and its saying that the model type is unable to be detected.
```


### Other

_No response_

**Comment by LukeG89** [comment]
It's not detected because it's probably the Unet model, you need to move it to `models/diffusion_models` folder.
And also you need to download the t5xxl and clip l text encoders and the VAE.

Follow this instructions: https://comfyanonymous.github.io/ComfyUI_examples/flux/
You will also find the links to all the models and an example workflow.
