### ISSUE TITLE
CLIPTextEncode

### ISSUE THREAD

**Issue by miguelgargallo** [comfyanonymous/ComfyUI#5305]
### Expected Behavior

Do it correctly

### Actual Behavior

Prompts the error

### Steps to Reproduce

Just start the node

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** CLIPTextEncode
- **Exception Type:** torch.cuda.OutOfMemoryError
- **Exception Message:** Allocation on device 
## Stack Trace

  File "PATH\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "PATH\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\nodes.py", line 65, in encode
    output = clip.encode_from_tokens(tokens, return_pooled=True, return_dict=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\sd.py", line 125, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\text_encoders\flux.py", line 55, in encode_token_weights
    t5_out, t5_pooled = self.t5xxl.encode_token_weights(token_weight_pairs_t5)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\sd1_clip.py", line 41, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\sd1_clip.py", line 238, in encode
    return self(tokens)
           ^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\sd1_clip.py", line 210, in forward
    outputs = self.transformer(tokens, attention_mask_model, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\text_encoders\t5.py", line 238, in forward
    x = self.shared(input_ids, out_dtype=kwargs.get("dtype", torch.float32))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\comfy\ops.py", line 203, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 152, in forward_comfy_cast_weights
    return self.forward_ggml_cast_weights(input, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 187, in forward_ggml_cast_weights
    weight, _bias = self.cast_bias_weight(self, device=input.device, dtype=out_dtype)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 146, in cast_bias_weight
    weight = s.get_weight(s.weight.to(device), dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 119, in get_weight
    weight = dequantize_tensor(tensor, dtype, self.dequant_dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\dequant.py", line 23, in dequantize_tensor
    return dequantize(tensor.data, qtype, oshape, dtype=dequant_dtype).to(dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 23, in to
    new = super().to(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "PATH\python_embeded\Lib\site-packages\torch\_tensor.py", line 1443, in __torch_function__
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3-23-g83ca891
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 11534336000
  - **Torch VRAM Total:** 67108864
  - **Torch VRAM Free:** 33554432

## Logs
```
2024-10-21 10:56:03,289 - root - INFO - Total VRAM 12282 MB, total RAM 32509 MB
2024-10-21 10:56:03,289 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-21 10:56:03,289 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-21 10:56:03,289 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-10-21 10:56:03,903 - root - INFO - Using pytorch cross attention
2024-10-21 10:56:04,652 - root - INFO - [Prompt Server] web root: PATH\ComfyUI\web
2024-10-21 10:56:05,353 - root - INFO - Total VRAM 12282 MB, total RAM 32509 MB
2024-10-21 10:56:05,353 - root - INFO - pytorch version: 2.3.1+cu121
2024-10-21 10:56:05,354 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-21 10:56:05,354 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
2024-10-21 10:56:10,337 - root - INFO - 
Import times for custom nodes:
2024-10-21 10:56:10,337 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-21 10:56:10,337 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-10-21 10:56:10,337 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-21 10:56:10,337 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-21 10:56:10,337 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-21 10:56:10,337 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\rgthree-comfy
2024-10-21 10:56:10,338 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-21 10:56:10,338 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\x-flux-comfyui
2024-10-21 10:56:10,338 - root - INFO -    0.0 seconds: PATH\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-21 10:56:10,338 - root - INFO -    0.1 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-21 10:56:10,338 - root - INFO -    0.2 seconds: PATH\ComfyUI\custom_nodes\comfyui-tensorops
2024-10-21 10:56:10,338 - root - INFO -    0.2 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-21 10:56:10,338 - root - INFO -    0.2 seconds: PATH\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-10-21 10:56:10,338 - root - INFO -    4.5 seconds: PATH\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-21 10:56:10,338 - root - INFO - 
2024-10-21 10:56:10,344 - root - INFO - Starting server

2024-10-21 10:56:10,345 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-21 10:56:11,031 - root - ERROR - [ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
2024-10-21 10:56:11,032 - root - ERROR - Traceback (most recent call last):
  File "PATH\ComfyUI\server.py", line 564, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "PATH\ComfyUI\server.py", line 531, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 148, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 148, in <listcomp>
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 931, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\Try2\\ComfyUI_windows_portable\\ComfyUI\\models\\LLM'

2024-10-21 10:56:13,932 - root - INFO - got prompt
2024-10-21 10:56:14,963 - root - INFO - Using pytorch attention in VAE
2024-10-21 10:56:14,964 - root - INFO - Using pytorch attention in VAE
2024-10-21 10:57:04,659 - root - INFO - model weight dtype torch.bfloat16, manual cast: None
2024-10-21 10:57:04,660 - root - INFO - model_type FLUX
2024-10-21 10:57:05,637 - root - INFO - Requested to load FluxClipModel_
2024-10-21 10:57:05,638 - root - INFO - Loading 1 new model
2024-10-21 10:58:11,311 - root - INFO - loaded completely 0.0 5062.70263671875 True
2024-10-21 10:58:12,322 - root - INFO - Requested to load Flux
2024-10-21 10:58:12,322 - root - INFO - Loading 1 new model
2024-10-21 11:00:06,763 - root - INFO - loaded partially 9498.496 9498.316528320312 0
2024-10-21 11:01:37,146 - root - INFO - Requested to load AutoencodingEngine
2024-10-21 11:01:37,146 - root - INFO - Loading 1 new model
2024-10-21 11:01:38,173 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-10-21 11:01:44,905 - root - INFO - Prompt executed in 330.97 seconds
2024-10-21 11:04:43,317 - root - INFO - got prompt
2024-10-21 11:04:44,821 - root - INFO - Requested to load FluxClipModel_
2024-10-21 11:04:44,822 - root - INFO - Loading 1 new model
2024-10-21 11:04:45,868 - root - INFO - loaded completely 0.0 5062.70263671875 True
2024-10-21 11:04:48,432 - root - ERROR - !!! Exception during processing !!! Allocation on device 
2024-10-21 11:04:48,611 - root - ERROR - Traceback (most recent call last):
  File "PATH\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "PATH\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\nodes.py", line 65, in encode
    output = clip.encode_from_tokens(tokens, return_pooled=True, return_dict=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\sd.py", line 125, in encode_from_tokens
    o = self.cond_stage_model.encode_token_weights(tokens)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\text_encoders\flux.py", line 55, in encode_token_weights
    t5_out, t5_pooled = self.t5xxl.encode_token_weights(token_weight_pairs_t5)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\sd1_clip.py", line 41, in encode_token_weights
    o = self.encode(to_encode)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\sd1_clip.py", line 238, in encode
    return self(tokens)
           ^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\sd1_clip.py", line 210, in forward
    outputs = self.transformer(tokens, attention_mask_model, intermediate_output=self.layer_idx, final_layer_norm_intermediate=self.layer_norm_hidden_state, dtype=torch.float32)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\text_encoders\t5.py", line 238, in forward
    x = self.shared(input_ids, out_dtype=kwargs.get("dtype", torch.float32))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\comfy\ops.py", line 203, in forward
    return self.forward_comfy_cast_weights(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 152, in forward_comfy_cast_weights
    return self.forward_ggml_cast_weights(input, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 187, in forward_ggml_cast_weights
    weight, _bias = self.cast_bias_weight(self, device=input.device, dtype=out_dtype)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 146, in cast_bias_weight
    weight = s.get_weight(s.weight.to(device), dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 119, in get_weight
    weight = dequantize_tensor(tensor, dtype, self.dequant_dtype)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\dequant.py", line 23, in dequantize_tensor
    return dequantize(tensor.data, qtype, oshape, dtype=dequant_dtype).to(dtype)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\ComfyUI\custom_nodes\ComfyUI-GGUF\ops.py", line 23, in to
    new = super().to(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "PATH\python_embeded\Lib\site-packages\torch\_tensor.py", line 1443, in __torch_function__
    ret = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: Allocation on device 

2024-10-21 11:04:48,612 - root - ERROR - Got an OOM, unloading all loaded models.
2024-10-21 11:04:51,604 - root - INFO - Prompt executed in 8.28 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
This issue should be moved to ComfyUI-GGUF.
https://github.com/city96/ComfyUI-GGUF

Please share your system specifications and workflow with your inquiry.

**Comment by luisfn** [comment]
hey @miguelgargallo, have you fixed this issue on your side? I'm having same problem and didn't find anything on  https://github.com/city96/ComfyUI-GGUF
