### ISSUE TITLE
how can i fix it?

### ISSUE THREAD

**Issue by baby11233** [comfyanonymous/ComfyUI#5311]
### Your question

PulidFluxInsightFaceLoader can not work.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** PulidFluxInsightFaceLoader
- **Exception Type:** AssertionError
- **Exception Message:** 
## Stack Trace

  File "D:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 198, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI\.ext\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.3-23-g83ca8911
- **Arguments:** D:\AI\ComfyUI\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.11.6 | packaged by conda-forge | (main, Oct  3 2023, 10:29:11) [MSC v.1935 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 10736893952
  - **VRAM Free:** 9287370426
  - **Torch VRAM Total:** 167772160
  - **Torch VRAM Free:** 132794

## Logs
```
2024-10-22 00:04:24,168 - root - INFO - Total VRAM 10240 MB, total RAM 32627 MB
2024-10-22 00:04:24,168 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-22 00:04:24,983 - root - INFO - xformers version: 0.0.28.post1
2024-10-22 00:04:24,992 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-22 00:04:24,992 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
2024-10-22 00:04:25,114 - root - INFO - Using xformers cross attention
2024-10-22 00:04:25,816 - root - INFO - [Prompt Server] web root: D:\AI\ComfyUI\web
2024-10-22 00:04:27,895 - root - INFO - 
Import times for custom nodes:
2024-10-22 00:04:27,895 - root - INFO -    0.0 seconds: D:\AI\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-22 00:04:27,895 - root - INFO -    0.0 seconds: D:\AI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-10-22 00:04:27,895 - root - INFO -    0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-22 00:04:27,895 - root - INFO -    0.0 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-22 00:04:27,895 - root - INFO -    0.1 seconds: D:\AI\ComfyUI\custom_nodes\PuLID_ComfyUI
2024-10-22 00:04:27,895 - root - INFO -    0.2 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-22 00:04:27,895 - root - INFO -    1.5 seconds: D:\AI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-10-22 00:04:27,895 - root - INFO - 
2024-10-22 00:04:27,901 - root - INFO - Starting server

2024-10-22 00:04:27,901 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-22 00:04:33,132 - root - INFO - got prompt
2024-10-22 00:04:33,178 - root - INFO - Using xformers attention in VAE
2024-10-22 00:04:33,179 - root - INFO - Using xformers attention in VAE
2024-10-22 00:04:33,550 - root - INFO - Requested to load AutoencodingEngine
2024-10-22 00:04:33,551 - root - INFO - Loading 1 new model
2024-10-22 00:04:33,606 - root - INFO - loaded completely 0.0 159.87335777282715 True
2024-10-22 00:04:33,953 - root - ERROR - !!! Exception during processing !!! 
2024-10-22 00:04:33,955 - root - ERROR - Traceback (most recent call last):
  File "D:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 198, in load_insightface
    model = FaceAnalysis(name="antelopev2", root=INSIGHTFACE_DIR, providers=[provider + 'ExecutionProvider',]) # alternative to buffalo_l
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI\.ext\Lib\site-packages\insightface\app\face_analysis.py", line 43, in __init__
    assert 'detection' in self.models
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

2024-10-22 00:04:33,955 - root - INFO - Prompt executed in 0.80 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":54,"last_link_id":64,"nodes":[{"id":3,"type":"VAELoader","pos":{"0":1,"1":593},"size":{"0":315,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[3,8],"slot_index":0,"shape":3,"label":"VAE"}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.safetensors"]},{"id":2,"type":"DualCLIPLoader","pos":{"0":16,"1":392},"size":{"0":315,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[1],"slot_index":0,"shape":3,"label":"CLIP"}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","clip_l.safetensors","flux"]},{"id":7,"type":"BasicGuider","pos":{"0":777,"1":343},"size":{"0":241.79998779296875,"1":46},"flags":{},"order":14,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":7,"label":"model"},{"name":"conditioning","type":"CONDITIONING","link":4,"label":"conditioning"}],"outputs":[{"name":"GUIDER","type":"GUIDER","links":[11],"slot_index":0,"shape":3,"label":"GUIDER"}],"properties":{"Node name for S&R":"BasicGuider"},"widgets_values":[]},{"id":9,"type":"RandomNoise","pos":{"0":996,"1":-4},"size":{"0":315,"1":82},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"NOISE","type":"NOISE","links":[15],"slot_index":0,"shape":3,"label":"NOISE"}],"properties":{"Node name for S&R":"RandomNoise"},"widgets_values":[239034192307978,"randomize"]},{"id":27,"type":"ImageUpscaleWithModel","pos":{"0":2418.430908203125,"1":4.326371192932129},"size":{"0":340.20001220703125,"1":46},"flags":{},"order":21,"mode":0,"inputs":[{"name":"upscale_model","type":"UPSCALE_MODEL","link":23,"label":"upscale_model"},{"name":"image","type":"IMAGE","link":54,"label":"image"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[27],"slot_index":0,"shape":3,"label":"IMAGE"}],"properties":{"Node name for S&R":"ImageUpscaleWithModel"},"widgets_values":[]},{"id":26,"type":"UpscaleModelLoader","pos":{"0":2369,"1":-175},"size":{"0":315,"1":58},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"UPSCALE_MODEL","type":"UPSCALE_MODEL","links":[23],"slot_index":0,"shape":3,"label":"UPSCALE_MODEL"}],"properties":{"Node name for S&R":"UpscaleModelLoader"},"widgets_values":["RealESRGAN_x2.pth"]},{"id":10,"type":"VAEDecode","pos":{"0":1220,"1":160},"size":{"0":210,"1":46},"flags":{},"order":19,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":13,"label":"samples"},{"name":"vae","type":"VAE","link":8,"label":"vae"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[52,54],"slot_index":0,"shape":3,"label":"IMAGE"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":11,"type":"KSamplerSelect","pos":{"0":553,"1":587},"size":{"0":315,"1":58},"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"SAMPLER","type":"SAMPLER","links":[10],"slot_index":0,"shape":3,"label":"SAMPLER"}],"properties":{"Node name for S&R":"KSamplerSelect"},"widgets_values":["euler"]},{"id":30,"type":"SaveImage","pos":{"0":1332,"1":584},"size":{"0":591.6146240234375,"1":716.5614013671875},"flags":{},"order":20,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":52,"label":"images"}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":13,"type":"SamplerCustomAdvanced","pos":{"0":933,"1":574},"size":{"0":381.85467529296875,"1":399.6275329589844},"flags":{},"order":18,"mode":0,"inputs":[{"name":"noise","type":"NOISE","link":15,"label":"noise"},{"name":"guider","type":"GUIDER","link":11,"label":"guider"},{"name":"sampler","type":"SAMPLER","link":10,"label":"sampler"},{"name":"sigmas","type":"SIGMAS","link":31,"label":"sigmas"},{"name":"latent_image","type":"LATENT","link":14,"label":"latent_image"}],"outputs":[{"name":"output","type":"LATENT","links":[13],"slot_index":0,"shape":3,"label":"output"},{"name":"denoised_output","type":"LATENT","links":null,"shape":3,"label":"denoised_output"}],"properties":{"Node name for S&R":"SamplerCustomAdvanced"},"widgets_values":[]},{"id":6,"type":"VAEEncode","pos":{"0":558,"1":698},"size":{"0":210,"1":46},"flags":{},"order":15,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":49,"label":"pixels"},{"name":"vae","type":"VAE","link":3,"label":"vae"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[14],"slot_index":0,"shape":3,"label":"LATENT"}],"properties":{"Node name for S&R":"VAEEncode"},"widgets_values":[]},{"id":16,"type":"BasicScheduler","pos":{"0":1107,"1":324},"size":{"0":315,"1":106},"flags":{},"order":17,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":60,"label":"model"}],"outputs":[{"name":"SIGMAS","type":"SIGMAS","links":[31],"slot_index":0,"shape":3,"label":"SIGMAS"}],"properties":{"Node name for S&R":"BasicScheduler"},"widgets_values":["normal",25,0.75]},{"id":5,"type":"LoadImage","pos":{"0":1480,"1":126},"size":{"0":291.9613342285156,"1":403.07073974609375},"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[50],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["0019.jpg","image"]},{"id":29,"type":"SaveImage","pos":{"0":1988,"1":363},"size":{"0":851.0107421875,"1":1025.13427734375},"flags":{},"order":22,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":27,"label":"images"}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":47,"type":"PulidFluxModelLoader","pos":{"0":89,"1":1072},"size":{"0":315,"1":58},"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"PULIDFLUX","type":"PULIDFLUX","links":[55],"slot_index":0,"label":"PULIDFLUX"}],"properties":{"Node name for S&R":"PulidFluxModelLoader"},"widgets_values":["pulid_flux_v0.9.0.safetensors"]},{"id":49,"type":"PulidFluxEvaClipLoader","pos":{"0":92,"1":1171},"size":{"0":327.5999755859375,"1":26},"flags":{},"order":7,"mode":0,"inputs":[],"outputs":[{"name":"EVA_CLIP","type":"EVA_CLIP","links":[56],"label":"EVA_CLIP"}],"properties":{"Node name for S&R":"PulidFluxEvaClipLoader"},"widgets_values":[]},{"id":8,"type":"UNETLoader","pos":{"0":-25,"1":52},"size":{"0":315,"1":82},"flags":{},"order":8,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[7,17],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["墨幽随拍F.1_MYHuman_1.2-train.safetensors","fp8_e4m3fn"]},{"id":19,"type":"LoraLoaderModelOnly","pos":{"0":399,"1":59},"size":{"0":315,"1":82},"flags":{},"order":13,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":17,"label":"model"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[61],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"LoraLoaderModelOnly"},"widgets_values":["F.1-Lora-网图_MYH-1.1.safetensors",1]},{"id":4,"type":"CLIPTextEncode","pos":{"0":244,"1":349},"size":{"0":400,"1":200},"flags":{},"order":11,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":1,"label":"clip"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0,"shape":3,"label":"CONDITIONING"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["This is a real high-definition photo, This is a clear mobile selfie photo with a daily style, pretty gitl,light smile,"]},{"id":50,"type":"LoadImage","pos":{"0":126,"1":715},"size":{"0":315,"1":314},"flags":{},"order":9,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[57],"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["00003.png","image"]},{"id":46,"type":"ImageScaleBy","pos":{"0":1893,"1":174},"size":{"0":315,"1":82},"flags":{},"order":12,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":50,"label":"image"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[49],"label":"IMAGE"}],"properties":{"Node name for S&R":"ImageScaleBy"},"widgets_values":["nearest-exact",0.3]},{"id":48,"type":"ApplyPulidFlux","pos":{"0":563,"1":919},"size":{"0":315,"1":326},"flags":{},"order":16,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":61,"label":"model"},{"name":"pulid_flux","type":"PULIDFLUX","link":55,"label":"pulid_flux"},{"name":"eva_clip","type":"EVA_CLIP","link":56,"label":"eva_clip"},{"name":"face_analysis","type":"FACEANALYSIS","link":64,"label":"face_analysis"},{"name":"image","type":"IMAGE","link":57,"label":"image"},{"name":"attn_mask","type":"MASK","link":null,"shape":7,"label":"attn_mask"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[60],"slot_index":0,"label":"MODEL"}],"properties":{"Node name for S&R":"ApplyPulidFlux"},"widgets_values":[1,0,1,"mean",1,0,3000,true]},{"id":54,"type":"PulidFluxInsightFaceLoader","pos":{"0":43,"1":1256},"size":{"0":365.4000244140625,"1":58},"flags":{},"order":10,"mode":0,"inputs":[],"outputs":[{"name":"FACEANALYSIS","type":"FACEANALYSIS","links":[64],"label":"FACEANALYSIS"}],"properties":{"Node name for S&R":"PulidFluxInsightFaceLoader"},"widgets_values":["CPU"]}],"links":[[1,2,0,4,0,"CLIP"],[3,3,0,6,1,"VAE"],[4,4,0,7,1,"CONDITIONING"],[7,8,0,7,0,"MODEL"],[8,3,0,10,1,"VAE"],[10,11,0,13,2,"SAMPLER"],[11,7,0,13,1,"GUIDER"],[13,13,0,10,0,"LATENT"],[14,6,0,13,4,"LATENT"],[15,9,0,13,0,"NOISE"],[17,8,0,19,0,"MODEL"],[23,26,0,27,0,"UPSCALE_MODEL"],[27,27,0,29,0,"IMAGE"],[31,16,0,13,3,"SIGMAS"],[49,46,0,6,0,"IMAGE"],[50,5,0,46,0,"IMAGE"],[52,10,0,30,0,"IMAGE"],[54,10,0,27,1,"IMAGE"],[55,47,0,48,1,"PULIDFLUX"],[56,49,0,48,2,"EVA_CLIP"],[57,50,0,48,4,"IMAGE"],[60,48,0,16,0,"MODEL"],[61,19,0,48,0,"MODEL"],[64,54,0,48,3,"FACEANALYSIS"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.1167815779425627,"offset":[5.41387638171534,-423.5141646461981]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ClothingAI** [comment]
How did you solve the "assert 'detection' in self.models" problem @baby11233 ?
