### ISSUE TITLE
Error handling request Traceback (most recent call last):   File "/home/ks/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request     resp = await request_handler(request)

### ISSUE THREAD

**Issue by kairin** [comfyanonymous/ComfyUI#5321]
### Your question

the last line of the error is this:

```

File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

but something tells me it is probably in here where i should start but... i just dunno what to do.

```

Import times for custom nodes:
   0.0 seconds: /home/ks/comfui/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
Error handling request
Traceback (most recent call last):
  File "/home/ks/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```

### Logs

```powershell
comfui  ddd  nodes  venv
Command 'nvcc' not found, but can be installed with:
sudo apt install nvidia-cuda-toolkit
Tue Oct 22 19:15:12 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.51.01              Driver Version: 565.90         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    On  |   00000000:0B:00.0  On |                  N/A |
|  0%   41C    P0             30W /  320W |     434MiB /  16376MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        35      G   /Xwayland                                   N/A      |
+-----------------------------------------------------------------------------------------+
VIRTUAL_ENV=/home/ks/venv
VIRTUAL_ENV_PROMPT=(venv)
comfui  ddd  nodes  venv
CODEOWNERS       app               comfyui.prev2.log               fix_torch.py       models           pytest.ini        tests
CONTRIBUTING.md  comfy             comfyui_screenshot.png          folder_paths.py    new_updater.py   req.txt           tests-unit
LICENSE          comfy_execution   cuda_malloc.py                  input              node_helpers.py  requirements.txt  user
README.md        comfy_extras      custom_nodes                    latent_preview.py  nodes.py         script_examples   utils
__pycache__      comfyui.log       execution.py                    main.py            notebooks        server.py         web
api_server       comfyui.prev.log  extra_model_paths.yaml.example  model_filemanager  output           temp
  on    bash   ks 3.12.3    master ≡  ?1  1                                                                             0ms 
╭─ 19:15:13 |  22 Oct, Tuesday |   in     comfui
╰─❯ python main.py
Total VRAM 16376 MB, total RAM 40071 MB
pytorch version: 2.5.0+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: /home/ks/comfui/web
/home/ks/venv/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: /home/ks/comfui/custom_nodes/websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188
Error handling request
Traceback (most recent call last):
  File "/home/ks/venv/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 477, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/aiohttp/web_app.py", line 559, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/comfui/server.py", line 63, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/comfui/server.py", line 141, in origin_only_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/comfui/app/app_settings.py", line 28, in get_settings
    return web.json_response(self.get_settings(request))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/comfui/app/app_settings.py", line 15, in get_settings
    return json.load(f)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 293, in load
    return loads(fp.read(),
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Other

i've removed al custom nodes... and honestly not sure where to start this time.

**Comment by ltdrdata** [comment]
Check the `ComfyUI/user/default/comfy.settings.json` file.
It seems that the file is broken.
