### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by jinkaka98** [comfyanonymous/ComfyUI#5346]
### Expected Behavior

# ComfyUI Error Report
## Error Details
- **Node Type:** SaveImageWithMetaData
- **Exception Type:** UnboundLocalError
- **Exception Message:** cannot access local variable 'lora_hashes_string' where it is not associated with a value
## Stack Trace
```
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\nodes\node.py", line 67, in save_images
    pnginfo_dict = self.generate_metadata(extra_metadata, save_prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\nodes\node.py", line 117, in generate_metadata
    pnginfo_dict = self.gen_pnginfo(SAMPLER_SELECTION_METHOD[0], 0, True, save_prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\nodes\node.py", line 161, in gen_pnginfo
    return Capture.gen_pnginfo_dict(inputs_before_sampler_node, inputs_before_this_node, save_civitai_sampler, save_prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\capture.py", line 149, in gen_pnginfo_dict
    if lora_hashes_string:
       ^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.4-4-g66b0961
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 6441992192
  - **VRAM Free:** 4961610852
  - **Torch VRAM Total:** 369098752
  - **Torch VRAM Free:** 25963620

## Logs
```
2024-10-24 15:48:47,756 - root - INFO - Total VRAM 6144 MB, total RAM 32668 MB
2024-10-24 15:48:47,757 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-24 15:48:47,764 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-24 15:48:47,764 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
2024-10-24 15:48:49,082 - root - INFO - Using pytorch cross attention
2024-10-24 15:48:50,777 - root - INFO - [Prompt Server] web root: E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\web
2024-10-24 15:48:51,751 - root - WARNING - Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\__init__.py", line 1, in <module>
    from .py.nodes.node import SaveImageWithMetaData, CreateExtraMetaData
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\__init__.py", line 3, in <module>
    from .hook import pre_execute, pre_get_input_data
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\hook.py", line 1, in <module>
    from .nodes.node import SaveImageWithMetaData
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData\py\nodes\node.py", line 11, in <module>
    import piexif
ModuleNotFoundError: No module named 'piexif'

2024-10-24 15:48:51,752 - root - WARNING - Cannot import E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData module for custom nodes: No module named 'piexif'
2024-10-24 15:48:51,753 - root - INFO - 
Import times for custom nodes:
2024-10-24 15:48:51,753 - root - INFO -    0.0 seconds: E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-24 15:48:51,753 - root - INFO -    0.0 seconds (IMPORT FAILED): E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SaveImageWithMetaData
2024-10-24 15:48:51,753 - root - INFO -    0.0 seconds: E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension
2024-10-24 15:48:51,753 - root - INFO -    0.4 seconds: E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-24 15:48:51,753 - root - INFO - 
2024-10-24 15:48:51,758 - root - INFO - Starting server

2024-10-24 15:48:51,758 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-24 15:51:43,289 - root - INFO - got prompt
2024-10-24 15:51:43,290 - root - WARNING - invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#51'", 'extra_info': {}}
2024-10-24 15:52:18,815 - root - INFO - got prompt
2024-10-24 15:52:18,815 - root - WARNING - invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#51'", 'extra_info': {}}
2024-10-24 15:56:42,518 - root - INFO - got prompt
2024-10-24 15:56:42,520 - root - ERROR - Failed to validate prompt for output 53:
2024-10-24 15:56:42,521 - root - ERROR - * CheckpointLoaderSimple 38:
2024-10-24 15:56:42,521 - root - ERROR -   - Value not in list: ckpt_name: 'Refiner\FluxRefiner.safetensors' not in ['againmix_v20.safetensors', 'disneyPixarCartoon_v10.safetensors', 'juggernaut_reborn.safetensors', 'v1-5-pruned-emaonly-fp16.safetensors']
2024-10-24 15:56:42,521 - root - ERROR - Output will be ignored
2024-10-24 15:56:42,614 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-24 15:56:42,615 - root - INFO - model_type EPS
2024-10-24 15:56:43,624 - root - INFO - Using pytorch attention in VAE
2024-10-24 15:56:43,626 - root - INFO - Using pytorch attention in VAE
2024-10-24 15:56:44,504 - root - INFO - Requested to load SD1ClipModel
2024-10-24 15:56:44,504 - root - INFO - Loading 1 new model
2024-10-24 15:56:44,673 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-10-24 15:56:44,924 - root - INFO - Requested to load BaseModel
2024-10-24 15:56:44,925 - root - INFO - Loading 1 new model
2024-10-24 15:56:45,790 - root - INFO - loaded completely 0.0 1639.406135559082 True
2024-10-24 15:56:52,495 - root - INFO - Requested to load AutoencoderKL
2024-10-24 15:56:52,496 - root - INFO - Loading 1 new model
2024-10-24 15:56:53,547 - root - INFO - loaded completely 0.0 319.11416244506836 True
2024-10-24 15:57:04,537 - root - INFO - Prompt executed in 22.02 seconds
2024-10-24 15:57:38,972 - root - INFO - got prompt
2024-10-24 15:57:38,973 - root - ERROR - Failed to validate prompt for output 53:
2024-10-24 15:57:38,974 - root - ERROR - * CheckpointLoaderSimple 38:
2024-10-24 15:57:38,974 - root - ERROR -   - Value not in list: ckpt_name: 'Refiner\FluxRefiner.safetensors' not in ['againmix_v20.safetensors', 'disneyPixarCartoon_v10.safetensors', 'juggernaut_reborn.safetensors', 'v1-5-pruned-emaonly-fp16.safetensors']
2024-10-24 15:57:38,974 - root - ERROR - Output will be ignored
2024-10-24 15:57:39,376 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-24 15:57:39,376 - root - INFO - model_type EPS
2024-10-24 15:57:45,816 - root - INFO - Using pytorch attention in VAE
2024-10-24 15:57:45,818 - root - INFO - Using pytorch attention in VAE
2024-10-24 15:57:48,205 - root - INFO - Requested to load SD1ClipModel
2024-10-24 15:57:48,205 - root - INFO - Loading 1 new model
2024-10-24 15:57:48,434 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-10-24 15:57:48,595 - root - INFO - Requested to load BaseModel
2024-10-24 15:57:48,595 - root - INFO - Loading 1 new model
2024-10-24 15:57:49,207 - root - INFO - loaded completely 0.0 1639.406135559082 True
2024-10-24 15:57:55,258 - root - INFO - Requested to load AutoencoderKL
2024-10-24 15:57:55,258 - root - INFO - Loading 1 new model
2024-10-24 15:57:56,257 - root - INFO - loaded completely 0.0 319.11416244506836 True
2024-10-24 15:58:03,858 - root - INFO - Prompt executed in 24.88 seconds
2024-10-24 15:58:14,100 - root - INFO - got prompt
2024-10-24 15:58:14,212 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-24 15:58:14,212 - root - INFO - model_type EPS
2024-10-24 15:58:15,246 - root - INFO - Using pytorch attention in VAE
2024-10-24 15:58:15,248 - root - INFO - Using pytorch attention in VAE
2024-10-24 15:58:15,912 - root - INFO - Requested to load AutoencoderKL
2024-10-24 15:58:15,912 - root - INFO - Loading 1 new model
2024-10-24 15:58:16,242 - root - INFO - loaded completely 0.0 319.11416244506836 True
2024-10-24 15:58:20,120 - root - INFO - Requested to load SD1ClipModel
2024-10-24 15:58:20,120 - root - INFO - Loading 1 new model
2024-10-24 15:58:20,232 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-10-24 15:58:20,288 - root - INFO - Requested to load BaseModel
2024-10-24 15:58:20,288 - root - INFO - Loading 1 new model
2024-10-24 15:58:20,988 - root - INFO - loaded completely 0.0 1639.406135559082 True
2024-10-24 15:58:40,923 - root - INFO - Requested to load AutoencoderKL
2024-10-24 15:58:40,924 - root - INFO - Loading 1 new model
2024-10-24 15:58:41,797 - root - INFO - loaded completely 0.0 319.11416244506836 True
2024-10-24 15:58:55,596 - root - ERROR - !!! Exception during processing !!! cannot access local variable 'lora_hashes_string' where it is not associated with a value
2024-10-24 15:58:55,598 - root - ERROR - Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\nodes\node.py", line 67, in save_images
    pnginfo_dict = self.generate_metadata(extra_metadata, save_prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\nodes\node.py", line 117, in generate_metadata
    pnginfo_dict = self.gen_pnginfo(SAMPLER_SELECTION_METHOD[0], 0, True, save_prompt)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\nodes\node.py", line 161, in gen_pnginfo
    return Capture.gen_pnginfo_dict(inputs_before_sampler_node, inputs_before_this_node, save_civitai_sampler, save_prompt)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-ImageMetadataExtension\py\capture.py", line 149, in gen_pnginfo_dict
    if lora_hashes_string:
       ^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'lora_hashes_string' where it is not associated with a value

2024-10-24 15:58:55,600 - root - INFO - Prompt executed in 41.50 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":57,"last_link_id":120,"nodes":[{"id":6,"type":"CLIPTextEncode","pos":{"0":280,"1":330},"size":{"0":419.8943176269531,"1":156.7379913330078},"flags":{"collapsed":true},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":94},{"name":"text","type":"STRING","link":87,"widget":{"name":"text"}}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[107],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["closeup photo of a beautiful girl from a dream"]},{"id":7,"type":"CLIPTextEncode","pos":{"0":340,"1":370},"size":{"0":417.61761474609375,"1":152.91053771972656},"flags":{"collapsed":true},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":95}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[108],"slot_index":0}],"title":"Empty Negative","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""]},{"id":46,"type":"PrimitiveNode","pos":{"0":130,"1":160},"size":{"0":360,"1":130},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"STRING","type":"STRING","links":[86,87],"slot_index":0,"widget":{"name":"text"}}],"title":"Prompt","properties":{"Run widget replace on values":false},"widgets_values":["closeup photo of a beautiful girl from a dream"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":160,"1":550},"size":{"0":317.3262023925781,"1":106},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[106],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[960,1280,4]},{"id":42,"type":"CLIPTextEncode","pos":{"0":1320,"1":790},"size":{"0":320,"1":54},"flags":{"collapsed":false},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":72},{"name":"text","type":"STRING","link":86,"widget":{"name":"text"}}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[110],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["closeup photo of a beautiful girl from a dream"]},{"id":8,"type":"VAEDecode","pos":{"0":830,"1":190},"size":{"0":150,"1":50},"flags":{},"order":9,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":116},{"name":"vae","type":"VAE","link":88}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[26,118],"slot_index":0}],"title":"Decode Flux","properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":57,"type":"VAEEncode","pos":{"0":990,"1":190},"size":{"0":150,"1":50},"flags":{},"order":11,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":118},{"name":"vae","type":"VAE","link":119}],"outputs":[{"name":"LATENT","type":"LATENT","links":[120],"slot_index":0,"shape":3}],"title":"Encode Flux","properties":{"Node name for S&R":"VAEEncode"},"widgets_values":[]},{"id":56,"type":"VAEDecode","pos":{"0":1150,"1":190},"size":{"0":150,"1":50},"flags":{},"order":13,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":115},{"name":"vae","type":"VAE","link":114}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[113],"slot_index":0}],"title":"Decode Refiner","properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":54,"type":"KSamplerAdvanced","pos":{"0":500,"1":190},"size":{"0":315,"1":334},"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":109},{"name":"positive","type":"CONDITIONING","link":107},{"name":"negative","type":"CONDITIONING","link":108},{"name":"latent_image","type":"LATENT","link":106}],"outputs":[{"name":"LATENT","type":"LATENT","links":[116],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSamplerAdvanced"},"widgets_values":["enable",418855271472732,"fixed",3,1,"euler","normal",0,10000,"enable"]},{"id":43,"type":"CLIPTextEncode","pos":{"0":1320,"1":670},"size":{"0":320,"1":76},"flags":{"collapsed":false},"order":7,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":74}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[111],"slot_index":0}],"title":"Empty Negative","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""]},{"id":55,"type":"KSamplerAdvanced","pos":{"0":1320,"1":290},"size":{"0":320,"1":334},"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":117},{"name":"positive","type":"CONDITIONING","link":110},{"name":"negative","type":"CONDITIONING","link":111},{"name":"latent_image","type":"LATENT","link":120}],"outputs":[{"name":"LATENT","type":"LATENT","links":[115],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSamplerAdvanced"},"widgets_values":["enable",878506494596043,"randomize",6,2,"dpmpp_sde","karras",3,6,"disable"]},{"id":17,"type":"PreviewImage","pos":{"0":830,"1":278},"size":{"0":470,"1":650},"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":26}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":53,"type":"SaveImageWithMetaData","pos":{"0":1659,"1":149},"size":{"0":540,"1":960},"flags":{},"order":14,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":113},{"name":"extra_metadata","type":"EXTRA_METADATA","link":null,"shape":7}],"outputs":[],"properties":{"Node name for S&R":"SaveImageWithMetaData"},"widgets_values":["ComfyUI","Farthest",0]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":130,"1":410},"size":{"0":350,"1":100},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[109],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[94,95],"slot_index":1},{"name":"VAE","type":"VAE","links":[88],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["disneyPixarCartoon_v10.safetensors"]},{"id":38,"type":"CheckpointLoaderSimple","pos":{"0":1317,"1":127},"size":{"0":320,"1":100},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[117],"slot_index":0,"shape":3},{"name":"CLIP","type":"CLIP","links":[72,74],"slot_index":1,"shape":3},{"name":"VAE","type":"VAE","links":[114,119],"slot_index":2,"shape":3}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["juggernaut_reborn.safetensors"]}],"links":[[26,8,0,17,0,"IMAGE"],[72,38,1,42,0,"CLIP"],[74,38,1,43,0,"CLIP"],[86,46,0,42,1,"STRING"],[87,46,0,6,1,"STRING"],[88,4,2,8,1,"VAE"],[94,4,1,6,0,"CLIP"],[95,4,1,7,0,"CLIP"],[106,5,0,54,3,"LATENT"],[107,6,0,54,1,"CONDITIONING"],[108,7,0,54,2,"CONDITIONING"],[109,4,0,54,0,"MODEL"],[110,42,0,55,1,"CONDITIONING"],[111,43,0,55,2,"CONDITIONING"],[113,56,0,53,0,"IMAGE"],[114,38,2,56,1,"VAE"],[115,55,0,56,0,"LATENT"],[116,54,0,8,0,"LATENT"],[117,38,0,55,0,"MODEL"],[118,8,0,57,0,"IMAGE"],[119,38,2,57,1,"VAE"],[120,57,0,55,3,"LATENT"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.38554328942953175,"offset":[2161.930933366446,373.5510041476738]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

### Actual Behavior

bug

### Steps to Reproduce

bug

### Debug Logs

```powershell
bug
```

**Comment by LukeG89** [comment]
The error is from a custom node, not ComfyUI.
You need to file a bug report to the custom node repository. 

"Install Missing Custom Nodes" suggested me two similar custom nodes:
- [ComfyUI-SaveImageWithMetaData](https://github.com/nkchocoai/ComfyUI-SaveImageWithMetaData)
- [ComfyUI-ImageMetadataExtension](https://github.com/edelvarden/ComfyUI-ImageMetadataExtension) 

I don't know which one you have.

**Comment by kalle07** [comment]
i have same error !
so only these two custom nodes exist to save metadata for CIVITAi 

maybe you should write a working one  ;)
