### ISSUE TITLE
RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.

### ISSUE THREAD

**Issue by kairin** [comfyanonymous/ComfyUI#5365]
### Your question

okay so below is the first error that i encountered when trying to use a SUPIR workflow.

the subsequent steps are what i used to get my comfyui running but with other errors...

### Logs

```powershell
ddd  venv
Command 'nvcc' not found, but can be installed with:
sudo apt install nvidia-cuda-toolkit
Fri Oct 25 22:39:20 2024
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 565.51.01              Driver Version: 565.90         CUDA Version: 12.7     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4080 ...    On  |   00000000:0B:00.0  On |                  N/A |
|  0%   40C    P2             17W /  320W |     602MiB /  16376MiB |      7%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A        35      G   /Xwayland                                   N/A      |
|    0   N/A  N/A    619741      C   /python3.12                                 N/A      |
+-----------------------------------------------------------------------------------------+
VIRTUAL_ENV=/home/ks/venv
VIRTUAL_ENV_PROMPT=(venv)
ddd  venv
CODEOWNERS       app               comfyui.prev2.log               fix_torch.py       models           pytest.ini        tests-unit
CONTRIBUTING.md  comfy             comfyui_screenshot.png          folder_paths.py    new_updater.py   requirements.txt  user
LICENSE          comfy_execution   cuda_malloc.py                  input              node_helpers.py  script_examples   utils
README.md        comfy_extras      custom_nodes                    latent_preview.py  nodes.py         server.py         web
__pycache__      comfyui.log       execution.py                    main.py            notebooks        temp
api_server       comfyui.prev.log  extra_model_paths.yaml.example  model_filemanager  output           tests
  on    bash   ks 3.12.3    master ≡                                                                                      0ms 
╭─ 22:39:29 |  25 Oct, Friday |   in     venv  comf
╰─❯ pip3 install -U xformers --index-url https://download.pytorch.org/whl/cu124
Looking in indexes: https://download.pytorch.org/whl/cu124
Collecting xformers
  Downloading https://download.pytorch.org/whl/cu124/xformers-0.0.28.post2-cp312-cp312-manylinux_2_28_x86_64.whl (20.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.6/20.6 MB 10.5 MB/s eta 0:00:00
Requirement already satisfied: numpy in /home/ks/venv/lib/python3.12/site-packages (from xformers) (1.26.4)
Collecting torch==2.5.0 (from xformers)
  Downloading https://download.pytorch.org/whl/cu124/torch-2.5.0%2Bcu124-cp312-cp312-linux_x86_64.whl (908.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 908.2/908.2 MB 9.9 MB/s eta 0:00:00
Requirement already satisfied: filelock in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (4.12.2)
Requirement already satisfied: networkx in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (3.4.2)
Requirement already satisfied: jinja2 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (3.1.4)
Requirement already satisfied: fsspec in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (2024.10.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.4.127 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.4.127 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.4.127)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.4.127 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.4.127)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.4.5.8 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.4.5.8)
Requirement already satisfied: nvidia-cufft-cu12==11.2.1.3 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (11.2.1.3)
Requirement already satisfied: nvidia-curand-cu12==10.3.5.147 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (10.3.5.147)
Requirement already satisfied: nvidia-cusolver-cu12==11.6.1.9 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (11.6.1.9)
Requirement already satisfied: nvidia-cusparse-cu12==12.3.1.170 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.3.1.170)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.4.127 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.4.127)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.4.127 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (12.4.127)
Requirement already satisfied: triton==3.1.0 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (3.1.0)
Requirement already satisfied: setuptools in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (75.2.0)
Requirement already satisfied: sympy==1.13.1 in /home/ks/venv/lib/python3.12/site-packages (from torch==2.5.0->xformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /home/ks/venv/lib/python3.12/site-packages (from sympy==1.13.1->torch==2.5.0->xformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /home/ks/venv/lib/python3.12/site-packages (from jinja2->torch==2.5.0->xformers) (3.0.2)
Installing collected packages: torch, xformers
  Attempting uninstall: torch
    Found existing installation: torch 2.5.1+cu124
    Uninstalling torch-2.5.1+cu124:
      Successfully uninstalled torch-2.5.1+cu124
Successfully installed torch-2.5.0+cu124 xformers-0.0.28.post2
  on    bash   ks 3.12.3    master ≡                                                                             1m 38s 383ms 
╭─ 22:41:02 |  25 Oct, Friday |   in     venv  comf
╰─❯ pip install upgrade torch
ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade
  on    bash   ks 3.12.3    master ≡                                                                                    564ms 
╭─ 22:41:19 |  25 Oct, Friday |   in     venv  comf
╰─❯ python main.py
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-10-25 22:41:38.549009
** Platform: Linux
** Python version: 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
** Python executable: /home/ks/venv/bin/python
** ComfyUI Path: /home/ks/venv/comf
** Log path: /home/ks/venv/comf/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /home/ks/venv/comf/custom_nodes/rgthree-comfy
   0.5 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-Manager

Total VRAM 16376 MB, total RAM 40071 MB
pytorch version: 2.5.0+cu124
xformers version: 0.0.28.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /home/ks/venv/comf/web
/home/ks/venv/lib/python3.12/site-packages/kornia/feature/lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.51.8)
### ComfyUI Revision: 2785 [52810907] | Released on '2024-10-24'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
/home/ks/venv/lib/python3.12/site-packages/albumentations/__init__.py:24: UserWarning: A new version of Albumentations is available: 1.4.20 (you have 0.0.19). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.5.0+cu124
Total VRAM 16376 MB, total RAM 40071 MB
pytorch version: 2.5.0+cu124
xformers version: 0.0.28.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync

[rgthree-comfy] Loaded 42 exciting nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/home/ks/venv/comf/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Don't let yesterday take up too much of today." - Will Rogers


Import times for custom nodes:
   0.0 seconds: /home/ks/venv/comf/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/ks/venv/comf/custom_nodes/Skimmed_CFG
   0.0 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-AutomaticCFG
   0.0 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI_JPS-Nodes
   0.0 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-Image-Saver
   0.0 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-KJNodes
   0.0 seconds: /home/ks/venv/comf/custom_nodes/rgthree-comfy
   0.0 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-Manager
   0.2 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI_ExtraModels
   0.4 seconds: /home/ks/venv/comf/custom_nodes/comfyui_face_parsing
   0.8 seconds: /home/ks/venv/comf/custom_nodes/comfyui-reactor-node
   0.8 seconds: /home/ks/venv/comf/custom_nodes/was-node-suite-comfyui
   0.9 seconds: /home/ks/venv/comf/custom_nodes/ComfyUI-SUPIR

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: /home/ks/venv/comf/custom_nodes/ComfyUI-Manager/extension-node-map.json [DONE]
got prompt
model weight dtype torch.float8_e4m3fn, manual cast: torch.float16
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Model maximum sigma: 14.614640235900879 / Model minimum sigma: 0.029167160391807556
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
Requested to load SDXL
Loading 1 new model
loaded completely 0.0 2448.5241737365723 True
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:31<00:00,  3.18it/s]
Requested to load AutoencoderKL
Loading 1 new model
loaded completely 0.0 159.55708122253418 True
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Model maximum sigma: 14.614640235900879 / Model minimum sigma: 0.029167160391807556
Loading weights to:  cpu
Diffusion using fp16
Using XFORMERS
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Attempting to load SDXL model from node inputs
Requested to load SDXL
Loading 1 new model
loaded completely 0.0 4897.0483474731445 True
Loading first clip model from SDXL checkpoint
Requested to load SDXLClipModel
Loading 1 new model
loaded completely 0.0 1560.802734375 True
Loading second clip model from SDXL checkpoint
Attempting to load SUPIR model: [/home/ks/venv/comf/models/checkpoints/SUPIR_pruned/SUPIR-v0Q_fp16.safetensors]
Loaded state_dict from [/home/ks/venv/comf/models/checkpoints/SUPIR_pruned/SUPIR-v0Q_fp16.safetensors]
Encoder using bf16
[Tiled VAE]: input_size: torch.Size([1, 3, 2688, 1536]), tile_size: 512, padding: 32
[Tiled VAE]: split to 6x3 = 18 tiles. Optimal tile size 512x448, original tile size 512x512
[Tiled VAE]: Executing Encoder Task Queue: 100%|████████████████████████████████████████████████████████| 1638/1638 [00:06<00:00, 242.84it/s]
[Tiled VAE]: Done in 7.317s, max VRAM alloc 664.499 MB
[Tiled VAE]: input_size: torch.Size([1, 4, 336, 192]), tile_size: 64, padding: 11
[Tiled VAE]: split to 5x3 = 15 tiles. Optimal tile size 64x64, original tile size 64x64
[Tiled VAE]: Executing Decoder Task Queue: 100%|████████████████████████████████████████████████████████| 1845/1845 [00:16<00:00, 113.50it/s]
[Tiled VAE]: Done in 16.819s, max VRAM alloc 1760.142 MB
captions:  [['']]
Batch captioning
Could not load library libcuda.so. Error: libcuda.so: cannot open shared object file: No such file or directory
Could not load library libcuda.so. Error: libcuda.so: cannot open shared object file: No such file or directory
Could not load library libcuda.so. Error: libcuda.so: cannot open shared object file: No such file or directory
!!! Exception during processing !!! cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.
Traceback (most recent call last):
  File "/home/ks/venv/comf/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/comf/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/comf/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/ks/venv/comf/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/comf/custom_nodes/ComfyUI-SUPIR/nodes_v2.py", line 637, in condition
    _c, _uc = SUPIR_model.conditioner.get_unconditional_conditioning(cond, uncond)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/comf/custom_nodes/ComfyUI-SUPIR/sgm/modules/encoders/modules.py", line 190, in get_unconditional_conditioning
    c = self(batch_c)
        ^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/comf/custom_nodes/ComfyUI-SUPIR/sgm/modules/encoders/modules.py", line 211, in forward
    emb_out = embedder(batch[embedder.input_key])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/comf/custom_nodes/ComfyUI-SUPIR/sgm/modules/encoders/modules.py", line 503, in forward
    outputs = self.transformer(
              ^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 997, in forward
    return self.text_model(
           ^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 901, in forward
    encoder_outputs = self.encoder(
                      ^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 824, in forward
    layer_outputs = encoder_layer(
                    ^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 559, in forward
    hidden_states, attn_weights = self.self_attn(
                                  ^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ks/venv/lib/python3.12/site-packages/transformers/models/clip/modeling_clip.py", line 491, in forward
    attn_output = torch.nn.functional.scaled_dot_product_attention(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: cuDNN Frontend error: [cudnn_frontend] Error: No execution plans support the graph.
```

### Other

when searching online this is the first item that i found similar to what i was facing:

https://github.com/huggingface/diffusers/issues/9704#issuecomment-2423400790

**Comment by Atlas3DSS** [comment]
the latest comfyui update caused this issue to start occuring for me - everything was working before.

**Comment by jurassicjordan** [comment]
im getting this issue too, this issue should be reopened

**Comment by BobLiu20** [comment]
+1
