### ISSUE TITLE
Error: AV_ControlNetPreprocessor 'resolution' is not in list

### ISSUE THREAD

**Issue by Rusty-sk** [comfyanonymous/ComfyUI#5367]
### Your question

First I am relatively new to ComfyUI so please be gentle.

I have looked at many many resources and updated segmentate_anything, changed the directory spelling, tried updating comfyui, and installing and uninstalling the node repeatedly to solve this error. I believe it to be an issue getting the list but nothing has solved my issues.

Ideas?

### Logs

```powershell
!!! Exception during processing !!! 'resolution' is not in list
Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Art-Venture\modules\controlnet\__init__.py", line 136, in detect_controlnet
    image = apply_preprocessor(image, preprocessor, resolution=resolution)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Art-Venture\modules\controlnet\__init__.py", line 38, in apply_preprocessor
    resolution_idx = list(optional_args).index("resolution")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'resolution' is not in list
```

**Comment by ltdrdata** [comment]
Please move this issue to comfyui-art-venture repo.
https://github.com/sipherxyz/comfyui-art-venture
