### ISSUE TITLE
c1['c_adm'].shape != c2['c_adm'].shape: AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by asd417** [comfyanonymous/ComfyUI#537]
Got an error while trying out clip vision with area conditioning.
![Capture](https://user-images.githubusercontent.com/33945246/233145747-36422520-79a9-424b-ae32-db785243d29a.PNG)

```got prompt
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
LatentDiffusion: Running in eps-prediction mode
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
DiffusionWrapper has 859.52 M params.
  0%|                                                                                                                                      | 0/80 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\execution.py", line 184, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\execution.py", line 60, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\execution.py", line 60, in recursive_execute
    executed += recursive_execute(server, prompt, outputs, input_unique_id, extra_data)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\execution.py", line 69, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\nodes.py", line 841, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\nodes.py", line 810, in common_ksampler
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 581, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 277, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 265, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 244, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 174, in calc_cond_uncond_batch
    if can_concat_cond(to_run[x][0], first[0]):
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 123, in can_concat_cond
    return cond_equal_size(c1[2], c2[2])
  File "C:\Users\locti\OneDrive\Documents\stable_diffusion_git\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 101, in cond_equal_size
    if c1['c_adm'].shape != c2['c_adm'].shape:
AttributeError: 'list' object has no attribute 'shape'```

**Comment by comfyanonymous** [comment]
Can you give me a copy of a workflow that causes the bug?

**Comment by comfyanonymous** [comment]
Should be fixed now, it's a bug that happened when using unCLIPConditioning on a non unCLIP model.

**Comment by asd417** [comment]
[workflow (10).txt](https://github.com/comfyanonymous/ComfyUI/files/11292462/workflow.10.txt)
![Capture](https://user-images.githubusercontent.com/33945246/233547473-dbacb3fa-ab61-4c03-9b1a-96d933949210.PNG)
Isn't this a unclipmodel though? I included a workflow in txt format

**Comment by comfyanonymous** [comment]
You need to use unCLIPCheckpointLoader to load the unclip checkpoint and use the MODEL output from it.

**Comment by asd417** [comment]
but the clip vision encoder only takes clip_vision and image input?

**Comment by comfyanonymous** [comment]
the unCLIP checkpoint contains a model that is slightly different from a regular model: one that can accept a CLIPVision embedding.

**Comment by asd417** [comment]
Does that mean I cant use unclip with other pretrained models?

**Comment by comfyanonymous** [comment]
it can only be used with unclip models.
