### ISSUE TITLE
comfyUI ImageResize+ question

### ISSUE THREAD

**Issue by JaegerNIE** [comfyanonymous/ComfyUI#5394]
### Your question

ImageResize+ error prompt

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** ImageResize+
- **Exception Type:** numpy.core._exceptions._ArrayMemoryError
- **Exception Message:** Unable to allocate 40.5 MiB for an array with shape (1536, 2304, 3) and data type float32
## Stack Trace

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials-main\image.py", line 431, in execute
    outputs = comfy.utils.lanczos(outputs, width, height)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 686, in lanczos
    images = [Image.fromarray(np.clip(255. * image.movedim(0, -1).cpu().numpy(), 0, 255).astype(np.uint8)) for image in samples]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 686, in <listcomp>
    images = [Image.fromarray(np.clip(255. * image.movedim(0, -1).cpu().numpy(), 0, 255).astype(np.uint8)) for image in samples]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^

  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\_methods.py", line 99, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 7109099658
  - **Torch VRAM Total:** 4496293888
  - **Torch VRAM Free:** 97271946

## Logs
```
2024-10-28 16:09:55,075 - root - INFO - Total VRAM 12282 MB, total RAM 16002 MB
2024-10-28 16:09:55,075 - root - INFO - pytorch version: 2.4.1+cu124
2024-10-28 16:09:55,076 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-28 16:09:55,076 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 Laptop GPU : cudaMallocAsync
2024-10-28 16:09:55,834 - root - INFO - Using pytorch cross attention
2024-10-28 16:09:57,007 - root - INFO - [Prompt Server] web root: D:\comfyui\ComfyUI_windows_portable\ComfyUI\web
2024-10-28 16:09:58,159 - root - WARNING - Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_windows_portable\\__init__.py'

2024-10-28 16:09:58,160 - root - WARNING - Cannot import D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_windows_portable module for custom nodes: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI_windows_portable\\__init__.py'
2024-10-28 16:09:58,177 - root - INFO - 
Import times for custom nodes:
2024-10-28 16:09:58,178 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-28 16:09:58,178 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUi_NNLatentUpscale-master
2024-10-28 16:09:58,178 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_windows_portable
2024-10-28 16:09:58,178 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus-main
2024-10-28 16:09:58,178 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet-main
2024-10-28 16:09:58,179 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation-main
2024-10-28 16:09:58,179 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui-main
2024-10-28 16:09:58,179 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-workspace-manager
2024-10-28 16:09:58,179 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials-main
2024-10-28 16:09:58,179 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved-main
2024-10-28 16:09:58,179 - root - INFO -    0.0 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux-main
2024-10-28 16:09:58,179 - root - INFO -    0.1 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-28 16:09:58,180 - root - INFO -    0.2 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-28 16:09:58,180 - root - INFO -    0.3 seconds: D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
2024-10-28 16:09:58,180 - root - INFO - 
2024-10-28 16:09:58,186 - root - INFO - Starting server

2024-10-28 16:09:58,186 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-28 16:11:04,289 - root - INFO - got prompt
2024-10-28 16:11:04,368 - root - ERROR - Failed to validate prompt for output 52:
2024-10-28 16:11:04,368 - root - ERROR - * LoadImage 165:
2024-10-28 16:11:04,368 - root - ERROR -   - Custom validation failed for node: image - Invalid image file: 5.png
2024-10-28 16:11:04,368 - root - ERROR - Output will be ignored
2024-10-28 16:11:04,402 - root - ERROR - Failed to validate prompt for output 27:
2024-10-28 16:11:04,402 - root - ERROR - Output will be ignored
2024-10-28 16:11:04,437 - root - ERROR - Failed to validate prompt for output 210:
2024-10-28 16:11:04,438 - root - ERROR - Output will be ignored
2024-10-28 16:11:04,486 - root - WARNING - WARNING: [Errno 2] No such file or directory: 'D:\\comfyui\\ComfyUI_windows_portable\\ComfyUI\\input\\5.png'
2024-10-28 16:11:12,060 - root - INFO - Prompt executed in 7.59 seconds
2024-10-28 16:11:23,308 - root - INFO - got prompt
2024-10-28 16:11:23,872 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-10-28 16:11:23,883 - root - INFO - model_type EPS
2024-10-28 16:11:25,990 - root - INFO - Using pytorch attention in VAE
2024-10-28 16:11:25,992 - root - INFO - Using pytorch attention in VAE
2024-10-28 16:11:26,360 - root - INFO - loaded straight to GPU
2024-10-28 16:11:26,361 - root - INFO - Requested to load BaseModel
2024-10-28 16:11:26,361 - root - INFO - Loading 1 new model
2024-10-28 16:11:26,376 - root - INFO - loaded completely 0.0 1639.406135559082 True
2024-10-28 16:11:30,190 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-28 16:11:30,190 - root - INFO - Loading 1 new model
2024-10-28 16:11:30,839 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-10-28 16:11:31,935 - root - INFO - Requested to load SD1ClipModel
2024-10-28 16:11:31,935 - root - INFO - Loading 1 new model
2024-10-28 16:11:32,019 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-10-28 16:11:32,146 - root - WARNING - warning, embedding:easynegative does not exist, ignoring
2024-10-28 16:11:34,054 - root - INFO - Requested to load AutoencoderKL
2024-10-28 16:11:34,054 - root - INFO - Loading 1 new model
2024-10-28 16:11:34,182 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-28 16:11:44,366 - root - INFO - Requested to load ControlNet
2024-10-28 16:11:44,366 - root - INFO - Requested to load BaseModel
2024-10-28 16:11:44,366 - root - INFO - Requested to load AnimateDiffModel
2024-10-28 16:11:44,366 - root - INFO - Requested to load ControlNet
2024-10-28 16:11:44,367 - root - INFO - Loading 4 new models
2024-10-28 16:11:46,262 - root - INFO - loaded completely 0.0 689.0852355957031 True
2024-10-28 16:11:48,393 - root - INFO - loaded completely 0.0 1639.406135559082 True
2024-10-28 16:11:48,921 - root - INFO - loaded completely 0.0 864.4281005859375 True
2024-10-28 16:11:49,228 - root - INFO - loaded completely 0.0 689.0852355957031 True
2024-10-28 16:15:54,343 - root - INFO - Requested to load AutoencoderKL
2024-10-28 16:15:54,343 - root - INFO - Loading 1 new model
2024-10-28 16:15:54,477 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-28 16:16:16,385 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-10-28 16:16:18,997 - root - INFO - Requested to load ControlNet
2024-10-28 16:16:18,997 - root - INFO - Loading 1 new model
2024-10-28 16:17:39,581 - aiohttp.server - ERROR - Error handling request
Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1073, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohappyeyeballs\impl.py", line 104, in start_connection
    raise first_exception
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohappyeyeballs\impl.py", line 81, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohappyeyeballs\impl.py", line 166, in _connect_sock
    await loop.sock_connect(sock, address)
  File "asyncio\proactor_events.py", line 726, in sock_connect
  File "asyncio\windows_events.py", line 854, in _poll
  File "asyncio\windows_events.py", line 641, in finish_connect
OSError: [WinError 121] 信号灯超时时间已到

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 462, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 537, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\server.py", line 61, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\server.py", line 73, in cors_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main\glob\manager_server.py", line 1186, in get_notice
    async with session.get(f"https://{url}{path}") as response:
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 1353, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\client.py", line 657, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 564, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 975, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1350, in _create_direct_connection
    raise last_exc
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1319, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\connector.py", line 1088, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host github.com:443 ssl:default [信号灯超时时间已到]
2024-10-28 16:29:45,558 - root - INFO - Requested to load AutoencoderKL
2024-10-28 16:29:45,559 - root - INFO - Loading 1 new model
2024-10-28 16:29:45,686 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-28 16:30:39,303 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-10-28 16:35:38,681 - root - ERROR - !!! Exception during processing !!! Unable to allocate 40.5 MiB for an array with shape (1536, 2304, 3) and data type float32
2024-10-28 16:35:38,729 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials-main\image.py", line 431, in execute
    outputs = comfy.utils.lanczos(outputs, width, height)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 686, in lanczos
    images = [Image.fromarray(np.clip(255. * image.movedim(0, -1).cpu().numpy(), 0, 255).astype(np.uint8)) for image in samples]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 686, in <listcomp>
    images = [Image.fromarray(np.clip(255. * image.movedim(0, -1).cpu().numpy(), 0, 255).astype(np.uint8)) for image in samples]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\_methods.py", line 99, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 40.5 MiB for an array with shape (1536, 2304, 3) and data type float32

2024-10-28 16:35:38,748 - root - INFO - Prompt executed in 1455.28 seconds
2024-10-28 16:38:16,087 - root - INFO - got prompt
2024-10-28 16:38:17,908 - root - INFO - Requested to load CLIPVisionModelProjection
2024-10-28 16:38:17,909 - root - INFO - Loading 1 new model
2024-10-28 16:38:21,617 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-10-28 16:38:22,477 - root - INFO - Requested to load ControlNet
2024-10-28 16:38:22,477 - root - INFO - Requested to load BaseModel
2024-10-28 16:38:22,477 - root - INFO - Loading 2 new models
2024-10-28 16:42:27,820 - root - INFO - Requested to load AutoencoderKL
2024-10-28 16:42:27,820 - root - INFO - Loading 1 new model
2024-10-28 16:42:27,923 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-28 16:42:49,643 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-10-28 16:42:52,179 - root - INFO - Requested to load ControlNet
2024-10-28 16:42:52,179 - root - INFO - Loading 1 new model
2024-10-28 16:56:00,695 - root - INFO - Requested to load AutoencoderKL
2024-10-28 16:56:00,695 - root - INFO - Loading 1 new model
2024-10-28 16:56:00,823 - root - INFO - loaded completely 0.0 159.55708122253418 True
2024-10-28 16:56:53,640 - asyncio - ERROR - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "asyncio\events.py", line 84, in _run
  File "asyncio\proactor_events.py", line 165, in _call_connection_lost
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
2024-10-28 17:02:34,512 - root - ERROR - !!! Exception during processing !!! Unable to allocate 40.5 MiB for an array with shape (1536, 2304, 3) and data type float32
2024-10-28 17:02:34,554 - root - ERROR - Traceback (most recent call last):
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials-main\image.py", line 431, in execute
    outputs = comfy.utils.lanczos(outputs, width, height)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 686, in lanczos
    images = [Image.fromarray(np.clip(255. * image.movedim(0, -1).cpu().numpy(), 0, 255).astype(np.uint8)) for image in samples]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 686, in <listcomp>
    images = [Image.fromarray(np.clip(255. * image.movedim(0, -1).cpu().numpy(), 0, 255).astype(np.uint8)) for image in samples]
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 2169, in clip
    return _wrapfunc(a, 'clip', a_min, a_max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numpy\core\_methods.py", line 99, in _clip
    return um.clip(a, min, max, out=out, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 40.5 MiB for an array with shape (1536, 2304, 3) and data type float32

2024-10-28 17:02:34,588 - root - INFO - Prompt executed in 1458.32 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
Remove ComfyUI_essentials-main and install ComfyUI_essentials via ComfyUI-Manager or use git clone.

If you install by downloading the zip file that way, you won't be able to properly update it.
