### ISSUE TITLE
Efficient Loader: too many values to unpack (expected 3)

### ISSUE THREAD

**Issue by deepakpf** [comfyanonymous/ComfyUI#5398]
### Your question

I am having this issue when running a workflow called [Easy Theme Photo](https://openart.ai/workflows/whmc76/easy-theme-photo/YnSmJrwnJ0Bs4CCzCLy7)

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** Efficient Loader
- **Exception Type:** ValueError
- **Exception Message:** too many values to unpack (expected 3)
## Stack Trace

  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")

```
## System Information
- **ComfyUI Version:** v0.2.4-12-g669d9e4
- **Arguments:** C:\StabilityMatrix\Data\Packages\ComfyUI\main.py --normalvram --preview-method auto
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 4294443008
  - **VRAM Free:** 3463865959
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-28 22:12:04,170 - root - INFO - Total VRAM 4096 MB, total RAM 7919 MB
2024-10-28 22:12:04,170 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-28 22:12:04,170 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-28 22:12:04,171 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
2024-10-28 22:12:06,240 - root - INFO - Using pytorch cross attention
2024-10-28 22:12:08,486 - root - INFO - [Prompt Server] web root: C:\StabilityMatrix\Data\Packages\ComfyUI\web
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path checkpoints C:\StabilityMatrix\Data\Models\StableDiffusion
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path vae C:\StabilityMatrix\Data\Models\VAE
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path loras C:\StabilityMatrix\Data\Models\Lora
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path loras C:\StabilityMatrix\Data\Models\LyCORIS
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path upscale_models C:\StabilityMatrix\Data\Models\ESRGAN
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path upscale_models C:\StabilityMatrix\Data\Models\RealESRGAN
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path upscale_models C:\StabilityMatrix\Data\Models\SwinIR
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path embeddings C:\StabilityMatrix\Data\Models\TextualInversion
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path hypernetworks C:\StabilityMatrix\Data\Models\Hypernetwork
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path controlnet C:\StabilityMatrix\Data\Models\ControlNet
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path controlnet C:\StabilityMatrix\Data\Models\T2IAdapter
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path clip C:\StabilityMatrix\Data\Models\CLIP
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path clip_vision C:\StabilityMatrix\Data\Models\InvokeClipVision
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path diffusers C:\StabilityMatrix\Data\Models\Diffusers
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path gligen C:\StabilityMatrix\Data\Models\GLIGEN
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path vae_approx C:\StabilityMatrix\Data\Models\ApproxVAE
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path ipadapter C:\StabilityMatrix\Data\Models\IpAdapter
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path ipadapter C:\StabilityMatrix\Data\Models\InvokeIpAdapters15
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path ipadapter C:\StabilityMatrix\Data\Models\InvokeIpAdaptersXl
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path prompt_expansion C:\StabilityMatrix\Data\Models\PromptExpansion
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path ultralytics C:\StabilityMatrix\Data\Models\Ultralytics
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path ultralytics_bbox C:\StabilityMatrix\Data\Models\Ultralytics\bbox
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path ultralytics_segm C:\StabilityMatrix\Data\Models\Ultralytics\segm
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path sams C:\StabilityMatrix\Data\Models\Sams
2024-10-28 22:12:08,486 - root - INFO - Adding extra search path diffusion_models C:\StabilityMatrix\Data\Models\unet
2024-10-28 22:12:16,065 - root - INFO - Total VRAM 4096 MB, total RAM 7919 MB
2024-10-28 22:12:16,065 - root - INFO - pytorch version: 2.5.0+cu124
2024-10-28 22:12:16,067 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-28 22:12:16,067 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
2024-10-28 22:12:17,686 - root - INFO - --------------
2024-10-28 22:12:17,686 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-10-28 22:12:17,691 - root - INFO - ChatGPT.available False
2024-10-28 22:12:17,693 - root - INFO - edit_mask.available True
2024-10-28 22:12:19,018 - root - INFO - ClipInterrogator.available True
2024-10-28 22:12:19,246 - root - INFO - PromptGenerate.available True
2024-10-28 22:12:19,246 - root - INFO - ChinesePrompt.available True
2024-10-28 22:12:19,246 - root - INFO - RembgNode_.available True
2024-10-28 22:12:20,047 - root - INFO - TripoSR.available
2024-10-28 22:12:20,048 - root - INFO - MiniCPMNode.available
2024-10-28 22:12:20,050 - root - INFO - Scenedetect.available False
2024-10-28 22:12:20,160 - root - INFO - FishSpeech.available False
2024-10-28 22:12:20,164 - root - INFO - SenseVoice.available False
2024-10-28 22:12:20,167 - root - INFO - Whisper.available False
2024-10-28 22:12:20,178 - root - INFO - FalVideo.available
2024-10-28 22:12:20,179 - root - INFO - [93m -------------- [0m
2024-10-28 22:12:27,730 - root - INFO - 
Import times for custom nodes:
2024-10-28 22:12:27,730 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\sdxl_prompt_styler
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-YOLO
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Gemini_Flash
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-copilot
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUi_PromptStylers
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus.old
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-photoshop
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\masquerade-nodes-comfyui
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-28 22:12:27,731 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyLiterals
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-stablesr
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-various
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyMath
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes-main
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\rgthree-comfy
2024-10-28 22:12:27,732 - root - INFO -    0.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-28 22:12:27,733 - root - INFO -    0.1 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-28 22:12:27,733 - root - INFO -    0.1 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-28 22:12:27,733 - root - INFO -    0.1 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfy_mtb
2024-10-28 22:12:27,733 - root - INFO -    0.1 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
2024-10-28 22:12:27,733 - root - INFO -    0.2 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-10-28 22:12:27,733 - root - INFO -    0.2 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\eden_comfy_pipelines
2024-10-28 22:12:27,733 - root - INFO -    0.4 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Gemini
2024-10-28 22:12:27,733 - root - INFO -    0.7 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-28 22:12:27,733 - root - INFO -    0.8 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-28 22:12:27,733 - root - INFO -    0.9 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\clipseg.py
2024-10-28 22:12:27,733 - root - INFO -    1.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-10-28 22:12:27,733 - root - INFO -    1.0 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-28 22:12:27,733 - root - INFO -    1.3 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-art-venture
2024-10-28 22:12:27,733 - root - INFO -    1.9 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Allor
2024-10-28 22:12:27,733 - root - INFO -    2.9 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
2024-10-28 22:12:27,733 - root - INFO -    2.9 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-28 22:12:27,734 - root - INFO -    3.2 seconds: C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\comfyui-mixlab-nodes
2024-10-28 22:12:27,734 - root - INFO - 
2024-10-28 22:12:27,756 - root - INFO - Starting server

2024-10-28 22:12:27,757 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-28 22:14:41,791 - root - INFO - got prompt
2024-10-28 22:14:54,367 - root - ERROR - !!! Exception during processing !!! too many values to unpack (expected 3)
2024-10-28 22:14:54,417 - root - ERROR - Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")
ValueError: too many values to unpack (expected 3)

2024-10-28 22:14:54,449 - root - INFO - Prompt executed in 12.62 seconds
2024-10-28 22:16:54,585 - root - INFO - got prompt
2024-10-28 22:17:00,081 - root - ERROR - !!! Exception during processing !!! too many values to unpack (expected 3)
2024-10-28 22:17:00,089 - root - ERROR - Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")
ValueError: too many values to unpack (expected 3)

2024-10-28 22:17:00,101 - root - INFO - Prompt executed in 5.46 seconds
2024-10-28 22:17:03,015 - root - INFO - got prompt
2024-10-28 22:17:03,129 - root - ERROR - !!! Exception during processing !!! too many values to unpack (expected 3)
2024-10-28 22:17:03,129 - root - ERROR - Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")
ValueError: too many values to unpack (expected 3)

2024-10-28 22:17:03,129 - root - INFO - Prompt executed in 0.08 seconds
2024-10-28 22:26:24,074 - root - INFO - got prompt
2024-10-28 22:26:24,408 - root - ERROR - !!! Exception during processing !!! too many values to unpack (expected 3)
2024-10-28 22:26:24,417 - root - ERROR - Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")
ValueError: too many values to unpack (expected 3)

2024-10-28 22:26:24,424 - root - INFO - Prompt executed in 0.16 seconds
2024-10-28 22:26:30,868 - root - INFO - got prompt
2024-10-28 22:26:30,935 - root - ERROR - !!! Exception during processing !!! too many values to unpack (expected 3)
2024-10-28 22:26:30,939 - root - ERROR - Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")
ValueError: too many values to unpack (expected 3)

2024-10-28 22:26:30,941 - root - INFO - Prompt executed in 0.05 seconds
2024-10-29 07:37:11,875 - root - INFO - got prompt
2024-10-29 07:37:21,927 - root - ERROR - !!! Exception during processing !!! too many values to unpack (expected 3)
2024-10-29 07:37:21,940 - root - ERROR - Traceback (most recent call last):
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\efficiencyNodesFor_v172\efficiency_nodes.py", line 86, in efficientloader
    vae_cache, ckpt_cache, lora_cache = get_cache_numbers("Efficient Loader")
ValueError: too many values to unpack (expected 3)

2024-10-29 07:37:21,948 - root - INFO - Prompt executed in 9.76 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
Remove efficiencyNodesFor_v172 and install via ComfyUI-Manager.

**Comment by deepakpf** [comment]
> Remove efficiencyNodesFor_v172 and install efficiency-nodes-comfyui via ComfyUI-Manager.

Thanks man! This solved the issue.
