### ISSUE TITLE
TypeError: ImageSaver.save_files() missing 1 required positional argument: 'clip_skip'

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#5418]
### Expected Behavior

Save images I guess

### Actual Behavior

Error message below, I think this might be an update issue? I just updated, does this mean some node needs updating too and has a mismatch? this workflow worked fine until now.

### Steps to Reproduce

/

### Debug Logs

```powershell
`Start update check...Processing image with shape:  992 x 1496 to  1984 x 2992
!!! Exception during processing !!! ImageSaver.save_files() missing 1 required positional argument: 'clip_skip'
Traceback (most recent call last):
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "W:\smatrix\Data\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
TypeError: ImageSaver.save_files() missing 1 required positional argument: 'clip_skip'`
```

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Image-Saver repo.
https://github.com/alexopus/ComfyUI-Image-Saver
