### ISSUE TITLE
Using the latest version of kijai/ComfyUI IC Light plugin and the latest version of Comfyui error

### ISSUE THREAD

**Issue by baiyi-os** [comfyanonymous/ComfyUI#5437]
### Expected Behavior

Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-IC-Light/nodes.py", line 78, in load
    raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")
Exception: IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'

### Actual Behavior

Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-IC-Light/nodes.py", line 78, in load
    raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")
Exception: IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'

### Steps to Reproduce

Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-IC-Light/nodes.py", line 78, in load
    raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")
Exception: IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'

### Debug Logs

```powershell
Traceback (most recent call last):
  File "/app/ComfyUI/execution.py", line 316, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 191, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/app/ComfyUI/execution.py", line 168, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/app/ComfyUI/execution.py", line 157, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/app/ComfyUI/custom_nodes/ComfyUI-IC-Light/nodes.py", line 78, in load
    raise Exception(f"IC-Light: Could not patch calculate_weight - {str(e)}")
Exception: IC-Light: Could not patch calculate_weight - IC-Light: The 'calculate_weight' function does not exist in 'lora'
```

**Comment by ltdrdata** [comment]
See this:
https://github.com/comfyanonymous/ComfyUI/issues/5355
