### ISSUE TITLE
Followed latest mac insall instructions and Yaml missing

### ISSUE THREAD

**Issue by lindsayfowler** [comfyanonymous/ComfyUI#5443]
### Your question

The instructions for install on Mac seem broken unless I am mistaken.
Here's what I did:

python3.12 -m venv .venv
source .venv/bin/activate
pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
git clone https://github.com/comfyanonymous/ComfyUI.git

python3 main.py
Traceback (most recent call last):
  File "/Users/lf/Documents/comfy/main.py", line 66, in <module>
    import utils.extra_config
  File "/Users/lf/Documents/comfy/utils/extra_config.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

Also pip installing requirements.txt always resulted in impossible to resolve no matter which version of Python I tried 3.10, 3.11, 3.12

**Comment by bianchi74** [comment]
I also have the same problem on Mac:
Python 3.13.0 (v3.13.0:60403a5409f, Oct  7 2024, 00:37:40) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin - Apple M2 Pro. 

`pip install -r requirements.txt` does not produce any error, but this is the output of `python main.py`
```
Traceback (most recent call last):
  File "/Users/bianchi/Documents/GitHub/ComfyUI/main.py", line 66, in <module>
    import utils.extra_config
  File "/Users/bianchi/Documents/GitHub/ComfyUI/utils/extra_config.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```
This is the output of pip install:

```
pip install -r requirements.txt

Collecting torch (from -r requirements.txt (line 1))
  Downloading torch-2.5.1-cp311-none-macosx_11_0_arm64.whl.metadata (28 kB)
Collecting torchsde (from -r requirements.txt (line 2))
  Downloading torchsde-0.2.6-py3-none-any.whl.metadata (5.3 kB)
Collecting torchvision (from -r requirements.txt (line 3))
  Downloading torchvision-0.20.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.1 kB)
Collecting torchaudio (from -r requirements.txt (line 4))
  Downloading torchaudio-2.5.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.4 kB)
Collecting einops (from -r requirements.txt (line 5))
  Downloading einops-0.8.0-py3-none-any.whl.metadata (12 kB)
Collecting transformers>=4.28.1 (from -r requirements.txt (line 6))
  Downloading transformers-4.46.2-py3-none-any.whl.metadata (44 kB)
Collecting tokenizers>=0.13.3 (from -r requirements.txt (line 7))
  Downloading tokenizers-0.20.3-cp311-cp311-macosx_11_0_arm64.whl.metadata (6.7 kB)
Collecting sentencepiece (from -r requirements.txt (line 8))
  Downloading sentencepiece-0.2.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.7 kB)
Collecting safetensors>=0.4.2 (from -r requirements.txt (line 9))
  Downloading safetensors-0.4.5-cp311-cp311-macosx_11_0_arm64.whl.metadata (3.8 kB)
Collecting aiohttp (from -r requirements.txt (line 10))
  Downloading aiohttp-3.11.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.7 kB)
Requirement already satisfied: pyyaml in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 11)) (6.0.1)
Requirement already satisfied: Pillow in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from -r requirements.txt (line 12)) (10.3.0)
Collecting scipy (from -r requirements.txt (line 13))
  Downloading scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl.metadata (60 kB)
Collecting tqdm (from -r requirements.txt (line 14))
  Downloading tqdm-4.67.0-py3-none-any.whl.metadata (57 kB)
Collecting psutil (from -r requirements.txt (line 15))
  Downloading psutil-6.1.0-cp36-abi3-macosx_11_0_arm64.whl.metadata (22 kB)
Collecting kornia>=0.7.1 (from -r requirements.txt (line 18))
  Downloading kornia-0.7.4-py2.py3-none-any.whl.metadata (18 kB)
Collecting spandrel (from -r requirements.txt (line 19))
  Downloading spandrel-0.4.0-py3-none-any.whl.metadata (15 kB)
Collecting soundfile (from -r requirements.txt (line 20))
  Downloading soundfile-0.12.1-py2.py3-none-macosx_11_0_arm64.whl.metadata (14 kB)
Collecting filelock (from torch->-r requirements.txt (line 1))
  Downloading filelock-3.16.1-py3-none-any.whl.metadata (2.9 kB)
Collecting typing-extensions>=4.8.0 (from torch->-r requirements.txt (line 1))
  Downloading typing_extensions-4.12.2-py3-none-any.whl.metadata (3.0 kB)
Collecting networkx (from torch->-r requirements.txt (line 1))
  Downloading networkx-3.4.2-py3-none-any.whl.metadata (6.3 kB)
Requirement already satisfied: jinja2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from torch->-r requirements.txt (line 1)) (3.1.2)
Collecting fsspec (from torch->-r requirements.txt (line 1))
  Downloading fsspec-2024.10.0-py3-none-any.whl.metadata (11 kB)
Collecting sympy==1.13.1 (from torch->-r requirements.txt (line 1))
  Downloading sympy-1.13.1-py3-none-any.whl.metadata (12 kB)
Collecting mpmath<1.4,>=1.1.0 (from sympy==1.13.1->torch->-r requirements.txt (line 1))
  Downloading mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Collecting numpy>=1.19 (from torchsde->-r requirements.txt (line 2))
  Downloading numpy-2.1.3-cp311-cp311-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting trampoline>=0.1.2 (from torchsde->-r requirements.txt (line 2))
  Downloading trampoline-0.1.2-py3-none-any.whl.metadata (10 kB)
Collecting huggingface-hub<1.0,>=0.23.2 (from transformers>=4.28.1->-r requirements.txt (line 6))
  Downloading huggingface_hub-0.26.2-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging>=20.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers>=4.28.1->-r requirements.txt (line 6)) (23.2)
Collecting regex!=2019.12.17 (from transformers>=4.28.1->-r requirements.txt (line 6))
  Downloading regex-2024.11.6-cp311-cp311-macosx_11_0_arm64.whl.metadata (40 kB)
Requirement already satisfied: requests in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from transformers>=4.28.1->-r requirements.txt (line 6)) (2.31.0)
Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->-r requirements.txt (line 10))
  Downloading aiohappyeyeballs-2.4.3-py3-none-any.whl.metadata (6.1 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->-r requirements.txt (line 10))
  Downloading aiosignal-1.3.1-py3-none-any.whl.metadata (4.0 kB)
Collecting attrs>=17.3.0 (from aiohttp->-r requirements.txt (line 10))
  Downloading attrs-24.2.0-py3-none-any.whl.metadata (11 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->-r requirements.txt (line 10))
  Downloading frozenlist-1.5.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (13 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->-r requirements.txt (line 10))
  Downloading multidict-6.1.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (5.0 kB)
Collecting propcache>=0.2.0 (from aiohttp->-r requirements.txt (line 10))
  Downloading propcache-0.2.0-cp311-cp311-macosx_11_0_arm64.whl.metadata (7.7 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp->-r requirements.txt (line 10))
  Downloading yarl-1.17.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (64 kB)
Collecting kornia-rs>=0.1.0 (from kornia>=0.7.1->-r requirements.txt (line 18))
  Downloading kornia_rs-0.1.7-cp311-cp311-macosx_11_0_arm64.whl.metadata (9.1 kB)
Collecting cffi>=1.0 (from soundfile->-r requirements.txt (line 20))
  Downloading cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl.metadata (1.5 kB)
Collecting pycparser (from cffi>=1.0->soundfile->-r requirements.txt (line 20))
  Downloading pycparser-2.22-py3-none-any.whl.metadata (943 bytes)
Requirement already satisfied: idna>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from yarl<2.0,>=1.17.0->aiohttp->-r requirements.txt (line 10)) (3.4)
Requirement already satisfied: MarkupSafe>=2.0 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from jinja2->torch->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers>=4.28.1->-r requirements.txt (line 6)) (3.3.0)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers>=4.28.1->-r requirements.txt (line 6)) (2.0.6)
Requirement already satisfied: certifi>=2017.4.17 in /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages (from requests->transformers>=4.28.1->-r requirements.txt (line 6)) (2023.7.22)
Downloading torch-2.5.1-cp311-none-macosx_11_0_arm64.whl (63.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.9/63.9 MB 50.2 MB/s eta 0:00:00
Downloading sympy-1.13.1-py3-none-any.whl (6.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 51.7 MB/s eta 0:00:00
Downloading torchsde-0.2.6-py3-none-any.whl (61 kB)
Downloading torchvision-0.20.1-cp311-cp311-macosx_11_0_arm64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 41.7 MB/s eta 0:00:00
Downloading torchaudio-2.5.1-cp311-cp311-macosx_11_0_arm64.whl (1.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 43.5 MB/s eta 0:00:00
Downloading einops-0.8.0-py3-none-any.whl (43 kB)
Downloading transformers-4.46.2-py3-none-any.whl (10.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 52.0 MB/s eta 0:00:00
Downloading tokenizers-0.20.3-cp311-cp311-macosx_11_0_arm64.whl (2.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 48.0 MB/s eta 0:00:00
Downloading sentencepiece-0.2.0-cp311-cp311-macosx_11_0_arm64.whl (1.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 41.8 MB/s eta 0:00:00
Downloading safetensors-0.4.5-cp311-cp311-macosx_11_0_arm64.whl (381 kB)
Downloading aiohttp-3.11.0-cp311-cp311-macosx_11_0_arm64.whl (453 kB)
Downloading scipy-1.14.1-cp311-cp311-macosx_14_0_arm64.whl (23.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.1/23.1 MB 48.9 MB/s eta 0:00:00
Downloading tqdm-4.67.0-py3-none-any.whl (78 kB)
Downloading psutil-6.1.0-cp36-abi3-macosx_11_0_arm64.whl (248 kB)
Downloading kornia-0.7.4-py2.py3-none-any.whl (899 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 899.4/899.4 kB 36.3 MB/s eta 0:00:00
Downloading spandrel-0.4.0-py3-none-any.whl (297 kB)
Downloading soundfile-0.12.1-py2.py3-none-macosx_11_0_arm64.whl (1.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 39.7 MB/s eta 0:00:00
Downloading aiohappyeyeballs-2.4.3-py3-none-any.whl (14 kB)
Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Downloading attrs-24.2.0-py3-none-any.whl (63 kB)
Downloading cffi-1.17.1-cp311-cp311-macosx_11_0_arm64.whl (178 kB)
Downloading frozenlist-1.5.0-cp311-cp311-macosx_11_0_arm64.whl (52 kB)
Downloading huggingface_hub-0.26.2-py3-none-any.whl (447 kB)
Downloading fsspec-2024.10.0-py3-none-any.whl (179 kB)
Downloading kornia_rs-0.1.7-cp311-cp311-macosx_11_0_arm64.whl (1.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 45.7 MB/s eta 0:00:00
Downloading multidict-6.1.0-cp311-cp311-macosx_11_0_arm64.whl (29 kB)
Downloading numpy-2.1.3-cp311-cp311-macosx_14_0_arm64.whl (5.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.4/5.4 MB 46.5 MB/s eta 0:00:00
Downloading propcache-0.2.0-cp311-cp311-macosx_11_0_arm64.whl (45 kB)
Downloading regex-2024.11.6-cp311-cp311-macosx_11_0_arm64.whl (284 kB)
Downloading trampoline-0.1.2-py3-none-any.whl (5.2 kB)
Downloading typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Downloading yarl-1.17.1-cp311-cp311-macosx_11_0_arm64.whl (91 kB)
Downloading filelock-3.16.1-py3-none-any.whl (16 kB)
Downloading networkx-3.4.2-py3-none-any.whl (1.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 38.8 MB/s eta 0:00:00
Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 536.2/536.2 kB 23.1 MB/s eta 0:00:00
Downloading pycparser-2.22-py3-none-any.whl (117 kB)
Installing collected packages: trampoline, sentencepiece, mpmath, typing-extensions, tqdm, sympy, safetensors, regex, pycparser, psutil, propcache, numpy, networkx, multidict, kornia-rs, fsspec, frozenlist, filelock, einops, attrs, aiohappyeyeballs, yarl, torch, scipy, huggingface-hub, cffi, aiosignal, torchvision, torchsde, torchaudio, tokenizers, soundfile, kornia, aiohttp, transformers, spandrel
Successfully installed aiohappyeyeballs-2.4.3 aiohttp-3.11.0 aiosignal-1.3.1 attrs-24.2.0 cffi-1.17.1 einops-0.8.0 filelock-3.16.1 frozenlist-1.5.0 fsspec-2024.10.0 huggingface-hub-0.26.2 kornia-0.7.4 kornia-rs-0.1.7 mpmath-1.3.0 multidict-6.1.0 networkx-3.4.2 numpy-2.1.3 propcache-0.2.0 psutil-6.1.0 pycparser-2.22 regex-2024.11.6 safetensors-0.4.5 scipy-1.14.1 sentencepiece-0.2.0 soundfile-0.12.1 spandrel-0.4.0 sympy-1.13.1 tokenizers-0.20.3 torch-2.5.1 torchaudio-2.5.1 torchsde-0.2.6 torchvision-0.20.1 tqdm-4.67.0 trampoline-0.1.2 transformers-4.46.2 typing-extensions-4.12.2 yarl-1.17.1
```

**Comment by ltdrdata** [comment]
You need to activate the venv and then install the requirements.txt.

**Comment by yaolinhong** [comment]
same 

python main.py                          

Traceback (most recent call last):
  File "/Users/linhongyao/data/code/xz-code/ComfyUI/main.py", line 11, in <module>
    import utils.extra_config
  File "/Users/linhongyao/data/code/xz-code/ComfyUI/utils/extra_config.py", line 2, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by ltdrdata** [comment]
> same
> 
> python main.py
> 
> Traceback (most recent call last): File "/Users/linhongyao/data/code/xz-code/ComfyUI/main.py", line 11, in import utils.extra_config File "/Users/linhongyao/data/code/xz-code/ComfyUI/utils/extra_config.py", line 2, in import yaml ModuleNotFoundError: No module named 'yaml'

You didn't installed pip dependencies.
https://github.com/comfyanonymous/ComfyUI?tab=readme-ov-file#installing

**Comment by mommel** [comment]
The answer above is somewhat right but false.
The mentioned problem is no Problem from ComfyUI, even not pyyaml, but something you can easy run into with an apple. But ComfyUI-Manager does have a problem. 

This is how you can fix it:

Instead of using 
`pip install -r requirements.txt`  you need to do it with `python -m pip install -r requirements.txt`
That's it. But you will run into the same problem when you use ComfyUI-Manager, because there pip is used directly. But as you should always check the logs you can fix everything by hand what ComfyUI-Manager will install broken.

Hopefully that helps to all Mac Users

**Comment by ltdrdata** [comment]
> The answer above is somewhat right but false. The mentioned problem is no Problem from ComfyUI, even not pyyaml, but something you can easy run into with an apple and at least when using venv. But ComfyUI-Manager does have a problem.
> 
> This is how you can fix it:
> 
> Instead of using `pip install -r requirements.txt` you need to do it with `python -m pip install -r requirements.txt` That's it. But you will run into the same problem when you use ComfyUI-Manager, because there pip is used directly. But as you should always check the logs you can fix everything by hand what ComfyUI-Manager will install broken.
> 
> Hopefully that helps to all Mac Users

ComfyUI-Manager is designed to use the pip of the Python environment where ComfyUI is running for installation. 
Could you provide the log for cases where pip is used directly instead of `python -m pip`?
