### ISSUE TITLE
SamplerCustom/SamplerCustomAdvanced does not honor latent mask when sigmas are split

### ISSUE THREAD

**Issue by fintarn** [comfyanonymous/ComfyUI#5452]
### Expected Behavior

In a workflow where a sigmas are split with the SplitSigmas or SplitSigmasDenoise nodes between two samplers SamplerCustom/SamplerCustomAdvanced, and at the same time a latent mask is set with the "Set Latent Noise Mask" node before entering each sampler, the mask should be honored by both samplers, leaving the masked area untouched after sampling.

### Actual Behavior

In a workflow where a sigmas are split with the SplitSigmas or SplitSigmasDenoise nodes between two samplers SamplerCustom/SamplerCustomAdvanced, and at the same time a latent mask is set with the "Set Latent Noise Mask" node before entering each sampler, the mask is not honored by the sampler that receives the low_sigmas output from the SplitSigmas or SplitSigmasDenoise nodes, and the masked area comes out very noisy.

### Steps to Reproduce

Workflow and screenshot attached. Please check.

### Debug Logs

```powershell
F:\Stable Diffusion\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --lowvram
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-01 08:45:00.088985
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: F:\Stable Diffusion\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI
** Log path: F:\Stable Diffusion\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
  18.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 10240 MB, total RAM 32681 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints F:/Stable Diffusion\models/Stable-diffusion
Adding extra search path configs F:/Stable Diffusion\models/Stable-diffusion
Adding extra search path vae F:/Stable Diffusion\models/VAE
Adding extra search path loras F:/Stable Diffusion\models/Lora
Adding extra search path loras F:/Stable Diffusion\models/LyCORIS
Adding extra search path upscale_models F:/Stable Diffusion\models/ESRGAN
Adding extra search path upscale_models F:/Stable Diffusion\models/RealESRGAN
Adding extra search path upscale_models F:/Stable Diffusion\models/SwinIR
Adding extra search path embeddings F:/Stable Diffusion\models/embeddings
Adding extra search path hypernetworks F:/Stable Diffusion\models/hypernetworks
Adding extra search path controlnet F:/Stable Diffusion\models/ControlNet
Adding extra search path unet F:/Stable Diffusion\models/Stable-diffusion
Adding extra search path clip F:/Stable Diffusion\models/text_encoder
PATH BASENAME <function basename at 0x000001F1576AF2E0>
REGISTRY DIR F:\Stable Diffusion\ComfyUI_windows_portable\output\anynode
ChromaDB Path: F:\Stable Diffusion\ComfyUI_windows_portable\output\anynode\chroma_db_default, exists: True
Anonymized telemetry enabled. See                     https://docs.trychroma.com/telemetry for more information.
Traceback (most recent call last):
  File "F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\cogvideox-controlnet\\__init__.py'

Cannot import F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\cogvideox-controlnet module for custom nodes: [Errno 2] No such file or directory: 'F:\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\cogvideox-controlnet\\__init__.py'
Traceback (most recent call last):
  File "F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 38, in <module>
    from .mesh_processer.mesh import Mesh
  File "F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\mesh_processer\mesh.py", line 8, in <module>
    from kiui.op import safe_normalize, dot
ModuleNotFoundError: No module named 'kiui'

Cannot import F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
[AnimateDiff] - ERROR - No models available. Please download one and put it in models folder
sageattn not found, using sdpa
sageattn not found, using sdpa
sageattn not found, using sdpa
[Crystools INFO] Crystools version: 1.19.0
[Crystools INFO] CPU: AMD Ryzen 9 5900X 12-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3080
[Crystools INFO] NVIDIA Driver: 560.94
[ComfyUI-Easy-Use] server: v1.2.4 Loaded
[ComfyUI-Easy-Use] web root: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
### Loading: ComfyUI-Impact-Pack (V7.9)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.3)
Total VRAM 10240 MB, total RAM 32681 MB
pytorch version: 2.3.1+cu121
xformers version: 0.0.26.post1
Set vram state to: LOW_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.7)
### ComfyUI Revision: 2804 [cc9cf6d1] | Released on '2024-10-31'
Traceback (most recent call last):
  File "F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\__init__.py'

Cannot import F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NAI-styler module for custom nodes: [Errno 2] No such file or directory: 'F:\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-NAI-styler\\__init__.py'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[SD Prompt Reader] Node version: 1.3.4
[SD Prompt Reader] Core version: 1.3.5
F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()

F:\Stable Diffusion\ComfyUI_windows_portable
############################################
F:\Stable Diffusion\ComfyUI_windows_portable\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
[]
############################################
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
All packages from requirements.txt are installed and up to date.
llama-cpp installed
All packages from requirements.txt are installed and up to date.
AutoGPTQ installed
[comfy_mtb] | INFO -> loaded 83 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Patching UNetModel.forward
UNetModel.forward has been successfully patched.

[rgthree-comfy] Loaded 42 exciting nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "The best revenge is massive success." - Frank Sinatra


Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-NAI-styler
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds (IMPORT FAILED): F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\cogvideox-controlnet
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\FreeU_Advanced
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfy_KepListStuff
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_joytag
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-inpaint-nodes
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-plasma
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Dickson-Nodes
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inpaint-CropAndStitch
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SuperBeasts
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.1 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_PoP
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui_CXH_joy_caption
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-various
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_ExtraModels
   0.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dream-project
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.5 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
   0.5 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.6 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   1.0 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-prompt-reader-node
   1.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
   1.5 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-dynamicprompts
   1.6 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   1.9 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.9 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.2 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_VLM_nodes
   2.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
   2.7 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   3.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CCSR
   3.7 seconds (IMPORT FAILED): F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack
   3.9 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\CogVideoX-Fun
   6.4 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
  17.3 seconds: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\anynode

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[comfy_mtb] | INFO -> Found multiple match, we will pick the last F:/Stable Diffusion\models/SwinIR
['F:\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\models\\upscale_models', 'F:/Stable Diffusion\\models/ESRGAN', 'F:/Stable Diffusion\\models/RealESRGAN', 'F:/Stable Diffusion\\models/SwinIR']
[comfy_mtb] | WARNING -> Face restoration models not found.
[]
[]
got prompt
Using xformers attention in VAE
Using xformers attention in VAE
model_path:  F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\models\sam2\sam2.1_hiera_base_plus-fp16.safetensors
Using model config: F:\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2_configs\sam2.1_hiera_b+.yaml
Failed to torch jit script transforms: could not get source code, falling back to normal transforms
using sdpa for attention
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 9319.23095703125 True
clip missing: ['text_projection.weight']
model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
model_type FLUX
Requested to load Flux
Loading 1 new model
loaded partially 6872.475200363159 6872.173889160156 0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 30/30 [01:09<00:00,  2.32s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
</s><s>Large english text<loc_187><loc_247><loc_794><loc_765></s>
match index: 0 in mask_indexes: ['0']
Offloading model...
[[[192.00001525878906, 253.4400177001953, 813.5680541992188, 783.8720092773438]]]
Type of data: <class 'list'>
Data: [[[192.00001525878906, 253.4400177001953, 813.5680541992188, 783.8720092773438]]]
Indexes: [0]
Coordinates: [{"x": 502, "y": 518}]
Processing Images: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.22s/it]
loaded partially 7190.286035247803 7188.029357910156 0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:21<00:00,  2.20s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
loaded partially 7190.286035247803 7188.029357910156 0
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:43<00:00,  2.19s/it]
Requested to load AutoencodingEngine
Loading 1 new model
loaded completely 0.0 159.87335777282715 True
Prompt executed in 908.16 seconds
```

### Other

The prompt in the workflow may not be optimal to showcase the workflow.

The idea with the workflow is to generate an image with text and then use latent noise injection to further detail the image. Since text in the image from the first sampler is messed up with such a workflow, segment anything 2 is used to create a mask for the text based on description with Florence, so that the text is not changed by subsequent samplers. 

To further alter the image and get more detail in the background, The SplitSigmasDenoise is used to essentially split a latent inpaint pass between two samplers, which can give more detail with the right parameters. However the sampler that receives the low_sigmas does not honor the mask and any masked area comes out looking very noisy and therefore the resulting image is not good. I can't tell why this happens, is this a bug?

[workflow.json](https://github.com/user-attachments/files/17597550/workflow.json)
![ScreenshotComfy](https://github.com/user-attachments/assets/afbf4f95-d379-4d06-a2f1-54174fc71aad)

**Comment by catboxanon** [comment]
I don't think this is a bug. Check the `output` of your first `SamplerCustomAdvanced` node. You'll notice the entire output is noisy. The `noise_mask` effects inference but it intentionally, from my understanding by design, does not effect the raw output. This is why when you pass that result into the second `SamplerCustomAdvanced` node, it actually did honor the mask, but it masked the noisy latent. Check the `SamplerCustomAdvanced` code for reference. You'll see the `noise_mask` is only ever passed in as a reference to the sampler, and otherwise the output (`out`) is just a copy of your input `latent`.
https://github.com/comfyanonymous/ComfyUI/blob/619b8cde74538a1dc62b85e47e34daa493705c06/comfy_extras/nodes_custom_sampler.py#L636-L661

You can get around this if you use the `LatentCompositeMask` node -- for the inputs set `destination` to your initial latent after txt2img (your standard `KSampler` node output), `source` to the output of your first `SamplerCustomAdvanced`'s `output`, and `mask` to the relevant mask you want.

Technically this isn't fully how you should be doing this anyway though. Because the VAE is a lossy operation, after the second `SamplerCustomAdvanced` node, you should be compositing a masked version of the original KSampler output on top of that final output, so the text remains completely untouched by any lossy operation.

---

Also, cc @huchenlei I think you tagged a bunch of issues erroneously with AMD, maybe due to the Crystools log output for the CPU manufacturer. This user was using a NVIDIA card. Here's another example: https://github.com/comfyanonymous/ComfyUI/issues/6064
