### ISSUE TITLE
The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4

### ISSUE THREAD

**Issue by TOUTVJ** [comfyanonymous/ComfyUI#5455]
### Expected Behavior

render video with pyramid flow sampler

### Actual Behavior

The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4

### Steps to Reproduce

default setup

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** PyramidFlowSampler
- **Exception Type:** RuntimeError
- **Exception Message:** The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4
## Stack Trace

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 213, in sample
    latents = model["model"].generate_i2v(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 434, in generate_i2v
    intermed_latents = self.generate_one_unit(
                       ^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 277, in generate_one_unit
    latents = self.scheduler.step(
              ^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\diffusion_schedulers\scheduling_flow_matching.py", line 284, in step
    prev_sample = sample + (sigma_next - sigma) * model_output
                  ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```
## System Information
- **ComfyUI Version:** v0.2.3-23-g83ca891
- **Arguments:** C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.3.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589410304
  - **VRAM Free:** 3121372680
  - **Torch VRAM Total:** 4328521728
  - **Torch VRAM Free:** 122445320

## Logs
```
2024-11-01 13:07:21,140 - root - INFO - Total VRAM 8192 MB, total RAM 16239 MB
2024-11-01 13:07:21,140 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-01 13:07:21,141 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-01 13:07:21,141 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
2024-11-01 13:07:22,637 - root - INFO - Using pytorch cross attention
2024-11-01 13:07:24,529 - root - INFO - [Prompt Server] web root: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\web
2024-11-01 13:07:26,750 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-01 13:07:26,772 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-11-01 13:07:26,774 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-11-01 13:07:27,754 - root - INFO - Total VRAM 8192 MB, total RAM 16239 MB
2024-11-01 13:07:27,755 - root - INFO - pytorch version: 2.3.1+cu121
2024-11-01 13:07:27,755 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-01 13:07:27,756 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
2024-11-01 13:07:34,896 - root - INFO - 
Import times for custom nodes:
2024-11-01 13:07:34,896 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-01 13:07:34,896 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Crystools-save
2024-11-01 13:07:34,896 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Styles_CSV_Loader
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Lotus
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-seamless-tiling
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-CSV-Loader
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\sd-dynamic-thresholding
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\comfyui-fitsize
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyLiterals
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_InstantID
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\scenario_to_flux
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_experiments
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\comfyui-inpaint-nodes
2024-11-01 13:07:34,897 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-layerdiffuse
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\mikey_nodes
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Video-Matting
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\comfy-image-saver
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_Mira
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_FizzNodes
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_essentials
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Chibi-Nodes
2024-11-01 13:07:34,898 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-AutoCropFaces
2024-11-01 13:07:34,899 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-01 13:07:34,899 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-01 13:07:34,899 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-JDCN
2024-11-01 13:07:34,899 - root - INFO -    0.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\rgthree-comfy
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-11-01 13:07:34,899 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-01 13:07:34,900 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-11-01 13:07:34,900 - root - INFO -    0.1 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\comfyui-reactor-node
2024-11-01 13:07:34,900 - root - INFO -    0.2 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\comfyui_segment_anything
2024-11-01 13:07:34,900 - root - INFO -    0.2 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-tbox
2024-11-01 13:07:34,900 - root - INFO -    0.3 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-01 13:07:34,900 - root - INFO -    0.4 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-11-01 13:07:34,900 - root - INFO -    0.5 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI_LayerStyle
2024-11-01 13:07:34,900 - root - INFO -    0.5 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-01 13:07:34,900 - root - INFO -    0.6 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-01 13:07:34,901 - root - INFO -    0.6 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PhotoMaker-Plus
2024-11-01 13:07:34,901 - root - INFO -    0.6 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-11-01 13:07:34,901 - root - INFO -    1.0 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper
2024-11-01 13:07:34,901 - root - INFO -    1.3 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-11-01 13:07:34,901 - root - INFO -    2.2 seconds: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-11-01 13:07:34,901 - root - INFO - 
2024-11-01 13:07:34,916 - root - INFO - Starting server

2024-11-01 13:07:34,917 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-01 13:10:33,019 - root - INFO - got prompt
2024-11-01 13:10:33,194 - ComfyUI-PyramidFlowWrapper.nodes - INFO - Downloading model to: C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\models\pyramidflow\pyramid-flow-sd3
2024-11-01 13:16:46,619 - root - ERROR - !!! Exception during processing !!! The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4
2024-11-01 13:16:46,668 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 213, in sample
    latents = model["model"].generate_i2v(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 434, in generate_i2v
    intermed_latents = self.generate_one_unit(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 277, in generate_one_unit
    latents = self.scheduler.step(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\diffusion_schedulers\scheduling_flow_matching.py", line 284, in step
    prev_sample = sample + (sigma_next - sigma) * model_output
                  ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4

2024-11-01 13:16:46,683 - root - INFO - Prompt executed in 373.62 seconds
2024-11-01 13:25:03,069 - root - INFO - got prompt
2024-11-01 13:27:01,366 - root - ERROR - !!! Exception during processing !!! The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4
2024-11-01 13:27:01,386 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\nodes.py", line 213, in sample
    latents = model["model"].generate_i2v(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 434, in generate_i2v
    intermed_latents = self.generate_one_unit(
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\pyramid_dit\pyramid_dit_for_video_gen_pipeline.py", line 277, in generate_one_unit
    latents = self.scheduler.step(
              ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Oscar Bismuth\Documents\WORK\ComfyUI\ComfyUI-studio-v86\App\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper\diffusion_schedulers\scheduling_flow_matching.py", line 284, in step
    prev_sample = sample + (sigma_next - sigma) * model_output
                  ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
RuntimeError: The size of tensor a (31) must match the size of tensor b (30) at non-singleton dimension 4

2024-11-01 13:27:01,397 - root - INFO - Prompt executed in 118.27 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by TOUTVJ** [comment]
![image](https://github.com/user-attachments/assets/23f66b81-80dd-47cb-a3b1-f4e5ccf1378e)
![Capture d’écran 2024-11-01 133057](https://github.com/user-attachments/assets/f6b01775-522a-4daf-9cdd-b4120acbca89)

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-PyramidFlowWrapper.
https://github.com/kijai/ComfyUI-PyramidFlowWrapper
