### ISSUE TITLE
Node Bug

### ISSUE THREAD

**Issue by DJFlash999** [comfyanonymous/ComfyUI#5458]
### Expected Behavior

When I change the drive on a node I expect the change to persist

### Actual Behavior

The drive correction was not persistent

### Steps to Reproduce

change the drive on a node

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** LoadImagesFromDirectory
- **Exception Type:** FileNotFoundError
- **Exception Message:** Directory 'F:\#Projects\1) SD Animation\16) Loka Loka LCM\Passes\OP cannot be found.'
## Stack Trace

  File "D:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_deprecated.py", line 31, in load_images
    raise FileNotFoundError(f"Directory '{directory} cannot be found.'")

```
## System Information
- **ComfyUI Version:** v0.2.6-6-gcc9cf6d
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:15:49) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 10736893952
  - **VRAM Free:** 9513730048
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-01 08:04:26,487 - root - INFO - Total VRAM 10240 MB, total RAM 16197 MB
2024-11-01 08:04:26,488 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-01 08:04:26,488 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-01 08:04:26,488 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
2024-11-01 08:04:37,575 - root - INFO - Using pytorch cross attention
2024-11-01 08:04:51,477 - root - INFO - [Prompt Server] web root: D:\pinokio\api\comfy.git\app\web
2024-11-01 08:04:58,102 - root - INFO - Total VRAM 10240 MB, total RAM 16197 MB
2024-11-01 08:04:58,103 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-01 08:04:58,103 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-01 08:04:58,103 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3080 : cudaMallocAsync
2024-11-01 08:05:16,543 - root - INFO - 
Import times for custom nodes:
2024-11-01 08:05:16,543 - root - INFO -    0.0 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\websocket_image_save.py
2024-11-01 08:05:16,543 - root - INFO -    0.1 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-01 08:05:16,543 - root - INFO -    0.1 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-01 08:05:16,543 - root - INFO -    0.2 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\comfy-image-saver
2024-11-01 08:05:16,544 - root - INFO -    0.3 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-01 08:05:16,544 - root - INFO -    0.3 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-01 08:05:16,544 - root - INFO -    0.4 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_essentials
2024-11-01 08:05:16,544 - root - INFO -    0.5 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Manager
2024-11-01 08:05:16,544 - root - INFO -    0.8 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-KJNodes
2024-11-01 08:05:16,544 - root - INFO -    1.0 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_smZNodes
2024-11-01 08:05:16,544 - root - INFO -    1.1 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\comfyui_controlnet_aux
2024-11-01 08:05:16,544 - root - INFO -    1.2 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\was-node-suite-comfyui
2024-11-01 08:05:16,544 - root - INFO -    1.6 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-01 08:05:16,544 - root - INFO -    1.7 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-01 08:05:16,544 - root - INFO -   10.1 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\comfy_mtb
2024-11-01 08:05:16,544 - root - INFO - 
2024-11-01 08:05:16,551 - root - INFO - Starting server

2024-11-01 08:05:16,551 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-01 08:11:55,389 - root - INFO - got prompt
2024-11-01 08:11:55,396 - root - ERROR - Failed to validate prompt for output 334:
2024-11-01 08:11:55,396 - root - ERROR - * (prompt):
2024-11-01 08:11:55,396 - root - ERROR -   - Failed to convert an input value to a INT value: quality, false, invalid literal for int() with base 10: 'false'
2024-11-01 08:11:55,396 - root - ERROR -   - Value not in list: overwrite_mode: 'true' not in ['false', 'prefix_as_filename']
2024-11-01 08:11:55,397 - root - ERROR - * Text Concatenate 354:
2024-11-01 08:11:55,397 - root - ERROR -   - Value not in list: clean_whitespace: '' not in ['true', 'false']
2024-11-01 08:11:55,397 - root - ERROR - * LoraLoader 373:
2024-11-01 08:11:55,397 - root - ERROR -   - Value not in list: lora_name: 'lcm_pytorch_lora_weights.safetensors' not in ['AnimateLCM_sd15_t2v_lora.safetensors']
2024-11-01 08:11:55,397 - root - ERROR - * Image Save 334:
2024-11-01 08:11:55,398 - root - ERROR -   - Failed to convert an input value to a INT value: quality, false, invalid literal for int() with base 10: 'false'
2024-11-01 08:11:55,398 - root - ERROR -   - Value not in list: overwrite_mode: 'true' not in ['false', 'prefix_as_filename']
2024-11-01 08:11:55,398 - root - ERROR - Output will be ignored
2024-11-01 08:11:55,398 - root - ERROR - Failed to validate prompt for output 319:
2024-11-01 08:11:55,398 - root - ERROR - Output will be ignored
2024-11-01 08:11:55,419 - root - ERROR - !!! Exception during processing !!! Directory 'F:\#Projects\1) SD Animation\16) Loka Loka LCM\Passes\OP cannot be found.'
2024-11-01 08:11:55,458 - root - ERROR - Traceback (most recent call last):
  File "D:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Advanced-ControlNet\adv_control\nodes_deprecated.py", line 31, in load_images
    raise FileNotFoundError(f"Directory '{directory} cannot be found.'")
FileNotFoundError: Directory 'F:\#Projects\1) SD Animation\16) Loka Loka LCM\Passes\OP cannot be found.'

2024-11-01 08:11:55,459 - root - INFO - Prompt executed in 0.06 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by DJFlash999** [comment]
<img width="909" alt="F Drive Error1" src="https://github.com/user-attachments/assets/50e1a786-2512-445f-a27c-7dfcf2b23a03">
<img width="545" alt="F Drive Error2" src="https://github.com/user-attachments/assets/ca6a930f-cd4c-4710-9b3e-bb2094540b97">

**Comment by DJFlash999** [comment]
Why are people publishing so much code that does not work?

**Comment by ltdrdata** [comment]
`F:\#Projects\1) SD Animation\16) Loka Loka LCM...`
Is this really your correct directory name?
