### ISSUE TITLE
ExecuteAllControlNetPreprocessors - unhashable type: 'list'

### ISSUE THREAD

**Issue by hweikong** [comfyanonymous/ComfyUI#5460]
### Your question

i trying to install Flux Controlnet by following the instructions on

https://youtu.be/yrRY-CxEBg4?si=JoRY493dGzljKpu4 

** Encounter error when i query prompt ** 

# ComfyUI Error Report
## Error Details
- **Node Type:** ExecuteAllControlNetPreprocessors
- **Exception Type:** TypeError
- **Exception Message:** unhashable type: 'list'
## Stack Trace
```
  File "C:\ComfyUI-aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI-aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI-aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI-aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:

```
## System Information
- **ComfyUI Version:** v0.2.6
- **Arguments:** C:\ComfyUI-aki\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 15626911744
  - **Torch VRAM Total:** 234881024
  - **Torch VRAM Free:** 178241536

## Logs
```
2024-11-02 09:47:26,270 - root - INFO - Total VRAM 16376 MB, total RAM 31703 MB
2024-11-02 09:47:26,270 - root - INFO - pytorch version: 2.1.2+cu118
2024-11-02 09:47:26,441 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-11-02 09:47:26,441 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 09:47:26,441 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2024-11-02 09:47:27,073 - root - INFO - Using xformers cross attention
2024-11-02 09:47:27,514 - root - INFO - [Prompt Server] web root: C:\ComfyUI-aki\web
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path checkpoints C:\sd-webui-aki-v4.8\models/Stable-diffusion
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path configs C:\sd-webui-aki-v4.8\models/Stable-diffusion
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path vae C:\sd-webui-aki-v4.8\models/VAE
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path loras C:\sd-webui-aki-v4.8\models/Lora
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path loras C:\sd-webui-aki-v4.8\models/LyCORIS
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path upscale_models C:\sd-webui-aki-v4.8\models/ESRGAN
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path upscale_models C:\sd-webui-aki-v4.8\models/RealESRGAN
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path upscale_models C:\sd-webui-aki-v4.8\models/SwinIR		  
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path embeddings C:\sd-webui-aki-v4.8\embeddings
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path hypernetworks C:\sd-webui-aki-v4.8\models/hypernetworks
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path controlnet C:\sd-webui-aki-v4.8\models/ControlNet
2024-11-02 09:47:28,154 - root - WARNING - Traceback (most recent call last):
  File "C:\ComfyUI-aki\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI-aki\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
ModuleNotFoundError: No module named 'torchaudio'

2024-11-02 09:47:28,154 - root - WARNING - Cannot import C:\ComfyUI-aki\comfy_extras\nodes_audio.py module for custom nodes: No module named 'torchaudio'
2024-11-02 09:47:28,235 - root - INFO - Total VRAM 16376 MB, total RAM 31703 MB
2024-11-02 09:47:28,235 - root - INFO - pytorch version: 2.1.2+cu118
2024-11-02 09:47:28,235 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-11-02 09:47:28,235 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 09:47:28,235 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2024-11-02 09:47:43,640 - root - INFO - 
Import times for custom nodes:
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\websocket_image_save.py
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\FreeU_Advanced
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_TiledKSampler
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\stability-ComfyUI-nodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-WD14-Tagger
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_experiments
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\PowerNoiseSuite
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_FizzNodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\images-grid-comfy-plugin
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_essentials
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Custom-Scripts
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\comfy-image-saver
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-KJNodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\rgthree-comfy
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\comfyui-workspace-manager
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux
2024-11-02 09:47:43,641 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Inspire-Pack
2024-11-02 09:47:43,641 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Crystools
2024-11-02 09:47:43,641 - root - INFO -    0.1 seconds: C:\ComfyUI-aki\custom_nodes\comfyui_segment_anything
2024-11-02 09:47:43,641 - root - INFO -    0.1 seconds: C:\ComfyUI-aki\custom_nodes\comfyui-tensorops
2024-11-02 09:47:43,641 - root - INFO -    0.2 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Depth-Pro
2024-11-02 09:47:43,641 - root - INFO -    0.2 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Florence2
2024-11-02 09:47:43,641 - root - INFO -    0.2 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Manager
2024-11-02 09:47:43,641 - root - INFO -    0.4 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Impact-Pack
2024-11-02 09:47:43,641 - root - INFO -    0.4 seconds: C:\ComfyUI-aki\custom_nodes\comfyui-propost
2024-11-02 09:47:43,641 - root - INFO -    0.5 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Easy-Use
2024-11-02 09:47:43,641 - root - INFO -    4.1 seconds: C:\ComfyUI-aki\custom_nodes\was-node-suite-comfyui
2024-11-02 09:47:43,641 - root - INFO -    8.9 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-02 09:47:43,641 - root - INFO - 
2024-11-02 09:47:43,641 - root - WARNING - WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

2024-11-02 09:47:43,641 - root - WARNING - IMPORT FAILED: nodes_audio.py
2024-11-02 09:47:43,641 - root - WARNING - 
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
2024-11-02 09:47:43,641 - root - WARNING - Please do a: pip install -r requirements.txt
2024-11-02 09:47:43,641 - root - WARNING - 
2024-11-02 09:47:43,650 - root - INFO - Starting server

2024-11-02 09:47:43,651 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-02 09:49:47,512 - root - INFO - got prompt
2024-11-02 09:50:03,494 - root - ERROR - !!! Exception during processing !!! unhashable type: 'list'
2024-11-02 09:50:03,494 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI-aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:
TypeError: unhashable type: 'list'

2024-11-02 09:50:03,495 - root - INFO - Prompt executed in 15.98 seconds
2024-11-02 09:55:25,938 - root - INFO - got prompt
2024-11-02 09:55:33,992 - root - ERROR - !!! Exception during processing !!! unhashable type: 'list'
2024-11-02 09:55:33,992 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI-aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:
TypeError: unhashable type: 'list'

2024-11-02 09:55:33,993 - root - INFO - Prompt executed in 8.05 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":5,"last_link_id":4,"nodes":[{"id":1,"type":"LoadImage","pos":{"0":6,"1":38},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["00000-3070505320.png","image"]},{"id":3,"type":"PreviewImage","pos":{"0":687,"1":26},"size":{"0":1226.231689453125,"1":914.90185546875},"flags":{},"order":2,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":2,"label":"images"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":2,"type":"ExecuteAllControlNetPreprocessors","pos":{"0":353,"1":27},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1,"label":"image"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"slot_index":0,"shape":3,"label":"IMAGE"}],"properties":{"Node name for S&R":"ExecuteAllControlNetPreprocessors"},"widgets_values":[640]}],"links":[[1,1,0,2,0,"IMAGE"],[2,2,0,3,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.2284597357367295,"offset":[39.06818965797072,137.76018761537898]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** ExecuteAllControlNetPreprocessors
- **Exception Type:** TypeError
- **Exception Message:** unhashable type: 'list'
## Stack Trace

  File "C:\ComfyUI-aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI-aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "C:\ComfyUI-aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI-aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:

```
## System Information
- **ComfyUI Version:** v0.2.6
- **Arguments:** C:\ComfyUI-aki\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.1.2+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 15626911744
  - **Torch VRAM Total:** 234881024
  - **Torch VRAM Free:** 178241536

## Logs
```
2024-11-02 09:47:26,270 - root - INFO - Total VRAM 16376 MB, total RAM 31703 MB
2024-11-02 09:47:26,270 - root - INFO - pytorch version: 2.1.2+cu118
2024-11-02 09:47:26,441 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-11-02 09:47:26,441 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 09:47:26,441 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2024-11-02 09:47:27,073 - root - INFO - Using xformers cross attention
2024-11-02 09:47:27,514 - root - INFO - [Prompt Server] web root: C:\ComfyUI-aki\web
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path checkpoints C:\sd-webui-aki-v4.8\models/Stable-diffusion
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path configs C:\sd-webui-aki-v4.8\models/Stable-diffusion
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path vae C:\sd-webui-aki-v4.8\models/VAE
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path loras C:\sd-webui-aki-v4.8\models/Lora
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path loras C:\sd-webui-aki-v4.8\models/LyCORIS
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path upscale_models C:\sd-webui-aki-v4.8\models/ESRGAN
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path upscale_models C:\sd-webui-aki-v4.8\models/RealESRGAN
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path upscale_models C:\sd-webui-aki-v4.8\models/SwinIR		  
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path embeddings C:\sd-webui-aki-v4.8\embeddings
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path hypernetworks C:\sd-webui-aki-v4.8\models/hypernetworks
2024-11-02 09:47:27,517 - root - INFO - Adding extra search path controlnet C:\sd-webui-aki-v4.8\models/ControlNet
2024-11-02 09:47:28,154 - root - WARNING - Traceback (most recent call last):
  File "C:\ComfyUI-aki\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\ComfyUI-aki\comfy_extras\nodes_audio.py", line 1, in <module>
    import torchaudio
ModuleNotFoundError: No module named 'torchaudio'

2024-11-02 09:47:28,154 - root - WARNING - Cannot import C:\ComfyUI-aki\comfy_extras\nodes_audio.py module for custom nodes: No module named 'torchaudio'
2024-11-02 09:47:28,235 - root - INFO - Total VRAM 16376 MB, total RAM 31703 MB
2024-11-02 09:47:28,235 - root - INFO - pytorch version: 2.1.2+cu118
2024-11-02 09:47:28,235 - root - INFO - xformers version: 0.0.23.post1+cu118
2024-11-02 09:47:28,235 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-02 09:47:28,235 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
2024-11-02 09:47:43,640 - root - INFO - 
Import times for custom nodes:
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\websocket_image_save.py
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\FreeU_Advanced
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_TiledKSampler
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\stability-ComfyUI-nodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-WD14-Tagger
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_experiments
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\PowerNoiseSuite
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_FizzNodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\images-grid-comfy-plugin
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_essentials
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Custom-Scripts
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\comfy-image-saver
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-KJNodes
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\rgthree-comfy
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\comfyui-workspace-manager
2024-11-02 09:47:43,640 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux
2024-11-02 09:47:43,641 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Inspire-Pack
2024-11-02 09:47:43,641 - root - INFO -    0.0 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Crystools
2024-11-02 09:47:43,641 - root - INFO -    0.1 seconds: C:\ComfyUI-aki\custom_nodes\comfyui_segment_anything
2024-11-02 09:47:43,641 - root - INFO -    0.1 seconds: C:\ComfyUI-aki\custom_nodes\comfyui-tensorops
2024-11-02 09:47:43,641 - root - INFO -    0.2 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Depth-Pro
2024-11-02 09:47:43,641 - root - INFO -    0.2 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Florence2
2024-11-02 09:47:43,641 - root - INFO -    0.2 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Manager
2024-11-02 09:47:43,641 - root - INFO -    0.4 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Impact-Pack
2024-11-02 09:47:43,641 - root - INFO -    0.4 seconds: C:\ComfyUI-aki\custom_nodes\comfyui-propost
2024-11-02 09:47:43,641 - root - INFO -    0.5 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI-Easy-Use
2024-11-02 09:47:43,641 - root - INFO -    4.1 seconds: C:\ComfyUI-aki\custom_nodes\was-node-suite-comfyui
2024-11-02 09:47:43,641 - root - INFO -    8.9 seconds: C:\ComfyUI-aki\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-02 09:47:43,641 - root - INFO - 
2024-11-02 09:47:43,641 - root - WARNING - WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

2024-11-02 09:47:43,641 - root - WARNING - IMPORT FAILED: nodes_audio.py
2024-11-02 09:47:43,641 - root - WARNING - 
This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
2024-11-02 09:47:43,641 - root - WARNING - Please do a: pip install -r requirements.txt
2024-11-02 09:47:43,641 - root - WARNING - 
2024-11-02 09:47:43,650 - root - INFO - Starting server

2024-11-02 09:47:43,651 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-02 09:49:47,512 - root - INFO - got prompt
2024-11-02 09:50:03,494 - root - ERROR - !!! Exception during processing !!! unhashable type: 'list'
2024-11-02 09:50:03,494 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI-aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:
TypeError: unhashable type: 'list'

2024-11-02 09:50:03,495 - root - INFO - Prompt executed in 15.98 seconds
2024-11-02 09:55:25,938 - root - INFO - got prompt
2024-11-02 09:55:33,992 - root - ERROR - !!! Exception during processing !!! unhashable type: 'list'
2024-11-02 09:55:33,992 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI-aki\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\ComfyUI-aki\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI-aki\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\ComfyUI-aki\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:
TypeError: unhashable type: 'list'

2024-11-02 09:55:33,993 - root - INFO - Prompt executed in 8.05 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":5,"last_link_id":4,"nodes":[{"id":1,"type":"LoadImage","pos":{"0":6,"1":38},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1],"slot_index":0,"shape":3,"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["00000-3070505320.png","image"]},{"id":3,"type":"PreviewImage","pos":{"0":687,"1":26},"size":{"0":1226.231689453125,"1":914.90185546875},"flags":{},"order":2,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":2,"label":"images"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":2,"type":"ExecuteAllControlNetPreprocessors","pos":{"0":353,"1":27},"size":{"0":315,"1":58},"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1,"label":"image"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[2],"slot_index":0,"shape":3,"label":"IMAGE"}],"properties":{"Node name for S&R":"ExecuteAllControlNetPreprocessors"},"widgets_values":[640]}],"links":[[1,1,0,2,0,"IMAGE"],[2,2,0,3,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.2284597357367295,"offset":[39.06818965797072,137.76018761537898]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

.

**Comment by Amazon90** [comment]
# ComfyUI Error Report
## Error Details
- **Node Type:** ExecuteAllControlNetPreprocessors
- **Exception Type:** TypeError
- **Exception Message:** unhashable type: 'list'
## Stack Trace
```
  File "D:\Git\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Git\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\Git\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\Git\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\Git\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 117, in execute
    if input_type[0] in default_values:

```
## System Information
- **ComfyUI Version:** v0.2.6
- **Arguments:** D:\Git\ComfyUI\main.py --preview-method auto --disable-cuda-malloc --fast
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.0+cu124

**Comment by Amazon90** [comment]
https://github.com/Fannovel16/comfyui_controlnet_aux/issues/480

**Comment by cloudwooo** [comment]
only this preprocessor ![image](https://github.com/user-attachments/assets/93501f35-0c70-47f1-b368-f32cb90c6767)
