### ISSUE TITLE
ERROR: Could not detect model type of

### ISSUE THREAD

**Issue by MandraBlaise** [comfyanonymous/ComfyUI#5494]
### Your question

I followed the tutorial https://www.youtube.com/watch?v=rQ8mUwFtLto&t=328s to install SUPIR and did exactly as it's said, but, when I try to generate my image, it says
![Capture d'écran 2024-11-05 094238](https://github.com/user-attachments/assets/36bf9470-aa14-4c60-9d19-bb5666e7d526)
 : CheckpointLoaderSimple
ERROR: Could not detect model type of: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\SUPIR-v0F.ckpt
I downloaded the .ckpt from the link of the video and put it in the Checkpoint file, so I don't know where the error comes from.
Can someone help me please?

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** CheckpointLoaderSimple
- **Exception Type:** RuntimeError
- **Exception Message:** ERROR: Could not detect model type of: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\SUPIR-v0F.ckpt
## Stack Trace

  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 543, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 585, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))

```
## System Information
- **ComfyUI Version:** v0.2.4-16-g30c0c81
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12884377600
  - **VRAM Free:** 11053667180
  - **Torch VRAM Total:** 771751936
  - **Torch VRAM Free:** 76125036

## Logs
```
2024-11-05 10:35:48,571 - root - INFO - Total VRAM 12288 MB, total RAM 32438 MB
2024-11-05 10:35:48,571 - root - INFO - pytorch version: 2.5.0+cu124
2024-11-05 10:35:48,571 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-05 10:35:48,571 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
2024-11-05 10:35:49,860 - root - INFO - Using pytorch cross attention
2024-11-05 10:35:51,719 - root - INFO - [Prompt Server] web root: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\web
2024-11-05 10:35:55,013 - root - INFO - 
Import times for custom nodes:
2024-11-05 10:35:55,013 - root - INFO -    0.0 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-05 10:35:55,013 - root - INFO -    0.0 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Saver-main
2024-11-05 10:35:55,013 - root - INFO -    0.0 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Saver
2024-11-05 10:35:55,013 - root - INFO -    0.0 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-utils-nodes
2024-11-05 10:35:55,014 - root - INFO -    0.0 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials-main
2024-11-05 10:35:55,014 - root - INFO -    0.3 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
2024-11-05 10:35:55,014 - root - INFO -    0.3 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-05 10:35:55,014 - root - INFO -    0.4 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-05 10:35:55,014 - root - INFO -    0.6 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-11-05 10:35:55,014 - root - INFO -    1.0 seconds: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-11-05 10:35:55,014 - root - INFO - 
2024-11-05 10:35:55,014 - root - INFO - Starting server

2024-11-05 10:35:55,014 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-05 10:36:09,464 - root - INFO - got prompt
2024-11-05 10:36:23,217 - root - ERROR - !!! Exception during processing !!! ERROR: Could not detect model type of: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\SUPIR-v0F.ckpt
2024-11-05 10:36:23,255 - root - ERROR - Traceback (most recent call last):
  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 543, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\comfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 585, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: C:\comfyUI\ComfyUI_windows_portable\ComfyUI\models\checkpoints\SUPIR-v0F.ckpt

2024-11-05 10:36:23,264 - root - INFO - Prompt executed in 13.79 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":40,"last_link_id":45,"nodes":[{"id":18,"type":"Note","pos":{"0":847,"1":612},"size":{"0":210,"1":58},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["orginal src : motion 0\n"],"color":"#432","bgcolor":"#653"},{"id":17,"type":"Note","pos":{"0":1144,"1":966},"size":{"0":227.1239471435547,"1":58},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["motion 1"],"color":"#432","bgcolor":"#653"},{"id":16,"type":"Note","pos":{"0":1967,"1":1002},"size":{"0":483.8179931640625,"1":161.2032470703125},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["Command Description\n1 = 5:5\n0 = 3:5\n\n[Motion index] = [Changing frame length] : [Length of frames waiting for next motion]\n\nfor example, first line -> 1 = 5:5\nChange over 5 frames with motion 1, and wait for the next motion for 5 frames"],"color":"#432","bgcolor":"#653"},{"id":3,"type":"LoadImage","pos":{"0":844,"1":245},"size":{"0":223.20394897460938,"1":314},"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[18],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"slot_index":1,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["BLAISE_tete_34F_V00_fond_blanc.png","image"]},{"id":7,"type":"AdvancedLivePortrait","pos":{"0":2720,"1":301},"size":{"0":235.1999969482422,"1":523.0364379882812},"flags":{"collapsed":false},"order":4,"mode":0,"inputs":[{"name":"src_images","type":"IMAGE","link":null,"shape":7},{"name":"motion_link","type":"EDITOR_LINK","link":null,"shape":7},{"name":"driving_images","type":"IMAGE","link":null,"shape":7}],"outputs":[{"name":"images","type":"IMAGE","links":[],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"AdvancedLivePortrait"},"widgets_values":[0,0,1.7000000000000002,true,false,true,"1 = 5:5\n0 = 3:5"]},{"id":10,"type":"VHS_VideoCombine","pos":{"0":2988,"1":310},"size":[261.79998779296875,310],"flags":{},"order":5,"mode":4,"inputs":[{"name":"images","type":"IMAGE","link":null},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"AdvancedLivePortrait","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":19,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"AdvancedLivePortrait_00002.mp4","subfolder":"","type":"output","format":"video/h264-mp4","frame_rate":15}}}},{"id":26,"type":"SUPIR_conditioner","pos":{"0":2056,"1":-93},"size":{"0":400,"1":200},"flags":{},"order":16,"mode":0,"inputs":[{"name":"SUPIR_model","type":"SUPIRMODEL","link":35},{"name":"latents","type":"LATENT","link":32},{"name":"captions","type":"STRING","link":null,"widget":{"name":"captions"},"shape":7}],"outputs":[{"name":"positive","type":"SUPIR_cond_pos","links":[30],"slot_index":0},{"name":"negative","type":"SUPIR_cond_neg","links":[31],"slot_index":1}],"properties":{"Node name for S&R":"SUPIR_conditioner"},"widgets_values":["high quality, detailed","bad quality, blurry, messy",""]},{"id":27,"type":"Reroute","pos":{"0":1662,"1":-91},"size":[75,26],"flags":{},"order":11,"mode":0,"inputs":[{"name":"","type":"*","link":34}],"outputs":[{"name":"","type":"SUPIRMODEL","links":[35],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":25,"type":"SUPIR_sample","pos":{"0":2532,"1":-289},"size":{"0":315,"1":454},"flags":{},"order":17,"mode":0,"inputs":[{"name":"SUPIR_model","type":"SUPIRMODEL","link":37},{"name":"latents","type":"LATENT","link":27},{"name":"positive","type":"SUPIR_cond_pos","link":30},{"name":"negative","type":"SUPIR_cond_neg","link":31}],"outputs":[{"name":"latent","type":"LATENT","links":[38],"slot_index":0}],"properties":{"Node name for S&R":"SUPIR_sample"},"widgets_values":[719084098751595,"randomize",45,4,4,5,1.003,1,1,1,-1,false,"RestoreEDMSampler",1024,512]},{"id":30,"type":"Reroute","pos":{"0":2304,"1":-427},"size":[75,26],"flags":{},"order":13,"mode":0,"inputs":[{"name":"","type":"*","link":40}],"outputs":[{"name":"","type":"SUPIRVAE","links":[41],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":28,"type":"Reroute","pos":{"0":2305,"1":-453},"size":[75,26],"flags":{},"order":12,"mode":0,"inputs":[{"name":"","type":"*","link":36}],"outputs":[{"name":"","type":"SUPIRMODEL","links":[37],"slot_index":0}],"properties":{"showOutputText":false,"horizontal":false}},{"id":29,"type":"SUPIR_decode","pos":{"0":3076,"1":-433},"size":{"0":315,"1":102},"flags":{},"order":18,"mode":0,"inputs":[{"name":"SUPIR_VAE","type":"SUPIRVAE","link":41},{"name":"latents","type":"LATENT","link":38}],"outputs":[{"name":"image","type":"IMAGE","links":[43],"slot_index":0}],"properties":{"Node name for S&R":"SUPIR_decode"},"widgets_values":[true,512]},{"id":20,"type":"Image Saver","pos":{"0":3470,"1":-440},"size":{"0":400,"1":826},"flags":{},"order":19,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":43}],"outputs":[],"properties":{"Node name for S&R":"Image Saver"},"widgets_values":["%sampler_name_%counter","Z:\\02_DESIGN\\01_PERSONNAGES\\03_BLAISE\\04_pour_test_IA\\Profil","png",1,10,"","blaise_lips_test","normal","unknown","unknown",1,3936,3936,false,100,true,1,1,-1,"%Y-%m-%d-%H%M%S",false,false]},{"id":23,"type":"SUPIR_first_stage","pos":{"0":1663,"1":-304},"size":{"0":352.79998779296875,"1":170},"flags":{},"order":14,"mode":0,"inputs":[{"name":"SUPIR_VAE","type":"SUPIRVAE","link":22},{"name":"image","type":"IMAGE","link":45}],"outputs":[{"name":"SUPIR_VAE","type":"SUPIRVAE","links":[25],"slot_index":0},{"name":"denoised_image","type":"IMAGE","links":[26],"slot_index":1},{"name":"denoised_latents","type":"LATENT","links":[32],"slot_index":2}],"properties":{"Node name for S&R":"SUPIR_first_stage"},"widgets_values":[false,1024,1024,"auto"]},{"id":24,"type":"SUPIR_encode","pos":{"0":2074,"1":-303},"size":{"0":315,"1":126},"flags":{},"order":15,"mode":0,"inputs":[{"name":"SUPIR_VAE","type":"SUPIRVAE","link":25},{"name":"image","type":"IMAGE","link":26}],"outputs":[{"name":"latent","type":"LATENT","links":[27],"slot_index":0}],"properties":{"Node name for S&R":"SUPIR_encode"},"widgets_values":[true,1024,"auto"]},{"id":33,"type":"ImageResize+","pos":{"0":1220,"1":-156},"size":{"0":315,"1":218},"flags":{},"order":10,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":44}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[45],"slot_index":0},{"name":"width","type":"INT","links":null},{"name":"height","type":"INT","links":null}],"properties":{"Node name for S&R":"ImageResize+"},"widgets_values":[1024,1024,"nearest","stretch","always",0]},{"id":15,"type":"ExpressionEditor","pos":{"0":1124,"1":212},"size":{"0":210,"1":690},"flags":{},"order":7,"mode":0,"inputs":[{"name":"src_image","type":"IMAGE","link":18,"shape":7},{"name":"motion_link","type":"EDITOR_LINK","link":null,"shape":7},{"name":"sample_image","type":"IMAGE","link":null,"shape":7},{"name":"add_exp","type":"EXP_DATA","link":null,"shape":7}],"outputs":[{"name":"image","type":"IMAGE","links":[16,44],"slot_index":0,"shape":3},{"name":"motion_link","type":"EDITOR_LINK","links":[],"slot_index":1,"shape":3},{"name":"save_exp","type":"EXP_DATA","links":null,"shape":3}],"properties":{"Node name for S&R":"ExpressionEditor"},"widgets_values":[0,0,0,0,0,0,0,0,10,4,0,0.5,1,1,"All",1.5]},{"id":19,"type":"SaveImage","pos":{"0":1534,"1":238},"size":{"0":532.4799194335938,"1":694.95263671875},"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":16}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":22,"type":"CheckpointLoaderSimple","pos":{"0":779,"1":-450},"size":{"0":315,"1":98},"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[19],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[20],"slot_index":1},{"name":"VAE","type":"VAE","links":[21],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["SUPIR-v0F.ckpt"]},{"id":21,"type":"SUPIR_model_loader_v2","pos":{"0":1223,"1":-444},"size":{"0":315,"1":170},"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":19},{"name":"clip","type":"CLIP","link":20},{"name":"vae","type":"VAE","link":21}],"outputs":[{"name":"SUPIR_model","type":"SUPIRMODEL","links":[34,36],"slot_index":0},{"name":"SUPIR_VAE","type":"SUPIRVAE","links":[22,40],"slot_index":1}],"properties":{"Node name for S&R":"SUPIR_model_loader_v2"},"widgets_values":["SUPIR-v0F.ckpt",false,"auto",false]}],"links":[[16,15,0,19,0,"IMAGE"],[18,3,0,15,0,"IMAGE"],[19,22,0,21,0,"MODEL"],[20,22,1,21,1,"CLIP"],[21,22,2,21,2,"VAE"],[22,21,1,23,0,"SUPIRVAE"],[25,23,0,24,0,"SUPIRVAE"],[26,23,1,24,1,"IMAGE"],[27,24,0,25,1,"LATENT"],[30,26,0,25,2,"SUPIR_cond_pos"],[31,26,1,25,3,"SUPIR_cond_neg"],[32,23,2,26,1,"LATENT"],[34,21,0,27,0,"*"],[35,27,0,26,0,"SUPIRMODEL"],[36,21,0,28,0,"*"],[37,28,0,25,0,"SUPIRMODEL"],[38,25,0,29,1,"LATENT"],[40,21,1,30,0,"*"],[41,30,0,29,0,"SUPIRVAE"],[43,29,0,20,0,"IMAGE"],[44,15,0,33,0,"IMAGE"],[45,33,0,23,1,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015777,"offset":[-737.016236238133,599.7226650229127]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
You should not load supir model via Checkpoint Loader.
That model should be loaded via custom node `SUPIR Model Loader (v2)`

**Comment by MandraBlaise** [comment]
![Capture d'écran 2024-11-05 133143](https://github.com/user-attachments/assets/8b8dc56a-61c6-463b-a4c3-ab3733a05262)
I used SUPIR Model Loader (v2), and put a Load Checkpoint as shown in the tutorial

**Comment by ltdrdata** [comment]
This.
![image](https://github.com/user-attachments/assets/665841cb-f643-4081-9379-0c78f72782fc)
