### ISSUE TITLE
LoadImage - name 'node_helpers' is not defined

### ISSUE THREAD

**Issue by sariobba1562** [comfyanonymous/ComfyUI#5498]
### Your question

When running my workflow I receive the following sentence:

LoadImage
name 'node_helpers' is not defined

when I click: "show report" appears in clipboard:

# ComfyUI Error Report
## Error Details
- **Node Type:** LoadImage
- **Exception Type:** NameError
- **Exception Message:** name 'node_helpers' is not defined
## Stack Trace
```
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** unknown
- **Arguments:** ComfyUI\main.py --cpu --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.0+cu124
## Devices

- **Name:** cpu
  - **Type:** cpu
  - **VRAM Total:** 8490397696
  - **VRAM Free:** 2513420288
  - **Torch VRAM Total:** 8490397696
  - **Torch VRAM Free:** 2513420288

## Logs
```
2024-11-05 11:27:12,764 - root - INFO - Total VRAM 8097 MB, total RAM 8097 MB
2024-11-05 11:27:12,764 - root - INFO - pytorch version: 2.5.0+cu124
2024-11-05 11:27:12,764 - root - INFO - Set vram state to: DISABLED
2024-11-05 11:27:12,764 - root - INFO - Device: cpu
2024-11-05 11:27:15,814 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-11-05 11:27:19,318 - root - INFO - [Prompt Server] web root: C:\ComfyUI_windows_portable\ComfyUI\web
2024-11-05 11:27:20,630 - root - INFO - 
Import times for custom nodes:
2024-11-05 11:27:20,630 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails
2024-11-05 11:27:20,630 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-05 11:27:20,630 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
2024-11-05 11:27:20,630 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-portrait-master
2024-11-05 11:27:20,630 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-nodes-hnmr
2024-11-05 11:27:20,630 - root - INFO -    0.0 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-05 11:27:20,630 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyI2I
2024-11-05 11:27:20,630 - root - INFO -    0.1 seconds: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-05 11:27:20,630 - root - INFO - 
2024-11-05 11:27:20,646 - root - INFO - Starting server

2024-11-05 11:27:20,646 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-05 11:27:44,645 - root - INFO - got prompt
2024-11-05 11:27:44,663 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:27:44,665 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:27:45,477 - root - INFO - model weight dtype torch.float32, manual cast: None
2024-11-05 11:27:45,614 - root - INFO - model_type EPS
2024-11-05 11:28:42,245 - root - INFO - Using split attention in VAE
2024-11-05 11:28:42,328 - root - INFO - Using split attention in VAE
2024-11-05 11:28:47,801 - root - INFO - Requested to load SD1ClipModel
2024-11-05 11:28:47,801 - root - INFO - Loading 1 new model
2024-11-05 11:28:47,823 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-11-05 11:28:54,037 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:28:54,100 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:28:54,115 - root - INFO - Prompt executed in 69.46 seconds
2024-11-05 11:28:55,135 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
2024-11-05 11:29:48,654 - root - INFO - got prompt
2024-11-05 11:29:48,700 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:29:48,705 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:29:48,712 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:29:48,715 - root - INFO - Prompt executed in 0.03 seconds
2024-11-05 11:29:49,126 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
2024-11-05 11:33:33,139 - root - INFO - got prompt
2024-11-05 11:33:33,169 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:33:33,174 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:33:33,200 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:33:33,203 - root - INFO - Prompt executed in 0.05 seconds
2024-11-05 11:33:33,882 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
2024-11-05 11:34:19,534 - root - INFO - got prompt
2024-11-05 11:34:19,765 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:34:19,772 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:34:19,785 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:34:19,795 - root - INFO - Prompt executed in 0.03 seconds
2024-11-05 11:34:21,296 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
2024-11-05 11:44:29,907 - root - INFO - got prompt
2024-11-05 11:44:29,931 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:44:29,938 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:44:29,945 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:44:29,950 - root - INFO - Prompt executed in 0.02 seconds
2024-11-05 11:44:30,536 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
2024-11-05 11:49:17,620 - root - INFO - got prompt
2024-11-05 11:49:17,681 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:49:17,689 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:49:17,712 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:49:17,716 - root - INFO - Prompt executed in 0.09 seconds
2024-11-05 11:49:18,690 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
2024-11-05 11:50:09,870 - root - INFO - got prompt
2024-11-05 11:50:09,879 - root - WARNING - WARNING: name 'hashlib' is not defined
2024-11-05 11:50:09,884 - root - ERROR - !!! Exception during processing !!! name 'node_helpers' is not defined
2024-11-05 11:50:09,894 - root - ERROR - Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Thumbnails\ComfyUIThumbnails.py", line 109, in load_image
    img = node_helpers.pillow(Image.open, image_path)
          ^^^^^^^^^^^^
NameError: name 'node_helpers' is not defined

2024-11-05 11:50:09,898 - root - INFO - Prompt executed in 0.02 seconds
2024-11-05 11:50:10,460 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":24,"last_link_id":24,"nodes":[{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":-83.77899169921875,"1":100.79285430908203},"size":{"0":315,"1":98},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[],"slot_index":1},{"name":"VAE","type":"VAE","links":[],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["Bikini_Model_4_Pressly.safetensors"]},{"id":7,"type":"CLIPTextEncode","pos":{"0":312.93487548828125,"1":-146.46359252929688},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":12}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"title":"Negative Prompt","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark, deformation"],"color":"#322","bgcolor":"#533"},{"id":6,"type":"CLIPTextEncode","pos":{"0":312,"1":-363},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":14}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"title":"Positive Prompt","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["Create a stunning portrait of a 20-year-old brunette woman standing confidently. She embodies elegance and grace, with fair skin that glows softly under the light. Her slightly wavy hair cascades down her shoulders, framing her face perfectly. Capture her deep brown eyes, which are expressive and draw the viewer in with a piercing gaze.\n\nShe wears an elegant necklace resting delicately against her collarbone, adding sophistication to her appearance. Her full, pink lips are slightly parted, hinting at a serene smile. The composition should showcase her full body from head to toe, emphasizing her slender body and harmonious silhouette, who wears nothing, she is totally naked.\n\nPosition her in golden high heels that elevate her stature, highlighting her defined legs and large waist. The pose should exude confidence, subtly showcasing the strength and femininity of her bulky legs.\n\nThe background should be softly blurred to focus entirely on her captivating presence. Render the image in ultra-high definition, ensuring every detail is visible, from the texture of her skin to the shimmer of her jewelry, creating a breathtaking visual experience.\n\nFull body shot, sexy, sex\n"],"color":"#232","bgcolor":"#353"},{"id":8,"type":"VAEDecode","pos":{"0":987,"1":236},"size":{"0":210,"1":46},"flags":{},"order":7,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":11}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[10],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":3,"type":"KSampler","pos":{"0":800,"1":-74},"size":{"0":315,"1":262},"flags":{},"order":6,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":13},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":18}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[844615813665823,"randomize",20,8,"euler","karras",1]},{"id":17,"type":"VAEEncode","pos":{"0":658,"1":303},"size":{"0":210,"1":46},"flags":{},"order":5,"mode":0,"inputs":[{"name":"pixels","type":"IMAGE","link":24},{"name":"vae","type":"VAE","link":17}],"outputs":[{"name":"LATENT","type":"LATENT","links":[18],"slot_index":0}],"properties":{"Node name for S&R":"VAEEncode"},"widgets_values":[]},{"id":11,"type":"CheckpointLoaderSimple","pos":{"0":-86.7712173461914,"1":-43.60738754272461},"size":{"0":315,"1":98},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[13],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[12,14],"slot_index":1},{"name":"VAE","type":"VAE","links":[11,17],"slot_index":2}],"title":"Load Checkpoint (Loras)","properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["realisticVisionV60B1_v51HyperVAE.safetensors"]},{"id":24,"type":"LoadImage","pos":{"0":211,"1":317},"size":[315,314],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[24],"slot_index":0},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["example.png","image"]},{"id":10,"type":"PreviewImage","pos":{"0":1295,"1":-184},"size":{"0":902.0982055664062,"1":786.869873046875},"flags":{},"order":8,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":10}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]}],"links":[[4,6,0,3,1,"CONDITIONING"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[10,8,0,10,0,"IMAGE"],[11,11,2,8,1,"VAE"],[12,11,1,7,0,"CLIP"],[13,11,0,3,0,"MODEL"],[14,11,1,6,0,"CLIP"],[17,11,2,17,1,"VAE"],[18,17,0,3,3,"LATENT"],[24,24,0,17,0,"IMAGE"]],"groups":[{"title":"Load Checkpoint","bounding":[-102,-118,349,356],"color":"#3f789e","font_size":24,"flags":{}},{"title":"Prompts","bounding":[305,-435,444,481],"color":"#3f789e","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.6830134553650705,"offset":[343.4875001990447,567.5603327259921]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by LukeG89** [comment]
I tried your workflow and it works.

The error is probably caused by this other issue:

> WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

Try following what is suggested here: https://github.com/comfyanonymous/ComfyUI/issues/5193

**Comment by sariobba1562** [comment]
> I tried your workflow and it works.
> 
> The error is probably caused by this other issue:
> 
> > WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
> 
> Try following what is suggested here: #5193


what would be the solution?

**Comment by LukeG89** [comment]
Try updating ComfyUI using `update_comfyui_stable.bat` inside `update` folder and see if it fixes your issues.

**Comment by sariobba1562** [comment]
didn't solve

> Try updating ComfyUI using `update_comfyui_stable.bat` inside `update` folder and see if it fixes your issues.

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Thumbnails repo.
https://github.com/audioscavenger/ComfyUI-Thumbnails
