### ISSUE TITLE
Added route will never be executed, method POST is already registered

### ISSUE THREAD

**Issue by BrechtCorbeel** [comfyanonymous/ComfyUI#5502]
### Expected Behavior

Launch

### Actual Behavior

nothing

### Steps to Reproduce

/

### Debug Logs

```powershell
I will add it but launching takes 20 minutes of loading for me right now. tried over and over over hours. keeps fialing.
```

### Other

Solutions in other threads are outdated or do not work.

**Comment by BrechtCorbeel** [comment]
```
Traceback (most recent call last):
  File "W:\smatrix\Data\Packages\ComfyUI\main.py", line 217, in <module>
    server.add_routes()
  File "W:\smatrix\Data\Packages\ComfyUI\server.py", line 729, in add_routes
    self.app.add_routes(api_routes)
  File "W:\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 386, in add_routes
    return self.router.add_routes(routes)
  File "W:\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_urldispatcher.py", line 1277, in add_routes
    registered_routes.extend(route_def.register(self))
  File "W:\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_routedef.py", line 76, in register
    return [reg(self.path, self.handler, **self.kwargs)]
  File "W:\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_urldispatcher.py", line 1243, in add_post
    return self.add_route(hdrs.METH_POST, path, handler, **kwargs)
  File "W:\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_urldispatcher.py", line 1178, in add_route
    return resource.add_route(method, handler, expect_handler=expect_handler)
  File "W:\smatrix\Data\Packages\ComfyUI\venv\lib\site-packages\aiohttp\web_urldispatcher.py", line 359, in add_route
    raise RuntimeError(
RuntimeError: Added route will never be executed, method POST is already registered
```

**Comment by ltdrdata** [comment]
Try using the portable version instead of the stability matrix first.
If you install through other platforms, it's difficult to identify what's causing the errors.

**Comment by xiangcp** [comment]
custom nodes：
 custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
 custom_nodes/AIGODLIKE-ComfyUI-Translation
 
Just delete the capitalized node（AIGODLIKE-COMFYUI-TRANSLATION） above
work for me
