### ISSUE TITLE
Exception Message - 'VAE' object has no attribute 'vae_dtype' |  Node Type - VAEDecode

### ISSUE THREAD

**Issue by RakibMohaimin726** [comfyanonymous/ComfyUI#5508]
### Expected Behavior

I'm using GTX 1650 super with Reyzen 5 3600 and 16GB RAM 3000 MHz

Also, I'm using Comfy UI in side Pinokio 

I'm using this work flow - https://civitai.com/models/372584/ipivs-morph-img2vid-animatediff-lcm-hyper-sd

### Actual Behavior

# ComfyUI Error Report
## Error Details
- **Node Type:** VAEDecode
- **Exception Type:** AttributeError
- **Exception Message:** 'VAE' object has no attribute 'vae_dtype'
## Stack Trace
```
  File "H:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "H:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "H:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "H:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "H:\pinokio\api\comfy.git\app\nodes.py", line 284, in decode
    images = vae.decode(samples["samples"])

  File "H:\pinokio\api\comfy.git\app\comfy\sd.py", line 339, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)

```
## System Information
- **ComfyUI Version:** v0.2.7-3-g8afb97c
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.10.15 | packaged by conda-forge | (main, Oct 16 2024, 01:15:49) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA GeForce GTX 1650 SUPER : native
  - **Type:** cuda
  - **VRAM Total:** 4294639616
  - **VRAM Free:** 218733056
  - **Torch VRAM Total:** 3382706176
  - **Torch VRAM Free:** 182557184

## Logs
```
2024-11-06 08:13:54,842 - root - INFO - Total VRAM 4096 MB, total RAM 16310 MB
2024-11-06 08:13:54,842 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-06 08:13:54,857 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-06 08:13:54,858 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1650 SUPER : native
2024-11-06 08:13:57,135 - root - INFO - Using pytorch cross attention
2024-11-06 08:14:02,568 - root - INFO - [Prompt Server] web root: H:\pinokio\api\comfy.git\app\web
2024-11-06 08:14:04,104 - root - INFO - Total VRAM 4096 MB, total RAM 16310 MB
2024-11-06 08:14:04,104 - root - INFO - pytorch version: 2.5.1+cu121
2024-11-06 08:14:04,105 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-06 08:14:04,105 - root - INFO - Device: cuda:0 NVIDIA GeForce GTX 1650 SUPER : native
2024-11-06 08:14:08,384 - root - INFO - 
Import times for custom nodes:
2024-11-06 08:14:08,385 - root - INFO -    0.0 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\websocket_image_save.py
2024-11-06 08:14:08,385 - root - INFO -    0.0 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-06 08:14:08,385 - root - INFO -    0.0 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Frame-Interpolation
2024-11-06 08:14:08,386 - root - INFO -    0.0 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-06 08:14:08,386 - root - INFO -    0.0 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI_essentials
2024-11-06 08:14:08,386 - root - INFO -    0.1 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-06 08:14:08,386 - root - INFO -    0.3 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-KJNodes
2024-11-06 08:14:08,386 - root - INFO -    0.4 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Manager
2024-11-06 08:14:08,387 - root - INFO -    1.0 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-06 08:14:08,387 - root - INFO -    2.6 seconds: H:\pinokio\api\comfy.git\app\custom_nodes\comfy_mtb
2024-11-06 08:14:08,387 - root - INFO - 
2024-11-06 08:14:08,400 - root - INFO - Starting server

2024-11-06 08:14:08,400 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-06 09:45:50,622 - root - INFO - got prompt
2024-11-06 09:45:55,925 - root - WARNING - WARNING: No VAE weights detected, VAE not initalized.
2024-11-06 09:46:02,904 - root - INFO - model weight dtype torch.bfloat16, manual cast: torch.float32
2024-11-06 09:46:02,946 - root - INFO - model_type EPS
2024-11-06 09:46:06,498 - root - INFO - Using pytorch attention in VAE
2024-11-06 09:46:06,503 - root - INFO - Using pytorch attention in VAE
2024-11-06 09:46:07,061 - root - INFO - Requested to load SD1ClipModel
2024-11-06 09:46:07,062 - root - INFO - Loading 1 new model
2024-11-06 09:46:07,068 - root - INFO - loaded completely 0.0 235.84423828125 True
2024-11-06 09:46:07,552 - root - INFO - loaded straight to GPU
2024-11-06 09:46:07,552 - root - INFO - Requested to load BaseModel
2024-11-06 09:46:07,553 - root - INFO - Loading 1 new model
2024-11-06 09:46:07,583 - root - INFO - loaded completely 0.0 1639.406135559082 True
2024-11-06 09:46:19,198 - root - INFO - Requested to load CLIPVisionModelProjection
2024-11-06 09:46:19,200 - root - INFO - Loading 1 new model
2024-11-06 09:46:19,220 - root - INFO - loaded completely 0.0 1208.09814453125 True
2024-11-06 09:46:45,610 - root - INFO - Requested to load BaseModel
2024-11-06 09:46:45,611 - root - INFO - Requested to load ControlNet
2024-11-06 09:46:45,611 - root - INFO - Requested to load AnimateDiffModel
2024-11-06 09:46:45,611 - root - INFO - Loading 3 new models
2024-11-06 09:46:46,507 - root - INFO - loaded partially 64.0 63.99903106689453 128
2024-11-06 09:46:46,722 - root - INFO - loaded partially 64.0 63.99957275390625 0
2024-11-06 09:46:46,753 - root - INFO - loaded partially 64.0 63.997802734375 0
2024-11-06 11:50:27,865 - root - ERROR - !!! Exception during processing !!! 'VAE' object has no attribute 'vae_dtype'
2024-11-06 11:50:27,904 - root - ERROR - Traceback (most recent call last):
  File "H:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\pinokio\api\comfy.git\app\nodes.py", line 284, in decode
    images = vae.decode(samples["samples"])
  File "H:\pinokio\api\comfy.git\app\comfy\sd.py", line 339, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
AttributeError: 'VAE' object has no attribute 'vae_dtype'

2024-11-06 11:50:27,916 - root - INFO - Prompt executed in 7477.36 seconds
2024-11-06 13:09:47,176 - root - INFO - got prompt
2024-11-06 13:09:47,312 - root - INFO - Unloading models for lowram load.
2024-11-06 13:09:47,603 - root - INFO - 3 models unloaded.
2024-11-06 13:09:47,604 - root - INFO - Loading 3 new models
2024-11-06 13:09:47,666 - root - INFO - loaded partially 64.0 63.99903106689453 128
2024-11-06 13:09:47,689 - root - INFO - loaded partially 64.0 63.99957275390625 0
2024-11-06 13:09:47,769 - root - INFO - loaded partially 64.0 63.997802734375 0
2024-11-06 13:44:08,758 - root - ERROR - !!! Exception during processing !!! 'VAE' object has no attribute 'vae_dtype'
2024-11-06 13:44:08,768 - root - ERROR - Traceback (most recent call last):
  File "H:\pinokio\api\comfy.git\app\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\pinokio\api\comfy.git\app\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "H:\pinokio\api\comfy.git\app\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "H:\pinokio\api\comfy.git\app\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "H:\pinokio\api\comfy.git\app\nodes.py", line 284, in decode
    images = vae.decode(samples["samples"])
  File "H:\pinokio\api\comfy.git\app\comfy\sd.py", line 339, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
AttributeError: 'VAE' object has no attribute 'vae_dtype'

2024-11-06 13:44:08,778 - root - INFO - Prompt executed in 2061.55 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

### Steps to Reproduce

don't know

### Debug Logs

```powershell
don't know
```

**Comment by ltdrdata** [comment]
Please verify that the VAE model you loaded with VAELoader is valid.
