### ISSUE TITLE
Error fetching Ollama models

### ISSUE THREAD

**Issue by highfiiv** [comfyanonymous/ComfyUI#5510]
### Expected Behavior

I'm not sure if Ollama models are required in anyway but I do see errors related to them and would like the most healthy setup possible.

### Actual Behavior

When running the project I see Error fetching Ollama models

### Steps to Reproduce

Install on Macos and run the project

### Debug Logs

```powershell
There's 18,000 lines but here is a key snippet

Total VRAM 32768 MB, total RAM 32768 MB
pytorch version: 2.5.0
Set vram state to: SHARED
Device: mps
ComfyUI_FluxPromptGen loaded successfully
------------------------------------------
### N-Suite Revision: ae7cc848 
Current version of packaging: 23.1
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.10.0
Current version of skbuild: 0.18.1
Version of typing: Not found
Current version of diskcache: 5.6.3
Installing llama_cpp...
Error while checking AVX2 support: 'flags'
Python version: 311
OS: Darwin
OS bit: 64
Platform tag: cp311-cp311-macosx_15_0_arm64
Collecting llama-cpp-python==0.3.1
  ERROR: HTTP error 404 while getting https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl
ERROR: Could not install requirement llama-cpp-python==0.3.1 from https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl for URL https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl
Error while installing LLAMA: Command '['/usr/local/bin/python3.11', '-m', 'pip', 'install', 'https://github.com/abetlen/llama-cpp-python/releases/download/v0.3.1/llama_cpp_python-0.3.1-cp311-cp311-macosx_15_0_arm64.whl']' returned non-zero exit status 1.
Current version of timm: 1.0.9
Traceback (most recent call last):
  File "/Users/home/dev/ComfyUI/custom_nodes/ComfyUI-N-Nodes/__init__.py", line 64, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/home/dev/ComfyUI/custom_nodes/ComfyUI-N-Nodes/py/gptcpp_node.py", line 4, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
!!!VExpress path was added to /Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/VExpress.pth
 if meet `No module` error,try `python main.py` again, don't be foolish to pip install modules
```

### Other

I'm wondering if this is causing other issues, such as conflicts and instability for various custom nodes.

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-N-Nodes repo.
https://github.com/Nuked88/ComfyUI-N-Nodes
