### ISSUE TITLE
EXIF data is too long, what is that?

### ISSUE THREAD

**Issue by arcseedai** [comfyanonymous/ComfyUI#5514]
### Expected Behavior

when I press Queue prompt it should just queue the prompt

### Actual Behavior

when I press Queue prompt it should just do it, but instead I am getting an error EXIF data is too long

### Steps to Reproduce

My workflow is long, so you need a very long workflow

### Debug Logs

```powershell
got prompt
!!! Exception during processing !!! EXIF data is too long
Traceback (most recent call last):
  File "F:\AI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\AI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\AI\ComfyUI\custom_nodes\extended-saveimage-comfyui\save_image.py", line 80, in save_images
    img.save(os.path.join(full_output_folder, file), **kwargs)
  File "C:\Users\monte\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\Image.py", line 2568, in save
    save_handler(self, fp, filename)
  File "C:\Users\monte\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\JpegImagePlugin.py", line 769, in _save
    raise ValueError(msg)
ValueError: EXIF data is too long
```

### Other

So I am making an automated workflow to use it with a front end page that would allow me to produce  faster results with minimal efforts, the problem is that when I press queue it gives me this error.

**Comment by ltdrdata** [comment]
This issue should be addressed in the respective custom node repo. 
However, that custom node repo is no longer maintained. 
You need to replace it to an alternative custom node.

https://github.com/Goktug/comfyui-saveimage-plus

**Comment by arcseedai** [comment]
Thank you for your answer, I didn't realized it was because of the node!
