### ISSUE TITLE
CUDA error

### ISSUE THREAD

**Issue by 5czhongkai** [comfyanonymous/ComfyUI#5552]
### Your question

CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** KSampler
- **Exception Type:** RuntimeError
- **Exception Message:** CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
## Stack Trace

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1442, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1409, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 248, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 855, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 753, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 726, in sample_dpmpp_2m_sde
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 622, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\latent_preview.py", line 99, in callback
    preview_bytes = previewer.decode_latent_to_preview_image(preview_format, x0)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\latent_preview.py", line 26, in decode_latent_to_preview_image
    preview_image = self.decode_latent_to_preview(x0)

  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\latent_preview.py", line 50, in decode_latent_to_preview
    latent_image = torch.nn.functional.linear(x0[0].permute(1, 2, 0), self.latent_rgb_factors, bias=self.latent_rgb_factors_bias)

```
## System Information
- **ComfyUI Version:** v0.2.6-1-g09fdb2b2
- **Arguments:** D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\main.py --auto-launch --dont-upcast-attention --preview-method auto --use-quad-cross-attention --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu118
## Devices

- **Name:** cuda:0 AMD Radeon VII : native
  - **Type:** cuda
  - **VRAM Total:** 17163091968
  - **VRAM Free:** 8770915840
  - **Torch VRAM Total:** 7180648448
  - **Torch VRAM Free:** 270589440

## Logs
```
2024-11-09 16:31:01,872 - root - INFO - Total VRAM 16368 MB, total RAM 16331 MB
2024-11-09 16:31:01,873 - root - INFO - pytorch version: 2.3.1+cu118
2024-11-09 16:31:01,873 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-09 16:31:01,873 - root - INFO - Device: cuda:0 AMD Radeon VII : native
2024-11-09 16:31:04,372 - root - INFO - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-11-09 16:31:06,879 - root - INFO - [Prompt Server] web root: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\web
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path checkpoints D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/Stable-diffusion
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path configs D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/Stable-diffusion
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path vae D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/VAE
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path loras D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/Lora
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path loras D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/LyCORIS
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path upscale_models D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/ESRGAN
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path upscale_models D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/RealESRGAN
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path upscale_models D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/SwinIR
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path embeddings D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\embeddings
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path hypernetworks D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/hypernetworks
2024-11-09 16:31:06,883 - root - INFO - Adding extra search path controlnet D:\Stable Diffusion-A\sd-webui-aki-directml-v4.4\models/ControlNet
2024-11-09 16:31:08,401 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir SetUnionControlNetType' might differ from the native display name.
2024-11-09 16:31:08,401 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir ControlNetInpaintingAliMamaApply' might differ from the native display name.
2024-11-09 16:31:08,404 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir CFGGuider' might differ from the native display name.
2024-11-09 16:31:08,407 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir CLIPTextEncodeFlux' might differ from the native display name.
2024-11-09 16:31:08,408 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir FluxGuidance' might differ from the native display name.
2024-11-09 16:31:08,419 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir IPAdapterModelLoader' might differ from the native display name.
2024-11-09 16:31:08,419 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir IPAdapterAdvanced' might differ from the native display name.
2024-11-09 16:31:08,419 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir IPAdapterStyleComposition' might differ from the native display name.
2024-11-09 16:31:08,427 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir ModelSamplingSD3' might differ from the native display name.
2024-11-09 16:31:08,428 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir ModelSamplingFlux' might differ from the native display name.
2024-11-09 16:31:08,430 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir TripleCLIPLoader' might differ from the native display name.
2024-11-09 16:31:08,438 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir UltimateSDUpscale' might differ from the native display name.
2024-11-09 16:31:08,453 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir MinusZoneChatGLM3TextEncode' might differ from the native display name.
2024-11-09 16:31:08,463 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir SamplerCustomAdvanced' might differ from the native display name.
2024-11-09 16:31:08,463 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir BasicGuider' might differ from the native display name.
2024-11-09 16:31:08,463 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir BasicScheduler' might differ from the native display name.
2024-11-09 16:31:08,463 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir DualCLIPLoader' might differ from the native display name.
2024-11-09 16:31:08,463 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir KSamplerSelect' might differ from the native display name.
2024-11-09 16:31:08,463 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir RandomNoise' might differ from the native display name.
2024-11-09 16:31:08,464 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir InpaintModelConditioning' might differ from the native display name.
2024-11-09 16:31:08,464 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir ConditioningZeroOut' might differ from the native display name.
2024-11-09 16:31:08,464 - bizyair.nodes_base - WARNING - Display name '☁️BizyAir ConditioningSetTimestepRange' might differ from the native display name.
2024-11-09 16:31:09,645 - root - WARNING - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\ComfyUI-aki-v1.3\\ComfyUI-aki-v1.3\\custom_nodes\\cg-use-everywhere\\__init__.py'

2024-11-09 16:31:09,645 - root - WARNING - Cannot import D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\cg-use-everywhere module for custom nodes: [Errno 2] No such file or directory: 'D:\\ComfyUI-aki-v1.3\\ComfyUI-aki-v1.3\\custom_nodes\\cg-use-everywhere\\__init__.py'
2024-11-09 16:31:56,598 - root - WARNING - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 2006, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, KSamplerX0Inpaint, wrap_model
ImportError: cannot import name 'wrap_model' from 'comfy.samplers' (D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py)

2024-11-09 16:31:56,598 - root - WARNING - Cannot import D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'wrap_model' from 'comfy.samplers' (D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py)
2024-11-09 16:31:56,668 - root - INFO - 
Import times for custom nodes:
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\websocket_image_save.py
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_essentials
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
2024-11-09 16:31:56,668 - root - INFO -    0.0 seconds (IMPORT FAILED): D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
2024-11-09 16:31:56,669 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
2024-11-09 16:31:56,669 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-09 16:31:56,669 - root - INFO -    0.0 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-09 16:31:56,669 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-09 16:31:56,669 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-KwaiKolorsWrapper
2024-11-09 16:31:56,669 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
2024-11-09 16:31:56,669 - root - INFO -    0.1 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
2024-11-09 16:31:56,669 - root - INFO -    0.5 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
2024-11-09 16:31:56,669 - root - INFO -    0.5 seconds (IMPORT FAILED): D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\cg-use-everywhere
2024-11-09 16:31:56,669 - root - INFO -    0.7 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\BizyAir
2024-11-09 16:31:56,669 - root - INFO -    0.9 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\clipseg.py
2024-11-09 16:31:56,669 - root - INFO -    1.1 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
2024-11-09 16:31:56,669 - root - INFO -    1.3 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
2024-11-09 16:31:56,669 - root - INFO -    1.5 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle
2024-11-09 16:31:56,669 - root - INFO -    1.6 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
2024-11-09 16:31:56,669 - root - INFO -   11.5 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools
2024-11-09 16:31:56,669 - root - INFO -   27.9 seconds: D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-09 16:31:56,669 - root - INFO - 
2024-11-09 16:31:56,696 - root - INFO - Starting server

2024-11-09 16:31:56,696 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-09 16:32:41,874 - root - INFO - got prompt
2024-11-09 16:32:43,236 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-11-09 16:32:43,243 - root - INFO - model_type EPS
2024-11-09 16:32:46,375 - root - INFO - Using split attention in VAE
2024-11-09 16:32:46,377 - root - INFO - Using split attention in VAE
2024-11-09 16:32:47,077 - root - INFO - Requested to load SDXLClipModel
2024-11-09 16:32:47,078 - root - INFO - Loading 1 new model
2024-11-09 16:32:47,098 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-11-09 16:32:49,337 - root - INFO - loaded straight to GPU
2024-11-09 16:32:49,337 - root - INFO - Requested to load SDXL
2024-11-09 16:32:49,337 - root - INFO - Loading 1 new model
2024-11-09 16:32:49,387 - root - INFO - loaded completely 0.0 4897.0483474731445 True
2024-11-09 16:32:53,670 - root - ERROR - !!! Exception during processing !!! CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
2024-11-09 16:32:53,675 - root - ERROR - Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1442, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\nodes.py", line 1409, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved\animatediff\sampling.py", line 248, in motion_sample
    return orig_comfy_sample(model, noise, *args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\sample.py", line 43, in sample
    samples = sampler.sample(noise, positive, negative, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 855, in sample
    return sample(self.model, noise, positive, negative, cfg, self.device, sampler, sigmas, self.model_options, latent_image=latent_image, denoise_mask=denoise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 753, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 740, in sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 719, in inner_sample
    samples = sampler.sample(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 624, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 726, in sample_dpmpp_2m_sde
    callback({'x': x, 'i': i, 'sigma': sigmas[i], 'sigma_hat': sigmas[i], 'denoised': denoised})
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\comfy\samplers.py", line 622, in <lambda>
    k_callback = lambda x: callback(x["i"], x["denoised"], x["x"], total_steps)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\latent_preview.py", line 99, in callback
    preview_bytes = previewer.decode_latent_to_preview_image(preview_format, x0)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\latent_preview.py", line 26, in decode_latent_to_preview_image
    preview_image = self.decode_latent_to_preview(x0)
  File "D:\ComfyUI-aki-v1.3\ComfyUI-aki-v1.3\latent_preview.py", line 50, in decode_latent_to_preview
    latent_image = torch.nn.functional.linear(x0[0].permute(1, 2, 0), self.latent_rgb_factors, bias=self.latent_rgb_factors_bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INTERNAL_ERROR when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`

2024-11-09 16:32:53,677 - root - INFO - Prompt executed in 11.80 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":13,"last_link_id":9,"nodes":[{"id":8,"type":"VAEDecode","pos":{"0":1209,"1":188},"size":{"0":210,"1":46},"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7,"label":"Latent"},{"name":"vae","type":"VAE","link":8,"label":"VAE"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":{"0":1451,"1":189},"size":{"0":210,"1":270},"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"SaveImage"},"widgets_values":["ComfyUI"]},{"id":5,"type":"EmptyLatentImage","pos":{"0":473,"1":609},"size":{"0":315,"1":106},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[1312,736,1]},{"id":4,"type":"CheckpointLoaderSimple","pos":{"0":26,"1":474},"size":{"0":315,"1":98},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0,"label":"模型"},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1,"label":"CLIP"},{"name":"VAE","type":"VAE","links":[8],"slot_index":2,"label":"VAE"}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["4Guofeng4XL_v12.safetensors"]},{"id":3,"type":"KSampler","pos":{"0":863,"1":185},"size":{"0":315,"1":262},"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":4,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":6,"label":"负面条件"},{"name":"latent_image","type":"LATENT","link":2,"label":"Latent"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0,"label":"Latent"}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[578795184638068,"randomize",20,8,"dpmpp_2m_sde","karras",1]},{"id":7,"type":"CLIPTextEncode","pos":{"0":413,"1":389},"size":{"0":425.27801513671875,"1":180.6060791015625},"flags":{},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["ng_deepnegative_v1_75t,(badhandv4:1.2),EasyNegative,(worst quality:2),clothes, "]},{"id":6,"type":"CLIPTextEncode","pos":{"0":415,"1":186},"size":{"0":422.84503173828125,"1":164.31304931640625},"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3,"label":"CLIP"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["nfsw,XS,masterpiece:1.2),best quality,high resolution,unity 8k wallpaper,(illustration:1),perfect lighting,extremely detailed CG,finely detail,extremely detailed,soft lighting and shadow,soft yet striking lighting,film grain:1.2,(skin pores:1.2),(detailed skin texture:1),((solo:1.5)),Detailed face,(see-through:1.1),misty,Low Key:1.1,depth of field,A young woman with no clothes,sitting on her bed with contemplative expression.,"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015777,"offset":[68.18275244340464,324.85306346504876]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by real-human-male** [comment]
Not changing code doesn't make bugs go away....
