### ISSUE TITLE
'charmap' codec can't encode character '\u015b' in position 0: character maps to <undefined>

### ISSUE THREAD

**Issue by Torcelllo** [comfyanonymous/ComfyUI#5557]
### Expected Behavior

Automatically move from one generation to the next

### Actual Behavior

Stops after completing generation - but does not automatically move onto the next one

### Steps to Reproduce

![Torcello-GTM_2024-11-09_0074](https://github.com/user-attachments/assets/d8bca884-e37c-4759-b03c-f513d28b9e20)

### Debug Logs

```powershell
CPU
11%
RAM
80%
Temp
50°
VRAM
81%
GPU
15%

Manager




Show Image Feed 🐍
1

UnicodeEncodeError 387 easy saveText
easy saveText
'charmap' codec can't encode character '\u015b' in position 0: character maps to <undefined>


# ComfyUI Error Report
## Error Details
- **Node Type:** easy saveText
- **Exception Type:** UnicodeEncodeError
- **Exception Message:** 'charmap' codec can't encode character '\u015b' in position 0: character maps to <undefined>
## Stack Trace

  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 1625, in save_text
    text_file.write(line)

  File "encodings\cp1252.py", line 19, in encode

```
## System Information
- **ComfyUI Version:** v0.2.7-9-g6ee066a
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2070 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589475840
  - **VRAM Free:** 5954235764
  - **Torch VRAM Total:** 402653184
  - **Torch VRAM Free:** 33820020

## Logs
```
2024-11-09T11:37:48.639433 - got prompt
2024-11-09T11:37:55.348364 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T11:37:55.353065 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T11:37:55.353581 - 
2024-11-09T11:37:55.410883 - Requested to load SD3ClipModel_
2024-11-09T11:37:55.410883 - Loading 1 new model
2024-11-09T11:37:57.529376 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T11:38:13.526434 - Requested to load SD3ClipModel_
2024-11-09T11:38:13.526434 - Loading 1 new model
2024-11-09T11:38:17.316827 - loaded partially 5654.8 5643.38671875 0
2024-11-09T11:38:30.354691 - Requested to load SD3
2024-11-09T11:38:30.354691 - Loading 1 new model
2024-11-09T11:38:33.910927 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T11:40:51.890157 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:17<00:00, 27.59s/it]2024-11-09T11:40:51.891159 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:17<00:00, 27.60s/it]2024-11-09T11:40:51.891159 - 
2024-11-09T11:40:51.937199 - Requested to load AutoencodingEngine
2024-11-09T11:40:51.937199 - Loading 1 new model
2024-11-09T11:40:54.295345 - loaded completely 0.0 319.7467155456543 True
2024-11-09T11:40:57.091445 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0062.png[0m2024-11-09T11:40:57.091445 - 
2024-11-09T11:40:57.216559 - Prompt executed in 188.54 seconds
2024-11-09T11:40:57.512828 - got prompt
2024-11-09T11:41:03.824003 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T11:41:03.829365 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T11:41:03.829365 - 
2024-11-09T11:41:03.893136 - Requested to load SD3ClipModel_
2024-11-09T11:41:03.893136 - Loading 1 new model
2024-11-09T11:41:05.975901 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T11:41:23.139161 - Requested to load SD3ClipModel_
2024-11-09T11:41:23.139161 - Loading 1 new model
2024-11-09T11:41:26.827517 - loaded partially 5654.8 5643.38671875 0
2024-11-09T11:41:33.219054 - Requested to load SD3
2024-11-09T11:41:33.219054 - Loading 1 new model
2024-11-09T11:41:36.735253 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T11:43:53.428377 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:16<00:00, 27.47s/it]2024-11-09T11:43:53.428377 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:16<00:00, 27.34s/it]2024-11-09T11:43:53.429378 - 
2024-11-09T11:43:53.474419 - Requested to load AutoencodingEngine
2024-11-09T11:43:53.475420 - Loading 1 new model
2024-11-09T11:43:58.590075 - loaded completely 0.0 319.7467155456543 True
2024-11-09T11:44:01.076337 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0063.png[0m2024-11-09T11:44:01.076337 - 
2024-11-09T11:44:01.213462 - Prompt executed in 183.67 seconds
2024-11-09T11:44:01.513736 - got prompt
2024-11-09T11:44:08.367749 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T11:44:08.372919 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T11:44:08.372919 - 
2024-11-09T11:44:08.428217 - Requested to load SD3ClipModel_
2024-11-09T11:44:08.428217 - Loading 1 new model
2024-11-09T11:44:10.458907 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T11:44:26.804657 - Requested to load SD3ClipModel_
2024-11-09T11:44:26.805657 - Loading 1 new model
2024-11-09T11:44:30.566079 - loaded partially 5654.8 5643.38671875 0
2024-11-09T11:44:37.375275 - Requested to load SD3
2024-11-09T11:44:37.375275 - Loading 1 new model
2024-11-09T11:44:40.910492 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T11:47:05.107383 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:24<00:00, 28.65s/it]2024-11-09T11:47:05.107383 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:24<00:00, 28.84s/it]2024-11-09T11:47:05.108384 - 
2024-11-09T11:47:05.154425 - Requested to load AutoencodingEngine
2024-11-09T11:47:05.154425 - Loading 1 new model
2024-11-09T11:47:09.623592 - loaded completely 0.0 319.7467155456543 True
2024-11-09T11:47:12.256988 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0064.png[0m2024-11-09T11:47:12.256988 - 
2024-11-09T11:47:12.381101 - Prompt executed in 190.82 seconds
2024-11-09T11:47:12.662359 - got prompt
2024-11-09T11:47:20.379661 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T11:47:20.384284 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T11:47:20.384789 - 
2024-11-09T11:47:20.385367 - !!! Exception during processing !!! 'charmap' codec can't encode character '\u0111' in position 0: character maps to <undefined>
2024-11-09T11:47:20.387956 - Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 1625, in save_text
    text_file.write(line)
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u0111' in position 0: character maps to <undefined>

2024-11-09T11:47:20.390031 - Prompt executed in 7.69 seconds
2024-11-09T13:04:15.877679 - got prompt
2024-11-09T13:04:26.679797 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:04:26.685056 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:04:26.685056 - 
2024-11-09T13:04:26.779641 - Requested to load SD3ClipModel_
2024-11-09T13:04:26.780642 - Loading 1 new model
2024-11-09T13:04:29.556909 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:04:53.032672 - Requested to load SD3ClipModel_
2024-11-09T13:04:53.033673 - Loading 1 new model
2024-11-09T13:04:57.872962 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:05:04.538030 - Requested to load SD3
2024-11-09T13:05:04.538030 - Loading 1 new model
2024-11-09T13:05:08.264420 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:08:13.230997 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:04<00:00, 36.71s/it]2024-11-09T13:08:13.231997 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:04<00:00, 36.99s/it]2024-11-09T13:08:13.231997 - 
2024-11-09T13:08:13.285045 - Requested to load AutoencodingEngine
2024-11-09T13:08:13.285045 - Loading 1 new model
2024-11-09T13:08:15.833155 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:08:18.801857 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0065.png[0m2024-11-09T13:08:18.802858 - 
2024-11-09T13:08:18.922967 - Prompt executed in 243.01 seconds
2024-11-09T13:08:19.773904 - got prompt
2024-11-09T13:08:28.182025 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:08:28.187540 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:08:28.187540 - 
2024-11-09T13:08:28.292730 - Requested to load SD3ClipModel_
2024-11-09T13:08:28.292730 - Loading 1 new model
2024-11-09T13:08:30.272519 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:08:51.874499 - Requested to load SD3ClipModel_
2024-11-09T13:08:51.874499 - Loading 1 new model
2024-11-09T13:08:55.839109 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:09:10.064055 - Requested to load SD3
2024-11-09T13:09:10.064055 - Loading 1 new model
2024-11-09T13:09:14.276375 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:12:20.900490 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.59s/it]2024-11-09T13:12:20.900490 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.32s/it]2024-11-09T13:12:20.900490 - 
2024-11-09T13:12:20.964548 - Requested to load AutoencodingEngine
2024-11-09T13:12:20.964548 - Loading 1 new model
2024-11-09T13:12:25.891032 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:12:28.430415 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0066.png[0m2024-11-09T13:12:28.430415 - 
2024-11-09T13:12:28.553984 - Prompt executed in 248.75 seconds
2024-11-09T13:12:28.849256 - got prompt
2024-11-09T13:12:35.532191 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:12:35.537196 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:12:35.537196 - 
2024-11-09T13:12:35.600252 - Requested to load SD3ClipModel_
2024-11-09T13:12:35.601253 - Loading 1 new model
2024-11-09T13:12:37.779068 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:12:53.665097 - Requested to load SD3ClipModel_
2024-11-09T13:12:53.665097 - Loading 1 new model
2024-11-09T13:12:57.618695 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:13:04.430895 - Requested to load SD3
2024-11-09T13:13:04.430895 - Loading 1 new model
2024-11-09T13:13:08.241364 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:15:53.213843 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:44<00:00, 33.32s/it]2024-11-09T13:15:53.214844 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [02:44<00:00, 32.99s/it]2024-11-09T13:15:53.214844 - 
2024-11-09T13:15:53.273897 - Requested to load AutoencodingEngine
2024-11-09T13:15:53.273897 - Loading 1 new model
2024-11-09T13:15:58.157343 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:16:01.567446 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0067.png[0m2024-11-09T13:16:01.567446 - 
2024-11-09T13:16:01.695561 - Prompt executed in 212.81 seconds
2024-11-09T13:16:01.972813 - got prompt
2024-11-09T13:16:07.782970 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:16:07.787628 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:16:07.787628 - 
2024-11-09T13:16:07.839070 - Requested to load SD3ClipModel_
2024-11-09T13:16:07.839070 - Loading 1 new model
2024-11-09T13:16:09.994317 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:16:24.184106 - Requested to load SD3ClipModel_
2024-11-09T13:16:24.184106 - Loading 1 new model
2024-11-09T13:16:27.954534 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:16:34.699672 - Requested to load SD3
2024-11-09T13:16:34.700674 - Loading 1 new model
2024-11-09T13:16:38.227884 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:19:46.629207 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:08<00:00, 37.79s/it]2024-11-09T13:19:46.629207 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:08<00:00, 37.68s/it]2024-11-09T13:19:46.629207 - 
2024-11-09T13:19:46.682256 - Requested to load AutoencodingEngine
2024-11-09T13:19:46.682256 - Loading 1 new model
2024-11-09T13:19:52.069190 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:19:54.760608 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0068.png[0m2024-11-09T13:19:54.760608 - 
2024-11-09T13:19:54.884722 - Prompt executed in 232.88 seconds
2024-11-09T13:19:55.171983 - got prompt
2024-11-09T13:20:01.603363 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:20:01.608077 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:20:01.608601 - 
2024-11-09T13:20:01.663893 - Requested to load SD3ClipModel_
2024-11-09T13:20:01.663893 - Loading 1 new model
2024-11-09T13:20:03.723783 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:20:20.717816 - Requested to load SD3ClipModel_
2024-11-09T13:20:20.717816 - Loading 1 new model
2024-11-09T13:20:24.548301 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:20:39.279709 - Requested to load SD3
2024-11-09T13:20:39.279709 - Loading 1 new model
2024-11-09T13:20:43.203281 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:23:49.747374 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.28s/it]2024-11-09T13:23:49.747374 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.31s/it]2024-11-09T13:23:49.747374 - 
2024-11-09T13:23:49.801423 - Requested to load AutoencodingEngine
2024-11-09T13:23:49.801423 - Loading 1 new model
2024-11-09T13:23:53.913165 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:23:57.171130 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0069.png[0m2024-11-09T13:23:57.171130 - 
2024-11-09T13:23:57.315261 - Prompt executed in 242.10 seconds
2024-11-09T13:23:57.612533 - got prompt
2024-11-09T13:24:05.663793 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:24:05.675699 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:24:05.675699 - 
2024-11-09T13:24:05.751768 - Requested to load SD3ClipModel_
2024-11-09T13:24:05.751768 - Loading 1 new model
2024-11-09T13:24:07.955383 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:24:16.490281 - Requested to load SD3ClipModel_
2024-11-09T13:24:16.490281 - Loading 1 new model
2024-11-09T13:24:20.354799 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:24:26.653534 - Requested to load SD3
2024-11-09T13:24:26.653534 - Loading 1 new model
2024-11-09T13:24:30.403945 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:27:38.059028 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:07<00:00, 37.49s/it]2024-11-09T13:27:38.059028 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:07<00:00, 37.53s/it]2024-11-09T13:27:38.059028 - 
2024-11-09T13:27:38.112076 - Requested to load AutoencodingEngine
2024-11-09T13:27:38.113078 - Loading 1 new model
2024-11-09T13:27:42.847387 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:27:45.774053 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0070.png[0m2024-11-09T13:27:45.774053 - 
2024-11-09T13:27:45.930192 - Prompt executed in 228.28 seconds
2024-11-09T13:27:46.268501 - got prompt
2024-11-09T13:27:52.328776 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:27:52.333432 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:27:52.333432 - 
2024-11-09T13:27:52.377643 - Requested to load SD3ClipModel_
2024-11-09T13:27:52.377643 - Loading 1 new model
2024-11-09T13:27:54.500944 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:28:08.314406 - Requested to load SD3ClipModel_
2024-11-09T13:28:08.314406 - Loading 1 new model
2024-11-09T13:28:12.095690 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:28:18.797790 - Requested to load SD3
2024-11-09T13:28:18.797790 - Loading 1 new model
2024-11-09T13:28:22.906530 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:31:29.129780 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.15s/it]2024-11-09T13:31:29.129780 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.24s/it]2024-11-09T13:31:29.129780 - 
2024-11-09T13:31:29.182828 - Requested to load AutoencodingEngine
2024-11-09T13:31:29.183829 - Loading 1 new model
2024-11-09T13:31:33.800032 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:31:36.868826 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0071.png[0m2024-11-09T13:31:36.868826 - 
2024-11-09T13:31:36.994941 - Prompt executed in 230.67 seconds
2024-11-09T13:31:37.266187 - got prompt
2024-11-09T13:31:43.793139 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:31:43.798285 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:31:43.798285 - 
2024-11-09T13:31:43.866054 - Requested to load SD3ClipModel_
2024-11-09T13:31:43.866054 - Loading 1 new model
2024-11-09T13:31:45.960936 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:32:01.989206 - Requested to load SD3ClipModel_
2024-11-09T13:32:01.989206 - Loading 1 new model
2024-11-09T13:32:06.053756 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:32:12.869962 - Requested to load SD3
2024-11-09T13:32:12.869962 - Loading 1 new model
2024-11-09T13:32:17.114849 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:35:23.668446 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.16s/it]2024-11-09T13:35:23.669436 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:06<00:00, 37.31s/it]2024-11-09T13:35:23.669436 - 
2024-11-09T13:35:23.724486 - Requested to load AutoencodingEngine
2024-11-09T13:35:23.724486 - Loading 1 new model
2024-11-09T13:35:29.207477 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:35:33.535417 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0072.png[0m2024-11-09T13:35:33.536418 - 
2024-11-09T13:35:33.655526 - Prompt executed in 236.29 seconds
2024-11-09T13:35:33.944790 - got prompt
2024-11-09T13:35:40.129541 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:35:40.133653 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:35:40.134221 - 
2024-11-09T13:35:40.196385 - Requested to load SD3ClipModel_
2024-11-09T13:35:40.197387 - Loading 1 new model
2024-11-09T13:35:42.362428 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:35:55.382139 - Requested to load SD3ClipModel_
2024-11-09T13:35:55.382139 - Loading 1 new model
2024-11-09T13:35:59.271501 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:36:06.087706 - Requested to load SD3
2024-11-09T13:36:06.088707 - Loading 1 new model
2024-11-09T13:36:09.940694 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:39:14.407453 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:04<00:00, 36.85s/it]2024-11-09T13:39:14.408454 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:04<00:00, 36.89s/it]2024-11-09T13:39:14.408454 - 
2024-11-09T13:39:14.461503 - Requested to load AutoencodingEngine
2024-11-09T13:39:14.461503 - Loading 1 new model
2024-11-09T13:39:17.679432 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:39:21.000455 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0073.png[0m2024-11-09T13:39:21.000455 - 
2024-11-09T13:39:21.121566 - Prompt executed in 227.14 seconds
2024-11-09T13:39:21.411829 - got prompt
2024-11-09T13:39:27.227952 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:39:27.232592 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:39:27.232592 - 
2024-11-09T13:39:27.282841 - Requested to load SD3ClipModel_
2024-11-09T13:39:27.282841 - Loading 1 new model
2024-11-09T13:39:29.288214 - loaded partially 5654.8 5655.13525390625 0
2024-11-09T13:39:40.875688 - Requested to load SD3ClipModel_
2024-11-09T13:39:40.875688 - Loading 1 new model
2024-11-09T13:39:44.768231 - loaded partially 5654.8 5643.38671875 0
2024-11-09T13:39:51.366238 - Requested to load SD3
2024-11-09T13:39:51.367239 - Loading 1 new model
2024-11-09T13:39:55.255779 - loaded partially 5654.799977111817 5654.55029296875 0
2024-11-09T13:43:02.982096 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:07<00:00, 37.65s/it]2024-11-09T13:43:02.983096 - 
100%|████████████████████████████████████████████████████████████████████████████████████| 5/5 [03:07<00:00, 37.54s/it]2024-11-09T13:43:02.983096 - 
2024-11-09T13:43:03.036145 - Requested to load AutoencodingEngine
2024-11-09T13:43:03.036145 - Loading 1 new model
2024-11-09T13:43:09.772276 - loaded completely 0.0 319.7467155456543 True
2024-11-09T13:43:12.970187 - [34mWAS Node Suite: [0mImage file saved to: X:\ComfyUI_Base\output\GTM\Torcello-GTM_2024-11-09_0074.png[0m2024-11-09T13:43:12.970187 - 
2024-11-09T13:43:13.094300 - Prompt executed in 231.64 seconds
2024-11-09T13:43:13.386566 - got prompt
2024-11-09T13:43:21.047768 - HTTP Request: POST http://127.0.0.1:11434/v1/chat/completions "HTTP/1.1 200 OK"
2024-11-09T13:43:21.052411 - [1m[36m[EasyUse] Save Text:[0m Saving to Output/ComfyUI\2024-11-09 3.5LT_LLM.txt2024-11-09T13:43:21.052927 - 
2024-11-09T13:43:21.053455 - !!! Exception during processing !!! 'charmap' codec can't encode character '\u015b' in position 0: character maps to <undefined>
2024-11-09T13:43:21.055043 - Traceback (most recent call last):
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "X:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py", line 1625, in save_text
    text_file.write(line)
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u015b' in position 0: character maps to <undefined>

2024-11-09T13:43:21.056593 - Prompt executed in 7.63 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

Sporadic. Worked fine over 60 generations, then bug started to occur after every two or three generations. ComfyUI and all other nodes up-to-date.

**Comment by Torcelllo** [comment]
[Sporadic.txt](https://github.com/user-attachments/files/17687643/Sporadic.txt)

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Easy-Use repo.
https://github.com/yolain/ComfyUI-Easy-Use
