### ISSUE TITLE
!!! Exception during processing !!! 'tokenizers.AddedToken' object has no attribute 'special'

### ISSUE THREAD

**Issue by npubg** [comfyanonymous/ComfyUI#5561]
### Your question

Error while loading checkpoint:!!! Exception during processing !!!  'tokenizers.AddedToken' object has no attribute 'special'

### Logs

```powershell
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using pytorch attention in VAE
Using pytorch attention in VAE
Ignored unknown kwarg option special
Ignored unknown kwarg option special
Ignored unknown kwarg option special
!!! Exception during processing !!! 'tokenizers.AddedToken' object has no attribute 'special'
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\nodes.py", line 549, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\comfy\sd.py", line 611, in load_checkpoint_guess_config
    out = load_state_dict_guess_config(sd, output_vae, output_clip, output_clipvision, embedding_directory, output_model, model_options, te_model_options=te_model_options)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\comfy\sd.py", line 665, in load_state_dict_guess_config
    clip = CLIP(clip_target, embedding_directory=embedding_directory, tokenizer_data=clip_sd, parameters=parameters, model_options=te_model_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\comfy\sd.py", line 93, in __init__
    self.tokenizer = tokenizer(embedding_directory=embedding_directory, tokenizer_data=tokenizer_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\comfy\sdxl_clip.py", line 26, in __init__
    self.clip_l = clip_l_tokenizer_class(embedding_directory=embedding_directory)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 417, in __init__
    self.tokenizer = tokenizer_class.from_pretrained(tokenizer_path)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2213, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2447, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\python_embeded\Lib\site-packages\transformers\models\clip\tokenization_clip.py", line 323, in __init__
    super().__init__(
  File "D:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils.py", line 439, in __init__
    self._add_tokens(
  File "D:\ComfyUI\python_embeded\Lib\site-packages\transformers\tokenization_utils.py", line 569, in _add_tokens
    if not token.special and token.normalized and getattr(self, "do_lower_case", False):
           ^^^^^^^^^^^^^
AttributeError: 'tokenizers.AddedToken' object has no attribute 'special'

Prompt executed in 1.43 seconds
```

**Comment by ltdrdata** [comment]
What is your checkpoint model?

**Comment by Sorry-Im-Stupid** [comment]
Never had this before, now I'm having it. 
Tried the blender addon again today, it's even more useless than before...
But there shouldn't be any reason it would make a mess of the existing comfy install just from connecting to it.

**Comment by ltdrdata** [comment]
> Never had this before, now I'm having it. Tried the blender addon again today, it's even more useless than before... But there shouldn't be any reason it would make a mess of the existing comfy install just from connecting to it.
> 
> Terminal output has a new error I've not seen before: `Package diffusers installed failed Module 'diffusers' load failed. If you don't have it installed, do it: pip install diffusers Package diffusers installed failed `

literally you need to install `diffusers`.
And your issue doesn't seem to be related to this issue.
