### ISSUE TITLE
TripoSRModelLoader invalid load key, ' '.

### ISSUE THREAD

**Issue by liuhelen0402** [comfyanonymous/ComfyUI#5575]
### Expected Behavior

- Assemble workflow image to mask, mask to image, image to 3d using TripoSR.
- Press queue item
- Generates 3d model based on workflows

### Actual Behavior

- Assemble workflow image to mask, mask to image, image to 3d using TripoSR.
- Press queue item
- Around 30%, returns error code: TripoSRModelLoader
invalid load key, ' '.

### Steps to Reproduce

<img width="1202" alt="Screenshot 2024-11-10 at 8 32 18 PM" src="https://github.com/user-attachments/assets/b5db44a6-27a3-4b68-87b2-352ae607cb04">

### Debug Logs

```powershell
2024-11-10 20:27:50,421 - root - ERROR - Traceback (most recent call last):
  File "/Applications/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Applications/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI/custom_nodes/ComfyUI-Flowty-TripoSR/__init__.py", line 45, in load
    self.initialized_model = TSR.from_pretrained_custom(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI/custom_nodes/ComfyUI-Flowty-TripoSR/tsr/system.py", line 80, in from_pretrained_custom
    ckpt = torch.load(weight_path, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI/venv/lib/python3.11/site-packages/torch/serialization.py", line 1441, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "/Applications/ComfyUI/venv/lib/python3.11/site-packages/torch/serialization.py", line 1685, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.UnpicklingError: invalid load key, ' '.

2024-11-10 20:27:50,422 - root - INFO - Prompt executed in 6.16 seconds
```

**Comment by ltdrdata** [comment]
You have to use choose proper model to use TripoSR.
https://github.com/flowtyone/ComfyUI-Flowty-TripoSR?tab=readme-ov-file#installation
