### ISSUE TITLE
LayerUtility: Florence2Image2Prompt 'NoneType' object is not callable

### ISSUE THREAD

**Issue by busididi** [comfyanonymous/ComfyUI#5577]
### Your question

# ComfyUI Error Report
## Error Details
- **Node Type:** LayerUtility: Florence2Image2Prompt
- **Exception Type:** TypeError
- **Exception Message:** 'NoneType' object is not callable
### Logs

```powershell
## Stack Trace

  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 585, in florence2_image2prompt
    results, output_image = process_image(model, processor, img, task, max_new_tokens, num_beams,

  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 308, in process_image
    results = run_example(model, processor, task_prompt, image, max_new_tokens, num_beams, do_sample)

  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 210, in run_example
    inputs = processor(text=prompt, images=image, return_tensors="pt").to(device)

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** F:\ComfyUI\ComfyUI-aki-v1.3\main.py --auto-launch --preview-method auto --disable-cuda-malloc
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 13711444208
  - **Torch VRAM Total:** 2147483648
  - **Torch VRAM Free:** 110364912

## Logs
```
2024-11-11 10:48:37,716 - root - INFO - Total VRAM 16376 MB, total RAM 32581 MB
2024-11-11 10:48:37,717 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-11 10:48:43,369 - root - INFO - xformers version: 0.0.28.post3
2024-11-11 10:48:43,370 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-11 10:48:43,370 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-11-11 10:48:46,184 - root - INFO - Using xformers cross attention
2024-11-11 10:48:55,195 - root - INFO - [Prompt Server] web root: F:\ComfyUI\ComfyUI-aki-v1.3\web
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path checkpoints F:\sd-webui-aki-v4.8\models\Stable-diffusion
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path configs F:\sd-webui-aki-v4.8\configs
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path vae F:\sd-webui-aki-v4.8\models\VAE
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path loras F:\sd-webui-aki-v4.8\models/Lora
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path loras F:\sd-webui-aki-v4.8\models/LyCORIS
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path upscale_models F:\sd-webui-aki-v4.8\models/ESRGAN
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path upscale_models F:\sd-webui-aki-v4.8\models/RealESRGAN
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path upscale_models F:\sd-webui-aki-v4.8\models/SwinIR
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path embeddings F:\sd-webui-aki-v4.8\embeddings
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path hypernetworks F:\sd-webui-aki-v4.8\models/hypernetworks
2024-11-11 10:48:55,214 - root - INFO - Adding extra search path controlnet F:\sd-webui-aki-v4.8\models/ControlNet
2024-11-11 10:49:17,505 - root - INFO - Total VRAM 16376 MB, total RAM 32581 MB
2024-11-11 10:49:17,505 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-11 10:49:17,505 - root - INFO - xformers version: 0.0.28.post3
2024-11-11 10:49:17,505 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-11 10:49:17,505 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
2024-11-11 10:49:28,123 - root - INFO - --------------
2024-11-11 10:49:28,123 - root - INFO - [91m ### Mixlab Nodes: [93mLoaded
2024-11-11 10:49:28,125 - root - INFO - ChatGPT.available False
2024-11-11 10:49:28,126 - root - INFO - edit_mask.available True
2024-11-11 10:49:34,178 - root - INFO - ClipInterrogator.available True
2024-11-11 10:49:36,254 - root - INFO - PromptGenerate.available True
2024-11-11 10:49:36,254 - root - INFO - ChinesePrompt.available True
2024-11-11 10:49:36,254 - root - INFO - RembgNode_.available True
2024-11-11 10:49:41,262 - root - INFO - TripoSR.available
2024-11-11 10:49:41,263 - root - INFO - MiniCPMNode.available
2024-11-11 10:49:41,483 - root - INFO - Scenedetect.available
2024-11-11 10:49:42,181 - root - INFO - FishSpeech.available
2024-11-11 10:49:42,340 - root - INFO - SenseVoice.available
2024-11-11 10:49:43,138 - root - INFO - Whisper.available False
2024-11-11 10:49:43,231 - root - INFO - FalVideo.available
2024-11-11 10:49:43,231 - root - INFO - [93m -------------- [0m
2024-11-11 10:49:43,477 - root - WARNING - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Snap_Processing\\__init__.py'

2024-11-11 10:49:43,477 - root - WARNING - Cannot import F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Snap_Processing module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Snap_Processing\\__init__.py'
2024-11-11 10:50:04,171 - root - WARNING - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\efficiency-nodes-comfyui-main\\__init__.py'

2024-11-11 10:50:04,171 - root - WARNING - Cannot import F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\efficiency-nodes-comfyui-main\\__init__.py'
2024-11-11 10:50:04,468 - root - WARNING - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\SenseVoice-python-main\\__init__.py'

2024-11-11 10:50:04,468 - root - WARNING - Cannot import F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\SenseVoice-python-main module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\SenseVoice-python-main\\__init__.py'
2024-11-11 10:50:05,528 - root - WARNING - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\nodes.py", line 2012, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\Snaptag\\__init__.py'

2024-11-11 10:50:05,528 - root - WARNING - Cannot import F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\Snaptag module for custom nodes: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\Snaptag\\__init__.py'
2024-11-11 10:50:09,894 - root - INFO - 
Import times for custom nodes:
2024-11-11 10:50:09,894 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_IPAdapter_plus
2024-11-11 10:50:09,894 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\websocket_image_save.py
2024-11-11 10:50:09,894 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ControlNet-LLLite-ComfyUI
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui_controlnet_aux
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\Snaptag
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui-main
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\SenseVoice-python-main
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Impact-Pack
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\efficiency-nodes-comfyui
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Styles_CSV_Loader
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\PowerNoiseSuite
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\stability-ComfyUI-nodes
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\FreeU_Advanced
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_ADV_CLIP_emb
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\AIGODLIKE-ComfyUI-Translation
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\cg-use-everywhere
2024-11-11 10:50:09,895 - root - INFO -    0.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui-lama-remover
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_experiments
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-WD14-Tagger
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_TiledKSampler
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\cg-image-picker
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-CSV-Loader
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyLiterals
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Video-Matting
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\images-grid-comfy-plugin
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-IC-Light
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\Derfuu_ComfyUI_ModdedNodes
2024-11-11 10:50:09,895 - root - INFO -    0.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui-inpaint-nodes
2024-11-11 10:50:09,895 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_UltimateSDUpscale
2024-11-11 10:50:09,895 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_essentials
2024-11-11 10:50:09,895 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\rgthree-comfy
2024-11-11 10:50:09,895 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-11-11 10:50:09,895 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-JDCN
2024-11-11 10:50:09,895 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfy-image-saver
2024-11-11 10:50:09,896 - root - INFO -    0.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Text_Image-Composite
2024-11-11 10:50:09,896 - root - INFO -    0.2 seconds (IMPORT FAILED): F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Snap_Processing
2024-11-11 10:50:09,896 - root - INFO -    0.3 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-KJNodes
2024-11-11 10:50:09,896 - root - INFO -    0.3 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Marigold
2024-11-11 10:50:09,896 - root - INFO -    0.3 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Custom-Scripts
2024-11-11 10:50:09,896 - root - INFO -    0.4 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Inspire-Pack
2024-11-11 10:50:09,896 - root - INFO -    0.4 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Advanced-ControlNet
2024-11-11 10:50:09,896 - root - INFO -    0.5 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Crystools
2024-11-11 10:50:09,896 - root - INFO -    0.6 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui-workspace-manager
2024-11-11 10:50:09,896 - root - INFO -    0.7 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-11-11 10:50:09,896 - root - INFO -    0.7 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_MiniCPM-V-2_6-int4
2024-11-11 10:50:09,896 - root - INFO -    0.9 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui-string-converter
2024-11-11 10:50:09,896 - root - INFO -    1.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\Snap-Processing
2024-11-11 10:50:09,896 - root - INFO -    1.4 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager
2024-11-11 10:50:09,896 - root - INFO -    1.5 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui_segment_anything
2024-11-11 10:50:09,896 - root - INFO -    1.6 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Easy-Use
2024-11-11 10:50:09,896 - root - INFO -    2.4 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle
2024-11-11 10:50:09,896 - root - INFO -    2.4 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Gemini
2024-11-11 10:50:09,896 - root - INFO -    2.9 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui-art-venture
2024-11-11 10:50:09,896 - root - INFO -    3.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-BrushNet
2024-11-11 10:50:09,896 - root - INFO -    3.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_FizzNodes
2024-11-11 10:50:09,896 - root - INFO -    4.1 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Anyline
2024-11-11 10:50:09,896 - root - INFO -    4.3 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\was-node-suite-comfyui
2024-11-11 10:50:09,896 - root - INFO -   10.2 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_Custom_Nodes_AlekPet
2024-11-11 10:50:09,896 - root - INFO -   23.0 seconds: F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes
2024-11-11 10:50:09,896 - root - INFO - 
2024-11-11 10:50:10,088 - root - INFO - Starting server

2024-11-11 10:50:10,089 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-11 11:04:34,535 - root - INFO - got prompt
2024-11-11 11:04:34,555 - root - WARNING - WARNING: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Snap_Processing\\save\\output.png'
2024-11-11 11:04:44,750 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-11-11 11:04:44,751 - root - INFO - model_type EPS
2024-11-11 11:06:08,135 - root - INFO - Using xformers attention in VAE
2024-11-11 11:06:08,158 - root - INFO - Using xformers attention in VAE
2024-11-11 11:06:14,566 - root - INFO - Requested to load SDXLClipModel
2024-11-11 11:06:14,566 - root - INFO - Loading 1 new model
2024-11-11 11:06:14,574 - root - INFO - loaded completely 0.0 1560.802734375 True
2024-11-11 11:06:32,882 - root - INFO - model weight dtype torch.float16, manual cast: None
2024-11-11 11:06:32,883 - root - INFO - model_type EPS
2024-11-11 11:06:59,038 - root - INFO - Using xformers attention in VAE
2024-11-11 11:06:59,039 - root - INFO - Using xformers attention in VAE
2024-11-11 11:08:07,810 - root - ERROR - !!! Exception during processing !!! x1 must be greater than or equal to x0
2024-11-11 11:08:07,916 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\crop_by_mask_v2.py", line 93, in crop_by_mask_v2
    preview_image = draw_rect(preview_image, crop_box[0], crop_box[1],
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\imagefunc.py", line 745, in draw_rect
    draw.rectangle((x, y, x + width, y + height), fill=box_color, outline=line_color, width=line_width, )
  File "F:\ComfyUI\ComfyUI-aki-v1.3\python\lib\site-packages\PIL\ImageDraw.py", line 413, in rectangle
    self.draw.draw_rectangle(xy, ink, 0, width)
ValueError: x1 must be greater than or equal to x0

2024-11-11 11:08:07,917 - root - INFO - Prompt executed in 213.37 seconds
2024-11-11 11:08:59,341 - root - INFO - got prompt
2024-11-11 11:08:59,360 - root - WARNING - WARNING: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Snap_Processing\\save\\output.png'
2024-11-11 11:09:05,845 - root - ERROR - !!! Exception during processing !!! 'NoneType' object is not callable
2024-11-11 11:09:05,845 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 585, in florence2_image2prompt
    results, output_image = process_image(model, processor, img, task, max_new_tokens, num_beams,
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 308, in process_image
    results = run_example(model, processor, task_prompt, image, max_new_tokens, num_beams, do_sample)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 210, in run_example
    inputs = processor(text=prompt, images=image, return_tensors="pt").to(device)
TypeError: 'NoneType' object is not callable

2024-11-11 11:09:05,846 - root - INFO - Prompt executed in 6.49 seconds
2024-11-11 11:09:09,476 - root - INFO - got prompt
2024-11-11 11:09:09,494 - root - WARNING - WARNING: [Errno 2] No such file or directory: 'F:\\ComfyUI\\ComfyUI-aki-v1.3\\custom_nodes\\ComfyUI-Snap_Processing\\save\\output.png'
2024-11-11 11:09:09,734 - root - ERROR - !!! Exception during processing !!! 'NoneType' object is not callable
2024-11-11 11:09:09,735 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 585, in florence2_image2prompt
    results, output_image = process_image(model, processor, img, task, max_new_tokens, num_beams,
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 308, in process_image
    results = run_example(model, processor, task_prompt, image, max_new_tokens, num_beams, do_sample)
  File "F:\ComfyUI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI_LayerStyle\py\florence2_ultra.py", line 210, in run_example
    inputs = processor(text=prompt, images=image, return_tensors="pt").to(device)
TypeError: 'NoneType' object is not callable

2024-11-11 11:09:09,736 - root - INFO - Prompt executed in 0.24 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI_LayerStyle repo.
https://github.com/chflame163/ComfyUI_LayerStyle
