### ISSUE TITLE
ModelSamplingDiscreteDistilled.__init__() got an unexpected keyword argument 'zsnr'

### ISSUE THREAD

**Issue by BoynChan** [comfyanonymous/ComfyUI#5595]
### Expected Behavior

Good to go

### Actual Behavior

got exception
```
!!! Exception during processing !!! ModelSamplingDiscreteDistilled.__init__() got an unexpected keyword argument 'zsnr'
```

### Steps to Reproduce

-

### Debug Logs

```powershell
!!! Exception during processing !!! ModelSamplingDiscreteDistilled.__init__() got an unexpected keyword argument 'zsnr'
Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/comfy_extras/nodes_model_advanced.py", line 84, in patch
    model_sampling = ModelSamplingAdvanced(model.model.model_config, zsnr=zsnr)
TypeError: ModelSamplingDiscreteDistilled.__init__() got an unexpected keyword argument 'zsnr'
```

### Other

I think it's related on this commit https://github.com/comfyanonymous/ComfyUI/commit/2a18e98ccf083f7e8d54ef712610aa31adb570d0

_No response_

**Comment by ytoaa** [comment]
I have the same symptoms.

**Comment by lawncom** [comment]
I have the same symptoms.

**Comment by comfyanonymous** [comment]
Should be fixed now.
