### ISSUE TITLE
dzOmniGenWrapper OmniGen.from_pretrained() got an unexpected keyword argument 'quantize' 

### ISSUE THREAD

**Issue by ABIA2024** [comfyanonymous/ComfyUI#5599]
### Your question

how can i find a solution?

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** dzOmniGenWrapper
- **Exception Type:** TypeError
- **Exception Message:** OmniGen.from_pretrained() got an unexpected keyword argument 'quantize'
## Stack Trace

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 105, in run_omnigen
    self.model = OmniGen_Model(quantization)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 32, in __init__
    self.pipe = OmniGenPipeline.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 83, in from_pretrained
    model = OmniGen.from_pretrained(model_name, quantize=Quantization)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.7-19-g8ebf2d8
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 2080 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 8589475840
  - **VRAM Free:** 7443841024
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```

## Execute install/(de)activation script for 'C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper'2024-11-12T21:48:21.897605 - 
2024-11-12T21:48:23.054692 - 2024-11-12T21:48:23.054692 -  2024-11-12T21:48:23.054692 - Collecting peft
2024-11-12T21:48:23.054692 - 2024-11-12T21:48:23.056146 - 2024-11-12T21:48:23.056146 -  2024-11-12T21:48:23.056995 -   Using cached peft-0.13.2-py3-none-any.whl.metadata (13 kB)
2024-11-12T21:48:23.057163 - 2024-11-12T21:48:23.063181 - 2024-11-12T21:48:23.063181 -  2024-11-12T21:48:23.174037 - Using cached peft-0.13.2-py3-none-any.whl (320 kB)
2024-11-12T21:48:23.174986 - 2024-11-12T21:48:23.321077 - 2024-11-12T21:48:23.321077 -  2024-11-12T21:48:23.321077 - Installing collected packages: peft
2024-11-12T21:48:23.321077 - 2024-11-12T21:48:24.721052 - 2024-11-12T21:48:24.721052 -  2024-11-12T21:48:24.721052 - Successfully installed peft-0.13.2
2024-11-12T21:48:24.721052 - 2024-11-12T21:48:24.976986 - 
## ComfyUI-Manager: EXECUTE => ['C:\\ComfyUI\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-m', 'pip', 'install', 'huggingface_hub']2024-11-12T21:48:24.976986 - 
2024-11-12T21:48:24.977995 - 
## Execute install/(de)activation script for 'C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper'2024-11-12T21:48:24.978974 - 

[ComfyUI-Manager] Startup script completed.2024-11-12T21:48:26.305494 - 
2024-11-12T21:48:26.306832 - #######################################################################
2024-11-12T21:48:26.306832 - 
2024-11-12T21:48:26.307868 - 
Prestartup times for custom nodes:2024-11-12T21:48:26.307868 - 
2024-11-12T21:48:26.308841 -   58.0 seconds:2024-11-12T21:48:26.308841 -  2024-11-12T21:48:26.308841 - C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager2024-11-12T21:48:26.308841 - 
2024-11-12T21:48:26.309521 - 
2024-11-12T21:48:28.084551 - Total VRAM 8192 MB, total RAM 65469 MB
2024-11-12T21:48:28.084551 - pytorch version: 2.5.1+cu124
2024-11-12T21:48:28.090727 - Set vram state to: NORMAL_VRAM
2024-11-12T21:48:28.091726 - Device: cuda:0 NVIDIA GeForce RTX 2080 : cudaMallocAsync
2024-11-12T21:48:29.062732 - Using pytorch cross attention
2024-11-12T21:48:30.300165 - [Prompt Server] web root: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\web
2024-11-12T21:48:31.407765 - [Crystools [0;32mINFO[0m] Crystools version: 1.21.0
2024-11-12T21:48:31.431447 - [Crystools [0;32mINFO[0m] CPU: Intel(R) Core(TM) i9-9900KF CPU @ 3.60GHz - Arch: AMD64 - OS: Windows 10
2024-11-12T21:48:31.440429 - [Crystools [0;32mINFO[0m] Pynvml (Nvidia) initialized.
2024-11-12T21:48:31.440429 - [Crystools [0;32mINFO[0m] GPU/s:
2024-11-12T21:48:31.451086 - [Crystools [0;32mINFO[0m] 0) NVIDIA GeForce RTX 2080
2024-11-12T21:48:31.453083 - [Crystools [0;32mINFO[0m] NVIDIA Driver: 560.94
2024-11-12T21:48:31.464081 - ### Loading: ComfyUI-Manager (V2.51.9)2024-11-12T21:48:31.465051 - 
2024-11-12T21:48:31.570732 - ### ComfyUI Revision: 2827 [8ebf2d88] | Released on '2024-11-12'2024-11-12T21:48:31.570732 - 
2024-11-12T21:48:31.926954 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-12T21:48:31.927978 - 
2024-11-12T21:48:31.983801 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-12T21:48:31.983801 - 
2024-11-12T21:48:32.041647 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-12T21:48:32.041647 - 
2024-11-12T21:48:32.204617 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-12T21:48:32.204617 - 
2024-11-12T21:48:32.235562 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-12T21:48:32.235562 - 
2024-11-12T21:48:32.566317 - # 😺 ComfyUI_OmniGen_Wrapper: -> [1;32mSuccess loaded 1 nodes.[m2024-11-12T21:48:32.566876 - 
2024-11-12T21:48:32.568064 - Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2022, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\OmniGen\\__init__.py'

2024-11-12T21:48:32.569031 - Cannot import C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\OmniGen module for custom nodes: [Errno 2] No such file or directory: 'C:\\ComfyUI\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\OmniGen\\__init__.py'
2024-11-12T21:48:32.569031 - 
Import times for custom nodes:
2024-11-12T21:48:32.570028 -    0.0 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-12T21:48:32.570028 -    0.0 seconds (IMPORT FAILED): C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\OmniGen
2024-11-12T21:48:32.570028 -    0.0 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-OmniGen
2024-11-12T21:48:32.571025 -    0.0 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-11-12T21:48:32.571263 -    0.3 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-12T21:48:32.571263 -    0.8 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-11-12T21:48:32.571263 -    0.8 seconds: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper
2024-11-12T21:48:32.571263 - 
2024-11-12T21:48:32.578250 - Starting server

2024-11-12T21:48:32.579475 - To see the GUI go to: http://127.0.0.1:8188
2024-11-12T21:48:33.196069 - FETCH DATA from: C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json2024-11-12T21:48:33.196069 - 2024-11-12T21:48:33.199061 -  [DONE]2024-11-12T21:48:33.199906 - 
2024-11-12T21:49:17.960836 - got prompt
2024-11-12T21:49:19.743167 - 
Fetching 10 files:  40%|█████████████████████████▌                                      | 4/10 [00:01<00:01,  3.05it/s]2024-11-12T21:50:02.681138 - got prompt
2024-11-12T21:52:40.362287 - 
Fetching 10 files:  50%|████████████████████████████████                                | 5/10 [03:21<04:40, 56.12s/it]2024-11-12T21:52:40.363536 - 
Fetching 10 files: 100%|███████████████████████████████████████████████████████████████| 10/10 [03:21<00:00, 20.19s/it]2024-11-12T21:52:40.363873 - 
2024-11-12T21:52:40.466338 - Loading OmniGen Model2024-11-12T21:52:40.466480 - 
2024-11-12T21:52:40.469760 - !!! Exception during processing !!! OmniGen.from_pretrained() got an unexpected keyword argument 'quantize'
2024-11-12T21:52:40.471724 - Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 105, in run_omnigen
    self.model = OmniGen_Model(quantization)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 32, in __init__
    self.pipe = OmniGenPipeline.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 83, in from_pretrained
    model = OmniGen.from_pretrained(model_name, quantize=Quantization)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OmniGen.from_pretrained() got an unexpected keyword argument 'quantize'

2024-11-12T21:52:40.473749 - Prompt executed in 202.51 seconds
2024-11-12T21:52:40.794146 - Loading OmniGen Model2024-11-12T21:52:40.795143 - 
2024-11-12T21:52:40.797114 - !!! Exception during processing !!! OmniGen.from_pretrained() got an unexpected keyword argument 'quantize'
2024-11-12T21:52:40.798111 - Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 105, in run_omnigen
    self.model = OmniGen_Model(quantization)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\omnigen.py", line 32, in __init__
    self.pipe = OmniGenPipeline.from_pretrained(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_OmniGen_Wrapper\py\OmniGen\pipeline.py", line 83, in from_pretrained
    model = OmniGen.from_pretrained(model_name, quantize=Quantization)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: OmniGen.from_pretrained() got an unexpected keyword argument 'quantize'

2024-11-12T21:52:40.800106 - Prompt executed in 0.22 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":6,"last_link_id":6,"nodes":[{"id":3,"type":"PreviewImage","pos":{"0":1259.5111083984375,"1":303.1180725097656},"size":{"0":313.86669921875,"1":253.24444580078125},"flags":{},"order":4,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":6}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":2,"type":"LoadImage","pos":{"0":225,"1":121},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[4]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["young-woman-7080194_1280.jpg","image"]},{"id":4,"type":"LoadImage","pos":{"0":245,"1":498},"size":{"0":315,"1":314},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[5]},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["woman-1754895_1280.jpg","image"]},{"id":1,"type":"ailab_OmniGen","pos":{"0":754,"1":562},"size":{"0":400,"1":428},"flags":{},"order":2,"mode":4,"inputs":[{"name":"image_1","type":"IMAGE","link":null,"shape":7},{"name":"image_2","type":"IMAGE","link":null,"shape":7},{"name":"image_3","type":"IMAGE","link":null,"shape":7}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[],"slot_index":0}],"properties":{"Node name for S&R":"ailab_OmniGen"},"widgets_values":["None","2 woman run in a street","Auto","Balanced",3.5,1.8,50,true,true,512,512,900040610523934,"randomize",1024]},{"id":6,"type":"dzOmniGenWrapper","pos":{"0":782,"1":102},"size":{"0":400,"1":380},"flags":{},"order":3,"mode":0,"inputs":[{"name":"image_1","type":"IMAGE","link":4,"shape":7},{"name":"image_2","type":"IMAGE","link":5,"shape":7},{"name":"image_3","type":"IMAGE","link":null,"shape":7}],"outputs":[{"name":"image","type":"IMAGE","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"dzOmniGenWrapper"},"widgets_values":["default","2 woman run in a street.\nFirst woman in image_1 . Secund woman in image_2 .",1024,1024,2.5,1.6,25,true,false,1107564482828436,"randomize",false]}],"links":[[4,2,0,6,0,"IMAGE"],[5,4,0,6,1,"IMAGE"],[6,6,0,3,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.9090909090909091,"offset":[-28.48889312744143,56.077754974365256]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by ltdrdata** [comment]
Please move this issue to the ComfyUI_OmniGen_Wrapper repo.
https://github.com/chflame163/ComfyUI_OmniGen_Wrapper
