### ISSUE TITLE
ValueError: numpy.dtype size changed, may indicate binary incompatibility.

### ISSUE THREAD

**Issue by leoliuzcl** [comfyanonymous/ComfyUI#5614]
### Your question

when i test ComfyUI_IPAdapter_plus, some error happened. And here is my comfyui json file
[face_id_test.json](https://github.com/user-attachments/files/17750604/face_id_test.json)

ComfyUI  run_nvidia_gpu show:

```D:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-14 23:17:55.468559
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI_windows_portable\ComfyUI
** Log path: D:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.9 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 65349 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI_windows_portable\ComfyUI\web
D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2830 [122c9ca1] *DETACHED | Released on '2024-11-14'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.2 seconds: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
```

Below is a list run in powershell  : PS` D:\ComfyUI_windows_portable\python_embeded> .\python.exe -m pip list

```
Package                Version
---------------------- ------------
aiohappyeyeballs       2.4.3
aiohttp                3.10.10
aiosignal              1.3.1
albucore               0.0.20
albumentations         1.4.21
annotated-types        0.7.0
attrs                  24.2.0
certifi                2024.8.30
cffi                   1.17.1
charset-normalizer     3.4.0
click                  8.1.7
colorama               0.4.6
coloredlogs            15.0.1
contourpy              1.3.1
cryptography           43.0.3
cycler                 0.12.1
Cython                 3.0.11
Deprecated             1.2.14
easydict               1.13
einops                 0.8.0
eval_type_backport     0.2.0
filelock               3.16.1
flatbuffers            24.3.25
fonttools              4.54.1
frozenlist             1.5.0
fsspec                 2024.10.0
gitdb                  4.0.11
GitPython              3.1.43
huggingface-hub        0.26.2
humanfriendly          10.0
idna                   3.10
imageio                2.36.0
insightface            0.7.3
Jinja2                 3.1.4
joblib                 1.4.2
kiwisolver             1.4.7
kornia                 0.7.3
kornia_rs              0.1.7
lazy_loader            0.4
markdown-it-py         3.0.0
MarkupSafe             3.0.2
matplotlib             3.9.2
matrix-client          0.4.0
mdurl                  0.1.2
mpmath                 1.3.0
multidict              6.1.0
networkx               3.4.2
numpy                  2.1.3
onnx                   1.16.1
onnxruntime            1.20.0
onnxruntime-gpu        1.20.0
opencv-python-headless 4.10.0.84
packaging              24.1
pillow                 11.0.0
pip                    24.3.1
prettytable            3.12.0
propcache              0.2.0
protobuf               5.28.3
psutil                 6.1.0
pycparser              2.22
pydantic               2.9.2
pydantic_core          2.23.4
pygit2                 1.16.0
PyGithub               2.5.0
Pygments               2.18.0
PyJWT                  2.9.0
PyNaCl                 1.5.0
pyparsing              3.2.0
pyreadline3            3.5.4
python-dateutil        2.9.0.post0
PyYAML                 6.0.2
regex                  2024.9.11
requests               2.32.3
rich                   13.9.4
safetensors            0.4.5
scikit-image           0.24.0
scikit-learn           1.5.2
scipy                  1.14.1
sentencepiece          0.2.0
setuptools             75.3.0
shellingham            1.5.4
simsimd                6.0.5
six                    1.16.0
smmap                  5.0.1
soundfile              0.12.1
spandrel               0.4.0
stringzilla            3.10.10
sympy                  1.13.1
threadpoolctl          3.5.0
tifffile               2024.9.20
tokenizers             0.20.1
torch                  2.5.1+cu124
torchaudio             2.5.1+cu124
torchsde               0.2.6
torchvision            0.20.1+cu124
tqdm                   4.66.6
trampoline             0.1.2
transformers           4.46.1
typer                  0.13.0
typing_extensions      4.12.2
urllib3                1.26.20
wcwidth                0.2.13
wrapt                  1.16.0
yarl                   1.17.1
```

Anybody can help?

### Logs

```powershell
Prompt executed in 0.01 seconds
got prompt
!!! Exception during processing !!! numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 674, in load_insightface
    return (insightface_loader(provider, model_name=model_name),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 159, in insightface_loader
    from insightface.app import FaceAnalysis
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface\\thirdparty\\face3d\\mesh\\cython\\mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Prompt executed in 0.01 seconds
FETCH DATA from: D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
!!! Exception during processing !!! numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\IPAdapterPlus.py", line 674, in load_insightface
    return (insightface_loader(provider, model_name=model_name),)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus\utils.py", line 159, in insightface_loader
    from insightface.app import FaceAnalysis
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\__init__.py", line 18, in <module>
    from . import app
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\__init__.py", line 2, in <module>
    from .mask_renderer import *
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\app\mask_renderer.py", line 8, in <module>
    from ..thirdparty import face3d
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\__init__.py", line 3, in <module>
    from . import mesh
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\insightface\thirdparty\face3d\mesh\__init__.py", line 9, in <module>
    from .cython import mesh_core_cython
  File "insightface\\thirdparty\\face3d\\mesh\\cython\\mesh_core_cython.pyx", line 1, in init insightface.thirdparty.face3d.mesh.cython.mesh_core_cython
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

Prompt executed in 0.01 seconds
```

**Comment by leoliuzcl** [comment]
found solution at  https://github.com/Gourieff/comfyui-reactor-node/discussions/460 ,   run
` .\python.exe -m pip install numpy===1.26.4 can fix this issue`
