### ISSUE TITLE
- **Exception Message:** '141.0.0.3.0.0.91'提示该错误,请帮助我解决该问题下

### ISSUE THREAD

**Issue by logo66612** [comfyanonymous/ComfyUI#5636]
### Your question

# ComfyUI Error Report
## Error Details
- **Node Type:** easy forLoopEnd
- **Exception Type:** KeyError
- **Exception Message:** '141.0.0.3.0.0.91'
## Stack Trace
File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 388, in combine_video
    kwargs = prompt[unique_id]['inputs']

### Logs

```powershell
[2024-11-16 17:15:04.916] Loading model from: D:\AI\ComfyUI_windows_portable\ComfyUI\models\mimicmotion\MimicMotionMergedUnet_1-0-fp16.safetensors
[2024-11-16 17:15:04.917] Loading UNET
[2024-11-16 17:15:07.541] Loading VAE
[2024-11-16 17:15:07.770] Loading IMAGE_ENCODER
[2024-11-16 17:15:09.362] Loading POSE_NET
[2024-11-16 17:15:20.747] num_frames:  17
[2024-11-16 17:15:22.295] start_step_index: 0, end_step_index: 30
[2024-11-16 17:15:56.650] 
[2024-11-16 17:15:56.650] Processing interrupted
[2024-11-16 17:15:56.651] Prompt executed in 52.21 seconds
[2024-11-16 17:16:02.635] got prompt
[2024-11-16 17:16:07.785] num_frames:  17
[2024-11-16 17:16:09.576] start_step_index: 0, end_step_index: 30
[2024-11-16 17:16:44.238] 
[2024-11-16 17:16:44.239] Processing interrupted
[2024-11-16 17:16:44.240] Prompt executed in 41.50 seconds
[2024-11-16 17:17:47.155] got prompt
[2024-11-16 17:17:47.340] 1
[2024-11-16 17:17:51.899] num_frames:  16
[2024-11-16 17:17:53.565] start_step_index: 0, end_step_index: 30
[2024-11-16 17:26:31.008] 
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [08:37<00:00, 17.27s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [08:37<00:00, 17.25s/it]
[2024-11-16 17:26:58.208] 17
[2024-11-16 17:27:09.450] num_frames:  16
[2024-11-16 17:27:13.226] start_step_index: 0, end_step_index: 30
[2024-11-16 17:35:50.345] 
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [08:37<00:00, 17.17s/it]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [08:37<00:00, 17.24s/it]
[2024-11-16 17:36:15.131] !!! Exception during processing !!! '141.0.0.3.0.0.91'
[2024-11-16 17:36:15.132] Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite\videohelpersuite\nodes.py", line 388, in combine_video
    kwargs = prompt[unique_id]['inputs']
             ~~~~~~^^^^^^^^^^^
KeyError: '141.0.0.3.0.0.91'
```

**Comment by logo66612** [comment]
[gzl.json](https://github.com/user-attachments/files/17784230/gzl.json)这是我的工作流

**Comment by logo66612** [comment]
> 请上传您的工作流程。

[gzl.json](https://github.com/user-attachments/files/17784232/gzl.json)
这是我的工作流

**Comment by logo66612** [comment]
> > 请上传您的工作流程。
> 
> [gzl.json](https://github.com/user-attachments/files/17784232/gzl.json) 这是我的工作流

该工作流之前一直正常,前几天更新comfyui就发生这样的情况了

**Comment by ltdrdata** [comment]
I was unable to reproduce the issue.
Is your ComfyUI latest version?

**Comment by logo66612** [comment]
> 我无法重现该问题。 您的 ComfyUI 是最新版本吗？

是的,插件和comfyui都在经常更新

**Comment by ltdrdata** [comment]
> 是的,插件和comfyui都在经常更新


Can it be reproduced in a more simplified workflow?

**Comment by logo66612** [comment]
> > 是的，插件和 comfyui 都经常在更新
> 
> 是否可以在更简化的工作流程中重现它？
我不懂编程,这会就是在测试改下工作流,依然还是在for结束哪里报错:KeyError: '137.0.0.3.0.0.91'

**Comment by logo66612** [comment]
> > 是的，插件和 comfyui 都经常在更新
> 
> 是否可以在更简化的工作流程中取消它？

我是想分批次采样,每次采样16帧图像.不然就就得每次手动叠加,太麻烦了
