### ISSUE TITLE
Can't import imageio to python_embedded

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#564]
I can't seem to install imageio to the python embed. It just won't install right. It shows in the pip package freeze, but isn't in the site-packages, and thus isn't importable. The installation process also succeeds without issue. I thought "Oh, for some reason I'm using my systems python" so I checked the executable, but no, it's installing using `C:\ComfyUI_windows_portable\python_embeded\python.exe -m`

**Comment by WASasquatch** [comment]
Hmm. Nope same issue. 

This is the exact output

```
WAS NS: Installing imageio...
  WARNING: The script f2py.exe is installed in 'C:\Users\jorda\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts imageio_download_bin.exe and imageio_remove_bin.exe are installed in 'C:\Users\jorda\AppData\Roaming\Python\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 23.0.1 -> 23.1.1
[notice] To update, run: C:\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
Python Env: C:\ComfyUI_windows_portable\python_embeded\python.exe
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 182, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 1981, in create_morph_gif
    self.morph_images(image_a, image_b, steps, max_size, output_file)
  File "C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\WAS_Node_Suite.py", line 1990, in morph_images
    import imageio
ModuleNotFoundError: No module named 'imageio'
```

Could it be that imageio itself is erroring out, and thus not importable? I noticed it f2py.exe isn't added to the PATHS variable naturally, wonder if that causes an error in imageio init.

**Comment by WASasquatch** [comment]
I tried adding the scripts path to the system paths programmatically, but it didn't have any effect. I wonder if that sort of change requires the script to be restarted.

**Comment by melMass** [comment]
@WASasquatch Uninstall system python. It's a mess in all OSes but particularly on windows.

found this issue while trying to see if comfy was using imageio or not by default 😋

**Comment by WASasquatch** [comment]
I think I manually copied stuff over just cause system python controls so many other projects.
