### ISSUE TITLE
Infinite Loading 

### ISSUE THREAD

**Issue by ShashwatDubey99** [comfyanonymous/ComfyUI#5644]
### Your question

ui not loading 

### Logs

```powershell
Error handling request
Traceback (most recent call last):
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/home/studio-lab-user/.conda/envs/default/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/ComfyUI/server.py", line 63, in cache_control
    response: web.Response = await handler(request)
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/ComfyUI/server.py", line 141, in origin_only_middleware
    response = await handler(request)
  File "/home/studio-lab-user/sagemaker-studiolab-notebooks/ComfyUI/app/user_manager.py", line 181, in listuserdata
    def process_full_path(full_path: str) -> FileInfo | str | list[str]:
TypeError: unsupported operand type(s) for |: '_TypedDictMeta' and 'type'
```

**Comment by huchenlei** [comment]
Make sure you have python 3.10+
