### ISSUE TITLE
MochiSampler  object of type 'float' has no len()

### ISSUE THREAD

**Issue by LucidFir** [comfyanonymous/ComfyUI#5646]
### Your question

MochiSampler

object of type 'float' has no len()

I am not a wizard, I do not speak this language :( ChatGPT has also failed me.

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node Type:** MochiSampler
- **Exception Type:** TypeError
- **Exception Message:** object of type 'float' has no len()
## Stack Trace

  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 579, in process
    latents = model.run(args)
              ^^^^^^^^^^^^^^^

  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 196, in run
    len(cfg_schedule) == sample_steps
    ^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** v0.2.7
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756696576
  - **VRAM Free:** 13069102912
  - **Torch VRAM Total:** 10972299264
  - **Torch VRAM Free:** 18526016

## Logs
```
2024-11-16 17:37:02,313 - root - INFO - Total VRAM 24564 MB, total RAM 65307 MB
2024-11-16 17:37:02,313 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-16 17:37:02,313 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-16 17:37:02,313 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-16 17:37:03,266 - root - INFO - Using pytorch cross attention
2024-11-16 17:37:05,683 - root - INFO - [Prompt Server] web root: F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\web
2024-11-16 17:37:06,188 - root - INFO - Total VRAM 24564 MB, total RAM 65307 MB
2024-11-16 17:37:06,188 - root - INFO - pytorch version: 2.5.1+cu124
2024-11-16 17:37:06,188 - root - INFO - Set vram state to: NORMAL_VRAM
2024-11-16 17:37:06,188 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-11-16 17:37:06,848 - root - INFO - 
Import times for custom nodes:
2024-11-16 17:37:06,848 - root - INFO -    0.0 seconds: F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-11-16 17:37:06,848 - root - INFO -    0.0 seconds: F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper
2024-11-16 17:37:06,848 - root - INFO -    0.1 seconds: F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-11-16 17:37:06,848 - root - INFO -    0.2 seconds: F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-11-16 17:37:06,848 - root - INFO -    0.3 seconds: F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-11-16 17:37:06,848 - root - INFO - 
2024-11-16 17:37:06,848 - root - INFO - Starting server

2024-11-16 17:37:06,848 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-11-16 17:37:14,921 - root - INFO - got prompt
2024-11-16 17:37:21,071 - root - INFO - Initializing model...
2024-11-16 17:37:21,115 - root - INFO - Loading model state_dict from F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\models\diffusion_models\mochi\mochi_preview_dit_GGUF_Q8_0.safetensors...
2024-11-16 17:37:21,115 - root - INFO - Loading GGUF model state_dict...
2024-11-16 17:37:29,910 - ComfyUI-MochiWrapper.mochi_preview.t2v_synth_mochi - INFO - Set dynamo cache size limit to 64
2024-11-16 17:37:31,330 - root - INFO - Using cfg schedule: 0.0
2024-11-16 17:37:31,374 - root - ERROR - !!! Exception during processing !!! object of type 'float' has no len()
2024-11-16 17:37:31,374 - root - ERROR - Traceback (most recent call last):
  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 579, in process
    latents = model.run(args)
              ^^^^^^^^^^^^^^^
  File "F:\AItools\ComfyUI_Mochi\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\mochi_preview\t2v_synth_mochi.py", line 196, in run
    len(cfg_schedule) == sample_steps
    ^^^^^^^^^^^^^^^^^
TypeError: object of type 'float' has no len()

2024-11-16 17:37:31,374 - root - INFO - Prompt executed in 16.44 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":14,"last_link_id":16,"nodes":[{"id":13,"type":"MochiTorchCompileSettings","pos":{"0":110,"1":90},"size":{"0":352.79998779296875,"1":202},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"torch_compile_args","type":"MOCHICOMPILEARGS","links":[16]}],"properties":{"Node name for S&R":"MochiTorchCompileSettings"},"widgets_values":["inductor",false,"default",true,true,false,64],"color":"#232","bgcolor":"#353"},{"id":1,"type":"MochiTextEncode","pos":{"0":510,"1":80},"size":{"0":413.45361328125,"1":268.5947265625},"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":1}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[7],"slot_index":0},{"name":"clip","type":"CLIP","links":null}],"properties":{"Node name for S&R":"MochiTextEncode"},"widgets_values":["Ice crystals form in the air as the cryomancer channels their power. The summer knight charges forward, their flaming sword leaving trails of fire in its wake. Steam explodes between them as fire and ice collide with earth-shaking force.",1,true],"color":"#232","bgcolor":"#353"},{"id":12,"type":"Note","pos":{"0":900,"1":-190},"size":{"0":365.5867919921875,"1":208.3488311767578},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[],"title":"Note: WIP!","properties":{},"widgets_values":["VAE decoding is extremely heavy so tiling is necessary, I have not found best settings for it yet so testing help is appreciated, you can keep decoding after sampling as the latents are still in memory to see what works.\n\nEither adjust frame_batch_size to decode less frames at once, this tends to cause frame skipping though.\n\nOr use higher batch and smaller tiles to still fit it in memory."],"color":"#432","bgcolor":"#653"},{"id":8,"type":"MochiTextEncode","pos":{"0":520,"1":410},"size":{"0":400,"1":200},"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":8}],"outputs":[{"name":"conditioning","type":"CONDITIONING","links":[9],"slot_index":0},{"name":"clip","type":"CLIP","links":null}],"properties":{"Node name for S&R":"MochiTextEncode"},"widgets_values":["",1,true],"color":"#322","bgcolor":"#533"},{"id":9,"type":"VHS_VideoCombine","pos":{"0":1310,"1":90},"size":[520,310],"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":15},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":24,"loop_count":0,"filename_prefix":"mochi-hq\\mochi","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":13,"save_metadata":true,"pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"mochi_00004.mp4","subfolder":"mochi-hq","type":"output","format":"video/h264-mp4","frame_rate":24},"muted":false}},"color":"#223","bgcolor":"#335"},{"id":2,"type":"CLIPLoader","pos":{"0":46,"1":574},"size":{"0":429.837646484375,"1":82},"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[1,8]}],"properties":{"Node name for S&R":"CLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","sd3"],"color":"#232","bgcolor":"#353"},{"id":4,"type":"DownloadAndLoadMochiModel","pos":{"0":25,"1":334},"size":{"0":437.7432556152344,"1":198},"flags":{},"order":3,"mode":0,"inputs":[{"name":"trigger","type":"CONDITIONING","link":null,"shape":7},{"name":"compile_args","type":"MOCHICOMPILEARGS","link":16,"shape":7}],"outputs":[{"name":"mochi_model","type":"MOCHIMODEL","links":[3],"slot_index":0},{"name":"mochi_vae","type":"MOCHIVAE","links":[11],"slot_index":1}],"properties":{"Node name for S&R":"DownloadAndLoadMochiModel"},"widgets_values":["mochi_preview_dit_GGUF_Q8_0.safetensors","mochi_preview_vae_decoder_bf16.safetensors","fp8_e4m3fn","sage_attn",false,"default"],"color":"#232","bgcolor":"#353"},{"id":11,"type":"GetImageSizeAndCount","pos":{"0":1041,"1":768},"size":{"0":222.00714111328125,"1":86},"flags":{},"order":8,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":14}],"outputs":[{"name":"image","type":"IMAGE","links":[15],"slot_index":0},{"name":"width","type":"INT","links":null},{"name":"height","type":"INT","links":null},{"name":"count","type":"INT","links":null}],"properties":{"Node name for S&R":"GetImageSizeAndCount"},"widgets_values":[],"color":"#233","bgcolor":"#355"},{"id":10,"type":"MochiDecode","pos":{"0":963,"1":479},"size":{"0":315,"1":246},"flags":{},"order":7,"mode":0,"inputs":[{"name":"vae","type":"MOCHIVAE","link":11},{"name":"samples","type":"LATENT","link":12}],"outputs":[{"name":"images","type":"IMAGE","links":[14],"slot_index":0}],"properties":{"Node name for S&R":"MochiDecode"},"widgets_values":[true,false,10,160,312,0.25,0.25,false],"color":"#323","bgcolor":"#535"},{"id":5,"type":"MochiSampler","pos":{"0":961,"1":83},"size":{"0":315,"1":326},"flags":{},"order":6,"mode":0,"inputs":[{"name":"model","type":"MOCHIMODEL","link":3},{"name":"positive","type":"CONDITIONING","link":7},{"name":"negative","type":"CONDITIONING","link":9},{"name":"opt_sigmas","type":"SIGMAS","link":null,"shape":7},{"name":"samples","type":"LATENT","link":null,"shape":7},{"name":"fastercache","type":"FASTERCACHEARGS","link":null,"shape":7}],"outputs":[{"name":"samples","type":"LATENT","links":[12],"slot_index":0}],"properties":{"Node name for S&R":"MochiSampler"},"widgets_values":[848,480,79,75,4.5,12728265323067,"randomize",0],"color":"#323","bgcolor":"#535"}],"links":[[1,2,0,1,0,"CLIP"],[3,4,0,5,0,"MOCHIMODEL"],[7,1,0,5,1,"CONDITIONING"],[8,2,0,8,0,"CLIP"],[9,8,0,5,2,"CONDITIONING"],[11,4,1,10,0,"MOCHIVAE"],[12,5,0,10,1,"LATENT"],[14,10,0,11,0,"IMAGE"],[15,11,0,9,0,"IMAGE"],[16,13,0,4,1,"MOCHICOMPILEARGS"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.7513148009015783,"offset":[214.19246227423824,296.5316060259409]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

I cannot think of anything additional? I just got everything (Triton, sage attention) installed to try this workflow so that Mochi would be faster...

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-MochiWrapper repo.
https://github.com/kijai/ComfyUI-MochiWrapper

**Comment by MeatMattress** [comment]
Is this patched? This still doesn't seem to be working @Itdrdata

**Comment by MarzzLee** [comment]
I ran into this problem, MochiSampler object of type 'float' has no len(). I found that after changing the Mochi Sampler in the work flow solved this. Im also a noob to this but the more you play the more you learn. Hope this helps .

**Comment by ltdrdata** [comment]
See this:
https://github.com/kijai/ComfyUI-MochiWrapper/issues/60
