### ISSUE TITLE
Freeze UI even after clean install and no custom nodes

### ISSUE THREAD

**Issue by sirolim** [comfyanonymous/ComfyUI#5662]
### Expected Behavior

ComfyUI should load normally. The nodes and splines should be displayed normally. Nodes should load nomally.

### Actual Behavior

![Screenshot 2024-11-17 203959](https://github.com/user-attachments/assets/8ff35b5c-918f-42b3-b30e-e35426d27673)

When I load the default workflow it looks like this.

When I drop in a workflow it also doesnt load the nodes and splines correctly.
I can't move or zoom within the UI.

### Steps to Reproduce

It neither works in Stability Matrix nor portable ComfyUI.
After a clean install of Stability Matrix I'm not able to install the ComfyUI package. It fails during the install.

It seems like there is some global python issue. So I reinstalled globally python 3.10.9.
The problem still remains. My second guess there is a problem to create venv.

### Debug Logs

```powershell
The Log from a clean installed ComfyUI_portable:

C:\Tools\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 24576 MB, total RAM 65424 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Tools\ComfyUI_windows_portable\ComfyUI\web
C:\Tools\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)

Import times for custom nodes:
   0.0 seconds: C:\Tools\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py

Starting server

To see the GUI go to: http://127.0.0.1:8188


When I attempt to install within Stability Matrix:

Unpacking resources
Unpacking resources
Download Complete
Requirement already satisfied: pip in c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages (24.3.1)
Requirement already satisfied: wheel in c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages (0.44.0)
Collecting wheel
  Using cached wheel-0.45.0-py3-none-any.whl.metadata (2.3 kB)
Using cached wheel-0.45.0-py3-none-any.whl (72 kB)
Installing collected packages: wheel
  Attempting uninstall: wheel
    Found existing installation: wheel 0.44.0
    Uninstalling wheel-0.44.0:
      Successfully uninstalled wheel-0.44.0
  Rolling back uninstall of wheel
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages\wheel-0.44.0.dist-info\
   from C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Lib\site-packages\~heel-0.44.0.dist-info
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages\wheel-0.44.0.virtualenv
   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-qf4ak7zh\wheel-0.44.0.virtualenv
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages\wheel\
   from C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Lib\site-packages\~heel
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel-3.10.exe
   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel-3.10.exe
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel.exe
   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel.exe
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel3.10.exe
   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel3.10.exe
  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel3.exe
   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel3.exe
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\commands\install.py", line 457, in run
    installed = install_given_reqs(
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\req\__init__.py", line 70, in install_given_reqs
    requirement.install(
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\req\req_install.py", line 867, in install
    install_wheel(
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 732, in install_wheel
    _install_wheel(
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 649, in _install_wheel
    generated_console_scripts = maker.make_multiple(scripts_to_generate)
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 446, in make_multiple
    filenames.extend(self.make(specification, options))
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 419, in make
    return super().make(specification, options)
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 435, in make
    self._make_script(entry, filenames, options=options)
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 340, in _make_script
    self._write_script(scriptnames, shebang, script, filenames, ext)
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 265, in _write_script
    launcher = self._get_launcher('t')
  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 414, in _get_launcher
    raise ValueError(msg)
ValueError: Unable to find resource t64.exe in package pip._vendor.distlib
Error: StabilityMatrix.Core.Exceptions.ProcessException: pip install failed with code 2: 'Requirement already satisfied: pip in c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages (24.3.1)\r\nRequirement already satisfied: wheel in c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages (0.44.0)\r\nCollecting wheel\r\n  Using cached wheel-0.45.0-py3-none-any.whl.metadata (2.3 kB)\r\nUsing cached wheel-0.45.0-py3-none-any.whl (72 kB)\r\nInstalling collected packages: wheel\r\n  Attempting uninstall: wheel\r\n    Found existing installation: wheel 0.44.0\r\n    Uninstalling wheel-0.44.0:\r\n      Successfully uninstalled wheel-0.44.0\r\n  Rolling back uninstall of wheel\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages\wheel-0.44.0.dist-info\\r\n   from C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Lib\site-packages\~heel-0.44.0.dist-info\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages\wheel-0.44.0.virtualenv\r\n   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-qf4ak7zh\wheel-0.44.0.virtualenv\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\lib\site-packages\wheel\\r\n   from C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\Lib\site-packages\~heel\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel-3.10.exe\r\n   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel-3.10.exe\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel.exe\r\n   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel.exe\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel3.10.exe\r\n   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel3.10.exe\r\n  Moving to c:\users\peter\downloads\stabilitymatrix-win-x64\data\packages\comfyui\venv\scripts\wheel3.exe\r\n   from C:\Users\peter\AppData\Local\Temp\pip-uninstall-u4z3m_4t\wheel3.exe\r\nERROR: Exception:\r\nTraceback (most recent call last):\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper\r\n    status = _inner_run()\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run\r\n    return self.run(options, args)\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\cli\req_command.py", line 67, in wrapper\r\n    return func(self, options, args)\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\commands\install.py", line 457, in run\r\n    installed = install_given_reqs(\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\req\__init__.py", line 70, in install_given_reqs\r\n    requirement.install(\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\req\req_install.py", line 867, in install\r\n    install_wheel(\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 732, in install_wheel\r\n    _install_wheel(\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 649, in _install_wheel\r\n    generated_console_scripts = maker.make_multiple(scripts_to_generate)\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 446, in make_multiple\r\n    filenames.extend(self.make(specification, options))\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_internal\operations\install\wheel.py", line 419, in make\r\n    return super().make(specification, options)\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 435, in make\r\n    self._make_script(entry, filenames, options=options)\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 340, in _make_script\r\n    self._write_script(scriptnames, shebang, script, filenames, ext)\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 265, in _write_script\r\n    launcher = self._get_launcher('t')\r\n  File "C:\Users\peter\Downloads\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\pip\_vendor\distlib\scripts.py", line 414, in _get_launcher\r\n    raise ValueError(msg)\r\nValueError: Unable to find resource t64.exe in package pip._vendor.distlib\r\n'
   at StabilityMatrix.Core.Python.PyVenvRunner.PipInstall(ProcessArgs args, Action`1 outputDataReceived)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.InstallPackage(String installLocation, InstalledPackage installedPackage, InstallPackageOptions options, IProgress`1 progress, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.InstallPackageStep.ExecuteAsync(IProgress`1 progress, CancellationToken cancellationToken)
   at StabilityMatrix.Core.Models.PackageModification.PackageModificationRunner.ExecuteSteps(IEnumerable`1 steps)
```

**Comment by ltdrdata** [comment]
Check if the issue persists by performing a clean install with the portable version.

**Comment by sirolim** [comment]
Hey thanks! Yes the issue persists. I already performed several clean installs.
