### ISSUE TITLE
ImportError: cannot import name 'Phi3Config' from 'transformers' 

### ISSUE THREAD

**Issue by hkapavarapu** [comfyanonymous/ComfyUI#5665]
### Your question

I am getting below error when I run first time. Releated to Phi3Config, anyone faced similar issue? Help is appreciated. Thank You.

Error importing OmniGen: cannot import name 'Phi3Config' from 'transformers' (C:\ComfyUI\python_embeded\Lib\site-packages\transformers\__init__.py)
!!! Exception during processing !!! Failed to import OmniGen. Please check if the code was downloaded correctly.
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\ailab_OmniGen.py", line 53, in __init__
    from OmniGen import OmniGenPipeline
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\OmniGen\__init__.py", line 1, in <module>
    from .model import OmniGen
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\OmniGen\model.py", line 14, in <module>
    from OmniGen.transformer import Phi3Config, Phi3Transformer
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\OmniGen\transformer.py", line 18, in <module>
    from transformers import Phi3Config, Phi3Model
ImportError: cannot import name 'Phi3Config' from 'transformers' (C:\ComfyUI\python_embeded\Lib\site-packages\transformers\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\execution.py", line 289, in execute
    obj = class_def()
          ^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-OmniGen\ailab_OmniGen.py", line 57, in __init__
    raise RuntimeError("Failed to import OmniGen. Please check if the code was downloaded correctly.")
RuntimeError: Failed to import OmniGen. Please check if the code was downloaded correctly.

**Comment by LukeG89** [comment]
This is not a ComfyUI error, you need to find a solution or open a bug report here: [ComfyUI-OmniGen](https://github.com/1038lab/ComfyUI-OmniGen)
