### ISSUE TITLE
JSON Import Error, Cant Load Nodes

### ISSUE THREAD

**Issue by theduodecim** [comfyanonymous/ComfyUI#5675]
### Expected Behavior

After import use the workflow as always

### Actual Behavior

When i load my Json File, stucks and there is no nodes in the screen and i cant move to any place to ConfyUi Version 18/11/2024
Chrome : 
caught TypeError: Cannot read private member #boundingRect from an object whose class did not declare it
    at Proxy.updateArea (litegraph.es.js:1583:25)
    at LGraphCanvas.computeVisibleNodes (litegraph.es.js:5606:13)
    at LGraphCanvas.computeVisibleNodes (domWidget.ts:258:44)
    at LGraphCanvas.draw (litegraph.es.js:5622:12)
    at ComfyApp.resizeCanvas (app.ts:1899:18)
    at ResizeObserver.<anonymous> (app.ts:1833:46)

Firefox
![image](https://github.com/user-attachments/assets/7fe7a317-3568-459b-986b-e4212d54d8de)

Thanks !

### Steps to Reproduce

Import a JSON FILE 

### Debug Logs

```powershell
When i load my Json File, stucks and there is no nodes in the screen and i cant move to any place to ConfyUi Version 18/11/2024
Chrome : 
caught TypeError: Cannot read private member #boundingRect from an object whose class did not declare it
    at Proxy.updateArea (litegraph.es.js:1583:25)
    at LGraphCanvas.computeVisibleNodes (litegraph.es.js:5606:13)
    at LGraphCanvas.computeVisibleNodes (domWidget.ts:258:44)
    at LGraphCanvas.draw (litegraph.es.js:5622:12)
    at ComfyApp.resizeCanvas (app.ts:1899:18)
    at ResizeObserver.<anonymous> (app.ts:1833:46)

Firefox
![image](https://github.com/user-attachments/assets/7fe7a317-3568-459b-986b-e4212d54d8de)


Thanks !
```

**Comment by theduodecim** [comment]
Fixed after clicking **Update All** on Manager 👍
