### ISSUE TITLE
unexpected EOF, expected 8925839 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by buy3601223** [comfyanonymous/ComfyUI#5679]
### Expected Behavior

![11](https://github.com/user-attachments/assets/5fe1ab68-67da-4d4b-a801-11f50bfe80a0)

### Actual Behavior

这个不知道啥问题，运行到这里卡住了，unexpected EOF, expected 8925839 more bytes. The file might be corrupted.

### Steps to Reproduce

这个不知道啥问题，运行到这里卡住了，unexpected EOF, expected 8925839 more bytes. The file might be corrupted.

### Debug Logs

```powershell
Prompt executed in 0.41 seconds
got prompt
!!! Exception during processing !!! unexpected EOF, expected 8925839 more bytes. The file might be corrupted.
Traceback (most recent call last):
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 165, in _map_node_over_list
    process_inputs({})
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\custom_nodes\CharacterFaceSwap\nodes.py", line 270, in load
    return (init_parsing_model("bisenet", model_rootpath=self.models_dir), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\facexlib\parsing\__init__.py", line 20, in init_parsing_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\torch\serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\torch\serialization.py", line 1357, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 8925839 more bytes. The file might be corrupted.

Prompt executed in 0.46 seconds
got prompt
!!! Exception during processing !!! unexpected EOF, expected 8925839 more bytes. The file might be corrupted.
Traceback (most recent call last):
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 165, in _map_node_over_list
    process_inputs({})
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\ComfyUI\custom_nodes\CharacterFaceSwap\nodes.py", line 270, in load
    return (init_parsing_model("bisenet", model_rootpath=self.models_dir), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\facexlib\parsing\__init__.py", line 20, in init_parsing_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\torch\serialization.py", line 1114, in load
    return _legacy_load(
           ^^^^^^^^^^^^^
  File "S:\dapao_ComfyUI(1)\dapao_ComfyUI\python_dapao\Lib\site-packages\torch\serialization.py", line 1357, in _legacy_load
    typed_storage._untyped_storage._set_from_file(
RuntimeError: unexpected EOF, expected 8925839 more bytes. The file might be corrupted.

Prompt executed in 0.43 seconds
```

**Comment by ltdrdata** [comment]
Please move this issue to CharacterFaceSwap repo.
https://github.com/ArtBot2023/CharacterFaceSwap

**Comment by buy3601223** [comment]
公司最初由4位国内首批电商网站建设卖家发掘市场需求，阖力创办，旨在解决互联网平台销售中遇到的运营难题。公司专注于互联网营销推广，主营业务涵盖店铺整体托管、网店装修、精准营销，视觉设计、客服外包、产品摄影、软件开发、培训咨询与微社群营销，网站建设推广，依托大数据优势，帮助企业快速建立全新的销售系统，助力企业转型提速，开启“互联网+”时代的新商业未来。
