### ISSUE TITLE
Mac M2 Ultra - Comfy crashes on startup after completing update via Manger 11/20/24

### ISSUE THREAD

**Issue by pphoto808** [comfyanonymous/ComfyUI#5689]
### Your question

MacOS
Mac Studio M2 Ultra

After executing Update All via Manger get the following error. Also did new install and got the same error. 

python main.py
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-20 10:07:20.489225
** Platform: Darwin
** Python version: 3.10.15 (main, Oct  3 2024, 02:24:49) [Clang 14.0.6 ]
** Python executable: /opt/miniconda3/envs/comfyenv/bin/python
** ComfyUI Path: /Volumes/Extreme_Pro/ComfyUI
** Log path: /Volumes/Extreme_Pro/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /Volumes/Extreme_Pro/ComfyUI/custom_nodes/rgthree-comfy
   0.0 seconds: /Volumes/Extreme_Pro/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   1.0 seconds: /Volumes/Extreme_Pro/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 65536 MB, total RAM 65536 MB
pytorch version: 2.5.1
Set vram state to: SHARED
Device: mps
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
/Volumes/Extreme_Pro/ComfyUI/comfy/k_diffusion/sampling.py:3: UserWarning: A NumPy version >=1.22.4 and <1.29.0 is required for this version of SciPy (detected version 2.1.3)
  from scipy import integrate
Traceback (most recent call last):
  File "/Volumes/Extreme_Pro/ComfyUI/main.py", line 91, in <module>
    import execution
  File "/Volumes/Extreme_Pro/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/Volumes/Extreme_Pro/ComfyUI/nodes.py", line 22, in <module>
    import comfy.samplers
  File "/Volumes/Extreme_Pro/ComfyUI/comfy/samplers.py", line 1, in <module>
    from .k_diffusion import sampling as k_diffusion_sampling
  File "/Volumes/Extreme_Pro/ComfyUI/comfy/k_diffusion/sampling.py", line 3, in <module>
    from scipy import integrate
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/opt/miniconda3/envs/comfyenv/lib/python3.10/site-packages/scipy/__init__.py", line 134, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/opt/miniconda3/envs/comfyenv/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/miniconda3/envs/comfyenv/lib/python3.10/site-packages/scipy/integrate/__init__.py", line 94, in <module>
    from ._quadrature import *
  File "/opt/miniconda3/envs/comfyenv/lib/python3.10/site-packages/scipy/integrate/_quadrature.py", line 9, in <module>
    from scipy.special import roots_legendre
  File "/opt/miniconda3/envs/comfyenv/lib/python3.10/site-packages/scipy/special/__init__.py", line 777, in <module>
    from . import _ufuncs
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

**Comment by pphoto808** [comment]
Fixed my issue.
I deactivate conda env and restarted Comfy without conda. Fixed several import failed and reinstalled custom nodes that could not be fixed. 
All good now.
