### ISSUE TITLE
meshgraphormer hand refiner it doesn't work for me

### ISSUE THREAD

**Issue by alehex93** [comfyanonymous/ComfyUI#5690]
### Expected Behavior

Trying several community workflows I find that node (meshgraphormer hand refiner) does not work for me, does anyone know what can happen?

### Actual Behavior

Trying several community workflows I find that node (meshgraphormer hand refiner) does not work for me, does anyone know what can happen?

### Steps to Reproduce

Whenever I use said I don't get the following error

MeshGraphormer-DepthMapPreprocessor
[Errno 2] No such file or directory: 'D:\\CreaciondeIA\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\hr16\\ControlNet-HandRefiner-pruned\\.cache\\huggingface\\download\\hrnetv2_w64_imagenet_pretrained.pth.41ed675bcd1f4f4b62a49bad64901f08f8b67ed744b715da87738f926dae685c.incomplete'

### Debug Logs

```powershell
got prompt
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 21.36it/s]
Failed to find D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\hr16/ControlNet-HandRefiner-pruned\hrnetv2_w64_imagenet_pretrained.pth.
 Downloading from huggingface.co
cacher folder is C:\Users\alehe\AppData\Local\Temp, you can change it by custom_tmp_path in config.yaml
!!! Exception during processing !!! [Errno 2] No such file or directory: 'D:\\CreaciondeIA\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\hr16\\ControlNet-HandRefiner-pruned\\.cache\\huggingface\\download\\hrnetv2_w64_imagenet_pretrained.pth.41ed675bcd1f4f4b62a49bad64901f08f8b67ed744b715da87738f926dae685c.incomplete'
Traceback (most recent call last):
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\mesh_graphormer.py", line 64, in execute
    from custom_controlnet_aux.mesh_graphormer import MeshGraphormerDetector
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\mesh_graphormer\__init__.py", line 5, in <module>
    from custom_controlnet_aux.mesh_graphormer.pipeline import MeshGraphormerMediapipe, args
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\mesh_graphormer\pipeline.py", line 54, in <module>
    hrnet_checkpoint=custom_hf_download("hr16/ControlNet-HandRefiner-pruned", 'hrnetv2_w64_imagenet_pretrained.pth')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\custom_controlnet_aux\util.py", line 333, in custom_hf_download
    model_path = hf_hub_download(repo_id=pretrained_model_or_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_validators.py", line 114, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 842, in hf_hub_download
    return _hf_hub_download_to_local_dir(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1138, in _hf_hub_download_to_local_dir
    _download_to_tmp_and_move(
  File "D:\CreaciondeIA\Stable Diffusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1533, in _download_to_tmp_and_move
    with incomplete_path.open("ab") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1044, in open
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\CreaciondeIA\\Stable Diffusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\ckpts\\hr16\\ControlNet-HandRefiner-pruned\\.cache\\huggingface\\download\\hrnetv2_w64_imagenet_pretrained.pth.41ed675bcd1f4f4b62a49bad64901f08f8b67ed744b715da87738f926dae685c.incomplete'

Prompt executed in 1.66 seconds
fatal: detected dubious ownership in repository at 'D:/CreaciondeIA/Stable Diffusion/ComfyUI_windows_portable/ComfyUI'
'D:/CreaciondeIA/Stable Diffusion/ComfyUI_windows_portable/ComfyUI' is owned by:
        (inconvertible) (S-1-5-21-2008586876-4074674188-2766500355-1001)
but the current user is:
        ALEJANDRO/alehe (S-1-5-21-1234336972-2110887372-85783964-1001)
To add an exception for this directory, call:

        git config --global --add safe.directory 'D:/CreaciondeIA/Stable Diffusion/ComfyUI_windows_portable/ComfyUI'
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```

**Comment by promd** [comment]
I can confirm, same issue for me.

**Comment by ltdrdata** [comment]
That is a typical Windows long path issue.

You need to edit registry settings or move installed directory to root.
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
