### ISSUE TITLE
Unable to run in CPU mode

### ISSUE THREAD

**Issue by teward** [comfyanonymous/ComfyUI#5702]
### Expected Behavior

When executing `python server.py --cpu`, I expect the system to NOT test for CUDA devices.

### Actual Behavior

The system checks for CUDA devices and hits an AssertionError of "Torch is not compiled with CUDA" despite specifying `--cpu`, suggesting that there is no way to disable CUDA.

### Steps to Reproduce

Install the pytorch CPU wheel first.

`pip install torch torchaudio torchvision --extra-index-url https://download.pytorch.org/whl/cpu`

Set up ComfyUI as normal.

Execute with `--cpu` arguments passed:   `python server.py --cpu`

Hard-error will be observed.

### Debug Logs

```powershell
> python ./server.py --cpu
Traceback (most recent call last):
  File "C:\Users\User\Desktop\SD\ComfyUI\server.py", line 6, in <module>
    import nodes
  File "C:\Users\User\Desktop\SD\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "C:\Users\User\Desktop\SD\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "C:\Users\User\Desktop\SD\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "C:\Users\User\Desktop\SD\ComfyUI\comfy\model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\SD\ComfyUI\comfy\model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\Desktop\SD\venv\Lib\site-packages\torch\cuda\__init__.py", line 940, in current_device
    _lazy_init()
  File "C:\Users\User\Desktop\SD\venv\Lib\site-packages\torch\cuda\__init__.py", line 310, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

**Comment by ltdrdata** [comment]
`python ./main.py --cpu` is the correct command.

**Comment by huongng105** [comment]
i am having the same error despite using the command python main.py --cpu , please help :(
