### ISSUE TITLE
invalid style model flux1-redux-dev.safetensors

### ISSUE THREAD

**Issue by currenttime** [comfyanonymous/ComfyUI#5718]
### Expected Behavior

None

### Actual Behavior

flux1-redux is invalid style model

### Steps to Reproduce

![微信图片_20241122150030](https://github.com/user-attachments/assets/8299baa5-cdc4-46ee-9846-b78b990a4d5d)

### Debug Logs

```powershell
2024-11-22T08:55:39.889556 - !!! Exception during processing !!! invalid style model /ai/brx/ComfyUI/models/style_models/flux1-redux-dev.safetensors
2024-11-22T08:55:39.890883 - Traceback (most recent call last):
  File "/ai/brx/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/ai/brx/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/ai/brx/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/ai/brx/ComfyUI/nodes.py", line 994, in load_style_model
    style_model = comfy.sd.load_style_model(style_model_path)
  File "/ai/brx/ComfyUI/comfy/sd.py", line 437, in load_style_model
    keys = model_data.keys()
Exception: invalid style model /ai/brx/ComfyUI/models/style_models/flux1-redux-dev.safetensors

2024-11-22T08:55:39.891680 - Prompt executed in 0.07 seconds
2024-11-22T08:55:40.606976 - No pending upload
```

**Comment by ltdrdata** [comment]
Make sure your ComfyUI is latest version.

**Comment by currenttime** [comment]
> Make sure your ComfyUI is latest version.

yes, i am sure.

**Comment by currenttime** [comment]
OS
posix
Python Version
3.10.14 (main, May 6 2024, 19:42:50) [GCC 11.2.0]
Embedded Python
false
Pytorch Version
2.5.1+cu121
Arguments
main.py --listen 0.0.0.0
RAM Total
31.34 GB
RAM Free
10.67 GB

Name
cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Type
cuda
VRAM Total
23.48 GB
VRAM Free
16.34 GB
Torch VRAM Total
6.75 GB
Torch VRAM Free
8.96 MB

**Comment by ltdrdata** [comment]
> 2fd9c13

In that case, you need to check whether the model file was downloaded correctly. The file may have been downloaded incorrectly or corrupted during the download process.

**Comment by yxzh614** [comment]
I also encountered the same problem, have you solved it?

**Comment by currenttime** [comment]
> I also encountered the same problem, have you solved it?

Yes!
1. Ensure to update to the latest version of Comfyui
2. Kill the process
3. Manually restart Comfyui completely

**Comment by subzero2323** [comment]
upgrade your update_comfyui_and_python_dependencies and then it will work

**Comment by aiworksnew1** [comment]
Which version you have upgraded to?

**Comment by aiworksnew1** [comment]
how to update in colab pro ,I tried to update it but its asking me to commit th e changes

**Comment by subzero2323** [comment]
> Which version you have upgraded to?

Here are my logs you can see, this version is perfect working everything 

**********************************************************************
** Visual Studio 2022 Developer PowerShell v17.12.2
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
PS D:\ComfyUI> .\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --fast
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-06 10:39:12.036787
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\ComfyUI\python_embeded\python.exe
** ComfyUI Path: D:\ComfyUI\ComfyUI
** Log path: D:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.8 seconds: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 16376 MB, total RAM 32535 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: D:\ComfyUI\ComfyUI\web
Web extensions folder found at D:\ComfyUI\ComfyUI\web\extensions\ComfyLiterals
[AnimateDiffEvo] - ERROR - No motion models found. Please download one and place in: ['D:\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'D:\\ComfyUI\\ComfyUI\\models\\animatediff_models']
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: Intel(R) Core(TM) i9-14900K - Arch: AMD64 - OS: Windows 11
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 4070 Ti SUPER
[Crystools INFO] NVIDIA Driver: 566.14
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Total VRAM 16376 MB, total RAM 32535 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti SUPER : cudaMallocAsync
### Loading: ComfyUI-Impact-Pack (V7.14)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.9)
### Loading: ComfyUI-Manager (V2.55)
### ComfyUI Version: v0.3.6-7-gc1b92b7 | Released on '2024-12-03'

**Comment by DoryAi** [comment]
I also have the error: 
ccurred when executing StyleModelLoader:
invalid style model H:\ComfyUI_windows_portable\ComfyUI\models\style_models\flux1-redux-dev.safetensors
File "H:\ComfyUI_windows_portable\ComfyUI\[execution.py](javascript:void(0);)", line 317, in execute
output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb). Why?
If upgrading to pytorch version: 2.5.1, many Nodes will be broken, first is Node ComfyUI-BiRefNet-ZHO and then ComfyUI-Impact-Pack, ComfyUI-Inspire-Pack, ComfyUI_LayerStyle, comfyui_controlnet_aux... I don't understand why there is a conflict?

**Comment by nikhilkofficial** [comment]
Same error. Has anyone found any solution to this?

**Comment by aiworksnew1** [comment]
Yes my  issue got clear when i updated comfyui to latest version.
I just backed up my files . Reinstalled to the latest verion available on the site [v0.3.7](https://github.com/comfyanonymous/ComfyUI/releases/tag/v0.3.7).

If you want help for updating ,just ask chatgpt . it will help.
