### ISSUE TITLE
update the latest version，got a error

### ISSUE THREAD

**Issue by Lecho303** [comfyanonymous/ComfyUI#5727]
### Expected Behavior

update the comfyui 

### Actual Behavior

i was download the latest zip to update Comfyui,then i was unzip the zip,cover the last version comfyui's folder,then click 'run _nvdia_gpu'got this error:
[ComfyUI-Manager] Logging failed: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'comfyui.log' -> 'comfyui.prev.log'
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 21:41:53.523551
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI
** Log path: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.1 seconds: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager-main
   1.6 seconds: D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 32461 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\main.py", line 91, in <module>
    import execution
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 18, in <module>
    from . import model_detection
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\model_detection.py", line 1, in <module>
    import comfy.supported_models
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\supported_models.py", line 5, in <module>
    from . import sd1_clip
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\comfy\sd1_clip.py", line 3, in <module>
    from transformers import CLIPTokenizer
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\__init__.py", line 26, in <module>
    from . import dependency_versions_check
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\dependency_versions_check.py", line 57, in <module>
    require_version_core(deps[pkg])
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\versions.py", line 117, in require_version_core
    return require_version(requirement, hint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\versions.py", line 111, in require_version
    _compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
  File "D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\versions.py", line 44, in _compare_versions
    raise ImportError(
ImportError: tokenizers>=0.20,<0.21 is required for a normal functioning of this module, but found tokenizers==0.19.1.
Try: `pip install transformers -U` or `pip install -e '.[dev]'` if you're working with git main

D:\Comfyui\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable>pause

then i try to click the update comfyui,still can not run

### Steps to Reproduce

non

### Debug Logs

```powershell
non
```

### Other

non

**Comment by huchenlei** [comment]
You have a custom node python dependency conflict. You can fix this following the hint in the trace:
> Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main

**Comment by Xceciiiiiiilll** [comment]
The suggested solution does not work.

**Comment by Xceciiiiiiilll** [comment]
use this to install missing packages
.\python_embeded\python.exe -m pip install
