### ISSUE TITLE
[Error] Keyerror: model.diffusion_model.input_blocks.1.1.proj_in.weight

### ISSUE THREAD

**Issue by ShadiestGoat** [comfyanonymous/ComfyUI#573]
When I try to generate an image [using this model](https://civitai.com/models/7241/mix-pro-v4?modelVersionId=34559), I get the following log:

```
got prompt
Global Step: 300167
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
Traceback (most recent call last):
  File "/home/shady/Downloads/AUR/ComfyUI/execution.py", line 195, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "/home/shady/Downloads/AUR/ComfyUI/execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "/home/shady/Downloads/AUR/ComfyUI/execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "/home/shady/Downloads/AUR/ComfyUI/execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "/home/shady/Downloads/AUR/ComfyUI/execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "/home/shady/Downloads/AUR/ComfyUI/nodes.py", line 221, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/home/shady/Downloads/AUR/ComfyUI/comfy/sd.py", line 956, in load_checkpoint_guess_config
    if len(sd['model.diffusion_model.input_blocks.1.1.proj_in.weight'].shape) == 2:
KeyError: 'model.diffusion_model.input_blocks.1.1.proj_in.weight
```

And it crashes

**Comment by comfyanonymous** [comment]
Are you sure this is with mixProV4_v4.safetensors because I tried it and it works. I also see a print in your log that only happens when a ckpt is loaded not a safetensors file.
