### ISSUE TITLE
Error on tiled VAE with LTX-Video

### ISSUE THREAD

**Issue by gtx155** [comfyanonymous/ComfyUI#5735]
### Expected Behavior

It should produce a video using the LTX-Video workflow

### Actual Behavior

Pop-up with error `The expanded size of the tensor (192) must match the existing size (768) at non-singleton dimension 4.  Target sizes: [1, 3, 104, 128, 192].  Tensor sizes: [3, 97, 512, 768]`

### Steps to Reproduce

Load the default LTX video model workflow and run it

### Debug Logs

```powershell
got prompt
Requested to load LTXV
Loading 1 new model
loaded partially 3645.675 7255.519775390625 0
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [06:10<00:00, 12.34s/it]
Requested to load VideoVAE
Loading 1 new model
loaded completely 0.0 1599.096866607666 True
Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.
!!! Exception during processing !!! The expanded size of the tensor (192) must match the existing size (768) at non-singleton dimension 4.  Target sizes: [1, 3, 104, 128, 192].  Tensor sizes: [3, 97, 512, 768]
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 361, in decode
    out = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 697, in decode
    return self.decoder(self.per_channel_statistics.un_normalize(x))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 344, in forward
    sample = checkpoint_fn(up_block)(sample, causal=self.causal)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 407, in forward
    hidden_states = resnet(hidden_states, causal=causal)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\ldm\lightricks\vae\causal_video_autoencoder.py", line 560, in forward
    hidden_states = self.non_linearity(hidden_states)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\modules\activation.py", line 432, in forward
    return F.silu(input, inplace=self.inplace)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\nn\functional.py", line 2380, in silu
    return torch._C._nn.silu(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^
torch.OutOfMemoryError: Allocation on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 284, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 373, in decode
    pixel_samples = self.decode_tiled_3d(samples_in)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 331, in decode_tiled_3d
    return self.process_output(comfy.utils.tiled_scale_multidim(samples, decode_fn, tile=(tile_t, tile_x, tile_y), overlap=overlap, upscale_amount=self.upscale_ratio, out_channels=self.output_channels, output_device=self.output_device))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 775, in tiled_scale_multidim
    output[b:b+1] = function(s).to(output_device)
    ~~~~~~^^^^^^^
RuntimeError: The expanded size of the tensor (192) must match the existing size (768) at non-singleton dimension 4.  Target sizes: [1, 3, 104, 128, 192].  Tensor sizes: [3, 97, 512, 768]

Prompt executed in 408.69 seconds
```

**Comment by sidtrey** [comment]
Still happens for me, updated to latest version.  
Trying to load ltx model.
2024-11-22 19:24:48 comfyui  |                     ^^^^^^^^^
2024-11-22 19:24:48 comfyui  |   File "/usr/local/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1160, in convert
2024-11-22 19:24:48 comfyui  |     return t.to(
2024-11-22 19:24:48 comfyui  |            ^^^^^
2024-11-22 19:24:48 comfyui  | torch.OutOfMemoryError: Allocation on device 
2024-11-22 19:24:48 comfyui  | 
2024-11-22 19:24:48 comfyui  | Got an OOM, unloading all loaded models
