### ISSUE TITLE
Wrong Python version in Comfyui Portable

### ISSUE THREAD

**Issue by reefor** [comfyanonymous/ComfyUI#5743]
### Expected Behavior

Comfyui Portable includes Python 3.12.7 in this folder (Comfyui\ComfyUI_windows_portable\python_embeded\python.exe)

When I boot it up it tells me that's an unsupported version and I need to downgrade to versions 3.9, 3.10 or 3.11.

### Actual Behavior

Not sure if this is causing any of the problems I'm experiencing or not. Not sure if I really need to downgrade or if some tag someplace needs to be updated. (hope that made sense, drawing on my experience with skyrim character creation)

### Steps to Reproduce

Download Comfyui Portable, unzip it, and run it.

### Debug Logs

```powershell
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-11-22 09:58:33.205758
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI
** Log path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6144 MB, total RAM 16271 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\web
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Adding C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Could not find efficiency nodes
[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
Loaded ControlNetPreprocessors nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.11.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
### Loading: ComfyUI-Impact-Pack (V7.11.4)
Loaded ImpactPack nodes from C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes\nodes.py", line 9, in <module>
    from diffusers import ConsistencyDecoderVAE
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 5, in <module>
    from .utils import (
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\__init__.py", line 38, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import HfFolder, cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py). Did you mean: 'hf_hub_download'?

Cannot import C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes module for custom nodes: cannot import name 'cached_download' from 'huggingface_hub' (C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\__init__.py)
### Loading: ComfyUI-Impact-Pack (V7.11.4)
[Impact Pack] Wildcards loading done.
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\albumentations\__init__.py:13: UserWarning: A new version of Albumentations is available: 1.4.21 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
  check_for_updates()
C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
Total VRAM 6144 MB, total RAM 16271 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce GTX 1060 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2851 [94323a26] | Released on '2024-11-22'
------------------------------------------
### N-Suite Revision: ae7cc848
Current version of packaging: 23.2
Version of cpuinfo: Not found
Current version of git: 3.1.43
Current version of moviepy: 1.0.3
Current version of cv2: 4.10.0
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Current version of skbuild: 0.18.1
Version of typing: Not found
Current version of diskcache: 5.6.3
Installing llama_cpp...
Python version: None
OS: Windows
OS bit: 64
Platform tag: cp312-cp312-win_amd64
Unsupported Python version. Please use Python 3.9, 3.10 or 3.11.
Current version of timm: 1.0.11
Traceback (most recent call last):
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\__init__.py", line 64, in <module>
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes\py\gptcpp_node.py", line 4, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'
[tinyterraNodes] Loaded

[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉


Import times for custom nodes:
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Img2PaintingAssistant
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-copilot
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LivePortraitKJ
   0.0 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds (IMPORT FAILED): C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GlifNodes
   0.1 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.5 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-propost
   0.7 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   1.4 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspyrenet-Rembg
   3.3 seconds: C:\Users\Paul\Desktop\Comfyui\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-N-Nodes
```

**Comment by ltdrdata** [comment]
duplicate:
https://github.com/comfyanonymous/ComfyUI/issues/5731

**Comment by reefor** [comment]
> duplicate: #5731

Not a duplicate. The other message was me trying to get help to fix it. This message is letting the devs know so they can fix it in the download.
