### ISSUE TITLE
'VAE' object has no attribute 'vae_dtype'

### ISSUE THREAD

**Issue by ShivamKR12** [comfyanonymous/ComfyUI#5760]
### Expected Behavior

an image should be created according to the prompt

### Actual Behavior

got this error.
![Screenshot 2024-11-24 222317](https://github.com/user-attachments/assets/98b56462-6f4a-40b9-921b-f933084ce05a)

### Steps to Reproduce

run this workflow, the first one inside of it : https://openart.ai/workflows/oliviosarikas/lesson-2---text-to-image-some-cool-tricks-comfy-academy/j9ZrbVS2QKetKdiLVqmw

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 27
- **Node Type:** VAEDecode
- **Exception Type:** AttributeError
- **Exception Message:** 'VAE' object has no attribute 'vae_dtype'
## Stack Trace

  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/ComfyUI/nodes.py", line 284, in decode
    images = vae.decode(samples["samples"])

  File "/content/ComfyUI/comfy/sd.py", line 353, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)

```
## System Information
- **ComfyUI Version:** v0.3.4-5-gb4526d3
- **Arguments:** main.py --dont-print-server
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15835660288
  - **VRAM Free:** 13698260788
  - **Torch VRAM Total:** 1979711488
  - **Torch VRAM Free:** 4841268

## Logs
```
2024-11-24T16:38:59.831400 - [START] Security scan2024-11-24T16:38:59.831421 - 
2024-11-24T16:39:01.186757 - [DONE] Security scan2024-11-24T16:39:01.187283 - 
2024-11-24T16:39:01.265032 - ## ComfyUI-Manager: installing dependencies done.2024-11-24T16:39:01.265092 - 
2024-11-24T16:39:01.265127 - ** ComfyUI startup time:2024-11-24T16:39:01.265155 -  2024-11-24T16:39:01.265185 - 2024-11-24 16:39:01.2651082024-11-24T16:39:01.265211 - 
2024-11-24T16:39:01.265240 - ** Platform:2024-11-24T16:39:01.265266 -  2024-11-24T16:39:01.265290 - Linux2024-11-24T16:39:01.265314 - 
2024-11-24T16:39:01.265339 - ** Python version:2024-11-24T16:39:01.265363 -  2024-11-24T16:39:01.265387 - 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]2024-11-24T16:39:01.265411 - 
2024-11-24T16:39:01.265435 - ** Python executable:2024-11-24T16:39:01.265459 -  2024-11-24T16:39:01.265482 - /usr/bin/python32024-11-24T16:39:01.265513 - 
2024-11-24T16:39:01.265538 - ** ComfyUI Path:2024-11-24T16:39:01.265561 -  2024-11-24T16:39:01.265584 - /content/ComfyUI2024-11-24T16:39:01.265608 - 
2024-11-24T16:39:01.265651 - ** Log path:2024-11-24T16:39:01.265675 -  2024-11-24T16:39:01.265700 - /content/ComfyUI/comfyui.log2024-11-24T16:39:01.265723 - 
2024-11-24T16:39:04.487035 - 
Prestartup times for custom nodes:2024-11-24T16:39:04.487112 - 
2024-11-24T16:39:04.487162 -    4.7 seconds:2024-11-24T16:39:04.487195 -  2024-11-24T16:39:04.487223 - /content/ComfyUI/custom_nodes/ComfyUI-Manager2024-11-24T16:39:04.487251 - 
2024-11-24T16:39:04.487282 - 
2024-11-24T16:39:07.887333 - Total VRAM 15102 MB, total RAM 12979 MB
2024-11-24T16:39:07.887520 - pytorch version: 2.5.1+cu121
2024-11-24T16:39:07.919071 - Set vram state to: NORMAL_VRAM
2024-11-24T16:39:07.919318 - Device: cuda:0 Tesla T4 : cudaMallocAsync
2024-11-24T16:39:08.838456 - Using pytorch cross attention
2024-11-24T16:39:09.871622 - [Prompt Server] web root: /content/ComfyUI/web
2024-11-24T16:39:10.334951 - ### Loading: ComfyUI-Manager (V2.52)2024-11-24T16:39:10.335014 - 
2024-11-24T16:39:10.402504 - ### ComfyUI Revision: 2859 [b4526d3f] | Released on '2024-11-24'2024-11-24T16:39:10.402560 - 
2024-11-24T16:39:10.440503 - [AnimateDiffEvo] - [0;31mERROR[0m - No motion models found. Please download one and place in: ['/content/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved/models', '/content/ComfyUI/models/animatediff_models']
2024-11-24T16:39:10.460381 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-24T16:39:10.460676 - 
2024-11-24T16:39:10.516612 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-24T16:39:10.516685 - 
2024-11-24T16:39:10.529871 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-24T16:39:10.529933 - 
2024-11-24T16:39:10.551759 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-24T16:39:10.551841 - 
2024-11-24T16:39:10.605701 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-24T16:39:10.605800 - 
2024-11-24T16:39:10.643761 - Adding2024-11-24T16:39:10.643841 -  2024-11-24T16:39:10.643880 - /content/ComfyUI/custom_nodes2024-11-24T16:39:10.643916 -  2024-11-24T16:39:10.643945 - to sys.path2024-11-24T16:39:10.643976 - 
2024-11-24T16:39:10.778683 - Could not find efficiency nodes2024-11-24T16:39:10.778739 - 
2024-11-24T16:39:10.779874 - Could not find ControlNetPreprocessors nodes2024-11-24T16:39:10.779922 - 
2024-11-24T16:39:10.780168 - Could not find AdvancedControlNet nodes2024-11-24T16:39:10.780211 - 
2024-11-24T16:39:10.780771 - Could not find AnimateDiff nodes2024-11-24T16:39:10.780843 - 
2024-11-24T16:39:10.781259 - Loaded IPAdapter nodes from2024-11-24T16:39:10.781304 -  2024-11-24T16:39:10.781338 - /content/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus2024-11-24T16:39:10.781367 - 
2024-11-24T16:39:10.784611 - Loaded VideoHelperSuite from2024-11-24T16:39:10.784660 -  2024-11-24T16:39:10.784700 - /content/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite2024-11-24T16:39:10.784735 - 
2024-11-24T16:39:10.785244 - Could not load ImpactPack nodes2024-11-24T16:39:10.785291 -  2024-11-24T16:39:10.785329 - Could not find ImpactPack nodes2024-11-24T16:39:10.785364 - 
2024-11-24T16:39:10.887756 - 
Import times for custom nodes:
2024-11-24T16:39:10.887932 -    0.0 seconds: /content/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-24T16:39:10.888015 -    0.0 seconds: /content/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-11-24T16:39:10.888088 -    0.0 seconds: /content/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
2024-11-24T16:39:10.888161 -    0.1 seconds: /content/ComfyUI/custom_nodes/ComfyUI-Manager
2024-11-24T16:39:10.888234 -    0.2 seconds: /content/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-11-24T16:39:10.888308 -    0.2 seconds: /content/ComfyUI/custom_nodes/comfyui-art-venture
2024-11-24T16:39:10.888370 - 
2024-11-24T16:39:10.894357 - Starting server

2024-11-24T16:39:10.894689 - To see the GUI go to: http://127.0.0.1:8188
2024-11-24T16:40:23.787062 - FETCH DATA from: /content/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-11-24T16:40:23.787119 - 2024-11-24T16:40:23.939592 -  [DONE]2024-11-24T16:40:23.939657 - 
2024-11-24T16:45:28.761635 - got prompt
2024-11-24T16:45:28.777388 - Failed to validate prompt for output 31:
2024-11-24T16:45:28.777525 - * CheckpointLoaderSimple 23:
2024-11-24T16:45:28.777602 -   - Value not in list: ckpt_name: 'dreamshaper_8.safetensors' not in ['mdjrny-v4.ckpt']
2024-11-24T16:45:28.777674 - * VAELoader 28:
2024-11-24T16:45:28.777740 -   - Value not in list: vae_name: 'vae-ft-mse-840000-ema-pruned.safetensors' not in ['anything-v3-fp16-pruned.safetensors']
2024-11-24T16:45:28.777838 - Output will be ignored
2024-11-24T16:45:28.777927 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-24T16:45:48.521636 - got prompt
2024-11-24T16:45:48.554659 - Failed to validate prompt for output 31:
2024-11-24T16:45:48.554793 - * CheckpointLoaderSimple 23:
2024-11-24T16:45:48.554987 -   - Value not in list: ckpt_name: 'dreamshaper_8.safetensors' not in ['mdjrny-v4.ckpt']
2024-11-24T16:45:48.555088 - Output will be ignored
2024-11-24T16:45:48.555176 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-24T16:46:00.836998 - got prompt
2024-11-24T16:46:01.020942 - WARNING: No VAE weights detected, VAE not initalized.
2024-11-24T16:46:10.572474 - model weight dtype torch.float16, manual cast: None
2024-11-24T16:46:10.634614 - model_type EPS
2024-11-24T16:46:11.084780 - Using pytorch attention in VAE
2024-11-24T16:46:11.088793 - Using pytorch attention in VAE
2024-11-24T16:46:11.337258 - loaded straight to GPU
2024-11-24T16:46:11.337460 - Requested to load BaseModel
2024-11-24T16:46:11.337544 - Loading 1 new model
2024-11-24T16:46:11.356094 - loaded completely 0.0 1639.406135559082 True
2024-11-24T16:46:11.387846 - Requested to load SD1ClipModel
2024-11-24T16:46:11.388201 - Loading 1 new model
2024-11-24T16:46:11.465119 - loaded completely 0.0 235.84423828125 True
2024-11-24T16:46:19.258843 - 
100% 25/25 [00:06<00:00,  4.30it/s]2024-11-24T16:46:19.259118 - 
100% 25/25 [00:06<00:00,  3.71it/s]2024-11-24T16:46:19.259164 - 
2024-11-24T16:46:19.289843 - !!! Exception during processing !!! 'VAE' object has no attribute 'vae_dtype'
2024-11-24T16:46:19.292137 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 284, in decode
    images = vae.decode(samples["samples"])
  File "/content/ComfyUI/comfy/sd.py", line 353, in decode
    memory_used = self.memory_used_decode(samples_in.shape, self.vae_dtype)
AttributeError: 'VAE' object has no attribute 'vae_dtype'

2024-11-24T16:46:19.292607 - Prompt executed in 18.43 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

i changed the default models to my own. i think its because i am using a .safetensors model instead of a .ckpt

**Comment by LukeG89** [comment]
You loaded a checkpoint with the `Load VAE` node.

![image](https://github.com/user-attachments/assets/b669b75f-251b-41c8-aa5e-db2b8ebd75f1)

**Comment by ShivamKR12** [comment]
thanks @ltdrdata
