### ISSUE TITLE
Flux fill model not loading properly

### ISSUE THREAD

**Issue by Fqlox** [comfyanonymous/ComfyUI#5769]
### Expected Behavior

I wanted to run a flux fill model inference using the fp8 quantized model.

### Actual Behavior

 And got the error : 

`Error(s) in loading state_dict for Flux:
	size mismatch for img_in.weight: copying a param with shape torch.Size([3072, 384]) from checkpoint, the shape in current model is torch.Size([3072, 64]).`

### Steps to Reproduce

I did tes two workflows using flux fill and tested two different model  (one from civitai : https://civitai.com/models/969431/flux-fill-fp8 and the other from HG_hub: https://huggingface.co/dim/black-forest-labs_FLUX.1-Fill-dev_flux1-fill-dev_fp8.safetensors), the error comes strickly from load diffusiuon model node. I also tried all the dtype available (default, fp8 etc..).

![First Workflow](https://github.com/user-attachments/assets/234fa386-4698-4ef5-918f-b79a47cc22a5)
![Second Workflow)](https://github.com/user-attachments/assets/33edffc2-cefd-44b2-bbc0-d8f903b86767)

### Debug Logs

```powershell
model_type FLUX
!!! Exception during processing !!! Error(s) in loading state_dict for Flux:
        size mismatch for img_in.weight: copying a param with shape torch.Size([3072, 384]) from checkpoint, the shape in current model is torch.Size([3072, 64]).
Traceback (most recent call last):
  File "path_to_comfyui\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_comfyui\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_comfyui\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "path_to_comfyui\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_comfyui\ComfyUI\nodes.py", line 891, in load_unet
    model_options["dtype"] = torch.float8_e5m2
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path_to_comfyui\ComfyUI\comfy\sd.py", line 756, in load_diffusion_model
  File "path_to_comfyui\ComfyUI\comfy\sd.py", line 747, in load_diffusion_model_state_dict
  File "path_to_comfyui\ComfyUI\comfy\model_base.py", line 224, in load_model_weights
    to_load = {}
           ^^^^^^
  File "path_to_comfyui\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 2153, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Flux:
        size mismatch for img_in.weight: copying a param with shape torch.Size([3072, 384]) from checkpoint, the shape in current model is torch.Size([3072, 64]).
```

**Comment by ltdrdata** [comment]
duplicate:
https://github.com/comfyanonymous/ComfyUI/issues/5710

**Comment by pancnd** [comment]
I got the same error
