### ISSUE TITLE
Missing Manager Menu

### ISSUE THREAD

**Issue by smartyno** [comfyanonymous/ComfyUI#5773]
### Expected Behavior

Expected to see a button in the top-right corner that loads Manager dialog with features like install missing nodes/models

### Actual Behavior

Not seeing that button, not able to locate Manager anywhere in the UI.

### Steps to Reproduce

I am running ComfyUI v0.3.4-6-g61196d8 on an external GPU (using Run Pod, comfy UI template for that. When I launch the HTTP service, i first see the default UI  with all the menus on the left side bar (including Manager). However, when I update Comfy to the latest version, I can not find Manager anywhere. I did the same steps yesterday and the Managet button was in the top right corner.
<img width="1115" alt="Screenshot 2024-11-25 at 9 40 31 PM" src="https://github.com/user-attachments/assets/dc90f23c-55ef-448f-9135-33c38273d7c5">

### Debug Logs

```powershell
** ComfyUI startup time: 2024-11-25 20:22:29.782558
** Platform: Linux
** Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
** Python executable: /venv/bin/python
** Log path: /workspace/ComfyUI/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager

Total VRAM 24111 MB, total RAM 64070 MB
pytorch version: 2.0.1+cu118
xformers version: 0.0.22
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: /workspace/ComfyUI/web
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/comfy_extras/nodes_upscale_model.py", line 3, in <module>
    from spandrel import ModelLoader, ImageModelDescriptor
ModuleNotFoundError: No module named 'spandrel'

Cannot import /workspace/ComfyUI/comfy_extras/nodes_upscale_model.py module for custom nodes: No module named 'spandrel'
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/comfy_extras/nodes_canny.py", line 1, in <module>
    from kornia.filters import canny
ModuleNotFoundError: No module named 'kornia'

Cannot import /workspace/ComfyUI/comfy_extras/nodes_canny.py module for custom nodes: No module named 'kornia'
Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 2027, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/comfy_extras/nodes_morphology.py", line 4, in <module>
    from kornia.morphology import dilation, erosion, opening, closing, gradient, top_hat, bottom_hat
ModuleNotFoundError: No module named 'kornia'

Cannot import /workspace/ComfyUI/comfy_extras/nodes_morphology.py module for custom nodes: No module named 'kornia'
### Loading: ComfyUI-Manager (V2.7.1)
### ComfyUI Revision: 2860 [61196d88] | Released on '2024-11-25'

Import times for custom nodes:
   0.0 seconds: /workspace/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_upscale_model.py
IMPORT FAILED: nodes_canny.py
IMPORT FAILED: nodes_morphology.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt

Starting server

To see the GUI go to: http://0.0.0.0:3000
To see the GUI go to: http://[::]:3000
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#32'", 'extra_info': {}}
got prompt
invalid prompt: {'type': 'invalid_prompt', 'message': 'Cannot execute because a node is missing the class_type property.', 'details': "Node ID '#32'", 'extra_info': {}}
```

**Comment by StereoTypePro** [comment]
same issue

**Comment by Farley-0528** [comment]
我是没装git 装一个就好了

**Comment by ltdrdata** [comment]
It seems that you didn't installed `requirements.txt` of ComfyUI properly.
This issue may occur if you update a very old version of ComfyUI simply by performing a git pull.

**Comment by stormageadon** [comment]
Same here, installing the manager again did not work for me either

**Comment by ltdrdata** [comment]
Please make sure that both ComfyUI and ComfyUI-Manager are correctly installed and updated to the latest version.

**Comment by stormageadon** [comment]
They are, I've uninstalled and reinstalled both 3 times along with updating the JS batch

**Comment by axlaim** [comment]
Just installed portable comfy and can't get the manager. Tried all fixes I could see, here and other places.

**Comment by ltdrdata** [comment]
@stormageadon @axlaim 
I don't understand what you mean by updating the JS batch.

For now, please provide your terminal log. Just saying that it doesn’t appear is not enough to determine the issue.

**Comment by axlaim** [comment]
Resolved the issue from a Reddit post.  I had to run the update comfy batch
files, and that fixed the problem.  I'm so used to updating from the
manager, that I never thought to update manually.

**Comment by Djunx** [comment]
I found this article
https://github.com/Comfy-Org/ComfyUI-Manager

Installation[method1] (General installation method: ComfyUI-Manager only)
To install ComfyUI-Manager in addition to an existing installation of ComfyUI, you can follow the following steps:

goto ComfyUI/custom_nodes dir in terminal(cmd)
git clone https://github.com/ltdrdata/ComfyUI-Manager comfyui-manager
Restart ComfyUI
