### ISSUE TITLE
line 6131, in multi_head_attention_forward     raise RuntimeError( RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

### ISSUE THREAD

**Issue by CodeZ1LLa** [comfyanonymous/ComfyUI#5795]
### Expected Behavior

I expected that the CRM Pose sampler would work

### Actual Behavior

When I run the workflow, it cuts the background, but when it is passed through the CRM Preprocessor for Poser the preview image looks odd (see screenshot), but it passes it. However, when it's the turn of the CRM Sampler, it throws the error described in the name of the topic. 

![Screenshot 2024-11-26 215236](https://github.com/user-attachments/assets/207c682d-5a79-436f-8182-3bac8b14082d)

### Steps to Reproduce

I just installed the ComfyUI, added the ComfyUI manager, updated everything, and installed missing nodes for Flowty CRM. 
After that, I downloaded the missing .pth models from https://huggingface.co/Zhengyi/CRM/tree/main and tried to run the workflow

### Debug Logs

```powershell
got prompt
C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torchvision\transforms\v2\_deprecated.py:42: UserWarning: The transform `ToTensor()` is deprecated and will be removed in a future release. Instead, please use `v2.Compose([v2.ToImage(), v2.ToDtype(torch.float32, scale=True)])`.Output is equivalent up to float precision.
  warnings.warn(
Loading pixel model
Loaded ViT-H-14 model config.
Loading pretrained ViT-H-14 weights (laion2b_s32b_b79k).
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\imagedream\ldm\interface.py:115: RuntimeWarning: divide by zero encountered in divide
  "sqrt_recip_alphas_cumprod", to_torch(np.sqrt(1.0 / alphas_cumprod))
C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\imagedream\ldm\interface.py:118: RuntimeWarning: divide by zero encountered in divide
  "sqrt_recipm1_alphas_cumprod", to_torch(np.sqrt(1.0 / alphas_cumprod - 1))
C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\__init__.py:78: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  stage1_model.load_state_dict(torch.load(stage1_model_config.resume, map_location="cpu"), strict=False)
!!! Exception during processing !!! The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\__init__.py", line 81, in sample
    self.initialized_poser = get_obj_from_str(stage1_sampler_config.target)(
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\libs\sample.py", line 32, in __init__
    uc = model.get_learned_conditioning([neg_texts]).to(device)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\imagedream\ldm\interface.py", line 183, in get_learned_conditioning
    return self.clip_model(prompts)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\imagedream\ldm\modules\encoders\modules.py", line 218, in forward
    z = self.encode_with_transformer(tokens.to(self.device))
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\imagedream\ldm\modules\encoders\modules.py", line 282, in encode_with_transformer
    x = self.text_transformer_forward(x, attn_mask=self.model.attn_mask)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\custom_nodes\ComfyUI-Flowty-CRM-master\crmlib\imagedream\ldm\modules\encoders\modules.py", line 297, in text_transformer_forward
    x = r(x, attn_mask=attn_mask)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\open_clip\transformer.py", line 263, in forward
    x = q_x + self.ls_1(self.attention(q_x=self.ln_1(q_x), k_x=k_x, v_x=v_x, attn_mask=attn_mask))
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\open_clip\transformer.py", line 250, in attention
    return self.attn(
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\modules\activation.py", line 1368, in forward
    attn_output, attn_output_weights = F.multi_head_attention_forward(
  File "C:\Users\Admin\AppData\Roaming\StabilityMatrix\Packages\ComfyUI\venv\lib\site-packages\torch\nn\functional.py", line 6131, in multi_head_attention_forward
    raise RuntimeError(
RuntimeError: The shape of the 2D attn_mask is torch.Size([77, 77]), but should be (1, 1).

Prompt executed in 13.76 seconds
```

**Comment by CodeZ1LLa** [comment]
I just want to add, that if the foreground ratio is set to 1, the preview image is even more distorted. I'm not sure if this is an expected behavior. The preview looks the best when set to 0.8

![image](https://github.com/user-attachments/assets/b8fb9c92-7b1f-40fe-b0f2-b7c5fcf791fc)

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Flowty-CRM repo.
https://github.com/flowtyone/ComfyUI-Flowty-CRM

Additionally, custom nodes should not be installed by downloading and extracting zip files. This method can cause essential files required for updates to be missing, making updates impossible.
