### ISSUE TITLE
CLIPVisionLoader Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by ShivamKR12** [comfyanonymous/ComfyUI#5797]
### Expected Behavior

image coverted to animation

### Actual Behavior

got the error " CLIPVisionLoader
Error while deserializing header: HeaderTooLarge "

### Steps to Reproduce

https://civitai.com/articles/4339/image-to-video-comfyui-workflow-using-animatediff-and-ip-adapter-ready-to-use , run this work flow with the same models as listed in it and you will get same error. use to download links in the description of the page to download the models.

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 38
- **Node Type:** CLIPVisionLoader
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: HeaderTooLarge
## Stack Trace

  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/ComfyUI/nodes.py", line 967, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)

  File "/content/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)

  File "/content/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)

  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:

```
## System Information
- **ComfyUI Version:** v0.3.5-3-g0d4e29f
- **Arguments:** main.py --dont-print-server
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 Tesla T4 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 15835660288
  - **VRAM Free:** 13704552244
  - **Torch VRAM Total:** 1979711488
  - **Torch VRAM Free:** 4841268

## Logs
```
2024-11-27T08:09:24.737809 - [START] Security scan2024-11-27T08:09:24.737827 - 
2024-11-27T08:09:27.801396 - [DONE] Security scan2024-11-27T08:09:27.801424 - 
2024-11-27T08:09:28.034857 - ## ComfyUI-Manager: installing dependencies done.2024-11-27T08:09:28.034944 - 
2024-11-27T08:09:28.034987 - ** ComfyUI startup time:2024-11-27T08:09:28.035020 -  2024-11-27T08:09:28.035055 - 2024-11-27 08:09:28.0349642024-11-27T08:09:28.035083 - 
2024-11-27T08:09:28.035118 - ** Platform:2024-11-27T08:09:28.035177 -  2024-11-27T08:09:28.035207 - Linux2024-11-27T08:09:28.035236 - 
2024-11-27T08:09:28.035264 - ** Python version:2024-11-27T08:09:28.035291 -  2024-11-27T08:09:28.035318 - 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]2024-11-27T08:09:28.035345 - 
2024-11-27T08:09:28.035373 - ** Python executable:2024-11-27T08:09:28.035399 -  2024-11-27T08:09:28.035424 - /usr/bin/python32024-11-27T08:09:28.035449 - 
2024-11-27T08:09:28.035478 - ** ComfyUI Path:2024-11-27T08:09:28.035505 -  2024-11-27T08:09:28.035532 - /content/ComfyUI2024-11-27T08:09:28.035568 - 
2024-11-27T08:09:28.035627 - ** Log path:2024-11-27T08:09:28.035657 -  2024-11-27T08:09:28.035687 - /content/ComfyUI/comfyui.log2024-11-27T08:09:28.035716 - 
2024-11-27T08:09:31.456683 - 
Prestartup times for custom nodes:2024-11-27T08:09:31.456743 - 
2024-11-27T08:09:31.456793 -    6.7 seconds:2024-11-27T08:09:31.456823 -  2024-11-27T08:09:31.456852 - /content/ComfyUI/custom_nodes/ComfyUI-Manager2024-11-27T08:09:31.456880 - 
2024-11-27T08:09:31.456909 - 
2024-11-27T08:09:33.161902 - Total VRAM 15102 MB, total RAM 12979 MB
2024-11-27T08:09:33.162068 - pytorch version: 2.5.1+cu121
2024-11-27T08:09:33.193091 - Set vram state to: NORMAL_VRAM
2024-11-27T08:09:33.193339 - Device: cuda:0 Tesla T4 : cudaMallocAsync
2024-11-27T08:09:34.116199 - Using pytorch cross attention
2024-11-27T08:09:35.182018 - [Prompt Server] web root: /content/ComfyUI/web
2024-11-27T08:09:36.318185 - ### Loading: ComfyUI-Manager (V2.52.1)2024-11-27T08:09:36.318266 - 
2024-11-27T08:09:36.363708 - ### ComfyUI Revision: 2866 [0d4e29f1] | Released on '2024-11-27'2024-11-27T08:09:36.363769 - 
2024-11-27T08:09:36.368599 - 
Import times for custom nodes:
2024-11-27T08:09:36.368901 -    0.0 seconds: /content/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-27T08:09:36.369483 -    0.1 seconds: /content/ComfyUI/custom_nodes/ComfyUI-Manager
2024-11-27T08:09:36.369757 -    0.1 seconds: /content/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-11-27T08:09:36.369884 -    0.1 seconds: /content/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
2024-11-27T08:09:36.370027 -    0.5 seconds: /content/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-11-27T08:09:36.370121 - 
2024-11-27T08:09:36.378738 - Starting server

2024-11-27T08:09:36.379519 - To see the GUI go to: http://127.0.0.1:8188
2024-11-27T08:09:36.422781 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-27T08:09:36.422826 - 
2024-11-27T08:09:36.423623 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-27T08:09:36.423663 - 
2024-11-27T08:09:36.445206 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-27T08:09:36.445249 - 
2024-11-27T08:09:36.472969 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-27T08:09:36.473014 - 
2024-11-27T08:09:36.497558 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-27T08:09:36.497602 - 
2024-11-27T08:10:45.421613 - FETCH DATA from: /content/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-11-27T08:10:45.421676 - 2024-11-27T08:10:45.426223 -  [DONE]2024-11-27T08:10:45.426270 - 
2024-11-27T08:13:12.866226 - got prompt
2024-11-27T08:13:12.916790 - Failed to validate prompt for output 47:
2024-11-27T08:13:12.916923 - * ADE_AnimateDiffLoaderWithContext 27:
2024-11-27T08:13:12.916999 -   - Value not in list: model_name: 'v3_sd15_mm.ckpt' not in ['models/v3_sd15_mm.ckpt']
2024-11-27T08:13:12.917072 - Output will be ignored
2024-11-27T08:13:12.929201 - Failed to validate prompt for output 48:
2024-11-27T08:13:12.929325 - Output will be ignored
2024-11-27T08:13:12.929423 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-27T08:13:21.288540 - got prompt
2024-11-27T08:13:22.763456 - WARNING: No VAE weights detected, VAE not initalized.
2024-11-27T08:13:32.535002 - model weight dtype torch.float16, manual cast: None
2024-11-27T08:13:32.589622 - model_type EPS
2024-11-27T08:13:33.047991 - Using pytorch attention in VAE
2024-11-27T08:13:33.052282 - Using pytorch attention in VAE
2024-11-27T08:13:33.456709 - loaded straight to GPU
2024-11-27T08:13:33.456897 - Requested to load BaseModel
2024-11-27T08:13:33.456971 - Loading 1 new model
2024-11-27T08:13:33.474498 - loaded completely 0.0 1639.406135559082 True
2024-11-27T08:13:33.486767 - Requested to load SD1ClipModel
2024-11-27T08:13:33.486951 - Loading 1 new model
2024-11-27T08:13:33.563753 - loaded completely 0.0 235.84423828125 True
2024-11-27T08:13:34.493939 - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-11-27T08:13:34.494968 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 967, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)
  File "/content/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
  File "/content/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-11-27T08:13:34.495467 - Prompt executed in 13.16 seconds
2024-11-27T08:13:51.224680 - got prompt
2024-11-27T08:13:51.273207 - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-11-27T08:13:51.273736 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 967, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)
  File "/content/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
  File "/content/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-11-27T08:13:51.274242 - Prompt executed in 0.01 seconds
2024-11-27T08:15:21.670628 - FETCH DATA from: /content/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-11-27T08:15:21.670725 - 2024-11-27T08:15:21.677410 -  [DONE]2024-11-27T08:15:21.677463 - 
2024-11-27T08:15:42.801303 - got prompt
2024-11-27T08:15:42.877008 - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-11-27T08:15:42.877611 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 967, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)
  File "/content/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
  File "/content/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-11-27T08:15:42.878169 - Prompt executed in 0.01 seconds
2024-11-27T08:18:28.037314 - got prompt
2024-11-27T08:18:28.131106 - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-11-27T08:18:28.131854 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 967, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)
  File "/content/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
  File "/content/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-11-27T08:18:28.132412 - Prompt executed in 0.01 seconds
2024-11-27T08:18:48.904970 - got prompt
2024-11-27T08:18:48.946985 - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-11-27T08:18:48.947561 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 967, in load_clip
    clip_vision = comfy.clip_vision.load(clip_path)
  File "/content/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
  File "/content/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
  File "/usr/local/lib/python3.10/dist-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-11-27T08:18:48.948006 - Prompt executed in 0.01 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":52,"last_link_id":71,"nodes":[{"id":2,"type":"VAELoader","pos":[307,886],"size":[335.0110168457031,75.70606231689453],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[10,58],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["anything-v3-fp16-pruned.safetensors"]},{"id":3,"type":"CLIPTextEncode","pos":[678,1086.1939697265625],"size":[377.7811279296875,124.52955627441406],"flags":{},"order":10,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":2}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4,56],"slot_index":0,"shape":3}],"title":"positive prompt","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["nude photo, ultrarealistic, medium shot of a fairy queen, wearing a totally transparent dress that appears to be made of flowing water, cascading around her body with lifelike glow, catching light and creating subtle, mesmerizing patterns. her long, silver-blonde hair is woven with delicate silver and crystal accents, falling gently over her sholders. the background hints at an enchanted forest with blured, glowing foliage that enhace the the mystical atmosphere, her body is visible under the dress, her boobs are so beutifull and we can see their shape"],"color":"#232","bgcolor":"#353"},{"id":4,"type":"CLIPSetLastLayer","pos":[326.698486328125,783.452880859375],"size":[315,58],"flags":{},"order":8,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":44}],"outputs":[{"name":"CLIP","type":"CLIP","links":[2,3],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPSetLastLayer"},"widgets_values":[-1]},{"id":5,"type":"PrimitiveNode","pos":[1172,1241],"size":[210,82],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"INT","type":"INT","links":[6,59],"slot_index":0,"widget":{"name":"seed"}}],"title":"Seed","properties":{"Run widget replace on values":false},"widgets_values":[502421963493648,"randomize"],"color":"#2a363b","bgcolor":"#3f5159"},{"id":6,"type":"CLIPTextEncode","pos":[678,1251],"size":[369.7266845703125,86.23151397705078],"flags":{},"order":11,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[5,57],"slot_index":0,"shape":3}],"title":"negative prompt","properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["blur, distortion"],"color":"#322","bgcolor":"#533"},{"id":7,"type":"KSampler","pos":[1151,431],"size":[315,446],"flags":{},"order":13,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":42},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":5},{"name":"latent_image","type":"LATENT","link":39},{"name":"seed","type":"INT","link":6,"widget":{"name":"seed"}}],"outputs":[{"name":"LATENT","type":"LATENT","links":[9,53],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[502421963493648,"fixed",20,8,"uni_pc_bh2","sgm_uniform",1]},{"id":9,"type":"EmptyLatentImage","pos":[1171,1088],"size":[210,106],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[39],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,16]},{"id":10,"type":"VAEDecode","pos":[1193,919],"size":[210,46],"flags":{},"order":14,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":9},{"name":"vae","type":"VAE","link":10}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[66],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":27,"type":"ADE_AnimateDiffLoaderWithContext","pos":[698.179443359375,738.3181762695312],"size":[417.5771789550781,230],"flags":{},"order":12,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":71},{"name":"context_options","type":"CONTEXT_OPTIONS","link":null,"shape":7},{"name":"motion_lora","type":"MOTION_LORA","link":null,"shape":7},{"name":"ad_settings","type":"AD_SETTINGS","link":null,"shape":7},{"name":"sample_settings","type":"SAMPLE_SETTINGS","link":null,"shape":7},{"name":"ad_keyframes","type":"AD_KEYFRAMES","link":null,"shape":7}],"outputs":[{"name":"MODEL","type":"MODEL","links":[42,55],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"ADE_AnimateDiffLoaderWithContext"},"widgets_values":["models/v3_sd15_mm.ckpt","autoselect",1.3,false],"color":"#432","bgcolor":"#653"},{"id":32,"type":"CheckpointLoaderSimple","pos":[305,639],"size":[351.59136962890625,98],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[69],"slot_index":0,"shape":3},{"name":"CLIP","type":"CLIP","links":[44],"slot_index":1,"shape":3},{"name":"VAE","type":"VAE","links":null,"shape":3}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["mdjrny-v4.ckpt"]},{"id":36,"type":"LoadImage","pos":[298.5809020996094,1083.4569091796875],"size":[363.8095397949219,608.3573608398438],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[70],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ComfyUI_00004_.png","image"]},{"id":37,"type":"IPAdapterModelLoader","pos":[298.01641845703125,427.7124938964844],"size":[382.5260009765625,58.0932502746582],"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"IPADAPTER","type":"IPADAPTER","links":[67],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"IPAdapterModelLoader"},"widgets_values":["ip-adapter-plus-face_sd15.safetensors"]},{"id":40,"type":"LatentUpscaleBy","pos":[1520,1086],"size":[266.9209289550781,91.26343536376953],"flags":{},"order":15,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":53,"slot_index":0}],"outputs":[{"name":"LATENT","type":"LATENT","links":[54],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"LatentUpscaleBy"},"widgets_values":["nearest-exact",1.5]},{"id":41,"type":"KSampler","pos":[1505,437.37017822265625],"size":[315,446],"flags":{},"order":17,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":55,"slot_index":0},{"name":"positive","type":"CONDITIONING","link":56,"slot_index":1},{"name":"negative","type":"CONDITIONING","link":57,"slot_index":2},{"name":"latent_image","type":"LATENT","link":54},{"name":"seed","type":"INT","link":59,"slot_index":4,"widget":{"name":"seed"}}],"outputs":[{"name":"LATENT","type":"LATENT","links":[61],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[502421963493648,"fixed",20,8,"uni_pc_bh2","sgm_uniform",0.65]},{"id":43,"type":"VAEDecode","pos":[1552,926.3701782226562],"size":[210,46],"flags":{},"order":18,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":61},{"name":"vae","type":"VAE","link":58,"slot_index":1}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[65],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":47,"type":"VHS_VideoCombine","pos":[2355.52490234375,432.8139953613281],"size":[470.3313903808594,310],"flags":{},"order":19,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":65},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"1003_1","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":20,"save_metadata":true,"pingpong":true,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"1003_1_00002.mp4","subfolder":"","type":"temp","format":"video/h264-mp4"}}}},{"id":48,"type":"VHS_VideoCombine","pos":[1857.3067626953125,430.9084167480469],"size":[470.3313903808594,310],"flags":{},"order":16,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":66},{"name":"audio","type":"AUDIO","link":null,"shape":7},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"shape":7},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":8,"loop_count":0,"filename_prefix":"1003_0","format":"video/h264-mp4","pix_fmt":"yuv420p","crf":20,"save_metadata":true,"pingpong":true,"save_output":false,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"1003_0_00003.mp4","subfolder":"","type":"temp","format":"video/h264-mp4"}}}},{"id":51,"type":"Note","pos":[681,1385],"size":[1124.65087890625,290.0921630859375],"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[],"properties":{"text":""},"widgets_values":["first : install missing nodes by going to manager then install missing nodes\nsecond: download models for the generator nodes depending on what you want to run ( SD1.5 or SDXL ) you'll need ( ip-adapter_sd15.safetensor in load adapter model, clip-vit-h-b79k in clip vision, sd1.5 model for the load checkpoint, sd 1.5 vae for load vae, and finally v3_sd15_mm.ckpt for animatediff loader ) \nthird: upload image in input, fill in positive and negative prompts, set empty latent to 512 by 512 for sd15, set upscale latent by 1.5 \nclick queue prompt. \n\nfor sdxl you'll need to download the models for sdxl in step (second above) and set empty latent to 1024 instead of 512. SDXL will need 12 GB to run. "],"color":"#432","bgcolor":"#653"},{"id":52,"type":"IPAdapterAdvanced","pos":[758,397],"size":[315,278],"flags":{},"order":9,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":69},{"name":"ipadapter","type":"IPADAPTER","link":67},{"name":"image","type":"IMAGE","link":70},{"name":"image_negative","type":"IMAGE","link":null,"shape":7},{"name":"attn_mask","type":"MASK","link":null,"shape":7},{"name":"clip_vision","type":"CLIP_VISION","link":68,"shape":7}],"outputs":[{"name":"MODEL","type":"MODEL","links":[71],"slot_index":0}],"properties":{"Node name for S&R":"IPAdapterAdvanced"},"widgets_values":[1,"linear","concat",0,1,"V only"]},{"id":38,"type":"CLIPVisionLoader","pos":[302.01641845703125,533.7124633789062],"size":[374.1557922363281,58],"flags":{},"order":7,"mode":0,"inputs":[],"outputs":[{"name":"CLIP_VISION","type":"CLIP_VISION","links":[68],"slot_index":0,"shape":3}],"properties":{"Node name for S&R":"CLIPVisionLoader"},"widgets_values":["CLIP-ViT-H-14-laion.safetensors"]}],"links":[[2,4,0,3,0,"CLIP"],[3,4,0,6,0,"CLIP"],[4,3,0,7,1,"CONDITIONING"],[5,6,0,7,2,"CONDITIONING"],[6,5,0,7,4,"INT"],[9,7,0,10,0,"LATENT"],[10,2,0,10,1,"VAE"],[39,9,0,7,3,"LATENT"],[42,27,0,7,0,"MODEL"],[44,32,1,4,0,"CLIP"],[53,7,0,40,0,"LATENT"],[54,40,0,41,3,"LATENT"],[55,27,0,41,0,"MODEL"],[56,3,0,41,1,"CONDITIONING"],[57,6,0,41,2,"CONDITIONING"],[58,2,0,43,1,"VAE"],[59,5,0,41,4,"INT"],[61,41,0,43,0,"LATENT"],[65,43,0,47,0,"IMAGE"],[66,10,0,48,0,"IMAGE"],[67,37,0,52,1,"IPADAPTER"],[68,38,0,52,5,"CLIP_VISION"],[69,32,0,52,0,"MODEL"],[70,36,0,52,2,"IMAGE"],[71,52,0,27,0,"MODEL"]],"groups":[{"id":1,"title":"Generator","bounding":[288,354,838,625],"color":"#8AA","font_size":24,"flags":{}},{"id":2,"title":"Initial Output","bounding":[1136,356,344,622],"color":"#8AA","font_size":24,"flags":{}},{"id":3,"title":"Latent Upscale","bounding":[1490,356,343,627],"color":"#8AA","font_size":24,"flags":{}},{"id":4,"title":"Input","bounding":[289,1009,1537,692],"color":"#3f789e","font_size":24,"flags":{}},{"id":5,"title":"Output","bounding":[1847,357,989,840],"color":"#8A8","font_size":24,"flags":{}}],"config":{},"extra":{"ds":{"scale":0.5644739300537771,"offset":[247.72877502441406,-129.59942626953125]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by LukeG89** [comment]
Have you downloaded the model from here? https://huggingface.co/h94/IP-Adapter/resolve/main/models/image_encoder/model.safetensors

The download link comes from [ComfyUI_IPAdapter_plus](https://github.com/cubiq/ComfyUI_IPAdapter_plus) repo.
Also, use this name for the Clip vision model if you want to use the Unified Loader: `CLIP-ViT-H-14-laion2B-s32B-b79K`

P.S. You loaded again a checkpoint in VAE loader, expect another error.

![image](https://github.com/user-attachments/assets/69322d26-a67b-42b1-ad54-a2deff78cc12)

**Comment by ShivamKR12** [comment]
ya , my bad. thanks
