### ISSUE TITLE
aiohttp Server Error - ValueError: Host cannot contain port number

### ISSUE THREAD

**Issue by Brandon-c-tech** [comfyanonymous/ComfyUI#5814]
### Expected Behavior

The ComfyUI server should start and handle requests normally at http://127.0.0.1:8188.

### Actual Behavior

The server starts but fails to handle requests with the following error:
```
ValueError: Host '127.0.0.1:8188' cannot contain ':' (at position 9)
Error handling request
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
[...]
  File "/opt/conda/lib/python3.10/site-packages/yarl/_url.py", line 1476, in _encode_host
    raise ValueError(
ValueError: Host '127.0.0.1:8188' cannot contain ':' (at position 9)
```

### Steps to Reproduce

1. Start ComfyUI with `python main.py`
2. Server starts and shows message "To see the GUI go to: http://127.0.0.1:8188"
3. Error appears in console when trying to handle requests

### Debug Logs

```powershell
(base) root@comfyui-test-brandon:~# pip show aiohttp yarl
Name: aiohttp
Version: 3.11.8
Summary: Async http client/server framework (asyncio)
[...]
Name: yarl
Version: 1.18.0
[...]

# Server startup log:
Total VRAM 14918 MB, total RAM 3679 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
[...]
Starting server
To see the GUI go to: http://127.0.0.1:8188
Error handling request
[... error traceback as shown above ...]
```

### Other

**Environment info:**
OS: Linux
Python version: 3.10
aiohttp version: 3.11.8 (upgraded from 3.9.5)
yarl version: 1.18.0 (upgraded from 1.17.2)
**Attempted solutions: (Successful)**
1. Upgraded aiohttp and yarl to latest versions
2. Issue persists after upgrades
**Possible solutions to consider:**
1. Update server code to properly handle host/port separation
2. Lock dependency versions to known working versions (aiohttp==3.9.5, yarl==1.8.1)
3. Add specific version requirements in requirements.txt

**Comment by ataniz** [comment]
not using conda solved the issue for me

**Comment by ltdrdata** [comment]
This is fixed.
