### ISSUE TITLE
Could not detect model type of: /home/Aipathongit/ComfyUI/models/checkpoints/FLUX/flux_dev.safetensors

### ISSUE THREAD

**Issue by Aipathon** [comfyanonymous/ComfyUI#5824]
### Your question

Tried to run The Flux Model(https://civitai.com/models/618692/flux) and got the Error described in the Title. For more informations see the log section.

### Logs

```powershell
## Error Details
- **Node ID:** 4
- **Node Type:** CheckpointLoaderSimple
- **Exception Type:** RuntimeError
- **Exception Message:** ERROR: Could not detect model type of: /home/Aipathon/git/ComfyUI/models/checkpoints/FLUX/flux_dev.safetensors
## Stack Trace

  File "/home/Aipathon/git/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/Aipathon/git/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/Aipathon/git/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/home/Aipathon/git/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/Aipathon/git/ComfyUI/nodes.py", line 552, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/home/Aipathon/git/ComfyUI/comfy/sd.py", line 641, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))

```
## System Information
- **ComfyUI Version:** v0.3.5-8-gbf2650a
- **Arguments:** main.py
- **OS:** posix
- **Python Version:** 3.12.7 (main, Oct  1 2024, 00:00:00) [GCC 14.2.1 20240912 (Red Hat 14.2.1-3)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+rocm6.2
## Devices

- **Name:** cuda:0 AMD Radeon RX 6700 XT : native
  - **Type:** cuda
  - **VRAM Total:** 12868124672
  - **VRAM Free:** 12832473088
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-28T15:10:58.120562 - Total VRAM 12272 MB, total RAM 32011 MB
2024-11-28T15:10:58.120619 - pytorch version: 2.5.1+rocm6.2
2024-11-28T15:10:58.120772 - Set vram state to: NORMAL_VRAM
2024-11-28T15:10:58.120852 - Device: cuda:0 AMD Radeon RX 6700 XT : native
2024-11-28T15:10:58.809932 - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-11-28T15:10:59.512067 - ****** User settings have been changed to be stored on the server instead of browser storage. ******2024-11-28T15:10:59.512077 - 
2024-11-28T15:10:59.512088 - ****** For multi-user setups add the --multi-user CLI argument to enable multiple user profiles. ******2024-11-28T15:10:59.512090 - 
2024-11-28T15:10:59.512177 - [Prompt Server] web root: /home/Aipathon/git/ComfyUI/web
2024-11-28T15:10:59.846288 - 
Import times for custom nodes:
2024-11-28T15:10:59.846340 -    0.0 seconds: /home/Aipathon/git/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-28T15:10:59.846362 - 
2024-11-28T15:10:59.849022 - Starting server

2024-11-28T15:10:59.849353 - To see the GUI go to: http://127.0.0.1:8188
2024-11-28T15:12:05.527041 - got prompt
2024-11-28T15:12:05.527422 - Failed to validate prompt for output 9:
2024-11-28T15:12:05.527457 - * CheckpointLoaderSimple 4:
2024-11-28T15:12:05.527480 -   - Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in []
2024-11-28T15:12:05.527503 - Output will be ignored
2024-11-28T15:12:05.527536 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-28T15:12:17.309855 - got prompt
2024-11-28T15:12:17.310196 - Failed to validate prompt for output 9:
2024-11-28T15:12:17.310228 - * CheckpointLoaderSimple 4:
2024-11-28T15:12:17.310248 -   - Value not in list: ckpt_name: 'v1-5-pruned-emaonly.ckpt' not in []
2024-11-28T15:12:17.310268 - Output will be ignored
2024-11-28T15:12:17.310299 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-28T15:24:51.426241 - got prompt
2024-11-28T15:24:51.426630 - Failed to validate prompt for output 9:
2024-11-28T15:24:51.426676 - * CheckpointLoaderSimple 4:
2024-11-28T15:24:51.426705 -   - Required input is missing: ckpt_name
2024-11-28T15:24:51.426733 - Output will be ignored
2024-11-28T15:24:51.426767 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-28T15:25:20.520191 - got prompt
2024-11-28T15:25:20.520539 - Failed to validate prompt for output 9:
2024-11-28T15:25:20.520571 - * CheckpointLoaderSimple 4:
2024-11-28T15:25:20.520593 -   - Required input is missing: ckpt_name
2024-11-28T15:25:20.520615 - Output will be ignored
2024-11-28T15:25:20.520656 - invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}
2024-11-28T16:14:47.020547 - got prompt
2024-11-28T16:14:47.362096 - !!! Exception during processing !!! ERROR: Could not detect model type of: /home/Aipathon/git/ComfyUI/models/checkpoints/FLUX/flux_dev.safetensors
2024-11-28T16:14:47.363336 - Traceback (most recent call last):
  File "/home/Aipathon/git/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/Aipathon/git/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/nodes.py", line 552, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/comfy/sd.py", line 641, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: /home/Aipathon/git/ComfyUI/models/checkpoints/FLUX/flux_dev.safetensors

2024-11-28T16:14:47.363860 - Prompt executed in 0.34 seconds
2024-11-28T16:15:31.047304 - got prompt
2024-11-28T16:15:31.091187 - !!! Exception during processing !!! ERROR: Could not detect model type of: /home/Aipathon/git/ComfyUI/models/checkpoints/FLUX/flux_dev.safetensors
2024-11-28T16:15:31.091653 - Traceback (most recent call last):
  File "/home/Aipathon/git/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/home/Aipathon/git/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/nodes.py", line 552, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/Aipathon/git/ComfyUI/comfy/sd.py", line 641, in load_checkpoint_guess_config
    raise RuntimeError("ERROR: Could not detect model type of: {}".format(ckpt_path))
RuntimeError: ERROR: Could not detect model type of: /home/Aipathon/git/ComfyUI/models/checkpoints/FLUX/flux_dev.safetensors

2024-11-28T16:15:31.092111 - Prompt executed in 0.04 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":9,"last_link_id":9,"nodes":[{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":4,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1},{"name":"positive","type":"CONDITIONING","link":4},{"name":"negative","type":"CONDITIONING","link":6},{"name":"latent_image","type":"LATENT","link":2}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[607539957654043,"randomize",20,8,"euler","normal",1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":5,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":6,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":2,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["A cucumber that is programming"]},{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{"collapsed":true},"order":3,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":[""]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"title":"StableDiffusion","properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["FLUX/flux_dev.safetensors"]}],"links":[[1,4,0,3,0,"MODEL"],[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[0,0]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
Steps to reproduce:
1: Install ComfyUI on Fedora with an RX 6700XT
2: Download the Model FLUX from CIVITAI
3: Insert the Modell into the models directory
4: Use a basic worklow
5: Select Model
6: Run Image Generation
7: See Error
```


### Other

_No response_

**Comment by LukeG89** [comment]
You have to move the model to the “diffusion_models” folder because that file is not a checkpoint. Then you have to use “Load Diffusion Model” to load it.

You also have to load separately the text encoders (clip l to T5xxl) and the VAE.

You can find the models you are missing here: https://comfyanonymous.github.io/ComfyUI_examples/flux/

![loaders](https://github.com/user-attachments/assets/2d028001-ef49-40ff-8585-5730179483e2)


This is the example workflow: 
[flux_dev_example.json](https://github.com/user-attachments/files/17948045/flux_dev_example.json)

**Comment by Aipathon** [comment]
Thanks. I got everything to work.
