### ISSUE TITLE
ComfyUI crashed: Unobserved Task Exception ConfigParserException: Multi-line values are explicitly disallowed by parser settings. Please consider changing them.. On the line no. #2.

### ISSUE THREAD

**Issue by andrej-ka** [comfyanonymous/ComfyUI#5830]
### Expected Behavior

I expect it to start :)

### Actual Behavior

Hello, I’m experiencing an issue with StabilityMatrix + ComfyUI.

After installing a couple of new nodes, when I restarted ComfyUI within StabilityMatrix, my computer crashed with a blue screen.

After rebooting the computer, ComfyUI stopped launching within StabilityMatrix, and I now see the following error message:

Unobserved Task Exception ConfigParserException:
Multi-line values are explicitly disallowed by parser settings. Please consider changing them.. On the line no. 2.

I would greatly appreciate any ideas on how to restore ComfyUI.

Thank you!

### Steps to Reproduce

ComfyUI just won't start

### Debug Logs

```powershell
2024-11-28 23:15:57.4873|ERROR|StabilityMatrix.Avalonia.Program|Unobserved Task Exception|Salaros.Configuration.ConfigParserException: Multi-line values are explicitly disallowed by parser settings. Please consider changing them.. On the line no. #2.
   at Salaros.Configuration.ConfigParser.AppendValueToKey(ConfigSection& currentSection, ConfigLine& currentLine, String lineRaw, Int32 lineNumber)
   at Salaros.Configuration.ConfigParser.Read(String configContent)
   at Salaros.Configuration.ConfigParser..ctor(String configFile, ConfigParserSettings settings)
   at StabilityMatrix.Core.Python.PyVenvRunner.SetPyvenvCfg(String pythonDirectory, Boolean force)
   at StabilityMatrix.Core.Python.PyVenvRunner.RunDetached(ProcessArgs args, Action`1 outputDataReceived, Action`1 onExit, Boolean unbuffered)
   at StabilityMatrix.Core.Models.Packages.ComfyUI.RunPackage(String installLocation, InstalledPackage installedPackage, RunPackageOptions options, Action`1 onConsoleOutput, CancellationToken cancellationToken)
   at StabilityMatrix.Avalonia.Services.RunningPackageService.StartPackage(InstalledPackage installedPackage, String command, CancellationToken cancellationToken)
```

**Comment by ltdrdata** [comment]
That issue should be addressed in StabilityMatrix.

**Comment by andrej-ka** [comment]
> That issue should be addressed in StabilityMatrix.

However StabilityMatrix is shell only, but the problem as I understand is with the ComfyUI configuration file 
Where is the ComfyUI configuration file located ? What is its name?

I just installed all this a week ago and am still learning :)

Thanks!

**Comment by andrej-ka** [comment]
I didn't specify my configuration -
i9-13900K, 64 GB memory, NVIDIA GeForce RTX 4070 Ti SUPER 16.0 GB
Windows 10
