### ISSUE TITLE
MathExpression|pysssss Name not found: HEX 

### ISSUE THREAD

**Issue by valan2121** [comfyanonymous/ComfyUI#5831]
### Expected Behavior

# ComfyUI Error Report
## Error Details
- **Node ID:** 11560:14
- **Node Type:** MathExpression|pysssss
- **Exception Type:** NameError
- **Exception Message:** Name not found: HEX
### Actual Behavior

hello how to fix this error ?

### Steps to Reproduce

# ComfyUI Error Report
## Error Details
- **Node ID:** 11560:14
- **Node Type:** MathExpression|pysssss
- **Exception Type:** NameError
- **Exception Message:** Name not found: HEX
## Stack Trace
``

### Debug Logs

```powershell
File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 241, in evaluate
    r = eval_expr(node)
        ^^^^^^^^^^^^^^^

  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 204, in eval_expr
    raise NameError(f"Name not found: {node.id}")


## System Information
- **ComfyUI Version:** v0.3.5-8-gbf2650a
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.5.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12878086144
  - **VRAM Free:** 11574181888
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-11-29T00:08:17.871200 - Output will be ignored
2024-11-29T00:08:17.871200 - Failed to validate prompt for output 11053:1:
2024-11-29T00:08:17.871200 - * (prompt):
2024-11-29T00:08:17.871200 -   - Required input is missing: dictionary
2024-11-29T00:08:17.871200 - * Dictionary to Console 11053:1:
2024-11-29T00:08:17.871200 -   - Required input is missing: dictionary
2024-11-29T00:08:17.871200 - Output will be ignored
2024-11-29T00:08:17.871200 - Failed to validate prompt for output 1950:
2024-11-29T00:08:17.871200 - Output will be ignored
2024-11-29T00:08:17.871200 - Failed to validate prompt for output 11051:19:
2024-11-29T00:08:17.872204 - * ImageClamp 11051:0:
2024-11-29T00:08:17.872204 -   - Required input is missing: image
2024-11-29T00:08:17.872204 - Output will be ignored
2024-11-29T00:08:17.872204 - Failed to validate prompt for output 6170:
2024-11-29T00:08:17.872204 - Output will be ignored
2024-11-29T00:08:17.872204 - Failed to validate prompt for output 11054:1:
2024-11-29T00:08:17.872204 - * (prompt):
2024-11-29T00:08:17.872204 -   - Required input is missing: dictionary
2024-11-29T00:08:17.872204 - Output will be ignored
2024-11-29T00:08:17.872204 - Failed to validate prompt for output 11050:19:
2024-11-29T00:08:17.872204 - * Dictionary to Console 11050:1:
2024-11-29T00:08:17.872204 -   - Required input is missing: dictionary
2024-11-29T00:08:17.872204 - * ImageClamp 11050:0:
2024-11-29T00:08:17.872204 -   - Required input is missing: image
2024-11-29T00:08:17.873195 - Output will be ignored
2024-11-29T00:08:17.873195 - Failed to validate prompt for output 11052:19:
2024-11-29T00:08:17.873195 - * Dictionary to Console 11052:1:
2024-11-29T00:08:17.873195 -   - Required input is missing: dictionary
2024-11-29T00:08:17.873195 - * ImageClamp 11052:0:
2024-11-29T00:08:17.873195 -   - Required input is missing: image
2024-11-29T00:08:17.873195 - Output will be ignored
2024-11-29T00:08:17.873195 - Failed to validate prompt for output 11052:1:
2024-11-29T00:08:17.873195 - * (prompt):
2024-11-29T00:08:17.873195 -   - Required input is missing: dictionary
2024-11-29T00:08:17.873195 - Output will be ignored
2024-11-29T00:08:17.874165 - Failed to validate prompt for output 10974:
2024-11-29T00:08:17.874165 - Output will be ignored
2024-11-29T00:08:17.874165 - Failed to validate prompt for output 10762:
2024-11-29T00:08:17.874165 - Output will be ignored
2024-11-29T00:08:17.874165 - Failed to validate prompt for output 11050:1:
2024-11-29T00:08:17.874165 - * (prompt):
2024-11-29T00:08:17.874165 -   - Required input is missing: dictionary
2024-11-29T00:08:17.874165 - Output will be ignored
2024-11-29T00:08:17.876187 - Failed to validate prompt for output 11053:19:
2024-11-29T00:08:17.876187 - Output will be ignored
2024-11-29T00:08:17.903087 - WARNING: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\input\\a0a2f1951c4461958dd17ad824660eb6.jpg'
2024-11-29T00:08:17.905111 - WARNING: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\input\\36a5316894d29f056aed5010cd10552f.jpg'
2024-11-29T00:08:17.906079 - WARNING: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\input\\Final_Pass_172822.png'
2024-11-29T00:08:17.907077 - WARNING: [Errno 2] No such file or directory: 'D:\\ComfyUI_windows_portable\\ComfyUI\\input\\clipspace/clipspace-mask-6132213.6.png'
2024-11-29T00:08:18.634772 - Using pytorch attention in VAE
2024-11-29T00:08:18.648875 - Using pytorch attention in VAE
2024-11-29T00:08:30.512517 - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-11-29T00:08:30.769581 - model_type FLUX
2024-11-29T00:08:49.912013 - got prompt
2024-11-29T00:08:49.933806 - Failed to validate prompt for output 11054:19:
2024-11-29T00:08:49.933806 - * ImpactInt 11560:10:
2024-11-29T00:08:49.933806 -   - Failed to convert an input value to a INT value: value, euler, invalid literal for int() with base 10: 'euler'
2024-11-29T00:08:49.934778 - * Scheduler Selector (Comfy) (Image Saver) 11560:21:
2024-11-29T00:08:49.934778 -   - Value not in list: scheduler: '1313' not in ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic']
2024-11-29T00:08:49.934778 - * Sampler Selector (Image Saver) 11560:19:
2024-11-29T00:08:49.935122 -   - Value not in list: sampler_name: 'True' not in (list of length 29)
2024-11-29T00:08:49.935122 - * ImpactFloat 11560:11:
2024-11-29T00:08:49.935122 -   - Failed to convert an input value to a FLOAT value: value, beta, could not convert string to float: 'beta'
2024-11-29T00:08:49.935122 - * BasicScheduler 11560:22:
2024-11-29T00:08:49.935122 -   - Failed to convert an input value to a FLOAT value: denoise, fixed, could not convert string to float: 'fixed'
2024-11-29T00:08:49.935122 - * LatentClamp 11560:4:
2024-11-29T00:08:49.935122 -   - Failed to convert an input value to a FLOAT value: inside_multiplier, (a+b)%2**50, could not convert string to float: '(a+b)%2**50'
2024-11-29T00:08:49.935122 -   - Value 13.0 bigger than max of 10.0: min
2024-11-29T00:08:49.935122 -   - Required input is missing: samples
2024-11-29T00:08:49.936121 -   - Failed to convert an input value to a FLOAT value: max, fixed, could not convert string to float: 'fixed'
2024-11-29T00:08:49.936121 -   - Value 30.0 bigger than max of 10.0: outside_multiplier
2024-11-29T00:08:49.936121 - * SplitSigmasDenoise 11560:37:
2024-11-29T00:08:49.936121 -   - Failed to convert an input value to a FLOAT value: denoise, scheduler, could not convert string to float: 'scheduler'
2024-11-29T00:08:49.936121 - * ImpactFloat 11560:29:
2024-11-29T00:08:49.936121 -   - Failed to convert an input value to a FLOAT value: value, seed, could not convert string to float: 'seed'
2024-11-29T00:08:49.936121 - * ImpactFloat 11560:30:
2024-11-29T00:08:49.936121 -   - Failed to convert an input value to a FLOAT value: value, steps, could not convert string to float: 'steps'
2024-11-29T00:08:49.936121 - * InjectLatentNoise+ 11560:28:
2024-11-29T00:08:49.936121 -   - Value not in list: normalize: '0.7' not in ['false', 'true']
2024-11-29T00:08:49.936121 -   - Failed to convert an input value to a FLOAT value: noise_strength, max(a,0), could not convert string to float: 'max(a,0)'
2024-11-29T00:08:49.936121 - * DetailerForEachDebug 11754:13:
2024-11-29T00:08:49.936121 -   - Return type mismatch between linked nodes: scheduler, ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic', 'AYS SDXL', 'AYS SD1', 'AYS SVD', 'GITS[coeff=1.2]'] != ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic', 'AYS SDXL', 'AYS SD1', 'AYS SVD', 'GITS[coeff=1.2]', 'LTXV[default]']
2024-11-29T00:08:49.936121 - Output will be ignored
2024-11-29T00:08:49.937119 - Failed to validate prompt for output 11051:1:
2024-11-29T00:08:49.937119 - Output will be ignored
2024-11-29T00:08:49.945096 - Failed to validate prompt for output 1565:
2024-11-29T00:08:49.945096 - Output will be ignored
2024-11-29T00:08:49.946094 - Failed to validate prompt for output 11560:31:
2024-11-29T00:08:49.946094 - Output will be ignored
2024-11-29T00:08:49.946094 - Failed to validate prompt for output 11560:32:
2024-11-29T00:08:49.946094 - Output will be ignored
2024-11-29T00:08:49.946094 - Failed to validate prompt for output 1563:
2024-11-29T00:08:49.946094 - Output will be ignored
2024-11-29T00:08:49.946094 - Failed to validate prompt for output 11053:1:
2024-11-29T00:08:49.946094 - Output will be ignored
2024-11-29T00:08:49.947091 - Failed to validate prompt for output 6007:
2024-11-29T00:08:49.947091 - Output will be ignored
2024-11-29T00:08:49.947091 - Failed to validate prompt for output 11560:14:
2024-11-29T00:08:49.947091 - Output will be ignored
2024-11-29T00:08:49.947091 - Failed to validate prompt for output 11051:19:
2024-11-29T00:08:49.947091 - Output will be ignored
2024-11-29T00:08:49.947091 - Failed to validate prompt for output 11054:1:
2024-11-29T00:08:49.948088 - Output will be ignored
2024-11-29T00:08:49.948088 - Failed to validate prompt for output 11668:30:
2024-11-29T00:08:49.948088 - Output will be ignored
2024-11-29T00:08:49.948088 - Failed to validate prompt for output 11050:19:
2024-11-29T00:08:49.948088 - Output will be ignored
2024-11-29T00:08:49.948088 - Failed to validate prompt for output 11052:19:
2024-11-29T00:08:49.948088 - Output will be ignored
2024-11-29T00:08:49.948088 - Failed to validate prompt for output 6308:
2024-11-29T00:08:49.948088 - Output will be ignored
2024-11-29T00:08:49.949086 - Failed to validate prompt for output 11052:1:
2024-11-29T00:08:49.949086 - Output will be ignored
2024-11-29T00:08:49.949086 - Failed to validate prompt for output 10974:
2024-11-29T00:08:49.949086 - Output will be ignored
2024-11-29T00:08:49.949086 - Failed to validate prompt for output 6008:
2024-11-29T00:08:49.949086 - Output will be ignored
2024-11-29T00:08:49.949086 - Failed to validate prompt for output 11050:1:
2024-11-29T00:08:49.949086 - Output will be ignored
2024-11-29T00:08:49.949086 - Failed to validate prompt for output 6950:
2024-11-29T00:08:49.949086 - Output will be ignored
2024-11-29T00:08:49.951080 - Failed to validate prompt for output 11053:19:
2024-11-29T00:08:49.952078 - * ImageClamp 11053:0:
2024-11-29T00:08:49.952078 -   - Required input is missing: image
2024-11-29T00:08:49.952078 - Output will be ignored
2024-11-29T00:08:49.952078 - Failed to validate prompt for output 11668:29:
2024-11-29T00:08:49.952078 - Output will be ignored
2024-11-29T00:08:49.952078 - Failed to validate prompt for output 13:
2024-11-29T00:08:49.952078 - Output will be ignored
2024-11-29T00:11:52.114152 - Processing interrupted
2024-11-29T00:11:52.115166 - Prompt executed in 214.21 seconds
2024-11-29T00:11:53.308990 - !!! Exception during processing !!! Name not found: HEX
2024-11-29T00:11:53.406270 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 241, in evaluate
    r = eval_expr(node)
        ^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 204, in eval_expr
    raise NameError(f"Name not found: {node.id}")
NameError: Name not found: HEX

2024-11-29T00:11:53.409289 - Prompt executed in 1.05 seconds
2024-11-29T00:17:55.542757 - got prompt
2024-11-29T00:17:55.609669 - Failed to validate prompt for output 11054:19:
2024-11-29T00:17:55.609669 - * Dictionary to Console 11054:1:
2024-11-29T00:17:55.609669 -   - Required input is missing: dictionary
2024-11-29T00:17:55.609669 - * ImageClamp 11668:4:
2024-11-29T00:17:55.609669 -   - Required input is missing: image
2024-11-29T00:17:55.610639 - * DetailerForEachDebug 11754:13:
2024-11-29T00:17:55.610639 -   - Return type mismatch between linked nodes: scheduler, ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic', 'AYS SDXL', 'AYS SD1', 'AYS SVD', 'GITS[coeff=1.2]'] != ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic', 'AYS SDXL', 'AYS SD1', 'AYS SVD', 'GITS[coeff=1.2]', 'LTXV[default]']
2024-11-29T00:17:55.610639 - Output will be ignored
2024-11-29T00:17:55.610639 - Failed to validate prompt for output 11051:1:
2024-11-29T00:17:55.610639 - * (prompt):
2024-11-29T00:17:55.610639 -   - Required input is missing: dictionary
2024-11-29T00:17:55.610639 - * Dictionary to Console 11051:1:
2024-11-29T00:17:55.610639 -   - Required input is missing: dictionary
2024-11-29T00:17:55.611636 - Output will be ignored
2024-11-29T00:17:55.615625 - Failed to validate prompt for output 1565:
2024-11-29T00:17:55.615625 - * ImageClamp 6559:0:
2024-11-29T00:17:55.615625 -   - Required input is missing: image
2024-11-29T00:17:55.615625 - Output will be ignored
2024-11-29T00:17:55.615625 - Failed to validate prompt for output 11053:1:
2024-11-29T00:17:55.616623 - * (prompt):
2024-11-29T00:17:55.616623 -   - Required input is missing: dictionary
2024-11-29T00:17:55.616623 - * Dictionary to Console 11053:1:
2024-11-29T00:17:55.616623 -   - Required input is missing: dictionary
2024-11-29T00:17:55.616623 - Output will be ignored
2024-11-29T00:17:55.616623 - Failed to validate prompt for output 1563:
2024-11-29T00:17:55.616623 - Output will be ignored
2024-11-29T00:17:55.616623 - Failed to validate prompt for output 6007:
2024-11-29T00:17:55.617620 - Output will be ignored
2024-11-29T00:17:55.617620 - Failed to validate prompt for output 11051:19:
2024-11-29T00:17:55.617620 - Output will be ignored
2024-11-29T00:17:55.617620 - Failed to validate prompt for output 11054:1:
2024-11-29T00:17:55.617620 - * (prompt):
2024-11-29T00:17:55.617620 -   - Required input is missing: dictionary
2024-11-29T00:17:55.617620 - Output will be ignored
2024-11-29T00:17:55.617620 - Failed to validate prompt for output 11668:30:
2024-11-29T00:17:55.617620 - Output will be ignored
2024-11-29T00:17:55.618618 - Failed to validate prompt for output 11050:19:
2024-11-29T00:17:55.618618 - * Dictionary to Console 11050:1:
2024-11-29T00:17:55.618618 -   - Required input is missing: dictionary
2024-11-29T00:17:55.618618 - * ImageClamp 11050:0:
2024-11-29T00:17:55.618618 -   - Required input is missing: image
2024-11-29T00:17:55.618618 - Output will be ignored
2024-11-29T00:17:55.618618 - Failed to validate prompt for output 11052:19:
2024-11-29T00:17:55.618618 - * Dictionary to Console 11052:1:
2024-11-29T00:17:55.618618 -   - Required input is missing: dictionary
2024-11-29T00:17:55.618618 - Output will be ignored
2024-11-29T00:17:55.619615 - Failed to validate prompt for output 11052:1:
2024-11-29T00:17:55.619615 - * (prompt):
2024-11-29T00:17:55.619615 -   - Required input is missing: dictionary
2024-11-29T00:17:55.619615 - Output will be ignored
2024-11-29T00:17:55.619615 - Failed to validate prompt for output 10974:
2024-11-29T00:17:55.619615 - Output will be ignored
2024-11-29T00:17:55.619615 - Failed to validate prompt for output 6008:
2024-11-29T00:17:55.619615 - Output will be ignored
2024-11-29T00:17:55.619615 - Failed to validate prompt for output 11050:1:
2024-11-29T00:17:55.619615 - * (prompt):
2024-11-29T00:17:55.619615 -   - Required input is missing: dictionary
2024-11-29T00:17:55.619615 - Output will be ignored
2024-11-29T00:17:55.619615 - Failed to validate prompt for output 6950:
2024-11-29T00:17:55.619615 - Output will be ignored
2024-11-29T00:17:55.621610 - Failed to validate prompt for output 11053:19:
2024-11-29T00:17:55.622608 - * ImageClamp 11053:0:
2024-11-29T00:17:55.622608 -   - Required input is missing: image
2024-11-29T00:17:55.622608 - Output will be ignored
2024-11-29T00:17:55.622608 - Failed to validate prompt for output 11668:29:
2024-11-29T00:17:55.622608 - Output will be ignored
2024-11-29T00:17:56.006557 - =============================================================2024-11-29T00:17:56.006557 - 
2024-11-29T00:17:56.006557 - Portrait Master positive prompt:2024-11-29T00:17:56.006557 - 
2024-11-29T00:17:56.006557 - raw photo, (realistic:1.5), (woman 24-years-old:1.5), (fit, fit body:1.95), (brown eyes:1.05), (black hair:1.05), (long:1.05), (disheveled:1.95), (professional photo, balanced photo, balanced exposure:1.2)2024-11-29T00:17:56.006557 - 
2024-11-29T00:17:56.006557 - 2024-11-29T00:17:56.006557 - 
2024-11-29T00:17:56.006557 - Portrait Master negative prompt:2024-11-29T00:17:56.006557 - 
2024-11-29T00:17:56.006557 - , (shinny skin, shiny skin, reflections on the skin, skin reflections:1.35)2024-11-29T00:17:56.006557 - 
2024-11-29T00:17:56.006557 - =============================================================2024-11-29T00:17:56.006557 - 
2024-11-29T00:19:01.565126 - Requested to load FluxClipModel_
2024-11-29T00:19:01.565126 - Loading 1 new model
2024-11-29T00:19:01.588065 - loaded completely 0.0 4778.66552734375 True
2024-11-29T00:21:14.060767 - !!! Exception during processing !!! '<' not supported between instances of 'Tensor' and 'str'
2024-11-29T00:21:14.145105 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LatentClamp\__init__.py", line 56, in op
    mask_min = s1 < min
               ^^^^^^^^
TypeError: '<' not supported between instances of 'Tensor' and 'str'

2024-11-29T00:21:14.151322 - Prompt executed in 198.50 seconds
2024-11-29T00:23:24.007840 - got prompt
2024-11-29T00:23:24.028784 - Failed to validate prompt for output 11054:19:
2024-11-29T00:23:24.028784 - * ImpactInt 11560:10:
2024-11-29T00:23:24.028784 -   - Failed to convert an input value to a INT value: value, euler, invalid literal for int() with base 10: 'euler'
2024-11-29T00:23:24.028784 - * Scheduler Selector (Comfy) (Image Saver) 11560:21:
2024-11-29T00:23:24.029781 -   - Value not in list: scheduler: '1313' not in ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic']
2024-11-29T00:23:24.029781 - * Sampler Selector (Image Saver) 11560:19:
2024-11-29T00:23:24.029781 -   - Value not in list: sampler_name: 'True' not in (list of length 29)
2024-11-29T00:23:24.029781 - * ImpactFloat 11560:11:
2024-11-29T00:23:24.029781 -   - Failed to convert an input value to a FLOAT value: value, beta, could not convert string to float: 'beta'
2024-11-29T00:23:24.029781 - * BasicScheduler 11560:22:
2024-11-29T00:23:24.029781 -   - Failed to convert an input value to a FLOAT value: denoise, fixed, could not convert string to float: 'fixed'
2024-11-29T00:23:24.029781 - * LatentClamp 11560:4:
2024-11-29T00:23:24.029781 -   - Failed to convert an input value to a FLOAT value: inside_multiplier, None, float() argument must be a string or a real number, not 'NoneType'
2024-11-29T00:23:24.030779 -   - Value 13.0 bigger than max of 10.0: min
2024-11-29T00:23:24.030779 -   - Required input is missing: samples
2024-11-29T00:23:24.030779 -   - Failed to convert an input value to a FLOAT value: max, None, float() argument must be a string or a real number, not 'NoneType'
2024-11-29T00:23:24.030779 -   - Value 30.0 bigger than max of 10.0: outside_multiplier
2024-11-29T00:23:24.030779 - * SplitSigmasDenoise 11560:37:
2024-11-29T00:23:24.030779 -   - Failed to convert an input value to a FLOAT value: denoise, scheduler, could not convert string to float: 'scheduler'
2024-11-29T00:23:24.030779 - * ImpactFloat 11560:29:
2024-11-29T00:23:24.030779 -   - Failed to convert an input value to a FLOAT value: value, seed, could not convert string to float: 'seed'
2024-11-29T00:23:24.030779 - * ImpactFloat 11560:30:
2024-11-29T00:23:24.030779 -   - Failed to convert an input value to a FLOAT value: value, steps, could not convert string to float: 'steps'
2024-11-29T00:23:24.030779 - * InjectLatentNoise+ 11560:28:
2024-11-29T00:23:24.030779 -   - Value not in list: normalize: '0.7' not in ['false', 'true']
2024-11-29T00:23:24.030779 -   - Failed to convert an input value to a FLOAT value: noise_strength, max(a,0), could not convert string to float: 'max(a,0)'
2024-11-29T00:23:24.030779 - * DetailerForEachDebug 11754:13:
2024-11-29T00:23:24.030779 -   - Return type mismatch between linked nodes: scheduler, ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic', 'AYS SDXL', 'AYS SD1', 'AYS SVD', 'GITS[coeff=1.2]'] != ['normal', 'karras', 'exponential', 'sgm_uniform', 'simple', 'ddim_uniform', 'beta', 'linear_quadratic', 'AYS SDXL', 'AYS SD1', 'AYS SVD', 'GITS[coeff=1.2]', 'LTXV[default]']
2024-11-29T00:23:24.030779 - Output will be ignored
2024-11-29T00:23:24.030779 - Failed to validate prompt for output 11051:1:
2024-11-29T00:23:24.031775 - Output will be ignored
2024-11-29T00:23:24.039755 - Failed to validate prompt for output 1565:
2024-11-29T00:23:24.039755 - Output will be ignored
2024-11-29T00:23:24.039755 - Failed to validate prompt for output 11053:1:
2024-11-29T00:23:24.039755 - Output will be ignored
2024-11-29T00:23:24.039755 - Failed to validate prompt for output 11560:31:
2024-11-29T00:23:24.039755 - Output will be ignored
2024-11-29T00:23:24.039755 - Failed to validate prompt for output 1563:
2024-11-29T00:23:24.039755 - Output will be ignored
2024-11-29T00:23:24.040752 - Failed to validate prompt for output 11560:32:
2024-11-29T00:23:24.040752 - Output will be ignored
2024-11-29T00:23:24.040752 - Failed to validate prompt for output 6007:
2024-11-29T00:23:24.040752 - Output will be ignored
2024-11-29T00:23:24.040752 - Failed to validate prompt for output 11051:19:
2024-11-29T00:23:24.040752 - Output will be ignored
2024-11-29T00:23:24.040752 - Failed to validate prompt for output 11054:1:
2024-11-29T00:23:24.040752 - Output will be ignored
2024-11-29T00:23:24.040752 - Failed to validate prompt for output 11560:14:
2024-11-29T00:23:24.040752 - Output will be ignored
2024-11-29T00:23:24.041750 - Failed to validate prompt for output 11668:30:
2024-11-29T00:23:24.041750 - Output will be ignored
2024-11-29T00:23:24.041750 - Failed to validate prompt for output 11050:19:
2024-11-29T00:23:24.041750 - Output will be ignored
2024-11-29T00:23:24.041750 - Failed to validate prompt for output 11052:19:
2024-11-29T00:23:24.041750 - Output will be ignored
2024-11-29T00:23:24.041750 - Failed to validate prompt for output 6308:
2024-11-29T00:23:24.042746 - Output will be ignored
2024-11-29T00:23:24.042746 - Failed to validate prompt for output 11052:1:
2024-11-29T00:23:24.042746 - Output will be ignored
2024-11-29T00:23:24.042746 - Failed to validate prompt for output 10974:
2024-11-29T00:23:24.042746 - Output will be ignored
2024-11-29T00:23:24.042746 - Failed to validate prompt for output 6008:
2024-11-29T00:23:24.042746 - Output will be ignored
2024-11-29T00:23:24.042746 - Failed to validate prompt for output 11050:1:
2024-11-29T00:23:24.042746 - Output will be ignored
2024-11-29T00:23:24.042746 - Failed to validate prompt for output 6950:
2024-11-29T00:23:24.042746 - Output will be ignored
2024-11-29T00:23:24.045738 - Failed to validate prompt for output 11053:19:
2024-11-29T00:23:24.045738 - * ImageClamp 11053:0:
2024-11-29T00:23:24.045738 -   - Required input is missing: image
2024-11-29T00:23:24.045738 - Output will be ignored
2024-11-29T00:23:24.045738 - Failed to validate prompt for output 11668:29:
2024-11-29T00:23:24.045738 - Output will be ignored
2024-11-29T00:23:24.046736 - Failed to validate prompt for output 13:
2024-11-29T00:23:24.047734 - Output will be ignored
2024-11-29T00:23:25.169656 - !!! Exception during processing !!! Name not found: HEX
2024-11-29T00:23:25.170648 - Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 241, in evaluate
    r = eval_expr(node)
        ^^^^^^^^^^^^^^^
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts\py\math_expression.py", line 204, in eval_expr
    raise NameError(f"Name not found: {node.id}")
NameError: Name not found: HEX

2024-11-29T00:23:25.172643 - Prompt executed in 1.09 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Custom-Scripts repo.

https://github.com/pythongosssss/ComfyUI-Custom-Scripts
