### ISSUE TITLE
Tiled VAE does not support LTXVideo

### ISSUE THREAD

**Issue by cheezecrisp** [comfyanonymous/ComfyUI#5835]
### Expected Behavior

Output of LTXVideo could process by Tiled VAE 

### Actual Behavior

Output of LTXVideo could not process by Tiled VAE 

### Steps to Reproduce

exchange the vae decoder with vae decoder tiled, run LTXVideo workflow

### Debug Logs

```powershell
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 304, in decode
    compression = vae.spacial_compression_decode()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 443, in spacial_compression_decode
    return self.upscale_ratio
           ^^^^^^^^^^^^^^^^^^
AttributeError: 'LTXVVAE' object has no attribute 'upscale_ratio'
```

**Comment by LukeG89** [comment]
I just tried and it's working. Is your ComfyUI up-to-date?

**Comment by cheezecrisp** [comment]
> I just tried and it's working. Is your ComfyUI up-to-date?

Just now I tried workflow from ComfyUI_examples it did work, the error occurs with the workflow in the example folder of ltxvideo custom node.
Well, since comfyui supports LTX video by default, I think it's time to uninstall the LTXvideo custom node.

**Comment by x4080** [comment]
Is it support for the new 0.9.1 model ?

**Comment by ltdrdata** [comment]
> Is it support for the new 0.9.1 model ?

Latest ComfyUI supports LTXVideo 0.9.1.

**Comment by x4080** [comment]
cool

**Comment by joneschunghk** [comment]
I had the same issue when using SamplerCustomAdvanced node. But it works fine when using SamplerCustom node. 
Because the quality of STG is better than CFG. However STG must use the SamplerCustomAdvanced node.
