### ISSUE TITLE
IPAdapterUnifiedLoader Error while deserializing header: HeaderTooLarge

### ISSUE THREAD

**Issue by LIULE1** [comfyanonymous/ComfyUI#5838]
### Your question

I discovered this problem on the Mac client.
![image](https://github.com/user-attachments/assets/4d8fdc99-98fd-4477-b85a-1c354852dddf)
I made sure that there were no problems with either my installation path or the model.
The following is the error message.

# ComfyUI Error Report
## Error Details
- **Node ID:** 10
- **Node Type:** IPAdapterUnifiedLoader
- **Exception Type:** safetensors_rust.SafetensorError
- **Exception Message:** Error while deserializing header: HeaderTooLarge
## Stack Trace
```
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus-main/IPAdapterPlus.py", line 564, in load_models
    self.clipvision['model'] = load_clip_vision(clipvision_file)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Volumes/HP ZHAN SSD/ComfyUI/.venv/lib/python3.12/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

```
## System Information
- **ComfyUI Version:** unknown
- **Arguments:** /Applications/ComfyUI.app/Contents/Resources/ComfyUI/main.py --user-directory /Volumes/HP ZHAN SSD/ComfyUI/user --input-directory /Volumes/HP ZHAN SSD/ComfyUI/input --output-directory /Volumes/HP ZHAN SSD/ComfyUI/output --front-end-root /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app --extra-model-paths-config /Users/LIULEIsMAC/Library/Application Support/ComfyUI/extra_models_config.yaml --port 8000
- **OS:** posix
- **Python Version:** 3.12.4 (main, Jul 25 2024, 22:11:22) [Clang 18.1.8 ]
- **Embedded Python:** false
- **PyTorch Version:** 2.6.0.dev20241126
## Devices

- **Name:** mps
  - **Type:** mps
  - **VRAM Total:** 34359738368
  - **VRAM Free:** 8517582848
  - **Torch VRAM Total:** 34359738368
  - **Torch VRAM Free:** 8517582848

## Logs
```
2024-11-29T17:35:53.139156 - [START] Security scan2024-11-29T17:35:53.139170 - 
2024-11-29T17:35:54.082909 - [DONE] Security scan2024-11-29T17:35:54.082945 - 
2024-11-29T17:35:54.151062 - ## ComfyUI-Manager: installing dependencies done.2024-11-29T17:35:54.151103 - 
2024-11-29T17:35:54.151118 - ** ComfyUI startup time:2024-11-29T17:35:54.151128 -  2024-11-29T17:35:54.151138 - 2024-11-29 17:35:54.1511092024-11-29T17:35:54.151146 - 
2024-11-29T17:35:54.151172 - ** Platform:2024-11-29T17:35:54.151180 -  2024-11-29T17:35:54.151189 - Darwin2024-11-29T17:35:54.151197 - 
2024-11-29T17:35:54.151207 - ** Python version:2024-11-29T17:35:54.151216 -  2024-11-29T17:35:54.151224 - 3.12.4 (main, Jul 25 2024, 22:11:22) [Clang 18.1.8 ]2024-11-29T17:35:54.151232 - 
2024-11-29T17:35:54.151242 - ** Python executable:2024-11-29T17:35:54.151248 -  2024-11-29T17:35:54.151255 - /Volumes/HP ZHAN SSD/ComfyUI/.venv/bin/python2024-11-29T17:35:54.151262 - 
2024-11-29T17:35:54.151270 - ** ComfyUI Path:2024-11-29T17:35:54.151277 -  2024-11-29T17:35:54.151283 - /Applications/ComfyUI.app/Contents/Resources/ComfyUI2024-11-29T17:35:54.151290 - 
2024-11-29T17:35:54.151492 - ** Log path:2024-11-29T17:35:54.151500 -  2024-11-29T17:35:54.151506 - /Volumes/HP ZHAN SSD/ComfyUI/comfyui.log2024-11-29T17:35:54.151513 - 
2024-11-29T17:35:55.101473 - 
Prestartup times for custom nodes:2024-11-29T17:35:55.101517 - 
2024-11-29T17:35:55.101538 -    2.0 seconds:2024-11-29T17:35:55.101550 -  2024-11-29T17:35:55.101559 - /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager2024-11-29T17:35:55.101567 - 
2024-11-29T17:35:55.101575 - 
2024-11-29T17:35:56.399073 - Total VRAM 32768 MB, total RAM 32768 MB
2024-11-29T17:35:56.399154 - pytorch version: 2.6.0.dev20241126
2024-11-29T17:35:56.399254 - Set vram state to: SHARED
2024-11-29T17:35:56.399284 - Device: mps
2024-11-29T17:35:57.335114 - Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
2024-11-29T17:35:58.360929 - [Prompt Server] web root: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/web_custom_versions/desktop_app
2024-11-29T17:35:58.362147 - Adding extra search path checkpoints /Volumes/HP ZHAN SSD/ComfyUI/models/checkpoints/
2024-11-29T17:35:58.362192 - Adding extra search path classifiers /Volumes/HP ZHAN SSD/ComfyUI/models/classifiers/
2024-11-29T17:35:58.362215 - Adding extra search path clip /Volumes/HP ZHAN SSD/ComfyUI/models/clip/
2024-11-29T17:35:58.362232 - Adding extra search path clip_vision /Volumes/HP ZHAN SSD/ComfyUI/models/clip_vision/
2024-11-29T17:35:58.362248 - Adding extra search path configs /Volumes/HP ZHAN SSD/ComfyUI/models/configs/
2024-11-29T17:35:58.362265 - Adding extra search path controlnet /Volumes/HP ZHAN SSD/ComfyUI/models/controlnet/
2024-11-29T17:35:58.362280 - Adding extra search path diffusers /Volumes/HP ZHAN SSD/ComfyUI/models/diffusers/
2024-11-29T17:35:58.362294 - Adding extra search path diffusion_models /Volumes/HP ZHAN SSD/ComfyUI/models/diffusion_models/
2024-11-29T17:35:58.362309 - Adding extra search path embeddings /Volumes/HP ZHAN SSD/ComfyUI/models/embeddings/
2024-11-29T17:35:58.362323 - Adding extra search path gligen /Volumes/HP ZHAN SSD/ComfyUI/models/gligen/
2024-11-29T17:35:58.362337 - Adding extra search path hypernetworks /Volumes/HP ZHAN SSD/ComfyUI/models/hypernetworks/
2024-11-29T17:35:58.362352 - Adding extra search path loras /Volumes/HP ZHAN SSD/ComfyUI/models/loras/
2024-11-29T17:35:58.362614 - Adding extra search path photomaker /Volumes/HP ZHAN SSD/ComfyUI/models/photomaker/
2024-11-29T17:35:58.362848 - Adding extra search path style_models /Volumes/HP ZHAN SSD/ComfyUI/models/style_models/
2024-11-29T17:35:58.362939 - Adding extra search path unet /Volumes/HP ZHAN SSD/ComfyUI/models/unet/
2024-11-29T17:35:58.362998 - Adding extra search path upscale_models /Volumes/HP ZHAN SSD/ComfyUI/models/upscale_models/
2024-11-29T17:35:58.363024 - Adding extra search path vae /Volumes/HP ZHAN SSD/ComfyUI/models/vae/
2024-11-29T17:35:58.363073 - Adding extra search path vae_approx /Volumes/HP ZHAN SSD/ComfyUI/models/vae_approx/
2024-11-29T17:35:58.363100 - Adding extra search path animatediff_models /Volumes/HP ZHAN SSD/ComfyUI/models/animatediff_models/
2024-11-29T17:35:58.363118 - Adding extra search path animatediff_motion_lora /Volumes/HP ZHAN SSD/ComfyUI/models/animatediff_motion_lora/
2024-11-29T17:35:58.363136 - Adding extra search path animatediff_video_formats /Volumes/HP ZHAN SSD/ComfyUI/models/animatediff_video_formats/
2024-11-29T17:35:58.363152 - Adding extra search path ipadapter /Volumes/HP ZHAN SSD/ComfyUI/models/ipadapter/
2024-11-29T17:35:58.363167 - Adding extra search path liveportrait /Volumes/HP ZHAN SSD/ComfyUI/models/liveportrait/
2024-11-29T17:35:58.363181 - Adding extra search path insightface /Volumes/HP ZHAN SSD/ComfyUI/models/insightface/
2024-11-29T17:35:58.363196 - Adding extra search path layerstyle /Volumes/HP ZHAN SSD/ComfyUI/models/layerstyle/
2024-11-29T17:35:58.363210 - Adding extra search path LLM /Volumes/HP ZHAN SSD/ComfyUI/models/LLM/
2024-11-29T17:35:58.363224 - Adding extra search path Joy_caption /Volumes/HP ZHAN SSD/ComfyUI/models/Joy_caption/
2024-11-29T17:35:58.363325 - Adding extra search path sams /Volumes/HP ZHAN SSD/ComfyUI/models/sams/
2024-11-29T17:35:58.363359 - Adding extra search path blip /Volumes/HP ZHAN SSD/ComfyUI/models/blip/
2024-11-29T17:35:58.363379 - Adding extra search path CogVideo /Volumes/HP ZHAN SSD/ComfyUI/models/CogVideo/
2024-11-29T17:35:58.363422 - Adding extra search path xlabs /Volumes/HP ZHAN SSD/ComfyUI/models/xlabs/
2024-11-29T17:35:58.363437 - Adding extra search path instantid /Volumes/HP ZHAN SSD/ComfyUI/models/instantid/
2024-11-29T17:35:58.363451 - Adding extra search path custom_nodes /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/
2024-11-29T17:35:58.820754 - ### Loading: ComfyUI-Manager (V2.52.1)2024-11-29T17:35:58.820782 - 
2024-11-29T17:35:58.829844 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)2024-11-29T17:35:58.829887 - 
2024-11-29T17:35:58.898790 - Traceback (most recent call last):
  File "/Volumes/HP ZHAN SSD/ComfyUI/.venv/lib/python3.12/site-packages/insightface/__init__.py", line 8, in <module>
    import onnxruntime
ModuleNotFoundError: No module named 'onnxruntime'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/comfyui-simswap/__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "/Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/comfyui-simswap/nodes.py", line 15, in <module>
    from insightface.app.common import Face
  File "/Volumes/HP ZHAN SSD/ComfyUI/.venv/lib/python3.12/site-packages/insightface/__init__.py", line 10, in <module>
    raise ImportError(
ImportError: Unable to import dependency onnxruntime. 

2024-11-29T17:35:58.898862 - Cannot import /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/comfyui-simswap module for custom nodes: Unable to import dependency onnxruntime. 
2024-11-29T17:35:58.903966 - [VideoHelperSuite] - [0;33mWARNING[0m - Failed to import imageio_ffmpeg
2024-11-29T17:35:58.904302 - [VideoHelperSuite] - [0;31mERROR[0m - No valid ffmpeg found.
2024-11-29T17:35:58.910013 - ### Loading: ComfyUI-Manager (V2.52.1)2024-11-29T17:35:58.910039 - 
2024-11-29T17:35:58.910138 - ### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)2024-11-29T17:35:58.910147 - 
2024-11-29T17:35:58.912145 - 
Import times for custom nodes:
2024-11-29T17:35:58.912411 -    0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/websocket_image_save.py
2024-11-29T17:35:58.912556 -    0.0 seconds: /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
2024-11-29T17:35:58.912620 -    0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-TRANSLATION
2024-11-29T17:35:58.912649 -    0.0 seconds: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager
2024-11-29T17:35:58.912730 -    0.0 seconds: /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/comfyui-inpaint-nodes
2024-11-29T17:35:58.912755 -    0.0 seconds: /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
2024-11-29T17:35:58.912777 -    0.0 seconds: /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/ComfyUI-Manager-main
2024-11-29T17:35:58.912797 -    0.0 seconds: /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus-main
2024-11-29T17:35:58.912818 -    0.1 seconds (IMPORT FAILED): /Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/comfyui-simswap
2024-11-29T17:35:58.912843 - 
2024-11-29T17:35:58.916253 - Setting output directory to: /Volumes/HP ZHAN SSD/ComfyUI/output
2024-11-29T17:35:58.916387 - Setting input directory to: /Volumes/HP ZHAN SSD/ComfyUI/input
2024-11-29T17:35:58.916414 - Setting user directory to: /Volumes/HP ZHAN SSD/ComfyUI/user
2024-11-29T17:35:58.916869 - Starting server

2024-11-29T17:35:58.917139 - To see the GUI go to: http://127.0.0.1:8000
2024-11-29T17:35:59.489913 - FETCH DATA from: /Applications/ComfyUI.app/Contents/Resources/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-11-29T17:35:59.489935 - 2024-11-29T17:35:59.492539 -  [DONE]2024-11-29T17:35:59.492558 - 
2024-11-29T17:35:59.553659 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-29T17:35:59.553685 - 
2024-11-29T17:35:59.568982 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-29T17:35:59.569003 - 
2024-11-29T17:35:59.617463 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-11-29T17:35:59.617488 - 
2024-11-29T17:35:59.666002 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-11-29T17:35:59.666026 - 
2024-11-29T17:35:59.728877 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-29T17:35:59.728913 - 
2024-11-29T17:35:59.859923 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-11-29T17:35:59.859947 - 
2024-11-29T17:35:59.918513 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-29T17:35:59.918542 - 
2024-11-29T17:35:59.974505 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-29T17:35:59.974534 - 
2024-11-29T17:36:00.056670 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-11-29T17:36:00.056705 - 
2024-11-29T17:36:00.068303 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-11-29T17:36:00.068325 - 
2024-11-29T17:36:02.082264 - got prompt
2024-11-29T17:36:02.641573 - model weight dtype torch.float16, manual cast: None
2024-11-29T17:36:02.641834 - model_type EPS
2024-11-29T17:36:04.585083 - Using split attention in VAE
2024-11-29T17:36:04.585930 - Using split attention in VAE
2024-11-29T17:36:04.862443 - Requested to load SD1ClipModel
2024-11-29T17:36:04.862528 - Loading 1 new model
2024-11-29T17:36:04.865245 - loaded completely 0.0 471.68848037719727 True
2024-11-29T17:36:05.270120 - !!! Exception during processing !!! Error while deserializing header: HeaderTooLarge
2024-11-29T17:36:05.272978 - Traceback (most recent call last):
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/HP ZHAN SSD/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus-main/IPAdapterPlus.py", line 564, in load_models
    self.clipvision['model'] = load_clip_vision(clipvision_file)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/clip_vision.py", line 120, in load
    sd = load_torch_file(ckpt_path)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Applications/ComfyUI.app/Contents/Resources/ComfyUI/comfy/utils.py", line 34, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device=device.type)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/HP ZHAN SSD/ComfyUI/.venv/lib/python3.12/site-packages/safetensors/torch.py", line 313, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooLarge

2024-11-29T17:36:05.273983 - Prompt executed in 3.19 seconds
2024-11-29T17:36:05.442378 - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":12,"last_link_id":14,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5,"label":"clip"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[6],"slot_index":0,"label":"CONDITIONING"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[2],"slot_index":0,"label":"LATENT"}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":8,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7,"label":"samples"},{"name":"vae","type":"VAE","link":8,"label":"vae"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0,"label":"IMAGE"}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":9,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9,"label":"images"}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":7,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":12,"label":"model"},{"name":"positive","type":"CONDITIONING","link":4,"label":"positive"},{"name":"negative","type":"CONDITIONING","link":6,"label":"negative"},{"name":"latent_image","type":"LATENT","link":2,"label":"latent_image"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0,"label":"LATENT"}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[141065796232004,"randomize",20,8,"euler","normal",1]},{"id":11,"type":"IPAdapter","pos":[373.69921875,-123.89453125],"size":[315,190],"flags":{},"order":6,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":11,"label":"model"},{"name":"ipadapter","type":"IPADAPTER","link":14,"label":"ipadapter"},{"name":"image","type":"IMAGE","link":13,"label":"image"},{"name":"attn_mask","type":"MASK","link":null,"shape":7,"label":"attn_mask"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[12],"slot_index":0,"label":"MODEL"}],"properties":{"Node name for S&R":"IPAdapter"},"widgets_values":[1,0,1,"standard"]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[10],"slot_index":0,"label":"MODEL"},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1,"label":"CLIP"},{"name":"VAE","type":"VAE","links":[8],"slot_index":2,"label":"VAE"}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["v1-5-dream-shaper.safetensors"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":4,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3,"label":"clip"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[4],"slot_index":0,"label":"CONDITIONING"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["beautiful girl"]},{"id":12,"type":"LoadImage","pos":[-46.50390625,47.47265625],"size":[315,314],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[13],"label":"IMAGE"},{"name":"MASK","type":"MASK","links":null,"label":"MASK"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["ca19efed36b1d76b9909b72984f06b76.jpg","image"]},{"id":10,"type":"IPAdapterUnifiedLoader","pos":[-84.89453125,-146.234375],"size":[315,78],"flags":{},"order":3,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":10,"label":"model"},{"name":"ipadapter","type":"IPADAPTER","link":null,"shape":7,"label":"ipadapter"}],"outputs":[{"name":"model","type":"MODEL","links":[11],"slot_index":0,"label":"model"},{"name":"ipadapter","type":"IPADAPTER","links":[14],"slot_index":1,"label":"ipadapter"}],"properties":{"Node name for S&R":"IPAdapterUnifiedLoader"},"widgets_values":["LIGHT - SD1.5 only (low strength)"]}],"links":[[2,5,0,3,3,"LATENT"],[3,4,1,6,0,"CLIP"],[4,6,0,3,1,"CONDITIONING"],[5,4,1,7,0,"CLIP"],[6,7,0,3,2,"CONDITIONING"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[10,4,0,10,0,"MODEL"],[11,10,0,11,0,"MODEL"],[12,11,0,3,0,"MODEL"],[13,12,0,11,2,"IMAGE"],[14,10,1,11,1,"IPADAPTER"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.1000000000000003,"offset":[338.6671616735538,279.7428331611569]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by ltdrdata** [comment]
Typically, this happens when the model you downloaded is incorrect.  
Additionally, installing custom nodes by downloading a zip file and extracting it is not recommended.

**Comment by tmbj666** [comment]
我也有同样的问题，请问你解决了吗

**Comment by LIULE1** [comment]
> 我也有同样的问题，请问解决了吗

还没有，准备重新安装一下IPA试一试，大概率是comfyui mac客户端的问题，昨天在家里用PC尝试了一下，一次跑通

**Comment by popoleaf** [comment]
我一般第一报警，不管它再跑一次就通了
