### ISSUE TITLE
comfyui update error

### ISSUE THREAD

**Issue by Luckyjjjjjjj** [comfyanonymous/ComfyUI#5848]
### Your question

When I updated, I used update_comfyui_and_python_dependencies, which failed to update and kept getting errors. I tried to solve the dependencies myself for two days, but it couldn't be solved. I use a vpn, I can do any git, but I just can't update comfyui, hope kind people can help me.

The following error message is displayed:

stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-11-30_16_04_47
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "E:\ComfyUI_windows_portable\update\update.py", line 11, in pull
    remote.fetch()
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\remotes.py", line 160, in fetch
    payload.check_error(err)
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: failed to send request: 无法与服务器建立连接

-
This will try to update pytorch and all python dependencies.
-
If you just want to update normally, close this and run update_comfyui.bat instead.
-

**Comment by denzel10247** [comment]
Hi, is the problem solved? I have the same problem as you.

**Comment by ltdrdata** [comment]
It seems that it is a your network environmental issue.
Try with VPN.

**Comment by denzel10247** [comment]
> It seems that it is a your network environmental issue. Try with VPN.

Thanks, it was my network problem.
