### ISSUE TITLE
Empty Latent Image Node Settings

### ISSUE THREAD

**Issue by kyle215ps3** [comfyanonymous/ComfyUI#589]
Nevermind, I figured out how to make custom sizes with the convert the width to height into inputs and then use integer node to put in the sizes.

**Comment by kyle215ps3** [comment]
nevermind again, looks like putting in 592 as the height causes an issue. But doesn't at 512 for example. Is their another way to use the height of 592?

Error

Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 195, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 816, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 787, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 79, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 666, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 594, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 283, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 271, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 250, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 227, in calc_cond_uncond_batch
    output = model_function(input_x, timestep_, cond=c).chunk(batch_chunks)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\diffusion\ddpm.py", line 859, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\diffusion\ddpm.py", line 1337, in forward
    out = self.diffusion_model(x, t, context=cc, control=control, transformer_options=transformer_options)
  File "D:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\openaimodel.py", line 816, in forward
    h = th.cat([h, hsp], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 20 but got size 19 for tensor number 1 in the list.

**Comment by BlenderNeko** [comment]
The denoiser in ComfyUI currently only supports resolutions that are increments of 64, If you need something that is not an increment of 64, your options are resizing or padding/cropping

**Comment by kyle215ps3** [comment]
> The denoiser in ComfyUI currently only supports resolutions that are increments of 64, If you need something that is not an increment of 64, your options are resizing or padding/cropping

damnn xD I hope they can allow a way to change it, I want to recreate some images on comfy UI I made from A1111 haha.

**Comment by kyle215ps3** [comment]
> The denoiser in ComfyUI currently only supports resolutions that are increments of 64, If you need something that is not an increment of 64, your options are resizing or padding/cropping

just found out the latent image resolution got updated and i can now get the resolution i need. Thank you if you had anything to do with it!! :D Much appreciated!!
