### ISSUE TITLE
"data did not match any variant of untagged enum ModelWrapper at line 259572 column 3"

### ISSUE THREAD

**Issue by athossampaio** [comfyanonymous/ComfyUI#5894]
### Your question

Hi,
Maybe related to recently having installed LTXVideo nodes or Updating ComfyUI to its latest version, now when I try to queue a prompt from a workflow that uses Florence2Run or Miaoshou Tagger custom nodes (which both load the Florence-2l-large-PormptGen-v2.0 model fine-tune I donwloaded), I get this error in the title
"data did not match any variant of untagged enum ModelWrapper at line 259572 column 3"
which, based on some search for answers, seems related to some recent change in the transformers but I'm not sure. How I would urgently go about fixing this issue?
Again: I'm using ComfyUI's latest version.

### Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-03 20:42:34.958412
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: E:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI_windows_portable\ComfyUI
** Log path: E:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   3.5 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8191 MB, total RAM 32719 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\__init__.py", line 53, in <module>
    module = importlib.import_module(f".{nodes_filename}", package=__name__)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\nodes.py", line 38, in <module>
    from .mesh_processer.mesh import Mesh
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack\mesh_processer\mesh.py", line 8, in <module>
    from kiui.op import safe_normalize, dot
ModuleNotFoundError: No module named 'kiui'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack module for custom nodes: No module named 'kiui'
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using symlinks: False
[custom_nodes.comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py:26: UserWarning: DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly
  warnings.warn("DWPose: Onnxruntime not found or doesn't come with acceleration providers, switch to OpenCV with CPU device. DWPose might run very slowly")

Total VRAM 8191 MB, total RAM 32719 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 Ti : cudaMallocAsync
Initializing EasyNodes. Auto-registration: True
### Loading: ComfyUI-Manager (V2.51.9)
### ComfyUI Revision: 2885 [452179fe] | Released on '2024-12-03'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[comfyui_controlnet_aux] | INFO -> Using ckpts path: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
[comfy_mtb] | INFO -> loaded 83 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 8, in <module>
    from custom_nodes.facerestore_cf.facelib.utils.face_restoration_helper import FaceRestoreHelper
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\__init__.py", line 14, in <module>
    from custom_nodes.facerestore_cf.basicsr.utils.registry import ARCH_REGISTRY
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\__init__.py", line 5, in <module>
    from .losses import *
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\losses\__init__.py", line 5, in <module>
    from .losses import (CharbonnierLoss, GANLoss, L1Loss, MSELoss, PerceptualLoss, WeightedTVLoss, g_path_regularize,
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf\basicsr\losses\losses.py", line 2, in <module>
    import lpips
ModuleNotFoundError: No module named 'lpips'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf module for custom nodes: No module named 'lpips'
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 991, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1128, in get_code
  File "<frozen importlib._bootstrap_external>", line 1186, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'E:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\LLM-Base-Prompts\\__init__.py'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\LLM-Base-Prompts module for custom nodes: [Errno 2] No such file or directory: 'E:\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\LLM-Base-Prompts\\__init__.py'

[rgthree-comfy] Loaded 42 magnificent nodes. 🎉

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Believe in yourself, take on your challenges, and dig deep within yourself to conquer fears." - Chantal Sutherland


Import times for custom nodes:
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_bnb_nf4_fp4_Loaders
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\LLM-Base-Prompts
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Miaoshouai-Tagger
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Flux-Prompt-Saver
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IF_AI_HFDownloaderNode
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXTricks
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CogVideoX
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\Flux-Prompt-Generator
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\x-flux-comfyui
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\virtuoso-nodes
   0.0 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.2 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-tensorops
   0.2 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy_mtb
   0.2 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.5 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Anyline
   0.6 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.8 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Fluxpromptenhancer
   1.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LTXVideo
   1.1 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Filters
   2.6 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   3.0 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3D-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
got prompt
Failed to validate prompt for output 5:
* CheckpointLoaderSimple 9:
  - Value not in list: ckpt_name: 'wildcardxXLTURBO_wildcardxXLTURBOV10.safetensors' not in ['LTXvideo\\ltx-video-2b-v0.9-fp8_e4m3fn.safetensors', 'LTXvideo\\ltx-video-2b-v0.9.safetensors', 'flux\\fluxTurbo_v10FP8Unet.safetensors', 'sd1.5\\absolutereality_v181.safetensors', 'sd1.5\\dreamshaper_8.safetensors', 'sd1.5\\realisticVisionV60B1_v60B1VAE.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sdxl\\dreamshaperXL_v21TurboDPMSDE.safetensors', 'sdxl\\wildcardxXLTURBO_wildcardxXLTURBOV10.safetensors']
Output will be ignored
Failed to validate prompt for output 16:
Output will be ignored
Loading model from E:\ComfyUI_windows_portable\ComfyUI\models\LLM\Florence-2-large-PromptGen-v2.0
using sdpa for attention
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)

!!! Exception during processing !!! data did not match any variant of untagged enum ModelWrapper at line 259572 column 3
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 176, in loadmodel
    processor = AutoProcessor.from_pretrained(model_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\processing_auto.py", line 317, in from_pretrained
    return processor_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\processing_utils.py", line 892, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\processing_utils.py", line 938, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2271, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2505, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\bart\tokenization_bart_fast.py", line 143, in __init__
    super().__init__(
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_fast.py", line 115, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: data did not match any variant of untagged enum ModelWrapper at line 259572 column 3

Prompt executed in 3.80 seconds
got prompt
Failed to validate prompt for output 5:
* CheckpointLoaderSimple 9:
  - Value not in list: ckpt_name: 'wildcardxXLTURBO_wildcardxXLTURBOV10.safetensors' not in ['LTXvideo\\ltx-video-2b-v0.9-fp8_e4m3fn.safetensors', 'LTXvideo\\ltx-video-2b-v0.9.safetensors', 'flux\\fluxTurbo_v10FP8Unet.safetensors', 'sd1.5\\absolutereality_v181.safetensors', 'sd1.5\\dreamshaper_8.safetensors', 'sd1.5\\realisticVisionV60B1_v60B1VAE.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sdxl\\dreamshaperXL_v21TurboDPMSDE.safetensors', 'sdxl\\wildcardxXLTURBO_wildcardxXLTURBOV10.safetensors']
Output will be ignored
Failed to validate prompt for output 16:
Output will be ignored
Loading model from E:\ComfyUI_windows_portable\ComfyUI\models\LLM\Florence-2-large-PromptGen-v2.0
using sdpa for attention
!!! Exception during processing !!! data did not match any variant of untagged enum ModelWrapper at line 259572 column 3
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 176, in loadmodel
    processor = AutoProcessor.from_pretrained(model_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\processing_auto.py", line 317, in from_pretrained
    return processor_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\processing_utils.py", line 892, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\processing_utils.py", line 938, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2271, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2505, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\bart\tokenization_bart_fast.py", line 143, in __init__
    super().__init__(
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_fast.py", line 115, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: data did not match any variant of untagged enum ModelWrapper at line 259572 column 3

Prompt executed in 3.26 seconds
got prompt
Failed to validate prompt for output 5:
* CheckpointLoaderSimple 9:
  - Value not in list: ckpt_name: 'wildcardxXLTURBO_wildcardxXLTURBOV10.safetensors' not in ['LTXvideo\\ltx-video-2b-v0.9-fp8_e4m3fn.safetensors', 'LTXvideo\\ltx-video-2b-v0.9.safetensors', 'flux\\fluxTurbo_v10FP8Unet.safetensors', 'sd1.5\\absolutereality_v181.safetensors', 'sd1.5\\dreamshaper_8.safetensors', 'sd1.5\\realisticVisionV60B1_v60B1VAE.safetensors', 'sd_xl_refiner_1.0_0.9vae.safetensors', 'sdxl\\dreamshaperXL_v21TurboDPMSDE.safetensors', 'sdxl\\wildcardxXLTURBO_wildcardxXLTURBOV10.safetensors']
Output will be ignored
Failed to validate prompt for output 16:
Output will be ignored
Loading model from E:\ComfyUI_windows_portable\ComfyUI\models\LLM\Florence-2-large-PromptGen-v2.0
using sdpa for attention
!!! Exception during processing !!! data did not match any variant of untagged enum ModelWrapper at line 259572 column 3
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 176, in loadmodel
    processor = AutoProcessor.from_pretrained(model_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\auto\processing_auto.py", line 317, in from_pretrained
    return processor_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\processing_utils.py", line 892, in from_pretrained
    args = cls._get_arguments_from_pretrained(pretrained_model_name_or_path, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\processing_utils.py", line 938, in _get_arguments_from_pretrained
    args.append(attribute_class.from_pretrained(pretrained_model_name_or_path, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2271, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_base.py", line 2505, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\models\bart\tokenization_bart_fast.py", line 143, in __init__
    super().__init__(
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\tokenization_utils_fast.py", line 115, in __init__
    fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Exception: data did not match any variant of untagged enum ModelWrapper at line 259572 column 3

Prompt executed in 3.91 seconds
```

**Comment by athossampaio** [comment]
For now it seems I solved the problem, by simply downloading separately the most recent version of ComfyUI (portable) and copy-pasting the two tokenizers folders and two transformers folders (simple and name and name + version) in Lib\site-packages\ to the ComfyUI folder I was using, and also deleting the older versions of each (tokenizers and transformers) - the old versions seemed to have been loaded and causing the issue, when running ComfyUI portable's .bat file.

**Comment by athossampaio** [comment]
For a while For now it seemed that I solved the problem, by simply downloading separately the most recent version of ComfyUI (portable) and copy-pasting the two tokenizers folders and two transformers folders (simple and name and name + version) in Lib\site-packages\ to the ComfyUI folder I was using, and also deleting the older versions of each (tokenizers and transformers) - the old versions seemed to have been loaded and causing the issue, when running ComfyUI portable's .bat file.

But then, the LTXVideo nodes (downloaded via the Manager > Install Custom Nodes) stopped working, outputting always a black screen video.
So, I tried updating the LTXVideo custom nodes with "Try update" and it showed what I suspected before: it seems like it wants to use older versions of the tokenizers and transforms, so it installs them, which in turn leads me back to the beginning of the issue: Florence2Run and Miashou Tagger stop working.

Which is the proper solution, in this case?

**Comment by Tromazing** [comment]
Just adding that I'm having the exact same issue with Miaoshou Tagger since updating.

**Comment by Magenta-6** [comment]
Similar issue for me.  
I can see that the model has been downloaded to my hard drive at
E:\Ai\ComfyUi\ComfyUI_windows_portable\ComfyUI\models\LLM\Florence-2-large-PromptGen-v2.0
But for some reason it cannot see it.
regards

**Comment by ltdrdata** [comment]
> For a while For now it seemed that I solved the problem, by simply downloading separately the most recent version of ComfyUI (portable) and copy-pasting the two tokenizers folders and two transformers folders (simple and name and name + version) in Lib\site-packages\ to the ComfyUI folder I was using, and also deleting the older versions of each (tokenizers and transformers) - the old versions seemed to have been loaded and causing the issue, when running ComfyUI portable's .bat file.
> 
> But then, the LTXVideo nodes (downloaded via the Manager > Install Custom Nodes) stopped working, outputting always a black screen video. So, I tried updating the LTXVideo custom nodes with "Try update" and it showed what I suspected before: it seems like it wants to use older versions of the tokenizers and transforms, so it installs them, which in turn leads me back to the beginning of the issue: Florence2Run and Miashou Tagger stop working.
> 
> Which is the proper solution, in this case?

Conflicts between custom nodes can occur due to interdependencies, and these compatibility issues need to be resolved within the respective custom node's repository.

**Comment by StantheBrain** [comment]
utilise la version de base,; Florence-2-base-PromptGen-v2.0
