### ISSUE TITLE
"RecursionError: maximum recursion depth exceeded" after first launch

### ISSUE THREAD

**Issue by elegos** [comfyanonymous/ComfyUI#5895]
### Expected Behavior

I expect ComfyUI to run after the first run

### Actual Behavior

The application crashes at startup, with the error in the subject

### Steps to Reproduce

Download ComfyUI
Download the models (I downloaded the SD3.5 models for instance, not sure if this counts)
Run ComfyUI
Close ComfyUI
Start ComfyUI again

### Debug Logs

```powershell
C:\Users\giaco\ComfyUI_windows_portable_brok>.\python_embeded\python.exe -s ComfyUI\main.py --cuda-device 0 --listen 0.0.0.0 --windows-standalone-build --disable-all-custom-nodes
Set cuda device to: 0
Total VRAM 16376 MB, total RAM 130983 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4080 SUPER : cudaMallocAsync
Using pytorch cross attention
Traceback (most recent call last):
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\ComfyUI\main.py", line 91, in <module>
    import execution
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\ComfyUI\nodes.py", line 22, in <module>
    import comfy.samplers
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\ComfyUI\comfy\samplers.py", line 19, in <module>
    import scipy.stats
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\stats\__init__.py", line 610, in <module>
    from ._stats_py import *
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\stats\_stats_py.py", line 49, in <module>
    from . import distributions
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\stats\distributions.py", line 10, in <module>
    from . import _continuous_distns
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\stats\_continuous_distns.py", line 12, in <module>
    from scipy.interpolate import BSpline
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\interpolate\__init__.py", line 167, in <module>
    from ._interpolate import *
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\interpolate\_interpolate.py", line 12, in <module>
    from . import _fitpack_py
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\interpolate\_fitpack_py.py", line 8, in <module>
    from ._fitpack_impl import bisplrep, bisplev, dblint  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\scipy\interpolate\_fitpack_impl.py", line 103, in <module>
    'iwrk': array([], dfitpack_int), 'u': array([], float),
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

[!!!THIS IS REPEATED SEVERAL TIMES!!!]
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\_dtype.py", line 143, in _scalar_str
    elif np.issubdtype(dtype, np.number):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\numerictypes.py", line 417, in issubdtype
    arg1 = dtype(arg1).type
           ^^^^^^^^^^^
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\_dtype.py", line 46, in __repr__
    arg_str = _construction_repr(dtype, include_align=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\_dtype.py", line 100, in _construction_repr
    return _scalar_str(dtype, short=short)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!!!THIS IS REPEATED SEVERAL TIMES!!!]

  File "C:\Users\giaco\ComfyUI_windows_portable_brok\python_embeded\Lib\site-packages\numpy\core\_dtype.py", line 104, in _scalar_str
    byteorder = _byte_order_str(dtype)
                ^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded
```

**Comment by jakeatmsft** [comment]
following, same issue

**Comment by ApolloForge** [comment]
I started getting this error. I've been running CumryUI for a couple of weeks now on a Ubuntu machine.

Requirement already satisfied: setuptools in /opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages (75.6.0)
Setting output directory to: /home/admin_bnb_c/Pictures/ComfyUI_Output
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2025-01-11 10:01:05.245987
** Platform: Linux
** Python version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
** Python executable: /opt/comfyui/ComfyUI/venv/bin/python3
** ComfyUI Path: /opt/comfyui/ComfyUI
** User directory: /opt/comfyui/ComfyUI/user
** ComfyUI-Manager config path: /opt/comfyui/ComfyUI/user/default/ComfyUI-Manager/config.ini
** Log path: /opt/comfyui/ComfyUI/user/comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: /opt/comfyui/ComfyUI/custom_nodes/rgthree-comfy
   1.5 seconds: /opt/comfyui/ComfyUI/custom_nodes/ComfyUI-Manager

Traceback (most recent call last):
  File "/opt/comfyui/ComfyUI/main.py", line 134, in <module>
    import comfy.utils
  File "/opt/comfyui/ComfyUI/comfy/utils.py", line 18, in <module>
    import torch
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/torch/__init__.py", line 1706, in <module>
    from torch import storage as storage  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/torch/storage.py", line 23, in <module>
    import numpy as np
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/__init__.py", line 122, in <module>
    from ._core import (
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/_core/memmap.py", line 5, in <module>
    from .numeric import uint8, ndarray, dtype
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/_core/numeric.py", line 11, in <module>
    from . import multiarray
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/_core/multiarray.py", line 1, in <module>
    from numpy.core import multiarray
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/__init__.py", line 72, in <module>
    from . import numerictypes as nt
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/numerictypes.py", line 105, in <module>
    from ._type_aliases import (
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/_type_aliases.py", line 23, in <module>
    from numpy.core._dtype import _kind_name
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/_dtype.py", line 4, in __getattr__
    ret = getattr(_dtype, attr_name, None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/_dtype.py", line 4, in __getattr__
    ret = getattr(_dtype, attr_name, None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/_dtype.py", line 4, in __getattr__
    ret = getattr(_dtype, attr_name, None)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 927 more times]
  File "/opt/comfyui/ComfyUI/venv/lib/python3.12/site-packages/numpy/core/_dtype.py", line 2, in __getattr__
    from numpy._core import _dtype
RecursionError: maximum recursion depth exceeded


The command I use to start it is: source /opt/comfyui/ComfyUI/venv/bin/activate && pip3 install setuptools && python3 /opt/comfyui/ComfyUI/main.py --listen 0.0.0.0 --output-directory /home/admin_bnb_c/Pictures/ComfyUI_Output

I had to use that command to avoid other issues around loading torch.

The last thing I did was update ComfyUI under the 'Update All' option.

**Comment by ltdrdata** [comment]
`.\python_embeded\python.exe -m pip freeze`

What is the verion of the `numpy`?

**Comment by ApolloForge** [comment]
I have 1.26.4 installed

**Comment by ltdrdata** [comment]
Disable all custom nodes and try again.

**Comment by ApolloForge** [comment]
I'm not sure how to do that. Would I just copy the directory somewhere else so that directory is empty?

**Comment by ltdrdata** [comment]
> I'm not sure how to do that. Would I just copy the directory somewhere else so that directory is empty?
> 
> Tried to reset with an empty directory for Custom_nodes, still same error.

Move out all sub dirs from ComfyUI/custom_nodes to somewhere else.

**Comment by ApolloForge** [comment]
I moved all the files/folders to another folder outside the ComfyUI structure. I'm still getting the issue

**Comment by ltdrdata** [comment]
> I moved all the files/folders to another folder outside the ComfyUI structure and tried with the cli options. I'm still getting the issue

What it the scipy package version?

**Comment by ApolloForge** [comment]
Scipy version is 1.13.0

**Comment by ltdrdata** [comment]
Uninstall numpy and scipy and reinstall in your activated venv.

```
pip uninstall numpy scipy
pip install numpy==1.26.4 scipy
```
