### ISSUE TITLE
Expected all tensors to be on the same device, but found  at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper CUDAnative layer norm)

### ISSUE THREAD

**Issue by thefirstLeonliao** [comfyanonymous/ComfyUI#5902]
### Expected Behavior

what happen？can you fix it？

### Actual Behavior

<img width="945" alt="d791d7c296ce8d3592cd55919fa00e7" src="https://github.com/user-attachments/assets/71035d29-aab8-4262-bf6c-f02c4f2cf44e">

### Steps to Reproduce

[2024.12.2_FLUX文生图自我优化工作流.json](https://github.com/user-attachments/files/18003845/2024.12.2_FLUX.json)

### Debug Logs

```powershell
# 😺dzNodes: LayerStyle -> ImageRemoveAlpha Processed 1 image(s).
end_vram - start_vram: 3327435264 - 3327435264 = 0
#91 [LayerUtility: ImageRemoveAlpha]: 0.01s - vram 0b
end_vram - start_vram: 3327435264 - 3327435264 = 0
#92 [PreviewImage]: 0.02s - vram 0b
end_vram - start_vram: 3976295936 - 3327435264 = 648860672
#69 [LayerUtility: Florence2Image2Prompt]: 4.51s - vram 648860672b
end_vram - start_vram: 3327435264 - 3327435264 = 0
#72 [ShowText|pysssss]: 0.00s - vram 0b
end_vram - start_vram: 3327435264 - 3327435264 = 0
#73 [PurgeVRAM]: 0.34s - vram 0b
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI-aki-v1.3\models\insightface\models\antelopev2\1k3d68.onnx landmark_3d_68 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI-aki-v1.3\models\insightface\models\antelopev2\2d106det.onnx landmark_2d_106 ['None', 3, 192, 192] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI-aki-v1.3\models\insightface\models\antelopev2\genderage.onnx genderage ['None', 3, 96, 96] 0.0 1.0
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI-aki-v1.3\models\insightface\models\antelopev2\glintr100.onnx recognition ['None', 3, 112, 112] 127.5 127.5
Applied providers: ['CPUExecutionProvider'], with options: {'CPUExecutionProvider': {}}
find model: D:\AI\ComfyUI-aki-v1.3\models\insightface\models\antelopev2\scrfd_10g_bnkps.onnx detection [1, 3, '?', '?'] 127.5 128.0
set det-size: (640, 640)
end_vram - start_vram: 3327435264 - 3327435264 = 0
#25 [PulidFluxInsightFaceLoader]: 1.31s - vram 0b
Loaded EVA02-CLIP-L-14-336 model config.
Shape of rope freq: torch.Size([576, 64])
Loading pretrained EVA02-CLIP-L-14-336 weights (eva_clip).
incompatible_keys.missing_keys: ['visual.rope.freqs_cos', 'visual.rope.freqs_sin', 'visual.blocks.0.attn.rope.freqs_cos', 'visual.blocks.0.attn.rope.freqs_sin', 'visual.blocks.1.attn.rope.freqs_cos', 'visual.blocks.1.attn.rope.freqs_sin', 'visual.blocks.2.attn.rope.freqs_cos', 'visual.blocks.2.attn.rope.freqs_sin', 'visual.blocks.3.attn.rope.freqs_cos', 'visual.blocks.3.attn.rope.freqs_sin', 'visual.blocks.4.attn.rope.freqs_cos', 'visual.blocks.4.attn.rope.freqs_sin', 'visual.blocks.5.attn.rope.freqs_cos', 'visual.blocks.5.attn.rope.freqs_sin', 'visual.blocks.6.attn.rope.freqs_cos', 'visual.blocks.6.attn.rope.freqs_sin', 'visual.blocks.7.attn.rope.freqs_cos', 'visual.blocks.7.attn.rope.freqs_sin', 'visual.blocks.8.attn.rope.freqs_cos', 'visual.blocks.8.attn.rope.freqs_sin', 'visual.blocks.9.attn.rope.freqs_cos', 'visual.blocks.9.attn.rope.freqs_sin', 'visual.blocks.10.attn.rope.freqs_cos', 'visual.blocks.10.attn.rope.freqs_sin', 'visual.blocks.11.attn.rope.freqs_cos', 'visual.blocks.11.attn.rope.freqs_sin', 'visual.blocks.12.attn.rope.freqs_cos', 'visual.blocks.12.attn.rope.freqs_sin', 'visual.blocks.13.attn.rope.freqs_cos', 'visual.blocks.13.attn.rope.freqs_sin', 'visual.blocks.14.attn.rope.freqs_cos', 'visual.blocks.14.attn.rope.freqs_sin', 'visual.blocks.15.attn.rope.freqs_cos', 'visual.blocks.15.attn.rope.freqs_sin', 'visual.blocks.16.attn.rope.freqs_cos', 'visual.blocks.16.attn.rope.freqs_sin', 'visual.blocks.17.attn.rope.freqs_cos', 'visual.blocks.17.attn.rope.freqs_sin', 'visual.blocks.18.attn.rope.freqs_cos', 'visual.blocks.18.attn.rope.freqs_sin', 'visual.blocks.19.attn.rope.freqs_cos', 'visual.blocks.19.attn.rope.freqs_sin', 'visual.blocks.20.attn.rope.freqs_cos', 'visual.blocks.20.attn.rope.freqs_sin', 'visual.blocks.21.attn.rope.freqs_cos', 'visual.blocks.21.attn.rope.freqs_sin', 'visual.blocks.22.attn.rope.freqs_cos', 'visual.blocks.22.attn.rope.freqs_sin', 'visual.blocks.23.attn.rope.freqs_cos', 'visual.blocks.23.attn.rope.freqs_sin']
end_vram - start_vram: 3327435264 - 3327435264 = 0
#24 [PulidFluxEvaClipLoader]: 4.58s - vram 0b
Loading PuLID-Flux model.
end_vram - start_vram: 3327435264 - 3327435264 = 0
#23 [PulidFluxModelLoader]: 2.59s - vram 0b
end_vram - start_vram: 5331323904 - 3327435264 = 2003888640
#26 [ApplyPulidFlux]: 2.92s - vram 2003888640b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#53 [BasicScheduler]: 0.00s - vram 0b
Number of sigmas: 6, Number of schedule steps: 5
Adjusting sigma at index 0 with multiplier 0.0
Adjusting sigma at index 1 with multiplier 0.0
Adjusting sigma at index 2 with multiplier 0.010000000000000002
Adjusting sigma at index 3 with multiplier 0.0
Adjusting sigma at index 4 with multiplier 0.0
end_vram - start_vram: 5080496128 - 5080496128 = 0
#51 [DetailDaemonGraphSigmasNode]: 0.09s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#90 [CR Text]: 0.00s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#89 [JoinStringMulti]: 0.00s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#54 [CLIPTextEncode]: 14.95s - vram 0b
Requested to load CLIPVisionModelProjection
loaded completely 9.5367431640625e+25 787.7150573730469 True
end_vram - start_vram: 5080496128 - 5080496128 = 0
#83 [ReduxAdvanced]: 2.39s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#84 [PreviewImage]: 0.01s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#77 [ReduxAdvanced]: 2.38s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#80 [PreviewImage]: 0.02s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#99 [ControlNetApplyAdvanced]: 0.00s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#45 [FluxGuidance]: 0.00s - vram 0b
end_vram - start_vram: 5080496128 - 5080496128 = 0
#46 [CFGGuider]: 0.00s - vram 0b
Requested to load Flux
Requested to load ControlNetFlux
loaded partially 733.661328125 733.0303344726562 0
loaded partially 64.0 63.998046875 0
Requested to load AutoencodingEngine
0 models unloaded.
loaded completely 9.5367431640625e+25 159.87335777282715 True
Requested to load Flux
Requested to load ControlNetFlux
loaded partially 1497.96455078125 1497.9645385742188 0
loaded partially 64.0 63.998046875 0
!!! Exception during processing !!! Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)
Traceback (most recent call last):
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\AI\ComfyUI-aki-v1.3\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\AI\ComfyUI-aki-v1.3\comfy_extras\nodes_custom_sampler.py", line 633, in sample
    samples = guider.sample(noise.generate_noise(latent), latent_image, sampler, sigmas, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise.seed)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 904, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 873, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 857, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 714, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Detail-Daemon\detail_daemon_node.py", line 297, in detail_daemon_sampler
    return dds_wrapped_sampler.sampler_function(
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\k_diffusion\sampling.py", line 729, in sample_dpmpp_2m
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Detail-Daemon\detail_daemon_node.py", line 289, in model_wrapper
    return model(x, adjusted_sigma, **extra_args)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 384, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 839, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 842, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 364, in sampling_function
    out = calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 200, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\samplers.py", line 313, in _calc_cond_batch
    output = model.apply_model(input_x, timestep_, **c).chunk(batch_chunks)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\model_base.py", line 128, in apply_model
    return comfy.patcher_extension.WrapperExecutor.new_class_executor(
  File "D:\AI\ComfyUI-aki-v1.3\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\model_base.py", line 157, in _apply_model
    model_output = self.diffusion_model(xc, t, context=context, control=control, transformer_options=transformer_options, **extra_conds).float()
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\comfy\ldm\flux\model.py", line 184, in forward
    out = self.forward_orig(img, img_ids, context, txt_ids, timestep, y, guidance, control, transformer_options)
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 136, in forward_orig
    img = img + node_data['weight'] * self.pulid_ca[ca_idx](node_data['embedding'], img)
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\encoders_flux.py", line 52, in forward
    x = self.norm1(x)
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\modules\normalization.py", line 201, in forward
    return F.layer_norm(
  File "D:\AI\ComfyUI-aki-v1.3\python\lib\site-packages\torch\nn\functional.py", line 2573, in layer_norm
    return torch.layer_norm(input, normalized_shape, weight, bias, eps, torch.backends.cudnn.enabled)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument weight in method wrapper_CUDA__native_layer_norm)

end_vram - start_vram: 7056137728 - 5080496128 = 1975641600
#43 [SamplerCustomAdvanced]: 12.59s - vram 1975641600b
```

**Comment by rootliuat** [comment]
一样的问题，有解决方法了吗

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-PuLID-Flux-Enhanced repo.
https://github.com/sipie800/ComfyUI-PuLID-Flux-Enhanced
