### ISSUE TITLE
TypeError: ControlNet.get_control() missing 1 required positional argument: 'transformer_options'

### ISSUE THREAD

**Issue by SushiLibanais** [comfyanonymous/ComfyUI#5918]
### Your question

This workflow's last step is supposed to tile upscale. However, I have been getting this error since monday evening. The workflow was working well until thursday evening (haven't used it over the weekend and I always try to keep my ComfyUI up to date). This issue was also reported in another thread by another user, however it didn't have a dedicated thread.

### Logs

```powershell
!!! Exception during processing !!! ControlNet.get_control() missing 1 required positional argument: 'transformer_options'
Traceback (most recent call last):
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy_extras\nodes_custom_sampler.py", line 476, in sample
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\sample.py", line 48, in sample_custom
    samples = comfy.samplers.sample(model, noise, positive, negative, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 918, in sample
    return cfg_guider.sample(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 904, in sample
    output = executor.execute(noise, latent_image, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 873, in outer_sample
    output = self.inner_sample(noise, latent_image, device, sampler, sigmas, denoise_mask, callback, disable_pbar, seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 857, in inner_sample
    samples = executor.execute(self, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\utils.py", line 34, in KSAMPLER_sample
    return orig_fn(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 714, in sample
    samples = self.sampler_function(model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar, **self.extra_options)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon\detail_daemon_node.py", line 297, in detail_daemon_sampler
    return dds_wrapped_sampler.sampler_function(
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\k_diffusion\sampling.py", line 764, in sample_dpmpp_2m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon\detail_daemon_node.py", line 289, in model_wrapper
    return model(x, adjusted_sigma, **extra_args)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 384, in __call__
    out = self.inner_model(x, sigma, model_options=model_options, seed=seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 839, in __call__
    return self.predict_noise(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 842, in predict_noise
    return sampling_function(self.inner_model, x, timestep, self.conds.get("negative", None), self.conds.get("positive", None), self.cfg, model_options=model_options, seed=seed)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\nodes.py", line 52, in sampling_function_patched
    out = comfy.samplers.calc_cond_batch(model, conds, x, timestep, model_options)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 200, in calc_cond_batch
    return executor.execute(model, conds, x_in, timestep, model_options)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\patcher_extension.py", line 110, in execute
    return self.original(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\comfy\samplers.py", line 311, in _calc_cond_batch
    output = model_options['model_function_wrapper'](model.apply_model, {"input": input_x, "timestep": timestep_, "c": c, "cond_or_uncond": cond_or_uncond}).chunk(batch_chunks)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\StabilityMatrix-win-x64\Data\Packages\ComfyUI\custom_nodes\ComfyUI-TiledDiffusion\tiled_diffusion.py", line 524, in __call__
    c_tile['control'] = c_in['control'].get_control_orig(x_tile, t_tile, c_tile, len(cond_or_uncond))
TypeError: ControlNet.get_control() missing 1 required positional argument: 'transformer_options'
```

### Other

The workflow : [Daily SDXL.json](https://github.com/user-attachments/files/18014454/Daily.SDXL.json)
The error screen : ![image](https://github.com/user-attachments/assets/07a9c51b-3714-4d99-af09-303b88611dbc)

**Comment by shiimizu** [comment]
Update your TiledDiffusion node.

**Comment by SushiLibanais** [comment]
Thanks, it worked!

**Comment by Kwisss** [comment]
why is this fix not working for me?
