### ISSUE TITLE
Python.exe损坏的映像

### ISSUE THREAD

**Issue by YaoXiao-CS** [comfyanonymous/ComfyUI#5940]
### Your question

    import torchaudio
  File "C:\Users\Administrator\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\__init__.py", line 2, in <module>
    from . import _extension  # noqa  # usort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Administrator\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_extension\__init__.py", line 38, in <module>
    _load_lib("libtorchaudio")
  File "C:\Users\Administrator\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchaudio\_extension\utils.py", line 60, in _load_lib
    torch.ops.load_library(path)
  File "C:\Users\Administrator\Desktop\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_ops.py", line 1350, in load_library
    ctypes.CDLL(path)
  File "ctypes\__init__.py", line 379, in __init__
OSError: [WinError 193] %1 不是有效的 Win32 应用程序。

Cannot import C:\Users\Administrator\Desktop\ComfyUI_windows_portable\ComfyUI\comfy_extras\nodes_audio.py module for custom nodes: [WinError 193] %1 不是有效的 Win32 应用程序。
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2037, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
![微信截图_20241206110201](https://github.com/user-attachments/assets/eeb95947-9322-4001-b15f-fa4cda921655)

**Comment by YaoXiao-CS** [comment]
**I tried using the DLL repair tool, but there was no error message.**
