### ISSUE TITLE
MochiTextEncode not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by eSiiner** [comfyanonymous/ComfyUI#5950]
### Your question

I'm no big tech guy, if you have a solution or assistance to the following error, as I was using MochiTextEncode, explain it to me like I'm a baby.

### Logs

```powershell
!!! Exception during processing !!! not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 446, in process
    clip.tokenizer.t5xxl.pad_to_max_length = True
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: 'SD1Tokenizer' object has no attribute 't5xxl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 324, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 199, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 170, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 159, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 460, in process
    embeds, _, attention_mask = clip.cond_stage_model.encode_token_weights(tokens)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)

Prompt executed in 0.25 seconds
got prompt
!!! Exception during processing !!! not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "C:\Users\User1\Desktop\Comfy\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MochiWrapper\nodes.py", line 446, in process
    clip.tokenizer.t5xxl.pad_to_max_length = True
    ^^^^^^^^^^^^^^^^^^^^
```

**Comment by ltdrdata** [comment]
What is your workflow?
