### ISSUE TITLE
Help : Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.

### ISSUE THREAD

**Issue by ChaChrist25** [comfyanonymous/ComfyUI#5976]
### Your question

I am trying to run the ComfyUI program on my Windows machine, but I encountered an error message stating as shown below:

**Debug Logs :**
```
F:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-09 14:00:50.884833
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: F:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\ComfyUI_windows_portable\ComfyUI
** Log path: F:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   1.9 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6140 MB, total RAM 32488 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints path/to/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae path/to/stable-diffusion-webui/models/VAE
Adding extra search path loras path/to/stable-diffusion-webui/models/Lora
Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet path/to/stable-diffusion-webui/models/ControlNet
### Loading: ComfyUI-Impact-Pack (V7.14)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.7-7-g6579632 | Released on '2024-12-08'
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

Cannot import F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
------------------------------------------[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json

Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json

[rgthree-comfy] Loaded 42 epic nodes. 🎉


Import times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\example_node.py
   0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.2 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.4 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.9 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
BilboX LUTs path set to: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
got prompt
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
Using pytorch attention in VAE
Using pytorch attention in VAE

F:\ComfyUI_windows_portable>pause
```

**Comment by 925-Studio** [comment]
I'm facing the similar problem with ReActor.

```bash
loaded completely 9.5367431640625e+25 4897.0483474731445 True
100%|███████████████████████████████████████████████████████████████████| 32/32 [00:26<00:00,  1.19it/s]
Requested to load AutoencoderKL
loaded completely 9.5367431640625e+25 159.55708122253418 True
[ReActor] 00:39:29 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 00:39:29 - STATUS - Analyzing Source Image...
[ReActor] 00:39:31 - STATUS - Analyzing Target Image...
[ReActor] 00:39:31 - STATUS - Source Face 0: Detected Gender -F-
[ReActor] 00:39:31 - STATUS - OK - Detected Gender matches Condition
[ReActor] 00:39:32 - STATUS - Target Face 0: Detected Gender -F-
[ReActor] 00:39:32 - STATUS - OK - Detected Gender matches Condition
[ReActor] 00:39:32 - STATUS - Swapping...
[ReActor] 00:39:32 - STATUS - Face Boost is enabled
[ReActor] 00:39:33 - STATUS - Boosting the Face with GPEN-BFR-1024.onnx | Face Size is set to 1024 with Scale Factor = 8.0 and 'Lanczos' interpolation
[ReActor] 00:39:34 - STATUS - --Done!--
[ReActor] 00:39:34 - STATUS - Restoring with GFPGANv1.4.pth | Face Size is set to 512
Warning torch.load doesn't support weights_only on this pytorch version, loading unsafely.
	Failed inference: Allocation on device 
```

But somehow it works on the second queue (just hit the 'Queue' button again). Very annoying I have to say. I'm not sure it's because the ComfyUI or ReActor, or both.

**Comment by ltdrdata** [comment]
Just to share some information for the developers, there was the same issue when importing Ultralytics' YOLO in the Impact Subpack, so measures have been taken to bypass it. 

If such measures have not been implemented in other custom nodes that import YOLO, the same issue will occur.

https://github.com/ltdrdata/ComfyUI-Impact-Subpack/commit/bd4dedc4ea514dda9cfa333a0f42e296e32b8c10
https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/754

**Comment by ChaChrist25** [comment]
> Just to share some information for the developers, there was the same issue when importing Ultralytics' YOLO in the Impact Subpack, so measures have been taken to bypass it.
> 
> If such measures have not been implemented in other custom nodes that import YOLO (or similar thing), the same issue will occur.
> 
> [ltdrdata/ComfyUI-Impact-Subpack@bd4dedc](https://github.com/ltdrdata/ComfyUI-Impact-Subpack/commit/bd4dedc4ea514dda9cfa333a0f42e296e32b8c10) [ltdrdata/ComfyUI-Impact-Pack#754](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/754)

**I already try that ways. But it still can't work for me.
It's still 27% then reconnect.**
```
F:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-13 11:49:59.352987
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: F:\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\ComfyUI_windows_portable\ComfyUI
** Log path: F:\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   2.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 6140 MB, total RAM 32488 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints path/to/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
Adding extra search path vae path/to/stable-diffusion-webui/models/VAE
Adding extra search path loras path/to/stable-diffusion-webui/models/Lora
Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
Adding extra search path controlnet path/to/stable-diffusion-webui/models/ControlNet
### Loading: ComfyUI-Impact-Pack (V7.14)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.7-7-g6579632 | Released on '2024-12-08'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ReActor] - STATUS - Running v0.5.2-a1 in ComfyUI
Torch version: 2.5.1+cu124
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------

[rgthree-comfy] Loaded 42 magnificent nodes. 🎉


Import times for custom nodes:
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\example_node.py
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.4 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.7 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
   0.9 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
BilboX LUTs path set to: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
BilboX LUTs path set to: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE

F:\ComfyUI_windows_portable>pause
Press any key to continue . . .
```
![Screenshot 2024-12-13 115422](https://github.com/user-attachments/assets/9b7d94d7-1100-4dab-89ee-fce7fbccfaff)

**Comment by ltdrdata** [comment]
> > Just to share some information for the developers, there was the same issue when importing Ultralytics' YOLO in the Impact Subpack, so measures have been taken to bypass it.
> > If such measures have not been implemented in other custom nodes that import YOLO (or similar thing), the same issue will occur.
> > [ltdrdata/ComfyUI-Impact-Subpack@bd4dedc](https://github.com/ltdrdata/ComfyUI-Impact-Subpack/commit/bd4dedc4ea514dda9cfa333a0f42e296e32b8c10) [ltdrdata/ComfyUI-Impact-Pack#754](https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/754)
> 
> **I already try that ways. But it still can't work for me. It's still 27% then reconnect.**
> 
> ```
> F:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
> [START] Security scan
> [DONE] Security scan
> ## ComfyUI-Manager: installing dependencies done.
> ** ComfyUI startup time: 2024-12-13 11:49:59.352987
> ** Platform: Windows
> ** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
> ** Python executable: F:\ComfyUI_windows_portable\python_embeded\python.exe
> ** ComfyUI Path: F:\ComfyUI_windows_portable\ComfyUI
> ** Log path: F:\ComfyUI_windows_portable\comfyui.log
> 
> Prestartup times for custom nodes:
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
>    2.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
> 
> Total VRAM 6140 MB, total RAM 32488 MB
> pytorch version: 2.5.1+cu124
> Set vram state to: NORMAL_VRAM
> Device: cuda:0 NVIDIA GeForce RTX 4050 Laptop GPU : cudaMallocAsync
> Using pytorch cross attention
> [Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
> Adding extra search path checkpoints path/to/stable-diffusion-webui/models/Stable-diffusion
> Adding extra search path configs path/to/stable-diffusion-webui/models/Stable-diffusion
> Adding extra search path vae path/to/stable-diffusion-webui/models/VAE
> Adding extra search path loras path/to/stable-diffusion-webui/models/Lora
> Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
> Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
> Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
> Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
> Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
> Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
> Adding extra search path controlnet path/to/stable-diffusion-webui/models/ControlNet
> ### Loading: ComfyUI-Impact-Pack (V7.14)
> ### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
> [Impact Pack] Wildcards loading done.
> ### Loading: ComfyUI-Manager (V2.55.4)
> ### ComfyUI Version: v0.3.7-7-g6579632 | Released on '2024-12-08'
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
> [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
> [ReActor] - STATUS - Running v0.5.2-a1 in ComfyUI
> Torch version: 2.5.1+cu124
> ------------------------------------------
> Comfyroll Studio v1.76 :  175 Nodes Loaded
> ------------------------------------------
> ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
> ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
> ------------------------------------------
> 
> [rgthree-comfy] Loaded 42 magnificent nodes. 🎉
> 
> 
> Import times for custom nodes:
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\example_node.py
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
>    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
>    0.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
>    0.4 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
>    0.7 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node
>    0.9 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui
> 
> Starting server
> 
> To see the GUI go to: http://127.0.0.1:8188
> FETCH DATA from: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
> BilboX LUTs path set to: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
> BilboX LUTs path set to: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\bilbox-comfyui\luts
> got prompt
> Using pytorch attention in VAE
> Using pytorch attention in VAE
> 
> F:\ComfyUI_windows_portable>pause
> Press any key to continue . . .
> ```
> 
> ![Screenshot 2024-12-13 115422](https://private-user-images.githubusercontent.com/191087232/395433956-9b7d94d7-1100-4dab-89ee-fce7fbccfaff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNzcwOTcsIm5iZiI6MTczNDI3Njc5NywicGF0aCI6Ii8xOTEwODcyMzIvMzk1NDMzOTU2LTliN2Q5NGQ3LTExMDAtNGRhYi04OWVlLWZjZTdmYmNjZmFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQxNTMzMTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTNiMjJjMzE0NzQzNWJiMWUyMGQ0OTM2NzkwZmRlODY0NzY2YzY4Yzg3ZDM4NGFmZTA5YWQzZDI4YmZjYWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wJ9CifQ84sKClEBS7uk8CkvUqcVpNYjpHjLofF3b_rA)

The issue I shared is the `Warning: torch.load doesn't support weights_only on this PyTorch version, loading unsafely.` warning, and it is not an issue where the program crashes.

It is either due to the OS force-closing the program because of insufficient system RAM or an error occurring in the native code.
