### ISSUE TITLE
Suddenly unable to load certain safetensors

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#600]
Suddenly, like half my Safetensors are throwing this error:

```
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 182, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 220, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 868, in load_checkpoint_guess_config
    sd = utils.load_torch_file(ckpt_path)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 6, in load_torch_file
    sd = safetensors.torch.load_file(ckpt, device="cpu")
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\safetensors\torch.py", line 99, in load_file
    with safe_open(filename, framework="pt", device=device) as f:
safetensors_rust.SafetensorError: Error while deserializing header: HeaderTooSmall
```

What... like happened here?

**Comment by WASasquatch** [comment]
Oh, nevermind... my external harddrive has died. ALL the models on my external have 0 bytes, and files can't be deleted/moved. Sector has gone bad. :( Well that's unfortunate and 5tb of resources gone. Oof.

**Comment by comfyanonymous** [comment]
I recommend you take a look at ddrescue and TestDisk. That's what I usually use to recover files from dying hard drives.

**Comment by WASasquatch** [comment]
> I recommend you take a look at ddrescue and TestDisk. That's what I usually use to recover files from dying hard drives.

Thanks a lot! Looks like I can recover some of the loss, though going to take awhile.
