### ISSUE TITLE
When using LTX for image-to-video generation, the video is completely unrelated to the image, and here's a strange workaround.

### ISSUE THREAD

**Issue by judian17** [comfyanonymous/ComfyUI#6001]
### Expected Behavior

When I use the nodes from ltxtricks for image-to-video generation, the video is completely unrelated to the image (the same issue occurs with the official nodes from comfyui). 

### Actual Behavior

Interestingly, after performing a reverse sampling using ltxtricks (only generating latent, without needing to be related to the image-to-video workflow, and it can even be run in a completely new browser interface of comfyui), the image-to-video generation works perfectly without changing any parameters.

### Steps to Reproduce

[i2vdebug.json](https://github.com/user-attachments/files/18081588/i2vdebug.json)

### Debug Logs

```powershell
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
FETCH DATA from: E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
E:\comfyui\ComfyUI-aki-v1.3\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: E:\comfyui\ComfyUI-aki-v1.3

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: E:\comfyui\ComfyUI-aki-v1.3

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: E:\comfyui\ComfyUI-aki-v1.3

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: E:\comfyui\ComfyUI-aki-v1.3

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: E:\comfyui\ComfyUI-aki-v1.3

Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: E:\comfyui\ComfyUI-aki-v1.3

HTTP Request: GET http://127.0.0.1:11434/api/tags "HTTP/1.1 200 OK"
Error handling request
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
  File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp>", line 140, in sentry_app_handle
  File "<enhanced_experience vendors.sentry_sdk.utils>", line 1649, in reraise
  File "<enhanced_experience vendors.sentry_sdk.integrations.aiohttp>", line 130, in sentry_app_handle
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_app.py", line 569, in _handle
    return await handler(request)
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "E:\comfyui\ComfyUI-aki-v1.3\server.py", line 62, in cache_control
    response: web.Response = await handler(request)
  File "E:\comfyui\ComfyUI-aki-v1.3\server.py", line 140, in origin_only_middleware
    response = await handler(request)
  File "<enhanced_experience patches.comfyui.html_resources_patcher>", line 26, in http_resource_injector
  File "E:\comfyui\ComfyUI-aki-v1.3\server.py", line 74, in cors_middleware
    response = await handler(request)
  File "E:\comfyui\ComfyUI-aki-v1.3\server.py", line 384, in view_image
    if filename[0] == '/' or '..' in filename:
IndexError: string index out of range
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
got prompt
model weight dtype torch.bfloat16, manual cast: None
model_type FLUX
no CLIP/text encoder weights in checkpoint, the text encoder model will not be loaded.
Requested to load VideoVAE
loaded completely 9.5367431640625e+25 799.548433303833 True
Requested to load MochiTEModel_
loaded completely 9.5367431640625e+25 9083.38671875 True
Requested to load LTXV
loaded completely 9.5367431640625e+25 3667.902587890625 True
Requested to load VideoVAE
loaded completely 9.5367431640625e+25 799.548433303833 True
Prompt executed in 59.24 seconds
got prompt
Requested to load VideoVAE
loaded completely 9.5367431640625e+25 799.548433303833 True
Requested to load MochiTEModel_
loaded completely 9.5367431640625e+25 9083.38671875 True
Requested to load LTXV
loaded completely 9.5367431640625e+25 3667.902587890625 True
Requested to load VideoVAE
loaded completely 9.5367431640625e+25 799.548433303833 True
Prompt executed in 13.16 seconds
got prompt
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "E:\comfyui\ComfyUI-aki-v1.3\python\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。
Requested to load VideoVAE
loaded completely 9.5367431640625e+25 799.548433303833 True
Requested to load MochiTEModel_
loaded completely 9.5367431640625e+25 9083.38671875 True
Requested to load LTXV
loaded completely 9.5367431640625e+25 3667.902587890625 True
Requested to load VideoVAE
loaded completely 9.5367431640625e+25 799.548433303833 True
Prompt executed in 29.14 seconds
got prompt
Prompt executed in 6.80 seconds
```

**Comment by cheezecrisp** [comment]
Update ltxtricks, it was solved already.
