### ISSUE TITLE
Can't open ComfyUI - FileNotFoundError

### ISSUE THREAD

**Issue by Vektor369** [comfyanonymous/ComfyUI#6002]
### Your question

AnimateDiff-Evolved apparently had to have the absolute latest version of ComfyUI, so I updated. Now ComfyUI won't even open. (Incidently, this is why I make it a point to never ever ever never ever update unless absolutely necessary.) Everything worked fine before, and I didn't have any problems.

I'm using the portable version.

There's a **bunch** of crap in the console, so before I post that, I'll just point out something I noticed. At several points it says, "The system cannot find the path specified:" and lists a file path. However, the file path it specifies lists the "ComfyUI" directory twice. For example, instead of:
F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\tests\\inference\\testing_nodes
it lists:
F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes
So, I'm pretty sure that's the problem. I just have no idea how to fix it.

Thanks in advance for any help.

Okay, so here's the console dump:
```
F:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-10 12:18:08.630938
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: F:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: F:\AI\ComfyUI_windows_portable\ComfyUI
** Log path: F:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   2.5 seconds: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 32648 MB
pytorch version: 2.4.1+cu124
F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:211: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_fwd")
F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\xformers\ops\fmha\flash.py:344: FutureWarning: `torch.library.impl_abstract` was renamed to `torch.library.register_fake`. Please use that instead; we will remove `torch.library.impl_abstract` in a future version of PyTorch.
  @torch.library.impl_abstract("xformers_flash::flash_bwd")
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: F:\AI\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path custom_nodes F:\AI\ComfyUI_windows_portable\ComfyUI\ComfyUI\tests\inference\testing_nodes
Adding extra search path checkpoints F:\AI\Forge\webui\models/Stable-diffusion
Adding extra search path clip F:\AI\Forge\webui\models/text_encoder
Adding extra search path clip_vision F:\AI\Forge\webui\models/ControlNetPreprocessor
Adding extra search path configs F:\AI\Forge\webui\models/Stable-diffusion
Adding extra search path vae F:\AI\Forge\webui\models/VAE
Adding extra search path loras F:\AI\Forge\webui\models/Lora
Adding extra search path diffusion_models F:\AI\Forge\webui\models\Stable-diffusion\Flux
Adding extra search path upscale_models F:\AI\Forge\webui\models/ESRGAN
Adding extra search path upscale_models F:\AI\Forge\webui\models/RealESRGAN
Adding extra search path upscale_models F:\AI\Forge\webui\models/SwinIR
Adding extra search path embeddings F:\AI\Forge\webui\embeddings
Adding extra search path hypernetworks F:\AI\Forge\webui\models/hypernetworks
Adding extra search path controlnet F:\AI\Forge\webui\models/ControlNet
F:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Web extensions folder found at F:\AI\ComfyUI_windows_portable\ComfyUI\web\extensions\ComfyLiterals
Adding F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Adding F:\AI\ComfyUI_windows_portable\ComfyUI\ComfyUI\tests\inference\testing_nodes to sys.path
[WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
[WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
[WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
[WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
[WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
[WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
Could not load ImpactPack nodes [WinError 3] The system cannot find the path specified: 'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'
[Crystools ←[0;32mINFO←[0m] Crystools version: 1.21.0
[Crystools ←[0;32mINFO←[0m] CPU: 11th Gen Intel(R) Core(TM) i7-11700KF @ 3.60GHz - Arch: AMD64 - OS: Windows 10
[Crystools ←[0;32mINFO←[0m] Pynvml (Nvidia) initialized.
[Crystools ←[0;32mINFO←[0m] GPU/s:
[Crystools ←[0;32mINFO←[0m] 0) NVIDIA GeForce RTX 3070
[Crystools ←[0;32mINFO←[0m] NVIDIA Driver: 560.94

🌊 DEPTHFLOW NODES 🌊

[ComfyUI-Easy-Use] server: v1.2.3 Loaded
[ComfyUI-Easy-Use] web root: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
### Loading: ComfyUI-Impact-Pack (V7.8)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Inspire-Pack (V1.3)
Total VRAM 8192 MB, total RAM 32648 MB
pytorch version: 2.4.1+cu124
xformers version: 0.0.27.post2
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 : cudaMallocAsync
@@device:cuda
@@device:cuda
Please install pyav to use video processing functions.
theUpsiders Logic Nodes: Loaded
Initializing EasyNodes. Auto-registration: True
### Loading: ComfyUI-Manager (V2.50.3)
### ComfyUI Revision: 2901 [a220d11e] | Released on '2024-12-09'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
--------------
←[91m ### Mixlab Nodes: ←[93mLoaded
json_repair## OK
ChatGPT.available True
edit_mask.available True
## clip_interrogator_model not found: F:\AI\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
ClipInterrogator.available True
## text_generator_model not found: F:\AI\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
## zh_en_model not found: F:\AI\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
PromptGenerate.available True
ChinesePrompt.available True
RembgNode_.available True
TripoSR.available
MiniCPMNode.available
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Scenedetect.available
FishSpeech.available
SenseVoice.available
Whisper.available False
fal-client## OK
FalVideo.available
←[93m -------------- ←[0m
Nvidia APEX normalization not installed, using PyTorch LayerNorm
Please install flash attention
[ReActor] - STATUS - Running v0.5.1-b2 in ComfyUI
Torch version: 2.4.1+cu124
F:\AI\ComfyUI_windows_portable
############################################
F:\AI\ComfyUI_windows_portable\custom_nodes\ComfyUI-NAI-styler\CSV
############################################
[]
############################################
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[comfyui_controlnet_aux] | INFO -> Using ckpts path: F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
FizzleDorf Custom Nodes: Loaded
Traceback (most recent call last):
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter\__init__.py", line 1, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter\nodes.py", line 11, in <module>
    from .utils.model_utils import DynamiCrafterBase, DYNAMICRAFTER_CONFIG, \
  File "F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter\utils\model_utils.py", line 9, in <module>
    from comfy import sd2_clip
ImportError: cannot import name 'sd2_clip' from 'comfy' (unknown location)

Cannot import F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Native_DynamiCrafter module for custom nodes: cannot import name 'sd2_clip' from 'comfy' (unknown location)
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree] Loaded 42 extraordinary nodes.
[rgthree] NOTE: Will NOT use rgthree's optimized recursive execution as ComfyUI has changed.

Please 'pip install apex'
Searge-SDXL v4.3.1 in F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `F:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 218 nodes successfully.

        "Art is the breath of life." - Liza Donnelly

┌───────────────────────────────────────── Traceback (most recent call last) ─────────────────────────────────────────┐
│ F:\AI\ComfyUI_windows_portable\ComfyUI\main.py:219 in <module>                                                      │
│                                                                                                                     │
│   216 │   │   for config_path in itertools.chain(*args.extra_model_paths_config):                                   │
│   217 │   │   │   utils.extra_config.load_extra_path_config(config_path)                                            │
│   218 │                                                                                                             │
│ > 219 │   nodes.init_extra_nodes(init_custom_nodes=not args.disable_all_custom_nodes)                               │
│   220 │                                                                                                             │
│   221 │   cuda_malloc_warning()                                                                                     │
│   222                                                                                                               │
│                                                                                                                     │
│ F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py:2166 in init_extra_nodes                                            │
│                                                                                                                     │
│   2163 │   import_failed = init_builtin_extra_nodes()                                                               │
│   2164 │                                                                                                            │
│   2165 │   if init_custom_nodes:                                                                                    │
│ > 2166 │   │   init_external_custom_nodes()                                                                         │
│   2167 │   else:                                                                                                    │
│   2168 │   │   logging.info("Skipping loading of custom nodes")                                                     │
│   2169                                                                                                              │
│                                                                                                                     │
│ F:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py:2072 in init_external_custom_nodes                                  │
│                                                                                                                     │
│   2069 │   node_paths = folder_paths.get_folder_paths("custom_nodes")                                               │
│   2070 │   node_import_times = []                                                                                   │
│   2071 │   for custom_node_path in node_paths:                                                                      │
│ > 2072 │   │   possible_modules = os.listdir(os.path.realpath(custom_node_path))                                    │
│   2073 │   │   if "__pycache__" in possible_modules:                                                                │
│   2074 │   │   │   possible_modules.remove("__pycache__")                                                           │
│   2075                                                                                                              │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
FileNotFoundError: [WinError 3] The system cannot find the path specified:
'F:\\AI\\ComfyUI_windows_portable\\ComfyUI\\ComfyUI\\tests\\inference\\testing_nodes'

F:\AI\ComfyUI_windows_portable>pause
Press any key to continue . . .
```

**Comment by ltdrdata** [comment]
Why do you have `F:\AI\ComfyUI_windows_portable\ComfyUI\ComfyUI` dir? Remove that.
