### ISSUE TITLE
(LoRA Hook Issue) calculate_weight_patched() got an unexpected keyword argument 'original_weights'

### ISSUE THREAD

**Issue by formulake** [comfyanonymous/ComfyUI#6013]
### Your question

I get this error while running the lorahookmasking workflow from the comfyui blog post. I'm using SD 1.5 checkpoints an SD 1.5 LoRA, since the original workflow uses those. The workflow runs fine on a fresh install butnce I've loaded some nodes (only from the Manager). Are there dependencies that these nodes need that are potentially being up/downgraded by other nodes? In which case, could someone point out what they are and how I can resolve this, please?

### Logs

```powershell
!!! Exception during processing !!! calculate_weight_patched() got an unexpected keyword argument 'original_weights'
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\nodes.py", line 67, in encode
    return (clip.encode_from_tokens_scheduled(tokens), )
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\comfy\sd.py", line 143, in encode_from_tokens_scheduled
    pooled_dict = self.encode_from_tokens(tokens, return_pooled=return_pooled, return_dict=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\comfy\sd.py", line 204, in encode_from_tokens
    self.load_model()
  File "F:\ComfyUI\comfy\sd.py", line 237, in load_model
    model_management.load_model_gpu(self.patcher)
  File "F:\ComfyUI\comfy\model_management.py", line 520, in load_model_gpu
    return load_models_gpu([model])
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\comfy\model_management.py", line 515, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory, force_patch_weights=force_patch_weights)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\comfy\model_management.py", line 334, in model_load
    self.model_use_more_vram(use_more_vram, force_patch_weights=force_patch_weights)
  File "F:\ComfyUI\comfy\model_management.py", line 363, in model_use_more_vram
    return self.model.partially_load(self.device, extra_memory, force_patch_weights=force_patch_weights)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI\comfy\model_patcher.py", line 759, in partially_load
    raise e
  File "F:\ComfyUI\comfy\model_patcher.py", line 756, in partially_load
    self.load(device_to, lowvram_model_memory=current_used + extra_memory, force_patch_weights=force_patch_weights, full_load=full_load)
  File "F:\ComfyUI\comfy\model_patcher.py", line 627, in load
    self.apply_hooks(self.forced_hooks, force_apply=True)
  File "F:\ComfyUI\comfy\model_patcher.py", line 1012, in apply_hooks
    self.patch_hooks(hooks=hooks)
  File "F:\ComfyUI\comfy\model_patcher.py", line 1044, in patch_hooks
    self.patch_hook_weight_to_device(hooks=hooks, combined_patches=relevant_patches, key=key, original_weights=original_weights,
  File "F:\ComfyUI\comfy\model_patcher.py", line 1081, in patch_hook_weight_to_device
    out_weight = comfy.lora.calculate_weight(combined_patches[key],
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: calculate_weight_patched() got an unexpected keyword argument 'original_weights'
```

**Comment by yoland68** [comment]
Can you add your version information here?

**Comment by formulake** [comment]
Here's a screengrab of the version and system info
![image](https://github.com/user-attachments/assets/756a2acb-bb27-4224-961f-bfaee1820f38)

**Comment by ltdrdata** [comment]
The current code structure has completely changed, so this issue is no longer valid.
