### ISSUE TITLE
!!! Exception during processing !!! 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by YangJunJun666** [comfyanonymous/ComfyUI#6015]
### Your question

[ReActor] 23:30:00 - STATUS - Working: source face index [0], target face index [0]
[ReActor] 23:30:00 - STATUS - Using Hashed Source Face(s) Model...
[ReActor] 23:30:00 - STATUS - Analyzing Target Image 0...
[ReActor] 23:30:00 - STATUS - Analyzing Target Image 1...
[ReActor] 23:30:00 - STATUS - Analyzing Target Image 2...
[ReActor] 23:30:00 - STATUS - Analyzing Target Image 3...
[ReActor] 23:30:00 - STATUS - Swapping 0...
!!! Exception during processing !!! 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "F:\ComfyUI-Aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-Aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\ComfyUI-Aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI-Aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node\nodes.py", line 444, in execute
    result = reactor.execute(
  File "F:\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node\nodes.py", line 353, in execute
    script.process(
  File "F:\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node\scripts\reactor_faceswap.py", line 138, in process
    result = swap_face_many(
  File "F:\ComfyUI-aki-v1.4\custom_nodes\comfyui-reactor-node\scripts\reactor_swapper.py", line 551, in swap_face_many
    result = face_swapper.get(target_img, target_face_single, source_face)
AttributeError: 'NoneType' object has no attribute 'get'

![屏幕截图 2024-12-11 233654](https://github.com/user-attachments/assets/41e498f9-8813-4b8c-a57e-0b00d721b9f7)

**Comment by LukeG89** [comment]
Check this Troubleshooting section from [comfyui-reactor-node](https://github.com/Gourieff/comfyui-reactor-node) repository:
[II. "AttributeError: 'NoneType' object has no attribute 'get'"](https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#ii-attributeerror-nonetype-object-has-no-attribute-get)

**Comment by YangJunJun666** [comment]
thank LukeG89

**Comment by xdx97** [comment]
大佬，是怎么解决的呀，我是本来正常的不知道为啥预览图像节点就报这个错误了
