### ISSUE TITLE
"Search Nodes" typing lag issue

### ISSUE THREAD

**Issue by Amazon90** [comfyanonymous/ComfyUI#6022]
### Expected Behavior

Please fix the lag issue in the "Search Nodes" feature.

### Actual Behavior

After double-clicking the left mouse button, when typing the first letter in the "Search Nodes" interface, there is no lag. However, from the second letter onwards, there is a noticeable delay, and it takes a long time to respond.
![1](https://github.com/user-attachments/assets/4d002c11-c16e-4c44-9c17-982dfb44e0a3)

### Steps to Reproduce

This issue occurred on December 10, 2024. I thought others might have reported it, but it has persisted for three days now.

### Debug Logs

```powershell
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-12 13:37:08.454357
** Platform: Windows
** Python version: 3.12.8 (tags/v3.12.8:2dc476b, Dec  3 2024, 19:30:04) [MSC v.1942 64 bit (AMD64)]
** Python executable: D:\ComfyUI\venv\Scripts\Python.exe
** ComfyUI Path: D:\ComfyUI
** Log path: D:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
  11.3 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 16106 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
Using xformers cross attention
[Prompt Server] web root: D:\ComfyUI\web
generated new fontManager
D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\translate.py:188: SyntaxWarning: invalid escape sequence '\s'
  grammar = """
D:\ComfyUI\venv\Lib\site-packages\bitsandbytes\cextension.py:48: SyntaxWarning: invalid escape sequence '\d'
  library_name = re.sub("cuda\d+", f"cuda{override_value}", library_name, count=1)
D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\libs\wildcards.py:171: SyntaxWarning: invalid escape sequence '\+'
  subpattern = keyword.replace('*', '.*').replace('+','\+')
D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use\py\logic.py:1731: SyntaxWarning: invalid escape sequence '\o'
  if output_path.endswith("ComfyUI/output") or output_path.endswith("ComfyUI\output"):
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 2035, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\__init__.py", line 9, in <module>
    from .nodes.rf_edit_sampler_nodes import FlowEditForwardSamplerNode, FlowEditReverseSamplerNode, PrepareAttnBankNode, RFSingleBlocksOverrideNode, RFDoubleBlocksOverrideNode
  File "D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz\nodes\rf_edit_sampler_nodes.py", line 7, in <module>
    from ..utils.const import DEFAULT_DOUBLE_LAYERS, DEFAULT_SINGLE_LAYERS
ModuleNotFoundError: No module named 'ComfyUI-Fluxtapoz.utils.const'

Cannot import D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz module for custom nodes: No module named 'ComfyUI-Fluxtapoz.utils.const'
### Loading: ComfyUI-Impact-Pack (V8.0.1)
[Impact Pack] Wildcards loading done.
Total VRAM 12282 MB, total RAM 16106 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.7-18-g3dfdddcc | Released on '2024-12-11'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
Nvidia APEX normalization not installed, using PyTorch LayerNorm
[ReActor] - STATUS - Running v0.5.2-a1 in ComfyUI
Torch version: 2.5.1+cu124
[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree-comfy] Loaded 42 fantastic nodes. 🎉

Please 'pip install apex'

Import times for custom nodes:
   0.0 seconds: D:\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
   0.0 seconds: D:\ComfyUI\custom_nodes\cg-use-everywhere
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Detail-Daemon
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_AdvancedRefluxControl
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-InstantX-IPAdapter-SD3
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_InstantID
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-IPAdapter-Flux
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
   0.0 seconds: D:\ComfyUI\custom_nodes\ComfyUI-GGUF
   0.1 seconds: D:\ComfyUI\custom_nodes\rgthree-comfy
   0.1 seconds: D:\ComfyUI\custom_nodes\SDXL_EcomID_ComfyUI
   0.1 seconds: D:\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: D:\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.1 seconds: D:\ComfyUI\custom_nodes\PuLID_ComfyUI
   0.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance
   0.2 seconds: D:\ComfyUI\custom_nodes\comfyui_face_parsing
   0.2 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI-Fluxtapoz
   0.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.3 seconds: D:\ComfyUI\custom_nodes\comfyui-reactor-node
   0.4 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Manager
   1.8 seconds: D:\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   1.9 seconds: D:\ComfyUI\custom_nodes\ComfyUI_LayerStyle
   1.9 seconds: D:\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
   4.2 seconds: D:\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
FETCH DATA from: D:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

**Comment by LaoliAI** [comment]
该问题还在，希望尽快修复

**Comment by kk8bit** [comment]
same problem

**Comment by 15053285989** [comment]
same here

**Comment by q7793527** [comment]
I have the same problem. I thought it was something wrong with my portable bag. But I pulled a new bag today and the problem still exists. I hope it can be fixed as soon as possible.

**Comment by clownvary** [comment]
> I have the same problem. I thought it was something wrong with my portable bag. But I pulled a new bag today and the problem still exists. I hope it can be fixed as soon as possible.

yes, i roll back some old version issue still exist

**Comment by LukeG89** [comment]
@Amazon90 @LaoliAI @kk8bit @15053285989 @q7793527 @clownvary 
Maybe you all have an extension that is causing the issue, because I don't experience any delay.
You can try disabling all your nodes with this command argument: `--disable-all-custom-nodes`

But I would try disabling one by one the following nodes to see if the problem goes away:
- ComfyUI-Easy-Use
- AIGODLIKE-COMFYUI-TRANSLATION
- cg-use-everywhere

**Comment by huchenlei** [comment]
The frontend code is not updated recently, so probably be custom node issue.

**Comment by Amazon90** [comment]
https://github.com/AIGODLIKE/AIGODLIKE-ComfyUI-Translation/issues/310

Uninstall interface multilingual translation node.

**Comment by robinztc** [comment]
roll back AIGODLIKE-COMFYUI-TRANSLATION version worked for me

**Comment by q7793527** [comment]
> @Amazon90 @LaoliAI @kk8bit @15053285989 @q7793527 @clownvary Maybe you all have an extension that is causing the problem, as I'm not experiencing any lag. You can try disabling all nodes using this command parameter: `--disable-all-custom-nodes`
>
> But I will try disabling the following nodes one by one and see if the problem goes away:
>
> * ComfyUI - easy to use
> * AIGODLIKE-COMFYUI-Translation
> * CG-used-everywhere

It is indeed a problem with the interface translation plug-in. I tried to ask GPT to help me modify the source code, but it still cannot be solved. Is there any good way?

**Comment by kk8bit** [comment]
@Amazon90 @clownvary @huchenlei @robinztc 

I resolved this issue by rolling back the custom node "AIGODLIKE-COMFYUI-Translation." It’s a straightforward process:

1. Navigate to `ComfyUI/custom_nodes/AIGODLIKE-COMFYUI-Translation`
2. Open a CMD/terminal based in that folder
3. Enter the following commands:
*This command rolls back to the previous version*
```
 git reset --hard HEAD~1 
  ```
or
*This command rolls back to the version before the last two*
```
git reset --hard HEAD~2
```
5. Restart ComfyUI. This should fix the problem
