### ISSUE TITLE
API calls are broken: ValueError: Host '127.0.0.1:8188' cannot contain ':'

### ISSUE THREAD

**Issue by chinchaun** [comfyanonymous/ComfyUI#6038]
### Expected Behavior

The last version that this was working without any problem was:
Loading: ComfyUI-Manager (V2.55.4)
ComfyUI Version: v0.3.7-16-g5bea1d2 | Released on.

### Actual Behavior

Loading: ComfyUI-Manager (V2.55.4)
ComfyUI Version: v0.3.7-19-gfd5dfb8 | Released on '2024-12-12'

500: Error handling request

### Steps to Reproduce

The environment was the same when it was working and with the new version the problem started:
ComfyUI is running inside a container behind a proxy

trying to make any request the error is the same even if it's a GET or a POST

```
python main.py --listen 0.0.0.0 --port 8188

curl -H "Content-Type: application/json; charset=utf-8" "http://127.0.0.1:8188/api/customnode/getmappings?mode=local"

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 473, in _handle
    match_info = await self._router.resolve(request)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 1010, in resolve
    match_dict, allowed = await resource.resolve(request)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py", line 755, in resolve
    not request.url.raw_path.startswith(self._prefix2)
        ^^^^^^^^^^^
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 437, in url
    url = U500 Internal Server Error

Server got itself in troubleroot@modal:~/comfy/ComfyUI# tail customnodes.log 
  File "aiohttp/_helpers.pyx", line 26, in aiohttp._helpers.reify.__get__
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_request.py", line 437, in url
    url = URL.build(scheme=self.scheme, host=self.host)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 438, in build
    _host = _encode_host(host, validate_host=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yarl/_url.py", line 1514, in _encode_host
    raise ValueError(
ValueError: Host '127.0.0.1:8188' cannot contain ':' (at position 9)

```

if I put the server on the default HTTP port and call it without PORT it works

```
python main.py --listen 0.0.0.0 --port 80
curl -H "Content-Type: application/json; charset=utf-8" "http://127.0.0.1/api/customnode/getmappings?mode=local"

```

### Debug Logs

```powershell
the logs are in the step to reproduce
```

**Comment by JettHu** [comment]
update aiohttp via `pip3 install -U aiohttp`

**Comment by chinchaun** [comment]
@JettHu  , thanks for the response do you have a specific version that is supposed to be fixed in aiohttp?

**Comment by ac5l4t3r** [comment]
> update aiohttp via `pip3 install -U aiohttp`

If I do this and update to the latest version, I cant run the comfyui server. 

>ValueError: Host '127.0.0.1:8188' cannot contain ':' (at position 9)

is what I get

**Comment by SWHL** [comment]
I meet the same error. My env is [requirements.txt](https://github.com/user-attachments/files/18817300/requirements.txt).

**Comment by ltdrdata** [comment]
This is fxied.
