### ISSUE TITLE
 install of SANA incorrect

### ISSUE THREAD

**Issue by falcon5151** [comfyanonymous/ComfyUI#6044]
### Your question

gemma did load automatiquely at hugginface error 401 https://huggingface.co/google/gemma-2-2b-it/
i download 2 files manualy and put them in G:\ComfyUI_windows_portable\ComfyUI\models\text_encoders\models--unsloth--gemma-2-2b-it-bnb-4bit   try rename it gemma 

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 9
- **Node Type:** GemmaLoader
- **Exception Type:** ValueError
- **Exception Message:** `.to` is not supported for `4-bit` or `8-bit` bitsandbytes models. Please use the model as it is, since the model has already been set to the correct devices and casted to the correct `dtype`.
## Stack Trace

  
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 1666, in get_hf_file_metadata
    r = _request_wrapper(
        ^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 364, in _request_wrapper
    response = _request_wrapper(
               ^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\file_download.py", line 388, in _request_wrapper
    hf_raise_for_status(response)
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_http.py", line 423, in hf_raise_for_status
    raise _format(GatedRepoError, message, response) from e
huggingface_hub.errors.GatedRepoError: 401 Client Error. (Request ID: Root=1-675d4a10-62d974d34fea550c1e873d9c;7d617934-8c63-41e2-9f72-3fb6ff86331d)

Cannot access gated repo for url https://huggingface.co/google/gemma-2-2b-it/resolve/299a8560bedf22ed1c72a8a11e7dce4a7f9f51f8/.gitattributes.
Access to model google/gemma-2-2b-it is restricted. You must have access to it and be authenticated to access it. Please log in.

2024-12-14T10:03:57.644161 - end_vram - start_vram: 33554432 - 33554432 = 02024-12-14T10:03:57.644161 - 
2024-12-14T10:03:57.644161 - #9 [GemmaLoader]: 0.81s - vram 0b2024-12-14T10:03:57.644161 - 
2024-12-14T10:03:57.645159 - Prompt executed in 0.82 seconds
2024-12-14T10:03:58.102714 - 
Fetching 11 files:   0%|                                                                        | 0/11 [00:00<?, ?it/s]2024-12-14T10:03:58.736249 - 
Fetching 11 files:   0%|                                                                        | 0/11 [00:00<?, ?it/s]2024-12-14T10:03:58.736249 - 
2024-12-14T10:03:58.877870 - !!! Exception during processing !!! 401 Client Error. (Request ID: Root=1-675d4a12-7a150f9e133756ef6917c4d3;ddc49246-2b54-4133-9cc2-549575e0fc17)

Cannot access gated repo for url https://huggingface.co/google/gemma-2-2b-it/resolve/299a8560bedf22ed1c72a8a11e7dce4a7f9f51f8/.gitattributes.
Access to model google/gemma-2-2b-it is restricted. You must have access to it and be authenticated to access it. Please log in.
2024-12-14T10:03:58.879865 - Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\huggingface_hub\utils\_http.py", line 406, in hf_raise_for_status
    response.raise_for_status()
  File "G:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://huggingface.co/google/gemma-2-2b-it/resolve/299a8560bedf22ed1c72a8a11e7dce4a7f9f51f8/.gitattributes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
```

### Other

do you have a link showing how to install SANA correctly   i found no tutorial

**Comment by LukeG89** [comment]
It's a custom node, you have to ask for help in the custom node repo

**Comment by Meettya** [comment]
To [falcon5151](https://github.com/falcon5151) - go to huggingface.co , profile settings (upper right conner), chose "Access tokens". Create new token finegrained token, add model and read props. You got token, save it.
Next, go to console (at you Comfy Ui env, don`t forget select correct py env) and do `huggingface-cli --help` 
If you get error - install it first, then use `huggingface-cli login` and use your token.
After this steps Comfu UI will can download model.
