### ISSUE TITLE
DualCLIPLoader -- Model in folder 'clip' with filename 'long_clip\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not found.

### ISSUE THREAD

**Issue by jujujackson666** [comfyanonymous/ComfyUI#6056]
### Your question

When I try to create a character sheet, I get this Error message "Model in folder 'clip' with filename 'long_clip\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not found.". What should I do?

# ComfyUI Error Report
## Error Details
- **Node Type:** DualCLIPLoader
- **Exception Type:** FileNotFoundError
- **Exception Message:** Model in folder 'clip' with filename 'long_clip\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not found.
## Stack Trace
```
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 924, in load_clip
    clip_path2 = folder_paths.get_full_path_or_raise("clip", clip_name2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 279, in get_full_path_or_raise
    raise FileNotFoundError(f"Model in folder '{folder_name}' with filename '{filename}' not found.")

```
## System Information
- **ComfyUI Version:** v0.2.3
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 17170956288
  - **VRAM Free:** 12589113984
  - **Torch VRAM Total:** 1845493760
  - **Torch VRAM Free:** 60727936

## Logs
```
2024-12-14 20:35:07,435 - root - INFO - Total VRAM 16376 MB, total RAM 32508 MB
2024-12-14 20:35:07,435 - root - INFO - pytorch version: 2.4.1+cu124
2024-12-14 20:35:07,436 - root - INFO - Set vram state to: NORMAL_VRAM
2024-12-14 20:35:07,436 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
2024-12-14 20:35:08,246 - root - INFO - Using pytorch cross attention
2024-12-14 20:35:09,498 - root - INFO - [Prompt Server] web root: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\web
2024-12-14 20:35:11,083 - root - INFO - Total VRAM 16376 MB, total RAM 32508 MB
2024-12-14 20:35:11,083 - root - INFO - pytorch version: 2.4.1+cu124
2024-12-14 20:35:11,083 - root - INFO - Set vram state to: NORMAL_VRAM
2024-12-14 20:35:11,083 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 Laptop GPU : cudaMallocAsync
2024-12-14 20:35:13,067 - root - INFO - 
Import times for custom nodes:
2024-12-14 20:35:13,068 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-12-14 20:35:13,068 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
2024-12-14 20:35:13,068 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
2024-12-14 20:35:13,068 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-12-14 20:35:13,068 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
2024-12-14 20:35:13,069 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
2024-12-14 20:35:13,069 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
2024-12-14 20:35:13,069 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-12-14 20:35:13,069 - root - INFO -    0.0 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-12-14 20:35:13,069 - root - INFO -    0.1 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-12-14 20:35:13,069 - root - INFO -    0.2 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-12-14 20:35:13,070 - root - INFO -    0.4 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AdvancedLivePortrait
2024-12-14 20:35:13,070 - root - INFO -    0.6 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Image-Filters
2024-12-14 20:35:13,070 - root - INFO -    0.8 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-12-14 20:35:13,070 - root - INFO -    0.9 seconds: C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
2024-12-14 20:35:13,070 - root - INFO - 
2024-12-14 20:35:13,076 - root - INFO - Starting server

2024-12-14 20:35:13,076 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-12-14 20:35:24,388 - root - INFO - got prompt
2024-12-14 20:35:24,391 - root - ERROR - Failed to validate prompt for output 584:
2024-12-14 20:35:24,391 - root - ERROR - * DualCLIPLoader 761:
2024-12-14 20:35:24,391 - root - ERROR -   - Value not in list: clip_name2: 'long_clip\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not in ['clip_l.safetensors', 't5\\google_t5-v1_1-xxl_encoderonly-fp8_e4m3fn.safetensors']
2024-12-14 20:35:24,391 - root - ERROR - Output will be ignored
2024-12-14 20:35:26,062 - root - INFO - Loading PuLID-Flux model.
2024-12-14 20:35:28,178 - root - INFO - Loaded EVA02-CLIP-L-14-336 model config.
2024-12-14 20:35:28,211 - root - INFO - Shape of rope freq: torch.Size([576, 64])
2024-12-14 20:35:31,214 - root - INFO - Loading pretrained EVA02-CLIP-L-14-336 weights (eva_clip).
2024-12-14 20:35:31,765 - root - INFO - incompatible_keys.missing_keys: ['visual.rope.freqs_cos', 'visual.rope.freqs_sin', 'visual.blocks.0.attn.rope.freqs_cos', 'visual.blocks.0.attn.rope.freqs_sin', 'visual.blocks.1.attn.rope.freqs_cos', 'visual.blocks.1.attn.rope.freqs_sin', 'visual.blocks.2.attn.rope.freqs_cos', 'visual.blocks.2.attn.rope.freqs_sin', 'visual.blocks.3.attn.rope.freqs_cos', 'visual.blocks.3.attn.rope.freqs_sin', 'visual.blocks.4.attn.rope.freqs_cos', 'visual.blocks.4.attn.rope.freqs_sin', 'visual.blocks.5.attn.rope.freqs_cos', 'visual.blocks.5.attn.rope.freqs_sin', 'visual.blocks.6.attn.rope.freqs_cos', 'visual.blocks.6.attn.rope.freqs_sin', 'visual.blocks.7.attn.rope.freqs_cos', 'visual.blocks.7.attn.rope.freqs_sin', 'visual.blocks.8.attn.rope.freqs_cos', 'visual.blocks.8.attn.rope.freqs_sin', 'visual.blocks.9.attn.rope.freqs_cos', 'visual.blocks.9.attn.rope.freqs_sin', 'visual.blocks.10.attn.rope.freqs_cos', 'visual.blocks.10.attn.rope.freqs_sin', 'visual.blocks.11.attn.rope.freqs_cos', 'visual.blocks.11.attn.rope.freqs_sin', 'visual.blocks.12.attn.rope.freqs_cos', 'visual.blocks.12.attn.rope.freqs_sin', 'visual.blocks.13.attn.rope.freqs_cos', 'visual.blocks.13.attn.rope.freqs_sin', 'visual.blocks.14.attn.rope.freqs_cos', 'visual.blocks.14.attn.rope.freqs_sin', 'visual.blocks.15.attn.rope.freqs_cos', 'visual.blocks.15.attn.rope.freqs_sin', 'visual.blocks.16.attn.rope.freqs_cos', 'visual.blocks.16.attn.rope.freqs_sin', 'visual.blocks.17.attn.rope.freqs_cos', 'visual.blocks.17.attn.rope.freqs_sin', 'visual.blocks.18.attn.rope.freqs_cos', 'visual.blocks.18.attn.rope.freqs_sin', 'visual.blocks.19.attn.rope.freqs_cos', 'visual.blocks.19.attn.rope.freqs_sin', 'visual.blocks.20.attn.rope.freqs_cos', 'visual.blocks.20.attn.rope.freqs_sin', 'visual.blocks.21.attn.rope.freqs_cos', 'visual.blocks.21.attn.rope.freqs_sin', 'visual.blocks.22.attn.rope.freqs_cos', 'visual.blocks.22.attn.rope.freqs_sin', 'visual.blocks.23.attn.rope.freqs_cos', 'visual.blocks.23.attn.rope.freqs_sin']
2024-12-14 20:35:31,793 - root - INFO - Using pytorch attention in VAE
2024-12-14 20:35:31,793 - root - INFO - Using pytorch attention in VAE
2024-12-14 20:35:33,173 - root - INFO - model weight dtype torch.float8_e4m3fn, manual cast: torch.bfloat16
2024-12-14 20:35:33,175 - root - INFO - model_type FLUX
2024-12-14 20:36:06,741 - root - ERROR - !!! Exception during processing !!! Model in folder 'clip' with filename 'long_clip\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not found.
2024-12-14 20:36:06,796 - root - ERROR - Traceback (most recent call last):
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 924, in load_clip
    clip_path2 = folder_paths.get_full_path_or_raise("clip", clip_name2)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\anusa\Desktop\Comfu UI\ComfyUI_windows_portable\ComfyUI\folder_paths.py", line 279, in get_full_path_or_raise
    raise FileNotFoundError(f"Model in folder '{folder_name}' with filename '{filename}' not found.")
FileNotFoundError: Model in folder 'clip' with filename 'long_clip\ViT-L-14-TEXT-detail-improved-hiT-GmP-TE-only-HF.safetensors' not found.

2024-12-14 20:36:06,810 - root - INFO - Prompt executed in 42.41 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
Workflow too large. Please manually upload the workflow from local file system.
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by LukeG89** [comment]
Do you have the clip model file in `ComfyUI\models\clip\long_clip` folder?

**Comment by LukeG89** [comment]
If you don't have it, you can download it through the Manager -> Model Manager

![image](https://github.com/user-attachments/assets/ace0417b-909c-4ff8-afbc-5ca5958b724c)

Select "clip" as type and search "long". The one you are looking for is the lighter one (but I think you can try both)

![image](https://github.com/user-attachments/assets/03a0a0c0-6ab0-43bc-963f-8b33f8dfb14f)

**Comment by Metrix-1** [comment]
> If you don't have it, you can download it through the Manager -> Model Manager
> 
> ![image](https://private-user-images.githubusercontent.com/161304036/395860869-ace0417b-909c-4ff8-afbc-5ca5958b724c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDk0NDAsIm5iZiI6MTczNTg0OTE0MCwicGF0aCI6Ii8xNjEzMDQwMzYvMzk1ODYwODY5LWFjZTA0MTdiLTkwOWMtNGZmOC1hZmJjLTVjYTU5NThiNzI0Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQyMDE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDU5OTUxYWZmNGFjY2NkMjM4NWJjZTVkNDA4ZTlmNTQxNTI3MzdhZTY2MGRkYzQxMDFjMGFmNjU4MDU1MWUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.FTHE21aee06FqQmHNsfuH5R-p3HIQLdhYlHkitLWilg)
> 
> Select "clip" as type and search "long". The one you are looking for is the lighter one (but I think you can try both)
> 
> ![image](https://private-user-images.githubusercontent.com/161304036/395861334-03a0a0c0-6ab0-43bc-963f-8b33f8dfb14f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4NDk0NDAsIm5iZiI6MTczNTg0OTE0MCwicGF0aCI6Ii8xNjEzMDQwMzYvMzk1ODYxMzM0LTAzYTBhMGMwLTZhYjAtNDNiYy05NjNmLThiMzNmOGRmYjE0Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQyMDE5MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNDVmZWQ1Nzg4OTc0MjA1M2ZlODgzMmQ0YmU2YzU0YTRmZTc4MDU0MDUyMDQwNDY5NDM5OGZkZTdiYzU0YTE5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-1VPvlnUvnykK2H36e_aUdgXMZgBlrTLZR8GrmvxUe0)

This worked for me, thank you very much.
