### ISSUE TITLE
User specified an unsupported autocast device_type 'cuda:0'

### ISSUE THREAD

**Issue by aa5277** [comfyanonymous/ComfyUI#6061]
### Your question

# ComfyUI Error Report
## Error Details
- **Node ID:** 22
- **Node Type:** Joy_caption
- **Exception Type:** RuntimeError
- **Exception Message:** User specified an unsupported autocast device_type 'cuda:0'
## Stack Trace
```
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/root/ComfyUI/custom_nodes/Comfyui_CXH_joy_caption/Joy_caption_node.py", line 181, in gen
    with torch.amp.autocast_mode.autocast(str(DEVICE), enabled=True):

  File "/root/miniconda3/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
    raise RuntimeError(

```
## System Information
- **ComfyUI Version:** latest-2027-g26c60c2
- **Arguments:** main.py --port 7860 --extra-model-paths-config onething_extra_model_paths.yaml --output-directory /root/onethingai-tmp/comfyui-output --temp-directory /root/onethingai-tmp/comfyui-tmp --disable-auto-launch --enable-cors-header --fp16-unet
- **OS:** posix
- **Python Version:** 3.10.13 (main, Sep 11 2023, 13:44:35) [GCC 11.2.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.3.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 12629508096
  - **VRAM Free:** 4255254056
  - **Torch VRAM Total:** 7583301632
  - **Torch VRAM Free:** 7276072

## Logs
```
2024-12-15T21:00:30.630235 - []2024-12-15T21:00:30.630317 - 
2024-12-15T21:00:30.630386 - []2024-12-15T21:00:30.630415 - 
2024-12-15T21:00:31.184814 - []2024-12-15T21:00:31.184890 - 
2024-12-15T21:00:31.184976 - []2024-12-15T21:00:31.185017 - 
2024-12-15T21:00:31.881241 - []2024-12-15T21:00:31.881300 - 
2024-12-15T21:00:31.881355 - []2024-12-15T21:00:31.881384 - 
2024-12-15T21:00:32.416647 - []2024-12-15T21:00:32.416715 - 
2024-12-15T21:00:32.416766 - []2024-12-15T21:00:32.416795 - 
2024-12-15T21:00:33.127588 - []2024-12-15T21:00:33.127667 - 
2024-12-15T21:00:33.127757 - []2024-12-15T21:00:33.127808 - 
2024-12-15T21:00:33.654216 - []2024-12-15T21:00:33.654286 - 
2024-12-15T21:00:33.654355 - []2024-12-15T21:00:33.654385 - 
2024-12-15T21:00:34.362002 - []2024-12-15T21:00:34.362071 - 
2024-12-15T21:00:34.362158 - []2024-12-15T21:00:34.362201 - 
2024-12-15T21:00:35.878380 - []2024-12-15T21:00:35.878437 - 
2024-12-15T21:00:35.878490 - []2024-12-15T21:00:35.878518 - 
2024-12-15T21:00:36.559630 - []2024-12-15T21:00:36.559683 - 
2024-12-15T21:00:36.559756 - []2024-12-15T21:00:36.559787 - 
2024-12-15T21:00:37.106650 - []2024-12-15T21:00:37.106704 - 
2024-12-15T21:00:37.106771 - []2024-12-15T21:00:37.106800 - 
2024-12-15T21:00:37.796905 - []2024-12-15T21:00:37.796959 - 
2024-12-15T21:00:37.797025 - []2024-12-15T21:00:37.797054 - 
2024-12-15T21:00:38.350487 - []2024-12-15T21:00:38.350538 - 
2024-12-15T21:00:38.350587 - []2024-12-15T21:00:38.350614 - 
2024-12-15T21:00:39.032151 - []2024-12-15T21:00:39.032211 - 
2024-12-15T21:00:39.032284 - []2024-12-15T21:00:39.032313 - 
2024-12-15T21:00:39.568943 - []2024-12-15T21:00:39.568996 - 
2024-12-15T21:00:39.569047 - []2024-12-15T21:00:39.569075 - 
2024-12-15T21:00:40.252786 - []2024-12-15T21:00:40.252839 - 
2024-12-15T21:00:40.252889 - []2024-12-15T21:00:40.252917 - 
2024-12-15T21:00:40.795946 - []2024-12-15T21:00:40.796001 - 
2024-12-15T21:00:40.796090 - []2024-12-15T21:00:40.796142 - 
2024-12-15T21:00:42.161269 - []2024-12-15T21:00:42.161343 - 
2024-12-15T21:00:42.161399 - []2024-12-15T21:00:42.161428 - 
2024-12-15T21:00:42.863144 - []2024-12-15T21:00:42.863221 - 
2024-12-15T21:00:42.863293 - []2024-12-15T21:00:42.863323 - 
2024-12-15T21:00:43.415751 - []2024-12-15T21:00:43.415809 - 
2024-12-15T21:00:43.415864 - []2024-12-15T21:00:43.415896 - 
2024-12-15T21:00:44.135675 - []2024-12-15T21:00:44.135729 - 
2024-12-15T21:00:44.135797 - []2024-12-15T21:00:44.135826 - 
2024-12-15T21:00:44.671326 - []2024-12-15T21:00:44.671412 - 
2024-12-15T21:00:44.671483 - []2024-12-15T21:00:44.671511 - 
2024-12-15T21:00:45.351475 - []2024-12-15T21:00:45.351529 - 
2024-12-15T21:00:45.351613 - []2024-12-15T21:00:45.351644 - 
2024-12-15T21:00:45.861503 - []2024-12-15T21:00:45.861570 - 
2024-12-15T21:00:45.861638 - []2024-12-15T21:00:45.861667 - 
2024-12-15T21:00:46.527083 - []2024-12-15T21:00:46.527178 - 
2024-12-15T21:00:46.527270 - []2024-12-15T21:00:46.527301 - 
2024-12-15T21:00:47.040282 - []2024-12-15T21:00:47.040334 - 
2024-12-15T21:00:47.040409 - []2024-12-15T21:00:47.040439 - 
2024-12-15T21:00:47.734227 - []2024-12-15T21:00:47.734293 - 
2024-12-15T21:00:47.734360 - []2024-12-15T21:00:47.734388 - 
2024-12-15T21:00:48.946793 - []2024-12-15T21:00:48.946869 - 
2024-12-15T21:00:48.946963 - []2024-12-15T21:00:48.947010 - 
2024-12-15T21:00:49.642838 - []2024-12-15T21:00:49.642907 - 
2024-12-15T21:00:49.642975 - []2024-12-15T21:00:49.643005 - 
2024-12-15T21:00:50.191504 - []2024-12-15T21:00:50.191561 - 
2024-12-15T21:00:50.191625 - []2024-12-15T21:00:50.191653 - 
2024-12-15T21:00:50.890148 - []2024-12-15T21:00:50.890224 - 
2024-12-15T21:00:50.890287 - []2024-12-15T21:00:50.890320 - 
2024-12-15T21:00:51.448630 - []2024-12-15T21:00:51.448707 - 
2024-12-15T21:00:51.448783 - []2024-12-15T21:00:51.448816 - 
2024-12-15T21:00:52.163162 - []2024-12-15T21:00:52.163216 - 
2024-12-15T21:00:52.163273 - []2024-12-15T21:00:52.163302 - 
2024-12-15T21:00:52.696877 - []2024-12-15T21:00:52.696952 - 
2024-12-15T21:00:52.697026 - []2024-12-15T21:00:52.697058 - 
2024-12-15T21:00:53.389351 - []2024-12-15T21:00:53.389410 - 
2024-12-15T21:00:53.389466 - []2024-12-15T21:00:53.389496 - 
2024-12-15T21:00:53.923711 - []2024-12-15T21:00:53.923778 - 
2024-12-15T21:00:53.923834 - []2024-12-15T21:00:53.923877 - 
2024-12-15T21:00:54.626231 - []2024-12-15T21:00:54.626286 - 
2024-12-15T21:00:54.626341 - []2024-12-15T21:00:54.626371 - 
2024-12-15T21:00:55.842271 - []2024-12-15T21:00:55.842342 - 
2024-12-15T21:00:55.842412 - []2024-12-15T21:00:55.842459 - 
2024-12-15T21:00:56.524248 - []2024-12-15T21:00:56.524305 - 
2024-12-15T21:00:56.524358 - []2024-12-15T21:00:56.524387 - 
2024-12-15T21:00:57.079685 - []2024-12-15T21:00:57.079753 - 
2024-12-15T21:00:57.079821 - []2024-12-15T21:00:57.079851 - 
2024-12-15T21:00:57.786553 - []2024-12-15T21:00:57.786624 - 
2024-12-15T21:00:57.786695 - []2024-12-15T21:00:57.786740 - 
2024-12-15T21:00:58.337296 - []2024-12-15T21:00:58.337364 - 
2024-12-15T21:00:58.337421 - []2024-12-15T21:00:58.337451 - 
2024-12-15T21:00:59.040259 - []2024-12-15T21:00:59.040311 - 
2024-12-15T21:00:59.040394 - []2024-12-15T21:00:59.040424 - 
2024-12-15T21:00:59.613500 - []2024-12-15T21:00:59.613553 - 
2024-12-15T21:00:59.613635 - []2024-12-15T21:00:59.613680 - 
2024-12-15T21:01:00.302508 - []2024-12-15T21:01:00.302576 - 
2024-12-15T21:01:00.302665 - []2024-12-15T21:01:00.302705 - 
2024-12-15T21:01:00.839646 - []2024-12-15T21:01:00.839698 - 
2024-12-15T21:01:00.839746 - []2024-12-15T21:01:00.839772 - 
2024-12-15T21:01:01.567090 - []2024-12-15T21:01:01.567166 - 
2024-12-15T21:01:01.567223 - []2024-12-15T21:01:01.567254 - 
2024-12-15T21:01:02.885029 - []2024-12-15T21:01:02.885081 - 
2024-12-15T21:01:02.885154 - []2024-12-15T21:01:02.885185 - 
2024-12-15T21:01:03.464537 - []2024-12-15T21:01:03.464590 - 
2024-12-15T21:01:03.464638 - []2024-12-15T21:01:03.464664 - 
2024-12-15T21:01:04.104028 - []2024-12-15T21:01:04.104079 - 
2024-12-15T21:01:04.104142 - []2024-12-15T21:01:04.104171 - 
2024-12-15T21:01:04.699620 - []2024-12-15T21:01:04.699672 - 
2024-12-15T21:01:04.699736 - []2024-12-15T21:01:04.699765 - 
2024-12-15T21:01:05.345474 - []2024-12-15T21:01:05.345543 - 
2024-12-15T21:01:05.345612 - []2024-12-15T21:01:05.345657 - 
2024-12-15T21:01:05.916412 - []2024-12-15T21:01:05.916462 - 
2024-12-15T21:01:05.916510 - []2024-12-15T21:01:05.916536 - 
2024-12-15T21:01:06.619911 - []2024-12-15T21:01:06.619972 - 
2024-12-15T21:01:06.620032 - []2024-12-15T21:01:06.620065 - 
2024-12-15T21:01:07.217731 - []2024-12-15T21:01:07.217783 - 
2024-12-15T21:01:07.217849 - []2024-12-15T21:01:07.217892 - 
2024-12-15T21:01:07.926509 - []2024-12-15T21:01:07.926582 - 
2024-12-15T21:01:07.926656 - []2024-12-15T21:01:07.926689 - 
2024-12-15T21:01:09.502028 - []2024-12-15T21:01:09.502087 - 
2024-12-15T21:01:09.502168 - []2024-12-15T21:01:09.502220 - 
2024-12-15T21:01:09.803959 - 2024-12-15 21:01:09,803- root:599- INFO- got prompt
2024-12-15T21:01:09.827193 - /root/ComfyUI/models/clip/siglip-so400m-patch14-3842024-12-15T21:01:09.827656 - 
2024-12-15T21:01:11.043922 - []2024-12-15T21:01:11.043997 - 
2024-12-15T21:01:11.044066 - []2024-12-15T21:01:11.044097 - 
2024-12-15T21:01:11.569082 - /root/ComfyUI/models/LLM/Meta-Llama-3.1-8B-bnb-4bit2024-12-15T21:01:11.569361 - 
2024-12-15T21:01:13.281630 - []2024-12-15T21:01:13.281698 - 
2024-12-15T21:01:13.281755 - []2024-12-15T21:01:13.281785 - 
2024-12-15T21:01:14.143812 - []2024-12-15T21:01:14.143868 - 
2024-12-15T21:01:14.143950 - []2024-12-15T21:01:14.143979 - 
2024-12-15T21:01:14.846754 - []2024-12-15T21:01:14.846834 - 
2024-12-15T21:01:14.846904 - []2024-12-15T21:01:14.846948 - 
2024-12-15T21:01:15.770765 - []2024-12-15T21:01:15.770869 - 
2024-12-15T21:01:15.770940 - []2024-12-15T21:01:15.770969 - 
2024-12-15T21:01:16.510386 - []2024-12-15T21:01:16.510561 - 
2024-12-15T21:01:16.510622 - []2024-12-15T21:01:16.510666 - 
2024-12-15T21:01:17.407822 - []2024-12-15T21:01:17.407911 - 
2024-12-15T21:01:17.407995 - []2024-12-15T21:01:17.408045 - 
2024-12-15T21:01:18.118435 - []2024-12-15T21:01:18.118515 - 
2024-12-15T21:01:18.118603 - []2024-12-15T21:01:18.118646 - 
2024-12-15T21:01:19.898719 - []2024-12-15T21:01:19.898779 - 
2024-12-15T21:01:19.898833 - []2024-12-15T21:01:19.898862 - 
2024-12-15T21:01:20.691525 - []2024-12-15T21:01:20.691675 - 
2024-12-15T21:01:20.691794 - []2024-12-15T21:01:20.691867 - 
2024-12-15T21:01:21.374648 - []2024-12-15T21:01:21.374712 - 
2024-12-15T21:01:21.374770 - []2024-12-15T21:01:21.374799 - 
2024-12-15T21:01:22.188640 - []2024-12-15T21:01:22.188703 - 
2024-12-15T21:01:22.188757 - []2024-12-15T21:01:22.188786 - 
2024-12-15T21:01:22.852146 - []2024-12-15T21:01:22.852290 - 
2024-12-15T21:01:22.852367 - []2024-12-15T21:01:22.852407 - 
2024-12-15T21:01:23.706395 - []2024-12-15T21:01:23.706488 - 
2024-12-15T21:01:23.706564 - []2024-12-15T21:01:23.706613 - 
2024-12-15T21:01:24.387275 - []2024-12-15T21:01:24.387346 - 
2024-12-15T21:01:24.387401 - []2024-12-15T21:01:24.387431 - 
2024-12-15T21:01:26.239884 - []2024-12-15T21:01:26.239968 - 
2024-12-15T21:01:26.240066 - []2024-12-15T21:01:26.240121 - 
2024-12-15T21:01:26.693631 - 2024-12-15 21:01:26,693- root:392- ERROR- !!! Exception during processing !!! User specified an unsupported autocast device_type 'cuda:0'
2024-12-15T21:01:26.694376 - 2024-12-15 21:01:26,694- root:393- ERROR- Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/root/ComfyUI/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/root/ComfyUI/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/root/ComfyUI/custom_nodes/Comfyui_CXH_joy_caption/Joy_caption_node.py", line 181, in gen
    with torch.amp.autocast_mode.autocast(str(DEVICE), enabled=True):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 241, in __init__
    raise RuntimeError(
RuntimeError: User specified an unsupported autocast device_type 'cuda:0'

2024-12-15T21:01:26.695209 - 2024-12-15 21:01:26,694- root:146- INFO- Prompt executed in 16.88 seconds
2024-12-15T21:01:27.902739 - []2024-12-15T21:01:27.902807 - 
2024-12-15T21:01:27.902857 - []2024-12-15T21:01:27.902885 - 

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":27,"last_link_id":35,"nodes":[{"id":13,"type":"PreviewImage","pos":[2063,-750],"size":[395.6734924316406,609.4927978515625],"flags":{},"order":13,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":11,"label":"图像"}],"outputs":[],"properties":{"Node name for S&R":"PreviewImage"},"widgets_values":[]},{"id":21,"type":"Image Comparer (rgthree)","pos":[375,-727],"size":[282.46063232421875,322.6549987792969],"flags":{},"order":14,"mode":0,"inputs":[{"name":"image_a","type":"IMAGE","link":22,"label":"图像_A","dir":3},{"name":"image_b","type":"IMAGE","link":28,"label":"图像_B","dir":3}],"outputs":[],"properties":{"comparer_mode":"Slide"},"widgets_values":[[{"name":"A","selected":true,"url":"https://liblibai-tmp-image.liblib.cloud/sd-images/0da2e98289ef4b23712610319d14536cdd5080ca569699a433d183962665be45.png?filename=sd-images/0da2e98289ef4b23712610319d14536cdd5080ca569699a433d183962665be45.png&type=output&rand=0.6169517131960012"},{"name":"B","selected":true,"url":"https://liblibai-tmp-image.liblib.cloud/sd-images/a712c13ed827bf35e2783a2978b3e551b3db732576bf1e4ff84575a81832451d.png?filename=sd-images/a712c13ed827bf35e2783a2978b3e551b3db732576bf1e4ff84575a81832451d.png&type=output&rand=0.4225199573650502"}]]},{"id":12,"type":"UltimateSDUpscale","pos":[1687,-820],"size":[315,614],"flags":{},"order":12,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":21,"label":"图像"},{"name":"model","type":"MODEL","link":32,"label":"模型"},{"name":"positive","type":"CONDITIONING","link":15,"label":"正面条件"},{"name":"negative","type":"CONDITIONING","link":34,"label":"负面条件"},{"name":"vae","type":"VAE","link":19,"label":"VAE"},{"name":"upscale_model","type":"UPSCALE_MODEL","link":12,"label":"放大模型"},{"name":"denoise","type":"FLOAT","link":29,"widget":{"name":"denoise"},"label":"降噪"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[11,22],"slot_index":0,"label":"图像"}],"properties":{"Node name for S&R":"UltimateSDUpscale"},"widgets_values":[2,530646784319582,"randomize",20,1,"euler","normal",0.3,"Linear",1024,1024,8,32,"None",1,64,8,16,true,false]},{"id":17,"type":"CLIPTextEncode","pos":[817,-284],"size":[400,200],"flags":{},"order":10,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":17,"label":"CLIP"},{"name":"text","type":"STRING","link":24,"widget":{"name":"text"},"label":"文本"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[15,33],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["",[false,true]]},{"id":16,"type":"LoadImage","pos":[22,-716],"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[20],"slot_index":0,"label":"图像"},{"name":"MASK","type":"MASK","links":null,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["pasted/image (9).png","image"],"color":"#232","bgcolor":"#353"},{"id":14,"type":"UpscaleModelLoader","pos":[1240,-330],"size":[315,58],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"UPSCALE_MODEL","type":"UPSCALE_MODEL","links":[12],"label":"放大模型"}],"properties":{"Node name for S&R":"UpscaleModelLoader"},"widgets_values":["RealESRGAN_x4plus_anime_6B.pth"]},{"id":26,"type":"LoraLoaderModelOnly","pos":[1240,-830],"size":[315,82],"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":35,"label":"模型"}],"outputs":[{"name":"MODEL","type":"MODEL","links":[32],"slot_index":0,"label":"模型"}],"properties":{"Node name for S&R":"LoraLoaderModelOnly"},"widgets_values":["FLUX/anime_lora.safetensors",0.1]},{"id":27,"type":"ConditioningZeroOut","pos":[1240,-230],"size":[317.4000244140625,26],"flags":{},"order":11,"mode":0,"inputs":[{"name":"conditioning","type":"CONDITIONING","link":33,"label":"条件"}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[34],"slot_index":0,"label":"条件"}],"properties":{"Node name for S&R":"ConditioningZeroOut"},"widgets_values":[]},{"id":19,"type":"VAELoader","pos":[1240,-440],"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"VAE","type":"VAE","links":[19]}],"properties":{"Node name for S&R":"VAELoader"},"widgets_values":["ae.sft"]},{"id":15,"type":"UNETLoader","pos":[1240,-960],"size":[315,82],"flags":{},"order":4,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[35],"slot_index":0,"label":"模型"}],"properties":{"Node name for S&R":"UNETLoader"},"widgets_values":["flux1-dev-fp8.safetensors","fp8_e4m3fn"]},{"id":24,"type":"PrimitiveNode","pos":[910,-950],"size":[310,82],"flags":{},"order":5,"mode":0,"inputs":[],"outputs":[{"name":"FLOAT","type":"FLOAT","links":[29],"slot_index":0,"widget":{"name":"denoise"}}],"properties":{"Run widget replace on values":false},"widgets_values":[0.3,"fixed"]},{"id":22,"type":"Joy_caption","pos":[810,-550],"size":[400,200],"flags":{},"order":9,"mode":0,"inputs":[{"name":"joy_pipeline","type":"JoyPipeline","link":25,"label":"JoyCaption"},{"name":"image","type":"IMAGE","link":27,"label":"图像"}],"outputs":[{"name":"STRING","type":"STRING","links":[24],"label":"字符串"}],"properties":{"Node name for S&R":"Joy_caption"},"widgets_values":["A descriptive caption for this image",1024,0.7,false,[false,true]]},{"id":20,"type":"ImageResize+","pos":[1240,-700],"size":[315,218],"flags":{},"order":7,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":20,"label":"图像"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[21,27,28],"slot_index":0,"label":"图像"},{"name":"width","type":"INT","links":null,"label":"宽度"},{"name":"height","type":"INT","links":null,"label":"高度"}],"properties":{"Node name for S&R":"ImageResize+"},"widgets_values":[1024,1024,"nearest","keep proportion","always",0]},{"id":23,"type":"Joy_caption_load","pos":[890,-820],"size":[315,58],"flags":{},"order":6,"mode":0,"inputs":[],"outputs":[{"name":"JoyPipeline","type":"JoyPipeline","links":[25],"label":"JoyCaption"}],"properties":{"Node name for S&R":"Joy_caption_load"},"widgets_values":["unsloth/Meta-Llama-3.1-8B-bnb-4bit"]},{"id":18,"type":"DualCLIPLoader","pos":[890,-720],"size":[315,106],"flags":{"collapsed":false},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"CLIP","type":"CLIP","links":[17],"slot_index":0,"label":"CLIP"}],"properties":{"Node name for S&R":"DualCLIPLoader"},"widgets_values":["t5xxl_fp8_e4m3fn.safetensors","clip_l.safetensors","flux"]}],"links":[[11,12,0,13,0,"IMAGE"],[12,14,0,12,5,"UPSCALE_MODEL"],[15,17,0,12,2,"CONDITIONING"],[17,18,0,17,0,"CLIP"],[19,19,0,12,4,"VAE"],[20,16,0,20,0,"IMAGE"],[21,20,0,12,0,"IMAGE"],[22,12,0,21,0,"IMAGE"],[24,22,0,17,1,"STRING"],[25,23,0,22,0,"JoyPipeline"],[27,20,0,22,1,"IMAGE"],[28,20,0,21,1,"IMAGE"],[29,24,0,12,6,"FLOAT"],[32,26,0,12,1,"MODEL"],[33,17,0,27,0,"CONDITIONING"],[34,27,0,12,3,"CONDITIONING"],[35,15,0,26,0,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":1.167184107045003,"offset":[-504.87693665717455,947.045606052302]},"0246.VERSION":[0,0,4]},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

### Logs

```powershell
JoyCaption
User specified an unsupported autocast device_type 'cuda:0'
```

**Comment by LukeG89** [comment]
It's a [Comfyui_CXH_joy_caption](https://github.com/StartHua/Comfyui_CXH_joy_caption) bug.
Try updating the node. If it doesn't solve the problem, check this: 
- https://github.com/StartHua/Comfyui_CXH_joy_caption/issues/37#issuecomment-2345235830

**Comment by aa5277** [comment]
Pass https://github.com/StartHua/Comfyui_CXH_joy_caption/issues/37#issuecomment-2345235830 
Problem solved
