### ISSUE TITLE
Invalid Style Model

### ISSUE THREAD

**Issue by nikhilkofficial** [comfyanonymous/ComfyUI#6063]
### Expected Behavior

Redux Style Model To be loaded.

### Actual Behavior

<img width="891" alt="Screenshot 2024-12-15 at 8 39 18 PM" src="https://github.com/user-attachments/assets/c30ce904-f6b6-4446-910c-d521ecfb1bb0" />

### Steps to Reproduce

I tried updating Comfyui, python, numpy, torch... everything. Just gets stuck on this. Pl if anyone has found a solution, that would be extremely helpful.

Also tried on both Python 3.11.11 & 3.12.x
Thank you. 

### Debug Logs

```powershell
got prompt
Using split attention in VAE
Using split attention in VAE
Requested to load FluxClipModel_
Loading 1 new model
loaded completely 0.0 4777.53759765625 True
clip missing: ['text_projection.weight']
Requested to load CLIPVisionModelProjection
Loading 1 new model
loaded completely 0.0 581.275390625 True
!!! Exception during processing !!! invalid style model /Users/nikhil/pinokio/api/ComfyUI-cpu/models/style_models/flux1-redux-dev.safetensors
Traceback (most recent call last):
  File "/Users/nikhil/pinokio/api/ComfyUI-cpu/execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhil/pinokio/api/ComfyUI-cpu/execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhil/pinokio/api/ComfyUI-cpu/execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/Users/nikhil/pinokio/api/ComfyUI-cpu/execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhil/pinokio/api/ComfyUI-cpu/nodes.py", line 974, in load_style_model
    style_model = comfy.sd.load_style_model(style_model_path)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nikhil/pinokio/api/ComfyUI-cpu/comfy/sd.py", line 391, in load_style_model
    raise Exception("invalid style model {}".format(ckpt_path))
Exception: invalid style model /Users/nikhil/pinokio/api/ComfyUI-cpu/models/style_models/flux1-redux-dev.safetensors

Prompt executed in 31.21 seconds
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
fatal: No names found, cannot describe anything.
Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```

**Comment by ltdrdata** [comment]
It seems that your ComfyUI is outdated very much.
Maybe you are failing to update ComfyUI.

**Comment by nikhilkofficial** [comment]
Thank ou for the reply.

Sorry I am not too familiar with terminal usage. I am using a mac and cloned the repo specifically made for CPU. This one:
https://github.com/ArdeniusAI/ComfyUI-cpu.

Tried again.
Nikhils-MacBook-Pro-2:ComfyUI-cpu nikhil$ git pull
Already up to date.

**Comment by ltdrdata** [comment]
Check this.
![image](https://github.com/user-attachments/assets/2a790722-08a7-4fd5-bbb2-665cb4db8714)
