### ISSUE TITLE
ComfyUI's recursive_search will fail on Windows if it encounters a file/directory junction

### ISSUE THREAD

**Issue by ggarra13** [comfyanonymous/ComfyUI#6079]
### Expected Behavior

ComfyUI should be able to handle Windows' file or directory junctions.

will fail with an error similar to:

Traceback (most recent call last):
  File "C:\code\applications\narrative\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\code\applications\narrative\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 21, in <module>
    from .py.context import RgthreeContext
  File "C:\code\applications\narrative\ComfyUI\custom_nodes\rgthree-comfy\py\context.py", line 2, in <module>
    from .context_utils import (ORIG_CTX_OPTIONAL_INPUTS, ORIG_CTX_RETURN_NAMES, ORIG_CTX_RETURN_TYPES,
  File "C:\code\applications\narrative\ComfyUI\custom_nodes\rgthree-comfy\py\context_utils.py", line 22, in <module>
    "ckpt_name": ("ckpt_name", folder_paths.get_filename_list("checkpoints"), "CKPT_NAME"),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\applications\narrative\ComfyUI\folder_paths.py", line 327, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\applications\narrative\ComfyUI\folder_paths.py", line 291, in get_filename_list_
    files, folders_all = recursive_search(x, excluded_dir_names=[".git"])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\applications\narrative\ComfyUI\folder_paths.py", line 248, in recursive_search
    dirs[path] = os.path.getmtime(path)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 67, in getmtime
NotADirectoryError: [WinError 267] The directory name is invalid: 'C:\\code\\applications\\narrative\\ComfyUI\\models\\checkpoints\\XL\\test.safetensors'

### Actual Behavior

Fails with an error in os.path.getmtime(path).

### Steps to Reproduce

Create a file juntion (the equivalent of symlinks on Windows) from a valid checkpoint to another, like (cmd.exe command):

```
cd checkpoints/XL
mklink /J test.safetensors Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors
```

When loading comfyUI or any node that does:

`    
"ckpt_name": ("ckpt_name", folder_paths.get_filename_list("checkpoints"), "CKPT_NAME"),
`

### Debug Logs

```powershell
Traceback (most recent call last):
  File "C:\code\applications\narrative\ComfyUI\nodes.py", line 2026, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\code\applications\narrative\ComfyUI\custom_nodes\rgthree-comfy\__init__.py", line 21, in <module>
    from .py.context import RgthreeContext
  File "C:\code\applications\narrative\ComfyUI\custom_nodes\rgthree-comfy\py\context.py", line 2, in <module>
    from .context_utils import (ORIG_CTX_OPTIONAL_INPUTS, ORIG_CTX_RETURN_NAMES, ORIG_CTX_RETURN_TYPES,
  File "C:\code\applications\narrative\ComfyUI\custom_nodes\rgthree-comfy\py\context_utils.py", line 22, in <module>
    "ckpt_name": ("ckpt_name", folder_paths.get_filename_list("checkpoints"), "CKPT_NAME"),
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\applications\narrative\ComfyUI\folder_paths.py", line 327, in get_filename_list
    out = get_filename_list_(folder_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\applications\narrative\ComfyUI\folder_paths.py", line 291, in get_filename_list_
    files, folders_all = recursive_search(x, excluded_dir_names=[".git"])
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\applications\narrative\ComfyUI\folder_paths.py", line 248, in recursive_search
    dirs[path] = os.path.getmtime(path)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen genericpath>", line 67, in getmtime
```

**Comment by ltdrdata** [comment]
Make sure the link is valid.
Generally, that error occurs because of a broken link.

**Comment by ggarra13** [comment]
The link is valid.  ComfyUI works fine if I do a junction on the models dir, for example.  But for individual file junctions, it seems to fail.
Anyway, for the time being, I will do a junction on the models dir.

**Comment by catboxanon** [comment]
A limitation of junctions is they only work for directories. The command you ran means Windows will attempt to interpret `Juggernaut-XL_v9_RunDiffusionPhoto_v2.safetensors` as a directory, which then if you access `test.safetensors` from a file explorer, will also show you it's invalid.

**Comment by ggarra13** [comment]
@catboxanon Thanks for the clarification.
