### ISSUE TITLE
Hunyuan tiled vae decode fails with short videos

### ISSUE THREAD

**Issue by spacepxl** [comfyanonymous/ComfyUI#6093]
### Expected Behavior

Successful tiled decoding of the latents. The standard VAE decode node does work, with higher memory usage, even though it claims to fall back to tiled mode.

### Actual Behavior

When decoding latents with video length less than 29, the tiled vae decode node fails.

### Steps to Reproduce

Using the example hunyuan t2v workflow, set the latent video length to 25 or lower, and use the tiled vae decode node.

Minimum reproduction workflow: [hunyuan_vae_decode_tiled_bug.json](https://github.com/user-attachments/files/18171502/hunyuan_vae_decode_tiled_bug.json)

### Debug Logs

```powershell
Traceback (most recent call last):
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\nodes.py", line 306, in decode
    images = vae.decode_tiled(samples["samples"], tile_x=tile_size // compression, tile_y=tile_size // compression, overlap=overlap // compression)
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 483, in decode_tiled
    output = self.decode_tiled_3d(samples, **args)
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 416, in decode_tiled_3d
    return self.process_output(comfy.utils.tiled_scale_multidim(samples, decode_fn, tile=(tile_t, tile_x, tile_y), overlap=overlap, upscale_amount=self.upscale_ratio, out_channels=self.output_channels, output_device=self.output_device))
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\******\Desktop\ComfyUI_windows_portable\ComfyUI\comfy\utils.py", line 810, in tiled_scale_multidim
    mask.narrow(d, t, 1).mul_(a)
RuntimeError: start (25) + length (1) exceeds dimension size (25).
```

**Comment by LukeG89** [comment]
I just tried your workflow and I didn't get any error. Maybe it has been fixed after this commit? https://github.com/comfyanonymous/ComfyUI/commit/cd6f61503886ec6422f707975cf9db5d8e5ea18f

![image](https://github.com/user-attachments/assets/4c9954af-ae68-41c1-b0b2-d929fc314b10)

```powershell
got prompt
Using pytorch attention in VAE
Using pytorch attention in VAE
Requested to load AutoencoderKL
0 models unloaded.
loaded completely 9.5367431640625e+25 470.1210079193115 True
0 models unloaded.
Warning: Ran out of memory when regular VAE decoding, retrying with tiled VAE decoding.
Prompt executed in 38.05 seconds
```

**Comment by comfyanonymous** [comment]
Yeah that should be fixed now.
