### ISSUE TITLE
VAE Decode Error

### ISSUE THREAD

**Issue by ferdiansatria95** [comfyanonymous/ComfyUI#6097]
### Your question

I've updated everything using the ComfyUI manager, but when generating an image, the VAE decode gives an error. I've tried different checkpoints and workflows, but the result is the same.

Let me know if you need further adjustments!

### Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 8
- **Node Type:** VAEDecode
- **Exception Type:** TypeError
- **Exception Message:** 'float' object is not subscriptable
## Stack Trace

  File "/workspace/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/workspace/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/workspace/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/workspace/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/workspace/ComfyUI/nodes.py", line 285, in decode
    images = vae.decode(samples["samples"])

  File "/workspace/ComfyUI/comfy/sd.py", line 446, in decode
    out = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())

  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)

  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 723, in forward
    h = self.up[i_level].upsample(h)

  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)

  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 112, in forward
    x = interpolate_up(x, self.scale_factor)

  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 71, in interpolate_up
    out_shape.append(round(orig_shape[i + 2] * scale_factor[i]))

```
## System Information
- **ComfyUI Version:** v0.3.7-47-gca457f7
- **Arguments:** main.py --listen --port 3000
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.0.1+cu118
## Devices

- **Name:** cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 16883908608
  - **VRAM Free:** 9613325282
  - **Torch VRAM Total:** 6979321856
  - **Torch VRAM Free:** 6861794

## Logs
```
2024-12-18T04:06:55.677611 - [START] Security scan2024-12-18T04:06:55.677642 - 
2024-12-18T04:06:56.532260 - [DONE] Security scan2024-12-18T04:06:56.532291 - 
2024-12-18T04:06:56.642757 - ## ComfyUI-Manager: installing dependencies done.2024-12-18T04:06:56.642964 - 
2024-12-18T04:06:56.643121 - ** ComfyUI startup time:2024-12-18T04:06:56.643300 -  2024-12-18T04:06:56.643499 - 2024-12-18 04:06:56.6429792024-12-18T04:06:56.643678 - 
2024-12-18T04:06:56.643857 - ** Platform:2024-12-18T04:06:56.644003 -  2024-12-18T04:06:56.644139 - Linux2024-12-18T04:06:56.644307 - 
2024-12-18T04:06:56.644500 - ** Python version:2024-12-18T04:06:56.644633 -  2024-12-18T04:06:56.644764 - 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]2024-12-18T04:06:56.644935 - 
2024-12-18T04:06:56.645107 - ** Python executable:2024-12-18T04:06:56.645278 -  2024-12-18T04:06:56.645448 - /venv/bin/python2024-12-18T04:06:56.645579 - 
2024-12-18T04:06:56.645751 - ** ComfyUI Path:2024-12-18T04:06:56.645922 -  2024-12-18T04:06:56.646090 - /workspace/ComfyUI2024-12-18T04:06:56.646222 - 
2024-12-18T04:06:56.646377 - ** Log path:2024-12-18T04:06:56.646563 -  2024-12-18T04:06:56.646738 - /workspace/ComfyUI/comfyui.log2024-12-18T04:06:56.646921 - 
2024-12-18T04:06:58.060209 - 
Prestartup times for custom nodes:2024-12-18T04:06:58.060472 - 
2024-12-18T04:06:58.060687 -    2.4 seconds:2024-12-18T04:06:58.060856 -  2024-12-18T04:06:58.061048 - /workspace/ComfyUI/custom_nodes/ComfyUI-Manager2024-12-18T04:06:58.061230 - 
2024-12-18T04:06:58.061427 - 
2024-12-18T04:07:00.198592 - Total VRAM 16102 MB, total RAM 515612 MB
2024-12-18T04:07:00.198839 - pytorch version: 2.0.1+cu118
2024-12-18T04:07:00.730713 - xformers version: 0.0.22
2024-12-18T04:07:00.731007 - Set vram state to: NORMAL_VRAM
2024-12-18T04:07:00.731239 - Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
2024-12-18T04:07:01.007855 - Using xformers cross attention
2024-12-18T04:07:03.618228 - [Prompt Server] web root: /workspace/ComfyUI/web
2024-12-18T04:07:04.582115 - __name__ : ComfyUI_node_Lilly2024-12-18T04:07:04.582287 - 
2024-12-18T04:07:04.582448 - __file__ : /workspace/ComfyUI/custom_nodes/ComfyUI_node_Lilly/__init__.py2024-12-18T04:07:04.582570 - 
2024-12-18T04:07:04.582741 - os.path.basename(__file__) : __init__.py2024-12-18T04:07:04.582833 - 
2024-12-18T04:07:04.582976 - os.path.splitext(os.path.basename(__file__))[0] : __init__2024-12-18T04:07:04.583096 - 
2024-12-18T04:07:04.583228 - working directory : 2024-12-18T04:07:04.583407 -  2024-12-18T04:07:04.583531 - /workspace/ComfyUI2024-12-18T04:07:04.583662 - 
2024-12-18T04:07:04.681007 - ─────────────────────────────────  init start  ─────────────────────────────────
2024-12-18T04:07:04.702232 - __name__ : custom_nodes.ComfyUI_node_Lilly2024-12-18T04:07:04.702351 - 
2024-12-18T04:07:04.702429 - __file__ : /workspace/ComfyUI/custom_nodes/ComfyUI_node_Lilly/__init__.py2024-12-18T04:07:04.702488 - 
2024-12-18T04:07:04.702546 - os.path.basename(__file__) : __init__.py2024-12-18T04:07:04.702615 - 
2024-12-18T04:07:04.702728 - os.path.splitext(os.path.basename(__file__))[0] : __init__2024-12-18T04:07:04.702796 - 
2024-12-18T04:07:04.702862 - working directory : 2024-12-18T04:07:04.702925 -  2024-12-18T04:07:04.702992 - /workspace/ComfyUI2024-12-18T04:07:04.703101 - 
2024-12-18T04:07:04.734222 - [04:07:04] Load ok   : CheckpointLoaderRandom                     __init__.py:83
2024-12-18T04:07:04.761161 -            Load ok   : CheckpointLoaderSimpleText                 __init__.py:83
2024-12-18T04:07:04.792664 - [04:07:04] wildcards card_path :                                 wildcards.py:36
           /workspace/ComfyUI/custom_nodes/ComfyUI_node_Lilly/..                
           /../wildcards/**/*.txt                                               
2024-12-18T04:07:04.794764 -            cards file count :  0                                wildcards.py:187
2024-12-18T04:07:04.795561 -            wildcards test : aest                                wildcards.py:218
2024-12-18T04:07:04.796333 -            wildcards test : *test                               wildcards.py:219
2024-12-18T04:07:04.797100 -            wildcards test : ?est                                wildcards.py:220
2024-12-18T04:07:04.797854 -            wildcards test : test                                wildcards.py:221
2024-12-18T04:07:04.798677 -            wildcards test : /test                               wildcards.py:222
2024-12-18T04:07:04.799492 -            wildcards test : /0/test                             wildcards.py:223
2024-12-18T04:07:04.800297 -            Load ok   : CLIPTextEncodeWildcards                    __init__.py:83
2024-12-18T04:07:04.816835 -            Load ok   : LoraLoaderText                             __init__.py:83
2024-12-18T04:07:04.840081 -            Load ok   : LoraLoaderTextRandom                       __init__.py:83
2024-12-18T04:07:04.859260 -            Load ok   : Random_Sampler                             __init__.py:83
2024-12-18T04:07:04.874627 -            Load ok   : VAELoaderDecode                            __init__.py:83
2024-12-18T04:07:04.891052 -            Load ok   : VAELoaderText                              __init__.py:83
2024-12-18T04:07:04.913242 - Total VRAM 16102 MB, total RAM 515612 MB
2024-12-18T04:07:04.913466 - pytorch version: 2.0.1+cu118
2024-12-18T04:07:04.913654 - xformers version: 0.0.22
2024-12-18T04:07:04.913922 - Set vram state to: NORMAL_VRAM
2024-12-18T04:07:04.914138 - Device: cuda:0 NVIDIA RTX A4000 : cudaMallocAsync
2024-12-18T04:07:04.916351 -            Load ok   : SimpleSampler                              __init__.py:83
2024-12-18T04:07:04.929671 -            Load ok   : SaveImageSimple                            __init__.py:83
2024-12-18T04:07:04.942246 -            Load ok   : TextWildcards                              __init__.py:83
2024-12-18T04:07:04.943048 - ──────────────────────────────────  init end  ──────────────────────────────────
2024-12-18T04:07:05.572089 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: /workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts[0m
2024-12-18T04:07:05.572359 - [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
2024-12-18T04:07:05.572600 - [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
2024-12-18T04:07:06.124452 - ### Loading: ComfyUI-Impact-Subpack (V1.1)2024-12-18T04:07:06.124601 - 
2024-12-18T04:07:06.270082 - [Impact Subpack] ultralytics_bbox: /workspace/ComfyUI/models/ultralytics/bbox
2024-12-18T04:07:06.270337 - [Impact Subpack] ultralytics_segm: /workspace/ComfyUI/models/ultralytics/segm
2024-12-18T04:07:06.572240 - [36;20m[comfy_mtb] | INFO -> loaded [96m90[0m nodes successfuly[0m
2024-12-18T04:07:06.572907 - [36;20m[comfy_mtb] | INFO -> Some nodes (5) could not be loaded. This can be ignored, but go to http://0.0.0.0,:::3000/mtb if you want more information.[0m
2024-12-18T04:07:06.597113 - /venv/lib/python3.10/site-packages/torchvision/datapoints/__init__.py:12: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
2024-12-18T04:07:06.612019 - /venv/lib/python3.10/site-packages/torchvision/transforms/v2/__init__.py:54: UserWarning: The torchvision.datapoints and torchvision.transforms.v2 namespaces are still Beta. While we do not expect major breaking changes, some APIs may still change according to user feedback. Please submit any feedback you may have in this issue: https://github.com/pytorch/vision/issues/6753, and you can also check out https://github.com/pytorch/vision/issues/7319 to learn more about the APIs that we suspect might involve future changes. You can silence this warning by calling torchvision.disable_beta_transforms_warning().
  warnings.warn(_BETA_TRANSFORMS_WARNING)
2024-12-18T04:07:06.628537 - here: /workspace/ComfyUI/custom_nodes/ComfyUI-tbox2024-12-18T04:07:06.628648 - 
2024-12-18T04:07:06.634713 - Using ckpts path: /workspace/ComfyUI/custom_nodes/ComfyUI-tbox/../../models/annotator2024-12-18T04:07:06.634827 - 
2024-12-18T04:07:06.634930 - Using symlinks: False2024-12-18T04:07:06.635051 - 
2024-12-18T04:07:06.635156 - Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']2024-12-18T04:07:06.635245 - 
2024-12-18T04:07:06.807521 - Traceback (most recent call last):
  File "/workspace/ComfyUI/nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-tbox/__init__.py", line 26, in <module>
    from .nodes.face.face_enhance_node import GFPGANNode
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-tbox/nodes/face/face_enhance_node.py", line 7, in <module>
    from facefusion.yoloface_onnx import YoloFaceOnnx
  File "/workspace/ComfyUI/custom_nodes/ComfyUI-tbox/src/facefusion/yoloface_onnx.py", line 2, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'

2024-12-18T04:07:06.807797 - Cannot import /workspace/ComfyUI/custom_nodes/ComfyUI-tbox module for custom nodes: No module named 'onnx'
2024-12-18T04:07:06.857058 - ### Loading: ComfyUI-Impact-Pack (V8.0.1)2024-12-18T04:07:06.857186 - 
2024-12-18T04:07:07.012113 - [Impact Pack] Wildcards loading done.2024-12-18T04:07:07.012318 - 
2024-12-18T04:07:07.034071 - ### Loading: ComfyUI-Manager (V2.55.5)2024-12-18T04:07:07.034205 - 
2024-12-18T04:07:08.228274 - ### ComfyUI Version: v0.3.7-47-gca457f7 | Released on '2024-12-17'2024-12-18T04:07:08.228514 - 
2024-12-18T04:07:08.270650 - 
Import times for custom nodes:
2024-12-18T04:07:08.270992 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/websocket_image_save.py
2024-12-18T04:07:08.271206 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_essentials
2024-12-18T04:07:08.271424 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
2024-12-18T04:07:08.271628 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/tiled_ksampler
2024-12-18T04:07:08.271828 -    0.0 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-OtherVAEs
2024-12-18T04:07:08.272065 -    0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
2024-12-18T04:07:08.272266 -    0.1 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Subpack
2024-12-18T04:07:08.272477 -    0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
2024-12-18T04:07:08.272672 -    0.2 seconds (IMPORT FAILED): /workspace/ComfyUI/custom_nodes/ComfyUI-tbox
2024-12-18T04:07:08.272873 -    0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
2024-12-18T04:07:08.273109 -    0.2 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-KJNodes
2024-12-18T04:07:08.273309 -    0.3 seconds: /workspace/ComfyUI/custom_nodes/comfy_mtb
2024-12-18T04:07:08.273519 -    0.4 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI_node_Lilly
2024-12-18T04:07:08.273717 -    0.6 seconds: /workspace/ComfyUI/custom_nodes/comfyui_controlnet_aux
2024-12-18T04:07:08.273892 -    1.3 seconds: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager
2024-12-18T04:07:08.274123 - 
2024-12-18T04:07:08.316837 - Starting server

2024-12-18T04:07:08.317452 - To see the GUI go to: http://0.0.0.0:3000
2024-12-18T04:07:08.317895 - To see the GUI go to: http://[::]:3000
2024-12-18T04:07:08.429001 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json2024-12-18T04:07:08.429113 - 
2024-12-18T04:07:08.469523 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json2024-12-18T04:07:08.469658 - 
2024-12-18T04:07:08.526755 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json2024-12-18T04:07:08.526874 - 
2024-12-18T04:07:08.675271 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json2024-12-18T04:07:08.675508 - 
2024-12-18T04:07:08.747279 - [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json2024-12-18T04:07:08.747532 - 
2024-12-18T04:08:15.890625 - FETCH DATA from: /workspace/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json2024-12-18T04:08:15.890703 - 2024-12-18T04:08:15.903289 -  [DONE]2024-12-18T04:08:15.903517 - 
2024-12-18T04:08:17.392987 - [ERROR] An error occurred while retrieving information for the 'VAELoaderText' node.
2024-12-18T04:08:17.399811 - Traceback (most recent call last):
  File "/workspace/ComfyUI/server.py", line 579, in get_object_info
    out[x] = node_info(x)
  File "/workspace/ComfyUI/server.py", line 546, in node_info
    info['input'] = obj_class.INPUT_TYPES()
  File "/workspace/ComfyUI/custom_nodes/ComfyUI_node_Lilly/VAELoaderText.py", line 18, in INPUT_TYPES
    "default": random.choice(folder_paths.get_filename_list("vae"))
  File "/usr/lib/python3.10/random.py", line 378, in choice
    return seq[self._randbelow(len(seq))]
IndexError: list index out of range

2024-12-18T04:08:46.321221 - got prompt
2024-12-18T04:08:47.914078 - model weight dtype torch.float16, manual cast: None
2024-12-18T04:08:47.918667 - model_type EPS
2024-12-18T04:08:49.095772 - Using xformers attention in VAE
2024-12-18T04:08:49.097746 - Using xformers attention in VAE
2024-12-18T04:08:49.466349 - Requested to load SD1ClipModel
2024-12-18T04:08:49.540909 - loaded completely 9.5367431640625e+25 235.84423828125 True
2024-12-18T04:08:49.654789 - Requested to load BaseModel
2024-12-18T04:08:50.013330 - loaded completely 9.5367431640625e+25 1639.406135559082 True
2024-12-18T04:08:50.031468 - 
  0%|          | 0/20 [00:00<?, ?it/s]2024-12-18T04:08:50.158228 - /venv/lib/python3.10/site-packages/torch/nn/modules/conv.py:459: UserWarning: Applied workaround for CuDNN issue, install nvrtc.so (Triggered internally at ../aten/src/ATen/native/cudnn/Conv_v8.cpp:80.)
  return F.conv2d(input, weight, bias, self.stride,
2024-12-18T04:08:51.513759 - 
 95%|█████████▌| 19/20 [00:01<00:00, 15.66it/s]2024-12-18T04:08:51.576463 - 
100%|██████████| 20/20 [00:01<00:00, 12.95it/s]2024-12-18T04:08:51.576667 - 
2024-12-18T04:08:51.583314 - Requested to load AutoencoderKL
2024-12-18T04:08:51.611105 - loaded completely 9.5367431640625e+25 159.55708122253418 True
2024-12-18T04:08:51.722607 - !!! Exception during processing !!! 'float' object is not subscriptable
2024-12-18T04:08:51.736516 - Traceback (most recent call last):
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 66, in interpolate_up
    return torch.nn.functional.interpolate(x, scale_factor=scale_factor, mode="nearest")
  File "/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/nodes.py", line 285, in decode
    images = vae.decode(samples["samples"])
  File "/workspace/ComfyUI/comfy/sd.py", line 446, in decode
    out = self.process_output(self.first_stage_model.decode(samples).to(self.output_device).float())
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 112, in forward
    x = interpolate_up(x, self.scale_factor)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 71, in interpolate_up
    out_shape.append(round(orig_shape[i + 2] * scale_factor[i]))
TypeError: 'float' object is not subscriptable

2024-12-18T04:08:51.738665 - Prompt executed in 5.41 seconds
2024-12-18T04:09:22.983833 - got prompt
2024-12-18T04:09:24.271769 - 
100%|██████████| 20/20 [00:01<00:00, 16.12it/s]2024-12-18T04:09:24.272088 - 
100%|██████████| 20/20 [00:01<00:00, 15.95it/s]2024-12-18T04:09:24.272283 - 
2024-12-18T04:09:24.314018 - !!! Exception during processing !!! 'float' object is not subscriptable
2024-12-18T04:09:24.323089 - Traceback (most recent call last):
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 66, in interpolate_up
    return torch.nn.functional.interpolate(x, scale_factor=scale_factor, mode="nearest")
  File "/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/custom_nodes/comfy_mtb/nodes/model.py", line 55, in decode
    vae.decode_tiled(
  File "/workspace/ComfyUI/comfy/sd.py", line 481, in decode_tiled
    output = self.decode_tiled_(samples, **args)
  File "/workspace/ComfyUI/comfy/sd.py", line 404, in decode_tiled_
    (comfy.utils.tiled_scale(samples, decode_fn, tile_x // 2, tile_y * 2, overlap, upscale_amount = self.upscale_ratio, output_device=self.output_device, pbar = pbar) +
  File "/workspace/ComfyUI/comfy/utils.py", line 831, in tiled_scale
    return tiled_scale_multidim(samples, function, (tile_y, tile_x), overlap, upscale_amount, out_channels, output_device, pbar)
  File "/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/utils.py", line 803, in tiled_scale_multidim
    ps = function(s_in).to(output_device)
  File "/workspace/ComfyUI/comfy/sd.py", line 402, in <lambda>
    decode_fn = lambda a: self.first_stage_model.decode(a.to(self.vae_dtype).to(self.device)).float()
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 112, in forward
    x = interpolate_up(x, self.scale_factor)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 71, in interpolate_up
    out_shape.append(round(orig_shape[i + 2] * scale_factor[i]))
TypeError: 'float' object is not subscriptable

2024-12-18T04:09:24.326370 - Prompt executed in 1.34 seconds
2024-12-18T04:09:36.477123 - got prompt
2024-12-18T04:09:38.653397 - model weight dtype torch.float16, manual cast: None
2024-12-18T04:09:38.653917 - model_type V_PREDICTION
2024-12-18T04:09:39.680800 - Using xformers attention in VAE
2024-12-18T04:09:39.682011 - Using xformers attention in VAE
2024-12-18T04:09:39.984901 - Requested to load SD2ClipModel
2024-12-18T04:09:40.081630 - loaded completely 9.5367431640625e+25 675.263671875 True
2024-12-18T04:09:40.181017 - Requested to load BaseModel
2024-12-18T04:09:40.415190 - loaded completely 9.5367431640625e+25 1651.593635559082 True
2024-12-18T04:09:41.675676 - 
100%|██████████| 20/20 [00:01<00:00, 15.97it/s]2024-12-18T04:09:41.676003 - 
100%|██████████| 20/20 [00:01<00:00, 15.94it/s]2024-12-18T04:09:41.676184 - 
2024-12-18T04:09:41.679265 - Requested to load AutoencoderKL
2024-12-18T04:09:41.707256 - loaded completely 9.5367431640625e+25 159.55708122253418 True
2024-12-18T04:09:41.719142 - !!! Exception during processing !!! 'float' object is not subscriptable
2024-12-18T04:09:41.741663 - Traceback (most recent call last):
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 66, in interpolate_up
    return torch.nn.functional.interpolate(x, scale_factor=scale_factor, mode="nearest")
  File "/venv/lib/python3.10/site-packages/torch/nn/functional.py", line 3931, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: "upsample_nearest2d_out_frame" not implemented for 'BFloat16'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/workspace/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/workspace/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/workspace/ComfyUI/custom_nodes/comfy_mtb/nodes/model.py", line 55, in decode
    vae.decode_tiled(
  File "/workspace/ComfyUI/comfy/sd.py", line 481, in decode_tiled
    output = self.decode_tiled_(samples, **args)
  File "/workspace/ComfyUI/comfy/sd.py", line 404, in decode_tiled_
    (comfy.utils.tiled_scale(samples, decode_fn, tile_x // 2, tile_y * 2, overlap, upscale_amount = self.upscale_ratio, output_device=self.output_device, pbar = pbar) +
  File "/workspace/ComfyUI/comfy/utils.py", line 831, in tiled_scale
    return tiled_scale_multidim(samples, function, (tile_y, tile_x), overlap, upscale_amount, out_channels, output_device, pbar)
  File "/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/utils.py", line 803, in tiled_scale_multidim
    ps = function(s_in).to(output_device)
  File "/workspace/ComfyUI/comfy/sd.py", line 402, in <lambda>
    decode_fn = lambda a: self.first_stage_model.decode(a.to(self.vae_dtype).to(self.device)).float()
  File "/workspace/ComfyUI/comfy/ldm/models/autoencoder.py", line 209, in decode
    dec = self.decoder(dec, **decoder_kwargs)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 723, in forward
    h = self.up[i_level].upsample(h)
  File "/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 112, in forward
    x = interpolate_up(x, self.scale_factor)
  File "/workspace/ComfyUI/comfy/ldm/modules/diffusionmodules/model.py", line 71, in interpolate_up
    out_shape.append(round(orig_shape[i + 2] * scale_factor[i]))
TypeError: 'float' object is not subscriptable
```

**Comment by Raykarr** [comment]
same error

**Comment by comfyanonymous** [comment]
[Update your pytorch.](https://github.com/comfyanonymous/ComfyUI/commit/4c5c4ddedaba071872cc25ceaf3aaec25795562d)
