### ISSUE TITLE
Can't launch ComfyUI since December 19th update

### ISSUE THREAD

**Issue by pipCloneMe** [comfyanonymous/ComfyUI#6120]
### Your question

What's the solution for AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### Logs

```powershell
D:\generative\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
DEPRECATION: Loading egg at d:\generative\comfyui_windows_portable\python_embeded\lib\site-packages\sageattention-2.0.0-py3.12-win-amd64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-19 17:41:28.966915
** Platform: Windows
** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
** Python executable: D:\generative\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\generative\ComfyUI_windows_portable\ComfyUI
** Log path: D:\generative\ComfyUI_windows_portable\comfyui.log
DEPRECATION: Loading egg at d:\generative\comfyui_windows_portable\python_embeded\lib\site-packages\sageattention-2.0.0-py3.12-win-amd64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at d:\generative\comfyui_windows_portable\python_embeded\lib\site-packages\sageattention-2.0.0-py3.12-win-amd64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330

Prestartup times for custom nodes:
   0.0 seconds: D:\generative\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\generative\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Easy-Use
   0.0 seconds: D:\generative\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Marigold
   6.6 seconds: D:\generative\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 65448 MB
pytorch version: 2.5.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Traceback (most recent call last):
  File "D:\generative\ComfyUI_windows_portable\ComfyUI\main.py", line 132, in <module>
    import execution
  File "D:\generative\ComfyUI_windows_portable\ComfyUI\execution.py", line 13, in <module>
    import nodes
  File "D:\generative\ComfyUI_windows_portable\ComfyUI\nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "D:\generative\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\generative\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 10, in <module>
    from .ldm.cascade.stage_c_coder import StageC_coder
  File "D:\generative\ComfyUI_windows_portable\ComfyUI\comfy\ldm\cascade\stage_c_coder.py", line 19, in <module>
    import torchvision
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\__init__.py", line 10, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils  # usort:skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\models\__init__.py", line 2, in <module>
    from .convnext import *
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\models\convnext.py", line 8, in <module>
    from ..ops.misc import Conv2dNormActivation, Permute
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\__init__.py", line 23, in <module>
    from .poolers import MultiScaleRoIAlign
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\poolers.py", line 10, in <module>
    from .roi_align import roi_align
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torchvision\ops\roi_align.py", line 7, in <module>
    from torch._dynamo.utils import is_compile_supported
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\__init__.py", line 3, in <module>
    from . import convert_frame, eval_frame, resume_execution
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\convert_frame.py", line 31, in <module>
    from torch._dynamo.utils import CompileTimeInstructionCounter
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\_dynamo\utils.py", line 1320, in <module>
    if has_triton_package():
       ^^^^^^^^^^^^^^^^^^^^
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\utils\_triton.py", line 9, in has_triton_package
    from triton.compiler.compiler import triton_key
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\__init__.py", line 20, in <module>
    from .runtime import (
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\__init__.py", line 1, in <module>
    from .autotuner import (Autotuner, Config, Heuristics, autotune, heuristics)
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\autotuner.py", line 9, in <module>
    from ..testing import do_bench, do_bench_cudagraph
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\testing.py", line 7, in <module>
    from . import language as tl
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\language\__init__.py", line 4, in <module>
    from . import math
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\language\math.py", line 1, in <module>
    from . import core
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\language\core.py", line 10, in <module>
    from ..runtime.jit import jit
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\jit.py", line 12, in <module>
    from ..runtime.driver import driver
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\driver.py", line 1, in <module>
    from ..backends import backends
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 50, in <module>
    backends = _discover_backends()
               ^^^^^^^^^^^^^^^^^^^^
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 44, in _discover_backends
    driver = _load_module(name, os.path.join(root, name, 'driver.py'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\__init__.py", line 12, in _load_module
    spec.loader.exec_module(module)
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\backends\amd\driver.py", line 7, in <module>
    from triton.runtime.build import _build
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\triton\runtime\build.py", line 8, in <module>
    import setuptools
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
    import setuptools.version
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\setuptools\version.py", line 1, in <module>
    import pkg_resources
  File "D:\generative\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

D:\generative\ComfyUI_windows_portable>pause
Press any key to continue . . .
```

**Comment by pipCloneMe** [comment]
Solved by upgrading setuptools:
python_embeded\python.exe -m pip install --upgrade setuptools
python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build

**Comment by pipCloneMe** [comment]
Solved by upgrading setuptools:
python_embeded\python.exe -m pip install --upgrade setuptools
python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
