### ISSUE TITLE
How to solve this node error problem?

### ISSUE THREAD

**Issue by 112473228** [comfyanonymous/ComfyUI#6146]
### Expected Behavior

I am the desktop version of ComfyUI 0.40。  我在测试下面这个工作流
[ltxvideo-t2v.json](https://github.com/user-attachments/files/18218919/ltxvideo-t2v.json)

### Actual Behavior

<img width="453" alt="1734792710851" src="https://github.com/user-attachments/assets/e511548f-9f17-443a-a0db-fe7bc9a966c8" />

### Steps to Reproduce

[ltxvideo-t2v.json](https://github.com/user-attachments/files/18218918/ltxvideo-t2v.json)

### Debug Logs

```powershell
Adding extra search path checkpoints E:\ComfyUI\models\checkpoints\
Adding extra search path classifiers E:\ComfyUI\models\classifiers\
Adding extra search path clip E:\ComfyUI\models\clip\
Adding extra search path clip_vision E:\ComfyUI\models\clip_vision\
Adding extra search path configs E:\ComfyUI\models\configs\
Adding extra search path controlnet E:\ComfyUI\models\controlnet\
Adding extra search path diffusers E:\ComfyUI\models\diffusers\
Adding extra search path diffusion_models E:\ComfyUI\models\diffusion_models\
Adding extra search path embeddings E:\ComfyUI\models\embeddings\
Adding extra search path gligen E:\ComfyUI\models\gligen\
Adding extra search path hypernetworks E:\ComfyUI\models\hypernetworks\
Adding extra search path loras E:\ComfyUI\models\loras\
Adding extra search path photomaker E:\ComfyUI\models\photomaker\
Adding extra search path style_models E:\ComfyUI\models\style_models\
Adding extra search path unet E:\ComfyUI\models\unet\
Adding extra search path upscale_models E:\ComfyUI\models\upscale_models\
Adding extra search path vae E:\ComfyUI\models\vae\
Adding extra search path vae_approx E:\ComfyUI\models\vae_approx\
Adding extra search path animatediff_models E:\ComfyUI\models\animatediff_models\
Adding extra search path animatediff_motion_lora E:\ComfyUI\models\animatediff_motion_lora\
Adding extra search path animatediff_video_formats E:\ComfyUI\models\animatediff_video_formats\
Adding extra search path ipadapter E:\ComfyUI\models\ipadapter\
Adding extra search path liveportrait E:\ComfyUI\models\liveportrait\
Adding extra search path insightface E:\ComfyUI\models\insightface\
Adding extra search path layerstyle E:\ComfyUI\models\layerstyle\
Adding extra search path LLM E:\ComfyUI\models\LLM\
Adding extra search path Joy_caption E:\ComfyUI\models\Joy_caption\
Adding extra search path sams E:\ComfyUI\models\sams\
Adding extra search path blip E:\ComfyUI\models\blip\
Adding extra search path CogVideo E:\ComfyUI\models\CogVideo\
Adding extra search path xlabs E:\ComfyUI\models\xlabs\
Adding extra search path instantid E:\ComfyUI\models\instantid\
Adding extra search path custom_nodes E:\ComfyUI\custom_nodes/
Adding extra search path download_model_base E:\ComfyUI\models
Setting output directory to: E:\ComfyUI\output
Setting input directory to: E:\ComfyUI\input
Setting user directory to: E:\ComfyUI\user
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-21 23:09:37.262261
** Platform: Windows
** Python version: 3.12.4 (main, Jul 25 2024, 21:57:00) [MSC v.1929 64 bit (AMD64)]
** Python executable: E:\ComfyUI\.venv\Scripts\python.exe
** ComfyUI Path: C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI
** Log path: E:\ComfyUI\comfyui.log

Prestartup times for custom nodes:
   2.7 seconds: C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24563 MB, total RAM 65305 MB
pytorch version: 2.5.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using pytorch attention
[Prompt Server] web root: C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\web_custom_versions\desktop_app
Total VRAM 24563 MB, total RAM 65305 MB
pytorch version: 2.5.1+cu121
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
[comfy_mtb] | INFO -> loaded 76 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (19) could not be loaded. This can be ignored, but go to http://127.0.0.1:8000/mtb if you want more information.
### Loading: ComfyUI-Manager (V2.55.3)
### ComfyUI Revision: UNKNOWN (The currently installed ComfyUI is not a Git repository)

Import times for custom nodes:
   0.0 seconds: C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: E:\ComfyUI\custom_nodes/ComfyUI_Text_Translation
   0.0 seconds: E:\ComfyUI\custom_nodes/ComfyUI-Custom-Scripts
   0.0 seconds: C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager
   0.1 seconds: E:\ComfyUI\custom_nodes/ComfyUI-VideoHelperSuite
   0.1 seconds: E:\ComfyUI\custom_nodes/comfy_mtb
   0.1 seconds: E:\ComfyUI\custom_nodes/ComfyUI-KJNodes
   0.2 seconds: E:\ComfyUI\custom_nodes/comfyui-tensorops
   0.2 seconds: E:\ComfyUI\custom_nodes/ComfyUI-LTXVideo
   0.3 seconds: E:\ComfyUI\custom_nodes/ComfyUI-Florence2

Starting server

To see the GUI go to: http://127.0.0.1:8000
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
 [DONE]
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
Traceback (most recent call last):
  File "C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\server.py", line 579, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\server.py", line 546, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\custom_nodes/ComfyUI-Florence2\nodes.py", line 150, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI\uv-cache\cpython-3.12.4-windows-x86_64-none\Lib\pathlib.py", line 1056, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\Users\\GUO\\AppData\\Local\\Programs\\comfyui-electron\\resources\\ComfyUI\\models\\LLM'

[comfy_mtb] | INFO -> Found multiple match, we will pick the last C:\Users\GUO\AppData\Local\Programs\comfyui-electron\resources\ComfyUI\models\upscale_models
['E:\\ComfyUI\\models\\upscale_models\\', 'C:\\Users\\GUO\\AppData\\Local\\Programs\\comfyui-electron\\resources\\ComfyUI\\models\\upscale_models']
```

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-Florence2 repo.
https://github.com/kijai/ComfyUI-Florence2
