### ISSUE TITLE
The mask editor isn't working

### ISSUE THREAD

**Issue by juanml82** [comfyanonymous/ComfyUI#6160]
### Expected Behavior

Use the default load image node to load an image and the open mask editor window to mask the face, then inpaint a different face in there.

### Actual Behavior

Either the image doesn't show up in the mask editor (it's all a black canvas the size of the image), or it does, but the save to node button does nothing: upon closing the mask editor, the image is shown unmasked in the load image node, and inpainting doesn't work. Using the mask to image nodes shows no mask has been created.
![Captura de pantalla 2024-12-22 113523](https://github.com/user-attachments/assets/0d6ebb77-47b3-4117-bc0f-ab3497e4f72f)
![Captura de pantalla 2024-12-22 113512](https://github.com/user-attachments/assets/42c78cf5-9973-4087-a439-169cfdc6cbab)
![Captura de pantalla 2024-12-22 113446](https://github.com/user-attachments/assets/9e0e1c0f-3248-4ca2-a14a-de3bda8dab49)

### Steps to Reproduce

[inpaint-simple V2.json](https://github.com/user-attachments/files/18222249/inpaint-simple.V2.json)
Use this workflow, try to create a mask and change the sphinx face
![ComfyUI_temp_hyvdq_00001_](https://github.com/user-attachments/assets/96fbeaa4-9eed-4093-92a0-e2be41a54963)

### Debug Logs

```powershell
C:\Comfyui>python main.py --auto-launch --use-split-cross-attention
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-12-22 11:45:01.679329
** Platform: Windows
** Python version: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
** Python executable: C:\Users\juanm\AppData\Local\Programs\Python\Python311\python.exe
** ComfyUI Path: C:\Comfyui
** Log path: C:\Comfyui\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: C:\Comfyui\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Easy-Use
   5.3 seconds: C:\Comfyui\custom_nodes\ComfyUI-Manager

Total VRAM 24575 MB, total RAM 32680 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
Using xformers attention
[Prompt Server] web root: C:\Comfyui\web
C:\Users\juanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
Error:
[WinError 1314] El cliente no dispone de un privilegio requerido: 'C:\\Comfyui\\custom_nodes\\ComfyLiterals\\js' -> 'C:\\Comfyui\\web\\extensions\\ComfyLiterals'
Failed to create symlink to C:\Comfyui\web\extensions\ComfyLiterals. Please copy the folder manually.
Source: C:\Comfyui\custom_nodes\ComfyLiterals\js
Target: C:\Comfyui\web\extensions\ComfyLiterals
[Allor]: 0 nodes were overridden.
[Allor]: 12 modules were enabled.
[Allor]: 98 nodes were loaded.
Adding C:\Comfyui\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from C:\Comfyui\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from C:\Comfyui\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from C:\Comfyui\custom_nodes\ComfyUI-Advanced-ControlNet
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from C:\Comfyui\custom_nodes\ComfyUI_IPAdapter_plus
Loaded VideoHelperSuite from C:\Comfyui\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V7.14.3)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.8)
[WARN] ComfyUI-Impact-Pack: custom_wildcards path not found: C:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\..\..\custom_wildcards. Using default path.
### Loading: ComfyUI-Impact-Pack (V7.14.3)
Loaded ImpactPack nodes from C:\Comfyui\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
ConDelta Nodes: Loaded
[Crystools INFO] Crystools version: 1.21.0
[Crystools INFO] CPU: AMD Ryzen 5 3600 6-Core Processor - Arch: AMD64 - OS: Windows 10
[Crystools INFO] Pynvml (Nvidia) initialized.
[Crystools INFO] GPU/s:
[Crystools INFO] 0) NVIDIA GeForce RTX 3090
[Crystools INFO] NVIDIA Driver: 566.36
C:\Users\juanm\AppData\Local\Programs\Python\Python311\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[ComfyUI-Easy-Use] server: v1.2.5 Loaded
[ComfyUI-Easy-Use] web root: C:\Comfyui\custom_nodes\ComfyUI-Easy-Use\web_version/v2 Loaded
Successfully imported omost_function from omost.py in the current directory
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\juanm\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
### Loading: ComfyUI-Impact-Pack (V7.14.3)
### Loading: ComfyUI-Inspire-Pack (V1.9)
[Impact Pack] Wildcards loading done.
UserWarning: A new version of Albumentations is available: 1.4.23 (you have 1.4.15). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
Total VRAM 24575 MB, total RAM 32680 MB
pytorch version: 2.5.1+cu124
xformers version: 0.0.28.post3
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.55.4)
### ComfyUI Version: v0.3.9-10-g57f330c | Released on '2024-12-22'
OpenPose Editor: Loaded
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Openpose Editor Plus: Loaded
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[SD Prompt Reader] Node version: 1.3.4
[SD Prompt Reader] Core version: 1.3.5
Nvidia APEX normalization not installed, using PyTorch LayerNorm
[ReActor] - STATUS - Running v0.5.2-a1 in ComfyUI
Torch version: 2.5.1+cu124
here: C:\Comfyui\custom_nodes\ComfyUI-tbox
Using ckpts path: C:\Comfyui\custom_nodes\ComfyUI-tbox\..\..\models\annotator
Using symlinks: False
Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
C:\Comfyui
############################################
C:\Comfyui\custom_nodes\ComfyUI-Universal-Styler\CSV
############################################
['C:\\Comfyui\\custom_nodes\\ComfyUI-Universal-Styler\\CSV\\naifilters.csv', 'C:\\Comfyui\\custom_nodes\\ComfyUI-Universal-Styler\\CSV\\naistyles.csv', 'C:\\Comfyui\\custom_nodes\\ComfyUI-Universal-Styler\\CSV\\naitypes.csv']
############################################
(pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
(pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
Traceback (most recent call last):
  File "C:\Comfyui\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfyui\custom_nodes\comfyui-web-viewer-main\__init__.py", line 6, in <module>
    from .nodes.osc_control_nodes import *
  File "C:\Comfyui\custom_nodes\comfyui-web-viewer-main\nodes\osc_control_nodes.py", line 3, in <module>
    from pythonosc import dispatcher, osc_server
ModuleNotFoundError: No module named 'pythonosc'

Cannot import C:\Comfyui\custom_nodes\comfyui-web-viewer-main module for custom nodes: No module named 'pythonosc'
[12/22/24 11:45:20] WARNING  Your inference package version 0.9.13 is out of date! Please upgrade to      __init__.py:35
                             version 0.32.0 of inference for the latest features and bug fixes by running
                             `pip install --upgrade inference`.
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
Davemane42 Custom Nodes: Loaded
# 😺dzNodes: LayerStyle -> Cannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to https://github.com/chflame163/ComfyUI_LayerStyle/issues/5
Nimbus Nodes: Loaded
# ComfyUI_OmniGen_Nodes: -> Success loaded 4 nodes.
Traceback (most recent call last):
  File "C:\Comfyui\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS\__init__.py", line 5, in <module>
    from .parler_tts_node import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS\parler_tts_node.py", line 6, in <module>
    from .parler_tts import ParlerTTSForConditionalGeneration
  File "C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS\parler_tts\__init__.py", line 7, in <module>
    from .dac_wrapper import DACConfig, DACModel
  File "C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS\parler_tts\dac_wrapper\__init__.py", line 2, in <module>
    from .modeling_dac import DACModel
  File "C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS\parler_tts\dac_wrapper\modeling_dac.py", line 2, in <module>
    from ...dac.model import DAC
  File "C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS\dac\__init__.py", line 6, in <module>
    import audiotools
ModuleNotFoundError: No module named 'audiotools'

Cannot import C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS module for custom nodes: No module named 'audiotools'
[tinyterraNodes] Loaded
[comfy_mtb] | INFO -> loaded 91 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.

Initializing ControlAltAI Nodes
Traceback (most recent call last):
  File "C:\Comfyui\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Comfyui\\custom_nodes\\IP-Adapter-main\\__init__.py'

Cannot import C:\Comfyui\custom_nodes\IP-Adapter-main module for custom nodes: [Errno 2] No such file or directory: 'C:\\Comfyui\\custom_nodes\\IP-Adapter-main\\__init__.py'
Traceback (most recent call last):
  File "C:\Comfyui\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Comfyui\custom_nodes\LCM_Inpaint_Outpaint_Comfy\__init__.py", line 1, in <module>
    from .LCM_Nodes import NODE_CLASS_MAPPINGS
  File "C:\Comfyui\custom_nodes\LCM_Inpaint_Outpaint_Comfy\LCM_Nodes.py", line 9, in <module>
    from .LCM.LCM_reference_pipeline import LatentConsistencyModelPipeline_reference
  File "C:\Comfyui\custom_nodes\LCM_Inpaint_Outpaint_Comfy\LCM\LCM_reference_pipeline.py", line 33, in <module>
    from diffusers.models.unet_2d_blocks import CrossAttnDownBlock2D, CrossAttnUpBlock2D, DownBlock2D, UpBlock2D
ModuleNotFoundError: No module named 'diffusers.models.unet_2d_blocks'

Cannot import C:\Comfyui\custom_nodes\LCM_Inpaint_Outpaint_Comfy module for custom nodes: No module named 'diffusers.models.unet_2d_blocks'
Nvidia APEX normalization not installed, using PyTorch LayerNorm

[rgthree-comfy] Loaded 42 epic nodes. 🎉

WAS Node Suite: BlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.
WAS Node Suite: `CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\Comfyui\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 219 nodes successfully.

        "The best revenge is massive success." - Frank Sinatra


Import times for custom nodes:
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_ADV_CLIP_emb
   0.0 seconds: C:\Comfyui\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Crystools-save
   0.0 seconds (IMPORT FAILED): C:\Comfyui\custom_nodes\IP-Adapter-main
   0.0 seconds: C:\Comfyui\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\Comfyui\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-InstantIDUtils
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Detail-Daemon
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Florence-2
   0.0 seconds: C:\Comfyui\custom_nodes\SD-Latent-Interposer
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-deepcache
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-image-round
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-load-image-from-url
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_AdvancedRefluxControl
   0.0 seconds: C:\Comfyui\custom_nodes\Comfyui_MiniCPMv2_6-prompt-generator
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Fluxpromptenhancer
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-ComfyCouple
   0.0 seconds: C:\Comfyui\custom_nodes\sigmas_tools_and_the_golden_scheduler
   0.0 seconds: C:\Comfyui\custom_nodes\cg-use-everywhere
   0.0 seconds: C:\Comfyui\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\Comfyui\custom_nodes\sd-dynamic-thresholding
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-ArteMoon
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Prompt-Preview
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUi_NNLatentUpscale
   0.0 seconds: C:\Comfyui\custom_nodes\Comfyui_joytag
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_Steudio
   0.0 seconds: C:\Comfyui\custom_nodes\image-resize-comfyui
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-copilot
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-ConDelta
   0.0 seconds: C:\Comfyui\custom_nodes\qq-nodes-comfyui
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Florence2
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Inpaint-CropAndStitch
   0.0 seconds: C:\Comfyui\custom_nodes\Skimmed_CFG
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Universal-Styler
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_Nimbus-Pack
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_Human_Parts
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-AutomaticCFG
   0.0 seconds: C:\Comfyui\custom_nodes\cg-image-picker
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_InstantID
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-WD14-Tagger
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_ZenID
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyLiterals
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui_controlnet_aux
   0.0 seconds: C:\Comfyui\custom_nodes\A8R8_ComfyUI_nodes
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-instantId-faceswap
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_Dave_CustomNode
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-ELLA
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-PixelResolutionCalculator
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-OpenPose-Editor
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-OmniGen
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-DiffusersLoader
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Openpose-Editor-Plus
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-model-dynamic-loader
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-DiffusersImageOutpaint
   0.0 seconds: C:\Comfyui\custom_nodes\images-grid-comfy-plugin-main
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-TiledDiffusion
   0.0 seconds: C:\Comfyui\custom_nodes\images-grid-comfy-plugin
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_Soze
   0.0 seconds: C:\Comfyui\custom_nodes\DistanceSampler-main
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-LTXTricks
   0.0 seconds: C:\Comfyui\custom_nodes\comfy-image-saver
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-layerdiffuse
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Transformers
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-ScheduledGuider-Ext
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-various
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-inpaint-nodes
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-post-processing-nodes
   0.0 seconds: C:\Comfyui\custom_nodes\mikey_nodes
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-DepthAnythingV2
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyMath
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_essentials
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-browser
   0.0 seconds: C:\Comfyui\custom_nodes\Comfy_KepListStuff
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-MochiEdit
   0.0 seconds: C:\Comfyui\custom_nodes\ControlAltAI-Nodes
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Chibi-Nodes
   0.0 seconds (IMPORT FAILED): C:\Comfyui\custom_nodes\LCM_Inpaint_Outpaint_Comfy
   0.0 seconds: C:\Comfyui\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\Comfyui\custom_nodes\x-flux-comfyui
   0.0 seconds (IMPORT FAILED): C:\Comfyui\custom_nodes\ComfyUI_ParlerTTS
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-MochiWrapper
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Gemma
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-GGUF
   0.0 seconds: C:\Comfyui\custom_nodes\comfyui-prompt-reader-node
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-Whisper
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_OmniGen_Nodes
   0.0 seconds (IMPORT FAILED): C:\Comfyui\custom_nodes\comfyui-web-viewer-main
   0.0 seconds: C:\Comfyui\custom_nodes\rgthree-comfy
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-HunyuanVideoWrapper
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_ExtraModels
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-LTXVideo
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\Comfyui\custom_nodes\ComfyUI-tbox
   0.1 seconds: C:\Comfyui\custom_nodes\ComfyUI_LayerStyle_Advance
   0.1 seconds: C:\Comfyui\custom_nodes\comfy_mtb
   0.1 seconds: C:\Comfyui\custom_nodes\ComfyUI_tinyterraNodes
   0.1 seconds: C:\Comfyui\custom_nodes\comfyui-ollama
   0.1 seconds: C:\Comfyui\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds: C:\Comfyui\custom_nodes\ComfyUI-segment-anything-2
   0.1 seconds: C:\Comfyui\custom_nodes\PuLID_ComfyUI
   0.1 seconds: C:\Comfyui\custom_nodes\comfyui-reactor-node
   0.1 seconds: C:\Comfyui\custom_nodes\ComfyUI-ppm
   0.1 seconds: C:\Comfyui\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
   0.2 seconds: C:\Comfyui\custom_nodes\ComfyUI_MileHighStyler
   0.2 seconds: C:\Comfyui\custom_nodes\comfyui-dynamicprompts
   0.2 seconds: C:\Comfyui\custom_nodes\ComfyUI-DDColor
   0.4 seconds: C:\Comfyui\custom_nodes\ComfyUI-Crystools
   0.5 seconds: C:\Comfyui\custom_nodes\ComfyUI-InstantID
   0.5 seconds: C:\Comfyui\custom_nodes\comfyui_fluxMileHighBeta
   0.7 seconds: C:\Comfyui\custom_nodes\comfyui_dagthomas
   0.7 seconds: C:\Comfyui\custom_nodes\ComfyUI-IF_AI_WishperSpeechNode
   0.8 seconds: C:\Comfyui\custom_nodes\ComfyUI-Manager
   0.8 seconds: C:\Comfyui\custom_nodes\ComfyUI_Primere_Nodes
   0.8 seconds: C:\Comfyui\custom_nodes\ComfyUI-Easy-Use
   0.8 seconds: C:\Comfyui\custom_nodes\ComfyUI-CogVideoXWrapper
   1.3 seconds: C:\Comfyui\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
   1.4 seconds: C:\Comfyui\custom_nodes\comfyui-art-venture
   1.4 seconds: C:\Comfyui\custom_nodes\ComfyUI-Allor
   1.9 seconds: C:\Comfyui\custom_nodes\ComfyUI-IF_AI_tools
   2.3 seconds: C:\Comfyui\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Comfyui\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[]
[]
got prompt
model weight dtype torch.float16, manual cast: None
model_type EPS
Using xformers attention in VAE
Using xformers attention in VAE
Requested to load SDXLClipModel
loaded completely 9.5367431640625e+25 1560.802734375 True
loaded straight to GPU
Requested to load SDXL
loaded completely 9.5367431640625e+25 4897.0483474731445 True
Processing interrupted
Prompt executed in 4.89 seconds
got prompt
Requested to load AutoencoderKL
loaded completely 9.5367431640625e+25 159.55708122253418 True
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:03<00:00,  6.56it/s]
Prompt executed in 5.04 seconds
```

**Comment by LukeG89** [comment]
The problem is probably caused by a custom node. To test that you can use `--disable-all-custom-nodes` command argument and try opening mask editor. 

BTW, now there is the new mask editor, why using the old one?

**Comment by juanml82** [comment]
I've used the --disable-all-custom-nodes command argument, and also tried in a brand new installation of comfyui without any custom node.
I was using the new mask editor, it had those issues. So I've change to the old one to check if that was the issue, it wasn't. I'm having the same issue in both the new and the old mask editor.

**Comment by LukeG89** [comment]
@juanml82 In this case I would open a bug report in the frontend repository, reporting the test you made (fresh install + no custom nodes): https://github.com/Comfy-Org/ComfyUI_frontend/issues/new/choose

Maybe the problem is related to something about your browser (maybe an extension?)

**Comment by juanml82** [comment]
It's now working. No idea why.
