### ISSUE TITLE
Control net is not loading; 'NoneType' object has no attribute 'copy'

### ISSUE THREAD

**Issue by maheshnathwani** [comfyanonymous/ComfyUI#6194]
### Expected Behavior

ControlNet model should be loaded and should be provided as input to Apply ControlNet

### Actual Behavior

Getting NoneType as input to Apply ControlNet

### Steps to Reproduce

![Screenshot 2024-12-24 at 5 52 42 AM](https://github.com/user-attachments/assets/7957b6ce-0098-43ef-a96e-e5ba92a9b4fe)

### Debug Logs

```powershell
# ComfyUI Error Report
## Error Details
- **Node ID:** 14
- **Node Type:** ControlNetApplyAdvanced
- **Exception Type:** AttributeError
- **Exception Message:** 'NoneType' object has no attribute 'copy'
## Stack Trace

  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)

  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)

```
## System Information
- **ComfyUI Version:** v0.3.9-17-gf18ebbd
- **Arguments:** main.py --listen --port 80
- **OS:** posix
- **Python Version:** 3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.1+cu121
## Devices

- **Name:** cuda:0 NVIDIA A100-SXM4-40GB : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 42481811456
  - **VRAM Free:** 40279877624
  - **Torch VRAM Total:** 1677721600
  - **Torch VRAM Free:** 32581624

## Logs
```
2024-12-24T00:07:24.025316 - Total VRAM 40514 MB, total RAM 85480 MB
2024-12-24T00:07:24.025409 - pytorch version: 2.5.1+cu121
2024-12-24T00:07:24.025962 - Set vram state to: NORMAL_VRAM
2024-12-24T00:07:24.026102 - Device: cuda:0 NVIDIA A100-SXM4-40GB : cudaMallocAsync
2024-12-24T00:07:25.106868 - Using pytorch attention
2024-12-24T00:07:26.179216 - [Prompt Server] web root: /content/ComfyUI/web
2024-12-24T00:07:26.803753 - 
Import times for custom nodes:
2024-12-24T00:07:26.803887 -    0.0 seconds: /content/ComfyUI/custom_nodes/websocket_image_save.py
2024-12-24T00:07:26.803944 - 
2024-12-24T00:07:26.813171 - Starting server

2024-12-24T00:07:26.813625 - To see the GUI go to: http://0.0.0.0:80
2024-12-24T00:07:26.813877 - To see the GUI go to: http://[::]:80
2024-12-24T00:08:22.507735 - got prompt
2024-12-24T00:08:23.935970 - model weight dtype torch.float16, manual cast: None
2024-12-24T00:08:23.936905 - model_type EPS
2024-12-24T00:08:25.182028 - Using pytorch attention in VAE
2024-12-24T00:08:25.183769 - Using pytorch attention in VAE
2024-12-24T00:08:25.455581 - Requested to load SDXLClipModel
2024-12-24T00:08:25.476719 - loaded completely 9.5367431640625e+25 1560.802734375 True
2024-12-24T00:08:26.754452 - error could not detect control model type.
2024-12-24T00:08:26.756787 - error checkpoint does not contain controlnet or t2i adapter data /content/ComfyUI/models/controlnet/controllllite_v01032064e_sdxl_canny.safetensors
2024-12-24T00:08:27.369758 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:08:27.370515 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:08:27.370922 - Prompt executed in 4.86 seconds
2024-12-24T00:08:53.884405 - got prompt
2024-12-24T00:08:54.944060 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:08:54.944341 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:08:54.944778 - Prompt executed in 1.06 seconds
2024-12-24T00:09:12.094310 - got prompt
2024-12-24T00:09:12.503361 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:09:12.503632 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:09:12.503995 - Prompt executed in 0.41 seconds
2024-12-24T00:09:38.139720 - got prompt
2024-12-24T00:09:38.470051 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:09:38.470321 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:09:38.470691 - Prompt executed in 0.33 seconds
2024-12-24T00:09:58.789765 - got prompt
2024-12-24T00:09:58.839217 - error could not detect control model type.
2024-12-24T00:09:58.842383 - error checkpoint does not contain controlnet or t2i adapter data /content/ComfyUI/models/controlnet/controlnetLlliteXLPD_sdxlEpoch20.safetensors
2024-12-24T00:09:58.846542 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:09:58.846788 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:09:58.847163 - Prompt executed in 0.05 seconds
2024-12-24T00:10:07.915728 - got prompt
2024-12-24T00:10:07.964436 - error could not detect control model type.
2024-12-24T00:10:07.967988 - error checkpoint does not contain controlnet or t2i adapter data /content/ComfyUI/models/controlnet/controllllite_v01032064e_sdxl_canny.safetensors
2024-12-24T00:10:07.972315 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:10:07.972549 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:10:07.972930 - Prompt executed in 0.05 seconds
2024-12-24T00:13:47.867684 - got prompt
2024-12-24T00:13:47.879326 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:13:47.879554 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:13:47.879992 - Prompt executed in 0.01 seconds
2024-12-24T00:14:23.880673 - got prompt
2024-12-24T00:14:23.893835 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:14:23.894065 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:14:23.894448 - Prompt executed in 0.01 seconds
2024-12-24T00:19:30.438623 - got prompt
2024-12-24T00:19:30.452299 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:19:30.452536 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:19:30.452900 - Prompt executed in 0.01 seconds
2024-12-24T00:19:52.616022 - got prompt
2024-12-24T00:19:52.627996 - !!! Exception during processing !!! 'NoneType' object has no attribute 'copy'
2024-12-24T00:19:52.628237 - Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "/content/ComfyUI/execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "/content/ComfyUI/execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "/content/ComfyUI/nodes.py", line 860, in apply_controlnet
    c_net = control_net.copy().set_cond_hint(control_hint, strength, (start_percent, end_percent), vae=vae, extra_concat=extra_concat)
AttributeError: 'NoneType' object has no attribute 'copy'

2024-12-24T00:19:52.628584 - Prompt executed in 0.01 seconds

```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":14,"last_link_id":20,"nodes":[{"id":7,"type":"CLIPTextEncode","pos":[413,389],"size":[425.27801513671875,180.6060791015625],"flags":{},"order":6,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":5}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[15],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["text, watermark"]},{"id":8,"type":"VAEDecode","pos":[1209,188],"size":[210,46],"flags":{},"order":9,"mode":0,"inputs":[{"name":"samples","type":"LATENT","link":7},{"name":"vae","type":"VAE","link":8}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[9],"slot_index":0}],"properties":{"Node name for S&R":"VAEDecode"},"widgets_values":[]},{"id":9,"type":"SaveImage","pos":[1451,189],"size":[210,58],"flags":{},"order":10,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":9}],"outputs":[],"properties":{},"widgets_values":["ComfyUI"]},{"id":10,"type":"LoadImage","pos":[33.70193099975586,648.414794921875],"size":[315,314],"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[10],"slot_index":0},{"name":"MASK","type":"MASK","links":null}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["WhatsApp Image 2024-12-23 at 11.16.15 (1).jpeg","image"]},{"id":3,"type":"KSampler","pos":[863,186],"size":[315,262],"flags":{},"order":8,"mode":0,"inputs":[{"name":"model","type":"MODEL","link":1},{"name":"positive","type":"CONDITIONING","link":16},{"name":"negative","type":"CONDITIONING","link":17},{"name":"latent_image","type":"LATENT","link":18}],"outputs":[{"name":"LATENT","type":"LATENT","links":[7],"slot_index":0}],"properties":{"Node name for S&R":"KSampler"},"widgets_values":[32186919752993,"randomize",20,8,"euler","normal",1]},{"id":5,"type":"EmptyLatentImage","pos":[473,609],"size":[315,106],"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"LATENT","type":"LATENT","links":[18],"slot_index":0}],"properties":{"Node name for S&R":"EmptyLatentImage"},"widgets_values":[512,512,1]},{"id":4,"type":"CheckpointLoaderSimple","pos":[26,474],"size":[315,98],"flags":{},"order":2,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[1],"slot_index":0},{"name":"CLIP","type":"CLIP","links":[3,5],"slot_index":1},{"name":"VAE","type":"VAE","links":[8],"slot_index":2}],"properties":{"Node name for S&R":"CheckpointLoaderSimple"},"widgets_values":["interiorSceneXL_v1.safetensors"]},{"id":6,"type":"CLIPTextEncode","pos":[415,186],"size":[422.84503173828125,164.31304931640625],"flags":{},"order":5,"mode":0,"inputs":[{"name":"clip","type":"CLIP","link":3}],"outputs":[{"name":"CONDITIONING","type":"CONDITIONING","links":[20],"slot_index":0}],"properties":{"Node name for S&R":"CLIPTextEncode"},"widgets_values":["minimalist wall with clock and an abstract art"]},{"id":14,"type":"ControlNetApplyAdvanced","pos":[1069.471923828125,867.72021484375],"size":[315,186],"flags":{},"order":7,"mode":0,"inputs":[{"name":"positive","type":"CONDITIONING","link":20},{"name":"negative","type":"CONDITIONING","link":15},{"name":"control_net","type":"CONTROL_NET","link":12},{"name":"image","type":"IMAGE","link":13},{"name":"vae","type":"VAE","link":null,"shape":7}],"outputs":[{"name":"positive","type":"CONDITIONING","links":[16],"slot_index":0},{"name":"negative","type":"CONDITIONING","links":[17],"slot_index":1}],"properties":{"Node name for S&R":"ControlNetApplyAdvanced"},"widgets_values":[1,0,1]},{"id":11,"type":"Canny","pos":[419.29931640625,774.983642578125],"size":[315,82],"flags":{},"order":4,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":10}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[13],"slot_index":0}],"properties":{"Node name for S&R":"Canny"},"widgets_values":[0.15,0.3]},{"id":13,"type":"ControlNetLoader","pos":[41.298946380615234,1041.827392578125],"size":[315,58],"flags":{},"order":3,"mode":0,"inputs":[],"outputs":[{"name":"CONTROL_NET","type":"CONTROL_NET","links":[12],"slot_index":0}],"properties":{"Node name for S&R":"ControlNetLoader"},"widgets_values":["controllllite_v01032064e_sdxl_canny.safetensors"]}],"links":[[1,4,0,3,0,"MODEL"],[3,4,1,6,0,"CLIP"],[5,4,1,7,0,"CLIP"],[7,3,0,8,0,"LATENT"],[8,4,2,8,1,"VAE"],[9,8,0,9,0,"IMAGE"],[10,10,0,11,0,"IMAGE"],[12,13,0,14,2,"CONTROL_NET"],[13,11,0,14,3,"IMAGE"],[15,7,0,14,1,"CONDITIONING"],[16,14,0,3,1,"CONDITIONING"],[17,14,1,3,2,"CONDITIONING"],[18,5,0,3,3,"LATENT"],[20,6,0,14,0,"CONDITIONING"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.6830134553650709,"offset":{"0":372.40875244140625,"1":-130.33468627929688}}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)
```


### Other

_No response_

**Comment by maheshnathwani** [comment]
I tried using multiple control nets
https://huggingface.co/lllyasviel/sd_control_collection/blob/main/kohya_controllllite_xl_canny.safetensors
https://civitai.com/models/380700/controlnet-lllite-xl-pd-canny-alpha
https://huggingface.co/kohya-ss/controlnet-lllite/blob/main/controllllite_v01032064e_sdxl_canny.safetensors

Was getting the same error for all of them

**Comment by LukeG89** [comment]
For controlllite, you have to use this node: [ControlNet-LLLite-ComfyUI](https://github.com/kohya-ss/ControlNet-LLLite-ComfyUI)
It's an experimental node, so I don't recommend it.

To use ControlNet with SDXL checkpoint, you need to use these models: https://civitai.com/models/136070/controlnetxl-cnxl

**Comment by maheshnathwani** [comment]
Thanks for the reply @LukeG89, I tried using this model (https://civitai.com/models/136070?modelVersionId=267493) but it led to the same error

**Comment by LukeG89** [comment]
Ah sorry, there are also controlllite models in the link, and you used a controlllite one again.

Since you are using canny as controlnet, try this one: https://civitai.com/models/136070?modelVersionId=519249

**Comment by maheshnathwani** [comment]
It worked! Thanks a lot!

**Comment by Lahi1200** [comment]
anyone knows how to fix this in flux
