### ISSUE TITLE
Fix documentation on how to run via WSL2, AMD 24.12.1 and Ubuntu 22.04

### ISSUE THREAD

**Issue by kelteseth** [comfyanonymous/ComfyUI#6201]
### Expected Behavior

The current docs result in a not working pytorch installation, should be:

```
(venv) root@DESKTOP-F2OM8NV:~/Code/ComfyUI# python main.py
Total VRAM 24493 MB, total RAM 32036 MB
pytorch version: 2.3.0+rocm6.2.3
Set vram state to: NORMAL_VRAM
Device: cuda:0 AMD Radeon RX 7900 XTX : native
```

### Actual Behavior

Current documentation results in:
```
(venv) root@DESKTOP-F2OM8NV:~/Code/ComfyUI# python main.py
Traceback (most recent call last):
  File "/root/Code/ComfyUI/main.py", line 136, in <module>
    import execution
  File "/root/Code/ComfyUI/execution.py", line 13, in <module>
    import nodes
  File "/root/Code/ComfyUI/nodes.py", line 22, in <module>
    import comfy.diffusers_load
  File "/root/Code/ComfyUI/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/root/Code/ComfyUI/comfy/sd.py", line 6, in <module>
    from comfy import model_management
  File "/root/Code/ComfyUI/comfy/model_management.py", line 145, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "/root/Code/ComfyUI/comfy/model_management.py", line 114, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "/root/Code/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 955, in current_device
    _lazy_init()
  File "/root/Code/ComfyUI/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 320, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No HIP GPUs are available
```

### Steps to Reproduce

Use the steps in the current comfyUI readme

### Debug Logs

```powershell
-
```

### Other

To fix this simply follow the instructions in https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html#install-methods

Tested this with Win11 23h2, AMD Driver 24.12.1, WSL2 Ubunto 22.04
1. Install rocm via https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-radeon.html
2. Create env and enable it
3.  Install pytorch via https://rocm.docs.amd.com/projects/radeon/en/latest/docs/install/wsl/install-pytorch.html#
4. python main.py

**Comment by mdsolarflare** [comment]
Not sure why doc update got closed as not planned when it's right, but this helped me fix my broken install. lol.

Thanks @kelteseth 

Win 11 (idk), AMD 25.x, WSL2 Ubuntu 24.04
