### ISSUE TITLE
 run GLIGEN fail 

### ISSUE THREAD

**Issue by Zlztai** [comfyanonymous/ComfyUI#621]
Today, I tried using GLIGEN ,but it doesn't work
My workflow and logs are as follows：

###################workflow############
[workflow.txt](https://github.com/comfyanonymous/ComfyUI/files/11405867/workflow.txt)

###################this is my log############
`
D:\work\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Trying to enable lowvram mode because your GPU seems to have 4GB or less. If you don't want this use: --normalvram
xformers version: 0.0.19
Set vram state to: LOW_VRAM
Using xformers cross attention
Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
LatentDiffusion: Running in eps-prediction mode
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is None and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 768 and using 8 heads.
DiffusionWrapper has 859.52 M params.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 320 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 320 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 640 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 640 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1280 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1280 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1280 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1280 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1280 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 1280 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 640 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 640 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 640, context_dim is 640 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 320 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 320 and using 8 heads.
Setting up MemoryEfficientCrossAttention. Query dim is 320, context_dim is 320 and using 8 heads.
  0%|                                                                                           | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "D:\work\ComfyUI_windows_portable\ComfyUI\execution.py", line 195, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 851, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\nodes.py", line 822, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\sample.py", line 79, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 669, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "D:\work\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\sampling.py", line 128, in sample_euler
    denoised = model(x, sigma_hat * s_in, **extra_args)
  File "D:\work\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 283, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options)
  File "D:\work\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 114, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\k_diffusion\external.py", line 140, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 271, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 250, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 155, in calc_cond_uncond_batch
    p = get_area_and_mult(x, x_in, cond_concat_in, timestep)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py", line 79, in get_area_and_mult
    gligen_patch = gligen_model.set_position(input_x.shape, gligen[2], input_x.device)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\gligen.py", line 280, in set_position
    return self._set_position(
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\gligen.py", line 247, in _set_position
    objs = self.position_net(boxes, masks, positive_embeddings)
  File "D:\work\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "D:\work\ComfyUI_windows_portable\ComfyUI\comfy\gligen.py", line 229, in forward
    masks + (1 - masks) * positive_null
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

`

**Comment by Zlztai** [comment]
well ,now it run  ok . thanks!! 😊😊😊
