### ISSUE TITLE
ExtraVAELoader No module named 'diffusers'

### ISSUE THREAD

**Issue by Minimidget007-WE** [comfyanonymous/ComfyUI#6232]
### Your question

![image](https://github.com/user-attachments/assets/3ecfc5a1-c332-4a3a-86b3-127dd58b8a08)
Got this issue saying it dont find module named diffusers but ive installed it and it says its installed asked on the nvidia github about this issue doesnt seem to get any responses for now

### Logs

```powershell
`## ComfyUI-Manager: installing dependencies done.
[2024-12-26 19:02:05.774] ** ComfyUI startup time: 2024-12-26 19:02:05.774148
[2024-12-26 19:02:05.810] ** Platform: Windows
[2024-12-26 19:02:05.810] ** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
[2024-12-26 19:02:05.811] ** Python executable: E:\AI_Image\ComfyUI_windows_portable_nvidia\python_embeded\python.exe
[2024-12-26 19:02:05.811] ** ComfyUI Path: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI
[2024-12-26 19:02:05.811] ** Log path: E:\AI_Image\ComfyUI_windows_portable_nvidia\comfyui.log
[2024-12-26 19:02:06.680] 
Prestartup times for custom nodes:
[2024-12-26 19:02:06.680]    1.9 seconds: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-12-26 19:02:06.680] 
Total VRAM 12288 MB, total RAM 16310 MB
[2024-12-26 19:02:08.390] pytorch version: 2.5.1+cu124
[2024-12-26 19:02:08.390] Set vram state to: NORMAL_VRAM
[2024-12-26 19:02:08.391] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-12-26 19:02:09.374] Using pytorch attention
[2024-12-26 19:02:10.666] [Prompt Server] web root: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\web
[2024-12-26 19:02:11.135] ### Loading: ComfyUI-Manager (V2.55.5)
[2024-12-26 19:02:11.261] ### ComfyUI Revision: 2953 [418eb706] *DETACHED | Released on '2024-12-20'
[2024-12-26 19:02:11.511] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-12-26 19:02:11.526] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-12-26 19:02:11.529] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-12-26 19:02:11.570] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-12-26 19:02:11.609] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-12-26 19:02:11.645] 
Import times for custom nodes:
[2024-12-26 19:02:11.645]    0.0 seconds: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\websocket_image_save.py
[2024-12-26 19:02:11.645]    0.0 seconds: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Gemma
[2024-12-26 19:02:11.645]    0.2 seconds: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels
[2024-12-26 19:02:11.645]    0.3 seconds: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-12-26 19:02:11.645] 
[2024-12-26 19:02:11.651] Starting server

[2024-12-26 19:02:11.651] To see the GUI go to: http://127.0.0.1:8188
[2024-12-26 19:02:12.250] FETCH DATA from: E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2024-12-26 19:04:07.982] got prompt
[2024-12-26 19:04:07.998] !!! Exception during processing !!! No module named 'diffusers'
[2024-12-26 19:04:08.001] Traceback (most recent call last):
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels\VAE\nodes.py", line 48, in load_vae
    vae = EXVAE(model_path, model_conf, string_to_dtype(dtype, "vae"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels\VAE\loader.py", line 36, in __init__
    from .models.dcae import AutoencoderDC
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels\VAE\models\dcae.py", line 22, in <module>
    from diffusers import (
ModuleNotFoundError: No module named 'diffusers'

[2024-12-26 19:04:08.001] Prompt executed in 0.02 seconds
[2024-12-26 19:07:33.942] got prompt
[2024-12-26 19:07:33.961] !!! Exception during processing !!! No module named 'diffusers'
[2024-12-26 19:07:33.962] Traceback (most recent call last):
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels\VAE\nodes.py", line 48, in load_vae
    vae = EXVAE(model_path, model_conf, string_to_dtype(dtype, "vae"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels\VAE\loader.py", line 36, in __init__
    from .models.dcae import AutoencoderDC
  File "E:\AI_Image\ComfyUI_windows_portable_nvidia\ComfyUI\custom_nodes\ComfyUI_ExtraModels\VAE\models\dcae.py", line 22, in <module>
    from diffusers import (
ModuleNotFoundError: No module named 'diffusers'

[2024-12-26 19:07:33.963] Prompt executed in 0.02 seconds
[2024-12-26 19:07:40.612] 
Stopped server
```

**Comment by LukeG89** [comment]
I think you just have to install diffusers. Open terminal inside `python_embeded` folder and run this command:
```
.\python.exe -m pip install diffusers
```

**Comment by LukeG89** [comment]
If the problem still persists, you have to wait for the author of [ComfyUI_ExtraModels](https://github.com/city96/ComfyUI_ExtraModels) to fix the issue.
There is already a bug report about it:
- https://github.com/city96/ComfyUI_ExtraModels/issues/106

**Comment by Minimidget007-WE** [comment]
@LukeG89  It worked man thanks alot was strugling alot with it trying to install diffusers everywhere except that spot and not its working thanks mann
