### ISSUE TITLE
Problem whit video generation 

### ISSUE THREAD

**Issue by BPhantom2** [comfyanonymous/ComfyUI#6259]
### Your question

If i try to generate something i get:
No package metadata was found for bitsandbytes
as an Error 

### Logs

```powershell
Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: C:\Users\Samuel\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
got prompt
!!! Exception during processing !!! No package metadata was found for bitsandbytes
Traceback (most recent call last):
  File "importlib\metadata\__init__.py", line 397, in from_name
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-HunyuanVideoWrapper\nodes.py", line 582, in loadmodel
    quantization_config = BitsAndBytesConfig(
                          ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\quantization_config.py", line 417, in __init__
    self.post_init()
  File "C:\Users\Samuel\Documents\ComfyUI_windows_portable\python_embeded\Lib\site-packages\transformers\utils\quantization_config.py", line 475, in post_init
    if self.load_in_4bit and not version.parse(importlib.metadata.version("bitsandbytes")) >= version.parse(
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\metadata\__init__.py", line 889, in version
  File "importlib\metadata\__init__.py", line 862, in distribution
  File "importlib\metadata\__init__.py", line 399, in from_name
importlib.metadata.PackageNotFoundError: No package metadata was found for bitsandbytes

Prompt executed in 3.82 seconds
```

**Comment by ltdrdata** [comment]
Please move this issue to ComfyUI-HunyuanVideoWrapper repo.
https://github.com/kijai/ComfyUI-HunyuanVideoWrapper
