### ISSUE TITLE
OOM on LTX video 0.9.1 with new v0.3.10 comfyui (RTX 3060 12GB)

### ISSUE THREAD

**Issue by junaid3d** [comfyanonymous/ComfyUI#6278]
### Expected Behavior

The LTX workflow was rendering videos without OOM on previous comfyui version.

### Actual Behavior

torch.OutOfMemoryError: Allocation on device

### Steps to Reproduce

Render an LTX video

### Debug Logs

```powershell
CLIP model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
Requested to load MochiTEModel_
loaded partially 4293.600998687744 4283.38671875 0
loaded partially 4291.600998687744 4283.38671875 0
Requested to load LTXVModel
loaded completely 9.5367431640625e+25 3667.902587890625 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [03:12<00:00,  7.69s/it]
!!! Exception during processing !!! Allocation on device
Traceback (most recent call last):
  File "R:\AI\comfyui312\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "R:\AI\comfyui312\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\ComfyUI\nodes.py", line 285, in decode
    images = vae.decode(samples["samples"])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\ComfyUI\custom_nodes\ComfyUI-LTXVideo\vae.py", line 71, in decode
    result = vae_decode(
             ^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\vae_encode.py", line 122, in vae_decode
    images = _run_decoder(
             ^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\vae_encode.py", line 147, in _run_decoder
    image = vae.decode(
            ^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\vae.py", line 307, in decode
    else self._decode(z, target_shape=target_shape, timestep=timestep)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\vae.py", line 264, in _decode
    dec = self.decoder(z, target_shape=target_shape, timestep=timestep)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\causal_video_autoencoder.py", line 670, in forward
    sample = checkpoint_fn(up_block)(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\causal_video_autoencoder.py", line 872, in forward
    hidden_states = resnet(
                    ^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "R:\AI\comfyui312\Lib\site-packages\ltx_video\models\autoencoders\causal_video_autoencoder.py", line 1080, in forward
    hidden_states = hidden_states * (1 + scale1) + shift1
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
torch.OutOfMemoryError: Allocation on device

Got an OOM, unloading all loaded models.
Prompt executed in 247.38 seconds
```

**Comment by comfyanonymous** [comment]
Try the native nodes instead: https://comfyanonymous.github.io/ComfyUI_examples/ltxv/

**Comment by junaid3d** [comment]
The generation times are slower as compared to the older comfyui version. Perhaps memory management was better as even with the same .json file, it never OOM. Strangely, the generation time increases exponentially with every iteration as well. I have tried to even reinstall comfyui (downloaded the portable version too) I had a manual installation before which was upgraded to the new version. It was 0.3.8 which rendered LTX videos at 4.5s/it. The rest of the system configs are the same as of now. No new RTX drivers either. 
[LTX Video.json](https://github.com/user-attachments/files/18273418/LTX.Video.json)

**Comment by comfyanonymous** [comment]
The comfyui memory management only works when you use the native nodes that I linked above.

**Comment by junaid3d** [comment]
Is this a problem with the LTX nodes?

Initial Generation: 8.4GB during generation
11.3GB during VAE decode
6.9GB at Prompt finished
Speed: 3.7s/it

Subsequent Generation: 11.7GB during generation
11.3GB during VAE decode
10.2GB at Prompt finished
Speed: 8.56s/it


got prompt
model_type FLOW
using sdpa for attention
</s><s>The image shows a young child, probably around 2-3 years old, standing on a dirt road with three ducks. The child is wearing a red jacket, blue jeans, and gray shoes. He has blonde hair and appears to be looking down at the ducks with a curious expression on his face. In the background, there is a white trailer and a red truck parked on the side of the road. The sky is overcast and there are trees and houses visible in the distance.</s>
Offloading model...
Requested to load MochiTEModel_
loaded partially 4295.495568084717 4283.38671875 0
0 models unloaded.
loaded partially 4347.38671875 4331.38671875 0
Requested to load LTXVModel
loaded completely 9.5367431640625e+25 3667.902587890625 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [01:32<00:00,  3.70s/it]
Prompt executed in 136.75 seconds
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "R:\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "R:\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
got prompt
loaded partially 7924.062218475342 7899.38671875 0
Requested to load LTXVModel
loaded completely 9.5367431640625e+25 3667.902587890625 True
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 25/25 [03:34<00:00,  8.56s/it]
Prompt executed in 248.25 seconds
Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "R:\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "R:\Python312\Lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by junaid3d** [comment]
> The comfyui memory management only works when you use the native nodes that I linked above.

They are not compatible with LTX 0.9.1 unfortuntely

**Comment by junaid3d** [comment]
torch.cuda.empty_cache() has managed the OOM.
[ComfyUI-FreeMemory](https://github.com/ShmuelRonen/ComfyUI-FreeMemory) Node at the VAE decode.

**Comment by ltdrdata** [comment]
> > The comfyui memory management only works when you use the native nodes that I linked above.
> 
> They are not compatible with LTX 0.9.1 unfortuntely

Latest ComfyUI supports LTX 0.9.1, natively.

![0 9 1](https://github.com/user-attachments/assets/47af64f6-9e4a-4f47-a1b4-7f2c379fca86)

**Comment by junaid3d** [comment]
Its great to convert text video but does it have STG attention. I tried img to vid but the results were garbled. It seems there isn't a fix and LTX nodes have memory management issues. Native nodes dont.
