### ISSUE TITLE
Execute update_comfyui.bat：_pygit2.GitError: failed to send request: 操作超时

### ISSUE THREAD

**Issue by IAFFeng** [comfyanonymous/ComfyUI#6288]
### Expected Behavior

How to solve it, it can always be updated

### Actual Behavior

Execute update_comfyui.bat, unable to update, there are agents, can always pull, the error appears in the past two days

### Steps to Reproduce

Execute update_comfyui.bat, unable to update, there are agents, can always pull, the error appears in the past two days

### Debug Logs

```powershell
stashing current changes
nothing to stash
creating backup branch: backup_branch_2024-12-31_16_06_11
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "H:\ComfyUI_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "H:\ComfyUI_windows_portable\update\update.py", line 11, in pull
    remote.fetch()
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\remotes.py", line 160, in fetch
    payload.check_error(err)
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "H:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: failed to send request: 操作超时
```

**Comment by githubjoshuali** [comment]
I downloaded ComfyUI 0.3.10 portable version for Windows yesterday, and encountered the same problem as you when I clicked the update_comfyui.bat to run. Now it still hasn't been resolved, is there any big shot who can solve this?

**Comment by ltdrdata** [comment]
Please check if `git pull` works properly in the ComfyUI directory within your network environment.

**Comment by githubjoshuali** [comment]
> Please check if `git pull` works properly in the `ComfyUI_windows_portable\ComfyUI` directory within your network environment.
When I just ran git pull command in the ComfyUI_windows_portable\ComfyUI directory, the following feedback information was provided like this:
fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI/': Failed to connect to github.com port 443 after 21104 ms: Could not connect to server
My network environment is using VPN. but it still shows error even if I didn't use VPN.

**Comment by ltdrdata** [comment]
> When I just ran git pull command in the ComfyUI_windows_portable\ComfyUI directory, the following feedback information was provided like this: fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI/': Failed to connect to github.com port 443 after 21104 ms: Could not connect to server My network environment is using VPN. but it still shows error even if I didn't use VPN.

Try using a different VPN.

**Comment by githubjoshuali** [comment]
> > When I just ran git pull command in the ComfyUI_windows_portable\ComfyUI directory, the following feedback information was provided like this: fatal: unable to access 'https://github.com/comfyanonymous/ComfyUI/': Failed to connect to github.com port 443 after 21104 ms: Could not connect to server My network environment is using VPN. but it still shows error even if I didn't use VPN.
> 
> Try using a different VPN.

Thanks a lot! I JUST turn on TUN MODE in my proxy software, and then it works

**Comment by kaiery** [comment]
Does it not support http proxy?

**Comment by maweiqiang1978** [comment]
stashing current changes
nothing to stash
creating backup branch: backup_branch_2025-04-21_13_55_40
checking out master branch
pulling latest changes
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable\update\update.py", line 76, in <module>
    pull(repo)
  File "D:\ComfyUI_windows_portable\update\update.py", line 11, in pull
    remote.fetch()
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\remotes.py", line 160, in fetch
    payload.check_error(err)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\callbacks.py", line 99, in check_error
    check_error(error_code)
  File "D:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pygit2\errors.py", line 66, in check_error
    raise GitError(message)
_pygit2.GitError: failed to send request:

**Comment by maweiqiang1978** [comment]
D:\ComfyUI_windows_portable\ComfyUI>git pull
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=origin/<branch> master
