### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'infer'

### ISSUE THREAD

**Issue by sunnyxiao198** [comfyanonymous/ComfyUI#6290]
### Expected Behavior

Traceback (most recent call last):
  File "D:\ComfyUI-aki-v1.4\execution.py", line 328, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.4\execution.py", line 203, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\ComfyUI-aki-v1.4\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\ComfyUI-aki-v1.4\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI_LayerStyle_Advance\py\object_detector.py", line 350, in object_detector_yoloworld
    results = model.infer(
AttributeError: 'NoneType' object has no attribute 'infer'

### Actual Behavior

The above issues occur when running workflows in Comfyui

### Steps to Reproduce

The above issues occur when running workflows in Comfyui

### Debug Logs

```powershell
The above issues occur when running workflows in Comfyui
```

**Comment by huchenlei** [comment]
Please file issue in ComfyUI_LayerStyle_Advance repo instead. Thanks!
