### ISSUE TITLE
Jus throw an error

### ISSUE THREAD

**Issue by dule1970** [comfyanonymous/ComfyUI#6294]
### Expected Behavior

Workflow to works

### Actual Behavior

An error

### Steps to Reproduce

Just load CR_Simple_Banner_demo1.json

### Debug Logs

```powershell
got prompt
!!! Exception during processing !!! CR_TextList.make_list() missing 1 required positional argument: 'loops'
Traceback (most recent call last):
  File "J:\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "J:\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "J:\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: CR_TextList.make_list() missing 1 required positional argument: 'loops'
```

### Other

Just frustrated from LACK of info on nodes

**Comment by dule1970** [comment]
Yet another broken workflow....

**Comment by LukeG89** [comment]
If the problem comes from a custom node, you have to check in the custom node repo, in you case [ComfyUI_Comfyroll_CustomNodes](https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes)

There is a issue about your problem:

- https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/issues/116

**Comment by dule1970** [comment]
... And another....
