### ISSUE TITLE
A message indicating that the node installation is complete indicates that the import failed

### ISSUE THREAD

**Issue by zzzz88881** [comfyanonymous/ComfyUI#6297]
### Your question

There are a lot of nodes that are like this: Is there a kind person to help me C:\ComfyUI\ComfyUI\custom_nodes This folder contains the corresponding files ![image](https://github.com/user-attachments/assets/db4be409-821f-42ba-acb6-1208b8dab195)

### Logs

```powershell
## ComfyUI-Manager: installing dependencies done.
[2025-01-01 01:22:41.901] ** ComfyUI startup time: 2025-01-01 01:22:41.901517
[2025-01-01 01:22:41.931] ** Platform: Windows
[2025-01-01 01:22:41.931] ** Python version: 3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
[2025-01-01 01:22:41.931] ** Python executable: C:\ComfyUI\python_embeded\python.exe
[2025-01-01 01:22:41.931] ** ComfyUI Path: C:\ComfyUI\ComfyUI
[2025-01-01 01:22:41.931] ** Log path: C:\ComfyUI\comfyui.log
[2025-01-01 01:22:43.029] 
Prestartup times for custom nodes:
[2025-01-01 01:22:43.029]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
[2025-01-01 01:22:43.029]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
[2025-01-01 01:22:43.029]    0.2 seconds: C:\ComfyUI\ComfyUI\custom_nodes\BizyAir
[2025-01-01 01:22:43.030]    2.2 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
[2025-01-01 01:22:43.030] 
Total VRAM 8187 MB, total RAM 16241 MB
[2025-01-01 01:22:44.672] pytorch version: 2.5.1+cu124
[2025-01-01 01:22:44.672] Set vram state to: NORMAL_VRAM
[2025-01-01 01:22:44.672] Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
[2025-01-01 01:22:45.800] Using pytorch attention
[2025-01-01 01:22:47.138] [Prompt Server] web root: C:\ComfyUI\ComfyUI\web
[2025-01-01 01:22:47.813] Display name '☁️BizyAir SetUnionControlNetType' might differ from the native display name.
[2025-01-01 01:22:47.813] Display name '☁️BizyAir ControlNetInpaintingAliMamaApply' might differ from the native display name.
[2025-01-01 01:22:47.814] Display name '☁️BizyAir DisableNoise' might differ from the native display name.
[2025-01-01 01:22:47.814] Display name '☁️BizyAir VPScheduler' might differ from the native display name.
[2025-01-01 01:22:47.814] Display name '☁️BizyAir SplitSigmas' might differ from the native display name.
[2025-01-01 01:22:47.814] Display name '☁️BizyAir SplitSigmasDenoise' might differ from the native display name.
[2025-01-01 01:22:47.814] Display name '☁️BizyAir FlipSigmas' might differ from the native display name.
[2025-01-01 01:22:47.814] Display name '☁️BizyAir CFGGuider' might differ from the native display name.
[2025-01-01 01:22:47.815] Display name '☁️BizyAir CLIPTextEncodeFlux' might differ from the native display name.
[2025-01-01 01:22:47.815] Display name '☁️BizyAir FluxGuidance' might differ from the native display name.
[2025-01-01 01:22:47.817] Display name '☁️BizyAir InstructPixToPixConditioning' might differ from the native display name.
[2025-01-01 01:22:47.818] Display name '☁️BizyAir IPAdapterModelLoader' might differ from the native display name.
[2025-01-01 01:22:47.818] Display name '☁️BizyAir IPAdapterAdvanced' might differ from the native display name.
[2025-01-01 01:22:47.819] Display name '☁️BizyAir IPAdapterStyleComposition' might differ from the native display name.
[2025-01-01 01:22:47.820] Display name '☁️BizyAir ModelSamplingSD3' might differ from the native display name.
[2025-01-01 01:22:47.820] Display name '☁️BizyAir ModelSamplingFlux' might differ from the native display name.
[2025-01-01 01:22:47.820] Display name '☁️BizyAir TripleCLIPLoader' might differ from the native display name.
[2025-01-01 01:22:47.822] Display name '☁️BizyAir UltimateSDUpscale' might differ from the native display name.
[2025-01-01 01:22:47.824] Display name '☁️BizyAir MinusZoneChatGLM3TextEncode' might differ from the native display name.
[2025-01-01 01:22:47.897] Display name '☁️BizyAir LoraLoader_Legacy' might differ from the native display name.
[2025-01-01 01:22:47.898] Display name '☁️BizyAir ControlNetLoader_Legacy' might differ from the native display name.
[2025-01-01 01:22:47.898] Display name '☁️BizyAir SamplerCustomAdvanced' might differ from the native display name.
[2025-01-01 01:22:47.898] Display name '☁️BizyAir BasicGuider' might differ from the native display name.
[2025-01-01 01:22:47.898] Display name '☁️BizyAir BasicScheduler' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir DualCLIPLoader' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir KSamplerSelect' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir RandomNoise' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir InpaintModelConditioning' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir InpaintModelConditioning_v2' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir ConditioningZeroOut' might differ from the native display name.
[2025-01-01 01:22:47.899] Display name '☁️BizyAir ConditioningSetTimestepRange' might differ from the native display name.
[2025-01-01 01:22:47.908] 

[92m[BizyAir][0m Model hosting service initialized.

[2025-01-01 01:22:47.908] 
[2025-01-01 01:22:47.938] No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[2025-01-01 01:22:49.206] [34m[ComfyUI-Easy-Use] server: [0mv1.2.6 [92mLoaded[0m
[2025-01-01 01:22:49.206] [34m[ComfyUI-Easy-Use] web root: [0mC:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use\web_version/v2 [92mLoaded[0m
[2025-01-01 01:22:49.460] ### Loading: ComfyUI-Impact-Pack (V8.1.6)
[2025-01-01 01:22:49.509] [Impact Pack] Wildcards loading done.
[2025-01-01 01:22:49.511] ### Loading: ComfyUI-Impact-Pack (V8.1.6)
[2025-01-01 01:22:49.526] [Impact Pack] Wildcards loading done.
[2025-01-01 01:22:49.527] ### Loading: ComfyUI-Impact-Subpack (V1.1)
[2025-01-01 01:22:51.618] [Impact Subpack] ultralytics_bbox: C:\ComfyUI\ComfyUI\models\ultralytics\bbox
[2025-01-01 01:22:51.618] [Impact Subpack] ultralytics_segm: C:\ComfyUI\ComfyUI\models\ultralytics\segm
[2025-01-01 01:22:51.631] Total VRAM 8187 MB, total RAM 16241 MB
[2025-01-01 01:22:51.631] pytorch version: 2.5.1+cu124
[2025-01-01 01:22:51.631] Set vram state to: NORMAL_VRAM
[2025-01-01 01:22:51.631] Device: cuda:0 NVIDIA GeForce RTX 4060 : cudaMallocAsync
[2025-01-01 01:22:51.664] [94mtheUpsiders Logic Nodes: [92mLoaded[0m
[2025-01-01 01:22:51.666] ### Loading: ComfyUI-Manager (V2.56)
[2025-01-01 01:22:51.817] ### ComfyUI Revision: 2946 [9f4b181a] *DETACHED | Released on '2024-12-18'
[2025-01-01 01:22:52.443] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2025-01-01 01:22:52.557] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2025-01-01 01:22:52.625] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2025-01-01 01:22:52.811] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2025-01-01 01:22:52.870] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2025-01-01 01:22:53.421] --------------
[2025-01-01 01:22:53.421] [91m ### Mixlab Nodes: [93mLoaded
[2025-01-01 01:22:53.423] ChatGPT.available False
[2025-01-01 01:22:53.423] edit_mask.available True
[2025-01-01 01:22:53.713] ## clip_interrogator_model not found: C:\ComfyUI\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
[2025-01-01 01:22:53.713] ClipInterrogator.available True
[2025-01-01 01:22:53.755] ## text_generator_model not found: C:\ComfyUI\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
[2025-01-01 01:22:53.755] ## zh_en_model not found: C:\ComfyUI\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
[2025-01-01 01:22:53.756] PromptGenerate.available True
[2025-01-01 01:22:53.757] ChinesePrompt.available True
[2025-01-01 01:22:53.757] RembgNode_.available True
[2025-01-01 01:22:53.761] ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
[2025-01-01 01:22:54.170] TripoSR.available
[2025-01-01 01:22:54.170] MiniCPMNode.available
[2025-01-01 01:22:54.244] Scenedetect.available
[2025-01-01 01:22:54.465] FishSpeech.available
[2025-01-01 01:22:54.467] SenseVoice.available False
[2025-01-01 01:22:54.560] Whisper.available False
[2025-01-01 01:22:54.561] fal-client## OK
[2025-01-01 01:22:54.569] FalVideo.available
[2025-01-01 01:22:54.569] [93m -------------- [0m
[2025-01-01 01:22:54.580] Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\__init__.py", line 1, in <module>
    from .pulidflux import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced\pulidflux.py", line 11, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

[2025-01-01 01:22:54.580] Cannot import C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced module for custom nodes: No module named 'insightface'
[2025-01-01 01:22:54.584] Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

[2025-01-01 01:22:54.584] Cannot import C:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node module for custom nodes: No module named 'insightface'
[2025-01-01 01:22:54.682] C:\ComfyUI
[2025-01-01 01:22:54.682] ############################################
[2025-01-01 01:22:54.682] C:\ComfyUI\custom_nodes\ComfyUI-NAI-styler\CSV
[2025-01-01 01:22:54.682] ############################################
[2025-01-01 01:22:54.682] []
[2025-01-01 01:22:54.682] ############################################
[2025-01-01 01:22:54.705] [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: C:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[2025-01-01 01:22:54.705] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[2025-01-01 01:22:54.706] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2025-01-01 01:22:54.722] DWPose: Onnxruntime with acceleration providers detected
[2025-01-01 01:22:54.751] Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID\__init__.py", line 1, in <module>
    from .InstantID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID\InstantID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

[2025-01-01 01:22:54.751] Cannot import C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID module for custom nodes: No module named 'insightface'
[2025-01-01 01:22:54.769] # 😺dzNodes: LayerStyle -> [1;33mCannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to [4mhttps://github.com/chflame163/ComfyUI_LayerStyle/issues/5[0m[m
[2025-01-01 01:22:54.828] C:\ComfyUI\python_embeded\Lib\site-packages\timm\models\layers\__init__.py:48: FutureWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", FutureWarning)
[2025-01-01 01:22:54.831] # 😺dzNodes: LayerStyle -> [1;33mCannot import name 'guidedFilter' from 'cv2.ximgproc'
A few nodes cannot works properly, while most nodes are not affected. Please REINSTALL package 'opencv-contrib-python'.
For detail refer to [4mhttps://github.com/chflame163/ComfyUI_LayerStyle/issues/5[0m[m
[2025-01-01 01:22:54.945] [92m[tinyterraNodes] [32mLoaded[0m
[2025-01-01 01:22:54.996] Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\nodes.py", line 2072, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ZenID\__init__.py", line 1, in <module>
    from .ZenID import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ZenID\ZenID.py", line 13, in <module>
    from insightface.app import FaceAnalysis
ModuleNotFoundError: No module named 'insightface'

[2025-01-01 01:22:54.996] Cannot import C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ZenID module for custom nodes: No module named 'insightface'
[2025-01-01 01:22:55.015] 
[2025-01-01 01:22:55.015] [92m[rgthree-comfy] Loaded 42 extraordinary nodes. 🎉[00m
[2025-01-01 01:22:55.015] 
[2025-01-01 01:22:55.531] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2025-01-01 01:22:55.531] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `C:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2025-01-01 01:22:56.034] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m220[0m [32mnodes successfully.[0m
[2025-01-01 01:22:56.035] 
	[3m[93m"Art should disturb the comfortable and comfort the disturbed." - Cesar Cruz[0m
[2025-01-01 01:22:56.035] 
[2025-01-01 01:22:56.037] 
Import times for custom nodes:
[2025-01-01 01:22:56.037]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
[2025-01-01 01:22:56.037]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\websocket_image_save.py
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\cg-use-everywhere
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\Comfyui_TTP_Toolset
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Logic
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Universal-Styler
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\cg-image-picker
[2025-01-01 01:22:56.038]    0.0 seconds (IMPORT FAILED): C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-PuLID-Flux-Enhanced
[2025-01-01 01:22:56.038]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2025-01-01 01:22:56.038]    0.0 seconds (IMPORT FAILED): C:\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
[2025-01-01 01:22:56.039]    0.0 seconds (IMPORT FAILED): C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_InstantID
[2025-01-01 01:22:56.039]    0.0 seconds (IMPORT FAILED): C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_ZenID
[2025-01-01 01:22:56.039]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui-inpaint-nodes
[2025-01-01 01:22:56.039]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui-tooling-nodes
[2025-01-01 01:22:56.039]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_essentials
[2025-01-01 01:22:56.039]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2025-01-01 01:22:56.040]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui-portrait-master
[2025-01-01 01:22:56.040]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2025-01-01 01:22:56.040]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2025-01-01 01:22:56.040]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main
[2025-01-01 01:22:56.040]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
[2025-01-01 01:22:56.041]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_CatVTON_Wrapper
[2025-01-01 01:22:56.041]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2025-01-01 01:22:56.041]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2025-01-01 01:22:56.041]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
[2025-01-01 01:22:56.041]    0.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle_Advance
[2025-01-01 01:22:56.041]    0.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[2025-01-01 01:22:56.041]    0.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
[2025-01-01 01:22:56.041]    0.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle
[2025-01-01 01:22:56.041]    0.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui-tensorops
[2025-01-01 01:22:56.041]    0.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AudioReactor
[2025-01-01 01:22:56.041]    0.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\BizyAir
[2025-01-01 01:22:56.041]    0.2 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
[2025-01-01 01:22:56.042]    0.3 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2
[2025-01-01 01:22:56.042]    1.0 seconds: C:\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
[2025-01-01 01:22:56.042]    1.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Easy-Use
[2025-01-01 01:22:56.042]    2.1 seconds: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Subpack
[2025-01-01 01:22:56.042]    2.7 seconds: C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes
[2025-01-01 01:22:56.042] 
[2025-01-01 01:22:56.056] Starting server

[2025-01-01 01:22:56.056] To see the GUI go to: http://127.0.0.1:8188
[2025-01-01 01:22:58.438] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
[2025-01-01 01:22:58.540] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
[2025-01-01 01:22:58.553] FETCH DATA from: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2025-01-01 01:22:58.568] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
[2025-01-01 01:22:58.955] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
[2025-01-01 01:22:58.957] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/model-viewer.min.js
[2025-01-01 01:22:58.961] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
[2025-01-01 01:22:58.965] C:\ComfyUI\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
[2025-01-01 01:22:59.139] [ERROR] An error occurred while retrieving information for the 'Florence2ModelLoader' node.
[2025-01-01 01:22:59.141] Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\server.py", line 579, in get_object_info
    out[x] = node_info(x)
             ^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\server.py", line 546, in node_info
    info['input'] = obj_class.INPUT_TYPES()
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Florence2\nodes.py", line 150, in INPUT_TYPES
    "model": ([item.name for item in Path(folder_paths.models_dir, "LLM").iterdir() if item.is_dir()], {"tooltip": "models are expected to be in Comfyui/models/LLM folder"}),
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pathlib.py", line 1056, in iterdir
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: 'C:\\ComfyUI\\ComfyUI\\models\\LLM'

[2025-01-01 01:23:00.191] Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI\ComfyUI
            
[2025-01-01 01:23:00.191] Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI\ComfyUI
            
[2025-01-01 01:23:00.191] Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI\ComfyUI
            
[2025-01-01 01:23:00.192] Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI\ComfyUI
            
[2025-01-01 01:23:00.192] Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI\ComfyUI
            
[2025-01-01 01:23:00.192] Error. No naistyles.csv found. Put your naistyles.csv in the custom_nodes/ComfyUI_NAI-mod/CSV directory of ComfyUI. Then press "Refresh".
                  Your current root directory is: C:\ComfyUI\ComfyUI
            
[2025-01-01 01:23:00.804] C:\ComfyUI\ComfyUI\custom_nodes\BizyAir\src\bizyair\common\client.py:52: UserWarning: API key is not set.
  warnings.warn("API key is not set.")
[2025-01-01 01:23:08.119] FETCH DATA from: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
[2025-01-01 01:23:08.156] FETCH DATA from: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json [DONE]
[2025-01-01 01:23:08.161] FETCH DATA from: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\746607195_github-stats.json [DONE]
[2025-01-01 01:23:08.254] FETCH DATA from: C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json [DONE]
```

**Comment by LukeG89** [comment]
You need to install insightface, follow these instructions: https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#troubleshooting
