### ISSUE TITLE
[Help] Mask Tensors

### ISSUE THREAD

**Issue by WASasquatch** [comfyanonymous/ComfyUI#643]
I have a really hard time with tensors and numpy. Try to avoid it as much as possible.

I am finding it really confusing getting a simple mask to pil system going for various operations. I always get spatial mismatches once my pasts hit the ksamplers encode. But they work fine for doing all my operations on and even converting to normal image tensor for previews... I just can't get a unified thing that works for everything, including the actual point of this all, and inpainting.

Here is my current functions

```python
    
def pil2mask(image):
    if image.mode == "L":
        image_np = np.array(image).astype(np.float32) / 255.0
    else:
        image_np = np.array(image.convert("L")).astype(np.float32) / 255.0
    mask = torch.from_numpy(image_np).unsqueeze(0)
    return 1.0 - mask if image.mode == "L" else mask

def mask2pil(mask):
    mask_np = (mask.numpy().squeeze() * 255).astype(np.uint8)
    mask_np = np.squeeze(mask_np)
    return Image.fromarray(mask_np, mode="L")
```

But then encode errors out on interpolation

```
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 182, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 174, in encode
    mask = torch.nn.functional.interpolate(mask[None,None,], size=(pixels.shape[1], pixels.shape[2]), mode="bilinear")[0][0]
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\functional.py", line 3869, in interpolate
    raise ValueError(
ValueError: Input and output must have the same number of spatial dimensions, but got input with spatial dimensions of [1, 512, 512] and output size of (512, 512). Please provide input tensor in (N, C, d1, d2, ...,dK) format and output size in (o1, o2, ...,oK) format.
```

What is weird, is it's telling me to provide a [N, C, H, W] shape, but the code in encode is expecting [N, H, W, ...]

**Comment by comfyanonymous** [comment]
Masks are supposed to be in shape: [height, width]

You can also shape them like this if you want to apply a different mask to different images in a batch: [batch_size, 1, height, width]

**Comment by WASasquatch** [comment]
So they have to be either [H, W] (single) or [N, C, H, W]?

**Comment by WASasquatch** [comment]
Thanks so much, I think I understand how to pass these around correctly now. I think. Lol 

And will do.

**Comment by WASasquatch** [comment]
> Yes originally masks were all [H, W] but then someone wanted to be able to apply them to different images in a batch so [N, C, H, W] are supported too now. If you find any nodes that don't work with [N, C, H, W] masks let me know and I'll fix them.

One issue I had is I wasn't up to date. But one thing I can't figure out now that I am, I am getting this:

```
Failed to validate prompt for output 17 Required input is missing. VAEEncodeForInpaint, grow_mask_by
```

With a batch of 3 images and batch of 3 masks. There is no "grow_mask_by" field. I've restarted and recreated the  node several times in new tabs to ensure it had the right template structure for the node, but nothing is showing to be able to set this mysterious "grow_mask_by" param.

**Comment by WASasquatch** [comment]
Ok. I did a full update instead of just comfy and that seems to be showing the inputs now. But the masks are killing sampling it seems

```
Traceback (most recent call last):
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 185, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "C:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "C:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 259, in encode
    t = vae.encode(pixels)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 561, in encode
    samples = self.first_stage_model.encode(2. * pixel_samples - 1.).sample() * self.scale_factor
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\models\autoencoder.py", line 87, in encode
    h = self.encoder(x)
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ComfyUI_windows_portable\ComfyUI\comfy\ldm\modules\diffusionmodules\model.py", line 614, in forward
    h = self.conv_in(x)
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "C:\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (double) and bias type (float) should be the same
```

**Comment by comfyanonymous** [comment]
>Input type (double)

Make sure your images are in float32. I'm not sure why they are in float64/double but .float() should work to convert them.

**Comment by WASasquatch** [comment]
def pil2tensor(image):
    return torch.from_numpy(np.array(image).astype(np.float32) / 255.0).unsqueeze(0)

They should be, so that's odd.

Looking online it told me that you should ensure float by using `image.float()`. So I added `pixels = pixels.float()` and it worked just fine. Maybe that should just be added encase of anomalies, cause I can't see anywhere in my code where float64 is used, it's all cast to float32.

**Comment by WASasquatch** [comment]
Oop. Got it. Happened because I spaced on adding `.astype()` altogether to the batch image creation, so it was naturally double. Oi.
