### ISSUE TITLE
"RuntimeError: Found no NVIDIA driver on your system." on AMD 6700XT

### ISSUE THREAD

**Issue by snaeker58** [comfyanonymous/ComfyUI#653]
Followed install instructions, clean Ubuntu 22.04 install.
System specs are a Ryzen 7 3700x and a Radeon 6700XT.

Full error:
```
got prompt
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
Global Step: 840000
Traceback (most recent call last):
  File "/home/karl/ComfyUI/execution.py", line 185, in execute
    recursive_execute(self.server, prompt, self.outputs, x, extra_data, executed)
  File "/home/karl/ComfyUI/execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "/home/karl/ComfyUI/execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "/home/karl/ComfyUI/execution.py", line 58, in recursive_execute
    recursive_execute(server, prompt, outputs, input_unique_id, extra_data, executed)
  File "/home/karl/ComfyUI/execution.py", line 67, in recursive_execute
    outputs[unique_id] = getattr(obj, obj.FUNCTION)(**input_data_all)
  File "/home/karl/ComfyUI/nodes.py", line 290, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
  File "/home/karl/ComfyUI/comfy/sd.py", line 962, in load_checkpoint_guess_config
    fp16 = model_management.should_use_fp16()
  File "/home/karl/ComfyUI/comfy/model_management.py", line 353, in should_use_fp16
    if torch.cuda.is_bf16_supported():
  File "/home/karl/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 122, in is_bf16_supported
    return torch.cuda.get_device_properties(torch.cuda.current_device()).major >= 8 and cuda_maj_decide
  File "/home/karl/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/karl/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

**Comment by snaeker58** [comment]
"That error means you installed the wrong pytorch, what's your python version?"

**Comment by snaeker58** [comment]
I'm uninstalling PyTorch: `pip3 uninstall torch`

**Comment by snaeker58** [comment]
Reinstalling via: `pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/rocm5.4.2`

**Comment by snaeker58** [comment]
Solved. getting error #650 again instead. This is family fun, thanks AMD!
