### ISSUE TITLE
Some custom nodes and extensions aren't working on Colab

### ISSUE THREAD

**Issue by Arata021** [comfyanonymous/ComfyUI#670]
Hi. Thanks for developing ComfyUI. I'm having lots of fun using it. I'm experiencing some issues in Colab though:

1. I'd like to change a node's name, but clicking properties just closes the pop-up menu.

2. I get errors when using some nodes in Colab:

Cannot import /content/ComfyUI/custom_nodes/sampler_tonemap.py module for custom nodes: invalid character '·' (U+00B7) (sampler_tonemap.py, line 72)

Cannot import /content/ComfyUI/custom_nodes/sampler_rescalecfg.py module for custom nodes: invalid character '·' (U+00B7) (sampler_rescalecfg.py, line 72)

Cannot import /content/ComfyUI/custom_nodes/comfy_controlnet_preprocessors module for custom nodes: No module named 'mediapipe'
Traceback (most recent call last):
  File "/content/ComfyUI/nodes.py", line 1304, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1017, in get_code
  File "<frozen importlib._bootstrap_external>", line 947, in source_to_code
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

3. Then the image feed and node locking extensions aren't working. I also tried putting the .js files directly in the extensions folder but they still don't work. Here are all the additional lines I'm using in Colab:

!git clone https://github.com/BlenderNeko/ComfyUI_ADV_CLIP_emb/ /content/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
!git clone https://github.com/BlenderNeko/ComfyUI_Cutoff/ /content/ComfyUI/custom_nodes/ComfyUI_Cutoff
!git clone https://github.com/BlenderNeko/ComfyUI_Noise/ /content/ComfyUI/custom_nodes/ComfyUI_Noise
!git clone https://github.com/BlenderNeko/ComfyUI_TiledKSampler/ /content/ComfyUI/custom_nodes/ComfyUI_TiledKSampler
!git clone https://github.com/Fannovel16/comfy_controlnet_preprocessors/ /content/ComfyUI/custom_nodes/comfy_controlnet_preprocessors
!git clone https://github.com/ltdrdata/ComfyUI-Impact-Pack/ /content/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
!git clone https://github.com/LucianoCirino/efficiency-nodes-comfyui/ /content/ComfyUI/custom_nodes/efficiency-nodes-comfyui
!git clone https://github.com/WASasquatch/was-node-suite-comfyui/ /content/ComfyUI/custom_nodes/was-node-suite-comfyui
!wget -c https://github.com/comfyanonymous/ComfyUI_experiments/blob/master/sampler_rescalecfg.py -P ./custom_nodes/
!wget -c https://github.com/comfyanonymous/ComfyUI_experiments/blob/master/sampler_tonemap.py -P ./custom_nodes/
!wget -c https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/main/image-feed/imageFeed.js -P ./web/extensions/image-feed/
!wget -c https://github.com/pythongosssss/ComfyUI-Custom-Scripts/blob/main/lock-nodes-and-groups/locking.js -P ./web/extensions/lock-nodes-and-groups/

**Comment by ltdrdata** [comment]
I think you downloaded html instead of file.

you must download through "raw" button.
if you downloaded from github.

**Comment by ltdrdata** [comment]
> Thank you. I'm just a novice when it comes to these stuff, so I didn't know that's what's happening. It's not showing errors on those two anymore and the extensions are now working.
> 
> Any thoughts on why the properties in the pop-up menu doesn't work?

https://github.com/ltdrdata/ComfyUI-Manager

This is extension help you for convenient custom nodes handling. :)

And.. what do you meaning about popup menu?

**Comment by Arata021** [comment]
That's a pretty neat extension. I'll make sure to try it out.

I'm referring to this menu:
https://i.postimg.cc/fL1sNx5x/Screenshot-73.png

Almost forgot to ask. Would you happen to know where to get mediapipe?
When adding comfy_controlnet_preprocessors, I'm getting this: No module named 'mediapipe'

**Comment by ltdrdata** [comment]
> That's a pretty neat extension. I'll make sure to try it out.
> 
> I'm referring to this menu:
> https://i.postimg.cc/fL1sNx5x/Screenshot-73.png
> 
> Almost forgot to ask. Would you happen to know where to get mediapipe?
> When adding comfy_controlnet_preprocessors, I'm getting this: No module named 'mediapipe'

lol...the properties is nothing for now.


And for the controlnet...

You need to pip install requirements.txt and execute install.py.

pip install -r requirements.txt
python install.py

ar the custom node directory.

Actually, manager do that automatically.

**Comment by Arata021** [comment]
Ah I see. I hope it gets fixed because I'd like to change a node's name, but I can't since it closes the menu when clicked.

That's cool. I'll definitely try the manager the next time I use ComfyUI.

Thank you.

**Comment by ltdrdata** [comment]
> Ah I see. I hope it gets fixed because I'd like to change a node's name, but I can't since it closes the menu when clicked.
> 
> That's cool. I'll definitely try the manager the next time I use ComfyUI.
> 
> Thank you.

You can change node name by "Title" menu.
