### ISSUE TITLE
Crashes if prompt failed to validate: `UnboundLocalError: local variable 'node_id' referenced before assignment`

### ISSUE THREAD

**Issue by space-nuko** [comfyanonymous/ComfyUI#686]
```
Traceback (most recent call last):
  File "E:\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "E:\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "E:\ComfyUI\venv\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "E:\ComfyUI\server.py", line 29, in cache_control
    response: web.Response = await handler(request)
  File "E:\ComfyUI\server.py", line 41, in cors_middleware
    response = await handler(request)
  File "E:\ComfyUI\server.py", line 331, in post_prompt
    valid = execution.validate_prompt(prompt)
  File "E:\ComfyUI\execution.py", line 384, in validate_prompt
    if node_id not in node_errors:
UnboundLocalError: local variable 'node_id' referenced before assignment
ERROR:asyncio:Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Users\yuno\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\yuno\AppData\Local\Programs\Python\Python310\lib\asyncio\proactor_events.py", line 165, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
```

**Comment by comfyanonymous** [comment]
https://github.com/comfyanonymous/ComfyUI/commit/48fcc5b777b3a1ab5d6dc5fec6adaebeb32c2c93
