### ISSUE TITLE
RuntimeError: shape '[4096, 1024]' is invalid for input of size 2359296

### ISSUE THREAD

**Issue by danildf** [comfyanonymous/ComfyUI#810]
First time attempted to load lora and none of the two I tried worked. Both work fine in automatic1111.
[Lora1](https://civitai.com/models/58390/detail-tweaker-lora-lora)
[Lora2](https://civitai.com/models/7505/hu-tao-or-genshin-impact)

Traceback (most recent call last):
  File "ComfyUI/execution.py", line 141, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/traveler/drived/ComfyUI/nodes.py", line 52, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
  File "ComfyUI/comfy/sd.py", line 572, in encode_from_tokens
    raise e
  File "ComfyUI/comfy/sd.py", line 567, in encode_from_tokens
    self.patch_model()
  File "ComfyUI/comfy/sd.py", line 590, in patch_model
   self.patcher.patch_model()
  File "ComfyUI/comfy/sd.py", line 453, in patch_model
    weight += (alpha * torch.mm(mat1.flatten(start_dim=1).float(), mat2.flatten(start_dim=1).float())).reshape(weight.shape).type(weight.dtype).to(weight.device)
RuntimeError: shape '[4096, 1024]' is invalid for input of size 2359296

Workflow
[workflow.json.zip](https://github.com/comfyanonymous/ComfyUI/files/11902667/workflow.json.zip)

**Comment by danildf** [comment]
Sorry, incorrect code line numbers because I tried to debug myself. Corrected: 
Traceback (most recent call last):
  File "ComfyUI/execution.py", line 141, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "ComfyUI/nodes.py", line 52, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
  File "ComfyUI/comfy/sd.py", line 568, in encode_from_tokens
    raise e
  File "ComfyUI/comfy/sd.py", line 563, in encode_from_tokens
    self.patch_model()
  File "ComfyUI/comfy/sd.py", line 586, in patch_model
    self.patcher.patch_model()
  File "ComfyUI/comfy/sd.py", line 449, in patch_model
    weight += (alpha * torch.mm(mat1.flatten(start_dim=1).float(), mat2.flatten(start_dim=1).float())).reshape(weight.shape).type(weight.dtype).to(weight.device)
RuntimeError: shape '[4096, 1024]' is invalid for input of size 2359296

**Comment by danildf** [comment]
Nevermind, I used the wrong model.

**Comment by danildf** [comment]
Nevermind, I used the wrong model.
