### ISSUE TITLE
Dependency installation fails: No matching distribution found for torchdiffeq

### ISSUE THREAD

**Issue by ThatOneCalculator** [comfyanonymous/ComfyUI#813]
OS: Arch Linux Rolling x86_64
GPU: AMD 6700XT
Python: 3.11.3

```
(venv) ➜  ComfyUI git:(master) pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5 -r requirements.txt
Looking in indexes: https://download.pytorch.org/whl/nightly/rocm5.5
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/rocm5.5/torch-2.1.0.dev20230628%2Brocm5.5-cp311-cp311-linux_x86_64.whl (1420.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.4/1.4 GB 2.8 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/nightly/rocm5.5/torchvision-0.16.0.dev20230629%2Brocm5.5-cp311-cp311-linux_x86_64.whl (64.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 MB 4.4 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/nightly/rocm5.5/torchaudio-2.1.0.dev20230629%2Brocm5.5-cp311-cp311-linux_x86_64.whl (2.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 4.8 MB/s eta 0:00:00
ERROR: Could not find a version that satisfies the requirement torchdiffeq (from versions: none)
ERROR: No matching distribution found for torchdiffeq
WARNING: There was an error checking the latest version of pip.
```

**Comment by comfyanonymous** [comment]
Install pytorch with rocm5.5 then after do another pip install -r requirements.txt

**Comment by ThatOneCalculator** [comment]
Attempting install right now, my internet is a bit slow so it may take a bit. Unrelated to this issue, but I wonder if the Nvidia deps could be skipped if you don't have an Nvidia GPU, that'd save maybe half a gig?

![image](https://github.com/comfyanonymous/ComfyUI/assets/44733677/9521be40-8f5f-4723-ad99-69f59b5bcc7d)

**Comment by ThatOneCalculator** [comment]
Ok, so that just finished. I tried `python main.py` but got this error:

```py
(venv) ➜  ComfyUI git:(master) python main.py
Traceback (most recent call last):
  File "/home/kainoa/.local/share/ComfyUI/main.py", line 28, in <module>
    import execution
  File "/home/kainoa/.local/share/ComfyUI/execution.py", line 12, in <module>
    import nodes
  File "/home/kainoa/.local/share/ComfyUI/nodes.py", line 19, in <module>
    import comfy.diffusers_load
  File "/home/kainoa/.local/share/ComfyUI/comfy/diffusers_load.py", line 6, in <module>
    from comfy.sd import ModelPatcher, load_model_weights, CLIP, VAE, load_checkpoint
  File "/home/kainoa/.local/share/ComfyUI/comfy/sd.py", line 6, in <module>
    from comfy import model_management
  File "/home/kainoa/.local/share/ComfyUI/comfy/model_management.py", line 103, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/home/kainoa/.local/share/ComfyUI/comfy/model_management.py", line 73, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kainoa/.local/share/ComfyUI/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 674, in current_device
    _lazy_init()
  File "/home/kainoa/.local/share/ComfyUI/venv/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```

The commands I ran before were:

- `python3 -m venv venv`
- `source ./venv/bin/activate`
- `pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/rocm5.5 -r requirements.txt`
- `pip install -r requirements.txt`
