### ISSUE TITLE
Error loading LoRas

### ISSUE THREAD

**Issue by GregorioBrc** [comfyanonymous/ComfyUI#833]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/content/ComfyUI/execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/ComfyUI/nodes.py", line 477, in load_lora
    model_lora, clip_lora = comfy.sd.load_lora_for_models(model, clip, lora, strength_model, strength_clip)
  File "/content/ComfyUI/custom_nodes/efficiency-nodes-comfyui/lora_patch.py", line 250, in load_lora_for_models
    loaded = load_lora(lora_path, key_map)
  File "/content/ComfyUI/custom_nodes/efficiency-nodes-comfyui/lora_patch.py", line 50, in load_lora
    lora = utils.load_torch_file(path)
  File "/content/ComfyUI/comfy/utils.py", line 8, in load_torch_file
    if ckpt.lower().endswith(".safetensors"):
AttributeError: 'dict' object has no attribute 'lower'

**Comment by GregorioBrc** [comment]
Sorry, it's an efficiency nodes error

**Comment by CoraAI** [comment]
intreresting, I'm having exactly the same issue but with the default loraloader,  the loader of efficiency nodes works well.
The only thing I've done is updating comfyUI to the lastest version. Same workflow with same lora model worked before the update
