### ISSUE TITLE
[bug] Custom nodes can overwrite core nodes through class and display name mappings

### ISSUE THREAD

**Issue by dotJack** [comfyanonymous/ComfyUI#839]
There's no protection or guard for core nodes in nodes.py's definition against being overwritten by custom nodes.
`nodes.py`: `NODE_CLASS_MAPPINGS` | `NODE_DISPLAY_NAME_MAPPINGS`

I was writing custom logic to split all custom nodes to a separate subdirectory and saw that some of the core nodes were being overwritten by custom nodes. Not only the display name but also internals.

I think the node set to the unique id just gets swapped out along with the description.

The fix can be as easy as adding unique identifiers in-front of the entries in nodes.py's `NODE_CLASS_MAPPINGS` / `NODE_DISPLAY_NAME_MAPPINGS`.

```
NODE_CLASS_MAPPINGS = {
    "CoreComfy_KSampler": KSampler,
    "CoreComfy_CheckpointLoaderSimple": CheckpointLoaderSimple,
    "CoreComfy_CLIPTextEncode": CLIPTextEncode,
    ...
```

and
```
NODE_DISPLAY_NAME_MAPPINGS = {
    # Sampling
    "CoreComfy_KSampler": "KSampler",
    "CoreComfy_KSamplerAdvanced": "KSampler (Advanced)",
    ...
````

This is not a perfect solution obviously since any of the custom nodes COULD just go in and add CoreComfy_ to the front of their mappings and sidestep this fix if they wanted to for some reason. Not sure why they would outside of being a bad actor of some kind.

I'm mainly a js/ts developer, so I don't know if it would make sense to move the `name`, `description` and maybe an additional `group` field to the node classes to allow for more descriptive definitions / splitting?But that's like a ComfyUi internal architecture decision.

**Comment by audioscavenger** [comment]
maybe i'm doing it wrong but I cannot overwrite a core class. That's the whole point of my node LoadImage Thumbnails, to replace Loadimage, but latest release won't let me:
```
# here we override the default LoadImage node with our own. It's okay since 
NODE_CLASS_MAPPINGS = {
  'LoadImage': LoadImageThumbnails,
}

NODE_DISPLAY_NAME_MAPPINGS = {
  'LoadImage': 'LoadImageThumbnails',
}
```

result:
```
Traceback (most recent call last):
  File "E:\GPT\ComfyUI\nodes.py", line 2036, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\GPT\ComfyUI\custom_nodes\ComfyUI-Thumbnails\__init__.py", line 23, in <module>
    nodes.NODE_CLASS_MAPPINGS['LoadImage'] = NODE_CLASS_MAPPINGS['LoadImageThumbnails']
KeyError: 'LoadImageThumbnails'

Cannot import E:\GPT\ComfyUI\custom_nodes\ComfyUI-Thumbnails module for custom nodes: 'LoadImageThumbnails'
```
