### ISSUE TITLE
Permission Error

### ISSUE THREAD

**Issue by Marcus-Arcadius** [comfyanonymous/ComfyUI#851]
![image](https://github.com/comfyanonymous/ComfyUI/assets/78793842/0deca0c0-8e99-404b-b67f-0c80fe5538df)

Traceback (most recent call last):
  File ".\main.py", line 123, in <module>
    loop.run_until_complete(run(server, address=args.listen, port=args.port, verbose=not args.dont_print_server, call_on_start=call_on_start))
  File "C:\Users\emery\miniconda3\envs\comfy\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File ".\main.py", line 47, in run
    await asyncio.gather(server.start(address, port, verbose, call_on_start), server.publish_loop())
  File "E:\Stable_Diffusion\ComfyUI_windows_portable\ComfyUI\server.py", line 548, in start
    await site.start()
  File "C:\Users\emery\miniconda3\envs\comfy\lib\site-packages\aiohttp\web_runner.py", line 121, in start
    self._server = await loop.create_server(
  File "C:\Users\emery\miniconda3\envs\comfy\lib\asyncio\base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 10013] error while attempting to bind on address ('127.0.0.1', 8188): an attempt was made to access a socket in a way forbidden by its access permissions

**Comment by comfyanonymous** [comment]
Are you running another ComfyUI at the same time?

**Comment by BileFlask** [comment]
Check your local firewall and/or antivirus. Make sure that your OS is allowed to use that port. You may also try rebooting to force the port open and try again if your firewall is already off. Finally, you may try adding the “—-listen” argument when launching and specify your local IP instead of loopback which would technically be a different socket.

**Comment by robinjhuang** [comment]
Can you change the port using `--listen`. or just stop the previous process taking up that port.
