### ISSUE TITLE
NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by AkhilAndroid** [comfyanonymous/ComfyUI#906]
This is the terminal output
got prompt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/execution.py", line 145, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/execution.py", line 75, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/execution.py", line 68, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/nodes.py", line 1080, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/nodes.py", line 1050, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/comfy/sample.py", line 75, in sample
    comfy.model_management.load_model_gpu(model)
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/comfy/model_management.py", line 299, in load_model_gpu
    raise e
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/comfy/model_management.py", line 295, in load_model_gpu
    real_model = model.patch_model()
                 ^^^^^^^^^^^^^^^^^^^
  File "/run/media/Akhil/6C1067752159A12D/st22/ComfyUI/comfy/sd.py", line 343, in patch_model
    self.backup[key] = weight.to(self.offload_device, copy=True)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Cannot copy out of meta tensor; no data!

Prompt executed in 2.20 seconds

OS-Arch Linux
Python version 3.11.3
Cuda 12.2

**Comment by comfyanonymous** [comment]
Update your comfyui.
This should have been fixed with: https://github.com/comfyanonymous/ComfyUI/commit/5f5736261371664a8224c220a8d9e2c2fa9eed4f

**Comment by AkhilAndroid** [comment]
Yea it works 
Thanks
