### ISSUE TITLE
'GLIBCXX_3.4.26' not found

### ISSUE THREAD

**Issue by Cupcc** [comfyanonymous/ComfyUI#999]
run `python main.py`
error:
**ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-39-x86_64-linux-gnu.so)**
```
Traceback (most recent call last):
  File "/root/ComfyUI/main.py", line 69, in <module>
    import execution
  File "/root/ComfyUI/execution.py", line 11, in <module>
    import nodes
  File "/root/ComfyUI/nodes.py", line 21, in <module>
    import comfy.samplers
  File "/root/ComfyUI/comfy/samplers.py", line 1, in <module>
    from .k_diffusion import sampling as k_diffusion_sampling
  File "/root/ComfyUI/comfy/k_diffusion/sampling.py", line 3, in <module>
    from scipy import integrate
  File "/opt/conda/lib/python3.9/site-packages/scipy/__init__.py", line 211, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.9/site-packages/scipy/integrate/__init__.py", line 91, in <module>
    from ._quadrature import *
  File "/opt/conda/lib/python3.9/site-packages/scipy/integrate/_quadrature.py", line 12, in <module>
    from scipy.special import roots_legendre
  File "/opt/conda/lib/python3.9/site-packages/scipy/special/__init__.py", line 657, in <module>
    from . import _orthogonal
  File "/opt/conda/lib/python3.9/site-packages/scipy/special/_orthogonal.py", line 81, in <module>
    from scipy import linalg
  File "/opt/conda/lib/python3.9/site-packages/scipy/__init__.py", line 211, in __getattr__
    return _importlib.import_module(f'scipy.{name}')
  File "/opt/conda/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.9/site-packages/scipy/linalg/__init__.py", line 209, in <module>
    from ._matfuncs import *
  File "/opt/conda/lib/python3.9/site-packages/scipy/linalg/_matfuncs.py", line 19, in <module>
    from ._matfuncs_sqrtm import sqrtm
  File "/opt/conda/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm.py", line 24, in <module>
    from ._matfuncs_sqrtm_triu import within_block_loop
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /opt/conda/lib/python3.9/site-packages/scipy/linalg/_matfuncs_sqrtm_triu.cpython-39-x86_64-linux-gnu.so)
```
Run `apt-get install --only-upgrade libstdc++6`
Output :
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
libstdc++6 is already the newest version (8.4.0-1ubuntu1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```
How can I Fix it

**Comment by Cupcc** [comment]
I've resolved it.

# Solution
This indicates that the simple solution is to append the path to the conda file to the LD_LIBRARY_PATH.
`export LD_LIBRARY_PATH=/path-to-your-conda/envs/your-env-name/lib:$LD_LIBRARY_PATH`
# reference link:
https://stackoverflow.com/questions/72540359/glibcxx-3-4-30-not-found-for-librosa-in-conda-virtual-environment-after-tryin
